Repository Qiskit/qiskit, pull requests merged in 2018-12, with the labels that each got.

#1359 Standardize visualization signatures and styling.
  CHANGELOG.rst
  qiskit/tools/visualization/__init__.py
  qiskit/tools/visualization/_counts_visualization.py
  qiskit/tools/visualization/_state_visualization.py
  qiskit/tools/visualization/_utils.py
  qiskit/tools/visualization/interactive/__init__.py
  qiskit/tools/visualization/interactive/_iplot_blochsphere.py
  qiskit/tools/visualization/interactive/_iplot_cities.py
  qiskit/tools/visualization/interactive/_iplot_hinton.py
  qiskit/tools/visualization/interactive/_iplot_histogram.py
  qiskit/tools/visualization/interactive/_iplot_paulivec.py
  qiskit/tools/visualization/interactive/_iplot_qsphere.py
  qiskit/tools/visualization/interactive/_iplot_state.py
Labels: type: enhancement

#1416 Fix small legend bug in plot_histogram
  qiskit/tools/visualization/_counts_visualization.py
Labels: type: bug

#1427 Use integers in properties.gates.qubits
  qiskit/backends/models/backendproperties.py
  qiskit/schemas/backend_properties_schema.json
Labels: specs

#1231 Backend monitor and overview
  CHANGELOG.rst
  qiskit/backends/aer/qasm_simulator_cpp
  qiskit/tools/__init__.py
  qiskit/tools/jupyter/__init__.py
  qiskit/tools/jupyter/backend_monitor.py
  qiskit/tools/jupyter/backend_overview.py
  qiskit/tools/jupyter/jupyter_magics.py
  qiskit/tools/monitor/__init__.py
  qiskit/tools/monitor/backend_overview.py
  qiskit/tools/monitor/job_monitor.py
  qiskit/tools/visualization/__init__.py
  qiskit/tools/visualization/_gate_map.py
  qiskit/transpiler/progressbar.py
  test/python/notebooks/test_backend_tools.ipynb
  test/python/notebooks/test_pbar_status.ipynb
  test/python/tools/jupyter/test_notebooks.py
  test/python/tools/monitor/test_backend_monitor.py
  test/python/tools/monitor/test_job_monitor.py
Labels: type: enhancement

#1526 Fix name conflict between text and Jupyter backend tools
  qiskit/tools/jupyter/__init__.py
  qiskit/tools/jupyter/_backend_monitor.py
  qiskit/tools/jupyter/_backend_overview.py
Labels: type: bug

#1581 ENH: Adaptive job status check interval
  qiskit/tools/jupyter/jupyter_magics.py
  qiskit/tools/monitor/job_monitor.py
Labels: type: enhancement
