Repository Qiskit/qiskit, pull requests merged in 2018-10, with the labels that each got.

#1091 Better handling of Bloch sphere output
  qiskit/tools/visualization/_bloch.py
  qiskit/tools/visualization/_state_visualization.py
Labels: type: enhancement

#1097 Fix slow compiling in parallel mode
  qiskit/transpiler/_transpiler.py
Labels: type: bug

#1115 Add support for reversebits and plotbarriers for text drawer
  qiskit/tools/visualization/_circuit_visualization.py
  qiskit/tools/visualization/_text.py
  test/python/test_circuit_text_drawer.py
Labels: priority: medium
