Repository Qiskit/qiskit, pull requests merged in 2018-09, with the labels that each got.

#734 Jupyter job status magic
  CHANGELOG.rst
  qiskit/wrapper/jupyter/__init__.py
  qiskit/wrapper/jupyter/jupyter_magics.py
Labels: type: enhancement

#887 Fix main __init__ py instruction order
  qiskit/__init__.py
Labels: type: bug

#867 0.6 release notes
  CHANGELOG.rst
  Makefile
  cmake/code-qa.cmake
  doc/dev_introduction.rst
  doc/install.rst
  doc/ja/index.rst
  doc/releases.rst
  qiskit/backends/ibmq/ibmqjob.py
  qiskit/backends/local/localjob.py
  qiskit/qobj/_result.py
  qiskit/result/_utils.py
Labels: type: documentation

#701 Parallel tools and compiling
  CHANGELOG.rst
  qiskit/__init__.py
  qiskit/_util.py
  qiskit/transpiler/__init__.py
  qiskit/transpiler/_parallel.py
  qiskit/transpiler/_progressbar.py
  qiskit/transpiler/_receiver.py
  qiskit/transpiler/_transpiler.py
  qiskit/wrapper/_wrapper.py
  qiskit/wrapper/jupyter/__init__.py
  qiskit/wrapper/jupyter/jupyter_magics.py
  qiskit/wrapper/jupyter/progressbar.py
  requirements.txt
  test/python/current_matplot.png
  test/python/test_compiler.py
  test/python/test_parallel.py
Labels: type: enhancement

#942 Fix number to keep in plot_histogram
  qiskit/tools/visualization/_counts_visualization.py
Labels: type: bug

#945 Fix reversed width and height options in plot_histogram
  qiskit/tools/visualization/_counts_visualization.py
Labels: type: bug

#974 Immediately set job magic status value
  qiskit/wrapper/jupyter/jupyter_magics.py
Labels: type: bug
