Repository Qiskit/qiskit, pull requests merged in 2018-11, with the labels that each got.

#1154 Test Jupyter functionality.
  appveyor.yml
  requirements-dev.txt
  test/python/notebooks/test_jupyter.ipynb
  test/python/test_notebooks.py
Labels: type: enhancement

#1181 Text draw object with _repr_html_
  qiskit/tools/visualization/_circuit_visualization.py
  qiskit/tools/visualization/_text.py
  test/python/test_circuit_text_drawer.py
  test/python/test_visualization_output.py
Labels: status: on hold

#1248 Fix links to languages in sphinx docs
  doc/_templates/layout.html
Labels: priority: low

#1187 Visualization utility to get the operations directly from a DAG
  qiskit/dagcircuit/_dagcircuit.py
  qiskit/tools/visualization/_utils.py
  test/python/test_dagcircuit.py
  test/python/test_visualization.py
Labels: priority: medium

#1297 Korean translation for Terra README.md
  doc/ko/README.md
Labels: status: needs information

#1311 Fully deprecate `BaseProvider.available backends()`
  CHANGELOG.rst
  qiskit/backends/baseprovider.py
  test/python/_mockutils.py
Labels: specs

#1305 Remove .parameters() and .calibration() (now .properties())
  CHANGELOG.rst
  qiskit/backends/basebackend.py
  qiskit/backends/ibmq/api/ibmqconnector.py
  qiskit/backends/ibmq/ibmqbackend.py
  test/python/ibmq/test_ibmq_connector.py
  test/python/test_backends.py
Labels: specs

#1327 Updated schemas to fix n_qubits and results statevector and unitary l…
  qiskit/schemas/backend_configuration_schema.json
  qiskit/schemas/examples/backend_configuration_openqasm_simulator_example.json
  qiskit/schemas/examples/result_openpulse_level_0_example.json
  qiskit/schemas/examples/result_statevector_simulator_example.json
  qiskit/schemas/examples/result_unitary_simulator_example.json
  qiskit/schemas/result_schema.json
  test/python/test_backends.py
  test/python/test_schemas.py
Labels: specs

#1369 Set n_qubits for Aer simulators to max supported by local memory.
  qiskit/backends/aer/qasm_simulator.py
  qiskit/backends/aer/qasm_simulator_py.py
  qiskit/backends/aer/statevector_simulator.py
  qiskit/backends/aer/statevector_simulator_py.py
  qiskit/backends/aer/unitary_simulator_py.py
  test/python/test_backends.py
Labels: type: enhancement

#1388 Update configuration.n_qubits model, disallow -1
  qiskit/backends/models/backendconfiguration.py
Labels: specs

#1394 Fix parallel_map publishing for an input of len=1
  CHANGELOG.rst
  qiskit/transpiler/_parallel.py
  test/python/notebooks/test_pbar_status.ipynb
Labels: type: bug
