Repository Qiskit/qiskit, pull requests merged in 2018-05, with the labels that each got.

#446 Documentation tweaks and release notes for 0.5
  README.md
  doc/_templates/better-apidoc/package.rst
  doc/example_real_backend.rst
  doc/index.rst
  doc/install.rst
  doc/ja/example_real_backend.rst
  doc/quickstart.rst
  doc/releases.rst
  qiskit/_quantumprogram.py
  qiskit/backends/local/statevector_simulator_sympy.py
  qiskit/backends/local/unitary_simulator_sympy.py
  requirements.txt
Labels: documentation

#465 Bug/async test
  qiskit/_compiler.py
  qiskit/backends/ibmq/ibmqjob.py
  test/python/common.py
  test/python/test_api_ibmq.py
  test/python/test_backends.py
  test/python/test_compiler.py
  test/python/test_ibmqjob.py
  test/python/test_localjob.py
  test/python/test_quantumprogram.py
  test/python/test_reordering.py
  test/python/test_simulator_interfaces.py
Labels: type: bug

#510 Replace "QI Software Kit" with "QI Science Kit"
  README.md
  doc/conf.py
  doc/index.rst
  doc/ja/index.rst
  doc/ko/README.md
  doc/zh/README.md
  src/qasm-simulator-cpp/README.md
Labels: type: documentation
