Repository Qiskit/qiskit, pull requests merged in 2018-08, with the labels that each got.

#698 Fix error in tensor_index.hpp for 3+ qubit operations
  CHANGELOG.rst
  src/qasm-simulator-cpp/src/Makefile
  src/qasm-simulator-cpp/src/utilities/qubit_vector.hpp
  src/qasm-simulator-cpp/src/utilities/tensor_index.hpp
Labels: priority: high

#740 Update to new Q network url format
  CHANGELOG.rst
  README.md
  doc/install.rst
  qiskit/_util.py
  qiskit/backends/ibmq/ibmqprovider.py
  qiskit/wrapper/_wrapper.py
  qiskit/wrapper/credentials/__init__.py
  test/python/common.py
  test/python/test_backend_name_resolution.py
  test/python/test_backends.py
  test/python/test_compiler.py
  test/python/test_filter_backends.py
  test/python/test_ibmqjob.py
  test/python/test_quantumprogram.py
  test/python/test_registration.py
  test/python/test_reordering.py
  test/python/test_simulator_interfaces.py
  test/python/test_wrapper.py
Labels: type: enhancement

#694 Add tests for Qobj
  test/python/test_qobj.py
Labels: type: qa

#790 Remove the test `test_simulator_online_size`
  test/python/test_quantumprogram.py
Labels: type: qa

#697 Save network interactions to allow tests to run offline
  .github/CONTRIBUTING.rst
  Makefile
  doc/de/dev_introduction.rst
  doc/dev_introduction.rst
  requirements-dev.txt
  requirements.txt
  test/cassettes/test_aliases
  test/cassettes/test_available_backends_exist
  test/cassettes/test_backends_with_filter
  test/cassettes/test_compile_remote
  test/cassettes/test_compile_run_remote
  test/cassettes/test_compile_two_remote
  test/cassettes/test_compile_two_run_remote
  test/cassettes/test_deprecated
  test/cassettes/test_double_submit_fails
  test/cassettes/test_execute_one_circuit_real_online
  test/cassettes/test_execute_one_circuit_simulator_online
  test/cassettes/test_execute_remote
  test/cassettes/test_execute_several_circuits_simulator_online
  test/cassettes/test_execute_two_remote
  test/cassettes/test_filter_config_callable
  test/cassettes/test_filter_config_dict
  test/cassettes/test_filter_least_busy
  test/cassettes/test_filter_status_config_dict
  test/cassettes/test_get_backend_calibration
  test/cassettes/test_get_backend_configuration_online
  test/cassettes/test_get_backend_name
  test/cassettes/test_get_backend_parameters
  test/cassettes/test_get_jobs_filter_counts
  test/cassettes/test_get_jobs_filter_date
  test/cassettes/test_get_jobs_filter_job_status
  test/cassettes/test_get_jobs_from_backend
  test/cassettes/test_hpc_parameter_is_correct
  test/cassettes/test_hpc_parameter_is_incorrect
  test/cassettes/test_job_id
  test/cassettes/test_online_backends_exist
  test/cassettes/test_online_devices
  test/cassettes/test_online_qasm_simulator_two_registers
  test/cassettes/test_online_simulators
  test/cassettes/test_qasm
  test/cassettes/test_qasm_reset_measure
  test/cassettes/test_register_twice
  test/cassettes/test_remote_backend_calibration
  test/cassettes/test_remote_backend_configuration
  test/cassettes/test_remote_backend_parameters
  test/cassettes/test_remote_backends_exist
  test/cassettes/test_remote_backends_exist_real_device
  test/cassettes/test_remote_backends_exist_simulator
  test/cassettes/test_retrieve_job
  test/cassettes/test_retrieve_job_error
  test/cassettes/test_run_simulator
  test/cassettes/test_setup_api
  test/cassettes/test_unregister
  test/cassettes/test_unregister_non_existent
  test/cassettes/test_wrapper_register_ok
  test/python/_test_options.py
  test/python/common.py
  test/python/http_recorder.py
  test/python/test_compiler.py
  test/python/test_ibmqjob.py
Labels: type: enhancement, type: qa

#738 Fixed string formatting issue when `CouplingError` is raised
  qiskit/mapper/_coupling.py
  test/python/test_coupling.py
Labels: priority: low, type: bug
