Repository Qiskit/qiskit, pull requests merged in 2018-06, with the labels that each got.

#565 Fix: Gate._qubit_coupling
  qiskit/_compiler.py
  qiskit/_gate.py
  test/python/test_compiler.py
Labels: priority: critical

#562 fix skip_transpiler: do not remove gates
  CHANGELOG.rst
  qiskit/_compiler.py
Labels: priority: critical

#501 get jobs from IBM Q backend
  qiskit/_result.py
  qiskit/backends/__init__.py
  qiskit/backends/basejob.py
  qiskit/backends/ibmq/ibmqbackend.py
  qiskit/backends/ibmq/ibmqjob.py
  qiskit/backends/jobstatus.py
  qiskit/backends/local/localjob.py
  qiskit/backends/local/qasm_simulator_cpp.py
  qiskit/backends/local/qasm_simulator_py.py
  qiskit/backends/local/statevector_simulator_py.py
  qiskit/backends/local/unitary_simulator_py.py
  qiskit/tools/file_io.py
  test/python/_dummybackend.py
  test/python/test_backends.py
  test/python/test_compiler.py
  test/python/test_ibmqjob.py
  test/python/test_quantumprogram.py
  test/python/test_reordering.py
Labels: priority: high

#573 Fix initializer gate inversion
  CHANGELOG.rst
  qiskit/extensions/quantum_initializer/_initializer.py
Labels: priority: low, type: bug

#563 Replace QuantumJob with qobj dictionary
  examples/python/using_qiskit_core_level_1.py
  qiskit/_quantumprogram.py
  qiskit/backends/basebackend.py
  qiskit/backends/ibmq/ibmqbackend.py
  qiskit/backends/ibmq/ibmqjob.py
  qiskit/backends/local/localjob.py
  qiskit/backends/local/qasm_simulator_cpp.py
  qiskit/backends/local/qasm_simulator_py.py
  qiskit/backends/local/statevector_simulator_cpp.py
  qiskit/backends/local/statevector_simulator_py.py
  qiskit/backends/local/unitary_simulator_py.py
  qiskit/wrapper/_wrapper.py
  test/python/_dummybackend.py
  test/python/test_compiler.py
  test/python/test_ibmqjob.py
  test/python/test_localjob.py
  test/python/test_qasm_simulator_cpp.py
  test/python/test_qasm_simulator_py.py
  test/python/test_reordering.py
  test/python/test_unitary_simulator_py.py
Labels: priority: high

#515 Adding test suite for testing IBMQJob in isolation.
  qiskit/backends/ibmq/ibmqjob.py
  test/python/_mockutils.py
  test/python/test_ibmqjob_states.py
  test/python/test_quantumprogram.py
Labels: priority: high

#584 Add unregister() via DefaultQISKitProvider changes
  CHANGELOG.rst
  qiskit/__init__.py
  qiskit/_quantumprogram.py
  qiskit/wrapper/__init__.py
  qiskit/wrapper/_wrapper.py
  qiskit/wrapper/defaultqiskitprovider.py
  test/python/common.py
  test/python/test_backends.py
  test/python/test_quantumprogram.py
  test/python/test_wrapper.py
Labels: priority: high
