Repository Qiskit/qiskit, pull requests merged in 2019-05, with the labels that each got.

#2226 Rework los and lo_ranges for channels
  qiskit/assembler/assemble_schedules.py
  qiskit/compiler/assemble.py
  qiskit/pulse/__init__.py
  qiskit/pulse/channels/channels.py
  qiskit/pulse/channels/device_specification.py
  qiskit/pulse/channels/pulse_channels.py
  qiskit/pulse/channels/qubit.py
  qiskit/pulse/configuration.py
  qiskit/qobj/converters/lo_config.py
  test/python/compiler/test_assembler.py
  test/python/pulse/test_channels.py
  test/python/pulse/test_experiment_configurations.py
  test/python/pulse/test_schedule.py
  test/python/qobj/test_pulse_converter.py
Labels: API

#2263 Pulse command definition
  qiskit/assembler/assemble_schedules.py
  qiskit/providers/models/__init__.py
  qiskit/providers/models/pulsedefaults.py
  qiskit/pulse/__init__.py
  qiskit/pulse/cmd_def.py
  qiskit/pulse/commands/sample_pulse.py
  qiskit/pulse/pulse_lib/continuous.py
  qiskit/pulse/schedule.py
  qiskit/qobj/__init__.py
  qiskit/qobj/converters/__init__.py
  qiskit/qobj/converters/pulse_instruction.py
  qiskit/qobj/models/pulse.py
  qiskit/schemas/qobj_schema.json
  qiskit/test/mock.py
  test/python/pulse/test_cmd_def.py
  test/python/qobj/test_pulse_converter.py
  test/python/qobj/test_qobj.py
Labels: API

#2265 Move schedule children attribute to private
  qiskit/pulse/commands/instruction.py
  qiskit/pulse/interfaces.py
  qiskit/pulse/schedule.py
  test/python/pulse/test_schedule.py
Labels: API

#2213 Openpulse drawer
  qiskit/pulse/__init__.py
  qiskit/pulse/channels/channels.py
  qiskit/pulse/commands/__init__.py
  qiskit/pulse/commands/acquire.py
  qiskit/pulse/commands/instruction.py
  qiskit/pulse/commands/sample_pulse.py
  qiskit/pulse/schedule.py
  qiskit/visualization/interpolation.py
  qiskit/visualization/matplotlib.py
  qiskit/visualization/pulse_visualization.py
  qiskit/visualization/qcstyle.py
  test/python/visualization/references/circuit_latex_ref.png
  test/python/visualization/references/circuit_matplotlib_ref.png
  test/python/visualization/references/circuit_text_ref.txt
  test/python/visualization/references/instruction_matplotlib_ref.png
  test/python/visualization/references/pulse_matplotlib_ref.png
  test/python/visualization/references/schedule_matplotlib_ref.png
  test/python/visualization/test_circuit_visualization_output.py
  test/python/visualization/test_pulse_visualization_output.py
  test/python/visualization/visualization.py
Labels: API

#2274 schedule assembly bug.
  qiskit/assembler/assemble_circuits.py
  qiskit/assembler/assemble_schedules.py
  test/python/compiler/test_assembler.py
Labels: API, bug

#2276 Enforce meas map at assembly
  qiskit/assembler/assemble_schedules.py
  qiskit/compiler/assemble.py
  qiskit/pulse/__init__.py
  qiskit/qobj/converters/pulse_instruction.py
  test/python/compiler/test_assembler.py
Labels: API, bug

#2225 Obtain a reduced coupling_map for a subgraph of a device
  qiskit/transpiler/coupling.py
  test/python/transpiler/test_coupling.py
Labels: enhancement

#2280 Remove buffer from first pulse on channel
  qiskit/pulse/ops.py
  test/python/pulse/test_schedule.py
Labels: bug

#2344 Make colored circuits the default for mpl drawer
  qiskit/user_config.py
  qiskit/visualization/latex.py
  qiskit/visualization/matplotlib.py
  qiskit/visualization/qcstyle.py
  test/python/test_user_config.py
Labels: enhancement

#2361 Preset passmanager should honor seed_transpiler
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
Labels: stable-backport-potential

#2370 fix 2339: run level 0 optimization level
  qiskit/transpiler/transpile_circuit.py
Labels: stable-backport-potential

#2367 Add missing optimization level to transpile() docstring
  qiskit/compiler/transpile.py
Labels: stable-backport-potential

#2376 Update expression math sanitization
  qiskit/qobj/converters/pulse_instruction.py
  test/python/qobj/test_pulse_converter.py
Labels: stable-backport-potential

#2351 Make assemble_schedule arguments non-optional
  qiskit/assembler/assemble_schedules.py
Labels: stable-backport-potential

#2416 make rep_times an integer and not a float
  qiskit/providers/models/backendconfiguration.py
  qiskit/test/mock.py
Labels: bug, stable backport potential

#2413 Framechange instruction as_dict bug
  qiskit/qobj/models/pulse.py
  test/python/qobj/test_qobj.py
Labels: bug, priority: high, stable backport potential

#2305 skip backend monitor tests if no internet connection
  test/python/tools/monitor/test_backend_monitor.py
Labels: enhancement

#2436 Add cython files to manifest to enable sdist compilation
  MANIFEST.in
Labels: stable backport potential

#2432 Add framechange phase casting to float.
  qiskit/pulse/commands/frame_change.py
  qiskit/qobj/models/pulse.py
  test/python/pulse/test_commands.py
  test/python/qobj/test_qobj.py
Labels: stable backport potential

#2431 Bug fix sample pulse name conflict in qobj assembly
  qiskit/assembler/assemble_schedules.py
  test/python/compiler/test_assembler.py
Labels: stable backport potential

#2463 remove layout modification from stochastic swap
  qiskit/transpiler/passes/mapping/stochastic_swap.py
  test/python/transpiler/test_stochastic_swap.py
Labels: stable backport potential

#2460 optimization_level=0 without coupling map
  qiskit/transpiler/preset_passmanagers/level0.py
  test/python/transpiler/test_preset_passmanagers.py
Labels: stable backport potential
