Repository Qiskit/qiskit, pull requests merged in 2019-04, with the labels that each got.

#2064 Allow for bit string distance measures (Hamming dist) in plot_histogram
  CHANGELOG.rst
  qiskit/tools/visualization/_counts_visualization.py
Labels: enhancement

#2085 Add meas_level to result schema
  CHANGELOG.rst
  qiskit/result/models.py
  qiskit/schemas/result_schema.json
Labels: type: specs

#2086 Optimize gates up to fixed point in the default pipeline
  qiskit/transpiler/transpiler.py
  test/python/compiler/test_compiler.py
Labels: pass manager

#1778 Conditionals must be updated to match schema
  qiskit/compiler/assembler.py
  qiskit/providers/basicaer/qasm_simulator.py
  qiskit/qobj/__init__.py
  qiskit/qobj/models/qasm.py
  qiskit/schemas/qobj_schema.json
  test/python/compiler/test_assembler.py
Labels: type: specs

#2101 Remove pulse defaults required parameters
  CHANGELOG.rst
  qiskit/providers/models/pulsedefaults.py
  qiskit/schemas/default_pulse_configuration_schema.json
Labels: type: specs

#1993 Update QuantumCircuit properties
  CHANGELOG.rst
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_circuit_properties.py
Labels: enhancement

#2106 get_memory for pulse measurement level 0 and 1
  qiskit/pulse/__init__.py
  qiskit/result/postprocess.py
  qiskit/result/result.py
  test/python/result/__init__.py
  test/python/result/test_result.py
Labels: enhancement

#2157 Layout is bijective dict only, transpile accomodates list and dict
  CHANGELOG.rst
  qiskit/execute.py
  qiskit/mapper/layout.py
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/mapping/enlarge_with_ancilla.py
  qiskit/transpiler/passes/mapping/extend_layout.py
  qiskit/transpiler/passes/mapping/full_ancilla_allocation.py
  qiskit/transpiler/preset_passmanagers/default.py
  qiskit/transpiler/transpiler.py
  test/python/pickles/TestsBasicSwap_a_cx_to_map.pickle
  test/python/pickles/TestsBasicSwap_handle_measurement.pickle
  test/python/pickles/TestsBasicSwap_initial_layout.pickle
  test/python/pickles/TestsLegacySwap_a_cx_to_map.pickle
  test/python/pickles/TestsLegacySwap_handle_measurement.pickle
  test/python/pickles/TestsLookaheadSwap_a_cx_to_map.pickle
  test/python/pickles/TestsLookaheadSwap_handle_measurement.pickle
  test/python/pickles/TestsLookaheadSwap_initial_layout.pickle
  test/python/pickles/TestsStochasticSwap_a_cx_to_map.pickle
  test/python/pickles/TestsStochasticSwap_handle_measurement.pickle
  test/python/pickles/TestsStochasticSwap_initial_layout.pickle
  test/python/test_layout.py
  test/python/transpiler/test_basic_swap.py
  test/python/transpiler/test_enlarge_with_ancilla_pass.py
  test/python/transpiler/test_extend_layout.py
  test/python/transpiler/test_full_ancilla_allocation.py
  test/python/transpiler/test_mappers.py
  test/python/transpiler/test_stochastic_swap.py
Labels: API

#2118 accept integers in gates and instructions
  CHANGELOG.rst
  qiskit/circuit/decorators.py
  qiskit/circuit/measure.py
  qiskit/circuit/quantumcircuit.py
  qiskit/extensions/quantum_initializer/initializer.py
  qiskit/extensions/standard/barrier.py
  qiskit/extensions/standard/ccx.py
  qiskit/extensions/standard/ch.py
  qiskit/extensions/standard/crz.py
  qiskit/extensions/standard/cswap.py
  qiskit/extensions/standard/cu1.py
  qiskit/extensions/standard/cu3.py
  qiskit/extensions/standard/cx.py
  qiskit/extensions/standard/cxbase.py
  qiskit/extensions/standard/cy.py
  qiskit/extensions/standard/cz.py
  qiskit/extensions/standard/h.py
  qiskit/extensions/standard/iden.py
  qiskit/extensions/standard/rx.py
  qiskit/extensions/standard/ry.py
  qiskit/extensions/standard/rz.py
  qiskit/extensions/standard/rzz.py
  qiskit/extensions/standard/s.py
  qiskit/extensions/standard/swap.py
  qiskit/extensions/standard/t.py
  qiskit/extensions/standard/u0.py
  qiskit/extensions/standard/u1.py
  qiskit/extensions/standard/u2.py
  qiskit/extensions/standard/u3.py
  qiskit/extensions/standard/ubase.py
  qiskit/extensions/standard/x.py
  qiskit/extensions/standard/y.py
  qiskit/extensions/standard/z.py
  test/python/circuit/test_circuit_registers.py
  test/python/circuit/test_extensions_standard.py
  test/python/circuit/test_registerless_circuit.py
Labels: API

#2185 Fix quantumcircuit.size for (instr,qargs,cargs) format of self.data.
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_circuit_properties.py
Labels: bug

#2166 interface to execute(), transpile() and assemble()
  CHANGELOG.rst
  qiskit/__init__.py
  qiskit/compiler/__init__.py
  qiskit/compiler/assembler.py
  qiskit/compiler/models.py
  qiskit/compiler/run_config.py
  qiskit/compiler/transpile_config.py
  qiskit/compiler/transpiler.py
  qiskit/converters/circuits_to_qobj.py
  qiskit/execute.py
  qiskit/tools/compiler.py
  qiskit/tools/parallel.py
  qiskit/transpiler/passes/unroller.py
  qiskit/transpiler/passmanager.py
  qiskit/transpiler/preset_passmanagers/default.py
  qiskit/transpiler/transpiler.py
  test/python/aer_provider_integration_test/test_aer_qobj_headers.py
  test/python/basicaer/test_basicaer_qobj_headers.py
  test/python/basicaer/test_qasm_simulator.py
  test/python/circuit/test_variable_parameters.py
  test/python/compiler/test_assembler.py
  test/python/compiler/test_compiler.py
  test/python/compiler/test_disassembler.py
  test/python/compiler/test_transpiler.py
  test/python/converters/test_qobj_to_circuits.py
  test/python/notebooks/test_pbar_status.ipynb
  test/python/qobj/test_qobj.py
  test/python/qobj/test_qobj_identifiers.py
  test/python/quantum_info/test_unitary.py
Labels: API

#2186 Issue 2114 immutable schedules
  CHANGELOG.rst
  qiskit/compiler/assembler.py
  qiskit/pulse/channels/qubit.py
  qiskit/pulse/commands/acquire.py
  qiskit/pulse/commands/frame_change.py
  qiskit/pulse/commands/instruction.py
  qiskit/pulse/commands/persistent_value.py
  qiskit/pulse/commands/pulse_command.py
  qiskit/pulse/commands/sample_pulse.py
  qiskit/pulse/commands/snapshot.py
  qiskit/pulse/common/__init__.py
  qiskit/pulse/common/interfaces.py
  qiskit/pulse/interfaces.py
  qiskit/pulse/ops.py
  qiskit/pulse/pulse_lib/discrete.py
  qiskit/pulse/schedule.py
  qiskit/pulse/schedule/__init__.py
  qiskit/pulse/schedule/pulse_schedule.py
  qiskit/pulse/timeslots.py
  qiskit/qobj/converters/pulse_instruction.py
  test/python/pulse/test_commands.py
  test/python/pulse/test_schedule.py
  test/python/pulse/test_timeslots.py
  test/python/qobj/test_pulse_converter.py
Labels: API

#2167 Fix Pulse naming issues
  qiskit/compiler/assembler.py
  qiskit/execute.py
  qiskit/providers/models/pulsedefaults.py
  qiskit/pulse/channels/__init__.py
  qiskit/pulse/channels/channels.py
  qiskit/pulse/channels/device_specification.py
  qiskit/pulse/channels/pulse_channels.py
  qiskit/pulse/channels/qubit.py
  qiskit/pulse/commands/__init__.py
  qiskit/pulse/commands/acquire.py
  qiskit/pulse/commands/command.py
  qiskit/pulse/commands/frame_change.py
  qiskit/pulse/commands/instruction.py
  qiskit/pulse/commands/persistent_value.py
  qiskit/pulse/commands/sample_pulse.py
  qiskit/pulse/commands/snapshot.py
  qiskit/pulse/configuration.py
  qiskit/qobj/converters/pulse_instruction.py
  test/python/qobj/test_pulse_converter.py
Labels: API

#2052 PulseQobj and Json Schema updates for pulse simulator
  qiskit/qobj/__init__.py
  qiskit/qobj/models/pulse.py
  qiskit/schemas/backend_configuration_schema.json
  qiskit/schemas/qobj_schema.json
  qiskit/validation/fields/__init__.py
  qiskit/validation/fields/containers.py
  qiskit/validation/fields/custom.py
  qiskit/validation/validate.py
  test/python/qobj/test_qobj.py
Labels: API, type: specs

#2241 Refactor enhance schedule
  qiskit/compiler/assembler.py
  qiskit/pulse/commands/instruction.py
  qiskit/pulse/interfaces.py
  qiskit/pulse/ops.py
  qiskit/pulse/schedule.py
  test/python/pulse/test_schedule.py
Labels: API

#2216 Pulse backend configuration
  qiskit/providers/basicaer/qasm_simulator.py
  qiskit/providers/basicaer/statevector_simulator.py
  qiskit/providers/basicaer/unitary_simulator.py
  qiskit/providers/models/__init__.py
  qiskit/providers/models/backendconfiguration.py
  qiskit/test/mock.py
  test/python/test_schemas.py
Labels: API
