Repository Qiskit/qiskit, pull requests merged in 2019-08, with the labels that each got.

#2889 Add style and lint check to azure pipelines.
  azure-pipelines.yml
Labels: type: qa

#2898 Add __init__ to test/randomized directory and fix missing import
  test/randomized/__init__.py
  test/randomized/test_transpiler_equivalence.py
Labels: type: qa

#2844 Plot circuit layout on backend coupling map
  qiskit/visualization/__init__.py
  qiskit/visualization/gate_map.py
Labels: enhancement

#2791 Jupyter version table and copyright
  qiskit/tools/jupyter/__init__.py
  qiskit/tools/jupyter/backend_monitor.py
  qiskit/tools/jupyter/copyright.py
  qiskit/tools/jupyter/version_table.py
  test/python/notebooks/test_backend_tools.ipynb
Labels: enhancement

#2926 Ordered count_ops
  CHANGELOG.md
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_circuit_properties.py
Labels: enhancement

#2505 MPL drawer to match IQX with IBM design colors
  qiskit/visualization/matplotlib.py
  qiskit/visualization/qcstyle.py
  test/python/visualization/references/circuit_matplotlib_ref.png
  test/python/visualization/references/current_no_barriers_matplotlib_ref.png
  test/python/visualization/references/matplotlib_barriers_ref.png
  test/python/visualization/references/matplotlib_long_name_ref.png
  test/python/visualization/test_circuit_matplotlib_drawer.py
Labels: enhancement

#2537 Add ParameterExpression class supporting basic Parameter math.
  CHANGELOG.md
  qiskit/circuit/__init__.py
  qiskit/circuit/instruction.py
  qiskit/circuit/parameter.py
  qiskit/circuit/parameterexpression.py
  qiskit/circuit/quantumcircuit.py
  qiskit/transpiler/passes/optimize_1q_gates.py
  qiskit/transpiler/passes/unroller.py
  qiskit/validation/fields/custom.py
  test/python/circuit/test_instructions.py
  test/python/circuit/test_parameters.py
  test/python/compiler/test_assembler.py
  test/python/compiler/test_transpiler.py
  test/python/converters/test_circuit_to_instruction.py
  test/python/transpiler/test_optimize_1q_gates.py
  test/python/transpiler/test_unroller.py
  test/python/validation/test_custom_fields.py
Labels: enhancement

#2946 reduce space mpl circ takes, fix cH gate color, revert color scheme
  qiskit/visualization/matplotlib.py
  qiskit/visualization/qcstyle.py
Labels: enhancement

#2776 Tag benchmark failures in travis
  .travis.yml
  tools/report_ci_failure.py
Labels: type: qa

#2881 Moved samplers module into pulse.pulse_lib.samplers
  CHANGELOG.md
  qiskit/pulse/pulse_lib/discrete.py
  qiskit/pulse/pulse_lib/samplers/__init__.py
  qiskit/pulse/pulse_lib/samplers/decorators.py
  qiskit/pulse/pulse_lib/samplers/strategies.py
  test/python/pulse/test_samplers.py
Labels: enhancement

#2833 Add more informative errors missing qubit and measurement los
  CHANGELOG.md
  qiskit/assembler/assemble_schedules.py
  qiskit/compiler/assemble.py
  qiskit/qobj/converters/lo_config.py
  test/python/compiler/test_assembler.py
Labels: enhancement

#2986 faster job status checking in job watcher
  qiskit/tools/jupyter/watcher_monitor.py
Labels: enhancement

#2796 Clip pulse samples if within epsilon unit norm
  CHANGELOG.md
  qiskit/pulse/commands/sample_pulse.py
  test/python/pulse/test_commands.py
Labels: bug

#2869 Add delay instruction
  CHANGELOG.md
  qiskit/assembler/assemble_schedules.py
  qiskit/pulse/__init__.py
  qiskit/pulse/commands/__init__.py
  qiskit/pulse/commands/delay.py
  test/python/compiler/test_assembler.py
  test/python/pulse/test_commands.py
  test/python/pulse/test_schedule.py
  test/python/qobj/test_pulse_converter.py
  test/python/visualization/references/schedule_matplotlib_ref.png
  test/python/visualization/test_pulse_visualization_output.py
Labels: enhancement

#2965 Adds error_map plot
  qiskit/tools/jupyter/backend_monitor.py
  qiskit/visualization/__init__.py
  qiskit/visualization/gate_map.py
Labels: enhancement

#3013 Deepcopy all but first instruction when broadcasting.
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_extensions_standard.py
  test/python/circuit/test_parameters.py
Labels: bug

#3027 remove cx_direction from O3 if symmetric
  qiskit/transpiler/preset_passmanagers/level3.py
Labels: bug

#3037 Remove jsonschema cap
  requirements.txt
  setup.py
Labels: stable backport potential

#3041 Make graphviz availability check at runtime
  qiskit/visualization/pass_manager_visualization.py
  test/python/visualization/test_pass_manager_drawer.py
Labels: stable backport potential
