Repository Qiskit/qiskit, pull requests merged in 2019-03, with the labels that each got.

#1909 Move qobj implementation to models and schemas
  CHANGELOG.rst
  qiskit/converters/circuits_to_qobj.py
  qiskit/converters/qobj_to_circuits.py
  qiskit/qobj/__init__.py
  qiskit/qobj/_converter.py
  qiskit/qobj/models.py
  qiskit/qobj/qobj.py
  qiskit/qobj/run_config.py
  qiskit/qobj/utils.py
  qiskit/test/mock.py
  qiskit/validation/base.py
  test/python/aer_provider_integration_test/test_extensions_simulator.py
  test/python/aer_provider_integration_test/test_qasm_simulator.py
  test/python/converters/test_qobj_to_circuits.py
  test/python/qobj/test_qobj.py
Labels: type: specs

#1959 Fix qobj.experiment.instructions.parameters serialization
  qiskit/qobj/models.py
  qiskit/validation/fields/__init__.py
  qiskit/validation/fields/custom.py
  test/python/aer_provider_integration_test/test_extensions_simulator.py
  test/python/aer_provider_integration_test/test_qasm_simulator.py
Labels: type: specs

#1970 Extend InstructionParameter for containers
  qiskit/validation/fields/custom.py
  test/python/validation/test_custom_fields.py
Labels: type: specs

#1974 Support `None` for simulator backend coupling_map
  qiskit/providers/basicaer/qasm_simulator.py
  qiskit/providers/basicaer/statevector_simulator.py
  qiskit/providers/basicaer/unitary_simulator.py
  qiskit/providers/models/backendconfiguration.py
  qiskit/transpiler/transpiler.py
Labels: enhancement, type: specs

#1863 Make all random seed values accessible and log them.
  qiskit/mapper/mapping.py
  qiskit/quantum_info/states/_states.py
  qiskit/transpiler/passes/mapping/stochastic_swap.py
  test/python/tools/visualization/test_visualization.py
Labels: enhancement

#2008 Tests for dag.depth()
  qiskit/dagcircuit/dagcircuit.py
  test/python/test_dagcircuit.py
Labels: enhancement

#1992 Layout has repr
  qiskit/mapper/layout.py
  test/python/test_layout.py
Labels: enhancement
