Repository Qiskit/qiskit, pull requests merged in 2019-06, with the labels that each got.

#2560 Fix labeling of 2Q gate qubits on FakeBackends.
  qiskit/test/mock.py
Labels: type: qa

#2561 Upload wheels to pypi.org instead of test.pypi.org
  .travis.yml
  appveyor.yml
Labels: stable backport potential

#2544 Add randomized transpiler equivalence testing
  qiskit/test/base.py
  requirements-dev.txt
  test/randomized/test_transpiler_equivalence.py
Labels: type: discussion, type: qa

#2624 One more fix for backend monitor
  qiskit/tools/jupyter/backend_monitor.py
Labels: bug

#2630 More backend monitor updates
  qiskit/tools/jupyter/backend_monitor.py
Labels: stable backport potential

#2586 Handle AttributeError in create_from under device_specification.py
  qiskit/pulse/channels/device_specification.py
Labels: enhancement

#2626 Ensure is_mergeable_with does not mutate TimeslotCollection
  qiskit/pulse/timeslots.py
  test/python/pulse/test_timeslots.py
Labels: stable backport potential

#2636 Update backend overview
  qiskit/tools/jupyter/backend_overview.py
Labels: enhancement

#2634 Backend monitor as backend HTML repr in Jupyter
  qiskit/tools/jupyter/__init__.py
  qiskit/tools/jupyter/backend_monitor.py
Labels: enhancement

#2632 Fix cmd line backend monitor
  qiskit/tools/monitor/backend_overview.py
Labels: bug, stable backport potential

#2493 Expression parser for parameters
  qiskit/pulse/__init__.py
  qiskit/pulse/parser.py
  qiskit/qobj/converters/pulse_instruction.py
  test/python/pulse/test_parser.py
  test/python/qobj/test_pulse_converter.py
Labels: enhancement

#2620 Add randomized testing stage to travis
  .travis.yml
  Makefile
  tools/report_ci_failure.py
Labels: type: qa

#2642 checking parameters in CmdDef
  qiskit/pulse/schedule.py
  test/python/pulse/test_cmd_def.py
Labels: bug

#2663 never remove id gates
  CHANGELOG.md
  qiskit/extensions/standard/iden.py
  qiskit/transpiler/passes/optimize_1q_gates.py
  test/python/circuit/test_diag.py
  test/python/circuit/test_isometry.py
  test/python/circuit/test_squ.py
  test/python/circuit/test_ucg.py
  test/python/circuit/test_ucx_y_z.py
  test/python/transpiler/test_optimize_1q_gates.py
  test/python/transpiler/test_unroller.py
Labels: stable backport potential

#2633 Run benchmarks in CI, resolve hypothesis errors
  .travis.yml
  test/randomized/test_transpiler_equivalence.py
Labels: type: qa

#2653 Automated job tracking in Jupyter notebooks
  qiskit/tools/jupyter/__init__.py
  qiskit/tools/jupyter/job_watcher.py
  qiskit/tools/jupyter/job_widgets.py
  qiskit/tools/jupyter/watcher_monitor.py
  qiskit/tools/monitor/job_monitor.py
  test/python/notebooks/test_pbar_status.ipynb
Labels: enhancement

#2539 KAK decomposition triggered only if basis gate count in a block is not equal to that of KAK
  qiskit/quantum_info/synthesis/local_invariance.py
  qiskit/quantum_info/synthesis/two_qubit_decompose.py
  qiskit/quantum_info/synthesis/weyl.py
  qiskit/transpiler/passes/consolidate_blocks.py
  test/python/quantum_info/test_local_invariance.py
  test/python/quantum_info/test_synthesis.py
  test/python/quantum_info/test_weyl.py
  test/python/transpiler/test_consolidate_blocks.py
  test/python/transpiler/test_kak_over_optimization.py
Labels: enhancement

#2694 Allow command names to start with a capital letter
  CHANGELOG.md
  qiskit/pulse/commands/command.py
Labels: bug

#2685 Ops merge refactor tangential to #2678
  qiskit/pulse/commands/instruction.py
  qiskit/pulse/ops.py
  qiskit/pulse/schedule.py
Labels: enhancement

#2697 First rep time by default
  CHANGELOG.md
  qiskit/compiler/assemble.py
Labels: stable backport potential

#2705 Fix NumPy dot array alignment in KAK
  qiskit/quantum_info/synthesis/two_qubit_decompose.py
Labels: bug

#2672 Remove LegacySwap, Remove default_pass_manager, Fix layout issues
  CHANGELOG.md
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/mapping/check_cx_direction.py
  qiskit/transpiler/passes/mapping/check_map.py
  qiskit/transpiler/passes/mapping/cx_direction.py
  qiskit/transpiler/passes/mapping/legacy_swap.py
  qiskit/transpiler/preset_passmanagers/__init__.py
  qiskit/transpiler/preset_passmanagers/default.py
  qiskit/transpiler/preset_passmanagers/level0.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  qiskit/transpiler/transpile_circuit.py
  test/python/compiler/test_compiler.py
  test/python/compiler/test_transpiler.py
  test/python/transpiler/test_cx_direction.py
  test/python/transpiler/test_mappers.py
  test/python/transpiler/test_preset_passmanagers.py
Labels: stable backport potential
