Repository Qiskit/qiskit, pull requests merged in 2019-11, with the labels that each got.

#3363 FullAncillaAllocation and EnlargeWithAncilla do not allow initial_layout at construction time
  qiskit/transpiler/passes/mapping/enlarge_with_ancilla.py
  qiskit/transpiler/passes/mapping/full_ancilla_allocation.py
  test/python/transpiler/test_enlarge_with_ancilla_pass.py
  test/python/visualization/references/pass_manager_standard.dot
  test/python/visualization/references/pass_manager_style.dot
  test/python/visualization/test_pass_manager_drawer.py
Labels: automerge

#3365 no more random in test_visualization
  test/python/visualization/test_visualization.py
Labels: automerge

#3258 Add class's __init__() docstring too
  docs/conf.py
Labels: automerge

#3321 Add layout score analysis pass
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/mapping/layout_2q_distance.py
  releasenotes/notes/Layout2qDistance-84fccae5eb89699c.yaml
  test/python/transpiler/test_layout_score.py
Labels: Changelog: New Feature, automerge

#3179 graphviz installation instructions
  qiskit/visualization/dag_visualization.py
Labels: automerge

#3381 Fake Johannesburg device (20 qubit)
  qiskit/test/mock/fake_johannesburg.py
Labels: automerge

#3361 pulse Schedule not filter
  qiskit/pulse/schedule.py
  test/python/pulse/test_schedule.py
Labels: automerge

#3376 Fixes bug in concurrence using ``eigh`` instead of ``eigvals`` for possibly non-hermitian matrices
  qiskit/tools/qi/qi.py
  test/python/test_qi.py
Labels: Changelog: Bugfix, automerge

#3396 small apidocs fixes
  qiskit/assembler/disassemble.py
  qiskit/circuit/quantumcircuit.py
  qiskit/extensions/quantum_initializer/diag.py
  qiskit/extensions/standard/ccx.py
  qiskit/extensions/standard/cxbase.py
Labels: automerge

#3388 Change benchmarks run in CI job
  .travis.yml
Labels: automerge

#3389 Add overview of doc structure and process to contributing guide
  CONTRIBUTING.md
Labels: automerge

#3418 Fix Schedule Plot reflecting duration of final schedule even if it is not plotted
  qiskit/visualization/pulse/matplotlib.py
Labels: Changelog: Bugfix, automerge

#3439 a less noisy test_deprecated
  test/python/basicaer/test_basicaer_backends.py
Labels: automerge

#3421 Set the scale parameter of QuantumCircuit.draw to a default of 1
  qiskit/circuit/quantumcircuit.py
Labels: automerge

#3280 Rewrite dag drawer to not use nxpd
  constraints.txt
  qiskit/visualization/dag_visualization.py
  requirements-dev.txt
  requirements.txt
  setup.py
  test/python/visualization/test_dag_drawer.py
Labels: automerge

#3448 Remove warning about units of dt
  qiskit/providers/models/backendconfiguration.py
  test/python/providers/test_backendconfiguration.py
Labels: automerge

#3367 Deprecate backend config replacement
  qiskit/pulse/channels/__init__.py
  qiskit/pulse/channels/pulse_channel_spec.py
  qiskit/pulse/channels/qubit.py
  qiskit/pulse/channels/system_topology.py
  qiskit/pulse/commands/acquire.py
  releasenotes/notes/deprecate-pulse-channel-spec-c33de7335eaa1a4f.yaml
  test/python/compiler/test_assembler.py
  test/python/pulse/test_channels.py
  test/python/pulse/test_cmd_def.py
  test/python/pulse/test_reschedule.py
  test/python/pulse/test_schedule.py
  test/python/pulse/test_system_topology.py
  test/python/qobj/test_pulse_converter.py
  test/python/visualization/test_pulse_visualization_output.py
Labels: automerge

#3452 Create codeowners for scheduler
  .github/CODEOWNERS
Labels: automerge

#3342 Add from_label to Operator class
  qiskit/quantum_info/operators/operator.py
Labels: automerge

#2862 add ControlledGate class
  .pylintrc
  qiskit/circuit/__init__.py
  qiskit/circuit/add_control.py
  qiskit/circuit/controlledgate.py
  qiskit/circuit/gate.py
  qiskit/circuit/instruction.py
  qiskit/converters/__init__.py
  qiskit/converters/instruction_to_gate.py
  qiskit/extensions/standard/__init__.py
  qiskit/extensions/standard/ccx.py
  qiskit/extensions/standard/ch.py
  qiskit/extensions/standard/crz.py
  qiskit/extensions/standard/cswap.py
  qiskit/extensions/standard/cu1.py
  qiskit/extensions/standard/cu3.py
  qiskit/extensions/standard/cx.py
  qiskit/extensions/standard/cxbase.py
  qiskit/extensions/standard/cy.py
  qiskit/extensions/standard/cz.py
  qiskit/extensions/standard/multi_control_rotation_gates.py
  qiskit/extensions/standard/multi_control_toffoli_gate.py
  qiskit/extensions/standard/multi_control_u1_gate.py
  qiskit/extensions/standard/relative_phase_toffoli.py
  qiskit/extensions/standard/swap.py
  qiskit/extensions/standard/x.py
  qiskit/extensions/standard/y.py
  qiskit/test/utils.py
  test/python/circuit/test_controlled_gate.py
  test/python/converters/test_instruction_to_gate.py
  test/python/pickles/TestsBasicSwap_a_cx_to_map.pickle
  test/python/pickles/TestsBasicSwap_handle_measurement.pickle
  test/python/pickles/TestsBasicSwap_initial_layout.pickle
  test/python/pickles/TestsLookaheadSwap_a_cx_to_map.pickle
  test/python/pickles/TestsLookaheadSwap_handle_measurement.pickle
  test/python/pickles/TestsLookaheadSwap_initial_layout.pickle
  test/python/pickles/TestsStochasticSwap_a_cx_to_map.pickle
  test/python/pickles/TestsStochasticSwap_handle_measurement.pickle
  test/python/pickles/TestsStochasticSwap_initial_layout.pickle
Labels: automerge

#3438 Add mock function for qiskit.IBMQ
  qiskit/execute.py
  qiskit/test/ibmq_mock.py
  qiskit/visualization/gate_map.py
Labels: automerge

#3442 controlled gate text drawer
  qiskit/visualization/text.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: automerge

#3445 restructure mock backends and fix packaging of backend data
  MANIFEST.in
  qiskit/test/mock/__init__.py
  qiskit/test/mock/backends/__init__.py
  qiskit/test/mock/backends/almaden/__init__.py
  qiskit/test/mock/backends/almaden/fake_almaden.py
  qiskit/test/mock/backends/almaden/props_almaden.json
  qiskit/test/mock/backends/boeblingen/__init__.py
  qiskit/test/mock/backends/boeblingen/fake_boeblingen.py
  qiskit/test/mock/backends/boeblingen/props_boeblingen.json
  qiskit/test/mock/backends/burlington/__init__.py
  qiskit/test/mock/backends/burlington/conf_burlington.json
  qiskit/test/mock/backends/burlington/defs_burlington.json
  qiskit/test/mock/backends/burlington/fake_burlington.py
  qiskit/test/mock/backends/burlington/props_burlington.json
  qiskit/test/mock/backends/johannesburg/__init__.py
  qiskit/test/mock/backends/johannesburg/fake_johannesburg.py
  qiskit/test/mock/backends/johannesburg/props_johannesburg.json
  qiskit/test/mock/backends/melbourne/__init__.py
  qiskit/test/mock/backends/melbourne/fake_melbourne.py
  qiskit/test/mock/backends/melbourne/props_melbourne.json
  qiskit/test/mock/backends/ourense/__init__.py
  qiskit/test/mock/backends/ourense/fake_ourense.py
  qiskit/test/mock/backends/ourense/props_ourense.json
  qiskit/test/mock/backends/poughkeepsie/__init__.py
  qiskit/test/mock/backends/poughkeepsie/fake_poughkeepsie.py
  qiskit/test/mock/backends/poughkeepsie/props_poughkeepsie.json
  qiskit/test/mock/backends/rueschlikon/__init__.py
  qiskit/test/mock/backends/rueschlikon/fake_rueschlikon.py
  qiskit/test/mock/backends/singapore/__init__.py
  qiskit/test/mock/backends/singapore/fake_singapore.py
  qiskit/test/mock/backends/singapore/props_singapore.json
  qiskit/test/mock/backends/tenerife/__init__.py
  qiskit/test/mock/backends/tenerife/fake_tenerife.py
  qiskit/test/mock/backends/tenerife/props_tenerife.json
  qiskit/test/mock/backends/tokyo/__init__.py
  qiskit/test/mock/backends/tokyo/fake_tokyo.py
  qiskit/test/mock/backends/tokyo/props_tokyo.json
  qiskit/test/mock/backends/vigo/__init__.py
  qiskit/test/mock/backends/vigo/fake_vigo.py
  qiskit/test/mock/backends/vigo/props_vigo.json
  qiskit/test/mock/backends/yorktown/__init__.py
  qiskit/test/mock/backends/yorktown/fake_yorktown.py
  qiskit/test/mock/backends/yorktown/props_yorktown.json
  qiskit/test/mock/fake_provider.py
Labels: automerge

#3043 CSP layout selector
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/mapping/csp_layout.py
  releasenotes/notes/csplayout-fb9deb7fc133acfd.yaml
  test/python/transpiler/test_csp_layout.py
Labels: automerge

#3454 Params in controlled gates
  qiskit/circuit/add_control.py
  qiskit/visualization/text.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: automerge

#3316 Fixed execute documentation
  qiskit/execute.py
Labels: automerge

#3430 TestTextWithLayout is using line_length, which is deprecated
  test/python/visualization/test_circuit_text_drawer.py
Labels: automerge

#3394 Schedule: deprecate channels_to_plot parameter and use channels instead
  qiskit/pulse/commands/instruction.py
  qiskit/pulse/schedule.py
  qiskit/visualization/pulse/matplotlib.py
  qiskit/visualization/pulse_visualization.py
Labels: automerge

#3459 Update visualization picheck to handle parameters
  qiskit/visualization/tools/pi_check.py
Labels: automerge

#3273 Run BarrierBeforeFinalMeasurements pass regardless of property_set['is_swap_mapped']
  qiskit/transpiler/preset_passmanagers/level0.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: automerge

#3458 Deal with None as return from job.queue_position()
  qiskit/tools/jupyter/jupyter_magics.py
  qiskit/tools/monitor/job_monitor.py
  releasenotes/notes/job_queue_position_None-da3e6c2a203bc795.yaml
Labels: Changelog: Bugfix, automerge

#3411 Bugfix/issue 3387 adding late gates
  qiskit/scheduler/methods/basic.py
  test/python/scheduler/test_basic_scheduler.py
Labels: automerge

#3479 syncing qiskit/qasm/libs/qelib1.inc and qiskit/extensions/standard/cu3.py
  qiskit/extensions/standard/cu3.py
  qiskit/qasm/libs/qelib1.inc
  test/python/test_qasm_parser.py
Labels: automerge

#3318 Remove deprecation message for TranspilerAccessError
  qiskit/transpiler/exceptions.py
Labels: automerge

#3474 Use \frac for fractions of pi with latex drawer
  qiskit/visualization/tools/pi_check.py
Labels: automerge

#3455 replace q_if with control
  qiskit/circuit/add_control.py
  qiskit/circuit/gate.py
  qiskit/circuit/instruction.py
  qiskit/circuit/instructionset.py
  qiskit/circuit/quantumcircuit.py
  qiskit/converters/__init__.py
  qiskit/converters/circuit_to_gate.py
  qiskit/converters/instruction_to_gate.py
  test/python/circuit/test_controlled_gate.py
  test/python/converters/test_circuit_to_gate.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: automerge

#3495 Refactor plot histogram
  qiskit/visualization/counts_visualization.py
Labels: automerge

#3473 Handle unicode parameters in latex circuit drawer
  qiskit/visualization/latex.py
Labels: automerge

#3431 Removing U0Gate
  qiskit/converters/ast_to_dag.py
  qiskit/extensions/standard/__init__.py
  qiskit/extensions/standard/u0.py
  releasenotes/notes/remove_u0-6514a8ddcf51f609.yaml
  test/python/circuit/test_extensions_standard.py
  test/python/transpiler/test_unroller.py
  test/python/visualization/references/circuit_latex_ref.png
  test/python/visualization/references/circuit_matplotlib_ref.png
  test/python/visualization/references/circuit_text_ref.txt
  test/python/visualization/test_circuit_visualization_output.py
  test/randomized/test_transpiler_equivalence.py
Labels: Changelog: Removal, automerge

#3490 Gate parameters support mix of indexes and bits
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_circuit_registers.py
Labels: Changelog: Bugfix, automerge

#3319 Pulse: improved error message for overlapping pulses; Fixes #2523
  qiskit/pulse/schedule.py
  qiskit/pulse/timeslots.py
  test/python/pulse/test_schedule.py
Labels: automerge

#3498 Issue #3496: empty filter bug for pulse.Schedule
  qiskit/pulse/schedule.py
  test/python/pulse/test_schedule.py
Labels: automerge

#3450 Added better shift method for timeslot collection
  qiskit/pulse/timeslots.py
Labels: automerge, performance

#3451 don't serialize private attributes
  qiskit/validation/base.py
Labels: automerge

#3446 Result marginal counts
  qiskit/result/__init__.py
  qiskit/result/postprocess.py
  qiskit/result/result.py
  qiskit/result/utils.py
  releasenotes/notes/marginal-counts-51108f216cc684d1.yaml
  test/python/result/test_result.py
Labels: Changelog: New Feature, automerge

#3506 Revert auto-Parameter creation from param of type str.
  qiskit/circuit/instruction.py
Labels: automerge

#3504 Add FakeRochester to mock backends.
  qiskit/test/mock/backends/__init__.py
  qiskit/test/mock/backends/rochester/__init__.py
  qiskit/test/mock/backends/rochester/fake_rochester.py
  qiskit/test/mock/backends/rochester/props_rochester.json
  qiskit/test/mock/fake_provider.py
  test/python/visualization/references/53_plot_circuit_layout.png
  test/python/visualization/references/53bit_quantum_computer.png
  test/randomized/test_transpiler_equivalence.py
Labels: automerge

#3513 A circuit without registers should have depth=0
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_circuit_properties.py
Labels: Changelog: Bugfix, automerge

#3507 Remove top-level sympy imports from multi-control gates.
  qiskit/extensions/standard/multi_control_rotation_gates.py
  qiskit/extensions/standard/multi_control_u1_gate.py
Labels: automerge

#3510 Add Hellinger fidelity discrete probability measure.
  qiskit/quantum_info/__init__.py
  qiskit/quantum_info/analysis/__init__.py
  qiskit/quantum_info/analysis/distance.py
  test/python/quantum_info/test_analyzation.py
Labels: automerge, enhancement

#3469 add test for to_matrix method of standard gates
  test/python/circuit/test_extensions_standard.py
Labels: automerge

#3514 Add ability to get counts from statevectors and density matrices
  qiskit/quantum_info/states/__init__.py
  qiskit/quantum_info/states/counts.py
  qiskit/quantum_info/states/densitymatrix.py
  qiskit/quantum_info/states/statevector.py
  qiskit/result/result.py
  test/python/quantum_info/test_counts.py
  test/python/quantum_info/test_states.py
Labels: automerge

#3508 Update error map colormap to cube helix
  qiskit/visualization/gate_map.py
Labels: automerge

#3505 Revert addition of p as alias for s gate on QuantumCircuit.
  qiskit/extensions/standard/s.py
  releasenotes/notes/add-cnot-alias-d4e4c8a409c85ad2.yaml
Labels: automerge

#3465 added release notes for controlled gate class (#2862).
  releasenotes/notes/add_ControlledGate_class-010c5c90f8f95e78.yaml
  test/python/circuit/test_controlled_gate.py
Labels: automerge
