Repository Qiskit/qiskit, pull requests merged in 2019-01, with the labels that each got.

#1638 Fix plot_histogram with number_to_keep
  qiskit/tools/visualization/_counts_visualization.py
Labels: type: bug

#1674 do not attempt to access old result of non-qobj device
  test/python/ibmq/test_ibmq_job.py
Labels: good first issue

#1735 Update coupling distance and computing of random scalings in Stochastic mapper
  qiskit/mapper/_coupling.py
  qiskit/transpiler/passes/mapping/stochastic_swap.py
Labels: type: enhancement
