Repository Qiskit/qiskit, pull requests merged in 2019-02, with the labels that each got.

#1746 Only copy Layout when needed
  qiskit/transpiler/passes/mapping/stochastic_swap.py
Labels: type: enhancement

#1757 Add model for pulse "defaults"
  qiskit/providers/models/__init__.py
  qiskit/providers/models/pulsedefaults.py
  qiskit/schemas/default_pulse_configuration_schema.json
  qiskit/schemas/examples/default_pulse_configuration_example.json
  test/python/test_schemas.py
Labels: type: specs

#1071 Utility for reporting a CI failure as a GitHub issue.
  .travis.yml
  appveyor.yml
  requirements-dev.txt
  tools/report_ci_failure.py
Labels: type: qa

#1834 25% faster DAG.add_wire
  qiskit/dagcircuit/_dagcircuit.py
Labels: type: enhancement

#1865 Simple Qobj repr
  qiskit/qobj/qobj.py
Labels: enhancement
