Repository Qiskit/qiskit, pull requests merged in 2020-12, with the labels that each got.

#5365 Update pulse qobj schema to return parametric pulse name
  qiskit/qobj/converters/pulse_instruction.py
  releasenotes/notes/add-parametric-pulse-label-e74e5c614c446d66.yaml
  test/python/qobj/test_pulse_converter.py
Labels: automerge

#5454 Pin appnope in CI
  constraints.txt
Labels: automerge, priority: high

#5301 Deprecate Python 3.6 support
  qiskit/__init__.py
  releasenotes/notes/deprecate-3.6-d48643e1b778d70c.yaml
Labels: Changelog: Deprecation, automerge

#5452 Added meas_level and meas_return for circuit jobs
  qiskit/compiler/assemble.py
  qiskit/qobj/qasm_qobj.py
  releasenotes/notes/circuit-meas-level-one-147399217ce0b34b.yaml
  test/python/compiler/test_assembler.py
Labels: Changelog: New Feature, automerge

#5448 Add myself to codeowner of visualization module
  .github/CODEOWNERS
Labels: automerge

#5449 Move ``Quaternion`` from operators to synthesis
  qiskit/quantum_info/__init__.py
  qiskit/quantum_info/operators/__init__.py
  qiskit/quantum_info/synthesis/__init__.py
  qiskit/quantum_info/synthesis/quaternion.py
  qiskit/transpiler/passes/optimization/optimize_1q_gates.py
  releasenotes/notes/quaternion-906f490b42fc034c.yaml
  test/python/quantum_info/test_quaternions.py
Labels: Changelog: API Change, automerge

#5352 Add stacklevel kwarg to deprecate function decorator
  qiskit/utils/deprecation.py
Labels: automerge

#5189 Add support for Python 3.9
  azure-pipelines.yml
  qiskit/test/base.py
  qiskit/test/utils.py
  releasenotes/notes/python39-617f3ed823e63cfe.yaml
  setup.py
  test/python/tools/jupyter/test_notebooks.py
Labels: Changelog: New Feature, automerge

#5418 Add integer option to initialize to init using bitmap
  qiskit/extensions/quantum_initializer/initializer.py
  releasenotes/notes/initialize_from_int-800e4db98b502baa.yaml
  test/python/circuit/test_initializer.py
Labels: Changelog: New Feature, automerge

#5190 allow statevectors to be parameter in initialize
  qiskit/extensions/quantum_initializer/initializer.py
  test/python/circuit/test_initializer.py
Labels: Changelog: API Change, automerge

#5315 use cu instead of mcrz-mcry-mcrz in add_control for gate u
  qiskit/circuit/add_control.py
  test/python/circuit/test_controlled_gate.py
Labels: automerge

#5422 Migrate qiskit.aqua.utils, qiskit.aqua.aqua_globals and qiskit.aqua.quantum_instance to qiskit.utils
  qiskit/__init__.py
  qiskit/circuit/duration.py
  qiskit/circuit/library/generalized_gates/mcmt.py
  qiskit/circuit/quantumcircuit.py
  qiskit/exceptions.py
  qiskit/extensions/quantum_initializer/squ.py
  qiskit/providers/basicaer/qasm_simulator.py
  qiskit/providers/basicaer/statevector_simulator.py
  qiskit/providers/basicaer/unitary_simulator.py
  qiskit/providers/models/backendproperties.py
  qiskit/pulse/schedule.py
  qiskit/scheduler/utils.py
  qiskit/tools/parallel.py
  qiskit/transpiler/instruction_durations.py
  qiskit/utils/__init__.py
  qiskit/utils/aqua_globals.py
  qiskit/utils/arithmetic.py
  qiskit/utils/backend_utils.py
  qiskit/utils/circuit_utils.py
  qiskit/utils/entangler_map.py
  qiskit/utils/measurement_error_mitigation.py
  qiskit/utils/name_unnamed_args.py
  qiskit/utils/quantum_instance.py
  qiskit/utils/run_circuits.py
  qiskit/utils/validation.py
  qiskit/visualization/state_visualization.py
Labels: on hold

#5215 Add support for circuits and labels in Statevector.equiv
  qiskit/quantum_info/states/densitymatrix.py
  qiskit/quantum_info/states/statevector.py
  releasenotes/notes/statevector-equiv-ad588688fa260940.yaml
  test/python/quantum_info/states/test_densitymatrix.py
  test/python/quantum_info/states/test_statevector.py
Labels: Changelog: New Feature, automerge

#5458 Fix parameter assignment bug.
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_parameters.py
Labels: automerge

#5444 ParameterExpression.__eq__ takes bounded expr == value
  qiskit/circuit/parameterexpression.py
  releasenotes/notes/parameterexpression-eq-compares-bounded-expr-to-val-ba7588cac6e53b5d.yaml
  test/python/circuit/test_parameters.py
Labels: automerge

#5433 Remove deprecated DAGCircuit.qubits() and .clbits() methods.
  qiskit/dagcircuit/dagcircuit.py
  releasenotes/notes/dagcircuit-remove-deprecated-bit-methods-8fb2d97ac4abdf4a.yaml
Labels: Changelog: Removal, automerge

#4811 Remove autoscale view call from plot_state_hinton
  qiskit/visualization/state_visualization.py
Labels: automerge

#5410 set UchannelLO scale property as complex number
  qiskit/test/mock/backends/almaden/fake_almaden.py
  qiskit/test/mock/backends/armonk/fake_armonk.py
  qiskit/test/mock/backends/athens/fake_athens.py
  qiskit/test/mock/backends/boeblingen/fake_boeblingen.py
  qiskit/test/mock/backends/burlington/fake_burlington.py
  qiskit/test/mock/backends/cambridge/fake_cambridge.py
  qiskit/test/mock/backends/essex/fake_essex.py
  qiskit/test/mock/backends/johannesburg/fake_johannesburg.py
  qiskit/test/mock/backends/london/fake_london.py
  qiskit/test/mock/backends/manhattan/fake_manhattan.py
  qiskit/test/mock/backends/montreal/fake_montreal.py
  qiskit/test/mock/backends/ourense/fake_ourense.py
  qiskit/test/mock/backends/paris/fake_paris.py
  qiskit/test/mock/backends/rochester/fake_rochester.py
  qiskit/test/mock/backends/rome/fake_rome.py
  qiskit/test/mock/backends/santiago/fake_santiago.py
  qiskit/test/mock/backends/singapore/fake_singapore.py
  qiskit/test/mock/backends/toronto/fake_toronto.py
  qiskit/test/mock/backends/valencia/fake_valencia.py
  qiskit/test/mock/backends/vigo/fake_vigo.py
  qiskit/test/mock/backends/yorktown/fake_yorktown.py
  qiskit/test/mock/fake_pulse_backend.py
  qiskit/test/mock/fake_qasm_backend.py
  qiskit/test/mock/utils/json_decoder.py
  qiskit/visualization/pulse_v2/device_info.py
  test/python/providers/test_backendconfiguration.py
Labels: automerge

#5463 Leverage retworkx for DAGCircuit.collect_runs()
  qiskit/dagcircuit/dagcircuit.py
  requirements.txt
  setup.py
Labels: automerge, performance

#5332 Optimize allocated qubits in arithmetic circuits
  qiskit/circuit/library/arithmetic/piecewise_linear_pauli_rotations.py
  qiskit/circuit/library/arithmetic/piecewise_polynomial_pauli_rotations.py
  qiskit/circuit/library/arithmetic/polynomial_pauli_rotations.py
  qiskit/circuit/library/arithmetic/weighted_adder.py
  releasenotes/notes/optimize-arithmetic-circuits-qubits-allocation-8ee9a9316f387b1f.yaml
  test/python/circuit/library/test_functional_pauli_rotations.py
  test/python/circuit/library/test_weighted_adder.py
  test/python/circuit/test_piecewise_polynomial.py
Labels: Changelog: Bugfix, Changelog: Deprecation, automerge

#5183 Use retworkx for CouplingMap
  qiskit/transpiler/coupling.py
  qiskit/transpiler/passes/routing/algorithms/token_swapper.py
  qiskit/transpiler/passes/routing/cython/stochastic_swap/swap_trial.pyx
  qiskit/transpiler/passes/routing/layout_transformation.py
  qiskit/transpiler/passes/routing/sabre_swap.py
  test/python/transpiler/test_token_swapper.py
Labels: automerge, performance

#5165 fixed issue #4878 by updating assemble.py file
  qiskit/compiler/assemble.py
  test/python/compiler/test_assembler.py
Labels: automerge

#5465 Expand test_examples skip on macOS
  test/python/test_examples.py
Labels: automerge

#5384 Add environment variable for number of procs in parallel_map
  qiskit/tools/parallel.py
  releasenotes/notes/paralle-config-options-97c1ad44ab76e052.yaml
Labels: Changelog: New Feature, automerge

#5294 Remove list searches in CouplingMap.distance()
  qiskit/transpiler/coupling.py
Labels: automerge, performance

#5459 Expands documentation and adds examples to circuit.initialize
  qiskit/extensions/quantum_initializer/initializer.py
Labels: automerge

#5396 Bug fix to ensure that calibrations are carried over by circuit compose
  qiskit/circuit/quantumcircuit.py
  qiskit/converters/circuit_to_dagdependency.py
  qiskit/converters/dag_to_circuit.py
  qiskit/converters/dagdependency_to_circuit.py
  qiskit/dagcircuit/dagcircuit.py
  qiskit/dagcircuit/dagdependency.py
  test/python/circuit/test_compose.py
  test/python/converters/test_circuit_to_dag.py
  test/python/converters/test_circuit_to_dagdependency.py
Labels: Changelog: Bugfix, automerge

#5469 Leverage retworkx generators for all cmap constructors
  qiskit/transpiler/coupling.py
Labels: automerge, performance

#5471 Migrate ApproximateTokenSwapper to only use retworkx and make networkx optional
  qiskit/dagcircuit/dagcircuit.py
  qiskit/dagcircuit/dagdependency.py
  qiskit/transpiler/passes/routing/algorithms/token_swapper.py
  releasenotes/notes/nx-optional-6b8ad63529fe32ca.yaml
  requirements-dev.txt
  requirements.txt
  setup.py
Labels: Changelog: Removal, performance

#5481 Convert delays to instructions when assembling
  qiskit/assembler/assemble_schedules.py
  qiskit/qobj/converters/pulse_instruction.py
  releasenotes/notes/bugfix-assemble-delay-32a96b59bb84badd.yaml
  test/python/compiler/test_assembler.py
  test/python/compiler/test_disassembler.py
Labels: Changelog: Bugfix, automerge

#5455 [Issue 5304]: Typecast to float only if bound to parameters
  qiskit/scheduler/lowering.py
  releasenotes/notes/fixissue5304-e9cf33c977ee38ee.yaml
  test/python/scheduler/test_basic_scheduler.py
Labels: Changelog: Bugfix, automerge

#5402 Add ``__array__`` method to ``Gate`` and ``quantum_info`` classes
  qiskit/circuit/delay.py
  qiskit/circuit/gate.py
  qiskit/circuit/library/generalized_gates/pauli.py
  qiskit/circuit/library/standard_gates/dcx.py
  qiskit/circuit/library/standard_gates/h.py
  qiskit/circuit/library/standard_gates/i.py
  qiskit/circuit/library/standard_gates/iswap.py
  qiskit/circuit/library/standard_gates/p.py
  qiskit/circuit/library/standard_gates/r.py
  qiskit/circuit/library/standard_gates/rx.py
  qiskit/circuit/library/standard_gates/rxx.py
  qiskit/circuit/library/standard_gates/ry.py
  qiskit/circuit/library/standard_gates/ryy.py
  qiskit/circuit/library/standard_gates/rz.py
  qiskit/circuit/library/standard_gates/rzx.py
  qiskit/circuit/library/standard_gates/rzz.py
  qiskit/circuit/library/standard_gates/s.py
  qiskit/circuit/library/standard_gates/swap.py
  qiskit/circuit/library/standard_gates/sx.py
  qiskit/circuit/library/standard_gates/t.py
  qiskit/circuit/library/standard_gates/u.py
  qiskit/circuit/library/standard_gates/u1.py
  qiskit/circuit/library/standard_gates/u2.py
  qiskit/circuit/library/standard_gates/u3.py
  qiskit/circuit/library/standard_gates/x.py
  qiskit/circuit/library/standard_gates/y.py
  qiskit/circuit/library/standard_gates/z.py
  qiskit/extensions/hamiltonian_gate.py
  qiskit/extensions/unitary.py
  qiskit/quantum_info/operators/channel/chi.py
  qiskit/quantum_info/operators/channel/choi.py
  qiskit/quantum_info/operators/channel/ptm.py
  qiskit/quantum_info/operators/channel/superop.py
  qiskit/quantum_info/operators/operator.py
  qiskit/quantum_info/operators/pauli.py
  qiskit/quantum_info/operators/scalar_op.py
  qiskit/quantum_info/operators/symplectic/clifford.py
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
  qiskit/quantum_info/states/densitymatrix.py
  qiskit/quantum_info/states/quantum_state.py
  qiskit/quantum_info/states/statevector.py
  test/python/circuit/test_delay.py
Labels: automerge

#5421 Fixes truncation of plain circuit drawers when used with matplotlib
  qiskit/visualization/matplotlib.py
  test/ipynb/mpl/references/no_op_circut.png
  test/ipynb/mpl/test_circuit_matplotlib_drawer.py
Labels: automerge

#5480 Allow specifying the last interval in PiecewisePolynomialPauliRotations
  qiskit/circuit/library/arithmetic/piecewise_polynomial_pauli_rotations.py
  releasenotes/notes/fix-piecewise-breakpoints-21db5a7823fdfbed.yaml
  test/python/circuit/test_piecewise_polynomial.py
Labels: Changelog: New Feature, automerge

#5427 Give more informative result memory error
  qiskit/result/result.py
Labels: automerge

#5483 Prevent base pulse channel classes from being instantiated
  qiskit/pulse/channels.py
  qiskit/pulse/macros.py
  releasenotes/notes/prevent-instantiation-base-channels-662dba1c144ef9b3.yaml
  test/python/pulse/test_channels.py
Labels: automerge

#5478 Bump cibuildwheel to latest version
  azure-pipelines.yml
Labels: automerge

#5411 Use retworkx neighbors method in noise adaptive layout
  qiskit/transpiler/passes/layout/noise_adaptive_layout.py
Labels: automerge, performance

#5462 Check if assigned string is valid in name setter method of Register class
  qiskit/circuit/register.py
  releasenotes/notes/check-name-string-in-setter-openqasm-valid-0fe1d7c42e37b679.yaml
  test/python/circuit/test_circuit_registers.py
Labels: automerge

#5451 Add cache step for stestr history dir
  azure-pipelines.yml
Labels: automerge

#5274 routing_method='none' and Error pass
  qiskit/compiler/transpile.py
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/utils/__init__.py
  qiskit/transpiler/passes/utils/check_map.py
  qiskit/transpiler/passes/utils/error.py
  qiskit/transpiler/preset_passmanagers/level0.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  releasenotes/notes/routing_method_none-d548ae4426db7412.yaml
  test/python/compiler/test_transpiler.py
  test/python/transpiler/test_error.py
Labels: Changelog: New Feature, automerge

#4832 Better reporting when result object fails
  qiskit/result/result.py
  test/python/result/test_result.py
Labels: automerge

#5489 Fix compensate_phase of pulse.builder.frequency_offset
  qiskit/pulse/builder.py
  releasenotes/notes/fix-compensate-phase-431a67867853b0c7.yaml
  test/python/pulse/test_builder.py
Labels: Changelog: Bugfix, automerge, stable backport potential

#5492 Add missing layout data for ibmq_casablanca.
  qiskit/visualization/gate_map.py
Labels: Changelog: Bugfix, automerge, stable backport potential

#5341 Only send options a backend supports in execute()
  qiskit/execute.py
Labels: automerge

#5488 Move equivalence drawer visualization imports to runtime
  qiskit/circuit/equivalence.py
Labels: automerge, performance

#5270 Add metadata attribute to QuantumCircuit
  qiskit/assembler/assemble_circuits.py
  qiskit/assembler/assemble_schedules.py
  qiskit/circuit/quantumcircuit.py
  qiskit/converters/circuit_to_dag.py
  qiskit/converters/circuit_to_dagdependency.py
  qiskit/converters/dag_to_circuit.py
  qiskit/converters/dag_to_dagdependency.py
  qiskit/converters/dagdependency_to_circuit.py
  qiskit/converters/dagdependency_to_dag.py
  qiskit/dagcircuit/dagcircuit.py
  qiskit/dagcircuit/dagdependency.py
  qiskit/pulse/schedule.py
  qiskit/pulse/transforms.py
  qiskit/scheduler/methods/basic.py
  qiskit/transpiler/passes/layout/apply_layout.py
  qiskit/transpiler/passes/scheduling/alap.py
  qiskit/transpiler/passes/scheduling/asap.py
  releasenotes/notes/circuit_metadata-3157879d02cfd722.yaml
  test/python/compiler/test_assembler.py
  test/python/compiler/test_transpiler.py
  test/python/converters/test_circuit_to_dagdependency.py
  test/python/converters/test_dag_to_dagdependency.py
  test/python/scheduler/test_basic_scheduler.py
Labels: Changelog: New Feature, automerge

#5224 Add alternate basis fake cambridge backend
  qiskit/test/mock/backends/__init__.py
  qiskit/test/mock/backends/cambridge/__init__.py
  qiskit/test/mock/backends/cambridge/fake_cambridge.py
  qiskit/test/mock/backends/cambridge/props_cambridge_alt.json
  qiskit/test/mock/fake_provider.py
Labels: automerge

#5505 Remove rx.is_directed_acyclic_graph() from DAGCircuit.depth()
  qiskit/dagcircuit/dagcircuit.py
Labels: automerge, stable backport potential

#5347 Fixed handling of "decimals" parameter by updating format_statevector and format_unitary
  qiskit/result/postprocess.py
  test/python/result/test_result.py
Labels: Changelog: Bugfix, automerge

#5495 Do not execute CSPLayout if layout_method is set in transpile
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  releasenotes/notes/if_layout_method_no_csplayout-a63d8e419e7f94e0.yaml
  test/python/transpiler/test_preset_passmanagers.py
Labels: Changelog: API Change, automerge

#5339 Allow process fidelity to work with a non-unitary target channel
  qiskit/quantum_info/operators/measures.py
  releasenotes/notes/process-fidelity-target-5bac750390aa3306.yaml
Labels: Changelog: Deprecation, Changelog: New Feature, automerge

#5431 Improve 1q decomposition pass with multiple matching basis
  qiskit/dagcircuit/dagcircuit.py
  qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py
  test/python/dagcircuit/test_dagcircuit.py
  test/python/transpiler/test_optimize_1q_decomposition.py
Labels: automerge

#5261 Improved Pauli operator class
  qiskit/circuit/library/generalized_gates/pauli.py
  qiskit/quantum_info/__init__.py
  qiskit/quantum_info/operators/__init__.py
  qiskit/quantum_info/operators/pauli.py
  qiskit/quantum_info/operators/random.py
  qiskit/quantum_info/operators/symplectic/__init__.py
  qiskit/quantum_info/operators/symplectic/base_pauli.py
  qiskit/quantum_info/operators/symplectic/pauli.py
  qiskit/quantum_info/operators/symplectic/pauli_table.py
  qiskit/quantum_info/operators/symplectic/random.py
  qiskit/quantum_info/random.py
  releasenotes/notes/pauli-operator-76ae910a340a4ad4.yaml
  test/python/quantum_info/operators/symplectic/test_legacy_pauli.py
  test/python/quantum_info/operators/symplectic/test_pauli.py
Labels: Changelog: API Change, Changelog: Deprecation, Changelog: New Feature, automerge

#5514 Fix performance regression in CSPLayout pass
  qiskit/transpiler/passes/layout/csp_layout.py
Labels: performance

#4890 Allow arbitrary data attributes in ``ExperimentResultData``
  qiskit/result/models.py
  test/python/result/test_result.py
Labels: automerge

#5355 EquivalenceLibrary.draw to return SVG instead of PNG.
  qiskit/circuit/equivalence.py
Labels: Changelog: API Change, automerge

#5397 Conditionals must display to the right of measures using the same register
  qiskit/visualization/utils.py
  releasenotes/notes/conditional-displays-after-measure-3f53a86800b2c459.yaml
  test/ipynb/mpl/references/meas_condition.png
  test/ipynb/mpl/test_circuit_matplotlib_drawer.py
  test/python/visualization/references/test_teleport.tex
  test/python/visualization/test_circuit_text_drawer.py
Labels: automerge

#5520 Remove deprecated usage of Pauli
  qiskit/opflow/converters/pauli_basis_change.py
  qiskit/opflow/legacy/matrix_operator.py
  qiskit/opflow/legacy/op_converter.py
  qiskit/opflow/legacy/pauli_graph.py
  qiskit/opflow/legacy/tpb_grouped_weighted_pauli_operator.py
  qiskit/opflow/legacy/weighted_pauli_operator.py
  qiskit/opflow/operator_globals.py
  qiskit/opflow/primitive_ops/pauli_op.py
  qiskit/opflow/primitive_ops/pauli_sum_op.py
  qiskit/opflow/primitive_ops/primitive_op.py
  qiskit/quantum_info/operators/symplectic/pauli.py
  test/python/opflow/legacy/test_op_converter.py
  test/python/opflow/legacy/test_tpb_grouped_weighted_pauli_operator.py
  test/python/opflow/legacy/test_weighted_pauli_operator.py
  test/python/opflow/test_op_construction.py
  test/python/opflow/test_pauli_sum_op.py
Labels: automerge

#5534 Fix unbound template parameters in template substitution
  qiskit/transpiler/passes/optimization/template_matching/template_substitution.py
  releasenotes/notes/fixissue5533-b519ea28b1b3a3e2.yaml
  test/python/transpiler/test_template_matching.py
Labels: Changelog: Bugfix, automerge

#5482 added R gate equivalences
  qiskit/circuit/library/standard_gates/equivalence_library.py
  releasenotes/notes/equivalent-rot-gates-fd54279d93ceba09.yaml
  test/python/compiler/test_transpiler.py
  test/python/transpiler/test_basis_translator.py
Labels: automerge

#5516 Add readout_length to backend properties
  qiskit/providers/models/backendproperties.py
  qiskit/test/mock/backends/armonk/conf_armonk.json
  qiskit/test/mock/backends/armonk/defs_armonk.json
  qiskit/test/mock/backends/armonk/props_armonk.json
  qiskit/test/mock/backends/athens/conf_athens.json
  qiskit/test/mock/backends/athens/defs_athens.json
  qiskit/test/mock/backends/athens/props_athens.json
  qiskit/test/mock/backends/boeblingen/conf_boeblingen.json
  qiskit/test/mock/backends/boeblingen/defs_boeblingen.json
  qiskit/test/mock/backends/boeblingen/props_boeblingen.json
  qiskit/test/mock/backends/bogota/conf_bogota.json
  qiskit/test/mock/backends/bogota/defs_bogota.json
  qiskit/test/mock/backends/bogota/props_bogota.json
  qiskit/test/mock/backends/manhattan/conf_manhattan.json
  qiskit/test/mock/backends/manhattan/defs_manhattan.json
  qiskit/test/mock/backends/manhattan/props_manhattan.json
  qiskit/test/mock/backends/melbourne/props_melbourne.json
  qiskit/test/mock/backends/montreal/conf_montreal.json
  qiskit/test/mock/backends/montreal/defs_montreal.json
  qiskit/test/mock/backends/montreal/props_montreal.json
  qiskit/test/mock/backends/ourense/conf_ourense.json
  qiskit/test/mock/backends/ourense/props_ourense.json
  qiskit/test/mock/backends/paris/conf_paris.json
  qiskit/test/mock/backends/paris/defs_paris.json
  qiskit/test/mock/backends/paris/props_paris.json
  qiskit/test/mock/backends/rome/conf_rome.json
  qiskit/test/mock/backends/rome/defs_rome.json
  qiskit/test/mock/backends/rome/props_rome.json
  qiskit/test/mock/backends/santiago/conf_santiago.json
  qiskit/test/mock/backends/santiago/props_santiago.json
  qiskit/test/mock/backends/toronto/conf_toronto.json
  qiskit/test/mock/backends/toronto/defs_toronto.json
  qiskit/test/mock/backends/toronto/props_toronto.json
  qiskit/test/mock/backends/valencia/conf_valencia.json
  qiskit/test/mock/backends/valencia/defs_valencia.json
  qiskit/test/mock/backends/valencia/props_valencia.json
  qiskit/test/mock/backends/vigo/conf_vigo.json
  qiskit/test/mock/backends/vigo/props_vigo.json
  qiskit/test/mock/backends/yorktown/conf_yorktown.json
  qiskit/test/mock/backends/yorktown/props_yorktown.json
  qiskit/transpiler/instruction_durations.py
  releasenotes/notes/add-readout-length-4858fe8b40249681.yaml
  test/python/circuit/test_scheduled_circuit.py
  test/python/compiler/test_assembler.py
  test/python/providers/test_backendproperties.py
  test/python/transpiler/test_instruction_durations.py
Labels: automerge, type: enhancement

#5358 Remove ParametrizedSchedule dependency from instmap
  qiskit/assembler/disassemble.py
  qiskit/providers/models/pulsedefaults.py
  qiskit/pulse/instruction_schedule_map.py
  qiskit/pulse/instructions/instruction.py
  qiskit/pulse/library/parametric_pulses.py
  qiskit/pulse/parser.py
  qiskit/pulse/schedule.py
  qiskit/pulse/transforms.py
  qiskit/pulse/utils.py
  qiskit/qobj/converters/pulse_instruction.py
  qiskit/test/mock/fake_openpulse_2q.py
  qiskit/test/mock/fake_openpulse_3q.py
  releasenotes/notes/deprecate-parameterized-schedule-b917c6692dff518d.yaml
  test/python/providers/test_pulse_defaults.py
  test/python/pulse/test_builder.py
  test/python/pulse/test_instruction_schedule_map.py
  test/python/pulse/test_parameters.py
  test/python/qobj/test_pulse_converter.py
  test/python/scheduler/test_basic_scheduler.py
Labels: automerge

#5540 Remove ancilla register from polynomial pauli rotations
  qiskit/circuit/library/arithmetic/piecewise_polynomial_pauli_rotations.py
  qiskit/circuit/library/arithmetic/polynomial_pauli_rotations.py
  qiskit/circuit/library/standard_gates/multi_control_rotation_gates.py
  releasenotes/notes/remove-ancilla-polynomial-rotation-62cad73f395270ca.yaml
Labels: automerge

#5522 passmanager(..., callback=...) parameter removed
  qiskit/transpiler/passmanager.py
  releasenotes/notes/pm_cb_remove_5522-30358587a8db2701.yaml
Labels: Changelog: Removal

#5526 Better initial_layout validation
  qiskit/transpiler/passes/layout/full_ancilla_allocation.py
  qiskit/transpiler/passes/layout/set_layout.py
  test/python/compiler/test_transpiler.py
  test/python/transpiler/test_full_ancilla_allocation.py
Labels: Changelog: API Change, automerge

#5364 Add PiecewiseChebyshev arithmetic circuit
  qiskit/circuit/library/arithmetic/piecewise_chebyshev.py
  qiskit/circuit/library/arithmetic/piecewise_polynomial_pauli_rotations.py
  qiskit/circuit/library/arithmetic/polynomial_pauli_rotations.py
  qiskit/circuit/library/blueprintcircuit.py
  releasenotes/notes/add-piecewise-polynomial-chebyshev-66c82ffe1d749dd6.yaml
  test/python/circuit/library/test_piecewise_chebyshev.py
Labels: Changelog: New Feature

#5496 Ensure aux_operator eigenvalues are normalized
  qiskit/algorithms/minimum_eigen_solvers/vqe.py
  test/python/algorithms/test_vqe.py
Labels: automerge
