Repository Qiskit/qiskit, pull requests merged in 2020-06, with the labels that each got.

#4505 Remove deprecated multi-qubit acquire instructions
  qiskit/assembler/assemble_schedules.py
  qiskit/pulse/commands/acquire.py
  qiskit/pulse/instructions/acquire.py
  qiskit/pulse/transforms.py
  qiskit/qobj/converters/pulse_instruction.py
  qiskit/scheduler/utils.py
  releasenotes/notes/remove-multi-acquires-747701103ddd816c.yaml
  test/python/compiler/test_assembler.py
  test/python/pulse/test_schedule.py
Labels: Changelog: Removal, automerge

#4548 Fix reno indentation errors that shows up during `tox -edocs`
  releasenotes/notes/0.9/changes-on-upgrade-6fcd573269a8ebc5.yaml
  releasenotes/notes/0.9/missing-changelog-d8129ba95dde3156.yaml
  releasenotes/notes/0.9/new-features-0.9-159645f977a139f7.yaml
Labels: automerge

#4481 fixed issue 4391 by updating idle_wires() in dagcircuit
  qiskit/dagcircuit/dagcircuit.py
  qiskit/visualization/text.py
  qiskit/visualization/utils.py
  test/python/dagcircuit/test_dagcircuit.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: Changelog: API Change, Changelog: Bugfix, stable backport potential

#4535 Cache dag qubits/clbits
  qiskit/dagcircuit/dagcircuit.py
  qiskit/dagcircuit/dagdependency.py
  qiskit/transpiler/passes/layout/csp_layout.py
  qiskit/transpiler/passes/layout/noise_adaptive_layout.py
  qiskit/transpiler/passes/optimization/consolidate_blocks.py
  qiskit/transpiler/passes/optimization/hoare_opt.py
  qiskit/transpiler/passes/routing/basic_swap.py
  qiskit/transpiler/passes/routing/layout_transformation.py
  qiskit/transpiler/passes/routing/lookahead_swap.py
  qiskit/transpiler/passes/routing/stochastic_swap.py
  qiskit/transpiler/passes/utils/barrier_before_final_measurements.py
  qiskit/visualization/utils.py
  releasenotes/notes/deprecate-dag-qubits-method-0a61b37fa4a5bcd5.yaml
  test/python/dagcircuit/test_dagdependency.py
Labels: Changelog: Bugfix, Changelog: Deprecation, automerge, performance, stable backport potential

#4444 fix bug in unrolling open controlled basis gates.
  qiskit/circuit/controlledgate.py
  qiskit/extensions/unitary.py
  qiskit/transpiler/passes/basis/unroll_custom_definitions.py
  qiskit/transpiler/passes/basis/unroller.py
  releasenotes/notes/fix-unrolling-open-ctrl-gate-4a72116526afb1fd.yaml
  test/python/circuit/test_controlled_gate.py
Labels: Changelog: Bugfix, automerge, bug, stable backport potential

#4559 [Stable] Pin sphinx version temporarily (#4556)
  requirements-dev.txt
Labels: stable-backport

#4551 Added num_ctrl_bits and ctrl_state to UnitaryGate call to ControlledGate
  qiskit/extensions/unitary.py
  test/python/circuit/test_controlled_gate.py
Labels: Changelog: Bugfix

#4539 Add rep delay
  qiskit/compiler/assemble.py
  qiskit/execute.py
  qiskit/providers/models/backendconfiguration.py
  qiskit/qobj/pulse_qobj.py
  qiskit/schemas/backend_configuration_schema.json
  qiskit/schemas/qobj_schema.json
  releasenotes/notes/add-rep-delay-c97d5aa8fc9696da.yaml
  test/python/compiler/test_assembler.py
Labels: automerge

#4540 Add SetPhase instruction to pulse
  qiskit/pulse/__init__.py
  qiskit/pulse/instructions/__init__.py
  qiskit/pulse/instructions/phase.py
  qiskit/qobj/converters/pulse_instruction.py
  qiskit/schemas/examples/qobj_openpulse_example.json
  qiskit/schemas/qobj_schema.json
  qiskit/visualization/pulse/matplotlib.py
  releasenotes/notes/implement-set-phase-b5581ad6085b3cec.yaml
  test/python/pulse/test_schedule.py
  test/python/qobj/test_pulse_converter.py
  test/python/qobj/test_qobj.py
  test/python/visualization/test_pulse_visualization_output.py
Labels: Changelog: New Feature, automerge

#4568 Give MCX implementations more specific names.
  qiskit/circuit/library/standard_gates/x.py
  releasenotes/notes/4524-MCXVChain-gate-being-incorrectly-assembled-as-MCX-gate-df73b216e9777ecf.yaml
Labels: Changelog: Bugfix, automerge, stable backport potential

#4527 circuit.repeat appends gate instead of instruction if possible
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_circuit_operations.py
Labels: automerge

#4582 Set register name for definition of ControlledGates with ctrl_state.
  qiskit/circuit/controlledgate.py
  releasenotes/notes/4573-Open-ControlledGates-not-marked-equivalent-729bc971c897ede3.yaml
  test/python/circuit/test_controlled_gate.py
Labels: Changelog: Bugfix, stable backport potential

#4529 update matrix representation documentation of gates.
  qiskit/circuit/library/standard_gates/h.py
  qiskit/circuit/library/standard_gates/r.py
  qiskit/circuit/library/standard_gates/rx.py
  qiskit/circuit/library/standard_gates/ry.py
  qiskit/circuit/library/standard_gates/rz.py
  qiskit/circuit/library/standard_gates/rzx.py
  qiskit/circuit/library/standard_gates/rzz.py
  qiskit/circuit/library/standard_gates/t.py
  qiskit/circuit/library/standard_gates/u1.py
  qiskit/circuit/library/standard_gates/u3.py
  qiskit/circuit/library/standard_gates/z.py
  test/python/circuit/test_controlled_gate.py
Labels: automerge

#4586 Fix ZZFeatureMap barriers
  qiskit/circuit/library/data_preparation/zz_feature_map.py
  releasenotes/notes/fix-zz-feature-map-barriers-ab1a2d930a6b5af1.yaml
Labels: Changelog: Bugfix, automerge

#4483 Return helpful message when appending an `Instruction` class
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_instructions.py
Labels: automerge

#4564 test_mappers regenerate does not empty test/python/qasm/
  test/python/transpiler/test_mappers.py
Labels: automerge

#4508 Draw method: remove deprecated channels_to_plot argument
  qiskit/pulse/instructions/instruction.py
  qiskit/pulse/schedule.py
  qiskit/visualization/pulse/matplotlib.py
  qiskit/visualization/pulse_visualization.py
  releasenotes/notes/remove-channels-to-plot-argument-388c6b33ed00b0d6.yaml
Labels: Changelog: Removal, automerge

#4192 Unused variables (such as qasm(..., prec)) are being removed
  qiskit/qasm/node/barrier.py
  qiskit/qasm/node/binaryop.py
  qiskit/qasm/node/binaryoperator.py
  qiskit/qasm/node/cnot.py
  qiskit/qasm/node/creg.py
  qiskit/qasm/node/customunitary.py
  qiskit/qasm/node/expressionlist.py
  qiskit/qasm/node/external.py
  qiskit/qasm/node/format.py
  qiskit/qasm/node/gate.py
  qiskit/qasm/node/gatebody.py
  qiskit/qasm/node/id.py
  qiskit/qasm/node/idlist.py
  qiskit/qasm/node/if_.py
  qiskit/qasm/node/indexedid.py
  qiskit/qasm/node/intnode.py
  qiskit/qasm/node/measure.py
  qiskit/qasm/node/opaque.py
  qiskit/qasm/node/prefix.py
  qiskit/qasm/node/primarylist.py
  qiskit/qasm/node/program.py
  qiskit/qasm/node/qreg.py
  qiskit/qasm/node/real.py
  qiskit/qasm/node/reset.py
  qiskit/qasm/node/unaryoperator.py
  qiskit/qasm/node/universalunitary.py
  qiskit/qasm/qasmlexer.py
  qiskit/qasm/qasmparser.py
  qiskit/quantum_info/operators/channel/transformations.py
  qiskit/test/mock/fake_job.py
  qiskit/tools/jupyter/backend_overview.py
  qiskit/visualization/latex.py
  test/python/test_qasm_parser.py
Labels: automerge

#4183 Issue #4182 Initializer should use at most 2^(n+1)-2n cnots
  qiskit/extensions/quantum_initializer/initializer.py
  test/python/circuit/test_initializer.py
Labels: automerge

#4507 remove draw(..., line_length, ...) (deprecated after #3108)
  qiskit/circuit/quantumcircuit.py
  qiskit/visualization/circuit_visualization.py
  releasenotes/notes/line_length_remove_0.10-d13e5a15524e67c0.yaml
Labels: Changelog: Removal, automerge

#4470 Bugfix: Modified Pulse Style to default to RCParams.
  qiskit/visualization/pulse/matplotlib.py
  qiskit/visualization/pulse/qcstyle.py
Labels: Changelog: API Change, automerge

#4498 Remove almost-one-year-old deprecated methods (warning was inserted in #2683)
  qiskit/qasm/qasm.py
  qiskit/qasm/qasmparser.py
  releasenotes/notes/qasm_remove_0.9-7150d53da8eebfd8.yaml
  test/python/test_qasm_parser.py
Labels: Changelog: Removal, automerge

#4509 Circuit reverse_bits operation
  qiskit/circuit/instruction.py
  qiskit/circuit/library/arithmetic/polynomial_pauli_rotations.py
  qiskit/circuit/quantumcircuit.py
  qiskit/extensions/quantum_initializer/initializer.py
  releasenotes/notes/circuit-reverse-bits-ce1873a89b06e3df.yaml
  test/python/circuit/test_circuit_operations.py
  test/python/circuit/test_instructions.py
  test/python/circuit/test_parameters.py
Labels: Changelog: Deprecation, automerge

#4596 fixes issue of crashing on unroll of 3+ qubit gates (#4577).
  qiskit/transpiler/passes/basis/unroll_3q_or_more.py
  releasenotes/notes/large_gate_bugfix-cbf0b6f1dcfbd5dd.yaml
  test/python/transpiler/test_unroll_3q_or_more.py
Labels: Changelog: Bugfix, automerge

#4544 Testing MPL with a notebook in binder
  .github/workflows/binder_mpl.yml
  .gitignore
  postBuild
  test/ipynb/mpl/references/long_name.png
  test/ipynb/mpl/test_circuit_matplotlib_drawer.py
  test/ipynb/mpl_tester.ipynb
  test/ipynb/results.py
Labels: automerge, priority: high

#4537 Sabre layout and routing transpiler passes
  .pylintrc
  qiskit/compiler/transpile.py
  qiskit/dagcircuit/dagcircuit.py
  qiskit/transpiler/coupling.py
  qiskit/transpiler/layout.py
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/layout/__init__.py
  qiskit/transpiler/passes/layout/csp_layout.py
  qiskit/transpiler/passes/layout/sabre_layout.py
  qiskit/transpiler/passes/routing/__init__.py
  qiskit/transpiler/passes/routing/lookahead_swap.py
  qiskit/transpiler/passes/routing/sabre_swap.py
  qiskit/transpiler/preset_passmanagers/level0.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  releasenotes/notes/combine-into-edge-map-279441b53ed4e790.yaml
  releasenotes/notes/sabre-2a3bba505e48ee82.yaml
  test/python/dagcircuit/test_dagcircuit.py
  test/python/qasm/TestsSabreSwap_a_cx_to_map.qasm
  test/python/qasm/TestsSabreSwap_handle_measurement.qasm
  test/python/qasm/TestsSabreSwap_initial_layout.qasm
  test/python/transpiler/test_coupling.py
  test/python/transpiler/test_mappers.py
  test/python/transpiler/test_sabre_swap.py
Labels: automerge

#4358 Have bot only report failures on maintained branches
  tools/report_ci_failure.py
Labels: automerge

#4479 Fix QSphere visualization
  qiskit/circuit/tools/pi_check.py
  qiskit/visualization/state_visualization.py
Labels: automerge

#4454 Added test_compose_conditonal to test_compose in circuit and dagcircuit
  test/python/circuit/test_compose.py
  test/python/dagcircuit/test_compose.py
Labels: automerge

#4446 Adds BasisTanslator, UnrollCustomDefinitions to default levels.
  qiskit/circuit/library/standard_gates/equivalence_library.py
  qiskit/compiler/transpile.py
  qiskit/quantum_info/synthesis/two_qubit_decompose.py
  qiskit/transpiler/passes/optimization/collect_2q_blocks.py
  qiskit/transpiler/passes/optimization/consolidate_blocks.py
  qiskit/transpiler/passmanager_config.py
  qiskit/transpiler/preset_passmanagers/level0.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  releasenotes/notes/add-basistranslator-to-default-levels-1c0de250f8ca4a59.yaml
  test/python/circuit/test_extensions_standard.py
  test/python/circuit/test_gate_definitions.py
  test/python/compiler/test_transpiler.py
  test/python/transpiler/test_basis_translator.py
  test/python/transpiler/test_consolidate_blocks.py
Labels: Changelog: New Feature, automerge

#4584 disallow specifying controlled gate with zero controls.
  qiskit/circuit/add_control.py
  qiskit/circuit/controlledgate.py
  qiskit/circuit/library/standard_gates/x.py
  releasenotes/notes/disallow_num_ctrl_qubits_zero-eb102aa087f30250.yaml
  test/python/circuit/test_controlled_gate.py
Labels: Changelog: Bugfix, automerge

#4478 QuantumCircuit.to_gate(..., label=...) support
  qiskit/circuit/quantumcircuit.py
  qiskit/converters/circuit_to_gate.py
  releasenotes/notes/to_gate_label-d825a2997a504604.yaml
  test/python/converters/test_circuit_to_gate.py
Labels: Changelog: API Change, automerge

#4617 fix u3 decomposition doc
  qiskit/quantum_info/synthesis/one_qubit_decompose.py
Labels: automerge

#4135 Removing `condition` argument from `apply_operation_back`
  qiskit/converters/ast_to_dag.py
  qiskit/converters/circuit_to_dag.py
  qiskit/dagcircuit/dagcircuit.py
  qiskit/dagcircuit/dagnode.py
  qiskit/transpiler/passes/layout/apply_layout.py
  qiskit/transpiler/passes/optimization/consolidate_blocks.py
  qiskit/transpiler/passes/utils/merge_adjacent_barriers.py
  qiskit/transpiler/passes/utils/remove_final_measurements.py
  releasenotes/notes/deprecate-optional-condition-arg-7645c645c738e290.yaml
  test/python/dagcircuit/test_dagcircuit.py
Labels: Changelog: API Change, Changelog: Deprecation, automerge

#4619 Parameter conjugate
  qiskit/circuit/parameterexpression.py
  releasenotes/notes/parameter-conjugate-a16fd7ae0dc18ede.yaml
  test/python/circuit/test_parameters.py
Labels: Changelog: API Change

#4621 Fix schema bug in `rep_delay` addition
  qiskit/compiler/assemble.py
  qiskit/execute.py
  qiskit/qobj/pulse_qobj.py
  qiskit/schemas/qobj_schema.json
  test/python/compiler/test_assembler.py
Labels: automerge

#4613 fix sample pulse normalization
  qiskit/pulse/pulse_lib/sample_pulse.py
Labels: automerge

#3748 Add composite circuit definition when calling circuit.qasm()
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_circuit_qasm.py
Labels: automerge

#4628 set seed for sabre_layout
  qiskit/transpiler/passes/layout/sabre_layout.py
Labels: automerge

#4629 Switch from std::set to std::unordered set in swap_trial
  qiskit/transpiler/passes/routing/cython/stochastic_swap/swap_trial.pyx
Labels: performance

#4326 cregbundle might be impossible sometimes
  qiskit/visualization/circuit_visualization.py
  qiskit/visualization/text.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: automerge

#4579 remove deprecated qi functions
  qiskit/quantum_info/__init__.py
  qiskit/quantum_info/states/__init__.py
  qiskit/quantum_info/states/counts.py
  qiskit/quantum_info/states/states.py
  qiskit/tools/__init__.py
  qiskit/tools/qi/__init__.py
  qiskit/tools/qi/qi.py
  releasenotes/notes/remove-deprecated-qi-b7d5a8ca00849b02.yaml
  test/python/quantum_info/test_counts.py
  test/python/quantum_info/test_states.py
  test/python/test_qi.py
Labels: automerge

#4604 Polish the MPL tester
  .gitignore
  test/ipynb/mpl/references/conditional.png
  test/ipynb/mpl/references/empty_circut.png
  test/ipynb/mpl/references/no_barriers.png
  test/ipynb/mpl/references/plot_barriers_false.png
  test/ipynb/mpl/references/plot_barriers_true.png
  test/ipynb/mpl/test_circuit_matplotlib_drawer.py
  test/ipynb/results.py
  test/python/visualization/references/matplotlib_barriers_ref.png
  test/python/visualization/references/matplotlib_conditional_ref.png
  test/python/visualization/test_circuit_matplotlib_drawer.py
Labels: automerge
