Repository Qiskit/qiskit, pull requests merged in 2020-04, with the labels that each got.

#4041 Add measure and reset methods to QuantumState classes
  qiskit/quantum_info/states/densitymatrix.py
  qiskit/quantum_info/states/quantum_state.py
  qiskit/quantum_info/states/statevector.py
  releasenotes/notes/state-measure-reset-8a3f2df197325e9c.yaml
  test/python/quantum_info/states/test_densitymatrix.py
  test/python/quantum_info/states/test_statevector.py
Labels: automerge

#4060 Transpiler should raise when conflicting parameters, not just ignore them silently
  qiskit/compiler/transpile.py
  qiskit/execute.py
  qiskit/transpiler/passmanager.py
  releasenotes/notes/fix-3925-c0e40ece078f2ce1.yaml
  releasenotes/notes/parameter_conflict_in_transpile-fc67d76288b480c4.yaml
  releasenotes/notes/passmanager_parameter_in_transpile-9768d95afbe9127e.yaml
  test/python/circuit/test_unitary.py
  test/python/compiler/test_compiler.py
  test/python/compiler/test_transpiler.py
  test/python/transpiler/test_collect_2q_blocks.py
  test/python/transpiler/test_commutative_cancellation.py
  test/python/transpiler/test_consolidate_blocks.py
  test/python/transpiler/test_cx_cancellation.py
  test/python/transpiler/test_mappers.py
  test/python/transpiler/test_optimize_1q_gates.py
  test/python/transpiler/test_optimize_swap_before_measure.py
  test/python/transpiler/test_pass_scheduler.py
  test/python/transpiler/test_passmanager.py
  test/python/transpiler/test_remove_diagonal_gates_before_measure.py
  test/python/transpiler/test_remove_reset_in_zero_state.py
  test/python/transpiler/test_resource_estimation_pass.py
Labels: Changelog: API Change, automerge

#3883 Implement multi-controlled U1 as gate
  qiskit/circuit/add_control.py
  qiskit/extensions/standard/__init__.py
  qiskit/extensions/standard/multi_control_rotation_gates.py
  qiskit/extensions/standard/multi_control_u1_gate.py
  qiskit/extensions/standard/u1.py
  qiskit/extensions/standard/u3.py
  test/python/circuit/gate_utils.py
  test/python/circuit/test_controlled_gate.py
  test/python/circuit/test_gate_definitions.py
Labels: automerge

#4069 Pass parameters to super when creating Qobj
  qiskit/qobj/__init__.py
Labels: automerge

#4065 Add auto backport rule to mergify configuration
  .mergify.yml
Labels: automerge

#4034 Issue 3750 wrap up
  qiskit/pulse/__init__.py
  qiskit/pulse/commands/__init__.py
  qiskit/pulse/commands/acquire.py
  qiskit/pulse/commands/delay.py
  qiskit/pulse/commands/frame_change.py
  qiskit/pulse/commands/parametric_pulses.py
  qiskit/pulse/commands/persistent_value.py
  qiskit/pulse/commands/pulse_command.py
  qiskit/pulse/commands/sample_pulse.py
  qiskit/pulse/configuration.py
  qiskit/pulse/exceptions.py
  qiskit/pulse/instruction_schedule_map.py
  qiskit/pulse/instructions/__init__.py
  qiskit/pulse/instructions/acquire.py
  qiskit/pulse/instructions/delay.py
  qiskit/pulse/instructions/frequency.py
  qiskit/pulse/instructions/instruction.py
  qiskit/pulse/instructions/phase.py
  qiskit/pulse/instructions/play.py
  qiskit/pulse/instructions/snapshot.py
  qiskit/pulse/pulse_lib/__init__.py
  qiskit/pulse/pulse_lib/parametric_pulses.py
  qiskit/pulse/pulse_lib/pulse.py
  qiskit/pulse/pulse_lib/sample_pulse.py
  qiskit/pulse/pulse_lib/samplers/__init__.py
  qiskit/pulse/reschedule.py
  qiskit/qobj/converters/pulse_instruction.py
  test/python/compiler/test_assembler.py
  test/python/pulse/test_commands.py
  test/python/pulse/test_instruction_schedule_map.py
  test/python/pulse/test_instructions.py
  test/python/pulse/test_pulse_lib.py
  test/python/pulse/test_reschedule.py
  test/python/pulse/test_schedule.py
  test/python/qobj/test_pulse_converter.py
  test/python/scheduler/test_basic_scheduler.py
  test/python/scheduler/test_utils.py
Labels: automerge

#4058 Cleanup quantum_info.random
  qiskit/quantum_info/__init__.py
  qiskit/quantum_info/operators/__init__.py
  qiskit/quantum_info/operators/random.py
  qiskit/quantum_info/random.py
  qiskit/quantum_info/random/utils.py
  qiskit/quantum_info/states/random.py
  releasenotes/notes/quantum-info-random-970923d446d10471.yaml
  test/python/quantum_info/operators/test_random.py
  test/python/quantum_info/states/test_random.py
  test/python/quantum_info/test_random.py
  test/python/quantum_info/test_states.py
  test/python/test_qi.py
Labels: Changelog: Deprecation, Changelog: New Feature, automerge

#3904 Add channels to Pulse backend config schema
  qiskit/schemas/backend_configuration_schema.json
Labels: automerge

#4088 Fixed #4078 by checking for numpy int and added test to TestDelay
  qiskit/pulse/instructions/instruction.py
  test/python/pulse/test_instructions.py
Labels: automerge

#4068 Support for circuit.draw(initial_state=False)
  qiskit/circuit/quantumcircuit.py
  qiskit/visualization/circuit_visualization.py
  qiskit/visualization/latex.py
  qiskit/visualization/text.py
  releasenotes/notes/initial_state_draw_parameter-f360ac4e998ee944.yaml
  test/python/visualization/test_circuit_text_drawer.py
  test/python/visualization/test_circuit_visualization_output.py
Labels: Changelog: API Change, automerge

#4085 Add "channels" to pulse mock backends
  qiskit/test/mock/fake_openpulse_2q.py
  qiskit/test/mock/fake_openpulse_3q.py
Labels: automerge

#3960 Add printable string representation for new Qobj objects
  qiskit/qobj/pulse_qobj.py
  qiskit/qobj/qasm_qobj.py
Labels: automerge

#4075 Deprecate some unneeded methods of QuantumState
  qiskit/quantum_info/states/densitymatrix.py
  qiskit/quantum_info/states/quantum_state.py
  qiskit/quantum_info/states/statevector.py
  releasenotes/notes/states-dep-028ed0ef6a7db02a.yaml
  test/python/quantum_info/states/test_densitymatrix.py
  test/python/quantum_info/states/test_statevector.py
  test/python/quantum_info/test_counts.py
Labels: Changelog: Deprecation, automerge

#4061 Kickoff the arithmetics library
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/arithmetic/__init__.py
  qiskit/circuit/library/arithmetic/functional_pauli_rotations.py
  qiskit/circuit/library/arithmetic/integer_comparator.py
  qiskit/circuit/library/arithmetic/linear_pauli_rotations.py
  qiskit/circuit/library/arithmetic/piecewise_linear_pauli_rotations.py
  qiskit/circuit/library/arithmetic/polynomial_pauli_rotations.py
  qiskit/circuit/library/arithmetic/weighted_adder.py
  qiskit/circuit/quantumcircuit.py
  qiskit/extensions/standard/__init__.py
  qiskit/extensions/standard/boolean_logical_gates.py
  test/python/circuit/test_library.py
Labels: automerge

#4096 Remove marshmallow from RunConfig
  qiskit/assembler/models.py
  qiskit/assembler/run_config.py
Labels: automerge

#4062 Add random Clifford and pauli table functions
  qiskit/quantum_info/__init__.py
  qiskit/quantum_info/operators/random.py
  qiskit/quantum_info/operators/symplectic/random.py
  qiskit/quantum_info/random.py
  releasenotes/notes/random-clifford-b1ed4e3a9ee9e361.yaml
  test/python/quantum_info/operators/test_random.py
Labels: Changelog: New Feature, automerge

#4050 Add diamond norm function for quantum channels
  qiskit/quantum_info/__init__.py
  qiskit/quantum_info/operators/__init__.py
  qiskit/quantum_info/operators/measures.py
  releasenotes/notes/diamond-norm-8d2eb8f0ecfe0c04.yaml
  test/python/quantum_info/operators/test_measures.py
Labels: Changelog: New Feature, automerge

#4103 add a name attribute to CouplingMap
  qiskit/transpiler/coupling.py
  releasenotes/notes/coupling-map-name-b3bde705196bfe15.yaml
Labels: Changelog: New Feature, automerge

#4098 Optimized clifford synthesis for up to 3 qubits
  qiskit/quantum_info/operators/symplectic/clifford.py
  qiskit/quantum_info/operators/symplectic/clifford_circuits.py
  qiskit/quantum_info/synthesis/clifford_decompose.py
  releasenotes/notes/clifford-synthesis-42a959703bfc9c9a.yaml
  test/python/quantum_info/operators/symplectic/test_clifford.py
Labels: automerge

#4019 Optional parameter basis_gates in Optimize1qGates
  qiskit/transpiler/passes/optimization/optimize_1q_gates.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  test/python/compiler/test_transpiler.py
  test/python/transpiler/test_optimize_1q_gates.py
Labels: Changelog: API Change, automerge

#4037 Upgrading bind_parameters: allow in place and mixed floats + parameters
  qiskit/circuit/equivalence.py
  qiskit/circuit/quantumcircuit.py
  qiskit/converters/circuit_to_gate.py
  qiskit/converters/circuit_to_instruction.py
  releasenotes/notes/bind-parameters-mixed-values-and-in-place-48a68c882a03070b.yaml
  test/python/circuit/test_parameters.py
Labels: Changelog: API Change, automerge

#3668 Moving up some parameter checks in the class hierarchy
  qiskit/circuit/gate.py
  qiskit/circuit/instruction.py
  qiskit/converters/ast_to_dag.py
  qiskit/extensions/quantum_initializer/diagonal.py
  qiskit/extensions/quantum_initializer/initializer.py
  qiskit/extensions/quantum_initializer/isometry.py
  qiskit/extensions/quantum_initializer/mcg_up_to_diagonal.py
  qiskit/extensions/quantum_initializer/squ.py
  qiskit/extensions/quantum_initializer/uc.py
  qiskit/extensions/standard/barrier.py
  qiskit/extensions/unitary.py
  test/python/circuit/test_extensions_standard.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: automerge

#4112 Add LookaheadSwap condition to prevent hangs
  qiskit/transpiler/passes/routing/lookahead_swap.py
  test/python/transpiler/test_lookahead_swap.py
Labels: Changelog: Bugfix, automerge

#4082 Convert the MCX functions to gates
  qiskit/extensions/standard/__init__.py
  qiskit/extensions/standard/equivalence_library.py
  qiskit/extensions/standard/multi_control_toffoli_gate.py
  qiskit/extensions/standard/rcccx.py
  qiskit/extensions/standard/rccx.py
  qiskit/extensions/standard/x.py
  qiskit/qasm/libs/qelib1.inc
  qiskit/qasm/pygments/lexer.py
  test/python/circuit/test_controlled_gate.py
Labels: automerge

#4101 add circuit.num_nonlocal_gates
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/circuit-num-nonlocal-gates-e957432b1e6acc91.yaml
  test/python/circuit/test_circuit_properties.py
Labels: automerge

#4117 Revert "Moving up some parameter checks in the class hierarchy (#3668)"
  qiskit/circuit/gate.py
  qiskit/circuit/instruction.py
  qiskit/converters/ast_to_dag.py
  qiskit/extensions/quantum_initializer/diagonal.py
  qiskit/extensions/quantum_initializer/initializer.py
  qiskit/extensions/quantum_initializer/isometry.py
  qiskit/extensions/quantum_initializer/mcg_up_to_diagonal.py
  qiskit/extensions/quantum_initializer/squ.py
  qiskit/extensions/quantum_initializer/uc.py
  qiskit/extensions/standard/barrier.py
  qiskit/extensions/unitary.py
  test/python/circuit/test_extensions_standard.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: automerge, priority: high

#3932 Add ``SparsePauliOp`` operator class
  qiskit/quantum_info/__init__.py
  qiskit/quantum_info/operators/__init__.py
  qiskit/quantum_info/operators/symplectic/__init__.py
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
  test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
Labels: Changelog: New Feature, automerge

#4119 Bump version string post release
  .mergify.yml
  docs/conf.py
  qiskit/VERSION.txt
  setup.py
Labels: automerge

#3185 Hoare optimization transpiler pass
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/optimization/__init__.py
  qiskit/transpiler/passes/optimization/_gate_extension.py
  qiskit/transpiler/passes/optimization/hoare_opt.py
  requirements-dev.txt
  test/python/transpiler/test_hoare_opt.py
Labels: automerge

#4123 Visualization of open controlled gates added in latex drawer
  qiskit/visualization/latex.py
Labels: automerge

#4122 Show instance name in output of pulse drawer
  qiskit/visualization/pulse/matplotlib.py
  qiskit/visualization/pulse/qcstyle.py
  releasenotes/notes/add-title-to-pulse-drawer-69db1ddb2f696367.yaml
  test/python/visualization/references/instruction_matplotlib_ref.png
  test/python/visualization/references/parametric_matplotlib_ref.png
  test/python/visualization/references/pulse_matplotlib_ref.png
  test/python/visualization/references/schedule_matplotlib_ref.png
  test/python/visualization/references/schedule_show_framechange_ref.png
  test/python/visualization/references/truncated_schedule_matplotlib_ref.png
  test/python/visualization/test_pulse_visualization_output.py
Labels: automerge

#4140 Fix #4120 - Remove renaming the schedule after using `exclude` and `filter`
  qiskit/pulse/schedule.py
  test/python/pulse/test_schedule.py
Labels: automerge

#4136 fix latex control
  qiskit/visualization/latex.py
Labels: automerge

#4143 Fix import exception of Z3 package to be compatible with python 3.5
  qiskit/transpiler/passes/optimization/_gate_extension.py
  qiskit/transpiler/passes/optimization/hoare_opt.py
Labels: automerge

#4152 Fix conversion of numpy.number instruction params to python types.
  qiskit/circuit/instruction.py
  test/python/circuit/test_initializer.py
Labels: Changelog: Bugfix, automerge, stable backport potential

#4154 Use RZGate in RZXGate definition
  qiskit/extensions/standard/rzx.py
Labels: automerge

#4072 Circuit library: QFT
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/basis_change/__init__.py
  qiskit/circuit/library/basis_change/qft.py
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_library.py
Labels: automerge

#4150 Check circuit.mcx() ancilla input
  qiskit/extensions/standard/x.py
Labels: automerge

#4097 Add methods to retrieve info from channels config in backends
  qiskit/providers/models/backendconfiguration.py
  releasenotes/notes/fix-control-channel-logic-cdb45b7adae394d8.yaml
  test/python/providers/test_backendconfiguration.py
  test/python/pulse/test_schedule.py
Labels: automerge

#4115 Error checking, esp for Play.pulse
  qiskit/pulse/instructions/instruction.py
  qiskit/pulse/instructions/phase.py
  qiskit/pulse/instructions/play.py
  qiskit/pulse/pulse_lib/pulse.py
  qiskit/pulse/pulse_lib/sample_pulse.py
Labels: automerge

#4169 Fix performance of QuantumCircuit append() and qasm()
  qiskit/circuit/library/basis_change/qft.py
  qiskit/circuit/quantumcircuit.py
Labels: automerge

#4130 Boolean logic AND and OR to circuit library
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/boolean_logic.py
  qiskit/extensions/standard/boolean_logical_gates.py
  releasenotes/notes/logical-and-or-circuits-edcffef0b4b8ee62.yaml
  test/python/circuit/test_library.py
Labels: automerge

#4131 Add visualization of open controlled gates for mpl #3957
  qiskit/visualization/matplotlib.py
  qiskit/visualization/qcstyle.py
Labels: automerge

#3854 fixed issue 3427 by updating interpolation module functions
  qiskit/visualization/pulse/interpolation.py
Labels: Changelog: Bugfix, automerge

#3876 Changed pi_check to handle parameter values where possible
  qiskit/visualization/tools/pi_check.py
  test/python/visualization/test_circuit_text_drawer.py
  test/python/visualization/test_tools.py
Labels: Changelog: Bugfix, automerge

#4172 Remove FakeRochester from randomized transpiler testing.
  test/randomized/test_transpiler_equivalence.py
Labels: automerge

#4178 Properly copy registers on circuit copy
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_circuit_operations.py
Labels: automerge, bug, priority: high

#4095 For appended circuit add padding for wire labels in text drawing mode
  qiskit/visualization/text.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: Changelog: Bugfix, automerge

#4071 HamiltonianGate
  qiskit/extensions/__init__.py
  qiskit/extensions/hamiltonian_gate.py
  qiskit/visualization/text.py
  releasenotes/notes/introduce-hamiltonian-gate-5c51bb576706cee9.yaml
  test/python/circuit/test_hamiltonian_gate.py
  test/python/circuit/test_unitary.py
  test/python/quantum_info/states/test_measures.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: Changelog: New Feature, automerge

#4125 Allow last_update_date to be a string for BackendProperties.from_dict()
  qiskit/providers/models/backendproperties.py
  releasenotes/notes/properties-last-update-date-3d09884ff8634a2f.yaml
  requirements.txt
  setup.py
Labels: automerge

#4059 Assert rep_time is properly handled in backendconfiguration tests
  test/python/providers/test_backendconfiguration.py
Labels: automerge

#4124 Add missing dict conversion in backconfiguration class
  qiskit/providers/models/backendconfiguration.py
  qiskit/providers/models/pulsedefaults.py
  test/python/providers/test_fake_backends.py
Labels: automerge

#4205 Fix lint failure in diagonal gate
  qiskit/circuit/library/generalized_gates/diagonal.py
Labels: automerge

#4077 ParametricPulses: rename constantpulse to constant
  qiskit/pulse/__init__.py
  qiskit/pulse/commands/__init__.py
  qiskit/pulse/commands/parametric_pulses.py
  qiskit/pulse/commands/persistent_value.py
  qiskit/pulse/pulse_lib/__init__.py
  qiskit/pulse/pulse_lib/parametric_pulses.py
  qiskit/qobj/converters/pulse_instruction.py
  releasenotes/notes/rename-constant-pulse-dd5e5843df379ae2.yaml
  test/python/compiler/test_assembler.py
  test/python/pulse/test_pulse_lib.py
  test/python/pulse/test_schedule.py
  test/python/qobj/test_pulse_converter.py
  test/python/visualization/test_pulse_visualization_output.py
Labels: Changelog: API Change, automerge

#4173 Correct display of cx & ccx gates and fix bug on multi-control gates in text_drawer
  qiskit/visualization/text.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: Changelog: Bugfix, automerge

#4100 do not transpile Schedule when execute
  qiskit/execute.py
Labels: automerge

#4193 deterministic test/python/quantum_info/operators/test_random.py
  test/python/quantum_info/operators/test_random.py
  test/randomized/test_clifford.py
Labels: automerge

#4213 * Fixed SetFrequency name sf -> setf in pulse instructions.
  qiskit/qobj/converters/pulse_instruction.py
  qiskit/schemas/qobj_schema.json
  test/python/qobj/test_pulse_converter.py
Labels: automerge

#4212 Support delay in specification
  qiskit/schemas/qobj_schema.json
Labels: automerge

#4198 Instruction.is_parameterized to return False when fully bound.
  qiskit/circuit/instruction.py
  releasenotes/notes/instruction.is_parameterized-to-check-if-fully-bound-f1004abf10f15930.yaml
  test/python/circuit/test_parameters.py
Labels: Changelog: Bugfix, automerge

#4226 pickles to QASM in test/python/transpiler/test_mappers.py
  test/python/pickles/TestsBasicSwap_a_cx_to_map.pickle
  test/python/pickles/TestsBasicSwap_handle_measurement.pickle
  test/python/pickles/TestsBasicSwap_initial_layout.pickle
  test/python/pickles/TestsLookaheadSwap_a_cx_to_map.pickle
  test/python/pickles/TestsLookaheadSwap_handle_measurement.pickle
  test/python/pickles/TestsLookaheadSwap_initial_layout.pickle
  test/python/pickles/TestsStochasticSwap_a_cx_to_map.pickle
  test/python/pickles/TestsStochasticSwap_handle_measurement.pickle
  test/python/pickles/TestsStochasticSwap_initial_layout.pickle
  test/python/qasm/TestsBasicSwap_a_cx_to_map.qasm
  test/python/qasm/TestsBasicSwap_handle_measurement.qasm
  test/python/qasm/TestsBasicSwap_initial_layout.qasm
  test/python/qasm/TestsLookaheadSwap_a_cx_to_map.qasm
  test/python/qasm/TestsLookaheadSwap_handle_measurement.qasm
  test/python/qasm/TestsLookaheadSwap_initial_layout.qasm
  test/python/qasm/TestsStochasticSwap_a_cx_to_map.qasm
  test/python/qasm/TestsStochasticSwap_handle_measurement.qasm
  test/python/qasm/TestsStochasticSwap_initial_layout.qasm
  test/python/transpiler/test_mappers.py
Labels: automerge

#4214 Add EquivalenceLibrary.has_entry.
  qiskit/circuit/equivalence.py
  releasenotes/notes/add-equivalence_library.has_entry-b58a6aa3f0b05d40.yaml
  test/python/circuit/test_equivalence.py
Labels: automerge

#4199 Fix ParameterExpression.subs not detecting parameter name conflicts.
  qiskit/circuit/parameterexpression.py
  releasenotes/notes/parameterexpression.subs-not-detecting-name-conflicts-1c8e5a791f1acb36.yaml
  test/python/circuit/test_parameters.py
Labels: Changelog: Bugfix, automerge

#3824 Docathon: update documentation for controlled gates
  qiskit/circuit/add_control.py
  qiskit/circuit/controlledgate.py
  qiskit/circuit/gate.py
Labels: type: documentation

#4207 allow setting label on circuit append
  qiskit/circuit/library/basis_change/qft.py
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/circuit-append-gate-label-6adba4c3fa6b308f.yaml
Labels: automerge

#4227 Cache Parameter hashes
  qiskit/circuit/parameter.py
Labels: automerge, performance

#4229 Handle error on import if pygments < 2.4 is installed
  qiskit/circuit/quantumcircuit.py
  qiskit/qasm/__init__.py
  qiskit/qasm/pygments/__init__.py
  qiskit/qasm/pygments/lexer.py
  qiskit/tools/jupyter/library.py
Labels: Changelog: Bugfix, automerge, stable backport potential

#4234 Change `QuantumCircuit` append back to accept `to_instruction()`
  qiskit/circuit/quantumcircuit.py
Labels: automerge

#4076 Adds ability to set ctrl_state on standard gates
  qiskit/circuit/_utils.py
  qiskit/circuit/add_control.py
  qiskit/circuit/controlledgate.py
  qiskit/extensions/standard/h.py
  qiskit/extensions/standard/rx.py
  qiskit/extensions/standard/ry.py
  qiskit/extensions/standard/rz.py
  qiskit/extensions/standard/swap.py
  qiskit/extensions/standard/u1.py
  qiskit/extensions/standard/u3.py
  qiskit/extensions/standard/x.py
  qiskit/extensions/standard/y.py
  qiskit/extensions/standard/z.py
  qiskit/extensions/unitary.py
  releasenotes/notes/fix-ctrl-state-std-gate-75a7a361dcc66001.yaml
  test/python/circuit/test_controlled_gate.py
Labels: Changelog: Bugfix, automerge, bug

#4236 Make z3-solver opt-in for testing
  azure-pipelines.yml
  requirements-dev.txt
  test/python/transpiler/test_hoare_opt.py
Labels: automerge

#4245 Fix potential cyclic imports
  qiskit/extensions/quantum_initializer/ucrx.py
  qiskit/extensions/quantum_initializer/ucry.py
  qiskit/extensions/quantum_initializer/ucrz.py
Labels: automerge

#4246 Compress built docs before upload
  azure-pipelines.yml
Labels: automerge

#4224 Error checking for time inputs to schedules and instructions
  qiskit/pulse/instructions/instruction.py
  qiskit/pulse/schedule.py
  test/python/pulse/test_schedule.py
Labels: automerge

#4185 Blueprint circuit for the circuit library
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/arithmetic/functional_pauli_rotations.py
  qiskit/circuit/library/arithmetic/integer_comparator.py
  qiskit/circuit/library/arithmetic/linear_pauli_rotations.py
  qiskit/circuit/library/arithmetic/piecewise_linear_pauli_rotations.py
  qiskit/circuit/library/arithmetic/polynomial_pauli_rotations.py
  qiskit/circuit/library/arithmetic/weighted_adder.py
  qiskit/circuit/library/basis_change/qft.py
  qiskit/circuit/library/blueprintcircuit.py
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_library.py
Labels: automerge

#4265 adding published reference to volume circuit
  qiskit/circuit/library/quantum_volume.py
Labels: automerge

#4267 changing name to openqasm and circuit properties
  qiskit/tools/jupyter/library.py
Labels: automerge

#4270 Improving gate labeling in text-drawer
  qiskit/visualization/text.py
  test/python/visualization/references/circuit_text_ref.txt
  test/python/visualization/test_circuit_text_drawer.py
Labels: automerge

#4243 Use isometry for decomposition of 3+ qubit unitary gates
  qiskit/extensions/quantum_initializer/isometry.py
  qiskit/extensions/unitary.py
  test/python/circuit/test_unitary.py
  test/python/transpiler/test_unroll_3q_or_more.py
Labels: automerge

#4263 Transpiling with basis_gates=None disables unrolling
  qiskit/compiler/transpile.py
  qiskit/transpiler/passes/basis/unroller.py
  releasenotes/notes/transpiling_basis_none-b2f1abdb3c080eca.yaml
  test/python/transpiler/test_preset_passmanagers.py
Labels: Changelog: Bugfix, automerge

#4268 Permutation removed from boolean and promoted to in decompose order
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/boolean_logic.py
  qiskit/circuit/library/generalized_gates/__init__.py
  qiskit/circuit/library/generalized_gates/permutation.py
  test/python/circuit/test_library.py
Labels: automerge

#4254 Add missing __init__.py file from dagcircuit tests
  test/python/dagcircuit/__init__.py
  test/python/dagcircuit/test_compose.py
  test/python/dagcircuit/test_dagcircuit.py
Labels: automerge

#4261 Add pip caching to azure pipelines jobs
  azure-pipelines.yml
Labels: automerge

#4275 fix rxx, ryy, rzz docs
  qiskit/extensions/__init__.py
  qiskit/extensions/standard/rxx.py
  qiskit/extensions/standard/ryy.py
  qiskit/extensions/standard/rzz.py
Labels: automerge

#4156 Floating-point error in weyl_coordinates
  qiskit/quantum_info/synthesis/weyl.py
  test/python/transpiler/test_consolidate_blocks.py
Labels: automerge

#4276 pi_check in qasm and truncate floats
  qiskit/circuit/instruction.py
  qiskit/circuit/tools/__init__.py
  qiskit/circuit/tools/pi_check.py
  qiskit/visualization/latex.py
  qiskit/visualization/matplotlib.py
  qiskit/visualization/text.py
  test/python/circuit/test_circuit_qasm.py
  test/python/circuit/test_tools.py
  test/python/circuit/test_unitary.py
Labels: automerge

#4287 Fix bug in random_clifford
  qiskit/quantum_info/operators/symplectic/random.py
  releasenotes/notes/fix-random-clifford-cff2b266c8ad7e2d.yaml
Labels: Changelog: Bugfix, automerge

#4218 controlled gates label awareness
  qiskit/circuit/add_control.py
  qiskit/extensions/standard/h.py
  qiskit/extensions/standard/ms.py
  qiskit/extensions/standard/rx.py
  qiskit/extensions/standard/ry.py
  qiskit/extensions/standard/rz.py
  qiskit/extensions/standard/swap.py
  qiskit/extensions/standard/u1.py
  qiskit/extensions/standard/u3.py
  qiskit/extensions/standard/x.py
  qiskit/extensions/standard/y.py
  qiskit/extensions/standard/z.py
  test/python/circuit/test_controlled_gate.py
Labels: Changelog: Bugfix, automerge

#4222 Add Cifford.from_label method
  qiskit/quantum_info/operators/symplectic/clifford.py
  releasenotes/notes/clifford-from-label-4ac8a987109916ef.yaml
  test/python/quantum_info/operators/symplectic/test_clifford.py
Labels: Changelog: New Feature, automerge

#4147 Refactor: timeslots
  qiskit/pulse/instructions/instruction.py
  qiskit/pulse/interfaces.py
  qiskit/pulse/reschedule.py
  qiskit/pulse/schedule.py
  qiskit/pulse/timeslots.py
  test/python/pulse/test_reschedule.py
  test/python/pulse/test_schedule.py
  test/python/pulse/test_timeslots.py
  test/python/qobj/test_pulse_converter.py
Labels: automerge, performance

#4114 #3891 | PulseCompression
  qiskit/assembler/assemble_schedules.py
  qiskit/pulse/pulse_lib/sample_pulse.py
  qiskit/pulse/reschedule.py
  releasenotes/notes/compress-indentical-pulses-cd20e82e1525b9f8.yaml
  test/python/pulse/test_reschedule.py
Labels: Changelog: New Feature, automerge, performance

#4294 Typo in RYGate docstring
  qiskit/extensions/standard/ry.py
Labels: automerge

#4274 Support for cregbundle in text circuit drawer
  qiskit/circuit/quantumcircuit.py
  qiskit/visualization/circuit_visualization.py
  qiskit/visualization/text.py
  test/python/visualization/test_circuit_text_drawer.py
  test/python/visualization/test_circuit_visualization_output.py
Labels: automerge

#4211 N-local circuits for circuit library
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/blueprintcircuit.py
  qiskit/circuit/library/data_encoding/__init__.py
  qiskit/circuit/library/data_encoding/first_order_expansion.py
  qiskit/circuit/library/data_encoding/pauli_expansion.py
  qiskit/circuit/library/data_encoding/second_order_expansion.py
  qiskit/circuit/library/n_local/__init__.py
  qiskit/circuit/library/n_local/n_local.py
  qiskit/circuit/library/n_local/ry.py
  qiskit/circuit/library/n_local/ryrz.py
  qiskit/circuit/library/n_local/swaprz.py
  qiskit/circuit/library/n_local/two_local.py
  qiskit/circuit/parametervector.py
  test/python/circuit/test_library.py
Labels: automerge

#4203 Correct typo in changelog
  releasenotes/notes/introduce-hamiltonian-gate-5c51bb576706cee9.yaml
Labels: automerge

#4223 Optimize initialization of Statevector and DensityMatrix classes
  qiskit/quantum_info/states/densitymatrix.py
  qiskit/quantum_info/states/quantum_state.py
  qiskit/quantum_info/states/statevector.py
  releasenotes/notes/statevector-init-91805b2f81f8e8c1.yaml
Labels: automerge, performance

#4232 Don't iterate over parameter table on circuit.parameters()
  qiskit/circuit/parametertable.py
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_parameters.py
Labels: automerge, performance

#4028 Multi-control multi-target gate
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/generalized_gates/__init__.py
  qiskit/circuit/library/generalized_gates/mcmt.py
  test/python/circuit/test_library.py
Labels: automerge

#4259 Circuit library: GraphState, HLF
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/graph_state.py
  qiskit/circuit/library/hidden_linear_function.py
  qiskit/circuit/quantumcircuit.py
  qiskit/extensions/unitary.py
Labels: automerge

#4330 Add new fake backends FakeAthens and FakeRome
  qiskit/test/mock/backends/__init__.py
  qiskit/test/mock/backends/athens/__init__.py
  qiskit/test/mock/backends/athens/conf_athens.json
  qiskit/test/mock/backends/athens/defs_athens.json
  qiskit/test/mock/backends/athens/fake_athens.py
  qiskit/test/mock/backends/athens/props_athens.json
  qiskit/test/mock/backends/rome/__init__.py
  qiskit/test/mock/backends/rome/conf_rome.json
  qiskit/test/mock/backends/rome/fake_rome.py
  qiskit/test/mock/backends/rome/props_rome.json
  qiskit/test/mock/fake_provider.py
Labels: automerge

#4332 Circuit compose() is compatible with append()
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/circuit-compose-c320c4057cd2bb8f.yaml
  test/python/circuit/test_compose.py
Labels: automerge

#4269 making the qv use permutation -- needs pr #4268
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/generalized_gates/permutation.py
  qiskit/circuit/library/quantum_volume.py
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_compose.py
  test/python/circuit/test_library.py
Labels: automerge

#4337 moving readme away from execute
  README.md
Labels: automerge

#4327 Fix to_dict() bugs and add script to update fake backends
  qiskit/providers/models/backendconfiguration.py
  qiskit/providers/models/backendproperties.py
  tools/update_fake_backends.py
Labels: automerge

#4336 Circuit library widget style updates
  qiskit/tools/jupyter/library.py
Labels: automerge

#4295 remove debugging set_printoptions in test_controlled_gate.py
  test/python/circuit/test_controlled_gate.py
Labels: automerge

#4321 set default draw(cregbundle=False)
  qiskit/circuit/quantumcircuit.py
  qiskit/visualization/circuit_visualization.py
Labels: automerge

#4344 Remove conditional execution for jobs in azure-pipelines
  azure-pipelines.yml
Labels: automerge

#4262 text-draw gates when are controlled and with a label
  qiskit/visualization/text.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: Changelog: Bugfix, automerge

#4266 Iqp circuit added to circuit library
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/iqp.py
  releasenotes/notes/added-to-circuit-library-iqp-circuits-c193be67dae6ea48.yaml
  test/python/circuit/test_library.py
Labels: automerge

#4319 QuantumCircuit.data modification methods to reset ParameterTable.
  qiskit/circuit/library/basis_change/qft.py
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/4235-to_instruction-call-throws-error-on-parametrized-inverted-circuit-acf38e3ddd111900.yaml
  test/python/circuit/test_parameters.py
Labels: Changelog: Bugfix, automerge

#4322 fixed issue 4292 by updating latex drawer
  qiskit/visualization/latex.py
Labels: Changelog: Bugfix, automerge

#4323 Optimize init order of PauliTable
  qiskit/quantum_info/operators/symplectic/pauli_table.py
Labels: automerge, performance

#4325 Remove unnecessary use of Pauli and basis_states in tests
  test/python/basicaer/test_multi_registers_convention.py
  test/python/quantum_info/test_synthesis.py
Labels: automerge

#4331 missing pass_manager_drawer(..., filename=None)
  qiskit/visualization/pass_manager_visualization.py
Labels: Changelog: Bugfix, automerge

#4347 unnecessary import in UnitaryGate.control
  qiskit/extensions/unitary.py
Labels: automerge

#4333 Global MS gate in circuit library
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/generalized_gates/__init__.py
  qiskit/circuit/library/generalized_gates/gms.py
  test/python/circuit/test_library.py
Labels: automerge

#4341 split boolean logic library into files
  qiskit/circuit/library/boolean_logic.py
  qiskit/circuit/library/boolean_logic/__init__.py
  qiskit/circuit/library/boolean_logic/inner_product.py
  qiskit/circuit/library/boolean_logic/quantum_and.py
  qiskit/circuit/library/boolean_logic/quantum_or.py
  qiskit/circuit/library/boolean_logic/quantum_xor.py
Labels: automerge

#4318 Renamings in circuit/library/data_encoding
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/data_preparation/__init__.py
  qiskit/circuit/library/data_preparation/pauli_feature_map.py
  qiskit/circuit/library/data_preparation/z_feature_map.py
  qiskit/circuit/library/data_preparation/zz_feature_map.py
  qiskit/circuit/library/n_local/__init__.py
  qiskit/circuit/library/n_local/efficient_su2.py
  qiskit/circuit/library/n_local/excitation_preserving.py
  qiskit/circuit/library/n_local/real_amplitudes.py
  qiskit/circuit/library/n_local/ry.py
  qiskit/circuit/library/n_local/ryrz.py
  test/python/circuit/test_library.py
Labels: automerge

#4297 Update to new NumPy RNG
  examples/python/stochastic_swap.py
  qiskit/circuit/library/boolean_logic/quantum_xor.py
  qiskit/circuit/library/generalized_gates/permutation.py
  qiskit/circuit/library/quantum_volume.py
  qiskit/circuit/random/utils.py
  qiskit/quantum_info/operators/pauli.py
  qiskit/quantum_info/operators/random.py
  qiskit/quantum_info/operators/symplectic/random.py
  qiskit/quantum_info/states/quantum_state.py
  qiskit/quantum_info/states/random.py
  qiskit/quantum_info/synthesis/two_qubit_decompose.py
  qiskit/quantum_info/synthesis/weyl.py
  qiskit/transpiler/passes/routing/algorithms/token_swapper.py
  qiskit/transpiler/passes/routing/algorithms/util.py
  qiskit/transpiler/passes/routing/cython/stochastic_swap/swap_trial.pyx
  qiskit/transpiler/passes/routing/layout_transformation.py
  qiskit/transpiler/passes/routing/stochastic_swap.py
  requirements.txt
  setup.py
  test/python/quantum_info/operators/symplectic/test_clifford.py
  test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
  test/python/quantum_info/operators/test_operator.py
  test/python/quantum_info/states/test_densitymatrix.py
  test/python/quantum_info/states/test_statevector.py
  test/python/transpiler/test_stochastic_swap.py
Labels: automerge

#4356 Fix deprecations coming from circuit.OR
  qiskit/circuit/library/arithmetic/integer_comparator.py
Labels: automerge

#4277 fix deprecation warnings from dag.compose
  qiskit/transpiler/layout.py
  qiskit/transpiler/passes/routing/basic_swap.py
  qiskit/transpiler/passes/routing/stochastic_swap.py
  releasenotes/notes/deprecate-combine-from-edge-b2884a5d124d36af.yaml
Labels: automerge

#4335 Timeslot error fix and tests
  qiskit/pulse/schedule.py
  test/python/pulse/test_schedule.py
Labels: automerge, priority: high

#4289 Add ``from_int`` method to ``Statevector`` and ``DensityMatrix``
  qiskit/quantum_info/states/densitymatrix.py
  qiskit/quantum_info/states/statevector.py
  releasenotes/notes/quantum-state-from-int-20a91dc5d4c62dbb.yaml
  test/python/quantum_info/states/test_densitymatrix.py
  test/python/quantum_info/states/test_statevector.py
Labels: Changelog: New Feature, automerge

#4328 Reverts #4207: allow setting label on circuit append
  qiskit/circuit/library/blueprintcircuit.py
  qiskit/circuit/library/generalized_gates/permutation.py
  qiskit/circuit/library/iqp.py
  qiskit/circuit/library/quantum_volume.py
  qiskit/circuit/quantumcircuit.py
  qiskit/visualization/matplotlib.py
  releasenotes/notes/circuit-append-gate-label-6adba4c3fa6b308f.yaml
Labels: automerge

#4360 spelling error: s/symetric/symmetric in circuit/library/iqp.py
  qiskit/circuit/library/iqp.py
Labels: automerge

#4364 Bump version string post release
  .mergify.yml
  docs/conf.py
  qiskit/VERSION.txt
  setup.py
Labels: automerge

#4366 Fix import of deprecated gates from qiskit.extensions
  qiskit/circuit/library/standard_gates/__init__.py
  test/python/circuit/test_controlled_gate.py
Labels: Changelog: Bugfix, automerge, stable backport potential
