Repository Qiskit/qiskit, pull requests merged in 2020-05, with the labels that each got.

#4351 Shaded barrier only along dotted line in mpl drawer
  qiskit/visualization/matplotlib.py
Labels: automerge

#4196 Add EquivalenceLibrary.draw() method.
  qiskit/circuit/equivalence.py
Labels: Changelog: New Feature, automerge

#4380 Actually update pip cache on each run
  azure-pipelines.yml
Labels: automerge

#3827 MPL circuit drawer cannot handle multiple super/sub script commands in register name
  qiskit/visualization/matplotlib.py
Labels: Changelog: Bugfix

#4363 Run lint in the example files
  Makefile
  examples/python/commutation_relation.py
  examples/python/load_qasm.py
  examples/python/rippleadd.py
  examples/python/stochastic_swap.py
  examples/python/using_qiskit_terra_level_0.py
Labels: automerge

#4134 Add supplementary information to transpiler module
  docs/source_images/mapping.png
  docs/source_images/transpiling_core_steps.png
  qiskit/transpiler/__init__.py
Labels: automerge, type: documentation

#4233 Add delay instruction to assemble schedules and disassemble
  qiskit/qobj/converters/pulse_instruction.py
  test/python/qobj/test_pulse_converter.py
Labels: automerge

#4359 Add shift frequency qobj instruction - `shiftf` to schema
  qiskit/schemas/examples/qobj_openpulse_example.json
  qiskit/schemas/qobj_schema.json
Labels: automerge

#4394 Add __len__ to Schedule in Pulse along with related tests.
  qiskit/pulse/schedule.py
  test/python/pulse/test_schedule.py
Labels: automerge

#4200 Add support for substituting Parameter with ParameterExpression
  qiskit/circuit/parameterexpression.py
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/support-substituting-parameterexpression-5f140ba243ba126a.yaml
  test/python/circuit/test_parameters.py
Labels: Changelog: New Feature, automerge

#3797 #3312 | Large Pulse backend mock
  qiskit/test/mock/utils/__init__.py
  qiskit/test/mock/utils/configurable_backend.py
  releasenotes/notes/configurable-backend-af0623b43bdcc35e.yaml
  test/mock/__init__.py
  test/mock/test_configurable_backend.py
  test/mock/test_fake_backends.py
Labels: automerge

#4385 Remove sympy usage in polynomial_pauli_rotations
  qiskit/circuit/library/arithmetic/polynomial_pauli_rotations.py
Labels: automerge

#4403 Fix bug in visualization/pulse/matplotlib
  qiskit/visualization/pulse/matplotlib.py
Labels: automerge, stable backport potential

#4407 Unblock CI with fix for new jupyter execute and pin ddt
  docs/conf.py
  requirements-dev.txt
Labels: automerge

#4030 Remove marshmallow from result/ and requirements
  qiskit/result/models.py
  qiskit/result/postprocess.py
  qiskit/result/result.py
  qiskit/result/utils.py
  qiskit/validation/__init__.py
  qiskit/validation/base.py
  qiskit/validation/exceptions.py
  qiskit/validation/fields/__init__.py
  qiskit/validation/fields/containers.py
  qiskit/validation/fields/custom.py
  qiskit/validation/fields/polymorphic.py
  qiskit/validation/validate.py
  releasenotes/notes/remove-marshmallow-validation-283fa62b3acc51e4.yaml
  requirements.txt
  setup.py
  test/python/result/test_result.py
  test/python/validation/__init__.py
  test/python/validation/test_custom_fields.py
  test/python/validation/test_fields.py
  test/python/validation/test_models.py
  test/python/validation/test_schemas.py
  test/python/validation/test_validators.py
Labels: automerge

#4408 Add paris coupling map
  qiskit/visualization/gate_map.py
Labels: automerge, stable backport potential

#4400 New slack invitation link
  README.md
Labels: automerge

#4412 Handle aer's current return format
  qiskit/result/postprocess.py
Labels: automerge

#4398 Wrong error message in StochasticSwap
  qiskit/transpiler/passes/routing/stochastic_swap.py
Labels: automerge

#4345 Allow bypassing parallel mode at init
  qiskit/tools/parallel.py
Labels: Changelog: Bugfix, automerge

#4251 Rename rescheduler to transform
  qiskit/assembler/assemble_schedules.py
  qiskit/pulse/__init__.py
  qiskit/pulse/reschedule.py
  qiskit/pulse/transforms.py
  releasenotes/notes/rename-rescheduler-d4210a234714ed5d.yaml
  test/python/pulse/test_transforms.py
Labels: Changelog: API Change, automerge

#4387 Allow transformation passes to modify the property set
  qiskit/transpiler/runningpassmanager.py
  releasenotes/notes/transformationpass_propertyset-3d1d9aedad9860be.yaml
  test/python/transpiler/test_pass_scheduler.py
Labels: automerge

#4416 [Stable] Unblock CI with fix for new jupyter execute and pin ddt (#4407)
  docs/conf.py
  requirements-dev.txt
Labels: automerge, stable-backport

#4419 Replace eight spaces with a tab in Makefile.
  Makefile
Labels: automerge

#4409 Add missing T gate to Sphinx
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/standard_gates/__init__.py
Labels: automerge, stable backport potential

#4430 pycodestyle 2.6.0
  qiskit/extensions/quantum_initializer/isometry.py
  qiskit/providers/models/backendconfiguration.py
Labels: automerge

#4429 Label support for controlled unitary
  qiskit/extensions/unitary.py
Labels: Changelog: Bugfix, automerge

#4399 Bugfix: Hz -> GHz conversion for SetFrequency -> PulseQobjInstruction
  qiskit/qobj/converters/pulse_instruction.py
  releasenotes/notes/bugfix-set-frequency-29608d213a8cbece.yaml
  test/python/qobj/test_pulse_converter.py
  test/python/qobj/test_qobj.py
Labels: Changelog: Bugfix, automerge, stable backport potential

#4384 Update qsphere plots to show state labels and phases
  qiskit/visualization/state_visualization.py
  releasenotes/notes/qsphere-state-display-819cc1e3e61314a2.yaml
Labels: automerge

#4431 Add equivalence_library kwarg to circuit_to_{gate,inst} converters.
  qiskit/converters/circuit_to_gate.py
  qiskit/converters/circuit_to_instruction.py
  releasenotes/notes/converters-equivalence-library-registration-optional-266758d497d82ce3.yaml
  test/python/circuit/test_equivalence.py
Labels: automerge

#4433 add DensityMatrix.to_statevector() for pure states
  qiskit/quantum_info/states/densitymatrix.py
  test/python/quantum_info/states/test_densitymatrix.py
Labels: automerge

#4432 Add init qubits flag to qobj
  qiskit/compiler/assemble.py
  qiskit/execute.py
  qiskit/schemas/examples/qobj_openpulse_example.json
  qiskit/schemas/examples/qobj_openqasm_example.json
  qiskit/schemas/qobj_schema.json
  releasenotes/notes/add-init-qubits-option-ea1844f88fcddcf6.yaml
  test/python/compiler/test_assembler.py
Labels: Changelog: New Feature, automerge

#4390 Add ShiftFrequency instruction to pulse
  qiskit/pulse/__init__.py
  qiskit/pulse/instructions/__init__.py
  qiskit/pulse/instructions/frequency.py
  qiskit/qobj/converters/pulse_instruction.py
  qiskit/visualization/pulse/matplotlib.py
  releasenotes/notes/implement-shift-frequency-46d4ea16d8be2f58.yaml
  test/python/pulse/test_schedule.py
  test/python/qobj/test_pulse_converter.py
  test/python/qobj/test_qobj.py
  test/python/visualization/test_pulse_visualization_output.py
Labels: Changelog: New Feature, automerge

#4468 Circuit library NLocal string circuit drawer issue
  qiskit/circuit/library/n_local/n_local.py
Labels: Changelog: Bugfix, automerge

#4465 Add support for reset to Statevector.from_instruction
  qiskit/quantum_info/states/densitymatrix.py
  qiskit/quantum_info/states/statevector.py
  releasenotes/notes/statevector-reset-3c819d1e2d598cc4.yaml
  test/python/quantum_info/states/test_densitymatrix.py
  test/python/quantum_info/states/test_statevector.py
Labels: automerge

#4402 Fix disassemble of isometry and added test_disassemble_isometry
  qiskit/assembler/disassemble.py
  test/python/compiler/test_disassembler.py
Labels: automerge

#4424 Move test/mock into proper namespace for discovery
  test/python/mock/__init__.py
  test/python/mock/test_configurable_backend.py
  test/python/mock/test_fake_backends.py
Labels: automerge

#4471 simplify codeowners
  .github/CODEOWNERS
Labels: automerge

#4422 Add ability to run tests with pytest to make
  Makefile
Labels: automerge, type: enhancement

#4165 fixed issue 4133 by updating U3 and U2 definitions
  qiskit/circuit/library/standard_gates/u2.py
  qiskit/circuit/library/standard_gates/u3.py
Labels: automerge, stable backport potential

#4255 Add from_networkx method to DAGCircuit class
  qiskit/dagcircuit/dagcircuit.py
  releasenotes/notes/add-dagcircuit-from-networkx-7815b9c575232b14.yaml
  test/python/dagcircuit/test_dagcircuit.py
Labels: Changelog: New Feature, automerge

#4420 Displaying a control gate as a labeled bullet instead of a multibox.
  qiskit/visualization/text.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: automerge

#4472 Fix #4445 | Bug in scheduler if circuit is empty
  qiskit/scheduler/methods/basic.py
  test/python/scheduler/test_basic_scheduler.py
Labels: Changelog: Bugfix, automerge, stable backport potential

#4475 Removing RemoveResetInZeroState from transpiler optimization level 0
  qiskit/transpiler/preset_passmanagers/level0.py
  releasenotes/notes/level0_RemoveResetInZeroState-942c0fb19cb6c087.yaml
  test/python/transpiler/test_preset_passmanagers.py
Labels: automerge

#4480 improve floating point precision in backend properties
  qiskit/providers/models/backendproperties.py
  test/python/providers/test_backendproperties.py
Labels: automerge

#4477 Enable parallel docs builds and bump reno min version
  requirements-dev.txt
  tox.ini
Labels: automerge

#3581 Add DAGDependency
  qiskit/converters/__init__.py
  qiskit/converters/circuit_to_dagdependency.py
  qiskit/converters/dag_to_dagdependency.py
  qiskit/converters/dagdependency_to_circuit.py
  qiskit/converters/dagdependency_to_dag.py
  qiskit/dagcircuit/__init__.py
  qiskit/dagcircuit/dagdependency.py
  qiskit/dagcircuit/dagdepnode.py
  qiskit/dagcircuit/exceptions.py
  qiskit/transpiler/passes/basis/decompose.py
  qiskit/visualization/dag_visualization.py
  releasenotes/notes/Add-canonical-form-47e0466ed57640f3.yaml
  test/python/converters/test_circuit_to_dagdependency.py
  test/python/converters/test_dag_to_dagdependency.py
  test/python/dagcircuit/test_dagdependency.py
Labels: automerge

#4410 fixed issue 4291 by adding support for cregbundle in latex drawer
  qiskit/circuit/quantumcircuit.py
  qiskit/visualization/circuit_visualization.py
  qiskit/visualization/latex.py
Labels: Changelog: API Change

#4486 Issue 4161 - TypeError issue for keyword argument in Parameter
  qiskit/circuit/parameter.py
  test/python/circuit/test_parameters.py
Labels: automerge

#4503 Remove circuit_instruction_map deprecated attribute
  qiskit/providers/models/pulsedefaults.py
  releasenotes/notes/remove-circuit-instruction-map-37fb34c3b5fe033c.yaml
Labels: Changelog: Removal, automerge

#4492 Added test for hidden_linear_function.py
  test/python/circuit/test_library.py
Labels: automerge

#4354 revert computing matrix for trivial matrices
  qiskit/circuit/library/standard_gates/h.py
  qiskit/circuit/library/standard_gates/swap.py
  qiskit/circuit/library/standard_gates/y.py
Labels: automerge

#4499 Correct typo in deprecation warning
  qiskit/quantum_info/synthesis/two_qubit_decompose.py
Labels: automerge

#4482 [Stable] Use FakeProvider for jupyter and monitor tests (#4296)
  CONTRIBUTING.md
  qiskit/test/mock/__init__.py
  qiskit/test/mock/fake_provider.py
  qiskit/tools/jupyter/backend_overview.py
  qiskit/tools/jupyter/job_watcher.py
  qiskit/tools/monitor/__init__.py
  qiskit/tools/monitor/overview.py
  test/python/tools/jupyter/test_notebooks.py
  test/python/tools/monitor/test_backend_monitor.py
Labels: automerge

#4487 Fix the circuit gate links in docs
  qiskit/circuit/quantumcircuit.py
Labels: automerge

#4511 Restrict hello_quantum ibmq example script to backends with at least two qubits
  examples/python/ibmq/hello_quantum.py
Labels: automerge

#4513 Fix infinite recursion in controlled gate definition
  qiskit/circuit/controlledgate.py
  test/python/circuit/test_controlled_gate.py
Labels: Changelog: Bugfix, automerge, stable backport potential

#4516 Revert "Fix infinite recursion in controlled gate definition (#4513)"
  qiskit/circuit/controlledgate.py
  test/python/circuit/test_controlled_gate.py
Labels: automerge

#4521 Add circuit.repeat
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/circuit-repeat-8db21ef8d8c21cda.yaml
  test/python/circuit/test_circuit_operations.py
  test/python/circuit/test_parameters.py
Labels: Changelog: New Feature
