Repository Qiskit/qiskit, pull requests merged in 2020-01, with the labels that each got.

#3662 Document `Bit.index` and `Bit.register`
  qiskit/circuit/classicalregister.py
  qiskit/circuit/quantumregister.py
Labels: automerge

#3672 Fix ``Operator.transpose`` for rectangular operators
  qiskit/quantum_info/operators/operator.py
  test/python/quantum_info/operators/test_operator.py
Labels: Changelog: Bugfix, automerge

#3424 Updates draw method scale parameter: SamplePulse, Schedule
  qiskit/pulse/commands/instruction.py
  qiskit/pulse/commands/sample_pulse.py
  qiskit/pulse/schedule.py
  qiskit/visualization/pulse/matplotlib.py
  qiskit/visualization/pulse_visualization.py
  releasenotes/notes/update-scaling-draw-option-7f28e83ff3e3939f.yaml
Labels: automerge

#3666 Visualizers properly represent complex numbers
  qiskit/visualization/tools/pi_check.py
  releasenotes/notes/fix3640-70e912031815d09a.yaml
  test/python/visualization/test_circuit_text_drawer.py
Labels: Changelog: Bugfix, automerge

#3687 Update deprecated call to cmd_qubits in the rescheduler
  qiskit/pulse/reschedule.py
  test/python/scheduler/test_basic_scheduler.py
Labels: automerge

#3597 Fix bug where lo units were not being properly converted
  qiskit/assembler/assemble_schedules.py
  qiskit/compiler/assemble.py
  qiskit/execute.py
  qiskit/providers/models/backendconfiguration.py
  qiskit/qobj/converters/lo_config.py
  test/python/compiler/test_assembler.py
  test/python/qobj/test_pulse_converter.py
Labels: Changelog: Bugfix, automerge, bug, priority: high, stable backport potential

#3686 [Stable] Replace scipy.kron with numpy.kron in quantum_initializer. (#3623)
  qiskit/extensions/quantum_initializer/initializer.py
Labels: stable backport potential

#3691 Pin nbformat to 4.4.0
  constraints.txt
Labels: stable backport potential

#3680 [Stable] Add one time warnings for dt and qubit_freq_est turn into properties
  qiskit/providers/models/backendconfiguration.py
  qiskit/providers/models/pulsedefaults.py
Labels: stable backport potential

#3635 Bump pylint version to unify across elements
  .pylintrc
  constraints.txt
  qiskit/assembler/assemble_schedules.py
  qiskit/converters/ast_to_dag.py
  qiskit/dagcircuit/dagcircuit.py
  qiskit/extensions/quantum_initializer/isometry.py
  qiskit/extensions/standard/barrier.py
  qiskit/extensions/standard/multi_control_rotation_gates.py
  qiskit/extensions/standard/multi_control_toffoli_gate.py
  qiskit/pulse/timeslots.py
  qiskit/quantum_info/operators/channel/chi.py
  qiskit/quantum_info/operators/channel/choi.py
  qiskit/quantum_info/operators/channel/kraus.py
  qiskit/quantum_info/operators/channel/ptm.py
  qiskit/quantum_info/operators/channel/superop.py
  qiskit/quantum_info/operators/channel/transformations.py
  qiskit/quantum_info/operators/pauli.py
  qiskit/quantum_info/operators/predicates.py
  qiskit/quantum_info/synthesis/one_qubit_decompose.py
  qiskit/test/decorators.py
  qiskit/tools/jupyter/jupyter_magics.py
  qiskit/tools/qi/qi.py
  qiskit/transpiler/coupling.py
  qiskit/transpiler/layout.py
  qiskit/transpiler/passes/crosstalk_adaptive_schedule.py
  qiskit/transpiler/passes/mapping/noise_adaptive_layout.py
  qiskit/transpiler/passes/unroller.py
  qiskit/transpiler/passmanager.py
  qiskit/transpiler/synthesis/graysynth.py
  qiskit/visualization/bloch.py
  qiskit/visualization/circuit_visualization.py
  qiskit/visualization/state_visualization.py
  qiskit/visualization/text.py
  test/python/circuit/test_parameters.py
  test/python/compiler/test_assembler.py
  test/python/quantum_info/test_pauli.py
  test/python/test_dagcircuit.py
  test/python/transpiler/test_collect_2q_blocks.py
Labels: automerge

#3696 [Stable] Fix bug where lo units were not being properly converted (#3597)
  qiskit/assembler/assemble_schedules.py
  qiskit/compiler/assemble.py
  qiskit/execute.py
  qiskit/providers/models/backendconfiguration.py
  qiskit/qobj/converters/lo_config.py
  test/python/compiler/test_assembler.py
  test/python/qobj/test_pulse_converter.py
Labels: stable-backport

#3681 [Stable] Fixes issue 3607 (#3642)
  qiskit/visualization/matplotlib.py
Labels: stable-backport

#3675 Fixed issue 3673
  qiskit/converters/ast_to_dag.py
  qiskit/qasm/libs/qelib1.inc
  test/python/test_qasm_parser.py
Labels: automerge

#3694 Assemble meas levels validation
  qiskit/compiler/assemble.py
  test/python/compiler/test_assembler.py
Labels: Changelog: API Change, automerge, type: enhancement

#3701 Fixup bug where name isnt maintained by align_measures
  qiskit/pulse/reschedule.py
  test/python/pulse/test_reschedule.py
Labels: automerge

#3708 Increase job watcher cancel button width.
  qiskit/tools/jupyter/job_widgets.py
Labels: Changelog: Bugfix, automerge

#3606 Make assemble() respect max_shots
  qiskit/compiler/assemble.py
  releasenotes/notes/respect-max-shots-a6f8ac0d88040f42.yaml
  test/python/compiler/test_assembler.py
Labels: Changelog: API Change, automerge

#3702 Update schemas for parametric pulses
  qiskit/schemas/backend_configuration_schema.json
  qiskit/schemas/examples/backend_configuration_openpulse_example.json
  qiskit/schemas/examples/qobj_openpulse_example.json
  qiskit/schemas/qobj_schema.json
Labels: automerge

#3716 Remove outdated code from when backend defaults wasn't done
  qiskit/compiler/assemble.py
Labels: automerge

#3717 Deprecate circuit_instruction_map, rename it to instruction_schedule_…
  qiskit/compiler/schedule.py
  qiskit/providers/models/pulsedefaults.py
  qiskit/pulse/cmd_def.py
  releasenotes/notes/circuit_instruction_map-rename-d011d5cc34d16b7b.yaml
  test/python/providers/test_pulse_defaults.py
  test/python/pulse/test_instruction_schedule_map.py
  test/python/pulse/test_reschedule.py
  test/python/scheduler/test_basic_scheduler.py
Labels: Changelog: Deprecation

#3715 Use raw literals in strings
  qiskit/visualization/utils.py
  test/python/visualization/test_visualization.py
Labels: automerge

#3620 Parametric Pulses
  .pylintrc
  qiskit/assembler/assemble_schedules.py
  qiskit/compiler/assemble.py
  qiskit/providers/models/pulsedefaults.py
  qiskit/pulse/__init__.py
  qiskit/pulse/commands/__init__.py
  qiskit/pulse/commands/parametric_pulses.py
  qiskit/pulse/commands/pulse_command.py
  qiskit/pulse/commands/sample_pulse.py
  qiskit/pulse/pulse_lib/continuous.py
  qiskit/pulse/pulse_lib/discrete.py
  qiskit/pulse/pulse_lib/samplers/decorators.py
  qiskit/qobj/converters/pulse_instruction.py
  qiskit/qobj/models/pulse.py
  qiskit/validation/fields/custom.py
  qiskit/visualization/pulse/matplotlib.py
  releasenotes/notes/add-parametric-pulses-51184457faf31053.yaml
  test/python/compiler/test_assembler.py
  test/python/pulse/test_commands.py
  test/python/pulse/test_discrete_pulses.py
  test/python/pulse/test_schedule.py
  test/python/qobj/test_pulse_converter.py
  test/python/scheduler/test_basic_scheduler.py
  test/python/visualization/references/parametric_matplotlib_ref.png
  test/python/visualization/test_pulse_visualization_output.py
Labels: automerge

#3734 Fix error message for shots exceeding max_shots
  qiskit/compiler/assemble.py
Labels: automerge

#3657 Run dense layout if trivial layout is not perfect at level 1
  qiskit/transpiler/passes/layout/noise_adaptive_layout.py
  qiskit/transpiler/preset_passmanagers/level1.py
  releasenotes/notes/level1_trivial_dense_layout-7b6be7221b18af0c.yaml
  test/python/transpiler/test_preset_passmanagers.py
Labels: Changelog: API Change, automerge

#3665 Fix ``partial_trace`` to work with ``Statevector`` and ``DensityMatrix`` classes
  qiskit/quantum_info/__init__.py
  qiskit/quantum_info/states/__init__.py
  qiskit/quantum_info/states/densitymatrix.py
  qiskit/quantum_info/states/utils.py
  qiskit/tools/qi/qi.py
  releasenotes/notes/partial-trace-87fd0ef50196a308.yaml
  test/python/quantum_info/states/test_utils.py
Labels: Changelog: Deprecation, Changelog: New Feature

#3670 fix ``state_fidelity`` to work with ``Statevector`` and ``DensityMatrix`` classes
  qiskit/quantum_info/__init__.py
  qiskit/quantum_info/states/__init__.py
  qiskit/quantum_info/states/measures.py
  qiskit/quantum_info/states/utils.py
  test/python/quantum_info/test_states.py
Labels: automerge

#3740 Add ``dot`` method to operator classes
  qiskit/quantum_info/operators/base_operator.py
  qiskit/quantum_info/operators/channel/chi.py
  qiskit/quantum_info/operators/channel/choi.py
  qiskit/quantum_info/operators/channel/kraus.py
  qiskit/quantum_info/operators/channel/ptm.py
  qiskit/quantum_info/operators/channel/quantum_channel.py
  qiskit/quantum_info/operators/channel/stinespring.py
  qiskit/quantum_info/operators/channel/superop.py
  qiskit/quantum_info/operators/operator.py
  releasenotes/notes/operator-dot-fd90e7e5ad99ff9b.yaml
  test/python/quantum_info/operators/channel/test_chi.py
  test/python/quantum_info/operators/channel/test_choi.py
  test/python/quantum_info/operators/channel/test_kraus.py
  test/python/quantum_info/operators/channel/test_ptm.py
  test/python/quantum_info/operators/channel/test_stinespring.py
  test/python/quantum_info/operators/channel/test_superop.py
  test/python/quantum_info/operators/test_operator.py
Labels: Changelog: API Change, Changelog: Deprecation, automerge

#3743 Remove deprecated path to align_measures, add_implicit_acquires and p…
  qiskit/pulse/utils.py
Labels: automerge

#3744 Add Lauren Capelluto to the codeowners list for 'assembler/'
  .github/CODEOWNERS
Labels: automerge

#3674 fix ``purity`` function to work with ``Statevector`` and ``DensityMatrix`` classes
  qiskit/quantum_info/__init__.py
  qiskit/quantum_info/states/__init__.py
  qiskit/quantum_info/states/measures.py
  qiskit/quantum_info/states/states.py
  test/python/quantum_info/states/test_measures.py
  test/python/quantum_info/test_states.py
Labels: automerge

#3713 Added better pulse object representations
  qiskit/pulse/commands/acquire.py
  qiskit/pulse/commands/command.py
  qiskit/pulse/commands/frame_change.py
  qiskit/pulse/commands/instruction.py
  qiskit/pulse/commands/persistent_value.py
  qiskit/pulse/commands/sample_pulse.py
  qiskit/pulse/commands/snapshot.py
  qiskit/pulse/schedule.py
  releasenotes/notes/better-pulse-repr-9e5ba50649322b6b.yaml
  test/python/qobj/test_pulse_converter.py
Labels: automerge

#3574 #2262 | Acquire commands on a single qubit
  qiskit/assembler/assemble_schedules.py
  qiskit/pulse/commands/acquire.py
  qiskit/pulse/commands/instruction.py
  qiskit/pulse/reschedule.py
  qiskit/qobj/converters/pulse_instruction.py
  qiskit/scheduler/methods/basic.py
  releasenotes/notes/acquire-single-channel-ea83cef8d991f945.yaml
  test/python/compiler/test_assembler.py
  test/python/pulse/test_reschedule.py
  test/python/pulse/test_schedule.py
  test/python/qobj/test_pulse_converter.py
  test/python/scheduler/test_basic_scheduler.py
Labels: automerge, type: enhancement

#3181 Enable numpy array local simulator return types
  qiskit/providers/basicaer/qasm_simulator.py
  qiskit/providers/basicaer/unitary_simulator.py
  qiskit/result/models.py
  qiskit/validation/fields/__init__.py
  qiskit/validation/fields/containers.py
Labels: Changelog: API Change

#3756 Deprecate the PersistentValue instruction.
  qiskit/pulse/commands/persistent_value.py
  qiskit/qobj/converters/pulse_instruction.py
  releasenotes/notes/deprecate-persistent-value-command-4ec516a314197887.yaml
Labels: automerge

#3667 Include tests in sdist
  MANIFEST.in
Labels: automerge

#3754 add repr method for ParameterTable
  qiskit/circuit/parametertable.py
Labels: automerge

#3612 Change rep_time unit to s
  qiskit/compiler/assemble.py
  qiskit/providers/models/backendconfiguration.py
  releasenotes/notes/change-rep-time-unit-48533d8fe474a035.yaml
  test/python/compiler/test_assembler.py
  test/python/providers/test_backendconfiguration.py
Labels: automerge

#3758 Add entropy and entanglement state measures to quantum_info
  qiskit/quantum_info/__init__.py
  qiskit/quantum_info/states/__init__.py
  qiskit/quantum_info/states/measures.py
  qiskit/quantum_info/states/states.py
  qiskit/quantum_info/states/utils.py
  qiskit/tools/qi/qi.py
  releasenotes/notes/state-measures-f662a847d0db42b8.yaml
  test/python/quantum_info/states/test_measures.py
  test/python/quantum_info/states/test_utils.py
Labels: Changelog: API Change, Changelog: Deprecation

#3631 override `control` of standard gates where possible
  qiskit/circuit/add_control.py
  qiskit/converters/ast_to_dag.py
  qiskit/extensions/quantum_initializer/initializer.py
  qiskit/extensions/standard/__init__.py
  qiskit/extensions/standard/ccx.py
  qiskit/extensions/standard/ch.py
  qiskit/extensions/standard/crx.py
  qiskit/extensions/standard/cry.py
  qiskit/extensions/standard/crz.py
  qiskit/extensions/standard/cswap.py
  qiskit/extensions/standard/cu1.py
  qiskit/extensions/standard/cu3.py
  qiskit/extensions/standard/cx.py
  qiskit/extensions/standard/cy.py
  qiskit/extensions/standard/cz.py
  qiskit/extensions/standard/h.py
  qiskit/extensions/standard/ms.py
  qiskit/extensions/standard/r.py
  qiskit/extensions/standard/rx.py
  qiskit/extensions/standard/rxx.py
  qiskit/extensions/standard/ry.py
  qiskit/extensions/standard/rz.py
  qiskit/extensions/standard/rzz.py
  qiskit/extensions/standard/s.py
  qiskit/extensions/standard/swap.py
  qiskit/extensions/standard/t.py
  qiskit/extensions/standard/u1.py
  qiskit/extensions/standard/u2.py
  qiskit/extensions/standard/u3.py
  qiskit/extensions/standard/x.py
  qiskit/extensions/standard/y.py
  qiskit/extensions/standard/z.py
  qiskit/quantum_info/synthesis/two_qubit_decompose.py
  qiskit/transpiler/passes/utils/check_cx_direction.py
  test/python/circuit/test_controlled_gate.py
  test/python/circuit/test_instructions.py
  test/python/pickles/TestsBasicSwap_a_cx_to_map.pickle
  test/python/pickles/TestsBasicSwap_handle_measurement.pickle
  test/python/pickles/TestsBasicSwap_initial_layout.pickle
  test/python/pickles/TestsLookaheadSwap_a_cx_to_map.pickle
  test/python/pickles/TestsLookaheadSwap_handle_measurement.pickle
  test/python/pickles/TestsLookaheadSwap_initial_layout.pickle
  test/python/pickles/TestsStochasticSwap_a_cx_to_map.pickle
  test/python/pickles/TestsStochasticSwap_handle_measurement.pickle
  test/python/pickles/TestsStochasticSwap_initial_layout.pickle
  test/python/test_dagcircuit.py
Labels: Changelog: API Change, automerge

#3755 Allow for circuit measure methods to return a new circuit with inplace kwarg
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/copy-measure-methods-562f0c1096f93145.yaml
  test/python/circuit/test_circuit_operations.py
Labels: Changelog: API Change, automerge, type: enhancement

#3730 Utility function to measure qubits using OpenPulse
  qiskit/scheduler/__init__.py
  qiskit/scheduler/methods/basic.py
  qiskit/scheduler/utils.py
  releasenotes/notes/add-utility-function-measure-4b951766cdfe5cd6.yaml
  test/python/scheduler/test_utils.py
Labels: automerge

#3776 Cleanup travis config file
  .travis.yml
Labels: automerge

#3771 Better support for controlled gates in text drawer
  qiskit/visualization/text.py
  releasenotes/notes/better_support_for_controlled_gates_in_text_drawer-b18cff47d64271ef.yaml
  test/python/visualization/test_circuit_text_drawer.py
Labels: automerge
