Repository Qiskit/qiskit, pull requests merged in 2020-08, with the labels that each got.

#4841 [text circuit drawer] Fixing labels in long layers
  qiskit/visualization/text.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: automerge

#4835 Round M2 dot product in Weyl decomposition
  qiskit/quantum_info/synthesis/two_qubit_decompose.py
  test/python/quantum_info/test_synthesis.py
Labels: automerge

#4640 Add zeroed ends to parametric pulses
  qiskit/pulse/library/continuous.py
  qiskit/pulse/library/discrete.py
  qiskit/pulse/library/parametric_pulses.py
  releasenotes/notes/zero-param-pulse-ends-c3ad82eae66f9252.yaml
  test/python/pulse/test_continuous_pulses.py
  test/python/pulse/test_discrete_pulses.py
  test/python/pulse/test_pulse_lib.py
Labels: automerge

#4842 Fixes 4749 with backend default instructions
  qiskit/circuit/library/standard_gates/u2.py
  qiskit/circuit/library/standard_gates/u3.py
Labels: automerge

#4824 Follow-up on quadratic form
  qiskit/circuit/library/arithmetic/quadratic_form.py
  test/python/circuit/test_library.py
Labels: automerge

#4765 Add U and Phase gate
  .pylintrc
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/standard_gates/__init__.py
  qiskit/circuit/library/standard_gates/equivalence_library.py
  qiskit/circuit/library/standard_gates/p.py
  qiskit/circuit/library/standard_gates/u.py
  qiskit/circuit/library/standard_gates/u3.py
  qiskit/circuit/quantumcircuit.py
  qiskit/qasm/libs/qelib1.inc
  releasenotes/notes/u-and-phase-gate-e308fb4bb009014f.yaml
  test/python/circuit/test_controlled_gate.py
  test/python/circuit/test_gate_definitions.py
Labels: Changelog: New Feature, automerge

#4795 Drawers support for "partial" layout
  qiskit/visualization/latex.py
  qiskit/visualization/matplotlib.py
  qiskit/visualization/text.py
  test/ipynb/mpl/references/partial_layout.png
  test/ipynb/mpl/test_circuit_matplotlib_drawer.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: Changelog: Bugfix, automerge

#4638 Sqrt(X) and C-Sqrt(X) gates
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/standard_gates/__init__.py
  qiskit/circuit/library/standard_gates/equivalence_library.py
  qiskit/circuit/library/standard_gates/s.py
  qiskit/circuit/library/standard_gates/sx.py
  qiskit/circuit/library/standard_gates/t.py
  qiskit/circuit/quantumcircuit.py
  qiskit/qasm/libs/qelib1.inc
  qiskit/visualization/matplotlib.py
  qiskit/visualization/qcstyle.py
  releasenotes/notes/sqrt-x-gates-3aba219f0efd8900.yaml
  test/python/circuit/test_controlled_gate.py
  test/python/circuit/test_extensions_standard.py
  test/python/circuit/test_gate_definitions.py
  test/python/visualization/references/circuit_text_ref.txt
  test/python/visualization/test_circuit_visualization_output.py
Labels: Changelog: New Feature, automerge, global-phase

#4836 Allow multi qubit to builder measure
  qiskit/pulse/builder.py
  test/python/pulse/test_builder.py
Labels: automerge, type: enhancement

#4870 Allow a single instruction to be assembled
  qiskit/assembler/assemble_schedules.py
  test/python/compiler/test_assembler.py
Labels: automerge

#4830 Modify `rep_delays` from backend to be a sliding `rep_delay_range`
  qiskit/compiler/assemble.py
  qiskit/execute.py
  qiskit/providers/models/backendconfiguration.py
  qiskit/qobj/pulse_qobj.py
  qiskit/schemas/backend_configuration_schema.json
  releasenotes/notes/add-rep-delay-c97d5aa8fc9696da.yaml
  test/python/compiler/test_assembler.py
  test/python/providers/test_backendconfiguration.py
Labels: automerge, bug

#4867 Allow Generator object for seed in QuantumVolume circuit
  qiskit/circuit/library/quantum_volume.py
  releasenotes/notes/quantum_volume_rng-2e6f46e3821aebeb.yaml
  test/python/circuit/test_library.py
Labels: automerge

#4560 Add schedule replace method
  qiskit/pulse/schedule.py
  releasenotes/notes/schedule-replace-2c5634a6133db237.yaml
  test/python/pulse/test_schedule.py
Labels: automerge

#4755 Fix and update align measures logic
  qiskit/pulse/transforms.py
  test/python/pulse/test_transforms.py
Labels: automerge

#4874 Bump configuration schema
  qiskit/schemas/backend_configuration_schema.json
Labels: automerge

#4782 Support for backends with defective qubits and gates
  qiskit/circuit/quantumcircuit.py
  qiskit/compiler/transpile.py
  qiskit/providers/models/backendproperties.py
  qiskit/test/mock/fake_backend.py
  qiskit/transpiler/coupling.py
  releasenotes/notes/defective_qubits-d826ccbd049603b9.yaml
  test/python/providers/faulty_backends.py
  test/python/providers/test_backendproperties.py
  test/python/providers/test_faulty_backend.py
  test/python/transpiler/test_faulty_backend.py
Labels: Changelog: New Feature, automerge

#4884 Bump version strings post release
  .mergify.yml
  docs/conf.py
  qiskit/VERSION.txt
  setup.py
Labels: automerge

#4885 Changed default labels for sdg, tdg, sx, and sxdg to None
  qiskit/circuit/library/standard_gates/s.py
  qiskit/circuit/library/standard_gates/sx.py
  qiskit/circuit/library/standard_gates/t.py
  qiskit/visualization/qcstyle.py
  qiskit/visualization/text.py
  test/python/visualization/references/circuit_text_ref.txt
Labels: automerge, stable backport potential

#4899 Prepare 0.15.1 release
  docs/conf.py
  qiskit/VERSION.txt
  setup.py
Labels: automerge

#4903 One reference to get_sample_pulse is raising deprecation warnings fro…
  qiskit/assembler/assemble_schedules.py
Labels: automerge

#4909 Explicitly convert gate params to float in to_matrix
  qiskit/circuit/library/standard_gates/r.py
  qiskit/circuit/library/standard_gates/rx.py
  qiskit/circuit/library/standard_gates/ry.py
  qiskit/circuit/library/standard_gates/ryy.py
  qiskit/circuit/library/standard_gates/rz.py
  qiskit/circuit/library/standard_gates/rzx.py
  test/python/circuit/test_parameters.py
Labels: automerge

#4852 Seeding test.python.circuit.test_initializer
  test/python/circuit/test_initializer.py
Labels: automerge

#4924 fix #4798
  qiskit/transpiler/passes/layout/sabre_layout.py
  test/python/transpiler/test_sabre_layout.py
Labels: automerge

#4904 Fixes #4894 : A small change in docstring.
  qiskit/qobj/pulse_qobj.py
Labels: automerge

#4935 Remove deprecated gate keyword arguments
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/remove-deprecated-gate-args-b29ba17badcb77ca.yaml
  test/python/circuit/test_extensions_standard.py
Labels: automerge

#4925 Doc fix of Clifford in quantum_info
  qiskit/quantum_info/operators/symplectic/clifford.py
Labels: automerge

#4929 Fixed Issue 4912 by deepcopying the results to utils.marginal_counts
  qiskit/result/utils.py
  releasenotes/notes/added-inplace-arg-8b7daf3abbd913cb.yaml
  test/python/result/test_result.py
Labels: automerge

#4937 schemas: remove remaining "PersistentValue"s
  qiskit/schemas/examples/qobj_openpulse_example.json
  test/python/qobj/test_qobj.py
Labels: automerge, type: enhancement

#4954 Update example in README.md to use transpiler.
  README.md
Labels: type: documentation

#3586 Deterministic test_synthesis.py
  test/python/quantum_info/test_synthesis.py
  test/randomized/test_synthesis.py
Labels: automerge

#4931 Fix +- in complex numbers and set mpl to all math minus signs
  qiskit/circuit/tools/pi_check.py
  qiskit/visualization/matplotlib.py
  test/python/circuit/test_tools.py
Labels: automerge

#4808 Enhance pulse builder alignment context
  qiskit/pulse/__init__.py
  qiskit/pulse/builder.py
  qiskit/pulse/transforms.py
  releasenotes/notes/add-pulse-builder-alignment-326f2d20dde5e658.yaml
  test/python/pulse/test_transforms.py
Labels: automerge, type: enhancement

#4966 Fixes #4965: Updated Docstring under Schedule.draw()
  qiskit/pulse/schedule.py
Labels: automerge

#4948 Fix on _bloch_multivector_data (utils.py) when number of qubit is 1
  qiskit/visualization/utils.py
Labels: automerge

#4972 Fix bug from #4859: Pulse gates calibrations
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_circuit_properties.py
Labels: automerge

#4974 Fix pulse transforms recursion bug fix that was lost in merge conflict
  qiskit/pulse/transforms.py
  releasenotes/notes/pulse-schedule-recursion-bugfix-1bf1b7d919cf1a0c.yaml
Labels: Changelog: Bugfix, automerge, stable backport potential

#4735 Pulse Schedule disassembler
  qiskit/assembler/disassemble.py
  releasenotes/notes/pulse-schedule-disassembler-5315a00bd5d17dfd.yaml
  test/python/compiler/test_disassembler.py
Labels: automerge, type: enhancement

#4969 Pulse gates: assembly changes
  qiskit/assembler/assemble_circuits.py
  qiskit/compiler/assemble.py
  qiskit/qobj/qasm_qobj.py
  releasenotes/notes/pulse-gate-calibrations-78fd3fa5a5328761.yaml
  test/python/compiler/test_assembler.py
Labels: automerge

#4989 Fixes MCPhaseGate definition
  qiskit/circuit/library/standard_gates/p.py
Labels: Changelog: Bugfix, automerge, stable backport potential

#4853 Fix pi_check not handling large numbers properly
  qiskit/circuit/tools/pi_check.py
  test/python/circuit/test_tools.py
Labels: Changelog: Bugfix, automerge

#4958 Move heavy visualization imports outside base namespace imports
  qiskit/visualization/transition_visualization.py
Labels: automerge, performance, stable backport potential

#4900 Encoding the circuit text drawer (based on preferred encoding) and ignore errors.
  qiskit/visualization/circuit_visualization.py
  qiskit/visualization/text.py
  test/python/test_examples.py
  test/python/visualization/references/circuit_text_ref_cp437.txt
  test/python/visualization/references/circuit_text_ref_original.txt
  test/python/visualization/references/circuit_text_ref_utf8.txt
  test/python/visualization/test_circuit_visualization_output.py
  test/python/visualization/visualization.py
Labels: automerge

#4807 Fix pi_check param expressions
  qiskit/circuit/tools/pi_check.py
  test/ipynb/mpl/references/pi_in_param_expr.png
  test/ipynb/mpl/test_circuit_matplotlib_drawer.py
  test/python/circuit/test_tools.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: automerge

#4994 Update PhaseGate.control(n) to return MCPhaseGate
  qiskit/circuit/library/standard_gates/p.py
  releasenotes/notes/4989-Fixes-MCPhaseGate-definition-cbe5e14992116e67.yaml
  test/python/circuit/test_controlled_gate.py
Labels: Changelog: Bugfix, stable backport potential

#5000 Unused attribute in CommutationAnalysis class
  qiskit/transpiler/passes/optimization/commutation_analysis.py
Labels: automerge

#4726 Updated transpiler test_mappers to utiliz Path.QASMS (#4724)
  test/python/transpiler/test_mappers.py
Labels: automerge

#4951 Pulse gates/scheduler
  qiskit/scheduler/lowering.py
  releasenotes/notes/pulse-gate-calibrations-78fd3fa5a5328761.yaml
  test/python/scheduler/test_basic_scheduler.py
Labels: automerge

#5006 Revert "Remove namespace packaging and hardcode elements (#4767)"
  qiskit/__init__.py
  qiskit/namespace.py
  qiskit/providers/__init__.py
  qiskit/tools/jupyter/job_watcher.py
  qiskit/version.py
  tox.ini
Labels: automerge

#4976 Fix inverse in controlled gates
  qiskit/circuit/library/standard_gates/h.py
  qiskit/circuit/library/standard_gates/p.py
  qiskit/circuit/library/standard_gates/rx.py
  qiskit/circuit/library/standard_gates/ry.py
  qiskit/circuit/library/standard_gates/rz.py
  qiskit/circuit/library/standard_gates/swap.py
  qiskit/circuit/library/standard_gates/u.py
  qiskit/circuit/library/standard_gates/u1.py
  qiskit/circuit/library/standard_gates/u3.py
  qiskit/circuit/library/standard_gates/x.py
  qiskit/circuit/library/standard_gates/y.py
  qiskit/circuit/library/standard_gates/z.py
  releasenotes/notes/fix-controlledgate-inverse-4f87ffd362127186.yaml
  test/python/circuit/test_controlled_gate.py
Labels: Changelog: Bugfix, automerge, stable backport potential
