Repository Qiskit/qiskit, pull requests merged in 2020-02, with the labels that each got.

#3767 Bugfix/acquires must be combined in assemble
  qiskit/assembler/assemble_schedules.py
  qiskit/pulse/commands/acquire.py
  qiskit/qobj/converters/pulse_instruction.py
  test/python/compiler/test_assembler.py
Labels: automerge

#3773 make controlled base gate an instance.
  qiskit/circuit/add_control.py
  qiskit/circuit/controlledgate.py
  qiskit/extensions/standard/h.py
  qiskit/extensions/standard/rx.py
  qiskit/extensions/standard/ry.py
  qiskit/extensions/standard/rz.py
  qiskit/extensions/standard/swap.py
  qiskit/extensions/standard/u1.py
  qiskit/extensions/standard/u3.py
  qiskit/extensions/standard/x.py
  qiskit/extensions/standard/y.py
  qiskit/extensions/standard/z.py
  qiskit/visualization/text.py
  test/python/circuit/test_controlled_gate.py
  test/python/pickles/TestsBasicSwap_a_cx_to_map.pickle
  test/python/pickles/TestsBasicSwap_handle_measurement.pickle
  test/python/pickles/TestsBasicSwap_initial_layout.pickle
  test/python/pickles/TestsLookaheadSwap_a_cx_to_map.pickle
  test/python/pickles/TestsLookaheadSwap_handle_measurement.pickle
  test/python/pickles/TestsLookaheadSwap_initial_layout.pickle
  test/python/pickles/TestsStochasticSwap_a_cx_to_map.pickle
  test/python/pickles/TestsStochasticSwap_handle_measurement.pickle
  test/python/pickles/TestsStochasticSwap_initial_layout.pickle
Labels: automerge

#3782 Collect2qBlocks to always exclude conditioned gates from blocks.
  qiskit/transpiler/passes/optimization/collect_2q_blocks.py
  releasenotes/notes/3215-ConsolidateBlocks-drops-classical-conditional-c5ed03f9a6d15284.yaml
  test/python/transpiler/test_collect_2q_blocks.py
Labels: Changelog: Bugfix, automerge

#3787 Add optional parameters to bind_schema
  qiskit/validation/base.py
  test/python/validation/test_schemas.py
Labels: automerge

#3779 Add support for controlled gates to mpl drawer
  qiskit/visualization/matplotlib.py
Labels: Changelog: Bugfix, automerge

#3777 Add support for displaying controlled gates to latex
  qiskit/visualization/latex.py
Labels: Changelog: Bugfix, automerge

#3788 Rename and deprecate qubit keyword args on standard gates.
  qiskit/extensions/standard/h.py
  qiskit/extensions/standard/iden.py
  qiskit/extensions/standard/r.py
  qiskit/extensions/standard/rx.py
  qiskit/extensions/standard/ry.py
  qiskit/extensions/standard/rz.py
  qiskit/extensions/standard/s.py
  qiskit/extensions/standard/swap.py
  qiskit/extensions/standard/t.py
  qiskit/extensions/standard/u1.py
  qiskit/extensions/standard/u2.py
  qiskit/extensions/standard/u3.py
  qiskit/extensions/standard/x.py
  qiskit/extensions/standard/y.py
  qiskit/extensions/standard/z.py
  qiskit/util.py
  releasenotes/notes/3399-Change-QuantumCircuit-method-input-arg-names-8422b6abfdfff081.yaml
  test/python/circuit/test_extensions_standard.py
Labels: Changelog: Deprecation, automerge

#3722 add __repr__ to qiskit.visualization.text.TextDrawing
  qiskit/visualization/text.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: Changelog: New Feature, automerge

#3802 deepcopy(Instruction) to use Instruction.copy.
  qiskit/circuit/instruction.py
Labels: automerge

#3729 Fix bind propagation when decomposing composite gates.
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/2482-decompose-does-not-propagate-bound-parameters-71fb409de3416255.yaml
  test/python/circuit/test_parameters.py
Labels: Changelog: Bugfix

#3803 Bump version string post release
  qiskit/VERSION.txt
  setup.py
Labels: automerge

#3792 Support Scheduler in execute pipeline
  qiskit/execute.py
  releasenotes/notes/support-scheduler-in-execute-42a1ebe9e3a67bbb.yaml
Labels: automerge

#3785 #3343 | FakePulseBackend: change fake backend phases to radians
  qiskit/test/mock/fake_openpulse_2q.py
  qiskit/test/mock/fake_openpulse_3q.py
  test/python/providers/test_pulse_defaults.py
  test/python/pulse/test_cmd_def.py
Labels: automerge

#3035 Defaults in TranspileConfig (now called PassManagerConfig)
  qiskit/compiler/transpile.py
  qiskit/transpiler/__init__.py
  qiskit/transpiler/models.py
  qiskit/transpiler/pass_manager_config.py
  qiskit/transpiler/passmanager.py
  qiskit/transpiler/preset_passmanagers/level0.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  qiskit/transpiler/runningpassmanager.py
  qiskit/transpiler/transpile_circuit.py
  qiskit/transpiler/transpile_config.py
  qiskit/validation/base.py
  releasenotes/notes/defaults_TranspileConfig-4109a90c278d46df.yaml
  test/python/transpiler/test_passmanager.py
  test/python/transpiler/test_passmanager_run.py
Labels: Changelog: API Change, Changelog: Deprecation, automerge

#3819 Fix Docstrings of Circuit Scheduler
  qiskit/scheduler/config.py
  qiskit/scheduler/methods/basic.py
  qiskit/scheduler/schedule_circuit.py
Labels: automerge, type: documentation

#3813 Remove deprecated pulse `channel` code
  qiskit/pulse/__init__.py
  qiskit/pulse/channels/__init__.py
  qiskit/pulse/channels/channels.py
  qiskit/pulse/channels/pulse_channel_spec.py
  qiskit/pulse/channels/pulse_channels.py
  qiskit/pulse/channels/qubit.py
  qiskit/pulse/commands/acquire.py
  releasenotes/notes/channel-module-deprecations-in-pulse-ffc384b325b077f1.yaml
  test/python/pulse/test_channels.py
  test/python/pulse/test_schedule.py
Labels: automerge, type: documentation

#3814 Pulse channel module to file
  qiskit/pulse/channels.py
  qiskit/pulse/channels/__init__.py
Labels: automerge, type: documentation

#3761 Implement the relative phase Toffoli gates
  qiskit/extensions/standard/__init__.py
  qiskit/extensions/standard/multi_control_toffoli_gate.py
  qiskit/extensions/standard/rcccx.py
  qiskit/extensions/standard/rccx.py
  qiskit/extensions/standard/relative_phase_toffoli.py
  qiskit/qasm/libs/qelib1.inc
  test/python/circuit/test_controlled_gate.py
  test/python/test_qasm_parser.py
Labels: automerge

#3818 Docathon: Remove utils until it is needed again one day :star-eyes:
  qiskit/pulse/utils.py
Labels: automerge, type: documentation

#3834 Make Dan Puzzuoli a codeowner for pulse and scheduler
  .github/CODEOWNERS
Labels: automerge

#3835 Revise docstrings for passes.basis.decompose
  qiskit/transpiler/passes/basis/decompose.py
Labels: automerge, type: documentation

#3826 Update the formatting and content of couplin gmap draw()
  qiskit/transpiler/coupling.py
Labels: automerge

#3815 Docathon: pulse channels
  qiskit/pulse/channels.py
Labels: automerge, type: documentation

#3823 Docathon: rescheduler
  qiskit/pulse/__init__.py
  qiskit/pulse/reschedule.py
Labels: automerge, type: documentation

#3833 Docathon: Add scheduling methods and scheduler utility functions to API docs
  qiskit/scheduler/__init__.py
  qiskit/scheduler/methods/__init__.py
  qiskit/scheduler/methods/basic.py
Labels: automerge, type: documentation

#3839 Revise docstrings for qiskit.transpiler.preset_passmanagers
  qiskit/transpiler/preset_passmanagers/level0.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
Labels: automerge, type: documentation

#3840 add falcon topology
  qiskit/visualization/gate_map.py
Labels: automerge, stable backport potential, type: enhancement

#3822 Docathon: pulse/parser.py (mostly type hints)
  qiskit/pulse/parser.py
Labels: automerge, type: documentation

#3844 Docathon: Fixup: formatting
  qiskit/pulse/reschedule.py
Labels: automerge, type: documentation

#3816 Docathon! Inst Sched Map (and CmdDef)
  qiskit/pulse/__init__.py
  qiskit/pulse/cmd_def.py
  qiskit/pulse/instruction_schedule_map.py
Labels: automerge, type: documentation

#3843 Fix circuit extending with self
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/copy-rhs-on-extending-qc-9e65804b6b0ab4da.yaml
  test/python/circuit/test_circuit_operations.py
Labels: Changelog: Bugfix, automerge

#3561 Single Qubit Transition Visualization
  qiskit/visualization/__init__.py
  qiskit/visualization/transition_visualization.py
  releasenotes/notes/quibit-transition-visualization-a62d0d119569fa05.yaml
Labels: automerge

#3845 Skip TestJupyter tests if ibmq provider is not installed
  test/python/tools/jupyter/test_notebooks.py
Labels: automerge

#3838 Docathon! Docs for discrete pulse functions
  qiskit/pulse/__init__.py
  qiskit/pulse/pulse_lib/__init__.py
  qiskit/pulse/pulse_lib/discrete.py
Labels: automerge, type: documentation

#3850 Fix citation in pulse_lib/discrete
  qiskit/pulse/pulse_lib/discrete.py
Labels: type: documentation

#3849 Docathon: Module level docs for Pulse
  qiskit/pulse/__init__.py
  qiskit/pulse/channels.py
Labels: automerge, type: documentation

#3836 Docathon: schedule.py and remove deprecated buffer arg
  qiskit/pulse/commands/instruction.py
  qiskit/pulse/interfaces.py
  qiskit/pulse/schedule.py
  releasenotes/notes/channel-module-deprecations-in-pulse-ffc384b325b077f1.yaml
Labels: Changelog: API Change, automerge, type: documentation

#3432 Improve jsonschema validation error messages
  qiskit/validation/jsonschema/schema_validation.py
Labels: automerge

#3795 Speed up schedule()
  qiskit/scheduler/methods/basic.py
Labels: automerge, performance

#3739 add ability to specify open controls.
  qiskit/circuit/__init__.py
  qiskit/circuit/add_control.py
  qiskit/circuit/controlledgate.py
  qiskit/circuit/gate.py
  qiskit/extensions/standard/h.py
  qiskit/extensions/standard/rx.py
  qiskit/extensions/standard/ry.py
  qiskit/extensions/standard/rz.py
  qiskit/extensions/standard/swap.py
  qiskit/extensions/standard/u1.py
  qiskit/extensions/standard/u3.py
  qiskit/extensions/standard/x.py
  qiskit/extensions/standard/y.py
  qiskit/extensions/standard/z.py
  qiskit/extensions/unitary.py
  releasenotes/notes/add-open-controls-bb21111b866ada43.yaml
  test/python/circuit/test_controlled_gate.py
  test/python/pickles/TestsBasicSwap_a_cx_to_map.pickle
  test/python/pickles/TestsBasicSwap_handle_measurement.pickle
  test/python/pickles/TestsBasicSwap_initial_layout.pickle
  test/python/pickles/TestsLookaheadSwap_a_cx_to_map.pickle
  test/python/pickles/TestsLookaheadSwap_handle_measurement.pickle
  test/python/pickles/TestsLookaheadSwap_initial_layout.pickle
  test/python/pickles/TestsStochasticSwap_a_cx_to_map.pickle
  test/python/pickles/TestsStochasticSwap_handle_measurement.pickle
  test/python/pickles/TestsStochasticSwap_initial_layout.pickle
Labels: automerge

#3709 Fixes 3684 - MPL drawer renders cU1 gate correctly
  qiskit/visualization/matplotlib.py
  releasenotes/notes/fix3684-69e230f98546deb6.yaml
Labels: automerge

#3841 start of a circuit library
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/boolean_logic.py
  releasenotes/notes/boolean-logic-circuit-library-0f913cc04063210b.yaml
  test/python/circuit/test_library.py
Labels: automerge

#3871 Fix the broken hyperlink in Pulse API docs
  qiskit/pulse/__init__.py
  qiskit/pulse/commands/__init__.py
Labels: automerge, type: documentation

#3794 Refactor/assemble schedules
  qiskit/assembler/assemble_schedules.py
Labels: automerge

#3882 Fix use of deprecated argument in ``iden``
  qiskit/extensions/standard/i.py
Labels: automerge

#3762 General routing
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/routing/__init__.py
  qiskit/transpiler/passes/routing/algorithms/__init__.py
  qiskit/transpiler/passes/routing/algorithms/token_swapper.py
  qiskit/transpiler/passes/routing/algorithms/types.py
  qiskit/transpiler/passes/routing/algorithms/util.py
  qiskit/transpiler/passes/routing/layout_transformation.py
  test/python/transpiler/test_layout_transformation.py
  test/python/transpiler/test_token_swapper.py
Labels: automerge

#3879 remove identity insertion in gate decomposition
  qiskit/extensions/quantum_initializer/isometry.py
  qiskit/extensions/quantum_initializer/squ.py
  qiskit/extensions/quantum_initializer/uc_pauli_rot.py
Labels: automerge

#3875 Simplify BaseOperator abstract class
  qiskit/quantum_info/operators/base_operator.py
  qiskit/quantum_info/operators/channel/chi.py
  qiskit/quantum_info/operators/channel/choi.py
  qiskit/quantum_info/operators/channel/kraus.py
  qiskit/quantum_info/operators/channel/ptm.py
  qiskit/quantum_info/operators/channel/quantum_channel.py
  qiskit/quantum_info/operators/channel/stinespring.py
  qiskit/quantum_info/operators/channel/superop.py
  qiskit/quantum_info/operators/operator.py
  releasenotes/notes/base-operator-update-b0d824738b4bfd4d.yaml
  test/python/quantum_info/operators/channel/test_chi.py
  test/python/quantum_info/operators/channel/test_choi.py
  test/python/quantum_info/operators/channel/test_kraus.py
  test/python/quantum_info/operators/channel/test_linearops.py
  test/python/quantum_info/operators/channel/test_ptm.py
  test/python/quantum_info/operators/channel/test_stinespring.py
  test/python/quantum_info/operators/channel/test_superop.py
  test/python/quantum_info/operators/test_operator.py
  test/python/quantum_info/states/test_densitymatrix.py
  test/python/quantum_info/states/test_statevector.py
Labels: Changelog: API Change, Changelog: Deprecation

#3703 Improves ``OneQubitEulerDecomposer`` class and add ``RR`` basis decomposition.
  qiskit/extensions/quantum_initializer/uc.py
  qiskit/extensions/unitary.py
  qiskit/quantum_info/__init__.py
  qiskit/quantum_info/operators/operator.py
  qiskit/quantum_info/synthesis/__init__.py
  qiskit/quantum_info/synthesis/one_qubit_decompose.py
  qiskit/quantum_info/synthesis/two_qubit_decompose.py
  releasenotes/notes/one-qubit-synthesis-c5e323717b8dfe4d.yaml
  test/python/quantum_info/test_synthesis.py
Labels: Changelog: API Change, Changelog: Deprecation, automerge

#3825 Revise docstrings for qiskit.transpiler.passmanager
  qiskit/transpiler/passmanager.py
Labels: automerge, type: documentation

#3464 Fix gate power for arbitrary gates
  qiskit/circuit/gate.py
  qiskit/converters/circuit_to_gate.py
  test/python/circuit/test_gate_power.py
Labels: automerge, global-phase

#3862 Command/Instruction unification
  qiskit/pulse/__init__.py
  qiskit/pulse/commands/instruction.py
  qiskit/pulse/instructions/__init__.py
  qiskit/pulse/instructions/instruction.py
  releasenotes/notes/unify-instructions-and-commands-aaa6d8724b8a29d3.yaml
Labels: automerge

#3821 Compiler docstring update
  qiskit/compiler/assemble.py
  qiskit/compiler/schedule.py
  qiskit/compiler/transpile.py
Labels: automerge, type: documentation

#3719 Define continuous waves by frequency
  qiskit/pulse/pulse_lib/continuous.py
  qiskit/pulse/pulse_lib/discrete.py
  releasenotes/notes/continuous-waves-defined-by-frequency-a86b4cc623a2e43b.yaml
  test/python/pulse/test_continuous_pulses.py
  test/python/pulse/test_discrete_pulses.py
Labels: automerge

#3685 Generate default name for Schedule instances
  qiskit/circuit/quantumcircuit.py
  qiskit/pulse/schedule.py
  qiskit/util.py
  releasenotes/notes/default-schedule-name-51ba198cf08978cd.yaml
  test/python/compiler/test_assembler.py
  test/python/pulse/test_schedule.py
  test/python/tools/test_parallel.py
Labels: automerge

#3591 Use catalina for some osx jobs
  azure-pipelines.yml
Labels: automerge

#3731 Add wait_for_final_state() to BaseJob
  qiskit/providers/basejob.py
  releasenotes/notes/job-wait-for-final-state-b9951d21aad5d3c2.yaml
  test/python/providers/test_jobmethods.py
Labels: Changelog: New Feature, automerge

#3894 Rename apidocs landing pages
  docs/apidocs/qiskit.rst
  docs/index.rst
Labels: automerge, type: documentation

#3391 Use CSPLayout in Level 2 and Level 3
  qiskit/transpiler/passes/layout/csp_layout.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  releasenotes/notes/csplayout_level_2and3-df6b06d05a34263f.yaml
  requirements.txt
  setup.py
  test/python/transpiler/test_csp_layout.py
  test/python/transpiler/test_preset_passmanagers.py
Labels: Changelog: API Change, automerge

#3890 Add support for backend.run to FakeBackend
  qiskit/test/mock/fake_backend.py
  releasenotes/notes/fake-backend-run-37d48dbf0e9de6f3.yaml
Labels: Changelog: New Feature, automerge

#3869 Fixed issue #3806 by checking if QuantumCircuit args can be cast to int
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_circuit_properties.py
Labels: automerge
