Repository Qiskit/qiskit, pull requests merged in 2020-03, with the labels that each got.

#3914 Fix substitute parameters when decomposing composite gates
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/fix-propagation-of-substituted-parameters-78bc9ece47013dbb.yaml
  test/python/circuit/test_parameters.py
Labels: Changelog: Bugfix, automerge

#3913 Less parameters in the RXX gate
  qiskit/extensions/standard/rxx.py
Labels: automerge

#3873 Add ``qargs`` property, ``__call__``, method to set qargs to BaseOperators
  qiskit/quantum_info/operators/base_operator.py
  qiskit/quantum_info/operators/channel/chi.py
  qiskit/quantum_info/operators/channel/choi.py
  qiskit/quantum_info/operators/channel/kraus.py
  qiskit/quantum_info/operators/channel/ptm.py
  qiskit/quantum_info/operators/channel/stinespring.py
  qiskit/quantum_info/operators/channel/superop.py
  qiskit/quantum_info/operators/operator.py
  releasenotes/notes/operator-qargs-aeb2254b5a643013.yaml
  test/python/quantum_info/operators/channel/test_chi.py
  test/python/quantum_info/operators/channel/test_choi.py
  test/python/quantum_info/operators/channel/test_kraus.py
  test/python/quantum_info/operators/channel/test_ptm.py
  test/python/quantum_info/operators/channel/test_stinespring.py
  test/python/quantum_info/operators/channel/test_superop.py
  test/python/quantum_info/operators/test_operator.py
Labels: automerge

#3878 Cache commutation results in commutation analysis pass
  qiskit/transpiler/passes/optimization/commutation_analysis.py
Labels: automerge, performance

#3791 Deprecate Schedule.union
  qiskit/pulse/instructions/instruction.py
  qiskit/pulse/interfaces.py
  qiskit/pulse/schedule.py
Labels: automerge

#3887 Add ``ScalarOp`` to `quantum_info.operators`
  qiskit/quantum_info/__init__.py
  qiskit/quantum_info/operators/__init__.py
  qiskit/quantum_info/operators/scalar_op.py
  qiskit/test/utils.py
  releasenotes/notes/scalar-op-f52a05d5485affc7.yaml
  test/__init__.py
  test/python/quantum_info/operators/test_scalar_op.py
Labels: automerge

#3918 Define __slots__ for bit class
  qiskit/circuit/bit.py
  test/python/pickles/TestsBasicSwap_a_cx_to_map.pickle
  test/python/pickles/TestsBasicSwap_handle_measurement.pickle
  test/python/pickles/TestsBasicSwap_initial_layout.pickle
  test/python/pickles/TestsLookaheadSwap_a_cx_to_map.pickle
  test/python/pickles/TestsLookaheadSwap_handle_measurement.pickle
  test/python/pickles/TestsLookaheadSwap_initial_layout.pickle
  test/python/pickles/TestsStochasticSwap_a_cx_to_map.pickle
  test/python/pickles/TestsStochasticSwap_handle_measurement.pickle
  test/python/pickles/TestsStochasticSwap_initial_layout.pickle
Labels: automerge

#3942 Remove benchmark jobs for PRs and master branch in Travis.
  .travis.yml
Labels: automerge

#3921 FakeAlmaden: Memoize properties and defaults
  qiskit/test/mock/backends/almaden/fake_almaden.py
Labels: automerge

#3919 Fix unused-import disables in tests
  test/python/circuit/test_circuit_qasm.py
  test/python/circuit/test_circuit_registers.py
  test/python/providers/test_backendproperties.py
Labels: automerge

#3682 Inconsistencies in linefeed lines in mpl drawer corrected.
  qiskit/visualization/matplotlib.py
  test/python/visualization/references/matplotlib_barriers_ref.png
  test/python/visualization/references/matplotlib_conditional_ref.png
Labels: automerge

#3393 Creates dag op for a call of QASM custom gate
  qiskit/converters/ast_to_dag.py
  releasenotes/notes/from_qasm_str_custom_gates-e3013f958def70e8.yaml
  test/python/circuit/test_circuit_load_from_qasm.py
Labels: automerge

#3934 Switch DAGCircuit wires property to a set instead of a list
  qiskit/dagcircuit/dagcircuit.py
Labels: automerge, performance

#3912 Implement the RYY gate
  qiskit/extensions/standard/__init__.py
  qiskit/extensions/standard/ryy.py
  test/python/circuit/test_gate_definitions.py
Labels: Changelog: New Feature, automerge

#3939 Use __slots__ for register and cache __hash__
  qiskit/circuit/register.py
  test/python/pickles/TestsBasicSwap_a_cx_to_map.pickle
  test/python/pickles/TestsBasicSwap_handle_measurement.pickle
  test/python/pickles/TestsBasicSwap_initial_layout.pickle
  test/python/pickles/TestsLookaheadSwap_a_cx_to_map.pickle
  test/python/pickles/TestsLookaheadSwap_handle_measurement.pickle
  test/python/pickles/TestsLookaheadSwap_initial_layout.pickle
  test/python/pickles/TestsStochasticSwap_a_cx_to_map.pickle
  test/python/pickles/TestsStochasticSwap_handle_measurement.pickle
  test/python/pickles/TestsStochasticSwap_initial_layout.pickle
Labels: automerge, performance

#3383 Remove marshmallow from Qobj
  qiskit/assembler/assemble_circuits.py
  qiskit/circuit/instruction.py
  qiskit/providers/models/pulsedefaults.py
  qiskit/qobj/__init__.py
  qiskit/qobj/models/pulse.py
  qiskit/qobj/models/qasm.py
  qiskit/qobj/pulse_qobj.py
  qiskit/qobj/qasm_qobj.py
  qiskit/qobj/qobj.py
  qiskit/qobj/utils.py
  qiskit/schemas/qobj_schema.json
  qiskit/test/mock/fake_openpulse_2q.py
  qiskit/test/mock/fake_openpulse_3q.py
  releasenotes/notes/qobj-no-marshmallow-3f2b3c7b10584b02.yaml
  requirements.txt
  setup.py
  test/python/circuit/test_unitary.py
  test/python/compiler/test_assembler.py
  test/python/qobj/test_qobj.py
Labels: automerge

#3874 Instruction.copy to deepcopy self._definition if it is set.
  qiskit/circuit/instruction.py
  releasenotes/notes/parameter-propagation-for-rebound-composite-gates-6cbd15bb69a9c85b.yaml
  test/python/circuit/test_parameters.py
Labels: Changelog: Bugfix, automerge

#3900 Fix schedule assember bug
  qiskit/assembler/assemble_schedules.py
  test/python/compiler/test_assembler.py
Labels: automerge

#3924 Command/Inst refactor: Delay
  qiskit/assembler/assemble_schedules.py
  qiskit/pulse/__init__.py
  qiskit/pulse/commands/delay.py
  qiskit/pulse/instructions/__init__.py
  qiskit/pulse/instructions/delay.py
  qiskit/pulse/instructions/instruction.py
  releasenotes/notes/unify-instructions-and-commands-aaa6d8724b8a29d3.yaml
  test/python/pulse/test_instructions.py
Labels: automerge

#3916 Transition DAGCircuit to retworkx
  .pylintrc
  .travis.yml
  qiskit/dagcircuit/dagcircuit.py
  qiskit/dagcircuit/networkx_dagcircuit.py
  qiskit/dagcircuit/retworkx_dagcircuit.py
  qiskit/transpiler/passes/utils/merge_adjacent_barriers.py
  releasenotes/notes/retworkx-ccd3019aae7cfb7d.yaml
  requirements.txt
  setup.py
  test/python/test_dagcircuit.py
  test/python/transpiler/test_commutation_analysis.py
  test/python/transpiler/test_pass_scheduler.py
Labels: automerge

#3955 Allow list params in Instruction
  qiskit/circuit/instruction.py
  releasenotes/notes/list-params-1fa4c3f8b67ff57d.yaml
Labels: automerge

#3888 Add ability to add operators on subsystems.
  qiskit/quantum_info/operators/base_operator.py
  qiskit/quantum_info/operators/channel/kraus.py
  qiskit/quantum_info/operators/channel/quantum_channel.py
  qiskit/quantum_info/operators/channel/stinespring.py
  qiskit/quantum_info/operators/operator.py
  qiskit/quantum_info/operators/scalar_op.py
  releasenotes/notes/base-operator-add-qargs-3c33348993dbc0b3.yaml
  test/python/quantum_info/operators/channel/test_chi.py
  test/python/quantum_info/operators/channel/test_choi.py
  test/python/quantum_info/operators/channel/test_kraus.py
  test/python/quantum_info/operators/channel/test_ptm.py
  test/python/quantum_info/operators/channel/test_stinespring.py
  test/python/quantum_info/operators/channel/test_superop.py
  test/python/quantum_info/operators/test_operator.py
  test/python/quantum_info/operators/test_scalar_op.py
Labels: automerge

#3933 Command/Inst refactor: Snapshot
  qiskit/pulse/__init__.py
  qiskit/pulse/commands/snapshot.py
  qiskit/pulse/instructions/__init__.py
  qiskit/pulse/instructions/snapshot.py
  test/python/pulse/test_instructions.py
Labels: automerge

#3949 Replace sympy GrayCode class with nested for loop
  qiskit/extensions/standard/multi_control_rotation_gates.py
Labels: automerge

#3969 Bump retworkx minimum
  requirements.txt
  setup.py
Labels: automerge

#3975 Update mergify config to require travis not azure
  .mergify.yml
Labels: automerge

#3965 Improve repr for quantum info classes
  qiskit/quantum_info/operators/channel/quantum_channel.py
  qiskit/quantum_info/operators/operator.py
  qiskit/quantum_info/states/quantum_state.py
Labels: automerge

#3966 QuantumCircuit.copy to manually deepcopy mutable circuit properties.
  qiskit/circuit/instruction.py
  qiskit/circuit/quantumcircuit.py
Labels: automerge, performance

#3946 Add library of gates with their equivalent circuit implementations.
  qiskit/circuit/__init__.py
  qiskit/circuit/equivalence.py
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_equivalence.py
Labels: automerge

#3940 Cache bit object's hashes
  qiskit/circuit/bit.py
  qiskit/circuit/register.py
  test/python/circuit/test_bit.py
  test/python/circuit/test_circuit_registers.py
  test/python/pickles/TestsBasicSwap_a_cx_to_map.pickle
  test/python/pickles/TestsBasicSwap_handle_measurement.pickle
  test/python/pickles/TestsBasicSwap_initial_layout.pickle
  test/python/pickles/TestsLookaheadSwap_a_cx_to_map.pickle
  test/python/pickles/TestsLookaheadSwap_handle_measurement.pickle
  test/python/pickles/TestsLookaheadSwap_initial_layout.pickle
  test/python/pickles/TestsStochasticSwap_a_cx_to_map.pickle
  test/python/pickles/TestsStochasticSwap_handle_measurement.pickle
  test/python/pickles/TestsStochasticSwap_initial_layout.pickle
Labels: automerge, performance

#3974 Remove stray prints form unit tests
  test/python/quantum_info/operators/test_scalar_op.py
Labels: automerge

#3948 Remove previously deprecated instruction parameter types
  qiskit/circuit/instruction.py
  qiskit/releasenotes/notes/remove-sympy-instruction-e05f08e511397305.yaml
  test/python/transpiler/test_optimize_1q_gates.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: automerge

#3893 Command/Inst refactor: FrameChange -> ShiftPhase
  qiskit/pulse/__init__.py
  qiskit/pulse/commands/frame_change.py
  qiskit/pulse/instructions/__init__.py
  qiskit/pulse/instructions/phase.py
  qiskit/qobj/converters/pulse_instruction.py
  qiskit/visualization/pulse/matplotlib.py
  releasenotes/notes/0.12/better-pulse-repr-9e5ba50649322b6b.yaml
  releasenotes/notes/unify-instructions-and-commands-aaa6d8724b8a29d3.yaml
  test/python/providers/test_pulse_defaults.py
  test/python/pulse/test_cmd_def.py
  test/python/pulse/test_commands.py
  test/python/pulse/test_instruction_schedule_map.py
  test/python/pulse/test_instructions.py
  test/python/pulse/test_schedule.py
  test/python/qobj/test_pulse_converter.py
Labels: automerge

#3954 Fix pulse drawer bug for plot range
  qiskit/visualization/pulse/matplotlib.py
  qiskit/visualization/pulse/qcstyle.py
  test/python/visualization/references/instruction_matplotlib_ref.png
  test/python/visualization/references/parametric_matplotlib_ref.png
  test/python/visualization/references/pulse_matplotlib_ref.png
  test/python/visualization/references/schedule_matplotlib_ref.png
  test/python/visualization/references/schedule_show_framechange_ref.png
  test/python/visualization/references/truncated_schedule_matplotlib_ref.png
  test/python/visualization/test_pulse_visualization_output.py
Labels: automerge

#3751 fix issue 3733 making result.get_counts() return also a list of dicts
  qiskit/result/result.py
  releasenotes/notes/get_counts-returns-also-dict_list-fcd23da8f3757105.yaml
  test/python/result/test_result.py
Labels: Changelog: API Change, automerge

#3784 add accordion to docs
  docs/_static/custom.css
  docs/_templates/page.html
  docs/conf.py
Labels: automerge, type: documentation, type: enhancement

#3880 Fixed Issue 3649 by adding 'pip install...' to ImportErrors
  qiskit/test/decorators.py
  qiskit/transpiler/passes/optimization/crosstalk_adaptive_schedule.py
  qiskit/visualization/gate_map.py
  qiskit/visualization/interactive/iplot_blochsphere.py
  qiskit/visualization/interactive/iplot_cities.py
  qiskit/visualization/interactive/iplot_hinton.py
  qiskit/visualization/interactive/iplot_histogram.py
  qiskit/visualization/interactive/iplot_paulivec.py
  qiskit/visualization/interactive/iplot_qsphere.py
  qiskit/visualization/matplotlib.py
  qiskit/visualization/state_visualization.py
Labels: automerge

#3468 New feature: SetFrequency command
  qiskit/pulse/__init__.py
  qiskit/pulse/instructions/__init__.py
  qiskit/pulse/instructions/frequency.py
  qiskit/qobj/converters/pulse_instruction.py
  qiskit/qobj/pulse_qobj.py
  qiskit/visualization/pulse/matplotlib.py
  releasenotes/notes/add-set-frequency-instruction-18a43ad97a5c6f7f.yaml
  releasenotes/notes/unify-instructions-and-commands-aaa6d8724b8a29d3.yaml
  test/python/pulse/test_schedule.py
  test/python/qobj/test_pulse_converter.py
  test/python/qobj/test_qobj.py
  test/python/visualization/references/schedule_matplotlib_ref.png
  test/python/visualization/test_pulse_visualization_output.py
Labels: automerge

#3971 Perform qobj circuit assembly in parallel
  qiskit/assembler/assemble_circuits.py
Labels: automerge, performance

#3981 Remove warnings about dt, dtm, and rep_time units changing
  qiskit/providers/models/backendconfiguration.py
  releasenotes/notes/remove-warnings-about-config-units-66e8525bd829db81.yaml
Labels: automerge

#3385 Allow generic callable to be inserted in CmdDef
  qiskit/pulse/instruction_schedule_map.py
  releasenotes/notes/inst-map-functions-84b176b4a14df449.yaml
  test/python/pulse/test_instruction_schedule_map.py
Labels: automerge

#3980 Qobj converter: commands.Snapshot to instructions.Snapshot
  qiskit/qobj/converters/pulse_instruction.py
Labels: automerge

#3984 self.assertWarns(DeprecationWarning) in quantum_info/test_states.py
  test/python/quantum_info/test_states.py
Labels: automerge

#3978 Drawing CCZ now consistent
  qiskit/visualization/latex.py
  qiskit/visualization/matplotlib.py
  qiskit/visualization/text.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: automerge

#3935 Command/Inst refactor: Acquire (and Kernel, Discriminator)
  qiskit/assembler/assemble_schedules.py
  qiskit/pulse/__init__.py
  qiskit/pulse/commands/acquire.py
  qiskit/pulse/commands/meas_opts.py
  qiskit/pulse/configuration.py
  qiskit/pulse/instructions/__init__.py
  qiskit/pulse/instructions/acquire.py
  qiskit/pulse/reschedule.py
  qiskit/qobj/converters/pulse_instruction.py
  qiskit/scheduler/utils.py
  releasenotes/notes/unify-instructions-and-commands-aaa6d8724b8a29d3.yaml
  test/python/pulse/test_commands.py
  test/python/pulse/test_reschedule.py
  test/python/pulse/test_schedule.py
  test/python/qobj/test_pulse_converter.py
  test/python/scheduler/test_utils.py
Labels: automerge

#3994 TestBasicAerQasmSimulator.test_qasm_simulator fails hourly
  test/python/basicaer/test_qasm_simulator.py
Labels: automerge

#3979 Populate equivalence library with existing gate definitions.
  qiskit/circuit/equivalence_library.py
  qiskit/circuit/instruction.py
  qiskit/circuit/parameter.py
  qiskit/circuit/parameterexpression.py
  qiskit/converters/circuit_to_gate.py
  qiskit/converters/circuit_to_instruction.py
  qiskit/extensions/standard/__init__.py
  qiskit/extensions/standard/equivalence_library.py
  test/python/circuit/test_equivalence.py
  test/python/circuit/test_gate_definitions.py
  test/python/circuit/test_parameters.py
Labels: automerge

#3985 Fix formatting issues with quantum_info doc strings
  qiskit/quantum_info/operators/base_operator.py
  qiskit/quantum_info/operators/channel/chi.py
  qiskit/quantum_info/operators/channel/choi.py
  qiskit/quantum_info/operators/channel/kraus.py
  qiskit/quantum_info/operators/channel/ptm.py
  qiskit/quantum_info/operators/channel/quantum_channel.py
  qiskit/quantum_info/operators/channel/stinespring.py
  qiskit/quantum_info/operators/channel/superop.py
  qiskit/quantum_info/operators/measures.py
  qiskit/quantum_info/operators/operator.py
  qiskit/quantum_info/operators/scalar_op.py
  qiskit/quantum_info/states/densitymatrix.py
  qiskit/quantum_info/states/quantum_state.py
  qiskit/quantum_info/states/statevector.py
  qiskit/quantum_info/states/utils.py
Labels: automerge, type: documentation

#3986 Add ``num_qubits`` attribute to ``QuantumState`` and ``BaseOperator``
  qiskit/quantum_info/operators/base_operator.py
  qiskit/quantum_info/states/quantum_state.py
  releasenotes/notes/state-operator-num-qubits-2cdfcefabb2836a3.yaml
  test/python/quantum_info/operators/channel/test_chi.py
  test/python/quantum_info/operators/channel/test_choi.py
  test/python/quantum_info/operators/channel/test_kraus.py
  test/python/quantum_info/operators/channel/test_ptm.py
  test/python/quantum_info/operators/channel/test_stinespring.py
  test/python/quantum_info/operators/channel/test_superop.py
  test/python/quantum_info/operators/test_operator.py
  test/python/quantum_info/operators/test_scalar_op.py
  test/python/quantum_info/states/test_densitymatrix.py
  test/python/quantum_info/states/test_statevector.py
Labels: automerge

#4006 Move release note to the correct directory
  releasenotes/notes/remove-sympy-instruction-e05f08e511397305.yaml
Labels: automerge

#3996 set depth/width for LookaheadSwap pass
  qiskit/transpiler/passes/routing/lookahead_swap.py
  releasenotes/notes/lookahead-swap-choose-depth-width-c265b261cb82b76d.yaml
  test/python/transpiler/test_lookahead_swap.py
Labels: automerge

#4005 Remove deprecated code! :)
  qiskit/compiler/schedule.py
  qiskit/providers/models/pulsedefaults.py
  qiskit/pulse/__init__.py
  qiskit/pulse/cmd_def.py
  qiskit/pulse/instruction_schedule_map.py
  qiskit/pulse/reschedule.py
  qiskit/qobj/converters/pulse_instruction.py
  releasenotes/notes/remove-deprecated-code-e48bbdd7cb0d61db.yaml
  test/python/pulse/test_cmd_def.py
  test/python/pulse/test_reschedule.py
  test/python/scheduler/test_basic_scheduler.py
Labels: automerge

#3992 add iswap and dcx gates
  .pylintrc
  qiskit/extensions/__init__.py
  qiskit/extensions/standard/__init__.py
  qiskit/extensions/standard/dcx.py
  qiskit/extensions/standard/equivalence_library.py
  qiskit/extensions/standard/iswap.py
  releasenotes/notes/iswap-dcx-gates-3e4b424aed0114d8.yaml
Labels: Changelog: New Feature, automerge

#4003 Each thread needs its own passmanager
  qiskit/compiler/transpile.py
  releasenotes/notes/fix-3925-c0e40ece078f2ce1.yaml
  test/python/compiler/test_transpiler.py
Labels: Changelog: Bugfix

#3936 Command/Inst refactor: Pulses and Play
  qiskit/assembler/assemble_schedules.py
  qiskit/pulse/__init__.py
  qiskit/pulse/commands/delay.py
  qiskit/pulse/commands/parametric_pulses.py
  qiskit/pulse/commands/pulse_decorators.py
  qiskit/pulse/commands/sample_pulse.py
  qiskit/pulse/instructions/__init__.py
  qiskit/pulse/instructions/play.py
  qiskit/pulse/pulse_lib/__init__.py
  qiskit/pulse/pulse_lib/discrete.py
  qiskit/pulse/pulse_lib/parametric_pulses.py
  qiskit/pulse/pulse_lib/pulse.py
  qiskit/pulse/pulse_lib/sample_pulse.py
  qiskit/pulse/pulse_lib/samplers/__init__.py
  qiskit/pulse/pulse_lib/samplers/decorators.py
  qiskit/qobj/converters/pulse_instruction.py
  qiskit/visualization/pulse/matplotlib.py
  releasenotes/notes/unify-instructions-and-commands-aaa6d8724b8a29d3.yaml
  test/python/compiler/test_assembler.py
  test/python/pulse/test_instructions.py
  test/python/pulse/test_schedule.py
  test/python/qobj/test_pulse_converter.py
  test/python/visualization/references/parametric_matplotlib_ref.png
  test/python/visualization/test_pulse_visualization_output.py
Labels: automerge

#3846 Docathon: pulse visualizer
  qiskit/visualization/__init__.py
  qiskit/visualization/pulse/__init__.py
  qiskit/visualization/pulse/interpolation.py
  qiskit/visualization/pulse/matplotlib.py
  qiskit/visualization/pulse/qcstyle.py
  qiskit/visualization/pulse_visualization.py
  test/python/visualization/test_pulse_visualization_output.py
Labels: type: documentation

#3931 Add ``StabilizerTable`` class
  qiskit/quantum_info/__init__.py
  qiskit/quantum_info/operators/__init__.py
  qiskit/quantum_info/operators/symplectic/__init__.py
  qiskit/quantum_info/operators/symplectic/stabilizer_table.py
  releasenotes/notes/stabilizer-table-97cf2949ffe2cea7.yaml
  test/python/quantum_info/operators/symplectic/test_stabilizer_table.py
Labels: Changelog: New Feature, automerge

#4017 Gate documentation overhaul
  qiskit/extensions/__init__.py
  qiskit/extensions/standard/__init__.py
  qiskit/extensions/standard/dcx.py
  qiskit/extensions/standard/h.py
  qiskit/extensions/standard/i.py
  qiskit/extensions/standard/iswap.py
  qiskit/extensions/standard/ms.py
  qiskit/extensions/standard/rx.py
  qiskit/extensions/standard/rxx.py
  qiskit/extensions/standard/ry.py
  qiskit/extensions/standard/ryy.py
  qiskit/extensions/standard/rz.py
  qiskit/extensions/standard/rzx.py
  qiskit/extensions/standard/rzz.py
  qiskit/extensions/standard/s.py
  qiskit/extensions/standard/swap.py
  qiskit/extensions/standard/t.py
  qiskit/extensions/standard/u1.py
  qiskit/extensions/standard/u2.py
  qiskit/extensions/standard/u3.py
  qiskit/extensions/standard/x.py
  qiskit/extensions/standard/y.py
  qiskit/extensions/standard/z.py
  releasenotes/notes/gate-documentation-5a376c8a471a13e1.yaml
  test/python/circuit/test_gate_definitions.py
Labels: automerge, type: documentation

#4033 Add pip check to CI jobs
  azure-pipelines.yml
Labels: automerge

#4027 Make pass manager config a flat class
  qiskit/transpiler/models.py
  qiskit/transpiler/pass_manager_config.py
Labels: priority: high

#3952 Add measure probability functions to QuantumState classes
  qiskit/quantum_info/states/__init__.py
  qiskit/quantum_info/states/counts.py
  qiskit/quantum_info/states/densitymatrix.py
  qiskit/quantum_info/states/quantum_state.py
  qiskit/quantum_info/states/statevector.py
  qiskit/result/result.py
  releasenotes/notes/state-probabilities-1956be0998281101.yaml
  test/python/quantum_info/states/test_densitymatrix.py
  test/python/quantum_info/states/test_statevector.py
Labels: Changelog: Deprecation, Changelog: New Feature, automerge

#3989 Clean up default class atol and rtol for operators and states
  qiskit/quantum_info/operators/base_operator.py
  qiskit/quantum_info/operators/channel/kraus.py
  qiskit/quantum_info/operators/channel/quantum_channel.py
  qiskit/quantum_info/operators/channel/stinespring.py
  qiskit/quantum_info/operators/operator.py
  qiskit/quantum_info/operators/scalar_op.py
  qiskit/quantum_info/states/densitymatrix.py
  qiskit/quantum_info/states/quantum_state.py
  qiskit/quantum_info/states/statevector.py
Labels: automerge

#3987 Add ``sample_measure`` to ``Statevector`` and ``DensityMatrix``
  qiskit/quantum_info/states/quantum_state.py
  releasenotes/notes/state-sample-measure-9710a22dfcb01ed6.yaml
  test/python/quantum_info/states/test_densitymatrix.py
  test/python/quantum_info/states/test_statevector.py
Labels: Changelog: New Feature, automerge

#3983 Update Statevector and DensityMatrix evolve to work with operator qargs
  qiskit/quantum_info/states/densitymatrix.py
  qiskit/quantum_info/states/statevector.py
Labels: automerge

#4040 Cache lexicographical topological sort key in DAGNode
  qiskit/dagcircuit/dagnode.py
  qiskit/dagcircuit/retworkx_dagcircuit.py
Labels: performance

#4042 fix equality check for controlled gates.
  qiskit/circuit/controlledgate.py
Labels: automerge

#4045 Add pygments to requirements list in setup.py and document it
  releasenotes/notes/add-pygments-dfe2cd949c237deb.yaml
  setup.py
Labels: automerge, priority: high

#3962 Bump cibuildwheel version
  azure-pipelines.yml
Labels: automerge

#3772 generalize dag.compose_back(), deprecate dag.extend_back()
  qiskit/dagcircuit/dagcircuit.py
  qiskit/transpiler/layout.py
  qiskit/transpiler/passes/optimization/optimize_swap_before_measure.py
  qiskit/transpiler/passes/routing/basic_swap.py
  qiskit/transpiler/passes/routing/layout_transformation.py
  qiskit/transpiler/passes/routing/stochastic_swap.py
  qiskit/transpiler/passes/utils/barrier_before_final_measurements.py
  releasenotes/notes/dag_compose-3847f210c6624f88.yaml
  test/python/dagcircuit/test_compose.py
  test/python/dagcircuit/test_dagcircuit.py
Labels: Changelog: Deprecation, automerge

#4051 Bugfix: Instruction name / pulse library name mismatch
  qiskit/assembler/assemble_schedules.py
  test/python/compiler/test_assembler.py
Labels: automerge

#3999 layout_method and routing_method selectors in transpile()
  qiskit/compiler/transpile.py
  qiskit/transpiler/pass_manager_config.py
  qiskit/transpiler/preset_passmanagers/level0.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  releasenotes/notes/transpile-method-selectors-1c426457743a6fa7.yaml
Labels: Changelog: API Change, automerge

#4054 BarrierBeforeFinalMeasurements pass to insert device-wide barrier.
  qiskit/transpiler/passes/utils/barrier_before_final_measurements.py
  releasenotes/notes/3937-transpiler-pushes-gates-behind-measurements-3799753c21878237.yaml
  test/python/transpiler/test_barrier_before_final_measurements.py
Labels: Changelog: Bugfix, automerge

#3926 Speed up fidelity computation
  qiskit/quantum_info/states/utils.py
Labels: automerge

#4049 Make pygments an optional dependency
  qiskit/circuit/quantumcircuit.py
  qiskit/qasm/__init__.py
  qiskit/qasm/pygments/__init__.py
  qiskit/qasm/pygments/lexer.py
  qiskit/tools/jupyter/library.py
  releasenotes/notes/add-pygments-dfe2cd949c237deb.yaml
  requirements-dev.txt
  requirements.txt
  setup.py
Labels: automerge

#4056 Rename sample_measure to sample_counts and sample_memory
  qiskit/quantum_info/states/quantum_state.py
  releasenotes/notes/state-sample-counts-9710a22dfcb01ed6.yaml
  test/python/quantum_info/states/test_densitymatrix.py
  test/python/quantum_info/states/test_statevector.py
Labels: automerge

#3362 Add env variable and user config option to suppress packaging warnings
  azure-pipelines.yml
  qiskit/__init__.py
  qiskit/user_config.py
  releasenotes/notes/suppress-packaging-warnings-396b38feb6b3d52f.yaml
  test/python/test_user_config.py
  tox.ini
Labels: Changelog: New Feature, automerge
