Repository Qiskit/qiskit, pull requests merged in 2020-11, with the labels that each got.

#5085 Allow full gates to be passed into get method of InstructionScheduleMap
  qiskit/pulse/instruction_schedule_map.py
  qiskit/scheduler/lowering.py
  test/python/pulse/test_instruction_schedule_map.py
Labels: automerge

#5316 Avoid deepcopy in sabre_swap
  qiskit/transpiler/passes/routing/sabre_swap.py
Labels: automerge, performance, stable backport potential

#5250 Add parameters attribute to schedules
  qiskit/pulse/channels.py
  qiskit/pulse/instructions/instruction.py
  qiskit/pulse/instructions/play.py
  qiskit/pulse/library/parametric_pulses.py
  qiskit/pulse/library/pulse.py
  qiskit/pulse/library/waveform.py
  qiskit/pulse/schedule.py
  releasenotes/notes/add-parameters-and-is_parameterized-to-pulse-d5695dd14e407537.yaml
  test/python/pulse/test_parameters.py
Labels: automerge

#5335 small patch for #5250
  qiskit/pulse/channels.py
Labels: automerge

#5273 Docs: add missing sections, fix formatting/typos
  README.md
  docs/conf.py
  qiskit/assembler/disassemble.py
  qiskit/circuit/parameter.py
  qiskit/circuit/parameterexpression.py
  qiskit/circuit/quantumcircuit.py
  qiskit/result/__init__.py
  qiskit/result/utils.py
  qiskit/visualization/__init__.py
  releasenotes/notes/0.15/add-rep-delay-c97d5aa8fc9696da.yaml
  releasenotes/notes/0.16/0.16.0-release-a06d0e1c3b705bda.yaml
  releasenotes/notes/0.16/instr-sched-map-params-9e8825134fe0b5c4.yaml
  releasenotes/notes/0.16/support-parameterexpressions-in-schedules-cbd0ac54cb01f617.yaml
  releasenotes/notes/0.16/timeline-drawer-1c5e9b4a7f50f8c8.yaml
  requirements-dev.txt
Labels: automerge, stable backport potential

#5286 Fix qubits indexing in Statevector._evolve_instruction
  qiskit/quantum_info/states/statevector.py
  releasenotes/notes/fix-qubits-indexing-in-evolve-instruction-7a3facdb53bc8892.yaml
  test/python/quantum_info/states/test_statevector.py
Labels: Changelog: Bugfix, automerge, stable backport potential

#5324 Add user config file options to control parallel execution
  qiskit/tools/parallel.py
  qiskit/user_config.py
  releasenotes/notes/paralle-config-options-97c1ad44ab76e052.yaml
  test/python/test_user_config.py
Labels: Changelog: API Change, Changelog: New Feature, automerge

#5248 Fix global phase tracking for Unroller, OneQubitEulerDecomposer, and ControlledGate
  qiskit/circuit/add_control.py
  qiskit/quantum_info/synthesis/one_qubit_decompose.py
  qiskit/transpiler/passes/basis/decompose.py
  qiskit/transpiler/passes/basis/unroller.py
  test/python/circuit/test_controlled_gate.py
  test/python/circuit/test_unitary.py
  test/python/transpiler/test_decompose.py
  test/python/transpiler/test_unroller.py
Labels: Changelog: Bugfix, automerge, stable backport potential

#5219 Add PiecewisePolynomialRotations and InverseChebychev to the circuit library
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/arithmetic/__init__.py
  qiskit/circuit/library/arithmetic/piecewise_polynomial_pauli_rotations.py
  releasenotes/notes/piecewise-polynomial-and-inverse-chebyshev-e3c4e0765b628c9f.yaml
  test/python/circuit/test_piecewise_polynomial.py
Labels: Changelog: New Feature, automerge

#5318 Improve init efficiency of BaseOperator for N-qubit operators
  qiskit/quantum_info/operators/base_operator.py
  qiskit/quantum_info/operators/channel/chi.py
  qiskit/quantum_info/operators/channel/choi.py
  qiskit/quantum_info/operators/channel/kraus.py
  qiskit/quantum_info/operators/channel/ptm.py
  qiskit/quantum_info/operators/channel/quantum_channel.py
  qiskit/quantum_info/operators/channel/stinespring.py
  qiskit/quantum_info/operators/channel/superop.py
  qiskit/quantum_info/operators/operator.py
  qiskit/quantum_info/operators/scalar_op.py
  qiskit/quantum_info/operators/symplectic/clifford.py
  qiskit/quantum_info/operators/symplectic/pauli_table.py
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
  qiskit/quantum_info/states/densitymatrix.py
  qiskit/quantum_info/states/quantum_state.py
  test/python/quantum_info/operators/channel/test_chi.py
  test/python/quantum_info/operators/test_operator.py
Labels: automerge

#5343 Fix bug in quantum channel subtraction
  qiskit/quantum_info/operators/channel/quantum_channel.py
  qiskit/quantum_info/operators/measures.py
  releasenotes/notes/fix-quantum_channel_sub-4a31394a7a1237d4.yaml
  test/python/quantum_info/operators/channel/test_linearops.py
Labels: Changelog: Bugfix, automerge, stable backport potential

#5314 Add ZSX basis to one qubit decomposition and optimization pass
  qiskit/quantum_info/synthesis/one_qubit_decompose.py
  qiskit/quantum_info/synthesis/two_qubit_decompose.py
  qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py
  test/python/quantum_info/test_synthesis.py
  test/python/transpiler/test_optimize_1q_decomposition.py
Labels: automerge, stable backport potential

#5319 Shift constant regex compiles to import time
  qiskit/circuit/register.py
  qiskit/result/counts.py
  qiskit/visualization/matplotlib.py
Labels: automerge

#5262 Deprecate schemas in qiskit-terra
  qiskit/providers/basicaer/basicaerjob.py
  qiskit/qobj/__init__.py
  qiskit/qobj/pulse_qobj.py
  qiskit/qobj/qasm_qobj.py
  qiskit/qobj/utils.py
  qiskit/validation/jsonschema/__init__.py
  qiskit/validation/jsonschema/schema_validation.py
  releasenotes/notes/deprecate-schemas-424c29fbd35c90de.yaml
  test/python/qobj/test_qobj.py
Labels: Changelog: Deprecation, automerge

#5368 Use deprecate_function for u1, u2, u3 methods
  qiskit/circuit/quantumcircuit.py
Labels: stable backport potential

#5370 Fix hasattr in Backend.set_options
  qiskit/providers/backend.py
Labels: Changelog: Bugfix, automerge, stable backport potential

#5375 Remove IBMQ provider from docs CI job
  qiskit/tools/jupyter/job_watcher.py
  tox.ini
Labels: stable backport potential

#5379 Fix parametric pulse hash generation
  qiskit/pulse/library/parametric_pulses.py
  test/python/pulse/test_pulse_lib.py
Labels: Changelog: Bugfix, automerge, stable backport potential

#5292 Remove lone identity gates in Optimize 1q decomposition pass
  qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py
  test/python/transpiler/test_optimize_1q_decomposition.py
Labels: Changelog: Bugfix, stable backport potential

#5344 Improve validation error messages for process fidelity
  qiskit/quantum_info/operators/measures.py
  test/python/basicaer/test_multi_registers_convention.py
  test/python/basicaer/test_unitary_simulator.py
  test/python/transpiler/test_consolidate_blocks.py
Labels: automerge, stable backport potential

#5295 Add circuit.tensor
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/circuit-tensor-f432dcd9302ded9f.yaml
  test/python/circuit/test_tensor.py
Labels: Changelog: New Feature, automerge

#5389 Prepare 0.16.1 release
  docs/conf.py
  qiskit/VERSION.txt
  setup.py
Labels: automerge

#5206 Conditional wires are drawn as classical wires in text circuit drawer
  qiskit/visualization/text.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: Changelog: Bugfix, automerge

#5298 transpile a list of circuits with a single element should return a list with a single element
  qiskit/compiler/transpile.py
  releasenotes/notes/transpile_singleton-61755c5cf1970111.yaml
  test/python/compiler/test_transpiler.py
Labels: Changelog: Bugfix, automerge

#5391 Use parameter for width in GaussianSquare
  qiskit/pulse/library/parametric_pulses.py
Labels: automerge

#5386 Fix docstring typos in qiskit.quantum_info.concurrence.
  qiskit/quantum_info/states/measures.py
Labels: automerge, type: documentation

#5356 Improve performance of matrix_equal function
  qiskit/quantum_info/operators/predicates.py
Labels: automerge, performance

#5382 Update x.py
  qiskit/circuit/library/standard_gates/x.py
Labels: automerge

#5336 Add R(v) gate; rotation wrt rotation vector
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/generalized_gates/__init__.py
  qiskit/circuit/library/generalized_gates/rv.py
  qiskit/circuit/library/standard_gates/r.py
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/rv-vector-rotation-gate-eb3311771ff7899b.yaml
  test/python/circuit/test_gate_definitions.py
Labels: automerge

#5416 Avoid module level sympy yet another time
  qiskit/transpiler/passes/optimization/template_matching/template_substitution.py
Labels: automerge, performance, priority: high

#5417 Fix bug when multiplying SparsePauliOp by np.int64
  qiskit/quantum_info/operators/base_operator.py
  releasenotes/notes/fix-op-ufunc-multiple-d1c59b236024f483.yaml
  test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
Labels: automerge, stable backport potential

#5192 Support complex parameters
  qiskit/circuit/gate.py
  qiskit/circuit/parameterexpression.py
  qiskit/circuit/quantumcircuit.py
  qiskit/extensions/hamiltonian_gate.py
  test/python/circuit/test_parameters.py
Labels: Changelog: New Feature

#5407 Convert tolerances metaclass to a mixin class
  qiskit/quantum_info/operators/base_operator.py
  qiskit/quantum_info/operators/channel/quantum_channel.py
  qiskit/quantum_info/operators/operator.py
  qiskit/quantum_info/operators/scalar_op.py
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
  qiskit/quantum_info/operators/tolerances.py
  qiskit/quantum_info/states/densitymatrix.py
  qiskit/quantum_info/states/quantum_state.py
  qiskit/quantum_info/states/statevector.py
Labels: automerge

#5181 Gradient functionality for parameter expressions
  qiskit/circuit/parameterexpression.py
  releasenotes/notes/parameter_expression_gradients-87db1ebad153025f.yaml
  test/python/circuit/test_parameters.py
Labels: Changelog: New Feature, automerge

#5272 Cache Bit and Register __repr__ and use for __eq__
  qiskit/circuit/bit.py
  qiskit/circuit/register.py
  qiskit/visualization/text.py
Labels: automerge, performance

#5267 Leverage retworkx for apply_operation* inner loop
  qiskit/dagcircuit/dagcircuit.py
  requirements.txt
  setup.py
Labels: automerge, performance

#5403 Use numpy sum instead of comprehension in _score_heuristic
  qiskit/transpiler/coupling.py
  qiskit/transpiler/passes/routing/sabre_swap.py
Labels: automerge, performance

#5420 Migrate qiskit.util module to qiskit.utils
  docs/apidocs/terra.rst
  docs/apidocs/utils.rst
  qiskit/test/decorators.py
  qiskit/util.py
  qiskit/utils/__init__.py
  qiskit/utils/deprecation.py
  qiskit/utils/multiprocessing.py
  qiskit/utils/units.py
  qiskit/visualization/__init__.py
  releasenotes/notes/deprecate_qiskit_utils-242f1b9700dd4cb8.yaml
Labels: automerge

#5281 LayoutTransformation when coupling_map=None
  qiskit/transpiler/passes/routing/layout_transformation.py
  test/python/transpiler/test_layout_transformation.py
Labels: automerge

#5346 Honor initial_layout when coupling map is None
  qiskit/transpiler/layout.py
  qiskit/transpiler/passes/layout/full_ancilla_allocation.py
  qiskit/transpiler/passes/utils/check_map.py
  qiskit/transpiler/preset_passmanagers/level0.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  releasenotes/notes/initial_layout_cp_none-8753d058743eeb79.yaml
  test/python/transpiler/test_preset_passmanagers.py
Labels: Changelog: Bugfix, automerge

#5290 warning when make test
  Makefile
Labels: automerge

#5429 Make optimize_1q_gates U and P aware
  qiskit/transpiler/passes/optimization/optimize_1q_gates.py
  test/python/transpiler/test_optimize_1q_gates.py
Labels: automerge

#5450 Handle type mismatch on bit and register __eq__
  qiskit/circuit/bit.py
  qiskit/circuit/register.py
  test/python/circuit/test_bit.py
  test/python/circuit/test_circuit_registers.py
Labels: automerge

#5439 Remove deprecated quantum_info methods
  qiskit/quantum_info/__init__.py
  qiskit/quantum_info/operators/base_operator.py
  qiskit/quantum_info/operators/measures.py
  qiskit/quantum_info/operators/quaternion.py
  qiskit/quantum_info/operators/tolerances.py
  qiskit/quantum_info/random.py
  qiskit/quantum_info/states/densitymatrix.py
  qiskit/quantum_info/states/quantum_state.py
  qiskit/quantum_info/states/random.py
  qiskit/quantum_info/states/statevector.py
  qiskit/quantum_info/synthesis/__init__.py
  qiskit/quantum_info/synthesis/two_qubit_decompose.py
  test/python/quantum_info/test_quaternions.py
Labels: automerge
