Repository Qiskit/qiskit, pull requests merged in 2020-10, with the labels that each got.

#5138 HoareOptimizer pass does preserve state between runs anymore
  qiskit/transpiler/passes/optimization/hoare_opt.py
  test/python/transpiler/test_hoare_opt.py
Labels: Changelog: Bugfix, automerge

#5173 Fix ``post_processing`` in linear amplitude function
  qiskit/circuit/library/arithmetic/linear_amplitude_function.py
  test/python/circuit/library/test_linear_amplitude_function.py
Labels: bug

#5172 The lookahead_swap pass is global_phase aware
  qiskit/transpiler/passes/routing/lookahead_swap.py
  test/python/transpiler/test_lookahead_swap.py
Labels: Changelog: Bugfix, global-phase

#5176 setting warnings=False for NoiseModel of FakeBackend
  qiskit/test/mock/fake_backend.py
Labels: automerge

#5175 Fix json load failure in mpl drawer
  qiskit/visualization/matplotlib.py
  releasenotes/notes/fix-mpl-json-load-failure-0da2a36351b13f5a.yaml
Labels: automerge

#5164 instruction_durations overwrites backend durations, does not extend them
  qiskit/compiler/transpile.py
  qiskit/transpiler/__init__.py
  qiskit/transpiler/instruction_durations.py
  test/python/circuit/test_scheduled_circuit.py
Labels: automerge

#4987 Add back repr for Result and related classes
  qiskit/result/models.py
  qiskit/result/result.py
  test/python/result/test_result.py
Labels: automerge

#5091 Fix in the circuit text drawer when a custom gate with even-length label is controlled
  qiskit/visualization/text.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: Changelog: Bugfix, automerge

#5146 Avoid excessive neighbor discovery in NoiseAdaptiveLayout
  qiskit/transpiler/passes/layout/noise_adaptive_layout.py
Labels: automerge, performance

#5170 Build BlueprintCircuit before inverse and compose
  qiskit/circuit/library/blueprintcircuit.py
  releasenotes/notes/build-blueprintcircuit-before-inverse-8ef85f6389588fe0.yaml
  test/python/circuit/library/test_blueprintcircuit.py
Labels: Changelog: Bugfix, automerge

#5182 Add per-qubit duration in a scheduled circuit
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_scheduled_circuit.py
Labels: automerge

#5193 add delay as a builtin instruction
  qiskit/compiler/transpile.py
  qiskit/transpiler/passes/basis/basis_translator.py
  qiskit/transpiler/passes/basis/ms_basis_decomposer.py
  qiskit/transpiler/passes/basis/unroll_custom_definitions.py
  qiskit/transpiler/passes/basis/unroller.py
  qiskit/transpiler/passes/optimization/commutation_analysis.py
Labels: automerge

#5194 Update Code of Conduct
  CODE_OF_CONDUCT.md
Labels: automerge

#5201 Remove deprecated DAGNode dict constructor argument
  qiskit/dagcircuit/dagnode.py
  qiskit/dagcircuit/releasenotes/notes/remove-dagnode-dict-32fa35479c0a8331.yaml
Labels: Changelog: Removal

#4979 Deprecate MSGate
  qiskit/circuit/library/generalized_gates/__init__.py
  qiskit/circuit/library/generalized_gates/gms.py
  qiskit/circuit/library/standard_gates/__init__.py
  qiskit/circuit/library/standard_gates/equivalence_library.py
  qiskit/circuit/library/standard_gates/ms.py
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/deprecate-MSGate-class-40495351761c202f.yaml
Labels: Changelog: Deprecation, automerge

#5211 Fix rendering of "pi" in the U3 documentation
  qiskit/circuit/library/standard_gates/u3.py
Labels: automerge, type: documentation

#5068 Probability distribution circuits
  .pylintrc
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/probability_distributions/__init__.py
  qiskit/circuit/library/probability_distributions/lognormal.py
  qiskit/circuit/library/probability_distributions/normal.py
  qiskit/circuit/library/probability_distributions/uniform.py
  releasenotes/notes/probability-distribution-circuits-d65c8e974001ca8c.yaml
  test/python/circuit/library/test_probability_distributions.py
Labels: Changelog: New Feature, automerge

#5222 Result object to warn when fetching by name is ambiguous.
  qiskit/result/result.py
  releasenotes/notes/3207-Results-object-should-inform-user-if-multiple-results-of-same-name-5757be483b0979c3.yaml
  test/python/result/test_result.py
Labels: automerge

#5218 Test circuit drawer uses "π" instead of "pi"
  qiskit/circuit/tools/pi_check.py
  test/python/circuit/test_tools.py
  test/python/visualization/references/circuit_text_ref_cp437.txt
  test/python/visualization/references/circuit_text_ref_utf8.txt
  test/python/visualization/test_circuit_text_drawer.py
Labels: Changelog: New Feature

#5225 substitute_node only in single-qubit gates with singleton decompositions
  qiskit/transpiler/passes/basis/decompose.py
  qiskit/transpiler/passes/basis/unroller.py
  releasenotes/notes/preserve-qreg-order-when-unrolling-and-decomposing-3d1789cd2eb4a8f9.yaml
  test/python/transpiler/test_decompose.py
  test/python/transpiler/test_unroller.py
Labels: Changelog: Bugfix, automerge

#5216 Add Optimize1qGatesDecomposition to optimize 1q gates using Euler Decomposer
  qiskit/quantum_info/synthesis/one_qubit_decompose.py
  qiskit/quantum_info/synthesis/two_qubit_decompose.py
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/optimization/__init__.py
  qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py
  qiskit/transpiler/passes/synthesis/unitary_synthesis.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  releasenotes/notes/optimize-1q-decomposition-53c78d7430b07c0c.yaml
  test/python/compiler/test_transpiler.py
  test/python/quantum_info/test_synthesis.py
  test/python/transpiler/test_optimize_1q_decomposition.py
Labels: Changelog: New Feature, automerge

#5231 Fix quantum_info docstrings with formula rendering issues
  qiskit/quantum_info/states/measures.py
  qiskit/quantum_info/states/utils.py
Labels: automerge, type: documentation

#5238 check absolute value for tiny angle removal
  qiskit/quantum_info/synthesis/one_qubit_decompose.py
  test/python/compiler/test_transpiler.py
Labels: automerge

#5239 fix statevector handling global phase
  qiskit/quantum_info/states/statevector.py
  test/python/quantum_info/states/test_statevector.py
Labels: automerge

#5242 Remove a stray file
  test.py
Labels: automerge

#5243 Bump version
  .mergify.yml
  docs/conf.py
  qiskit/VERSION.txt
  setup.py
Labels: automerge

#5141 Add dt/dtm to the circuit config
  qiskit/providers/models/backendconfiguration.py
  qiskit/schemas/examples/backend_configuration_openqasm_example.json
  qiskit/schemas/examples/backend_configuration_openqasm_simulator_example.json
  qiskit/test/mock/fake_qasm_simulator.py
  test/python/providers/test_backendconfiguration.py
Labels: automerge

#4858 Register or QuantumCircuit raises when an ambiguous non-integer gets passed to
  qiskit/circuit/quantumcircuit.py
  qiskit/circuit/register.py
  releasenotes/notes/must_pass_integer_num_bits-98d509c2ccfc53da.yaml
  test/python/circuit/test_circuit_properties.py
  test/python/circuit/test_circuit_registers.py
Labels: Changelog: API Change, automerge

#5187 Fix a bug with the way frequency is scaled in pulse_instruction.py (#4872)
  qiskit/assembler/assemble_schedules.py
  qiskit/qobj/converters/pulse_instruction.py
  test/python/qobj/test_pulse_converter.py
Labels: automerge

#5139 adding draw_title flag
  qiskit/pulse/library/parametric_pulses.py
  qiskit/pulse/library/pulse.py
  qiskit/pulse/library/waveform.py
  qiskit/pulse/schedule.py
  qiskit/visualization/pulse/matplotlib.py
  qiskit/visualization/pulse_visualization.py
Labels: automerge

#5153 Adding Pauli to the standard gate library
  qiskit/circuit/library/generalized_gates/__init__.py
  qiskit/circuit/library/generalized_gates/pauli.py
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/pauli-instruction-6e91f534ff19036c.yaml
  test/python/circuit/test_extensions_standard.py
  test/python/circuit/test_gate_definitions.py
Labels: Changelog: New Feature

#5258 Move scipy.stats imports to runtime
  qiskit/circuit/library/probability_distributions/lognormal.py
  qiskit/circuit/library/probability_distributions/normal.py
  qiskit/quantum_info/operators/random.py
Labels: automerge, performance

#5265 Fix C4XGate QASM definition.
  qiskit/circuit/library/standard_gates/x.py
  qiskit/qasm/libs/qelib1.inc
  releasenotes/notes/c4xgate-fix-inconsistent-qasm-def-b979edcc93a591d7.yaml
Labels: Changelog: Bugfix, automerge

#5263 Use numpy eigh instead of scipy eigh with driver kwarg
  qiskit/quantum_info/synthesis/two_qubit_decompose.py
Labels: automerge

#5229 allow Initialize from labels
  qiskit/extensions/quantum_initializer/initializer.py
  releasenotes/notes/initialize_from_labels-0f18f37188031d83.yaml
  test/python/circuit/test_initializer.py
Labels: Changelog: New Feature, automerge

#5288 classical_function decorator to handle parsing indented define.
  qiskit/circuit/classicalfunction/__init__.py
Labels: Changelog: Bugfix, automerge

#5289 Fix release note about the classical function compiler
  releasenotes/notes/0.16/classical_funciton_compliation-c5d75e0aaf04c8f1.yaml
Labels: automerge

#5279 Paul Feature_map update with rotation factor (alpha)
  qiskit/circuit/library/data_preparation/pauli_feature_map.py
  releasenotes/notes/paul_feature_alpha-1fdba69c577c6b4d.yaml
  test/python/circuit/library/test_pauli_feature_map.py
Labels: automerge

#5253 Fix issue with frequency change visualization.
  qiskit/visualization/pulse/matplotlib.py
Labels: Changelog: Bugfix, automerge, bug

#5256 CCX Equation Corrected
  qiskit/circuit/library/standard_gates/x.py
Labels: automerge

#5302 Fix bug: execute valid circuits built with delays
  qiskit/execute.py
  releasenotes/notes/bugfix-delays-are-supported-d294bc1cb478d149.yaml
  test/python/circuit/test_scheduled_circuit.py
Labels: automerge, stable backport potential

#5284 Fix display of backend name in Result.__repr__
  qiskit/result/result.py
  test/python/result/test_result.py
Labels: Changelog: Bugfix, automerge, stable backport potential

#5266 Skip classical function compiler tests if tweedledum unavailable.
  test/python/classical_function_compiler/test_classical_function.py
  test/python/classical_function_compiler/test_parse.py
  test/python/classical_function_compiler/test_simulate.py
  test/python/classical_function_compiler/test_synthesis.py
  test/python/classical_function_compiler/test_typecheck.py
Labels: automerge

#5223 Make all mpl styles json loads and update visualization code and docs
  MANIFEST.in
  postBuild
  qiskit/circuit/quantumcircuit.py
  qiskit/user_config.py
  qiskit/visualization/__init__.py
  qiskit/visualization/circuit_visualization.py
  qiskit/visualization/latex.py
  qiskit/visualization/matplotlib.py
  qiskit/visualization/qcstyle.py
  qiskit/visualization/styles/bw.json
  qiskit/visualization/styles/default.json
  qiskit/visualization/styles/iqx.json
  releasenotes/notes/load-user-style-json-files-823590b03f015e4b.yaml
  test/ipynb/mpl/references/bw.png
  test/ipynb/mpl/references/iqx_color.png
  test/ipynb/mpl/references/partial_layout.png
  test/ipynb/mpl/references/reverse_bits.png
  test/ipynb/mpl/references/subfont.png
  test/ipynb/mpl/references/user_style.png
  test/ipynb/mpl/test_circuit_matplotlib_drawer.py
  test/ipynb/mpl/user_style.json
  test/python/test_user_config.py
Labels: automerge

#5245 Remove schedule component
  qiskit/compiler/assemble.py
  qiskit/pulse/instructions/instruction.py
  qiskit/pulse/interfaces.py
  qiskit/pulse/schedule.py
  qiskit/pulse/transforms.py
  qiskit/visualization/pulse_visualization.py
  releasenotes/notes/deprecate-schedule-component-e7ab3654fe4fb8bf.yaml
Labels: automerge
