Repository Qiskit/qiskit, pull requests merged in 2021-01, with the labels that each got.

#5576 Avoid module level sympy yet another time
  qiskit/pulse/utils.py
Labels: performance

#5425 Fix pulse drawer v2 bugs
  qiskit/visualization/pulse_v2/generators/frame.py
  qiskit/visualization/pulse_v2/generators/waveform.py
Labels: automerge

#5558 docs: fix simple typo, omisiions -> omissions
  qiskit/circuit/library/boolean_logic/quantum_and.py
  qiskit/circuit/library/boolean_logic/quantum_or.py
Labels: automerge

#5562 Durations populated from calibrations
  qiskit/compiler/transpile.py
  releasenotes/notes/bugfix-inst-durations-from-calibrations-2b3e4698b1e20ca2.yaml
  test/python/compiler/test_transpiler.py
Labels: Changelog: Bugfix, automerge

#5583 Add ZSX Euler basis to UnitarySynthesis pass.
  qiskit/transpiler/passes/synthesis/unitary_synthesis.py
Labels: Changelog: Bugfix, automerge, stable backport potential

#5508 Fix quantum Fisher information computation based on overlap
  qiskit/opflow/gradients/circuit_qfis/overlap_diag.py
  releasenotes/notes/fix-overlap-qfis-252a97c776972aa0.yaml
  test/python/opflow/test_gradients.py
Labels: Changelog: Bugfix, automerge

#5546 Use actual gate name in backend monitor
  qiskit/tools/jupyter/backend_monitor.py
  qiskit/tools/monitor/overview.py
  releasenotes/notes/jupyter-gates-4940e03b3e4b6e12.yaml
  test/python/providers/test_backendproperties.py
  test/python/tools/monitor/test_backend_monitor.py
  test/python/transpiler/test_instruction_durations.py
Labels: Changelog: Bugfix, automerge, stable backport potential

#5588 Fix global phase handling in circuit.repeat
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/fix-global-phase-upon-repeat-f742f4c0201fea97.yaml
  test/python/circuit/test_circuit_operations.py
Labels: Changelog: Bugfix, automerge

#5572 Improve decomposition of (multi-)controlled-z
  qiskit/circuit/add_control.py
  test/python/circuit/test_controlled_gate.py
Labels: automerge

#5564 Remove deprecated pulse code
  qiskit/pulse/__init__.py
  qiskit/pulse/instructions/acquire.py
  qiskit/pulse/instructions/instruction.py
  qiskit/pulse/library/__init__.py
  qiskit/pulse/library/parametric_pulses.py
  qiskit/pulse/library/sample_pulse.py
  qiskit/pulse/pulse_lib/__init__.py
  qiskit/pulse/pulse_lib/samplers/__init__.py
  qiskit/visualization/pulse/matplotlib.py
  qiskit/visualization/pulse_visualization.py
  releasenotes/notes/0.14/add-title-to-pulse-drawer-69db1ddb2f696367.yaml
  releasenotes/notes/remove-deprecated-pulse-code-d98fc32cf385221a.yaml
  test/python/compiler/test_assembler.py
  test/python/pulse/test_parameters.py
  test/python/pulse/test_pulse_lib.py
Labels: Changelog: Removal, automerge

#5570 Avoid collecting non atomic nodes in 1q runs
  qiskit/dagcircuit/dagcircuit.py
  test/python/dagcircuit/test_dagcircuit.py
Labels: Changelog: Bugfix, automerge

#5593 Unroll parametervectors in circuit.execute
  qiskit/compiler/assemble.py
  releasenotes/notes/ParameterVectors-aren't-unrolled-by-execute-c8bd393818e926b0.yaml
  test/python/compiler/test_assembler.py
Labels: Changelog: Bugfix, automerge

#5477 Add qiskit.opflow and qiskit.algorithms to docs
  docs/apidocs/algorithms.rst
  docs/apidocs/opflow.rst
  docs/apidocs/qiskit.opflow.converters.rst
  docs/apidocs/qiskit.opflow.evolutions.rst
  docs/apidocs/qiskit.opflow.expectations.rst
  docs/apidocs/qiskit.opflow.gradients.rst
  docs/apidocs/qiskit.opflow.legacy.rst
  docs/apidocs/qiskit.opflow.list_ops.rst
  docs/apidocs/qiskit.opflow.primitive_ops.rst
  docs/apidocs/qiskit.opflow.state_fns.rst
  docs/apidocs/terra.rst
  docs/conf.py
  qiskit/algorithms/__init__.py
  qiskit/opflow/legacy/common.py
Labels: automerge

#5602 Propagate Pauli phase when evaluating PauliOp
  qiskit/opflow/primitive_ops/pauli_op.py
  releasenotes/notes/bugfix-propagate-pauli-phase-in-pauliop-eval-b7fa0d14b1e3b61a.yaml
  test/python/opflow/test_op_construction.py
Labels: Changelog: Bugfix

#5563 Output transpiled circuit in dt
  qiskit/compiler/transpile.py
  releasenotes/notes/convert-delay-units-62b3a5cf7650a0f4.yaml
  releasenotes/notes/transpile-delay-units-to-dt-538aa4b89f4ee94c.yaml
  test/python/circuit/test_scheduled_circuit.py
  test/python/compiler/test_transpiler.py
Labels: Changelog: Bugfix, automerge

#5560 Implement iterating/collecting PauliSumOp coefficients #5547
  qiskit/opflow/primitive_ops/pauli_sum_op.py
  test/python/opflow/test_pauli_sum_op.py
Labels: automerge

#5581 Replace legacy pulse drawer
  qiskit/pulse/__init__.py
  qiskit/pulse/library/parametric_pulses.py
  qiskit/pulse/library/pulse.py
  qiskit/pulse/library/waveform.py
  qiskit/pulse/schedule.py
  qiskit/visualization/__init__.py
  qiskit/visualization/pulse/interpolation.py
  qiskit/visualization/pulse/qcstyle.py
  qiskit/visualization/pulse_v2/core.py
  qiskit/visualization/pulse_v2/events.py
  qiskit/visualization/pulse_v2/interface.py
  qiskit/visualization/pulse_v2/stylesheet.py
  qiskit/visualization/pulse_visualization.py
  releasenotes/notes/replace-pulse-drawer-f9f667c8f71e1e02.yaml
  test/python/visualization/pulse_v2/test_events.py
  test/python/visualization/test_pulse_visualization_output.py
Labels: automerge

#5597 Consolidate Euler basis gate lists
  qiskit/quantum_info/synthesis/one_qubit_decompose.py
  qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py
  qiskit/transpiler/passes/synthesis/unitary_synthesis.py
Labels: automerge

#5613 Update setup.py: REQUIREMENTS
  MANIFEST.in
  setup.py
Labels: automerge

#5594 Log warning instead of raise exception in channel measures
  qiskit/quantum_info/operators/measures.py
  releasenotes/notes/process-fidelity-target-5bac750390aa3306.yaml
  test/python/quantum_info/operators/test_measures.py
Labels: Changelog: API Change, automerge

#5598 Handle log level cleanup in logging tests
  test/python/basicaer/test_basicaer_qobj_headers.py
  test/python/basicaer/test_qasm_simulator.py
  test/python/compiler/test_assembler.py
  test/python/compiler/test_transpiler.py
  test/python/transpiler/test_pass_scheduler.py
Labels: automerge

#5548 Improved handling of ``params`` argument in ``Gradient.convert``
  qiskit/circuit/parametervector.py
  qiskit/opflow/gradients/circuit_gradients/lin_comb.py
  qiskit/opflow/gradients/circuit_gradients/param_shift.py
  qiskit/opflow/gradients/circuit_qfis/circuit_qfi.py
  qiskit/opflow/gradients/circuit_qfis/lin_comb_full.py
  qiskit/opflow/gradients/circuit_qfis/overlap_block_diag.py
  qiskit/opflow/gradients/circuit_qfis/overlap_diag.py
  qiskit/opflow/gradients/gradient.py
  qiskit/opflow/gradients/hessian.py
  qiskit/opflow/gradients/natural_gradient.py
  qiskit/opflow/gradients/qfi.py
  test/python/opflow/test_gradients.py
Labels: automerge

#5517 Amplitude Estimation algorithms
  qiskit/algorithms/__init__.py
  qiskit/algorithms/amplitude_estimators/__init__.py
  qiskit/algorithms/amplitude_estimators/ae.py
  qiskit/algorithms/amplitude_estimators/ae_utils.py
  qiskit/algorithms/amplitude_estimators/amplitude_estimator.py
  qiskit/algorithms/amplitude_estimators/estimation_problem.py
  qiskit/algorithms/amplitude_estimators/fae.py
  qiskit/algorithms/amplitude_estimators/iae.py
  qiskit/algorithms/amplitude_estimators/mlae.py
  qiskit/circuit/library/grover_operator.py
  test/python/algorithms/test_amplitude_estimators.py
Labels: Changelog: New Feature

#5501 Fix & refactor the linear combination of unitaries gradients
  qiskit/opflow/gradients/circuit_gradients/lin_comb.py
  qiskit/opflow/gradients/circuit_qfis/lin_comb_full.py
  qiskit/opflow/gradients/natural_gradient.py
  test/python/opflow/test_gradients.py
Labels: Changelog: Bugfix, performance

#5626 Fix codeowners matching rule for utils
  .github/CODEOWNERS
Labels: automerge

#5474 Fix global phase in OneQubitEulerDecomposer using PSX and ZSX basis and in Diagonal gate
  qiskit/circuit/library/generalized_gates/diagonal.py
  qiskit/extensions/quantum_initializer/diagonal.py
  qiskit/quantum_info/operators/operator.py
  qiskit/quantum_info/synthesis/one_qubit_decompose.py
  test/python/circuit/library/test_diagonal.py
  test/python/circuit/test_diagonal_gate.py
  test/python/quantum_info/test_synthesis.py
  test/randomized/test_synthesis.py
Labels: Changelog: Bugfix, automerge, stable backport potential

#5432 Add `OpShape` class for dealing with state and operator subsystem dimensions
  qiskit/quantum_info/operators/base_operator.py
  qiskit/quantum_info/operators/channel/chi.py
  qiskit/quantum_info/operators/channel/choi.py
  qiskit/quantum_info/operators/channel/kraus.py
  qiskit/quantum_info/operators/channel/ptm.py
  qiskit/quantum_info/operators/channel/quantum_channel.py
  qiskit/quantum_info/operators/channel/stinespring.py
  qiskit/quantum_info/operators/channel/superop.py
  qiskit/quantum_info/operators/op_shape.py
  qiskit/quantum_info/operators/operator.py
  qiskit/quantum_info/operators/scalar_op.py
  qiskit/quantum_info/operators/symplectic/clifford.py
  qiskit/quantum_info/operators/symplectic/pauli.py
  qiskit/quantum_info/operators/symplectic/pauli_table.py
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
  qiskit/quantum_info/operators/symplectic/stabilizer_table.py
  qiskit/quantum_info/states/densitymatrix.py
  qiskit/quantum_info/states/quantum_state.py
  qiskit/quantum_info/states/statevector.py
  qiskit/quantum_info/states/utils.py
Labels: automerge, mod: quantum info

#5464 Add `reverse_qargs` method to `Statevector` and `DensityMatrix`
  qiskit/quantum_info/operators/op_shape.py
  qiskit/quantum_info/states/densitymatrix.py
  qiskit/quantum_info/states/statevector.py
  releasenotes/notes/state_reverse_qargs-f2f3c9a3e1c3aaa0.yaml
  test/python/quantum_info/states/test_densitymatrix.py
  test/python/quantum_info/states/test_statevector.py
Labels: Changelog: New Feature, automerge, mod: quantum info

#5653 Minor style improvements in disassemble.py
  qiskit/assembler/disassemble.py
  qiskit/pulse/instructions/acquire.py
Labels: automerge

#5655 [Stable] Improve 1q decomposition pass with multiple matching basis (#5431)
  qiskit/dagcircuit/dagcircuit.py
  qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py
  test/python/dagcircuit/test_dagcircuit.py
  test/python/transpiler/test_optimize_1q_decomposition.py
Labels: Changelog: Bugfix, automerge, stable-backport

#5660 Fix U2Gate decomposition in QuantumCircuit.u2 deprecation message.
  qiskit/circuit/quantumcircuit.py
Labels: Changelog: Bugfix, automerge, stable backport potential

#5552 Add ``PauliTwoDesign`` to the circuit library
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/n_local/__init__.py
  qiskit/circuit/library/n_local/n_local.py
  qiskit/circuit/library/n_local/pauli_two_design.py
  qiskit/circuit/parametervector.py
  releasenotes/notes/randompauli-76928cc17c840aea.yaml
  test/python/circuit/library/test_nlocal.py
  test/python/circuit/library/test_random_pauli.py
  test/python/circuit/test_parameters.py
  test/python/quantum_info/operators/test_random.py
Labels: Changelog: New Feature, automerge

#5601 Create explicit C3XGate/C4XGate in MCXGrayCode
  qiskit/circuit/library/standard_gates/x.py
  releasenotes/notes/mcx_create_explicit_c3x_c4x-d4475c0bb70fae49.yaml
  test/python/circuit/test_controlled_gate.py
Labels: automerge

#5668 More efficient C3X implementation
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/standard_gates/__init__.py
  qiskit/circuit/library/standard_gates/x.py
  qiskit/qasm/libs/qelib1.inc
  releasenotes/notes/improved-c3x-decomposition-aa812a0bc8280c7a.yaml
  test/python/circuit/test_controlled_gate.py
Labels: automerge, stable backport potential

#5550 Issue 5549 template matching
  qiskit/transpiler/passes/optimization/template_optimization.py
  releasenotes/notes/issue-5549-0b4e71d44dc13ce5.yaml
  test/python/transpiler/test_template_matching.py
Labels: Changelog: New Feature, automerge

#5618 Fix global phase tracking around DAGCircuit.substitute_node.
  qiskit/circuit/quantumcircuit.py
  qiskit/dagcircuit/dagcircuit.py
  qiskit/transpiler/passes/basis/basis_translator.py
  qiskit/transpiler/passes/basis/unroller.py
  releasenotes/notes/dagcircuit-fix-substitute-node-global-phase-usage-ee05476a7d0b24c6.yaml
  test/python/circuit/library/test_grover_operator.py
  test/python/circuit/test_circuit_qasm.py
  test/python/compiler/test_transpiler.py
  test/python/transpiler/test_basis_translator.py
  test/python/transpiler/test_unroller.py
Labels: Changelog: Bugfix, automerge, global-phase, stable backport potential

#5664 Allow integers as objective qubits in the ``EstimationProblem``
  qiskit/algorithms/amplitude_estimators/estimation_problem.py
  test/python/algorithms/test_amplitude_estimators.py
Labels: automerge

#5521 Enable user defined cost dict for templates
  qiskit/transpiler/passes/optimization/template_matching/template_substitution.py
  qiskit/transpiler/passes/optimization/template_optimization.py
  releasenotes/notes/issue-5232-995e0d1a57c7187e.yaml
Labels: Changelog: New Feature, automerge

#5671 Add unroll step to level2 passmanager optimization loop
  qiskit/transpiler/preset_passmanagers/level2.py
  test/python/transpiler/test_preset_passmanagers.py
Labels: Changelog: Bugfix, stable backport potential

#5685 Change collect_1q_runs return for performance
  qiskit/dagcircuit/dagcircuit.py
Labels: automerge, performance

#5682 Tune performance of optimize_1q_decomposition
  qiskit/dagcircuit/dagcircuit.py
  qiskit/quantum_info/operators/operator.py
  qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py
  test/python/compiler/test_transpiler.py
Labels: automerge, performance

#5687 Pulse builder interface: fix spelling
  qiskit/pulse/builder.py
Labels: automerge

#5595 Update the definition of the Hellinger fidelity
  qiskit/quantum_info/analysis/distance.py
  releasenotes/notes/fix_hellinger_fidelity_def-7f60d53e3577fdaf.yaml
Labels: Changelog: Bugfix, automerge, stable backport potential

#5704 enable Operator() of circuits with delay instruction
  qiskit/circuit/delay.py
  test/python/pulse/test_instructions.py
Labels: automerge

#5327 Move style docs to qcstyle.DefaultStyle
  qiskit/circuit/quantumcircuit.py
  qiskit/visualization/__init__.py
  qiskit/visualization/circuit_visualization.py
  qiskit/visualization/qcstyle.py
Labels: automerge

#5705 Raise if attempting to convert parameterized circuit to qasm.
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/library/test_blueprintcircuit.py
  test/python/circuit/test_circuit_qasm.py
Labels: automerge

#5693 Exploit symmetry in QFI and Hessian construction
  qiskit/opflow/gradients/circuit_qfis/lin_comb_full.py
  qiskit/opflow/gradients/circuit_qfis/overlap_block_diag.py
  qiskit/opflow/gradients/circuit_qfis/overlap_diag.py
  qiskit/opflow/gradients/hessian.py
  qiskit/utils/arithmetic.py
  test/python/test_util.py
Labels: mod: opflow

#5659 Rename aqua_globals to algorithm_globals
  qiskit/algorithms/amplitude_amplifiers/grover.py
  qiskit/algorithms/optimizers/adam_amsgrad.py
  qiskit/algorithms/optimizers/gsls.py
  qiskit/algorithms/optimizers/p_bfgs.py
  qiskit/algorithms/optimizers/spsa.py
  qiskit/algorithms/variational_algorithm.py
  qiskit/opflow/evolutions/trotterizations/qdrift.py
  qiskit/opflow/operator_base.py
  qiskit/opflow/state_fns/dict_state_fn.py
  qiskit/opflow/state_fns/vector_state_fn.py
  qiskit/utils/__init__.py
  qiskit/utils/algorithm_globals.py
  test/python/algorithms/test_measure_error_mitigation.py
  test/python/algorithms/test_optimizer_aqgd.py
  test/python/algorithms/test_optimizer_nft.py
  test/python/algorithms/test_optimizers.py
  test/python/algorithms/test_optimizers_scikitquant.py
  test/python/algorithms/test_vqe.py
  test/python/opflow/test_gradients.py
  test/python/opflow/test_pauli_expectation.py
Labels: automerge, mod: algorithms, mod: opflow

#5696 Fix deprecation msg on NumPyMinimumEigensolver and opflow
  qiskit/algorithms/minimum_eigen_solvers/numpy_minimum_eigen_solver.py
  qiskit/opflow/primitive_ops/pauli_op.py
Labels: mod: algorithms, mod: opflow

#5740 Fix typo adding non-gates to _collect_1q_runs() output
  qiskit/dagcircuit/dagcircuit.py
  releasenotes/notes/fix-invalid-ops-collect-runs-b9fd2f2e85136834.yaml
  test/python/dagcircuit/test_dagcircuit.py
Labels: Changelog: Bugfix, automerge, priority: high, stable-backport

#5741 Prepare 0.16.3 release
  docs/conf.py
  qiskit/VERSION.txt
  setup.py
Labels: automerge

#5689 Fix gradient use of the AQGD optimizer
  qiskit/algorithms/optimizers/aqgd.py
  qiskit/opflow/gradients/derivative_base.py
  test/python/algorithms/test_optimizer_aqgd.py
Labels: mod: algorithms

#5623 Improve Expectation and Evolution for PauliSumOp (PauliSumOp 3/3)
  qiskit/opflow/converters/abelian_grouper.py
  qiskit/opflow/converters/pauli_basis_change.py
  qiskit/opflow/evolutions/pauli_trotter_evolution.py
  qiskit/opflow/evolutions/trotterizations/qdrift.py
  qiskit/opflow/evolutions/trotterizations/suzuki.py
  qiskit/opflow/expectations/aer_pauli_expectation.py
  qiskit/opflow/expectations/pauli_expectation.py
  qiskit/opflow/primitive_ops/__init__.py
  qiskit/opflow/primitive_ops/pauli_sum_op.py
  qiskit/opflow/primitive_ops/primitive_op.py
  test/python/algorithms/test_vqe.py
  test/python/opflow/test_abelian_grouper.py
  test/python/opflow/test_aer_pauli_expectation.py
  test/python/opflow/test_evolution.py
  test/python/opflow/test_pauli_basis_change.py
  test/python/opflow/test_pauli_sum_op.py
Labels: mod: opflow

#5728 trace-preserving property for QuantumChannel verified more precisely
  qiskit/quantum_info/operators/channel/quantum_channel.py
Labels: automerge
