Repository Qiskit/qiskit, pull requests merged in 2021-06, with the labels that each got.

#6167 Enable lo frequencies to be passed in circuits
  qiskit/assembler/assemble_circuits.py
  qiskit/assembler/assemble_schedules.py
  qiskit/assembler/disassemble.py
  qiskit/compiler/assembler.py
  qiskit/execute_function.py
  qiskit/providers/models/backendconfiguration.py
  qiskit/qobj/converters/lo_config.py
  qiskit/qobj/pulse_qobj.py
  qiskit/qobj/qasm_qobj.py
  qiskit/schemas/backend_configuration_schema.json
  qiskit/schemas/qobj_schema.json
  qiskit/test/mock/backends/yorktown/conf_yorktown.json
  qiskit/test/mock/fake_qasm_simulator.py
  releasenotes/notes/lo-freqs-circuit-c2ec161873eb4a68.yaml
  test/python/compiler/test_assembler.py
  test/python/compiler/test_disassembler.py
  test/python/providers/test_backendconfiguration.py
Labels: Changelog: API Change, automerge

#6491 Fixed typo in LinearAmplitudeFunction docstring
  qiskit/circuit/library/arithmetic/linear_amplitude_function.py
Labels: Changelog: Bugfix, automerge

#6470 Arithmetic circuit library: multipliers
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/arithmetic/__init__.py
  qiskit/circuit/library/arithmetic/multipliers/__init__.py
  qiskit/circuit/library/arithmetic/multipliers/hrs_cumulative_multiplier.py
  qiskit/circuit/library/arithmetic/multipliers/multiplier.py
  qiskit/circuit/library/arithmetic/multipliers/rg_qft_multiplier.py
  releasenotes/notes/multipliers-8c7477859508ca58.yaml
  test/python/circuit/library/test_multipliers.py
Labels: Changelog: New Feature, automerge

#6459 Add plain Gradient Descent optimizer
  qiskit/algorithms/optimizers/__init__.py
  qiskit/algorithms/optimizers/gradient_descent.py
  releasenotes/notes/gradient-descent-optimizer-96a7a0eeb9502cef.yaml
  test/python/algorithms/optimizers/test_gradient_descent.py
  test/python/algorithms/optimizers/test_optimizers.py
Labels: Changelog: New Feature, automerge, mod: algorithms

#6463 Changing HHL to allow python list inputs and associatedd tests
  qiskit/algorithms/linear_solvers/hhl.py
  test/python/algorithms/test_linear_solvers.py
Labels: automerge, mod: algorithms

#6503 Fix deprecate msg in Measurement Error Mitigation
  qiskit/utils/measurement_error_mitigation.py
Labels: mod: algorithms

#6507 Fix HHL isinstance Failure
  qiskit/algorithms/linear_solvers/hhl.py
Labels: automerge, bug, mod: algorithms, priority: high

#6348 Fix excessive load time for mpl circuit drawer
  qiskit/visualization/matplotlib.py
Labels: Changelog: None, automerge

#6494 Add parametric_pulses as a documented kwarg to BackendConfiguration
  qiskit/providers/models/backendconfiguration.py
Labels: Changelog: None, automerge

#6329 Add a new transpiler pass to remove all barriers
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/utils/__init__.py
  qiskit/transpiler/passes/utils/remove_barriers.py
  releasenotes/notes/add-remove-barriers-pass-dab69660f61e9d75.yaml
  test/python/transpiler/test_remove_barriers.py
Labels: Changelog: New Feature, automerge

#5212 Update colormap for phase in qsphere state visualization
  qiskit/visualization/state_visualization.py
Labels: Changelog: None, PR for good first issue, automerge

#6524 Don't enable multiprocessing by default on Python 3.9
  qiskit/tools/parallel.py
  releasenotes/notes/disable-39-multirpc-8618c89aeaa620f9.yaml
Labels: Changelog: API Change, automerge, performance, priority: high

#6433 Performance improvements for collect_2q_blocks
  qiskit/dagcircuit/dagcircuit.py
  qiskit/transpiler/passes/optimization/collect_2q_blocks.py
  releasenotes/notes/bump-retworkx-59c7ab59ad02c3c0.yaml
  requirements.txt
  test/python/dagcircuit/test_dagcircuit.py
Labels: Changelog: None, automerge, performance

#6337 Deprecate legacy provider interface
  qiskit/providers/__init__.py
  qiskit/providers/basebackend.py
  qiskit/providers/basejob.py
  qiskit/providers/baseprovider.py
  releasenotes/notes/deprecate-legacy-providers-383bf4142153297a.yaml
  test/python/providers/test_fake_backends.py
Labels: Changelog: Deprecation, automerge

#6527 Fixed NFT optimizer by including argument for args as supplied
  qiskit/algorithms/optimizers/nft.py
Labels: Changelog: Bugfix, automerge, mod: algorithms

#5913 Remove invalid-hash-returned
  qiskit/transpiler/basepasses.py
Labels: Changelog: None, automerge

#5842 Add option to set encoding when saving Qasm to file
  qiskit/circuit/library/blueprintcircuit.py
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/encoding-qasm-6c61415cd92108e3.yaml
Labels: Changelog: New Feature, automerge

#6309 Fix adding controls to an open controlled gate
  qiskit/circuit/add_control.py
  releasenotes/notes/fix-control-of-open-controlled-gate-7a036e42ef5c1b72.yaml
  test/python/circuit/test_controlled_gate.py
Labels: Changelog: Bugfix, automerge

#6522 TwoLocal raises proper exception for reps input that is not int and added unit tests
  qiskit/circuit/library/n_local/n_local.py
  releasenotes/notes/bugfix-proper-exception-twolocal-4a348f45f5e2ad75.yaml
  test/python/circuit/library/test_nlocal.py
Labels: Changelog: Bugfix, automerge

#6458 Alternative parametrization of GaussianSquare
  qiskit/pulse/library/parametric_pulses.py
  test/python/pulse/test_pulse_lib.py
Labels: automerge

#6017 plot_city_state docstring fix for ax_imag kwarg.
  qiskit/visualization/state_visualization.py
Labels: Changelog: None, automerge, type: documentation

#6550 fixed issue 6538 by updating the documentation
  qiskit/pulse/builder.py
Labels: automerge

#6457 Revert "BasisTranslator to cache bound target DAG. (#6187)"
  qiskit/transpiler/passes/basis/basis_translator.py
Labels: Changelog: None, automerge

#6210 Fix PiecewiseChebyshev does not work as expected when breakpoints = None
  qiskit/circuit/library/arithmetic/piecewise_chebyshev.py
  releasenotes/notes/fix-issue-6198-0d439de830f80c65.yaml
  test/python/circuit/library/test_piecewise_chebyshev.py
Labels: Changelog: Bugfix, automerge

#6345 Make limit on waveform amplitude optional
  qiskit/pulse/library/parametric_pulses.py
  qiskit/pulse/library/pulse.py
  qiskit/pulse/library/waveform.py
  releasenotes/notes/add-option-to-disable-waveform-amplitude-limit-c58e2ec61f6789e6.yaml
  test/python/pulse/test_pulse_lib.py
Labels: automerge

#6530 fixed issue 6464 by adding note in SPSA docstring and other algorithms that use algorithm_globals
  qiskit/algorithms/optimizers/adam_amsgrad.py
  qiskit/algorithms/optimizers/gsls.py
  qiskit/algorithms/optimizers/spsa.py
  qiskit/algorithms/variational_algorithm.py
Labels: automerge, mod: algorithms, type: documentation

#6249 Remove unused code from MatplotlibDrawer
  qiskit/visualization/matplotlib.py
Labels: Changelog: None, automerge

#6532 Update basis equivalence test to be more specific
  test/python/qasm/TestBasisTranslator_skip_target.qasm
  test/python/transpiler/test_basis_translator.py
Labels: Changelog: None, automerge

#6554 Fix padding of zeros in keys of quasi-distribution and probabilities
  qiskit/result/distributions/probability.py
  qiskit/result/distributions/quasi.py
  test/python/result/test_probability.py
  test/python/result/test_quasi.py
Labels: Changelog: None, automerge

#5691 Add line_discipline kwarg to job_monitor function
  qiskit/tools/monitor/job_monitor.py
  releasenotes/notes/add-line_discipline-to-job_monitor-dc9b66a9d819dbfa.yaml
Labels: Changelog: New Feature, automerge

#6561 Update mailmap
  .mailmap
Labels: Changelog: None, automerge

#6519 qc.num_connected_components() now returns the correct output
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/fix-num-connected-components-ccbee4aa486dbd2c.yaml
  test/python/circuit/test_circuit_properties.py
Labels: Changelog: Bugfix, automerge

#6037 Lint tweaks
  .pylintrc
  qiskit/__init__.py
  qiskit/algorithms/amplitude_amplifiers/grover.py
  qiskit/algorithms/minimum_eigen_solvers/vqe.py
  qiskit/algorithms/optimizers/aqgd.py
  qiskit/circuit/equivalence_library.py
  qiskit/circuit/library/n_local/n_local.py
  qiskit/circuit/library/n_local/qaoa_ansatz.py
  qiskit/circuit/library/standard_gates/equivalence_library.py
  qiskit/circuit/parameterexpression.py
  qiskit/circuit/quantumcircuit.py
  qiskit/opflow/gradients/gradient_base.py
  qiskit/opflow/gradients/hessian_base.py
  qiskit/opflow/gradients/natural_gradient.py
  qiskit/opflow/gradients/qfi_base.py
  qiskit/opflow/operator_globals.py
  qiskit/opflow/primitive_ops/pauli_sum_op.py
  qiskit/opflow/state_fns/cvar_measurement.py
  qiskit/opflow/state_fns/dict_state_fn.py
  qiskit/providers/basicaer/__init__.py
  qiskit/providers/models/pulsedefaults.py
  qiskit/pulse/instruction_schedule_map.py
  qiskit/pulse/library/discrete.py
  qiskit/pulse/parser.py
  qiskit/pulse/schedule.py
  qiskit/pulse/utils.py
  qiskit/qobj/pulse_qobj.py
  qiskit/qobj/qasm_qobj.py
  qiskit/qobj/utils.py
  qiskit/quantum_info/operators/base_operator.py
  qiskit/quantum_info/operators/channel/transformations.py
  qiskit/quantum_info/operators/dihedral/dihedral.py
  qiskit/quantum_info/operators/linear_op.py
  qiskit/quantum_info/operators/mixins/tolerances.py
  qiskit/quantum_info/operators/predicates.py
  qiskit/quantum_info/operators/symplectic/stabilizer_table.py
  qiskit/scheduler/utils.py
  qiskit/test/base.py
  qiskit/transpiler/instruction_durations.py
  qiskit/transpiler/passes/layout/csp_layout.py
  qiskit/utils/algorithm_globals.py
  qiskit/visualization/bloch.py
  qiskit/visualization/pulse/interpolation.py
  qiskit/visualization/pulse/matplotlib.py
  qiskit/visualization/pulse_v2/core.py
  qiskit/visualization/pulse_v2/types.py
  qiskit/visualization/pulse_visualization.py
  qiskit/visualization/state_visualization.py
  qiskit/visualization/timeline/types.py
  test/python/circuit/test_uc.py
  test/python/circuit/test_ucx_y_z.py
  test/python/circuit/test_unitary.py
  test/python/opflow/test_z2_symmetries.py
  test/python/test_examples.py
  test/python/transpiler/test_unroller.py
Labels: on hold

#6498 Improve layout and routing methods
  qiskit/transpiler/passes/layout/sabre_layout.py
  qiskit/transpiler/passes/routing/basic_swap.py
  qiskit/transpiler/passes/routing/lookahead_swap.py
  qiskit/transpiler/passes/routing/sabre_swap.py
  qiskit/transpiler/passes/routing/stochastic_swap.py
Labels: automerge, performance

#6556 TwoLocal entangling map works for numpy integers
  qiskit/circuit/library/n_local/n_local.py
  releasenotes/notes/bugfix-supports-numpy-integers-03c60659fe4cc0c5.yaml
  test/python/circuit/library/test_nlocal.py
Labels: Changelog: Bugfix, automerge

#6573 Revert "Add ESP readout support to Qiskit (#6543)"
  qiskit/compiler/assembler.py
  qiskit/execute_function.py
  qiskit/providers/models/backendconfiguration.py
  qiskit/schemas/backend_configuration_schema.json
  releasenotes/notes/esp-readout-3aa5fff772ddbab1.yaml
  test/python/compiler/test_assembler.py
Labels: Changelog: None, automerge

#4646 Close the figures when testing them, to avoid memory leak
  test/ipynb/mpl/test_circuit_matplotlib_drawer.py
Labels: Changelog: None, automerge

#6570 Add Support to TensoredMeasFitter in QuantumInstance
  qiskit/utils/measurement_error_mitigation.py
  qiskit/utils/quantum_instance.py
  releasenotes/notes/TensoredMeasFitter-d327f0e2d736efdd.yaml
  test/python/algorithms/test_measure_error_mitigation.py
Labels: automerge, mod: algorithms, type: enhancement

#6418 Stateless ``VQE``
  qiskit/algorithms/minimum_eigen_solvers/qaoa.py
  qiskit/algorithms/minimum_eigen_solvers/vqe.py
  qiskit/algorithms/variational_algorithm.py
  test/python/algorithms/test_vqe.py
  test/python/opflow/test_expectation_factory.py
Labels: automerge, mod: algorithms

#6500 Fix #6497 (opflow.expectations ignore coefficients)
  qiskit/opflow/converters/circuit_sampler.py
  qiskit/opflow/converters/pauli_basis_change.py
  qiskit/opflow/expectations/aer_pauli_expectation.py
  qiskit/opflow/state_fns/circuit_state_fn.py
  qiskit/opflow/state_fns/dict_state_fn.py
  qiskit/opflow/state_fns/state_fn.py
  releasenotes/notes/fix-opflow-coeff-bug-5557c50cc2f47401.yaml
  test/python/opflow/test_aer_pauli_expectation.py
  test/python/opflow/test_pauli_expectation.py
Labels: Changelog: Bugfix, automerge, mod: opflow

#6599 Fixes deprecator decorator order on VQE optimal_params property
  qiskit/algorithms/minimum_eigen_solvers/vqe.py
Labels: automerge, bug, mod: algorithms, priority: high

#6365 Fix oracle_evaluation for PhaseOracle
  qiskit/circuit/library/phase_oracle.py
  releasenotes/notes/fix_phaseoracle_evaluate-52be05221d2761aa.yaml
  test/python/algorithms/test_grover.py
Labels: Changelog: Bugfix, automerge

#6601 Fix sabre regressions
  qiskit/transpiler/passes/layout/sabre_layout.py
  qiskit/transpiler/passes/routing/sabre_swap.py
Labels: Changelog: None, automerge, performance

#6508 QuantumCircuit.ccx(..., ctrl_state=...) parameter added for consistency with other controlled gates
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_controlled_gate.py
Labels: Changelog: API Change, automerge

#6606 Fix find_optional_imports.py
  tools/find_optional_imports.py
Labels: Changelog: None, automerge, type: qa

#6607 fix verify_headers.py
  qiskit/transpiler/passes/routing/cython/stochastic_swap/utils.pxd
  tools/verify_headers.py
Labels: Changelog: None, automerge, type: qa

#6614 Fix lint in subunit to junit tools script
  tools/subunit_to_junit.py
Labels: Changelog: None, automerge, type: qa

#6611 Blacken stragglers
  Makefile
  azure-pipelines.yml
  docs/conf.py
  examples/python/circuit_draw.py
  examples/python/ghz.py
  examples/python/ibmq/ghz.py
  examples/python/ibmq/hello_quantum.py
  examples/python/ibmq/qft.py
  examples/python/ibmq/using_qiskit_terra_level_0.py
  examples/python/ibmq/using_qiskit_terra_level_1.py
  examples/python/ibmq/using_qiskit_terra_level_2.py
  examples/python/initialize.py
  examples/python/load_qasm.py
  examples/python/qft.py
  examples/python/rippleadd.py
  examples/python/stochastic_swap.py
  examples/python/teleport.py
  examples/python/using_qiskit_terra_level_0.py
  setup.py
  tox.ini
Labels: Changelog: None, automerge, type: qa

#6613 Remove docplex in constraints.txt
  constraints.txt
Labels: Changelog: None, automerge

#6449 Reverse argument order on qpy_serialization.dump and fix warning
  qiskit/circuit/qpy_serialization.py
  test/python/circuit/test_circuit_load_from_qpy.py
Labels: Changelog: None, automerge

#6609 Pylint tools
  Makefile
  azure-pipelines.yml
  tools/report_ci_failure.py
  tools/update_fake_backends.py
  tox.ini
Labels: Changelog: None, automerge, type: qa

#6585 NLocal initial_state works for QuantumCircuit object
  qiskit/circuit/library/n_local/n_local.py
  test/python/circuit/library/test_nlocal.py
Labels: automerge

#6310 Fix quantum part of Shor's algorithm
  qiskit/algorithms/factorizers/shor.py
  test/python/algorithms/test_shor.py
Labels: Changelog: Bugfix, automerge, mod: algorithms

#6636 Pin jax version in constraints
  constraints.txt
Labels: Changelog: None, automerge, priority: high, type: qa

#6317 Upgrade to pylint 2.8.3
  qiskit/pulse/library/parametric_pulses.py
  qiskit/qasm/qasmparser.py
  qiskit/test/mock/fake_job.py
  qiskit/version.py
  qiskit/visualization/pass_manager_visualization.py
  qiskit/visualization/state_visualization.py
  requirements-dev.txt
  test/python/test_examples.py
  test/python/visualization/test_pass_manager_drawer.py
  tools/subunit_to_junit.py
  tools/verify_headers.py
Labels: Changelog: None, automerge, type: qa

#5911 Improve error handling in creating Pauli with an invalid label
  qiskit/quantum_info/operators/symplectic/pauli.py
  releasenotes/notes/improve-error-in-pauli-944a71008789fbaa.yaml
  test/python/quantum_info/operators/symplectic/test_pauli.py
Labels: automerge

#6442 Improve Clifford Synthesis to make it more efficient
  qiskit/quantum_info/synthesis/clifford_decompose.py
  test/python/quantum_info/operators/symplectic/test_clifford.py
Labels: automerge, mod: quantum info

#6600 Change DeprecationWarning filter to show only once per location.
  qiskit/utils/deprecation.py
Labels: automerge, type: qa

#6635 Update tutorials CI configuration
  azure-pipelines.yml
Labels: Changelog: None, automerge, type: qa

#6483 latex-source (and latex) circuit drawer support for standalone (and cleaner output)
  qiskit/visualization/latex.py
  test/python/visualization/references/test_latex_4597.tex
  test/python/visualization/references/test_latex_big_gates.tex
  test/python/visualization/references/test_latex_cnot.tex
  test/python/visualization/references/test_latex_conditional.tex
  test/python/visualization/references/test_latex_creg_initial_false.tex
  test/python/visualization/references/test_latex_creg_initial_true.tex
  test/python/visualization/references/test_latex_cswap_rzz.tex
  test/python/visualization/references/test_latex_deep.tex
  test/python/visualization/references/test_latex_empty.tex
  test/python/visualization/references/test_latex_ghz_to_gate.tex
  test/python/visualization/references/test_latex_global_phase.tex
  test/python/visualization/references/test_latex_huge.tex
  test/python/visualization/references/test_latex_init_reset.tex
  test/python/visualization/references/test_latex_inst_with_cbits.tex
  test/python/visualization/references/test_latex_iqx.tex
  test/python/visualization/references/test_latex_long_name.tex
  test/python/visualization/references/test_latex_meas_condition.tex
  test/python/visualization/references/test_latex_no_barriers_false.tex
  test/python/visualization/references/test_latex_no_ops.tex
  test/python/visualization/references/test_latex_normal.tex
  test/python/visualization/references/test_latex_partial_layout.tex
  test/python/visualization/references/test_latex_pauli_clifford.tex
  test/python/visualization/references/test_latex_pi_param_expr.tex
  test/python/visualization/references/test_latex_plot_barriers_false.tex
  test/python/visualization/references/test_latex_plot_barriers_true.tex
  test/python/visualization/references/test_latex_plot_partial_barriers.tex
  test/python/visualization/references/test_latex_r_gates.tex
  test/python/visualization/references/test_latex_reverse_bits.tex
  test/python/visualization/references/test_latex_scale_default.tex
  test/python/visualization/references/test_latex_scale_double.tex
  test/python/visualization/references/test_latex_scale_half.tex
  test/python/visualization/references/test_latex_teleport.tex
  test/python/visualization/references/test_latex_tiny.tex
  test/python/visualization/references/test_latex_u_gates.tex
  test/python/visualization/test_circuit_latex.py
Labels: Changelog: New Feature, PR for good first issue, automerge

#6638 Removing pending TODO blocked by #3304
  test/python/circuit/test_controlled_gate.py
Labels: Changelog: None, automerge

#6589 %qiskit_version_table with domain specific apps
  qiskit/tools/jupyter/version_table.py
Labels: Changelog: None, automerge

#6639 Fix in Register.__getitem__ docstring
  qiskit/circuit/register.py
Labels: Changelog: None, automerge, type: documentation

#6642 Deprecate the QiskitIndexError exception class
  qiskit/exceptions.py
  releasenotes/notes/QiskitIndexError-d75510dc0d626c93.yaml
Labels: Changelog: Deprecation, automerge

#6592 Add option to sort by values to plot_histogram
  qiskit/visualization/counts_visualization.py
  releasenotes/notes/value-sort-histogram-1b7033bdfe612f94.yaml
Labels: Changelog: New Feature, automerge

#6078 Move gate, control, and param label selections from 3 circuit drawers to utils
  qiskit/circuit/quantumcircuit.py
  qiskit/visualization/circuit_visualization.py
  qiskit/visualization/latex.py
  qiskit/visualization/matplotlib.py
  qiskit/visualization/qcstyle.py
  qiskit/visualization/styles/bw.json
  qiskit/visualization/styles/default.json
  qiskit/visualization/styles/iqx.json
  qiskit/visualization/text.py
  qiskit/visualization/utils.py
  releasenotes/notes/latex_style_user_math_text-266f9b411317ae6b.yaml
  test/ipynb/mpl/references/big_gates.png
  test/ipynb/mpl/references/scale_default.png
  test/ipynb/mpl/references/scale_double.png
  test/ipynb/mpl/references/scale_half.png
  test/ipynb/mpl/references/user_style.png
  test/ipynb/mpl/references/wide_params.png
  test/ipynb/mpl/test_circuit_matplotlib_drawer.py
  test/python/visualization/references/circuit_text_ref_cp437.txt
  test/python/visualization/references/circuit_text_ref_utf8.txt
  test/python/visualization/references/test_latex_big_gates.tex
  test/python/visualization/references/test_latex_boolean_negation.tex
  test/python/visualization/references/test_latex_cswap_rzz.tex
  test/python/visualization/references/test_latex_init_reset.tex
  test/python/visualization/references/test_latex_iqx.tex
  test/python/visualization/references/test_latex_partial_layout.tex
  test/python/visualization/references/test_latex_pauli_clifford.tex
  test/python/visualization/references/test_latex_pi_param_expr.tex
  test/python/visualization/references/test_latex_r_gates.tex
  test/python/visualization/references/test_latex_teleport.tex
  test/python/visualization/references/test_latex_u_gates.tex
  test/python/visualization/test_circuit_text_drawer.py
  test_iqx.tex
Labels: Changelog: New Feature, automerge

#6594 Delay support when loading from QASM2
  qiskit/circuit/delay.py
  qiskit/converters/ast_to_dag.py
  releasenotes/notes/delay_from_qasm-a6ad4f1fe3f49041.yaml
  test/python/circuit/test_circuit_load_from_qasm.py
Labels: Changelog: Bugfix, automerge, qasm

#6407 Add support for faulty directed gate
  qiskit/compiler/transpiler.py
  qiskit/transpiler/coupling.py
  test/python/providers/faulty_backends.py
  test/python/providers/test_faulty_backend.py
  test/python/transpiler/test_faulty_backend.py
Labels: Changelog: New Feature, automerge

#6562 Fix PauliOp.to_circuit() when phase exists
  qiskit/opflow/primitive_ops/pauli_op.py
  releasenotes/notes/fix-pauli-op-to-circuit-2ace141cac0dd97a.yaml
  test/python/opflow/test_op_construction.py
Labels: Changelog: Bugfix, automerge, mod: opflow

#6534 Performance improvement for Collect2qBlocks
  qiskit/transpiler/passes/optimization/collect_2q_blocks.py
  test/python/transpiler/test_collect_2q_blocks.py
Labels: Changelog: None, automerge, performance

#6655 Fix calibration handling of transpiler passes on gates with >2 qubits
  qiskit/transpiler/passes/basis/unroll_3q_or_more.py
  qiskit/transpiler/passes/utils/check_map.py
  test/python/compiler/test_transpiler.py
Labels: Changelog: Bugfix, priority: high

#6654 Remove unused and broken Make.bat script
  Make.bat
Labels: Changelog: None, automerge

#5993 Add PauliList class
  qiskit/quantum_info/__init__.py
  qiskit/quantum_info/operators/__init__.py
  qiskit/quantum_info/operators/random.py
  qiskit/quantum_info/operators/symplectic/__init__.py
  qiskit/quantum_info/operators/symplectic/base_pauli.py
  qiskit/quantum_info/operators/symplectic/pauli.py
  qiskit/quantum_info/operators/symplectic/pauli_list.py
  qiskit/quantum_info/operators/symplectic/random.py
  qiskit/quantum_info/random.py
  releasenotes/notes/add-pauli-list-5644d695f91de808.yaml
  test/python/quantum_info/operators/symplectic/test_pauli_list.py
  test/python/quantum_info/operators/test_random.py
Labels: Changelog: New Feature, automerge

#6629 Improve the performance of AerExpectationValue
  qiskit/opflow/converters/circuit_sampler.py
  test/python/opflow/test_aer_pauli_expectation.py
Labels: Changelog: None, automerge, mod: opflow, performance

#6662 Add string parameter handling to QPY
  qiskit/circuit/library/__init__.py
  qiskit/circuit/qpy_serialization.py
  test/python/circuit/test_circuit_load_from_qpy.py
Labels: Changelog: None, automerge, priority: high

#6650 Add operator settings
  qiskit/opflow/expectations/aer_pauli_expectation.py
  qiskit/opflow/expectations/matrix_expectation.py
  qiskit/opflow/gradients/gradient.py
  qiskit/opflow/list_ops/composed_op.py
  qiskit/opflow/list_ops/list_op.py
  qiskit/opflow/list_ops/summed_op.py
  qiskit/opflow/list_ops/tensored_op.py
  qiskit/opflow/operator_base.py
  qiskit/opflow/primitive_ops/pauli_sum_op.py
  qiskit/opflow/primitive_ops/primitive_op.py
  qiskit/opflow/primitive_ops/tapered_pauli_sum_op.py
  qiskit/opflow/state_fns/circuit_state_fn.py
  qiskit/opflow/state_fns/cvar_measurement.py
  qiskit/opflow/state_fns/dict_state_fn.py
  qiskit/opflow/state_fns/state_fn.py
  qiskit/quantum_info/operators/base_operator.py
  qiskit/quantum_info/operators/operator.py
  qiskit/quantum_info/operators/symplectic/pauli.py
  qiskit/quantum_info/operators/symplectic/pauli_table.py
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
  qiskit/quantum_info/states/statevector.py
Labels: automerge, mod: opflow, mod: quantum info
