Repository Qiskit/qiskit, pull requests merged in 2021-03, with the labels that each got.

#5910 Fix to carry over calibrations with __iadd__ and __add__
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/calibrations-add-iadd-265b92f42ffce92a.yaml
  test/python/circuit/test_calibrations.py
Labels: Changelog: Bugfix, automerge

#5946 Added LHS circuit calibrations with + operator
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/issue-5939-calibrations-34c4ddf684595105.yaml
  test/python/circuit/test_calibrations.py
Labels: automerge

#5813 fix for permutation circuit
  qiskit/circuit/library/generalized_gates/permutation.py
  releasenotes/notes/fix_permutation_circuit-3e336899efa6da98.yaml
  test/python/circuit/library/test_permutation.py
Labels: Changelog: Bugfix, automerge

#4849 QFT little endian
  qiskit/circuit/library/arithmetic/quadratic_form.py
  qiskit/circuit/library/basis_change/qft.py
  qiskit/circuit/library/phase_estimation.py
  releasenotes/notes/qft-little-endian-d232c93e044f0063.yaml
  test/python/algorithms/test_amplitude_estimators.py
  test/python/circuit/library/test_phase_estimation.py
  test/python/circuit/library/test_qft.py
  test/python/circuit/test_circuit_operations.py
Labels: automerge

#5672 make commutative_cancellation basis aware
  qiskit/transpiler/passes/optimization/commutative_cancellation.py
  qiskit/transpiler/preset_passmanagers/level2.py
  releasenotes/notes/basis_aware_commutative_cancellation-9f3b4924b0fa478d.yaml
  test/python/transpiler/test_commutative_cancellation.py
  test/python/transpiler/test_passmanager.py
Labels: Changelog: Bugfix, automerge, stable backport potential

#5952 Remove set() cast in noise adaptive layout
  qiskit/transpiler/passes/layout/noise_adaptive_layout.py
  requirements.txt
Labels: automerge, performance

#5383 Improve parallel default selection on macOS
  qiskit/tools/parallel.py
  qiskit/user_config.py
  releasenotes/notes/paralle-config-options-97c1ad44ab76e052.yaml
  test/python/test_user_config.py
Labels: automerge, performance

#5970 Add reverse_qargs to Operator
  qiskit/quantum_info/operators/operator.py
  releasenotes/notes/reverse_qargs-f2f3c9a3e1c3aaa0.yaml
  test/python/quantum_info/operators/test_operator.py
Labels: Changelog: New Feature, automerge, mod: quantum info

#5779 Improved Clifford synthesis method
  qiskit/quantum_info/synthesis/clifford_decompose.py
  releasenotes/notes/improve-clifford-synthesis-6bddeefa78a2cac1.yaml
  test/python/quantum_info/operators/symplectic/test_clifford.py
Labels: Changelog: New Feature, automerge, mod: quantum info

#5915 Tune performance of OneQubitEulerDecomposer
  qiskit/quantum_info/synthesis/one_qubit_decompose.py
Labels: automerge, performance

#5928 Add option to 1q euler decomposer for disabling unitary check
  qiskit/quantum_info/synthesis/one_qubit_decompose.py
  qiskit/quantum_info/synthesis/two_qubit_decompose.py
  qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py
  qiskit/transpiler/passes/synthesis/unitary_synthesis.py
Labels: automerge, performance

#5979 Remove DagNode.__hash__()
  qiskit/dagcircuit/dagnode.py
Labels: automerge, bug, performance

#5934 Allow caching more than the last operator in the CircuitSampler
  qiskit/opflow/converters/circuit_sampler.py
  qiskit/opflow/list_ops/list_op.py
  qiskit/opflow/operator_base.py
  qiskit/opflow/primitive_ops/primitive_op.py
  qiskit/opflow/state_fns/state_fn.py
  test/python/opflow/test_state_op_meas_evals.py
Labels: automerge, mod: opflow

#5442 Transfer the CNOTDihedral Operator class
  qiskit/quantum_info/__init__.py
  qiskit/quantum_info/operators/__init__.py
  qiskit/quantum_info/operators/dihedral/__init__.py
  qiskit/quantum_info/operators/dihedral/dihedral.py
  qiskit/quantum_info/operators/dihedral/dihedral_circuits.py
  qiskit/quantum_info/operators/dihedral/polynomial.py
  qiskit/quantum_info/operators/dihedral/random.py
  qiskit/quantum_info/operators/random.py
  qiskit/quantum_info/random.py
  qiskit/quantum_info/synthesis/cnotdihedral_decompose.py
  releasenotes/notes/cnot-dihedral-op-518a51b2827cd291.yaml
  test/python/quantum_info/operators/test_dihedral.py
Labels: Changelog: New Feature, automerge, mod: quantum info

#5935 Add name argument in builder.play
  qiskit/pulse/builder.py
  test/python/pulse/test_builder.py
Labels: automerge

#5257 Pulse builder macro decorator
  qiskit/pulse/__init__.py
  qiskit/pulse/builder.py
  releasenotes/notes/pulse-builder-macro-ba0d71dd353e0135.yaml
  test/python/pulse/test_builder.py
Labels: automerge, mod: pulse

#5983 Reorganize CI jobs and stages
  azure-pipelines.yml
Labels: automerge

#5957 Get rid of a few more pylint suppressions
  .pylintrc
  qiskit/circuit/library/n_local/qaoa_ansatz.py
  qiskit/opflow/primitive_ops/tapered_pauli_sum_op.py
  qiskit/test/mock/backends/almaden/__init__.py
  qiskit/test/mock/backends/armonk/__init__.py
  qiskit/test/mock/backends/athens/__init__.py
  qiskit/test/mock/backends/boeblingen/__init__.py
  qiskit/test/mock/backends/bogota/__init__.py
  qiskit/test/mock/backends/burlington/__init__.py
  qiskit/test/mock/backends/cambridge/__init__.py
  qiskit/test/mock/backends/essex/__init__.py
  qiskit/test/mock/backends/johannesburg/__init__.py
  qiskit/test/mock/backends/london/__init__.py
  qiskit/test/mock/backends/manhattan/__init__.py
  qiskit/test/mock/backends/melbourne/__init__.py
  qiskit/test/mock/backends/montreal/__init__.py
  qiskit/test/mock/backends/ourense/__init__.py
  qiskit/test/mock/backends/paris/__init__.py
  qiskit/test/mock/backends/poughkeepsie/__init__.py
  qiskit/test/mock/backends/rochester/__init__.py
  qiskit/test/mock/backends/rome/__init__.py
  qiskit/test/mock/backends/rueschlikon/__init__.py
  qiskit/test/mock/backends/santiago/__init__.py
  qiskit/test/mock/backends/singapore/__init__.py
  qiskit/test/mock/backends/tenerife/__init__.py
  qiskit/test/mock/backends/tokyo/__init__.py
  qiskit/test/mock/backends/toronto/__init__.py
  qiskit/test/mock/backends/valencia/__init__.py
  qiskit/test/mock/backends/vigo/__init__.py
  qiskit/test/mock/backends/yorktown/__init__.py
  qiskit/transpiler/passes/optimization/hoare_opt.py
  test/python/circuit/test_circuit_properties.py
Labels: automerge

#5964 Improve type hinting in OpFlow
  qiskit/opflow/converters/abelian_grouper.py
  qiskit/opflow/converters/circuit_sampler.py
  qiskit/opflow/converters/converter_base.py
  qiskit/opflow/converters/dict_to_circuit_sum.py
  qiskit/opflow/converters/pauli_basis_change.py
  qiskit/opflow/converters/two_qubit_reduction.py
  qiskit/opflow/evolutions/evolution_base.py
  qiskit/opflow/evolutions/evolution_factory.py
  qiskit/opflow/evolutions/evolved_op.py
  qiskit/opflow/evolutions/matrix_evolution.py
  qiskit/opflow/evolutions/pauli_trotter_evolution.py
  qiskit/opflow/evolutions/trotterizations/qdrift.py
  qiskit/opflow/evolutions/trotterizations/suzuki.py
  qiskit/opflow/evolutions/trotterizations/trotter.py
  qiskit/opflow/evolutions/trotterizations/trotterization_base.py
  qiskit/opflow/evolutions/trotterizations/trotterization_factory.py
  qiskit/opflow/expectations/aer_pauli_expectation.py
  qiskit/opflow/expectations/cvar_expectation.py
  qiskit/opflow/expectations/expectation_base.py
  qiskit/opflow/expectations/expectation_factory.py
  qiskit/opflow/expectations/matrix_expectation.py
  qiskit/opflow/expectations/pauli_expectation.py
  qiskit/opflow/list_ops/composed_op.py
  qiskit/opflow/list_ops/list_op.py
  qiskit/opflow/list_ops/summed_op.py
  qiskit/opflow/list_ops/tensored_op.py
  qiskit/opflow/operator_base.py
  qiskit/opflow/operator_globals.py
  qiskit/opflow/primitive_ops/circuit_op.py
  qiskit/opflow/primitive_ops/matrix_op.py
  qiskit/opflow/primitive_ops/pauli_op.py
  qiskit/opflow/primitive_ops/pauli_sum_op.py
  qiskit/opflow/primitive_ops/primitive_op.py
  qiskit/opflow/primitive_ops/tapered_pauli_sum_op.py
  qiskit/opflow/state_fns/circuit_state_fn.py
  qiskit/opflow/state_fns/cvar_measurement.py
  qiskit/opflow/state_fns/dict_state_fn.py
  qiskit/opflow/state_fns/operator_state_fn.py
  qiskit/opflow/state_fns/state_fn.py
  qiskit/opflow/state_fns/vector_state_fn.py
  qiskit/opflow/utils.py
Labels: mod: opflow

#5984 Fix density matrix expval cython function
  .gitignore
  qiskit/quantum_info/states/cython/exp_value.pyx
  qiskit/quantum_info/states/densitymatrix.py
  qiskit/quantum_info/states/statevector.py
  test/python/quantum_info/states/test_densitymatrix.py
  test/python/quantum_info/states/test_statevector.py
Labels: automerge

#5515 Transpiler updates for optional registers.
  qiskit/circuit/quantumcircuit.py
  qiskit/compiler/transpiler.py
  qiskit/converters/circuit_to_dag.py
  qiskit/converters/circuit_to_dagdependency.py
  qiskit/converters/dag_to_circuit.py
  qiskit/converters/dag_to_dagdependency.py
  qiskit/converters/dagdependency_to_circuit.py
  qiskit/converters/dagdependency_to_dag.py
  qiskit/dagcircuit/dagdependency.py
  qiskit/transpiler/layout.py
  qiskit/transpiler/passes/layout/apply_layout.py
  qiskit/transpiler/passes/layout/enlarge_with_ancilla.py
  qiskit/transpiler/passes/layout/full_ancilla_allocation.py
  qiskit/transpiler/passes/layout/sabre_layout.py
  qiskit/transpiler/passes/layout/trivial_layout.py
  qiskit/transpiler/passes/optimization/crosstalk_adaptive_schedule.py
  qiskit/transpiler/passes/optimization/hoare_opt.py
  qiskit/transpiler/passes/routing/cython/stochastic_swap/utils.pxd
  qiskit/transpiler/passes/routing/cython/stochastic_swap/utils.pyx
  qiskit/transpiler/passes/routing/sabre_swap.py
  qiskit/transpiler/passes/routing/stochastic_swap.py
  qiskit/transpiler/passes/utils/check_cx_direction.py
  qiskit/transpiler/passes/utils/check_map.py
  qiskit/transpiler/passes/utils/cx_direction.py
  qiskit/transpiler/passes/utils/remove_final_measurements.py
  test/python/compiler/test_transpiler.py
  test/python/dagcircuit/test_dagdependency.py
  test/python/transpiler/test_enlarge_with_ancilla_pass.py
  test/python/transpiler/test_full_ancilla_allocation.py
  test/python/transpiler/test_passmanager_run.py
  test/python/transpiler/test_preset_passmanagers.py
Labels: automerge, optional-registers

#6000 Remove delays from Acquire Channels
  qiskit/assembler/assemble_schedules.py
  qiskit/pulse/instructions/play.py
  test/python/compiler/test_assembler.py
  test/python/pulse/test_instructions.py
Labels: Changelog: Bugfix, automerge

#5989 Remove useless all 1s masks
  qiskit/quantum_info/states/cython/exp_value.pyx
Labels: automerge

#6015 Fix error in plot_state_city if only real axis is specified
  qiskit/visualization/state_visualization.py
Labels: Changelog: Bugfix, automerge

#5834 Deprecate __matmul__ and __mul__ in qinfo
  qiskit/quantum_info/operators/measures.py
  qiskit/quantum_info/operators/mixins/group.py
  qiskit/quantum_info/operators/symplectic/pauli.py
  qiskit/quantum_info/states/quantum_state.py
  releasenotes/notes/deprecate-matmul-f6e2faa7f82439fb.yaml
  test/python/quantum_info/operators/channel/test_chi.py
  test/python/quantum_info/operators/channel/test_choi.py
  test/python/quantum_info/operators/channel/test_kraus.py
  test/python/quantum_info/operators/channel/test_ptm.py
  test/python/quantum_info/operators/channel/test_stinespring.py
  test/python/quantum_info/operators/channel/test_superop.py
  test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
  test/python/quantum_info/operators/test_measures.py
  test/python/quantum_info/operators/test_operator.py
  test/python/quantum_info/operators/test_scalar_op.py
  test/python/transpiler/test_hoare_opt.py
Labels: Changelog: API Change, Changelog: Deprecation, automerge, mod: quantum info

#6013 new 16Q device map for ibmq_guadalupe
  qiskit/visualization/gate_map.py
Labels: automerge

#5994 Implemented Random Shuffling in CSPLayout
  qiskit/transpiler/passes/layout/csp_layout.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  releasenotes/notes/csplayout-refactor+randomize-ad5ee25943ba1f56.yaml
  test/python/transpiler/test_csp_layout.py
  test/python/transpiler/test_preset_passmanagers.py
Labels: automerge

#5865 Fix styling that conflicted with docs
  qiskit/tools/jupyter/library.py
Labels: automerge

#6021 Add fake backends for new IBM Quantum devices
  qiskit/test/mock/backends/__init__.py
  qiskit/test/mock/backends/belem/__init__.py
  qiskit/test/mock/backends/belem/conf_belem.json
  qiskit/test/mock/backends/belem/defs_belem.json
  qiskit/test/mock/backends/belem/fake_belem.py
  qiskit/test/mock/backends/belem/props_belem.json
  qiskit/test/mock/backends/casablanca/__init__.py
  qiskit/test/mock/backends/casablanca/conf_casablanca.json
  qiskit/test/mock/backends/casablanca/defs_casablanca.json
  qiskit/test/mock/backends/casablanca/fake_casablanca.py
  qiskit/test/mock/backends/casablanca/props_casablanca.json
  qiskit/test/mock/backends/lima/__init__.py
  qiskit/test/mock/backends/lima/conf_lima.json
  qiskit/test/mock/backends/lima/defs_lima.json
  qiskit/test/mock/backends/lima/fake_lima.py
  qiskit/test/mock/backends/lima/props_lima.json
  qiskit/test/mock/backends/mumbai/__init__.py
  qiskit/test/mock/backends/mumbai/conf_mumbai.json
  qiskit/test/mock/backends/mumbai/defs_mumbai.json
  qiskit/test/mock/backends/mumbai/fake_mumbai.py
  qiskit/test/mock/backends/mumbai/props_mumbai.json
  qiskit/test/mock/backends/quito/__init__.py
  qiskit/test/mock/backends/quito/conf_quito.json
  qiskit/test/mock/backends/quito/defs_quito.json
  qiskit/test/mock/backends/quito/fake_quito.py
  qiskit/test/mock/backends/quito/props_quito.json
  qiskit/test/mock/backends/sydney/__init__.py
  qiskit/test/mock/backends/sydney/conf_sydney.json
  qiskit/test/mock/backends/sydney/defs_sydney.json
  qiskit/test/mock/backends/sydney/fake_sydney.py
  qiskit/test/mock/backends/sydney/props_sydney.json
  qiskit/test/mock/fake_provider.py
  test/python/visualization/references/7_plot_circuit_layout.png
  test/python/visualization/references/7bit_quantum_computer.png
Labels: automerge

#6030 Improve error if too few qubits are used in ZZFeatureMap
  qiskit/circuit/library/data_preparation/zz_feature_map.py
  test/python/circuit/library/test_pauli_feature_map.py
Labels: automerge

#6035 Set utf8 character encoding for windows generate results steps
  azure-pipelines.yml
Labels: automerge

#5980 Display multi-qubit X gate correctly in mpl drawer
  qiskit/visualization/matplotlib.py
  test/ipynb/mpl/references/cnot.png
  test/ipynb/mpl/test_circuit_matplotlib_drawer.py
Labels: automerge

#6041 scikit-quant 0.8 is not installable
  requirements-dev.txt
Labels: automerge

#6014 Added reverse_bits parameter to plot_bloch_multivector() (#5959)
  qiskit/visualization/state_visualization.py
Labels: Changelog: API Change, automerge

#6051 Fix AncillaQubits added via .add_bits to be included in .qubits.
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_registerless_circuit.py
Labels: automerge

#6052 Switch slow algorithm tests to aer and tag slow
  test/python/algorithms/test_optimizer_aqgd.py
  test/python/algorithms/test_shor.py
Labels: automerge

#4208 Deprecate circuit.combine and circuit.extend
  qiskit/circuit/library/n_local/n_local.py
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/deprecate-circuit-combine-extend-ffc6a073ed114890.yaml
  test/python/basicaer/test_multi_registers_convention.py
  test/python/circuit/library/test_nlocal.py
  test/python/circuit/test_circuit_multi_registers.py
  test/python/circuit/test_circuit_operations.py
  test/python/circuit/test_parameters.py
Labels: Changelog: Deprecation, automerge

#6059 Fix QuantumCircuit.copy not deepcopying metadata.
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_circuit_properties.py
Labels: automerge

#6023 Verify ListOp on construction, and fix reduce
  qiskit/opflow/list_ops/list_op.py
  qiskit/opflow/list_ops/summed_op.py
  test/python/opflow/test_op_construction.py
Labels: mod: opflow

#5991 Remove deprecated interactive visualizations
  qiskit/visualization/__init__.py
  qiskit/visualization/interactive/__init__.py
  qiskit/visualization/interactive/iplot_blochsphere.py
  qiskit/visualization/interactive/iplot_cities.py
  qiskit/visualization/interactive/iplot_hinton.py
  qiskit/visualization/interactive/iplot_histogram.py
  qiskit/visualization/interactive/iplot_paulivec.py
  qiskit/visualization/interactive/iplot_qsphere.py
  releasenotes/notes/interactive_visualization-f3186e43f58ac7c6.yaml
Labels: Changelog: Removal

#6054 Improve error message when adding gate with incorrect num_qubits/num_clbits
  qiskit/circuit/gate.py
  qiskit/circuit/instruction.py
Labels: automerge, type: documentation

#3547 Enable parallel_map on windows
  qiskit/circuit/quantumcircuit.py
  qiskit/utils/multiprocessing.py
  releasenotes/notes/enable-windows-parallel-map-b33122a2122a95d7.yaml
Labels: Changelog: New Feature, automerge, performance

#5406 Add documentation guide on writing a provider
  qiskit/providers/__init__.py
Labels: automerge, type: documentation

#5971 Update interpretation of meas_map in Qiskit
  qiskit/assembler/assemble_schedules.py
  qiskit/pulse/macros.py
  releasenotes/notes/update-meas-map-interpretation-53795a9bc7d42857.yaml
  test/python/compiler/test_assembler.py
  test/python/pulse/test_macros.py
  test/python/scheduler/test_basic_scheduler.py
Labels: Changelog: Bugfix, automerge

#6026 Handle reduce() and eval() for empty TensoredOp and ComposedOp
  qiskit/opflow/list_ops/composed_op.py
  qiskit/opflow/list_ops/list_op.py
  qiskit/opflow/list_ops/tensored_op.py
  test/python/opflow/test_op_construction.py
Labels: automerge, mod: opflow

#6071 Fix QuantumInstance ignoring shots in the backend
  qiskit/utils/quantum_instance.py
  test/python/opflow/test_state_op_meas_evals.py
Labels: automerge, mod: opflow

#5961 Anonymous assigning of parameters for gradients and hessians
  qiskit/opflow/gradients/gradient.py
  qiskit/opflow/gradients/hessian.py
  qiskit/opflow/gradients/natural_gradient.py
  qiskit/opflow/gradients/qfi.py
  test/python/opflow/test_gradients.py
Labels: automerge, mod: opflow

#6027 Speedup binding circuit params
  qiskit/circuit/library/blueprintcircuit.py
  qiskit/circuit/library/n_local/n_local.py
  qiskit/circuit/quantumcircuit.py
Labels: automerge, performance

#5987 Update revision key of processor_type to a string in the backend configuration
  qiskit/providers/models/backendconfiguration.py
  qiskit/test/mock/fake_openpulse_2q.py
  releasenotes/notes/add-config-processor-type-field-916f98f2eebf7e72.yaml
  test/python/providers/test_backendconfiguration.py
Labels: automerge

#6076 Fix failing pulse simulator tests
  qiskit/assembler/assemble_schedules.py
  test/python/compiler/test_assembler.py
Labels: automerge

#6064 Remove `VariationalForm` and `InitialState`
  qiskit/algorithms/__init__.py
  qiskit/algorithms/minimum_eigen_solvers/vqe.py
  qiskit/algorithms/variational_algorithm.py
  qiskit/algorithms/variational_forms/__init__.py
  qiskit/algorithms/variational_forms/variational_form.py
  qiskit/circuit/library/n_local/efficient_su2.py
  qiskit/circuit/library/n_local/excitation_preserving.py
  qiskit/circuit/library/n_local/n_local.py
  qiskit/circuit/library/n_local/real_amplitudes.py
  qiskit/circuit/library/n_local/two_local.py
Labels: automerge, mod: algorithms

#6009 Flatten when composing StateFn with ComposedOp
  qiskit/opflow/state_fns/state_fn.py
  test/python/opflow/test_state_construction.py
Labels: automerge, mod: opflow

#5958 Subcircuits with classical wires stay right of measures
  qiskit/visualization/utils.py
  releasenotes/notes/subcircuits-misorder-classical-4f075dfa694c55c3.yaml
  test/python/visualization/test_utils.py
Labels: Changelog: Bugfix

#6082 fix quantum instance shot handling
  qiskit/utils/quantum_instance.py
Labels: automerge

#5642 Implement quantum phase estimation algorithms
  qiskit/algorithms/__init__.py
  qiskit/algorithms/phase_estimators/__init__.py
  qiskit/algorithms/phase_estimators/hamiltonian_phase_estimation.py
  qiskit/algorithms/phase_estimators/hamiltonian_phase_estimation_result.py
  qiskit/algorithms/phase_estimators/phase_estimation.py
  qiskit/algorithms/phase_estimators/phase_estimation_result.py
  qiskit/algorithms/phase_estimators/phase_estimation_scale.py
  qiskit/algorithms/phase_estimators/phase_estimator.py
  test/python/algorithms/test_phase_estimator.py
Labels: mod: algorithms

#6077 Fixes QASM parser to handle U
  qiskit/converters/ast_to_dag.py
  qiskit/qasm/node/universalunitary.py
  test/python/circuit/test_circuit_load_from_qasm.py
  test/python/qasm/all_gates.qasm
Labels: Changelog: Bugfix, automerge, qasm

#6090 Pin matlotlib in CI
  requirements-dev.txt
Labels: automerge

#6024 Enable consolidate blocks to to work with single gate blocks
  qiskit/transpiler/passes/optimization/consolidate_blocks.py
  test/python/compiler/test_transpiler.py
  test/python/transpiler/test_consolidate_blocks.py
Labels: Changelog: Bugfix, automerge

#6040 Fix condition in BasisTranslator and change node.condition to @property
  qiskit/dagcircuit/dagcircuit.py
  qiskit/dagcircuit/dagnode.py
  qiskit/transpiler/passes/basis/basis_translator.py
  releasenotes/notes/missing-condition-transpile-e2bfb51aa2d3aa00.yaml
  test/python/transpiler/test_basis_translator.py
Labels: Changelog: Bugfix, automerge

#6067 Fix CalibrationBuilder
  qiskit/transpiler/passes/scheduling/calibration_creators.py
  releasenotes/notes/calibration-builder-fix-1b95d293729bb877.yaml
Labels: Changelog: Bugfix, automerge

#6107 Cap ipython and ipykernel in CI
  requirements-dev.txt
Labels: automerge

#6109 Properly clear parameter table on remove_final_measurement
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_circuit_operations.py
Labels: Changelog: Bugfix, automerge

#5609 add ECR gate and approximation_degree option
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/standard_gates/__init__.py
  qiskit/circuit/library/standard_gates/ecr.py
  qiskit/circuit/library/standard_gates/equivalence_library.py
  qiskit/circuit/quantumcircuit.py
  qiskit/compiler/transpiler.py
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/optimization/consolidate_blocks.py
  qiskit/transpiler/passes/synthesis/unitary_synthesis.py
  qiskit/transpiler/passes/utils/__init__.py
  qiskit/transpiler/passes/utils/check_cx_direction.py
  qiskit/transpiler/passes/utils/check_gate_direction.py
  qiskit/transpiler/passes/utils/cx_direction.py
  qiskit/transpiler/passes/utils/gate_direction.py
  qiskit/transpiler/passmanager_config.py
  qiskit/transpiler/preset_passmanagers/level0.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  releasenotes/notes/ecr-gate-45cfda1b84ac792c.yaml
  test/python/circuit/test_gate_definitions.py
  test/python/compiler/test_transpiler.py
  test/python/transpiler/test_basis_translator.py
  test/python/transpiler/test_check_gate_direction.py
  test/python/transpiler/test_gate_direction.py
  test/python/transpiler/test_preset_passmanagers.py
Labels: Changelog: New Feature, automerge

#5128 Migrate basic aer provider to new versioned interface
  azure-pipelines.yml
  qiskit/providers/basicaer/basicaerjob.py
  qiskit/providers/basicaer/basicaerprovider.py
  qiskit/providers/basicaer/qasm_simulator.py
  qiskit/providers/basicaer/statevector_simulator.py
  qiskit/providers/basicaer/unitary_simulator.py
  qiskit/utils/run_circuits.py
  releasenotes/notes/basicaer-new-provider-ea7cf756df231c2b.yaml
  test/python/basicaer/test_basicaer_integration.py
  test/python/basicaer/test_basicaer_qobj_headers.py
  test/python/basicaer/test_qasm_simulator.py
  test/python/providers/test_jobmethods.py
Labels: Changelog: API Change, Changelog: New Feature, automerge

#6111 Fix RecursionError in SummedOp.to_pauli_op() and enhance PauliOp.tensor(), PauliSumOp.tensor()
  qiskit/opflow/list_ops/summed_op.py
  qiskit/opflow/primitive_ops/pauli_op.py
  qiskit/opflow/primitive_ops/pauli_sum_op.py
  test/python/opflow/test_op_construction.py
  test/python/opflow/test_pauli_sum_op.py
Labels: automerge, mod: opflow

#5519 Visualization updates for optional registers.
  qiskit/compiler/transpiler.py
  qiskit/transpiler/basepasses.py
  qiskit/transpiler/layout.py
  qiskit/transpiler/passes/layout/apply_layout.py
  qiskit/transpiler/passes/layout/csp_layout.py
  qiskit/transpiler/passes/layout/dense_layout.py
  qiskit/transpiler/passes/layout/enlarge_with_ancilla.py
  qiskit/transpiler/passes/layout/full_ancilla_allocation.py
  qiskit/transpiler/passes/layout/noise_adaptive_layout.py
  qiskit/transpiler/passes/layout/sabre_layout.py
  qiskit/transpiler/passes/layout/trivial_layout.py
  qiskit/visualization/circuit_visualization.py
  qiskit/visualization/latex.py
  qiskit/visualization/matplotlib.py
  qiskit/visualization/text.py
  qiskit/visualization/utils.py
  test/python/transpiler/test_enlarge_with_ancilla_pass.py
  test/python/transpiler/test_full_ancilla_allocation.py
  test/python/transpiler/test_layout.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: automerge, optional-registers

#6045 Improve handling of non-unitary CircuitStateFns
  qiskit/opflow/state_fns/circuit_state_fn.py
  qiskit/opflow/state_fns/operator_state_fn.py
  test/python/opflow/test_state_op_meas_evals.py
Labels: automerge, mod: opflow

#6065 Overload & and ^ for ciruit.compose and circuit.tensor
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_circuit_operations.py
Labels: Changelog: New Feature, automerge

#6116 Refactor SPSA
  qiskit/algorithms/optimizers/spsa.py
  test/python/algorithms/optimizers/__init__.py
  test/python/algorithms/optimizers/test_nlopt_optimizers.py
  test/python/algorithms/optimizers/test_optimizer_aqgd.py
  test/python/algorithms/optimizers/test_optimizer_nft.py
  test/python/algorithms/optimizers/test_optimizers.py
  test/python/algorithms/optimizers/test_optimizers_scikitquant.py
  test/python/algorithms/optimizers/test_spsa.py
Labels: automerge, mod: algorithms

#6115 Fix deprecation warnings and minor misprints in the CNOTDihedral class
  qiskit/quantum_info/operators/dihedral/dihedral.py
  qiskit/quantum_info/synthesis/cnotdihedral_decompose.py
  test/python/quantum_info/operators/test_dihedral.py
Labels: automerge, mod: quantum info

#6120 Fix the deprecation warning from old BasicAer usage in CircuitStateFn
  qiskit/opflow/state_fns/circuit_state_fn.py
Labels: automerge, mod: opflow

#6072 Set sympy.evaluate(False) on frequent code paths for phase tracking.
  qiskit/dagcircuit/dagcircuit.py
  qiskit/transpiler/passes/basis/basis_translator.py
  releasenotes/notes/5405-Slow-transpilation-of-ExcitationPreserving-297f3afd4a987cac.yaml
Labels: automerge, performance

#6080 Deprecate probability distribution circuits
  qiskit/circuit/library/probability_distributions/lognormal.py
  qiskit/circuit/library/probability_distributions/normal.py
  qiskit/circuit/library/probability_distributions/uniform.py
Labels: automerge

#5830 Boolean expression object
  qiskit/circuit/__init__.py
  qiskit/circuit/classicalfunction/__init__.py
  qiskit/circuit/classicalfunction/boolean_expression.py
  qiskit/circuit/classicalfunction/classical_element.py
  qiskit/circuit/classicalfunction/classical_function_visitor.py
  qiskit/circuit/classicalfunction/classicalfunction.py
  qiskit/circuit/classicalfunction/utils.py
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/phase_oracle.py
  releasenotes/notes/bool_expression_phaseoracle-1802be3016c83fa8.yaml
  requirements-dev.txt
  setup.py
  test/python/circuit/library/test_phase_oracle.py
  test/python/circuit/test_extensions_standard.py
  test/python/circuit/test_gate_definitions.py
  test/python/classical_function_compiler/dimacs/quinn.cnf
  test/python/classical_function_compiler/dimacs/simple_v3_c2.cnf
  test/python/classical_function_compiler/test_boolean_expression.py
  test/python/classical_function_compiler/test_classical_function.py
  test/python/classical_function_compiler/test_simulate.py
  test/python/classical_function_compiler/test_synthesis.py
  test/python/classical_function_compiler/test_tweedledum2qiskit.py
Labels: Changelog: New Feature, automerge

#6084 no full scheduling of circuits with delay unless explicitly requested
  qiskit/compiler/transpiler.py
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/scheduling/__init__.py
  qiskit/transpiler/passes/scheduling/alap.py
  qiskit/transpiler/passes/scheduling/asap.py
  qiskit/transpiler/passes/scheduling/time_unit_conversion.py
  qiskit/transpiler/preset_passmanagers/level0.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  releasenotes/notes/convert-delay-units-62b3a5cf7650a0f4.yaml
  test/python/circuit/test_scheduled_circuit.py
  test/python/transpiler/test_scheduling_pass.py
Labels: Changelog: Bugfix, automerge
