Repository Qiskit/qiskit, pull requests merged in 2021-12, with the labels that each got.

#7327 Adjust imports in aqc plugin to avoid discovery overhead
  qiskit/transpiler/synthesis/aqc/aqc_plugin.py
Labels: performance, automerge, Changelog: None

#5885 Add BackendV2 abstract class
  qiskit/compiler/scheduler.py
  qiskit/compiler/transpiler.py
  qiskit/providers/__init__.py
  qiskit/providers/backend.py
  qiskit/providers/options.py
  qiskit/test/mock/__init__.py
  qiskit/test/mock/fake_backend_v2.py
  qiskit/transpiler/__init__.py
  qiskit/transpiler/target.py
  releasenotes/notes/add-backend-v2-ce84c976fb13b038.yaml
  test/python/providers/test_backend_v2.py
  test/python/providers/test_options.py
  test/python/transpiler/test_target.py
Labels: priority: high, Changelog: New Feature, automerge, ISA

#7331 Fix arguments for RZXCalibrationBuilder and EchoRZXWeylDecomposition
  qiskit/transpiler/passes/calibration/builders.py
  qiskit/transpiler/passes/optimization/echo_rzx_weyl_decomposition.py
  releasenotes/notes/deprecate-backend-rzx-cal-build-8eda1526725d7e7d.yaml
  test/python/pulse/test_calibrationbuilder.py
  test/python/transpiler/test_echo_rzx_weyl_decomposition.py
Labels: Changelog: Deprecation, automerge

#7299 Add control flow support to QASM 3 exporter
  qiskit/circuit/library/standard_gates/x.py
  qiskit/qasm3/__init__.py
  qiskit/qasm3/ast.py
  qiskit/qasm3/exceptions.py
  qiskit/qasm3/exporter.py
  qiskit/qasm3/printer.py
  test/python/circuit/test_circuit_qasm3.py
Labels: priority: high, automerge, qasm, Changelog: None

#7323 Update top level provider documentation for BackendV2
  qiskit/providers/__init__.py
Labels: type: documentation, priority: high, automerge, Changelog: None

#7336 Fail safe in the QASM 3 exporter
  qiskit/qasm3/exporter.py
  releasenotes/notes/qasm3-limitations-ebfdedab3f4ab6e1.yaml
  test/python/circuit/test_circuit_qasm3.py
Labels: priority: high, automerge, qasm, Changelog: None

#7338 Fix performance regression of VQE by #7217
  qiskit/opflow/converters/circuit_sampler.py
Labels: mod: algorithms, Changelog: None

#7334 Speed up passmanager if it is empty
  qiskit/transpiler/passmanager.py
Labels: automerge, Changelog: None

#7282 Add control-flow builder interface
  qiskit/circuit/controlflow/__init__.py
  qiskit/circuit/controlflow/break_loop.py
  qiskit/circuit/controlflow/builder.py
  qiskit/circuit/controlflow/condition.py
  qiskit/circuit/controlflow/continue_loop.py
  qiskit/circuit/controlflow/for_loop.py
  qiskit/circuit/controlflow/if_else.py
  qiskit/circuit/controlflow/while_loop.py
  qiskit/circuit/quantumcircuit.py
  qiskit/qasm3/ast.py
  qiskit/qasm3/exporter.py
  releasenotes/notes/control-flow-builder-interface-63910843f8bea5e0.yaml
  test/python/circuit/test_circuit_operations.py
  test/python/circuit/test_circuit_qasm3.py
  test/python/circuit/test_control_flow.py
  test/python/circuit/test_control_flow_builders.py
Labels: priority: high, Changelog: New Feature, automerge, circuit-builder

#7345 Omit QuantumCircuit as a parameter when drawing ControlFlowOps.
  qiskit/visualization/utils.py
Labels: bug, automerge, Changelog: None

#6485 Readout mitigator classes
  qiskit/result/__init__.py
  qiskit/result/counts.py
  qiskit/result/distributions/quasi.py
  qiskit/result/mitigation/__init__.py
  qiskit/result/mitigation/base_readout_mitigator.py
  qiskit/result/mitigation/correlated_readout_mitigator.py
  qiskit/result/mitigation/local_readout_mitigator.py
  qiskit/result/mitigation/utils.py
  releasenotes/notes/readout-mitigation-classes-2ef175e232d791ae.yaml
  test/python/result/test_mitigators.py
Labels: Changelog: New Feature, automerge, mod: quantum info

#7347 Hack in SimpleNamespace-like functionality to Options
  qiskit/providers/options.py
  test/python/providers/test_options.py
Labels: priority: high, automerge, Changelog: None

#7227 Start making the transpiler Target aware
  qiskit/compiler/transpiler.py
  qiskit/providers/backend.py
  qiskit/test/mock/__init__.py
  qiskit/test/mock/fake_backend_v2.py
  qiskit/test/mock/fake_mumbai_v2.py
  qiskit/transpiler/passes/basis/basis_translator.py
  qiskit/transpiler/passes/utils/check_gate_direction.py
  qiskit/transpiler/passes/utils/gate_direction.py
  qiskit/transpiler/passmanager_config.py
  qiskit/transpiler/preset_passmanagers/level0.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  qiskit/transpiler/target.py
  releasenotes/notes/target-in-transpiler-c0a97bd33ad9417d.yaml
  test/python/providers/test_backend_v2.py
  test/python/transpiler/test_basis_translator.py
  test/python/transpiler/test_target.py
Labels: priority: high, automerge, Changelog: None

#7353 Add copy method to Options
  qiskit/providers/options.py
  test/python/providers/test_options.py
Labels: automerge, Changelog: None

#7357 Bump version strings post release
  .mergify.yml
  docs/conf.py
  qiskit/VERSION.txt
  setup.py
Labels: automerge, Changelog: None

#7295 Drop support for Python 3.6
  azure-pipelines.yml
  qiskit/__init__.py
  releasenotes/notes/drop-python3.6-support-45ecc9e1832934cd.yaml
  requirements.txt
  setup.py
  tox.ini
Labels: Changelog: Removal, automerge

#7363 Bump black to the latest version
  qiskit/test/base.py
  requirements-dev.txt
  test/ipynb/mpl_tester.ipynb
  test/python/notebooks/test_backend_tools.ipynb
  test/python/notebooks/test_pbar_status.ipynb
Labels: automerge, Changelog: None

#7365 Fix circuit instruction conversion with loose bits
  qiskit/converters/circuit_to_gate.py
  qiskit/converters/circuit_to_instruction.py
  releasenotes/notes/0.19/fix-circuit-conversion-loose-qubits-8d190426e4e892f1.yaml
  test/python/converters/test_circuit_to_gate.py
  test/python/converters/test_circuit_to_instruction.py
Labels: stable backport potential, Changelog: Bugfix

#7368 Fix copying control-flow bodies in builder interface
  qiskit/circuit/controlflow/builder.py
  releasenotes/notes/0.19/fix-control-flow-builder-parameter-copy-b1f6efcc6bc283e7.yaml
  test/python/circuit/test_control_flow_builders.py
Labels: stable backport potential, Changelog: Bugfix, automerge, circuit-builder

#7358 Fix VM image used for Linux release jobs
  azure-pipelines.yml
Labels: stable backport potential, automerge, Changelog: None

#7375 documentation update: c_if needs val
  qiskit/circuit/controlflow/for_loop.py
  qiskit/circuit/quantumcircuit.py
Labels: stable backport potential, automerge, Changelog: None

#7376 Reinstate and deprecate loose measure and reset functions
  qiskit/circuit/measure.py
  qiskit/circuit/reset.py
  releasenotes/notes/reinstate-deprecate-loose-measure-reset-11591e35d350aaeb.yaml
  test/python/circuit/test_circuit_operations.py
Labels: stable backport potential, Changelog: Deprecation, Changelog: Bugfix, automerge

#7383 Fix InverseCancellation pass to handle gates of different names.
  qiskit/transpiler/passes/optimization/inverse_cancellation.py
  test/python/transpiler/test_inverse_cancellation.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#7381 Fix ParameterVector handling in QPY serialization
  qiskit/circuit/qpy_serialization.py
  releasenotes/notes/fix-paramater-vector-qpy-52b16ccefecf8b2e.yaml
  test/python/circuit/test_circuit_load_from_qpy.py
  test/qpy_compat/test_qpy.py
Labels: stable backport potential, Changelog: Bugfix, automerge, mod: qpy

#7389 Fix register conditions in control-flow builders
  qiskit/circuit/controlflow/break_loop.py
  qiskit/circuit/controlflow/builder.py
  qiskit/circuit/controlflow/condition.py
  qiskit/circuit/controlflow/continue_loop.py
  qiskit/circuit/controlflow/for_loop.py
  qiskit/circuit/controlflow/if_else.py
  qiskit/circuit/controlflow/while_loop.py
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/fix-circuit-builder-registers-21deba9a43356fb5.yaml
  test/python/circuit/test_control_flow_builders.py
Labels: stable backport potential, Changelog: Bugfix, automerge, circuit-builder

#7396 Prepare 0.19.1 release
  docs/conf.py
  qiskit/VERSION.txt
  releasenotes/notes/0.19/fix-circuit-conversion-loose-qubits-8d190426e4e892f1.yaml
  releasenotes/notes/prepare-0.19.1-37d14fd5cf05a576.yaml
  setup.py
Labels: automerge, Changelog: None

#7395 Fix registerless bit conditions in circuit_to_instruction
  qiskit/converters/circuit_to_instruction.py
  releasenotes/notes/fix-circuit_to_instruction_single-bit-condition-db75291ce921001a.yaml
  test/python/converters/test_circuit_to_instruction.py
Labels: stable backport potential, Changelog: Bugfix

#7421 Pin Aer to 0.9.1 in CI
  .github/workflows/randomized_tests.yml
  azure-pipelines.yml
  tox.ini
Labels: stable backport potential, automerge, Changelog: None

#7186 Add the dark version of the IQX color scheme
  qiskit/visualization/matplotlib.py
  qiskit/visualization/styles/iqx-dark.json
  releasenotes/notes/iqx-dark-3dd0a500e1801673.yaml
  test/ipynb/mpl/circuit/references/iqx-dark_color.png
  test/ipynb/mpl/circuit/test_circuit_matplotlib_drawer.py
Labels: Changelog: New Feature, automerge

#7427 Revert "Pin Aer to 0.9.1 in CI (#7421)"
  .github/workflows/randomized_tests.yml
  azure-pipelines.yml
  tox.ini
Labels: stable backport potential, automerge, Changelog: None

#7426 Deprecate SuzukiTrotter odd order
  qiskit/synthesis/evolution/suzuki_trotter.py
  releasenotes/notes/deprecate_odd_suzuki-091178b1bdc8b172.yaml
  test/python/circuit/library/test_evolution_gate.py
Labels: Changelog: Deprecation, automerge

#7229 Add XYGate (#7164)
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/standard_gates/__init__.py
  qiskit/circuit/library/standard_gates/xy.py
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/add-xy-gate-e3ac32084273136a.yaml
  test/python/circuit/test_parameters.py
Labels: Changelog: New Feature, automerge

#7436 Pass `phase` in `PauliList.from_symplectic` example
  qiskit/quantum_info/operators/symplectic/pauli_list.py
Labels: stable backport potential, automerge, Changelog: None

#7435 Fix a few typos in comments and strings
  qiskit/algorithms/__init__.py
  qiskit/opflow/operator_globals.py
  qiskit/opflow/primitive_ops/pauli_sum_op.py
  qiskit/quantum_info/operators/measures.py
Labels: stable backport potential, automerge, Changelog: None

#7443 Update garrison's name in .mailmap
  .mailmap
Labels: automerge, Changelog: None

#7328 Added example of Parameter usage in docstring
  qiskit/circuit/parameter.py
Labels: stable backport potential, automerge, Changelog: None
