Repository Qiskit/qiskit, pull requests merged in 2021-07, with the labels that each got.

#6670 Fix for "Add Operator Settings #6650"
  qiskit/opflow/gradients/gradient.py
  qiskit/opflow/list_ops/list_op.py
Labels: Changelog: None, automerge, bug, mod: opflow, priority: high

#6625 Fixed issue 6623 by raising errors for negative delay durations
  qiskit/circuit/delay.py
  test/python/circuit/test_delay.py
Labels: Changelog: Bugfix, automerge

#6593 Replace SnapshotExpectationValue with SaveExpectationValue
  qiskit/opflow/converters/circuit_sampler.py
  qiskit/opflow/expectations/aer_pauli_expectation.py
  test/python/opflow/test_aer_pauli_expectation.py
Labels: Changelog: None, automerge, mod: opflow

#6580 BIP mapping pass
  azure-pipelines.yml
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/routing/__init__.py
  qiskit/transpiler/passes/routing/algorithms/bip_model.py
  qiskit/transpiler/passes/routing/bip_mapping.py
  releasenotes/notes/add-bip-mapper-f729f2c5672d7f3e.yaml
  requirements-dev.txt
  setup.py
  test/python/transpiler/test_bip_mapping.py
Labels: Changelog: New Feature, automerge, priority: high

#6564 Fixed qc.num_connected_components() for circuits with bit conditioned gates
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_circuit_properties.py
Labels: Changelog: Bugfix, automerge

#6588 Make tweedledum a hard requirement
  .pylintrc
  qiskit/circuit/classicalfunction/boolean_expression.py
  qiskit/circuit/classicalfunction/classical_function_visitor.py
  qiskit/circuit/classicalfunction/classicalfunction.py
  qiskit/circuit/classicalfunction/utils.py
  releasenotes/notes/requirements-updates-6059950dfde3cef6.yaml
  requirements.txt
  setup.py
  test/python/classical_function_compiler/test_classical_function.py
  test/python/classical_function_compiler/test_parse.py
  test/python/classical_function_compiler/test_simulate.py
  test/python/classical_function_compiler/test_synthesis.py
  test/python/classical_function_compiler/test_typecheck.py
Labels: Changelog: API Change, automerge

#6626 Move `Gate.label` to parent `Instruction` class
  qiskit/circuit/gate.py
  qiskit/circuit/instruction.py
  qiskit/circuit/library/blueprintcircuit.py
  qiskit/circuit/quantumcircuit.py
  qiskit/converters/circuit_to_instruction.py
  qiskit/extensions/simulator/snapshot.py
Labels: Changelog: API Change, automerge

#6545 Add settings property to optimizer classes in ``qiskit.algorithms.optimizers``
  qiskit/algorithms/optimizers/adam_amsgrad.py
  qiskit/algorithms/optimizers/aqgd.py
  qiskit/algorithms/optimizers/bobyqa.py
  qiskit/algorithms/optimizers/gradient_descent.py
  qiskit/algorithms/optimizers/gsls.py
  qiskit/algorithms/optimizers/imfil.py
  qiskit/algorithms/optimizers/nlopts/nloptimizer.py
  qiskit/algorithms/optimizers/optimizer.py
  qiskit/algorithms/optimizers/qnspsa.py
  qiskit/algorithms/optimizers/scipy_optimizer.py
  qiskit/algorithms/optimizers/snobfit.py
  qiskit/algorithms/optimizers/spsa.py
  releasenotes/notes/serializable-optimizers-642402828b0c733b.yaml
  test/python/algorithms/optimizers/test_optimizers.py
  test/python/algorithms/optimizers/test_spsa.py
  test/python/opflow/test_gradients.py
Labels: Changelog: New Feature, automerge, mod: algorithms

#6673 Add align measure pass
  qiskit/compiler/transpiler.py
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/scheduling/__init__.py
  qiskit/transpiler/passes/scheduling/instruction_alignment.py
  qiskit/transpiler/passmanager_config.py
  qiskit/transpiler/preset_passmanagers/level0.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  releasenotes/notes/add-alignment-management-passes-650b8172e1426a73.yaml
  test/python/transpiler/test_instruction_alignments.py
Labels: Changelog: New Feature, automerge, priority: high

#6370 Classical condition boxes are now drawn as bullets in text drawer
  qiskit/visualization/circuit_visualization.py
  qiskit/visualization/text.py
  releasenotes/notes/change-clcond-boxes-to-bullets-2f1799fc23793929.yaml
  test/python/visualization/test_circuit_text_drawer.py
Labels: Changelog: API Change, automerge

#6683 fix bug in layout deletion
  qiskit/transpiler/layout.py
  test/python/transpiler/test_layout.py
Labels: Changelog: Bugfix, automerge

#6274 Add Expectation Converter to Gradient Wrapper
  qiskit/opflow/gradients/derivative_base.py
  releasenotes/notes/grad_wrapper_expectation-5214882ba482c62f.yaml
  test/python/opflow/test_gradients.py
Labels: Changelog: Bugfix, automerge, mod: opflow

#6288 Pulse: fix minor docstring errors
  qiskit/pulse/__init__.py
  qiskit/pulse/schedule.py
Labels: automerge, stable backport potential

#6619 Add dynamical decoupling transpiler pass
  qiskit/circuit/library/standard_gates/u.py
  qiskit/dagcircuit/dagcircuit.py
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/scheduling/__init__.py
  qiskit/transpiler/passes/scheduling/dynamical_decoupling.py
  releasenotes/notes/dynamical-decoupling-3ce6e882954f6d3b.yaml
  test/python/transpiler/test_dynamical_decoupling.py
Labels: Changelog: New Feature, automerge, priority: high

#6686 Revert "Performance improvement for Collect2qBlocks (#6534)"
  qiskit/transpiler/passes/optimization/collect_2q_blocks.py
  test/python/transpiler/test_collect_2q_blocks.py
Labels: Changelog: None, automerge, performance

#6546 Fix ``QuantumCircuit.assign_parameters`` docstring
  qiskit/circuit/library/n_local/n_local.py
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/remove-deprecated-assign-parameters-args-9712d7d01e82c390.yaml
Labels: Changelog: Bugfix, Changelog: Removal, automerge

#6553 Fix `Optimize1qGatesDecomposition` length heuristic
  qiskit/quantum_info/synthesis/one_qubit_decompose.py
  qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py
  releasenotes/notes/fixed-bug-in-Optimize1qGatesDecomposition-skipping-short-sequences-044a64740bf414a7.yaml
  test/python/compiler/test_transpiler.py
  test/python/opflow/test_pauli_sum_op.py
  test/python/pulse/test_builder.py
  test/python/quantum_info/test_synthesis.py
  test/python/transpiler/test_basis_translator.py
  test/python/transpiler/test_optimize_1q_decomposition.py
Labels: Changelog: Bugfix, automerge, bug

#6634 Wrap library circuits
  qiskit/algorithms/linear_solvers/matrices/tridiagonal_toeplitz.py
  qiskit/algorithms/minimum_eigen_solvers/qaoa.py
  qiskit/circuit/library/arithmetic/adders/cdkm_ripple_carry_adder.py
  qiskit/circuit/library/arithmetic/adders/draper_qft_adder.py
  qiskit/circuit/library/arithmetic/adders/vbe_ripple_carry_adder.py
  qiskit/circuit/library/arithmetic/exact_reciprocal.py
  qiskit/circuit/library/arithmetic/integer_comparator.py
  qiskit/circuit/library/arithmetic/linear_amplitude_function.py
  qiskit/circuit/library/arithmetic/linear_pauli_rotations.py
  qiskit/circuit/library/arithmetic/multipliers/hrs_cumulative_multiplier.py
  qiskit/circuit/library/arithmetic/multipliers/rg_qft_multiplier.py
  qiskit/circuit/library/arithmetic/piecewise_chebyshev.py
  qiskit/circuit/library/arithmetic/piecewise_linear_pauli_rotations.py
  qiskit/circuit/library/arithmetic/piecewise_polynomial_pauli_rotations.py
  qiskit/circuit/library/arithmetic/polynomial_pauli_rotations.py
  qiskit/circuit/library/arithmetic/quadratic_form.py
  qiskit/circuit/library/arithmetic/weighted_adder.py
  qiskit/circuit/library/basis_change/qft.py
  qiskit/circuit/library/boolean_logic/inner_product.py
  qiskit/circuit/library/boolean_logic/quantum_and.py
  qiskit/circuit/library/boolean_logic/quantum_or.py
  qiskit/circuit/library/boolean_logic/quantum_xor.py
  qiskit/circuit/library/data_preparation/pauli_feature_map.py
  qiskit/circuit/library/data_preparation/z_feature_map.py
  qiskit/circuit/library/data_preparation/zz_feature_map.py
  qiskit/circuit/library/evolved_operator_ansatz.py
  qiskit/circuit/library/fourier_checking.py
  qiskit/circuit/library/generalized_gates/diagonal.py
  qiskit/circuit/library/generalized_gates/gms.py
  qiskit/circuit/library/generalized_gates/gr.py
  qiskit/circuit/library/generalized_gates/permutation.py
  qiskit/circuit/library/graph_state.py
  qiskit/circuit/library/grover_operator.py
  qiskit/circuit/library/hidden_linear_function.py
  qiskit/circuit/library/iqp.py
  qiskit/circuit/library/n_local/efficient_su2.py
  qiskit/circuit/library/n_local/excitation_preserving.py
  qiskit/circuit/library/n_local/n_local.py
  qiskit/circuit/library/n_local/pauli_two_design.py
  qiskit/circuit/library/n_local/real_amplitudes.py
  qiskit/circuit/library/n_local/two_local.py
  qiskit/circuit/library/phase_estimation.py
  qiskit/circuit/library/probability_distributions/lognormal.py
  qiskit/circuit/library/probability_distributions/normal.py
  qiskit/circuit/library/probability_distributions/uniform.py
  qiskit/circuit/library/quantum_volume.py
  releasenotes/notes/wrap-library-circuits-9b7f7398f3fce8a8.yaml
  test/python/algorithms/test_amplitude_estimators.py
  test/python/circuit/library/test_boolean_logic.py
  test/python/circuit/library/test_evolved_op_ansatz.py
  test/python/circuit/library/test_global_r.py
  test/python/circuit/library/test_grover_operator.py
  test/python/circuit/library/test_nlocal.py
  test/python/circuit/library/test_phase_estimation.py
  test/python/circuit/library/test_probability_distributions.py
  test/python/circuit/library/test_qaoa_ansatz.py
  test/python/circuit/library/test_qft.py
  test/python/circuit/library/test_random_pauli.py
  test/python/opflow/test_gradients.py
Labels: Changelog: API Change

#6523 Fix support for standalone registers in qpy format
  qiskit/circuit/instruction.py
  qiskit/circuit/qpy_serialization.py
  test/python/circuit/test_circuit_load_from_qpy.py
Labels: Changelog: None, automerge, priority: high

#6681 More docstring for align passes
  qiskit/transpiler/passes/scheduling/instruction_alignment.py
Labels: Changelog: None, automerge

#6659 Add the option to wrap circuits in ``QuantumCircuit.compose``
  qiskit/circuit/library/blueprintcircuit.py
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/compose-can-wrap-e839c29e426051e8.yaml
  test/python/circuit/test_compose.py
Labels: Changelog: New Feature, automerge

#5887 Fix qasm output for composite gates
  qiskit/circuit/quantumcircuit.py
  qiskit/extensions/unitary.py
  releasenotes/notes/fix-qasm-output-for-composite-gates-cc847103eec26c85.yaml
  test/python/circuit/test_circuit_qasm.py
  test/python/circuit/test_unitary.py
Labels: Changelog: Bugfix, PR for good first issue, automerge, qasm

#6697 Fix wrapping of ``GroverOperator``
  qiskit/circuit/library/grover_operator.py
  test/python/circuit/library/test_grover_operator.py
Labels: Changelog: None, automerge, priority: high

#6696 Revert "Fix ``QuantumCircuit.assign_parameters`` docstring (#6546)"
  qiskit/circuit/library/n_local/n_local.py
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/remove-deprecated-assign-parameters-args-9712d7d01e82c390.yaml
Labels: Changelog: None, automerge, priority: high

#6701 fix register in Layout found by BIP
  qiskit/transpiler/passes/routing/algorithms/bip_model.py
Labels: Changelog: None, automerge

#6704 Wrap probability distributions to `Gate`s, not `Instruction`s
  qiskit/circuit/library/probability_distributions/lognormal.py
  qiskit/circuit/library/probability_distributions/normal.py
Labels: Changelog: None, automerge, priority: high

#6705 Alignment to pulse constraints
  qiskit/compiler/transpiler.py
  qiskit/transpiler/passes/scheduling/instruction_alignment.py
  qiskit/transpiler/passmanager_config.py
  qiskit/transpiler/preset_passmanagers/level0.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  qiskit/transpiler/timing_constraints.py
  releasenotes/notes/add-alignment-management-passes-650b8172e1426a73.yaml
  test/python/transpiler/test_instruction_alignments.py
Labels: Changelog: None, automerge

#6711 Pin networkx for CI
  constraints.txt
Labels: automerge, priority: high

#6581 Pulse optimal decomposition of su4 for CNOT
  qiskit/circuit/quantumcircuit.py
  qiskit/quantum_info/synthesis/one_qubit_decompose.py
  qiskit/quantum_info/synthesis/two_qubit_decompose.py
  qiskit/transpiler/passes/synthesis/unitary_synthesis.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  releasenotes/notes/pulse_optimal_synthesis_cx_sx_rz-95156cc79231ffea.yaml
  test/python/quantum_info/test_synthesis.py
  test/python/transpiler/test_unitary_synthesis.py
Labels: Changelog: New Feature, automerge, priority: high

#6685 Use ddt for test_transpile_across_optimization_levels
  test/python/circuit/test_parameters.py
Labels: Changelog: None, automerge

#6713 Handle complex parameters and blueprint circuits in QPY
  qiskit/circuit/qpy_serialization.py
  test/python/circuit/test_circuit_load_from_qpy.py
Labels: Changelog: Bugfix, automerge, stable backport potential

#6722 Bump version strings post release
  .mergify.yml
  docs/conf.py
  qiskit/VERSION.txt
  setup.py
Labels: Changelog: None, automerge

#6730 Handle complex parameters and blueprint circuits in QPY (#6713)
  qiskit/circuit/qpy_serialization.py
  test/python/circuit/test_circuit_load_from_qpy.py
Labels: Changelog: Bugfix, automerge, stable-backport

#6723 Fix ``QuantumCircuit.assign_parameters`` docstring
  qiskit/circuit/library/n_local/n_local.py
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/remove-deprecated-assign-parameters-args-9712d7d01e82c390.yaml
Labels: Changelog: Bugfix, Changelog: Removal, automerge

#6644 Change operator comparison from `np.array_equal` to `np.allclose` (#6473)
  qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py
  releasenotes/notes/one-gate-identity-optimization-fix-d6d1496d9f5409a6.yaml
Labels: Changelog: Bugfix, automerge, stable backport potential

#6610 implement coeffs method for SummedOp (Issue #5931), matching coeffs m…
  qiskit/opflow/list_ops/list_op.py
  releasenotes/notes/listops-coeffs-1e04a34b46b2fd23.yaml
  test/python/opflow/test_pauli_sum_op.py
Labels: Changelog: New Feature, automerge, mod: opflow

#6261 Text drawer extended for drawing circuits with single classical bit conditioning
  qiskit/dagcircuit/dagcircuit.py
  qiskit/visualization/text.py
  qiskit/visualization/utils.py
  releasenotes/notes/fix-text-drawer-bit-cond-a3b02f0b0b6e3ec2.yaml
  test/python/visualization/test_circuit_text_drawer.py
Labels: Changelog: New Feature, automerge

#6505 Better ParameterExpression.__str__ by turning off full precision
  qiskit/circuit/parameterexpression.py
  releasenotes/notes/full_prec_sympy-aeee8210091ef20f.yaml
Labels: Changelog: None, automerge

#6737 update docstrings in UnitarySynthesis pass
  qiskit/transpiler/passes/synthesis/unitary_synthesis.py
Labels: automerge, stable backport potential, type: documentation

#6587 QuantumCircuit.decompose() does not take a single gate, but a set of gates to decompose.
  qiskit/circuit/quantumcircuit.py
  qiskit/transpiler/passes/basis/decompose.py
  releasenotes/notes/QuantumCircuit.decompose-takes-which-gate-to-decompose-d857da5d0c41fb66.yaml
  test/python/transpiler/test_decompose.py
Labels: Changelog: API Change, PR for good first issue, automerge

#6558 Remove deprecated schemas and validation modules
  docs/apidocs/terra.rst
  docs/apidocs/validation.rst
  qiskit/compiler/assembler.py
  qiskit/qobj/__init__.py
  qiskit/qobj/common.py
  qiskit/qobj/pulse_qobj.py
  qiskit/qobj/qasm_qobj.py
  qiskit/qobj/utils.py
  qiskit/schemas/backend_configuration_schema.json
  qiskit/schemas/backend_properties_schema.json
  qiskit/schemas/backend_status_schema.json
  qiskit/schemas/default_pulse_configuration_schema.json
  qiskit/schemas/deprecated/backends/backend_calibration_example.json
  qiskit/schemas/deprecated/backends/backend_calibration_schema.json
  qiskit/schemas/deprecated/backends/backend_configuration_example_old.json
  qiskit/schemas/deprecated/backends/backend_configuration_schema_old_py.json
  qiskit/schemas/deprecated/backends/backend_parameters_example.json
  qiskit/schemas/deprecated/backends/backend_parameters_schema.json
  qiskit/schemas/deprecated/backends/backend_status_example.json
  qiskit/schemas/deprecated/backends/backend_status_schema_py.json
  qiskit/schemas/deprecated/qobj/qobj_core_schema.json
  qiskit/schemas/deprecated/qobj/qobj_example.json
  qiskit/schemas/deprecated/qobj/qobj_generic_schema.json
  qiskit/schemas/deprecated/result/result_example.json
  qiskit/schemas/deprecated/result/result_schema.json
  qiskit/schemas/examples/backend_configuration_openpulse_example.json
  qiskit/schemas/examples/backend_configuration_openqasm_example.json
  qiskit/schemas/examples/backend_configuration_openqasm_simulator_example.json
  qiskit/schemas/examples/backend_properties_example.json
  qiskit/schemas/examples/backend_status_example.json
  qiskit/schemas/examples/default_pulse_configuration_example.json
  qiskit/schemas/examples/job_status_example.json
  qiskit/schemas/examples/qasm_w_pulse_gates.json
  qiskit/schemas/examples/qobj_openpulse_example.json
  qiskit/schemas/examples/qobj_openqasm_example.json
  qiskit/schemas/examples/result_openpulse_level_0_example.json
  qiskit/schemas/examples/result_openpulse_level_1_example.json
  qiskit/schemas/examples/result_openqasm_example.json
  qiskit/schemas/examples/result_statevector_simulator_example.json
  qiskit/schemas/examples/result_unitary_simulator_example.json
  qiskit/schemas/ibmq_device_qobj_schema.json
  qiskit/schemas/ibmq_simulator_qobj_schema.json
  qiskit/schemas/job_status_schema.json
  qiskit/schemas/qobj_schema.json
  qiskit/schemas/result_schema.json
  qiskit/validation/__init__.py
  qiskit/validation/jsonschema/__init__.py
  qiskit/validation/jsonschema/exceptions.py
  qiskit/validation/jsonschema/schema_validation.py
  releasenotes/notes/remove-schemas-ca9f3f2e0f08bca8.yaml
  requirements.txt
  test/python/circuit/test_unitary.py
  test/python/compiler/test_assembler.py
  test/python/qobj/test_qobj.py
  test/python/test_schemas.py
Labels: Changelog: Removal, automerge, performance

#6743 Fix fake backend kwargs
  qiskit/test/mock/fake_backend.py
  releasenotes/notes/fix-kwargs-mock-f581d5118a1c7589.yaml
  test/python/mock/test_fake_backends.py
Labels: Changelog: Bugfix, automerge, stable backport potential

#6537 Fixes circuit_to_instruction() method for circuits containing single bit conditions
  qiskit/converters/circuit_to_instruction.py
  test/python/converters/test_circuit_to_instruction.py
Labels: Changelog: Bugfix, automerge

#5661 Add circuit calibrations to disassembler
  qiskit/assembler/disassemble.py
  releasenotes/notes/add-circuit-calibrations-to-diassambler-2e68437a815cc729.yaml
  test/python/compiler/test_disassembler.py
Labels: Changelog: Bugfix, automerge

#6765 sx and sxdg colored as cliffords in mpl
  qiskit/visualization/qcstyle.py
Labels: automerge

#6758 Convert sym in pi_check to sympy sstr instead of str
  qiskit/circuit/tools/pi_check.py
  test/python/circuit/test_tools.py
Labels: Changelog: None, automerge

#6756 Add qubit_subset option to BIPMapping pass
  qiskit/transpiler/passes/routing/algorithms/bip_model.py
  qiskit/transpiler/passes/routing/bip_mapping.py
  releasenotes/notes/add-qubit-subset-to-bip-mapper-e1c6234d04484d58.yaml
  test/python/transpiler/test_bip_mapping.py
Labels: Changelog: New Feature

#6767 Improved optimization formulation for BIPMapper
  qiskit/transpiler/passes/routing/algorithms/bip_model.py
Labels: Changelog: None, performance

#6770 Add f to f-strings in mpl tester results.py
  test/ipynb/results.py
Labels: Changelog: None, automerge

#6783 Reapply "Performance improvement for Collect2qBlocks (#6534)"
  qiskit/transpiler/passes/optimization/collect_2q_blocks.py
  test/python/transpiler/test_collect_2q_blocks.py
Labels: automerge, performance

#6489 Remove U1, U2, and U3 gates from mpl tester to eliminate deprecation warnings
  qiskit/test/base.py
  test/ipynb/mpl/circuit/references/ctrl_labels.png
  test/ipynb/mpl/circuit/references/iqx_color.png
  test/ipynb/mpl/circuit/references/partial_layout.png
  test/ipynb/mpl/circuit/references/u_gates.png
  test/ipynb/mpl/circuit/references/user_style.png
  test/ipynb/mpl/circuit/test_circuit_matplotlib_drawer.py
Labels: Changelog: None, automerge

#6786 Add Jake to mailmap
  .mailmap
Labels: Changelog: None, automerge

#6700 Fix Gaussian Square Curve Docstring
  qiskit/pulse/library/parametric_pulses.py
Labels: Changelog: None, automerge

#6539 Disable parallel sphinx builds by default
  tox.ini
Labels: Changelog: None, automerge

#6782 Fix CompleteMeasFitter not imported in QuantumInstance
  qiskit/utils/quantum_instance.py
  qiskit/utils/run_circuits.py
  releasenotes/notes/completemeasfitter-386e94a271ba0180.yaml
  test/python/algorithms/test_measure_error_mitigation.py
Labels: automerge, bug, mod: algorithms, priority: high, stable backport potential

#6597 Add incremental pylint make target
  CONTRIBUTING.md
  Makefile
  tools/pylint_incr.py
  tox.ini
Labels: Changelog: None, automerge, type: qa

#6695 Add QPY backwards compatibility testing
  azure-pipelines.yml
  test/qpy_compat/run_tests.sh
  test/qpy_compat/test_qpy.py
Labels: Changelog: None, automerge, type: qa

#6796 Fix QPY documentation
  docs/apidocs/qpy.rst
  qiskit/circuit/qpy_serialization.py
Labels: Changelog: None, stable backport potential

#6792 Ensure a non-parameterized global phase in `EvolvedOperatorAnsatz` is a float
  qiskit/circuit/library/evolved_operator_ansatz.py
  releasenotes/notes/fix-qaoa-to-qpy-6364c96671bc8f36.yaml
  test/python/circuit/test_circuit_load_from_qpy.py
Labels: Changelog: Bugfix, automerge

#6771 Set minimum size for empty matplotlib circuit drawings
  qiskit/visualization/pulse_v2/plotters/matplotlib.py
Labels: Changelog: None, automerge

#6807 Consolidate quick CI jobs into 3.7 linux unittest job
  azure-pipelines.yml
Labels: Changelog: None, automerge, stable backport potential

#6738 Fix subgraph handling of non-contiguous nodelist argument
  qiskit/transpiler/coupling.py
  releasenotes/notes/fix-subgraph-cmap-47021596d94bb39f.yaml
  test/python/transpiler/test_coupling.py
Labels: Changelog: Bugfix, automerge, stable backport potential

#6814 Make zip in transpiler parsing more descriptive
  qiskit/compiler/transpiler.py
Labels: Changelog: None, automerge

#6598 Fix JupyterLab compatibility with job watcher widget
  qiskit/tools/jupyter/job_widgets.py
Labels: Changelog: Bugfix, automerge, stable backport potential

#6775 Handle single bit conditions in QPY
  qiskit/circuit/qpy_serialization.py
  releasenotes/notes/single-qubit-conditions-qpy-39a5a9a7204a27dd.yaml
  test/python/circuit/test_circuit_load_from_qpy.py
  test/qpy_compat/test_qpy.py
Labels: Changelog: Bugfix, automerge, stable backport potential

#6833 Specify version for Python 3.6 support ending
  qiskit/__init__.py
Labels: Changelog: None, automerge, stable backport potential

#6818 Fix QNSPSA settings
  qiskit/algorithms/optimizers/qnspsa.py
  releasenotes/notes/fix-qnspsa-settings-91d5a9553706cc72.yaml
  test/python/algorithms/optimizers/test_optimizers.py
Labels: Changelog: Bugfix, automerge, mod: algorithms, stable backport potential

#6843 Exclude bip-mapper extra from all
  qiskit/transpiler/passes/routing/bip_mapping.py
  releasenotes/notes/fix-bip-mapper-requirements-930c7dcd5a3b82ba.yaml
  setup.py
Labels: Changelog: API Change, automerge, stable backport potential

#6776 Ensure QNSPSA allows for batching
  qiskit/algorithms/optimizers/qnspsa.py
  qiskit/algorithms/optimizers/spsa.py
  releasenotes/notes/ensure-qnspsa-batching-e48f7ec72412c071.yaml
  test/python/algorithms/test_vqe.py
Labels: Changelog: New Feature, automerge, mod: algorithms
