Repository Qiskit/qiskit, pull requests merged in 2021-08, with the labels that each got.

#6557 A minor doc fix
  qiskit/circuit/register.py
Labels: Changelog: None, automerge

#6844 Build aarch64 wheels in github actions with QEMU emulation
  .github/workflows/wheels.yml
  .travis.yml
  releasenotes/notes/fix-aarch64-e75601c0b8f2da2c.yaml
Labels: Changelog: Bugfix, automerge, stable backport potential

#6853 Fix typos in release notes for 0.18.1
  releasenotes/notes/completemeasfitter-386e94a271ba0180.yaml
  releasenotes/notes/fix-qaoa-to-qpy-6364c96671bc8f36.yaml
  releasenotes/notes/fix-qnspsa-settings-91d5a9553706cc72.yaml
  releasenotes/notes/one-gate-identity-optimization-fix-d6d1496d9f5409a6.yaml
  releasenotes/notes/single-qubit-conditions-qpy-39a5a9a7204a27dd.yaml
Labels: Changelog: None, automerge

#6854 Build aarch64 wheels in github actions with QEMU emulation (backport of #6844)
  .github/workflows/wheels.yml
  .travis.yml
  releasenotes/notes/fix-aarch64-e75601c0b8f2da2c.yaml
Labels: Changelog: Bugfix, automerge, stable-backport

#6857 Prepare 0.18.1
  docs/conf.py
  qiskit/VERSION.txt
  releasenotes/notes/completemeasfitter-386e94a271ba0180.yaml
  releasenotes/notes/fix-qaoa-to-qpy-6364c96671bc8f36.yaml
  releasenotes/notes/fix-qnspsa-settings-91d5a9553706cc72.yaml
  releasenotes/notes/one-gate-identity-optimization-fix-d6d1496d9f5409a6.yaml
  releasenotes/notes/prepare-0.18.1-becf331b951bd2f0.yaml
  releasenotes/notes/single-qubit-conditions-qpy-39a5a9a7204a27dd.yaml
  setup.py
Labels: Changelog: None, automerge

#6858 Bump reno requirement to latest version and set default_branch
  releasenotes/config.yaml
  requirements-dev.txt
Labels: Changelog: None, automerge, stable backport potential

#6778 Add gate error and balanced objective to BIP mapper
  qiskit/transpiler/passes/routing/algorithms/bip_model.py
  qiskit/transpiler/passes/routing/bip_mapping.py
  releasenotes/notes/add-gate-error-objective-00a96f75055d1526.yaml
  test/python/transpiler/test_bip_mapping.py
Labels: Changelog: New Feature, automerge

#6567 Replace DAGNode class with OpNode, InNode, and OutNode classes
  qiskit/dagcircuit/__init__.py
  qiskit/dagcircuit/dagcircuit.py
  qiskit/dagcircuit/dagnode.py
  qiskit/transpiler/passes/analysis/dag_longest_path.py
  qiskit/transpiler/passes/layout/apply_layout.py
  qiskit/transpiler/passes/optimization/collect_2q_blocks.py
  qiskit/transpiler/passes/optimization/commutation_analysis.py
  qiskit/transpiler/passes/optimization/commutative_cancellation.py
  qiskit/transpiler/passes/optimization/consolidate_blocks.py
  qiskit/transpiler/passes/optimization/crosstalk_adaptive_schedule.py
  qiskit/transpiler/passes/optimization/hoare_opt.py
  qiskit/transpiler/passes/optimization/optimize_swap_before_measure.py
  qiskit/transpiler/passes/optimization/remove_diagonal_gates_before_measure.py
  qiskit/transpiler/passes/optimization/remove_reset_in_zero_state.py
  qiskit/transpiler/passes/optimization/template_matching/forward_match.py
  qiskit/transpiler/passes/routing/bip_mapping.py
  qiskit/transpiler/passes/routing/lookahead_swap.py
  qiskit/transpiler/passes/routing/sabre_swap.py
  qiskit/transpiler/passes/scheduling/calibration_creators.py
  qiskit/transpiler/passes/scheduling/dynamical_decoupling.py
  qiskit/transpiler/passes/utils/barrier_before_final_measurements.py
  qiskit/transpiler/passes/utils/merge_adjacent_barriers.py
  qiskit/transpiler/passes/utils/remove_final_measurements.py
  qiskit/visualization/dag_visualization.py
  releasenotes/notes/dag_node_to_op_in_out_node-af2cf9c3e7686285.yaml
  test/python/compiler/test_transpiler.py
  test/python/dagcircuit/test_dagcircuit.py
  test/python/transpiler/test_consolidate_blocks.py
  test/python/transpiler/test_faulty_backend.py
  test/python/transpiler/test_hoare_opt.py
Labels: Changelog: Deprecation, Changelog: New Feature, performance

#6753 Unify setup and teardown methods of TestCases
  qiskit/test/base.py
  qiskit/test/decorators.py
  test/python/circuit/test_gate_definitions.py
Labels: Changelog: None, automerge

#6868 Tame 1Q simplification warning
  qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py
  test/python/transpiler/test_optimize_1q_decomposition.py
Labels: Changelog: None, automerge, stable backport potential

#6808 Add fake backends for new IBM Quantum systems
  qiskit/test/mock/backends/__init__.py
  qiskit/test/mock/backends/brooklyn/__init__.py
  qiskit/test/mock/backends/brooklyn/conf_brooklyn.json
  qiskit/test/mock/backends/brooklyn/defs_brooklyn.json
  qiskit/test/mock/backends/brooklyn/fake_brooklyn.py
  qiskit/test/mock/backends/brooklyn/props_brooklyn.json
  qiskit/test/mock/backends/jakarta/__init__.py
  qiskit/test/mock/backends/jakarta/conf_jakarta.json
  qiskit/test/mock/backends/jakarta/defs_jakarta.json
  qiskit/test/mock/backends/jakarta/fake_jakarta.py
  qiskit/test/mock/backends/jakarta/props_jakarta.json
  qiskit/test/mock/backends/lagos/__init__.py
  qiskit/test/mock/backends/lagos/conf_lagos.json
  qiskit/test/mock/backends/lagos/defs_lagos.json
  qiskit/test/mock/backends/lagos/fake_lagos.py
  qiskit/test/mock/backends/lagos/props_lagos.json
  qiskit/test/mock/backends/manila/__init__.py
  qiskit/test/mock/backends/manila/conf_manila.json
  qiskit/test/mock/backends/manila/defs_manila.json
  qiskit/test/mock/backends/manila/fake_manila.py
  qiskit/test/mock/backends/manila/props_manila.json
  qiskit/test/mock/fake_provider.py
  releasenotes/notes/add-new-fake-backends-3376682dc5c63557.yaml
Labels: Changelog: New Feature, automerge

#6675 Fix 'ax' and 'figwidth' options to mpl drawer
  qiskit/visualization/matplotlib.py
  qiskit/visualization/text.py
  qiskit/visualization/utils.py
  releasenotes/notes/fix-ax-figwidth-scaling-mpl-drawer-dc480ccf82dc1007.yaml
  test/ipynb/mpl/circuit/references/figwidth.png
  test/ipynb/mpl/circuit/references/global_phase.png
  test/ipynb/mpl/circuit/references/user_ax.png
  test/ipynb/mpl/circuit/references/user_style.png
  test/ipynb/mpl/circuit/test_circuit_matplotlib_drawer.py
Labels: Changelog: Bugfix, automerge

#6824 Support non-float global phase in QPY
  qiskit/circuit/qpy_serialization.py
  releasenotes/notes/qpy-v2-f1c380b40936cccf.yaml
  test/python/circuit/test_circuit_load_from_qpy.py
  test/qpy_compat/test_qpy.py
Labels: Changelog: New Feature, automerge

#6847 Change float to complex for return from ParameterExpression gradient
  qiskit/circuit/parameterexpression.py
  test/python/opflow/test_gradients.py
Labels: Changelog: Bugfix, automerge

#6487 Added support for multiple image formats in QuantumCircuit.draw()
  qiskit/visualization/__init__.py
  qiskit/visualization/circuit_visualization.py
  releasenotes/notes/added-multiformat-support-b5d3c7c7c1536951.yaml
  test/python/visualization/test_circuit_drawer.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: Changelog: New Feature, automerge

#6690 Grouping commuting Pauli strings in quantum_info
  qiskit/quantum_info/operators/symplectic/pauli_list.py
  releasenotes/notes/add-group-qubit-wise-commuting-pauli-list-7b96834068a36928.yaml
  test/python/quantum_info/operators/symplectic/test_pauli_list.py
Labels: automerge

#6823 Deprecate the CouplingMap.subgraph() method
  qiskit/transpiler/coupling.py
  releasenotes/notes/deprecate-subgraph-coupling_map-93af284f5410e4b0.yaml
  test/python/transpiler/test_coupling.py
Labels: Changelog: Deprecation, automerge

#6890 Fix mpl circuit drawing duplication in ipykernel 6
  qiskit/visualization/bloch.py
  qiskit/visualization/counts_visualization.py
  qiskit/visualization/gate_map.py
  qiskit/visualization/matplotlib.py
  qiskit/visualization/pulse_v2/plotters/matplotlib.py
  qiskit/visualization/pulse_visualization.py
  qiskit/visualization/state_visualization.py
  qiskit/visualization/timeline/plotters/matplotlib.py
  qiskit/visualization/utils.py
  releasenotes/notes/fix-duplicate-mpl-drawer-ipykernel6-c64d9178e31ab9fe.yaml
Labels: stable backport potential, Changelog: Bugfix, automerge

#6693 Respect backend defaults for BackendV1 path in execute()
  qiskit/execute_function.py
  releasenotes/notes/execute-fix-108e835dc4f4593d.yaml
Labels: Changelog: API Change, automerge

#6896 Unify and simplify some Weyl decomposition code
  qiskit/quantum_info/synthesis/two_qubit_decompose.py
  qiskit/quantum_info/synthesis/weyl.py
Labels: automerge, Changelog: None

#6831 Add type hints to gates and QuantumCircuit
  qiskit/circuit/gate.py
  qiskit/circuit/library/standard_gates/h.py
  qiskit/circuit/library/standard_gates/i.py
  qiskit/circuit/library/standard_gates/iswap.py
  qiskit/circuit/library/standard_gates/ms.py
  qiskit/circuit/library/standard_gates/multi_control_rotation_gates.py
  qiskit/circuit/library/standard_gates/p.py
  qiskit/circuit/library/standard_gates/r.py
  qiskit/circuit/library/standard_gates/rx.py
  qiskit/circuit/library/standard_gates/rxx.py
  qiskit/circuit/library/standard_gates/ry.py
  qiskit/circuit/library/standard_gates/ryy.py
  qiskit/circuit/library/standard_gates/rz.py
  qiskit/circuit/library/standard_gates/rzx.py
  qiskit/circuit/library/standard_gates/rzz.py
  qiskit/circuit/library/standard_gates/s.py
  qiskit/circuit/library/standard_gates/swap.py
  qiskit/circuit/library/standard_gates/sx.py
  qiskit/circuit/library/standard_gates/t.py
  qiskit/circuit/library/standard_gates/u.py
  qiskit/circuit/library/standard_gates/u1.py
  qiskit/circuit/library/standard_gates/u2.py
  qiskit/circuit/library/standard_gates/u3.py
  qiskit/circuit/library/standard_gates/x.py
  qiskit/circuit/library/standard_gates/y.py
  qiskit/circuit/library/standard_gates/z.py
  qiskit/circuit/measure.py
  qiskit/circuit/parameterexpression.py
  qiskit/circuit/quantumcircuit.py
  qiskit/circuit/reset.py
  releasenotes/notes/gate-type-hints-b287215190144ceb.yaml
Labels: Changelog: API Change, automerge

#6856 Fix registerless bit naming collisions in QASM
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/fix-registerless-qasm-output-7a497dd8e9a0706b.yaml
  test/python/circuit/test_circuit_qasm.py
Labels: Changelog: Bugfix, automerge

#6910 Use `repeat` in `QuantumCircuit.power` if `power` is `numpy.integer`
  qiskit/circuit/quantumcircuit.py
Labels: Changelog: None

#6751 New plot_coupling_map(), like plot_gate_map() but without a backend
  qiskit/visualization/gate_map.py
  releasenotes/notes/plot_coupling_map-new-function-deb973b1bf0ad92f.yaml
  test/python/visualization/references/8qubits.png
  test/python/visualization/test_gate_map.py
Labels: Changelog: New Feature, automerge

#6922 Correctly handle parametric pulse assemble() kwarg if empty list
  qiskit/compiler/assembler.py
  releasenotes/notes/fix-assemble-parametric-pulse-eea8fba73c56a69f.yaml
  test/python/compiler/test_assembler.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#6885 Detach prefix util function
  qiskit/utils/__init__.py
  qiskit/utils/units.py
  releasenotes/notes/add-detach-prefix-088e96b88ba29927.yaml
  test/python/utils/__init__.py
  test/python/utils/test_units.py
Labels: Changelog: New Feature, automerge

#6886 Improve CXCancellation pass readability
  qiskit/transpiler/passes/optimization/cx_cancellation.py
  test/python/transpiler/test_cx_cancellation.py
Labels: automerge, Changelog: None

#6716 Fix typo in old-style Bit property error message
  qiskit/circuit/bit.py
Labels: type: documentation, stable backport potential, automerge, Changelog: None

#6800 Allow QuantumCircuit construction with zero qubit or clbit count
  qiskit/circuit/quantumcircuit.py
  qiskit/circuit/register.py
  test/python/circuit/test_circuit_registers.py
  test/python/circuit/test_register.py
Labels: Changelog: API Change, automerge

#6926 Fix issue#6902
  qiskit/compiler/assembler.py
Labels: automerge

#6957 Remove stray test file accidently commited
  test_iqx.tex
Labels: automerge, Changelog: None

#6826 Switch PauliTable to PauliList in SparsePauliOp
  qiskit/opflow/converters/pauli_basis_change.py
  qiskit/opflow/primitive_ops/pauli_sum_op.py
  qiskit/quantum_info/operators/symplectic/pauli.py
  qiskit/quantum_info/operators/symplectic/pauli_list.py
  qiskit/quantum_info/operators/symplectic/pauli_utils.py
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
  qiskit/test/base.py
  qiskit/visualization/utils.py
  releasenotes/notes/sparse-pauli-internal-8226b4f57a61b982.yaml
  test/python/opflow/test_pauli_sum_op.py
  test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
Labels: Changelog: Deprecation, automerge, mod: quantum info

#6951 Improve the readability of depth() method
  qiskit/circuit/quantumcircuit.py
Labels: stable backport potential, automerge, Changelog: None
