Repository Qiskit/qiskit, pull requests merged in 2021-02, with the labels that each got.

#5761 Clarify the CONTRIBUTING.md section on stream capture
  CONTRIBUTING.md
Labels: automerge

#5767 Disable pylint rule causing failure with fastjsonschema 2.15.0
  qiskit/qobj/utils.py
Labels: automerge

#5503 Easier way to call a pass on a circuit
  qiskit/transpiler/basepasses.py
  releasenotes/notes/calling_a_pass-4148f285ea717c74.yaml
  test/python/transpiler/_dummy_passes.py
  test/python/transpiler/test_pass_call.py
Labels: Changelog: New Feature, automerge

#5681 ScheduleBlock 1/4 - remove timeslot dependency from instruction
  qiskit/pulse/exceptions.py
  qiskit/pulse/instructions/acquire.py
  qiskit/pulse/instructions/delay.py
  qiskit/pulse/instructions/directives.py
  qiskit/pulse/instructions/frequency.py
  qiskit/pulse/instructions/instruction.py
  qiskit/pulse/instructions/phase.py
  qiskit/pulse/instructions/play.py
  qiskit/pulse/instructions/snapshot.py
  qiskit/pulse/library/parametric_pulses.py
  qiskit/pulse/library/pulse.py
  qiskit/pulse/schedule.py
  qiskit/pulse/utils.py
  releasenotes/notes/allow-parametric-instruction-duration-b4c6677544ed28c1.yaml
  test/python/pulse/test_parameters.py
Labels: automerge

#5749 Fix incorrect qargs setting in sabre_swap
  qiskit/transpiler/passes/routing/lookahead_swap.py
  qiskit/transpiler/passes/routing/sabre_swap.py
Labels: automerge

#5662 Fix handling of classical bits in timeline drawer and non-treament of delay as idle time
  qiskit/circuit/quantumcircuit.py
  qiskit/visualization/circuit_visualization.py
  qiskit/visualization/timeline/core.py
  qiskit/visualization/timeline/interface.py
  qiskit/visualization/timeline/plotters/matplotlib.py
  qiskit/visualization/timeline/stylesheet.py
  qiskit/visualization/utils.py
  releasenotes/notes/idle-time-visualization-b5404ad875cbdae4.yaml
  test/python/visualization/test_circuit_text_drawer.py
  test/python/visualization/timeline/test_core.py
Labels: Changelog: Bugfix, automerge

#5762 Add handling for no stdout encoding to text drawer
  qiskit/visualization/text.py
Labels: automerge

#5620 Add a lazy loading wrapper class for __qiskit_version__
  docs/apidocs/execute.rst
  qiskit/__init__.py
  qiskit/compiler/__init__.py
  qiskit/compiler/assembler.py
  qiskit/compiler/scheduler.py
  qiskit/compiler/sequencer.py
  qiskit/compiler/transpiler.py
  qiskit/execute_function.py
  qiskit/version.py
  releasenotes/notes/qiskit-version-wrapper-90cb7fcffeaafd6a.yaml
  test/python/circuit/test_parameters.py
  test/python/compiler/test_assembler.py
  test/python/compiler/test_disassembler.py
  test/python/providers/test_fake_backends.py
  test/python/quantum_info/test_local_invariance.py
  test/python/test_version.py
Labels: Changelog: API Change, automerge, performance

#5769 Clifford templates
  qiskit/circuit/library/templates/__init__.py
  qiskit/circuit/library/templates/clifford/__init__.py
  qiskit/circuit/library/templates/clifford/clifford_2_1.py
  qiskit/circuit/library/templates/clifford/clifford_2_2.py
  qiskit/circuit/library/templates/clifford/clifford_2_3.py
  qiskit/circuit/library/templates/clifford/clifford_2_4.py
  qiskit/circuit/library/templates/clifford/clifford_3_1.py
  qiskit/circuit/library/templates/clifford/clifford_4_1.py
  qiskit/circuit/library/templates/clifford/clifford_4_2.py
  qiskit/circuit/library/templates/clifford/clifford_4_3.py
  qiskit/circuit/library/templates/clifford/clifford_4_4.py
  qiskit/circuit/library/templates/clifford/clifford_5_1.py
  qiskit/circuit/library/templates/clifford/clifford_6_1.py
  qiskit/circuit/library/templates/clifford/clifford_6_2.py
  qiskit/circuit/library/templates/clifford/clifford_6_3.py
  qiskit/circuit/library/templates/clifford/clifford_6_4.py
  qiskit/circuit/library/templates/clifford/clifford_6_5.py
  qiskit/circuit/library/templates/clifford/clifford_8_1.py
  qiskit/circuit/library/templates/clifford/clifford_8_2.py
  qiskit/circuit/library/templates/clifford/clifford_8_3.py
  test/python/circuit/test_templates.py
Labels: automerge

#5778 Fix incorrect durations in scheduled circuit
  qiskit/transpiler/passes/scheduling/alap.py
  qiskit/transpiler/passes/scheduling/asap.py
  test/python/circuit/test_scheduled_circuit.py
Labels: automerge

#5648 Add proper error checking for bind/assign parameters in QuantumCircuit
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_parameters.py
Labels: automerge

#5755 Pulse Schedules: allow mixed schedule time types
  qiskit/pulse/schedule.py
  test/python/pulse/test_schedule.py
Labels: automerge

#5764 Global phase in TwoQubitBasisDecomposer
  qiskit/quantum_info/synthesis/two_qubit_decompose.py
  test/python/quantum_info/test_synthesis.py
Labels: Changelog: Bugfix, automerge, global-phase

#5777 Remove deprecated methods/parameters from algorithms and opflow
  qiskit/algorithms/optimizers/aqgd.py
  qiskit/algorithms/optimizers/gsls.py
  qiskit/algorithms/optimizers/spsa.py
  qiskit/opflow/gradients/circuit_gradients/lin_comb.py
  qiskit/opflow/gradients/circuit_qfis/lin_comb_full.py
Labels: automerge, mod: algorithms, mod: opflow, type: enhancement

#5485 Move matplotlib imports to runtime
  qiskit/visualization/counts_visualization.py
  qiskit/visualization/gate_map.py
  qiskit/visualization/matplotlib.py
  qiskit/visualization/pulse/matplotlib.py
  qiskit/visualization/pulse_visualization.py
  qiskit/visualization/state_visualization.py
Labels: performance

#5582 Add script to verify slow optional imports aren't used in default path
  Makefile
  azure-pipelines.yml
  tools/find_optional_imports.py
  tox.ini
Labels: automerge

#5788 Fix compatibility with numpy 1.20.0
  qiskit/circuit/register.py
  qiskit/qobj/utils.py
  qiskit/quantum_info/operators/pauli.py
  qiskit/quantum_info/operators/symplectic/clifford.py
  qiskit/quantum_info/operators/symplectic/pauli_table.py
  qiskit/quantum_info/operators/symplectic/pauli_utils.py
  qiskit/quantum_info/operators/symplectic/random.py
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
  qiskit/quantum_info/operators/symplectic/stabilizer_table.py
  qiskit/visualization/pulse_v2/generators/waveform.py
  qiskit/visualization/utils.py
  test/python/circuit/test_circuit_registers.py
  test/python/pulse/test_samplers.py
  test/python/quantum_info/operators/symplectic/test_clifford.py
  test/python/quantum_info/operators/symplectic/test_pauli_table.py
  test/python/quantum_info/operators/symplectic/test_stabilizer_table.py
  test/python/quantum_info/test_pauli.py
Labels: Changelog: Bugfix, automerge, stable-backport

#5619 Wrap qiskit.Aer and qiskit.IBMQ with lazy loading object
  azure-pipelines.yml
  qiskit/__init__.py
  qiskit/test/mock/fake_backend.py
  qiskit/user_config.py
  releasenotes/notes/lazy-load-provider-factory-bdfb3925a2514ef7.yaml
  test/python/algorithms/test_vqe.py
  test/python/opflow/test_state_op_meas_evals.py
  test/python/test_user_config.py
Labels: Changelog: API Change, Changelog: Removal, automerge, performance

#5798 Update slow optional import list to include additional packages
  tools/find_optional_imports.py
Labels: automerge

#5790 Fix PauliTwoDesign.assign_parameters
  qiskit/circuit/library/n_local/n_local.py
  qiskit/circuit/library/n_local/pauli_two_design.py
  test/python/circuit/library/test_random_pauli.py
Labels: automerge

#5801 Prepare 0.16.4 release
  docs/conf.py
  qiskit/VERSION.txt
  releasenotes/notes/prepare-0.16.4-721822aa11ee7d60.yaml
  setup.py
Labels: automerge

#5617 quantum_info.operator mixin interface refactor
  qiskit/quantum_info/operators/base_operator.py
  qiskit/quantum_info/operators/channel/chi.py
  qiskit/quantum_info/operators/channel/choi.py
  qiskit/quantum_info/operators/channel/kraus.py
  qiskit/quantum_info/operators/channel/ptm.py
  qiskit/quantum_info/operators/channel/quantum_channel.py
  qiskit/quantum_info/operators/channel/stinespring.py
  qiskit/quantum_info/operators/channel/superop.py
  qiskit/quantum_info/operators/channel/transformations.py
  qiskit/quantum_info/operators/linear_op.py
  qiskit/quantum_info/operators/mixins/__init__.py
  qiskit/quantum_info/operators/mixins/adjoint.py
  qiskit/quantum_info/operators/mixins/group.py
  qiskit/quantum_info/operators/mixins/linear.py
  qiskit/quantum_info/operators/mixins/multiply.py
  qiskit/quantum_info/operators/mixins/tolerances.py
  qiskit/quantum_info/operators/operator.py
  qiskit/quantum_info/operators/scalar_op.py
  qiskit/quantum_info/operators/symplectic/base_pauli.py
  qiskit/quantum_info/operators/symplectic/clifford.py
  qiskit/quantum_info/operators/symplectic/pauli.py
  qiskit/quantum_info/operators/symplectic/pauli_table.py
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
  qiskit/quantum_info/operators/symplectic/stabilizer_table.py
  qiskit/quantum_info/states/densitymatrix.py
  qiskit/quantum_info/states/statevector.py
  releasenotes/notes/base-operator-api-8465ba5ad8856d9f.yaml
  test/python/quantum_info/operators/channel/test_chi.py
  test/python/quantum_info/operators/channel/test_choi.py
  test/python/quantum_info/operators/channel/test_kraus.py
  test/python/quantum_info/operators/channel/test_ptm.py
  test/python/quantum_info/operators/channel/test_stinespring.py
  test/python/quantum_info/operators/channel/test_superop.py
  test/python/quantum_info/operators/symplectic/test_pauli.py
  test/python/quantum_info/operators/symplectic/test_pauli_table.py
  test/python/quantum_info/operators/symplectic/test_stabilizer_table.py
  test/python/quantum_info/operators/test_operator.py
Labels: Changelog: API Change

#5816 Attempt to install latest numpy in all CI jobs
  azure-pipelines.yml
  constraints.txt
  qiskit/opflow/converters/abelian_grouper.py
Labels: automerge

#5805 Move pycodestyle max-line-length to tox.ini
  Makefile
  azure-pipelines.yml
  tox.ini
Labels: automerge, type: qa

#5680 Refactor Grover: Algo and problem separation
  qiskit/algorithms/__init__.py
  qiskit/algorithms/amplitude_amplifiers/__init__.py
  qiskit/algorithms/amplitude_amplifiers/amplification_problem.py
  qiskit/algorithms/amplitude_amplifiers/amplitude_amplifier.py
  qiskit/algorithms/amplitude_amplifiers/grover.py
  test/python/algorithms/test_grover.py
Labels: automerge, mod: algorithms

#5678 Updated QAOA implementation
  qiskit/algorithms/minimum_eigen_solvers/qaoa.py
  qiskit/algorithms/minimum_eigen_solvers/qaoa/__init__.py
  qiskit/algorithms/minimum_eigen_solvers/qaoa/var_form.py
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/blueprintcircuit.py
  qiskit/circuit/library/n_local/__init__.py
  qiskit/circuit/library/n_local/qaoa_ansatz.py
  test/python/algorithms/test_qaoa.py
  test/python/circuit/library/test_qaoa_ansatz.py
Labels: automerge, mod: algorithms

#5807 Fix parameter handling in global phase
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/bind-global-phase-a7248943488f4010.yaml
  test/python/circuit/test_circuit_operations.py
  test/python/opflow/test_evolution.py
Labels: Changelog: Bugfix, automerge

#5490 Fix marginal_counts incorrect creg_sizes with Result object and add format_marginal kwarg
  qiskit/result/counts.py
  qiskit/result/utils.py
  releasenotes/notes/marginal_counts_format-dc20b15d6c04ec94.yaml
  test/python/result/test_result.py
Labels: automerge

#5360 Fixed inconsistency in gate names between text and matplotlib backends
  qiskit/visualization/matplotlib.py
  test/ipynb/mpl/references/big_gates.png
  test/ipynb/mpl/references/ctrl_labels.png
  test/ipynb/mpl/references/ghz_to_gate.png
  test/ipynb/mpl/test_circuit_matplotlib_drawer.py
Labels: automerge

#5822 Set up loggers using consistent syntax
  qiskit/compiler/assembler.py
  qiskit/compiler/scheduler.py
  qiskit/compiler/transpiler.py
  qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py
  qiskit/transpiler/passes/routing/stochastic_swap.py
Labels: automerge

#5823 Remove useless loggers
  qiskit/algorithms/amplitude_estimators/mlae.py
  qiskit/algorithms/minimum_eigen_solvers/qaoa.py
  qiskit/algorithms/optimizers/adam_amsgrad.py
  qiskit/algorithms/optimizers/bobyqa.py
  qiskit/algorithms/optimizers/cg.py
  qiskit/algorithms/optimizers/cobyla.py
  qiskit/algorithms/optimizers/gsls.py
  qiskit/algorithms/optimizers/imfil.py
  qiskit/algorithms/optimizers/l_bfgs_b.py
  qiskit/algorithms/optimizers/nelder_mead.py
  qiskit/algorithms/optimizers/nft.py
  qiskit/algorithms/optimizers/powell.py
  qiskit/algorithms/optimizers/slsqp.py
  qiskit/algorithms/optimizers/snobfit.py
  qiskit/algorithms/optimizers/tnc.py
  qiskit/circuit/library/n_local/n_local.py
  qiskit/circuit/library/standard_gates/multi_control_rotation_gates.py
  qiskit/opflow/converters/converter_base.py
  qiskit/opflow/converters/dict_to_circuit_sum.py
  qiskit/opflow/converters/pauli_basis_change.py
  qiskit/opflow/evolutions/evolution_base.py
  qiskit/opflow/evolutions/evolution_factory.py
  qiskit/opflow/evolutions/evolved_op.py
  qiskit/opflow/evolutions/trotterizations/trotterization_base.py
  qiskit/opflow/evolutions/trotterizations/trotterization_factory.py
  qiskit/opflow/expectations/cvar_expectation.py
  qiskit/opflow/expectations/expectation_base.py
  qiskit/opflow/expectations/expectation_factory.py
  qiskit/opflow/expectations/matrix_expectation.py
  qiskit/opflow/gradients/circuit_gradients/circuit_gradient.py
  qiskit/opflow/gradients/derivative_base.py
  qiskit/opflow/primitive_ops/circuit_op.py
  qiskit/opflow/primitive_ops/matrix_op.py
  qiskit/opflow/primitive_ops/pauli_op.py
  qiskit/opflow/primitive_ops/pauli_sum_op.py
  qiskit/opflow/primitive_ops/primitive_op.py
  qiskit/utils/measurement_error_mitigation.py
  qiskit/validation/jsonschema/schema_validation.py
  qiskit/visualization/matplotlib.py
  test/python/quantum_info/operators/symplectic/test_pauli.py
  test/python/quantum_info/states/test_utils.py
Labels: automerge

#5818 Fix adjoint in PauliSumOp
  qiskit/opflow/primitive_ops/pauli_sum_op.py
  test/python/opflow/test_pauli_sum_op.py
Labels: automerge, mod: opflow

#5772 Allow passmanager.append(flowcontroller) instead of passes
  qiskit/transpiler/passmanager.py
  qiskit/transpiler/runningpassmanager.py
  test/python/transpiler/test_pass_scheduler.py
Labels: Changelog: New Feature, automerge

#5833 OptimizeSwapBeforeMeasure in one run
  qiskit/transpiler/passes/optimization/optimize_swap_before_measure.py
  test/python/transpiler/test_optimize_swap_before_measure.py
Labels: automerge

#5486 API changes for optional registers in QuantumCircuit.
  qiskit/circuit/bit.py
  qiskit/circuit/classicalregister.py
  qiskit/circuit/quantumcircuit.py
  qiskit/circuit/quantumregister.py
  qiskit/circuit/register.py
  qiskit/dagcircuit/dagcircuit.py
  releasenotes/notes/bit-classes-register-index-optional-9aa6feff4fce3524.yaml
  test/python/circuit/test_bit.py
  test/python/circuit/test_register.py
  test/python/circuit/test_registerless_circuit.py
  test/python/dagcircuit/test_dagcircuit.py
Labels: automerge, optional-registers

#5847 Ensure uniqueness of nodes in neighbors()
  qiskit/transpiler/passes/layout/noise_adaptive_layout.py
Labels: automerge

#5849 Remove stray np.int usage
  qiskit/quantum_info/operators/symplectic/clifford.py
Labels: automerge

#5768 Fix an isintanceof statement to allow all numpy integers
  qiskit/circuit/register.py
  qiskit/quantum_info/operators/symplectic/pauli.py
  qiskit/quantum_info/operators/symplectic/pauli_table.py
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
  qiskit/quantum_info/operators/symplectic/stabilizer_table.py
Labels: automerge

#5848 Fix the endian bug in PauliSumOp
  qiskit/opflow/primitive_ops/pauli_sum_op.py
  test/python/algorithms/test_qaoa.py
  test/python/algorithms/test_vqe.py
  test/python/opflow/test_pauli_sum_op.py
Labels: mod: opflow

#5861 Fix seed in QAOA test
  test/python/algorithms/test_qaoa.py
Labels: automerge, mod: algorithms

#5860 Suppress stdout from TestJobMonitor
  test/python/tools/monitor/test_job_monitor.py
Labels: automerge

#5867 Make Register and Bit hashed attrs immutable
  qiskit/circuit/bit.py
  qiskit/circuit/register.py
  releasenotes/notes/bit-register-immutable-7a06a212400b3b60.yaml
  test/python/circuit/test_bit.py
  test/python/circuit/test_circuit_registers.py
Labels: Changelog: API Change, automerge

#5537 Add TwoQubitReduction and TaperedPauliSumOp (PauliSumOp 2/3)
  qiskit/opflow/__init__.py
  qiskit/opflow/converters/__init__.py
  qiskit/opflow/converters/two_qubit_reduction.py
  qiskit/opflow/primitive_ops/__init__.py
  qiskit/opflow/primitive_ops/pauli_op.py
  qiskit/opflow/primitive_ops/pauli_sum_op.py
  qiskit/opflow/primitive_ops/tapered_pauli_sum_op.py
  qiskit/opflow/utils.py
  test/python/opflow/test_abelian_grouper.py
  test/python/opflow/test_two_qubit_reduction.py
  test/python/opflow/test_z2_symmetries.py
Labels: automerge, mod: opflow

#5864 Fix more bugs in OverlapQFI on multi-parameter gates
  qiskit/opflow/gradients/circuit_qfis/overlap_diag.py
  test/python/opflow/test_gradients.py
Labels: automerge, mod: opflow

#4546 Add visualization methods to state classes
  qiskit/quantum_info/states/densitymatrix.py
  qiskit/quantum_info/states/measures.py
  qiskit/quantum_info/states/statevector.py
  qiskit/user_config.py
  qiskit/visualization/__init__.py
  qiskit/visualization/array.py
  qiskit/visualization/latex.py
  qiskit/visualization/state_visualization.py
  qiskit/visualization/utils.py
  releasenotes/notes/add_array_to_latex-0b5f655a47f132c0.yaml
  releasenotes/notes/add_state_ipython-6fd6305f3db04a23.yaml
  test/python/quantum_info/states/test_densitymatrix.py
  test/python/quantum_info/states/test_statevector.py
  test/python/visualization/test_utils.py
Labels: automerge

#5843 Add linux arm64 release wheel jobs
  .travis.yml
Labels: automerge

#5869 Remove np.bool and np.int in the unit tests
  test/python/algorithms/test_qaoa.py
  test/python/circuit/test_circuit_registers.py
Labels: automerge, mod: algorithms

#5701 Add `Instruction._directive` attribute support to transpiler, unroller, drawer
  qiskit/circuit/add_control.py
  qiskit/circuit/barrier.py
  qiskit/circuit/instruction.py
  qiskit/circuit/quantumcircuit.py
  qiskit/dagcircuit/dagcircuit.py
  qiskit/dagcircuit/dagdependency.py
  qiskit/extensions/simulator/snapshot.py
  qiskit/transpiler/passes/basis/unroll_custom_definitions.py
  qiskit/transpiler/passes/basis/unroller.py
  qiskit/transpiler/passes/optimization/commutation_analysis.py
  qiskit/visualization/dag_visualization.py
  qiskit/visualization/latex.py
  qiskit/visualization/matplotlib.py
  qiskit/visualization/text.py
  test/python/circuit/test_circuit_properties.py
  test/python/transpiler/test_unroller.py
Labels: automerge

#5882 Add missing snapshot from unroller custom def
  qiskit/dagcircuit/dagdependency.py
  qiskit/transpiler/passes/basis/unroll_custom_definitions.py
  qiskit/transpiler/passes/basis/unroller.py
Labels: automerge

#5554 Add simplify of U3->U1/U2 in OneQubitEulerDecomposer
  qiskit/quantum_info/synthesis/one_qubit_decompose.py
  qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  releasenotes/notes/1q_euler_decomp_u3_to_u1_u2-ca3bea2ca55ca961.yaml
  test/python/compiler/test_transpiler.py
  test/python/quantum_info/test_synthesis.py
  test/python/transpiler/test_optimize_1q_decomposition.py
Labels: Changelog: New Feature

#5688 fix qasm output with open controlled gates
  qiskit/circuit/controlledgate.py
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/fix_qasm_open_control_gates-7ec026cb0f7be642.yaml
  test/python/circuit/test_circuit_qasm.py
Labels: Changelog: Bugfix, automerge

#5876 Drop local import-outside-toplevel suppressions
  qiskit/algorithms/minimum_eigen_solvers/vqe.py
  qiskit/opflow/evolutions/evolved_op.py
  qiskit/opflow/expectations/aer_pauli_expectation.py
  qiskit/opflow/expectations/expectation_factory.py
  qiskit/opflow/list_ops/composed_op.py
  qiskit/opflow/list_ops/list_op.py
  qiskit/opflow/list_ops/summed_op.py
  qiskit/opflow/list_ops/tensored_op.py
  qiskit/opflow/operator_base.py
  qiskit/opflow/primitive_ops/circuit_op.py
  qiskit/opflow/primitive_ops/matrix_op.py
  qiskit/opflow/primitive_ops/pauli_op.py
  qiskit/opflow/primitive_ops/pauli_sum_op.py
  qiskit/opflow/primitive_ops/primitive_op.py
  qiskit/opflow/state_fns/circuit_state_fn.py
  qiskit/opflow/state_fns/cvar_measurement.py
  qiskit/opflow/state_fns/dict_state_fn.py
  qiskit/opflow/state_fns/operator_state_fn.py
  qiskit/opflow/state_fns/state_fn.py
  qiskit/opflow/state_fns/vector_state_fn.py
  qiskit/quantum_info/operators/operator.py
  qiskit/utils/backend_utils.py
  qiskit/utils/quantum_instance.py
  test/python/algorithms/test_measure_error_mitigation.py
  test/python/algorithms/test_skip_qobj_validation.py
  test/python/algorithms/test_vqe.py
  test/python/opflow/test_state_op_meas_evals.py
  test/python/quantum_info/operators/test_measures.py
Labels: automerge

#5863 Fix coefficient multiplication in ListOp evaluation
  qiskit/opflow/list_ops/list_op.py
  qiskit/opflow/state_fns/operator_state_fn.py
  test/python/opflow/test_state_op_meas_evals.py
Labels: automerge, mod: opflow

#5859 Pylint disabled import-errors
  qiskit/algorithms/minimum_eigen_solvers/qaoa.py
  qiskit/quantum_info/operators/mixins/adjoint.py
  qiskit/quantum_info/operators/mixins/group.py
  qiskit/quantum_info/operators/symplectic/base_pauli.py
  qiskit/quantum_info/operators/symplectic/clifford.py
  qiskit/quantum_info/operators/symplectic/pauli.py
  qiskit/quantum_info/operators/symplectic/pauli_table.py
  qiskit/tools/jupyter/__init__.py
  qiskit/tools/jupyter/backend_monitor.py
  qiskit/tools/jupyter/backend_overview.py
  qiskit/tools/jupyter/copyright.py
  qiskit/tools/jupyter/job_watcher.py
  qiskit/tools/jupyter/jupyter_magics.py
  qiskit/tools/jupyter/monospace.py
  qiskit/tools/jupyter/progressbar.py
  qiskit/tools/jupyter/version_table.py
  qiskit/tools/monitor/overview.py
  qiskit/transpiler/passes/layout/csp_layout.py
  qiskit/visualization/bloch.py
  qiskit/visualization/counts_visualization.py
  qiskit/visualization/gate_map.py
  qiskit/visualization/state_visualization.py
  test/python/opflow/test_state_op_meas_evals.py
  test/python/test_examples.py
Labels: type: qa

#5892 Move array_to_latex from latex.py to array.py
  qiskit/visualization/__init__.py
  qiskit/visualization/array.py
  qiskit/visualization/latex.py
Labels: automerge

#5828 Add the "processor_type" field to he QasmBackendConfiguration
  qiskit/providers/models/backendconfiguration.py
  qiskit/test/mock/fake_openpulse_2q.py
  releasenotes/notes/add-config-processor-type-field-916f98f2eebf7e72.yaml
  test/python/providers/test_backendconfiguration.py
Labels: automerge

#5804 Display CPhaseGate as symmetric in all circuit drawers
  qiskit/visualization/latex.py
  qiskit/visualization/matplotlib.py
  qiskit/visualization/text.py
  test/ipynb/mpl/references/cswap_rzz.png
  test/ipynb/mpl/references/iqx_color.png
  test/ipynb/mpl/references/r_gates.png
  test/ipynb/mpl/references/u_gates.png
  test/ipynb/mpl/references/user_style.png
  test/ipynb/mpl/test_circuit_matplotlib_drawer.py
  test/python/visualization/references/circuit_text_ref_cp437.txt
  test/python/visualization/references/circuit_text_ref_utf8.txt
  test/python/visualization/test_circuit_text_drawer.py
Labels: automerge

#5884 Fix circular entanglement edge case in ``NLocal``
  qiskit/circuit/library/n_local/n_local.py
  releasenotes/notes/fix-nlocal-circular-entanglement-0acf0195138b6aa2.yaml
  test/python/circuit/library/test_nlocal.py
Labels: automerge

#5498 QuantumCircuit and DAGCircuit updates for optional registers.
  qiskit/circuit/add_control.py
  qiskit/circuit/library/arithmetic/integer_comparator.py
  qiskit/circuit/library/arithmetic/piecewise_chebyshev.py
  qiskit/circuit/library/arithmetic/piecewise_linear_pauli_rotations.py
  qiskit/circuit/library/arithmetic/piecewise_polynomial_pauli_rotations.py
  qiskit/circuit/library/arithmetic/polynomial_pauli_rotations.py
  qiskit/circuit/library/arithmetic/weighted_adder.py
  qiskit/circuit/library/blueprintcircuit.py
  qiskit/circuit/library/n_local/qaoa_ansatz.py
  qiskit/circuit/quantumcircuit.py
  qiskit/dagcircuit/dagcircuit.py
  qiskit/dagcircuit/dagdependency.py
  qiskit/dagcircuit/dagnode.py
  qiskit/transpiler/passes/optimization/commutation_analysis.py
  qiskit/transpiler/passes/optimization/commutative_cancellation.py
  qiskit/visualization/dag_visualization.py
  releasenotes/notes/DAGNode.semantic_eq-to-use-qcarg-circuit-index-for-arg-equality-07cb556ec9fda5f2.yaml
  releasenotes/notes/remove-name-attribute-from-dagcircuit-wires-b54cd6abfce95da4.yaml
  test/python/circuit/test_circuit_properties.py
  test/python/circuit/test_circuit_registers.py
  test/python/circuit/test_registerless_circuit.py
  test/python/dagcircuit/test_dagcircuit.py
  test/python/transpiler/test_commutation_analysis.py
Labels: automerge, optional-registers

#5781 ScheduleBlock 2/4 - add Call instruction
  qiskit/assembler/assemble_schedules.py
  qiskit/pulse/__init__.py
  qiskit/pulse/builder.py
  qiskit/pulse/instructions/__init__.py
  qiskit/pulse/instructions/call.py
  qiskit/pulse/instructions/directives.py
  qiskit/pulse/instructions/instruction.py
  qiskit/pulse/instructions/play.py
  qiskit/pulse/library/parametric_pulses.py
  qiskit/pulse/library/pulse.py
  qiskit/pulse/library/waveform.py
  qiskit/pulse/schedule.py
  qiskit/pulse/transforms.py
  qiskit/visualization/pulse/matplotlib.py
  qiskit/visualization/pulse_v2/core.py
  releasenotes/notes/add-call-instruction-6f4fc37994090c2f.yaml
  test/python/pulse/test_builder.py
  test/python/pulse/test_instructions.py
  test/python/pulse/test_parameters.py
  test/python/pulse/test_transforms.py
Labels: automerge

#5903 Fix quotes in displaycolor documentation
  qiskit/visualization/qcstyle.py
Labels: automerge

#5909 Avoid Operator construction overhead in Optimize 1q decomposition pass
  qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py
Labels: performance

#5504 Converters, quantum_info, assembler, scheduler and circuit library updates for optional registers.
  qiskit/assembler/assemble_circuits.py
  qiskit/converters/circuit_to_gate.py
  qiskit/converters/circuit_to_instruction.py
  qiskit/quantum_info/operators/channel/superop.py
  qiskit/quantum_info/operators/operator.py
  qiskit/quantum_info/operators/symplectic/clifford_circuits.py
  qiskit/quantum_info/states/densitymatrix.py
  qiskit/scheduler/lowering.py
  qiskit/transpiler/instruction_durations.py
  qiskit/transpiler/passes/scheduling/alap.py
  qiskit/transpiler/passes/scheduling/asap.py
  releasenotes/notes/deprecate-instructionduration-get-with-qubit-instance-64a9a428bb3bdbbd.yaml
  test/python/circuit/library/test_grover_operator.py
  test/python/circuit/test_hamiltonian_gate.py
  test/python/circuit/test_unitary.py
Labels: automerge, optional-registers

#5925 fix global phase in Instruction.inverse
  qiskit/circuit/instruction.py
  releasenotes/notes/fix-global-phase-in-instruction-inverse-2306e4539ffb0bee.yaml
  test/python/circuit/test_instructions.py
Labels: stable backport potential
