Repository Qiskit/qiskit, pull requests merged in 2021-05, with the labels that each got.

#6335 Deprecate DerivativeBase.parameter_expression_grad
  qiskit/opflow/gradients/circuit_gradients/param_shift.py
  qiskit/opflow/gradients/circuit_qfis/overlap_block_diag.py
  qiskit/opflow/gradients/circuit_qfis/overlap_diag.py
  qiskit/opflow/gradients/derivative_base.py
  qiskit/opflow/gradients/gradient.py
  qiskit/opflow/gradients/hessian.py
Labels: automerge, mod: opflow

#6318 Fix #6307 (PauliExpectation takes unnecessary adjoint when it converts operators)
  qiskit/opflow/converters/pauli_basis_change.py
  releasenotes/notes/fix-expectation-for-non-hermitian-op-880a3b9b13320574.yaml
  test/python/opflow/test_aer_pauli_expectation.py
  test/python/opflow/test_gradients.py
  test/python/opflow/test_matrix_expectation.py
  test/python/opflow/test_pauli_expectation.py
Labels: automerge, mod: opflow

#6299 Add support on QuantumInstance/run_circuits for Backends that don't handle QasmQobj
  qiskit/utils/backend_utils.py
  qiskit/utils/measurement_error_mitigation.py
  qiskit/utils/quantum_instance.py
  qiskit/utils/run_circuits.py
  test/python/algorithms/test_backendv1.py
Labels: Changelog: Bugfix, automerge, stable backport potential

#6340 plot_histogram does not raise for neg values
  qiskit/visualization/counts_visualization.py
Labels: Changelog: Bugfix, NTC, automerge, stable backport potential

#6322 Fix schedule inline transform
  qiskit/pulse/schedule.py
  qiskit/pulse/transforms/alignments.py
  qiskit/pulse/transforms/canonicalization.py
  releasenotes/notes/fix-inline-bug-6b9461fa213b0aae.yaml
  test/python/pulse/test_parameter_manager.py
  test/python/pulse/test_schedule.py
  test/python/pulse/test_transforms.py
Labels: automerge

#6292 Fix behavior of instmap.add when partial function is specified
  qiskit/pulse/instruction_schedule_map.py
  releasenotes/notes/fix-instmap-add-partial-bind-604b74158e5a56e3.yaml
  test/python/pulse/test_instruction_schedule_map.py
Labels: automerge

#6315 Support multiplication of TaperedPauliSumOp with ParameterExpression
  qiskit/opflow/primitive_ops/pauli_sum_op.py
  qiskit/opflow/primitive_ops/tapered_pauli_sum_op.py
  releasenotes/notes/fix-tapered-pauli-with-params-6df0fcfe4197feac.yaml
  test/python/opflow/test_tapered_pauli.py
Labels: Changelog: Bugfix, automerge, mod: opflow, stable backport potential

#6350 BasisTranslator skips translating gates already in target basis
  qiskit/transpiler/passes/basis/basis_translator.py
  releasenotes/notes/bugfix-skip-target-basis-translation-12a9fa02c9ceef25.yaml
Labels: Changelog: Bugfix, automerge, stable backport potential

#6360 Remove SymPy usage from Opflow's DerivativeBase
  qiskit/opflow/gradients/derivative_base.py
Labels: automerge, mod: opflow

#6362 Add git blame ignore file
  .git-blame-ignore-revs
  CONTRIBUTING.md
Labels: automerge

#6270 Use symengine for parameter and parameter expressions
  qiskit/circuit/delay.py
  qiskit/circuit/gate.py
  qiskit/circuit/parameter.py
  qiskit/circuit/parameterexpression.py
  qiskit/circuit/parametervector.py
  qiskit/circuit/tools/pi_check.py
  releasenotes/notes/symengine-2fa0479fa7d9aa80.yaml
  requirements.txt
  test/python/circuit/test_parameters.py
  test/python/opflow/test_aer_pauli_expectation.py
  test/python/opflow/test_gradients.py
  test/python/pulse/test_parameters.py
Labels: Changelog: API Change, automerge, performance

#6298 fix optimal num iterations
  qiskit/algorithms/amplitude_amplifiers/grover.py
  test/python/algorithms/test_grover.py
Labels: automerge, mod: algorithms

#5836 fixed issue 5829 by updating visualization/state_visualization.py
  qiskit/visualization/state_visualization.py
Labels: good first issue

#6359 Keep schedule attributes during transformation
  qiskit/pulse/filters.py
  qiskit/pulse/schedule.py
  qiskit/pulse/transforms/alignments.py
  qiskit/pulse/transforms/canonicalization.py
  qiskit/scheduler/methods/basic.py
  releasenotes/notes/add-initialize-from-method-to-schedules-ce86083b5bd39e6b.yaml
  test/python/pulse/test_block.py
  test/python/pulse/test_schedule.py
Labels: automerge

#6368 Cast numpy fixed precision types for symengine subs
  qiskit/circuit/parameterexpression.py
Labels: Changelog: None, automerge

#6369 Add test for 6350
  test/python/transpiler/test_basis_translator.py
Labels: automerge

#6366 fix typos in the UGate doc string
  qiskit/circuit/library/standard_gates/u.py
Labels: automerge

#6374 Fix missing parenthesis in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Changelog: None

#6281 Fix 6159 (Remove Unexpected Warning of PauliExpectation and AerPauliExpectation)
  qiskit/opflow/expectations/aer_pauli_expectation.py
  qiskit/opflow/expectations/pauli_expectation.py
  releasenotes/notes/bugfix-pauli-expectation-warning-bdba193ace0f012e.yaml
  test/python/opflow/test_aer_pauli_expectation.py
  test/python/opflow/test_pauli_expectation.py
Labels: Changelog: Bugfix, automerge, mod: opflow

#6363 Fix windows wheel publish job
  azure-pipelines.yml
Labels: automerge, stable backport potential

#6390 Fix counts histogram for distributions of differing sizes.
  qiskit/visualization/counts_visualization.py
  releasenotes/notes/fix-histogram-labels-issue-52b30fb915eb2732.yaml
  test/python/visualization/test_plot_histogram.py
Labels: automerge, bug, priority: high, stable backport potential

#6386 Revert "Set sympy.evaluate(False) on frequent code paths for phase tracking. (#6072)"
  qiskit/dagcircuit/dagcircuit.py
  qiskit/transpiler/passes/basis/basis_translator.py
Labels: automerge, performance

#6399 Remove stestr's grouping configuration
  .stestr.conf
  test/python/test_user_config.py
  test/python/visualization/test_gate_map.py
Labels: PR for good first issue, automerge, type: qa

#6240 Drawing boxes of custom instructions extended to classical bits in latex
  qiskit/visualization/latex.py
  releasenotes/notes/issue3202-e930ff3706628cd0.yaml
  test/python/visualization/references/test_latex_inst_with_cbits.tex
  test/python/visualization/test_circuit_latex.py
Labels: Changelog: Bugfix, automerge

#6242 The text drawings of custom instructions with clbits are now drawn as expected
  qiskit/visualization/text.py
  releasenotes/notes/issue6178-79219754e53eafdd.yaml
  test/python/visualization/test_circuit_text_drawer.py
Labels: Changelog: Bugfix, automerge

#5578 Add qpy serialization format
  docs/apidocs/qpy.rst
  docs/apidocs/terra.rst
  qiskit/circuit/qpy_serialization.py
  test/python/circuit/test_circuit_load_from_qpy.py
Labels: Changelog: New Feature

#6409 Fix aqua link in nlopt
  qiskit/algorithms/optimizers/nlopts/nloptimizer.py
Labels: automerge, mod: algorithms

#6410 some black exceptions in test_circuit_text_drawer.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: automerge

#6373 VQE with L_BFGS_B and P_BFGS supports Gradient
  qiskit/algorithms/optimizers/l_bfgs_b.py
  qiskit/algorithms/optimizers/p_bfgs.py
  releasenotes/notes/support-gradient-for-lbfgsb-87a7261ca79c3ef0.yaml
  test/python/algorithms/test_vqe.py
Labels: Changelog: Bugfix, automerge, mod: algorithms

#6391 Respect max_experiments in QuantumInstance BackendV1 path
  qiskit/utils/run_circuits.py
  releasenotes/notes/respect-max-experiments-quantum-instance-aae99429034aab52.yaml
  test/python/algorithms/test_backendv1.py
Labels: Changelog: Bugfix, automerge, stable backport potential

#6396 Port the ``EvolvedOperatorAnsatz`` from Nature
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/evolved_operator_ansatz.py
  qiskit/circuit/library/n_local/qaoa_ansatz.py
  releasenotes/notes/evolved-op-ansatz-9165704a9e57dc13.yaml
  test/python/algorithms/test_qaoa.py
  test/python/circuit/library/test_evolved_op_ansatz.py
Labels: automerge

#6417 Correctly require is_good_state on AmplificationProblem constructor
  qiskit/algorithms/amplitude_amplifiers/amplification_problem.py
  releasenotes/notes/fix-amplification-problem-init-04ebfe3ade07e910.yaml
  test/python/algorithms/test_grover.py
Labels: Changelog: Bugfix, automerge, stable backport potential

#6421 removing ChennyBaBy from mailmap (reverting #3603)
  .mailmap
Labels: Changelog: None, automerge

#6096 Implement `IterativePhaseEstimation`
  qiskit/algorithms/__init__.py
  qiskit/algorithms/phase_estimators/__init__.py
  qiskit/algorithms/phase_estimators/ipe.py
  qiskit/algorithms/phase_estimators/phase_estimation.py
  test/python/algorithms/test_phase_estimator.py
Labels: automerge, mod: algorithms

#6377 Add distributions results objects
  qiskit/result/__init__.py
  qiskit/result/distributions/__init__.py
  qiskit/result/distributions/probability.py
  qiskit/result/distributions/quasi.py
  releasenotes/notes/result-distributions-ea0760ac6efc7237.yaml
  test/python/result/test_probability.py
  test/python/result/test_quasi.py
Labels: Changelog: New Feature, NTC, automerge, priority: high

#6429 Removed redundant definition of `__rand__`
  qiskit/circuit/parametertable.py
Labels: Changelog: None, automerge

#6312 Phase Fix Measurement Redefinition
  qiskit/opflow/gradients/circuit_qfis/lin_comb_full.py
  releasenotes/notes/phase_fix_fix-e6bff434a4b1e88d.yaml
  test/python/opflow/test_gradients.py
Labels: automerge, mod: opflow

#6405 2-SPSA and QN-SPSA
  qiskit/algorithms/optimizers/__init__.py
  qiskit/algorithms/optimizers/qnspsa.py
  qiskit/algorithms/optimizers/spsa.py
  releasenotes/notes/higher-order-spsa-f2eddb44b00b82e0.yaml
  test/python/algorithms/optimizers/test_spsa.py
Labels: Changelog: New Feature, automerge, mod: algorithms

#6297 Improve performance of ``Pauli.evolve``
  qiskit/quantum_info/operators/symplectic/pauli.py
Labels: automerge, mod: quantum info

#6055 Avoid Operator while checking commutation relation in DAGDependency
  qiskit/dagcircuit/dagdependency.py
Labels: automerge, performance

#6428 Update Call instruction repr
  qiskit/pulse/instructions/call.py
Labels: automerge

#6443 Limit params displayed in mpl drawer
  qiskit/visualization/matplotlib.py
  test/ipynb/mpl/references/wide_params.png
  test/ipynb/mpl/test_circuit_matplotlib_drawer.py
Labels: automerge

#6164 Arithmetic circuit library: Adders
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/arithmetic/__init__.py
  qiskit/circuit/library/arithmetic/adders/__init__.py
  qiskit/circuit/library/arithmetic/adders/adder.py
  qiskit/circuit/library/arithmetic/adders/cdkm_ripple_carry_adder.py
  qiskit/circuit/library/arithmetic/adders/draper_qft_adder.py
  qiskit/circuit/library/arithmetic/adders/vbe_ripple_carry_adder.py
  releasenotes/notes/library-adders-748dfdcc951dfd22.yaml
  test/python/circuit/library/test_adders.py
Labels: Changelog: New Feature, automerge

#6341 add representation method for notebooks for BackendStatus
  qiskit/circuit/library/n_local/qaoa_ansatz.py
  qiskit/providers/models/backendproperties.py
  qiskit/providers/models/backendstatus.py
  test/python/providers/test_backendstatus.py
Labels: automerge

#6456 Fix process_fidelity documentation
  qiskit/quantum_info/operators/measures.py
Labels: Changelog: None, automerge

#6018 Classical conditioning on individual classical bits now supported
  qiskit/assembler/assemble_circuits.py
  qiskit/circuit/instruction.py
  qiskit/dagcircuit/dagcircuit.py
  releasenotes/notes/added-clcond-on-indvidual-clbits-1615d39dc702e3de.yaml
  test/python/basicaer/test_qasm_simulator.py
  test/python/circuit/test_extensions_standard.py
  test/python/compiler/test_assembler.py
  test/python/dagcircuit/test_dagcircuit.py
Labels: Changelog: New Feature, automerge

#6423 Port the StarAlgebraMixin from Nature and Add TensorMixin
  qiskit/opflow/mixins/__init__.py
  qiskit/opflow/mixins/star_algebra.py
  qiskit/opflow/mixins/tensor.py
  qiskit/opflow/operator_base.py
  qiskit/opflow/primitive_ops/primitive_op.py
  releasenotes/notes/star-algebra-mixin-ef201e21ab5d7fdd.yaml
Labels: automerge, mod: opflow

#6357 QuantumInstance use circuit instead of qobj for all backends
  qiskit/opflow/converters/circuit_sampler.py
  qiskit/utils/backend_utils.py
  qiskit/utils/quantum_instance.py
  qiskit/utils/run_circuits.py
  test/python/algorithms/test_vqe.py
  test/python/opflow/test_aer_pauli_expectation.py
  test/python/opflow/test_gradients.py
  test/python/opflow/test_state_op_meas_evals.py
Labels: mod: algorithms, mod: opflow

#5907 Add StabilizerState class to qiskit.quantum_info.states
  qiskit/quantum_info/__init__.py
  qiskit/quantum_info/states/__init__.py
  qiskit/quantum_info/states/quantum_state.py
  qiskit/quantum_info/states/stabilizerstate.py
  releasenotes/notes/stabilizer_state-396fb754dc68ca13.yaml
  test/python/quantum_info/states/test_stabilizerstate.py
Labels: Changelog: New Feature, automerge, mod: quantum info

#6471 Fix aer backend deprecate msgs in algorithm unit tests
  test/python/algorithms/optimizers/test_optimizer_aqgd.py
  test/python/algorithms/test_measure_error_mitigation.py
  test/python/algorithms/test_vqe.py
Labels: automerge, type: qa

#6392 deprecation warnings as error while testing
  CONTRIBUTING.md
  qiskit/test/base.py
Labels: automerge, type: qa

#6462 update inner product documentation
  qiskit/circuit/library/boolean_logic/inner_product.py
Labels: automerge

#6316 Fix addition of PauliSumOp with parameters
  qiskit/opflow/primitive_ops/pauli_sum_op.py
  releasenotes/notes/fix-addition-parameterised-paulisumop-e9b859bca1e58ddd.yaml
  test/python/opflow/test_pauli_sum_op.py
Labels: Changelog: Bugfix, automerge, mod: opflow

#6339 Matplotlib drawer fix for drawing custom instructions with classical register
  qiskit/visualization/matplotlib.py
  releasenotes/notes/issue3201-c0c942d4eb79cf61.yaml
  test/ipynb/mpl/references/instruction_1q_1c.png
  test/ipynb/mpl/references/instruction_3q_3c_circ1.png
  test/ipynb/mpl/references/instruction_3q_3c_circ2.png
  test/ipynb/mpl/references/instruction_3q_3c_circ3.png
  test/ipynb/mpl/test_circuit_matplotlib_drawer.py
  test/ipynb/mpl_tester.ipynb
Labels: Changelog: Bugfix, automerge

#5943 Create function to set user config
  qiskit/user_config.py
  releasenotes/notes/set_config-c96a56d1b860386c.yaml
  test/python/test_user_config.py
Labels: Changelog: New Feature, PR for good first issue, automerge

#6446 save a PDF file if circuit.draw('latex', filename=<something>.pdf)
  qiskit/visualization/circuit_visualization.py
Labels: Changelog: API Change, automerge

#6478 Fix typo in error message of Hamiltonian gate
  qiskit/extensions/hamiltonian_gate.py
Labels: Changelog: None, automerge

#6476 Fixed error in qc.depth() when using on circuits with single bit classical conditions
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_circuit_properties.py
Labels: Changelog: None, automerge

#6098 Using MissingOptionalLibraryError for consistency
  qiskit/__init__.py
  qiskit/circuit/equivalence.py
  qiskit/circuit/quantumcircuit.py
  qiskit/dagcircuit/dagcircuit.py
  qiskit/dagcircuit/dagdependency.py
  qiskit/exceptions.py
  qiskit/qasm/node/binaryop.py
  qiskit/qasm/node/external.py
  qiskit/qasm/node/prefix.py
  qiskit/qasm/node/real.py
  qiskit/qasm/pygments/lexer.py
  qiskit/quantum_info/operators/measures.py
  qiskit/test/base.py
  qiskit/test/runtest.py
  qiskit/tools/jupyter/job_watcher.py
  qiskit/tools/jupyter/jupyter_magics.py
  qiskit/tools/jupyter/library.py
  qiskit/tools/jupyter/progressbar.py
  qiskit/tools/monitor/overview.py
  qiskit/transpiler/coupling.py
  qiskit/visualization/array.py
  qiskit/visualization/circuit_visualization.py
  qiskit/visualization/counts_visualization.py
  qiskit/visualization/dag_visualization.py
  qiskit/visualization/gate_map.py
  qiskit/visualization/matplotlib.py
  qiskit/visualization/pass_manager_visualization.py
  qiskit/visualization/pulse/matplotlib.py
  qiskit/visualization/pulse_v2/interface.py
  qiskit/visualization/pulse_visualization.py
  qiskit/visualization/state_visualization.py
  qiskit/visualization/timeline/interface.py
  qiskit/visualization/transition_visualization.py
  qiskit/visualization/utils.py
Labels: automerge

#6452 improve error message for LookaheadSwap pass
  qiskit/transpiler/passes/routing/lookahead_swap.py
Labels: Changelog: Bugfix, automerge

#5938 Fix 2 problems with reverse_bits on all 3 circuit drawers
  qiskit/visualization/circuit_visualization.py
  qiskit/visualization/matplotlib.py
  qiskit/visualization/utils.py
  releasenotes/notes/fix-reverse-bits-conditional-measure-33389d5fd23ffd61.yaml
  test/ipynb/mpl/references/reverse_bits_cond_false.png
  test/ipynb/mpl/references/reverse_bits_cond_true.png
  test/ipynb/mpl/test_circuit_matplotlib_drawer.py
  test/python/visualization/test_circuit_text_drawer.py
  test/python/visualization/test_utils.py
Labels: Changelog: Bugfix, automerge

#6488 C3XGate is 3-qubit
  qiskit/circuit/library/standard_gates/x.py
Labels: Changelog: None, automerge
