Repository Qiskit/qiskit, pull requests merged in 2022-04, with the labels that each got.

#7850 Fixes Clifford, Pauli, CNOTDihedral to handle Delay
  qiskit/quantum_info/operators/dihedral/dihedral_circuits.py
  qiskit/quantum_info/operators/symplectic/base_pauli.py
  qiskit/quantum_info/operators/symplectic/clifford_circuits.py
  qiskit/quantum_info/operators/symplectic/pauli.py
  releasenotes/notes/clifford_delay-be1a835413e2531e.yaml
  test/python/quantum_info/operators/symplectic/test_clifford.py
  test/python/quantum_info/operators/symplectic/test_pauli.py
  test/python/quantum_info/operators/test_dihedral.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#7853 Fix a few 0.20 release note typos.
  releasenotes/notes/0.20/add-sparsepauliop-equiv-7a8a1420117dba21.yaml
  releasenotes/notes/0.20/add-v2-backend-support-in-transpiler-parse-inst-map-a617801850178d05.yaml
  releasenotes/notes/0.20/add-xxminusyy-gate-63e6530c23500de9.yaml
  releasenotes/notes/0.20/cleanup-deprecated-circuitmeth-89edb244f572b754.yaml
  releasenotes/notes/0.20/dense-layout-target-aware-2b330ccee948d31a.yaml
  releasenotes/notes/0.20/update-instruction-alignment-passes-ef0f20d4f89f95f3.yaml
Labels: stable backport potential, automerge, Changelog: None, documentation

#7793 Fix hard-coded sleep in run_circuits
  qiskit/utils/run_circuits.py
  releasenotes/notes/fix-hard-coded-sleep-run-circuits-a1588164e61d5336.yaml
Labels: stable backport potential, Changelog: Bugfix, automerge

#7851 Fix potential copy/paste error in doc string
  qiskit/qpy/common.py
Labels: type: documentation, stable backport potential, automerge, Changelog: None

#7872 Improve parenthesis in circuit library equations
  qiskit/circuit/library/standard_gates/iswap.py
  qiskit/circuit/library/standard_gates/r.py
  qiskit/circuit/library/standard_gates/rx.py
  qiskit/circuit/library/standard_gates/rxx.py
  qiskit/circuit/library/standard_gates/ry.py
  qiskit/circuit/library/standard_gates/ryy.py
  qiskit/circuit/library/standard_gates/rz.py
  qiskit/circuit/library/standard_gates/rzx.py
  qiskit/circuit/library/standard_gates/rzz.py
  qiskit/circuit/library/standard_gates/u.py
  qiskit/circuit/library/standard_gates/u1.py
  qiskit/circuit/library/standard_gates/u3.py
  qiskit/circuit/library/standard_gates/xx_minus_yy.py
  qiskit/circuit/library/standard_gates/xx_plus_yy.py
Labels: Changelog: None, documentation

#7806 Add regression tests of single-bit conditions in QuantumCircuit.compose
  test/python/circuit/test_compose.py
Labels: type: qa, stable backport potential, automerge, Changelog: None

#7863 Fix of eval_observables() when quantum_circuit is a StateFn.
  qiskit/algorithms/aux_ops_evaluator.py
  releasenotes/notes/fix-aux-ops-evaluator-83ce1606d1ad19b3.yaml
  test/python/algorithms/test_aux_ops_evaluator.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#7880 Fix plot_error_map with BackendProperties set or BackendV2
  qiskit/visualization/gate_map.py
  releasenotes/notes/fix-plot-error-map-f3b4cc754b589d8f.yaml
  test/python/visualization/references/kolkata_error.png
  test/python/visualization/references/kolkata_v2_error.png
  test/python/visualization/references/washington_error.png
  test/python/visualization/references/washington_v2_error.png
  test/python/visualization/test_gate_map.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#7885 Fix return type from schedule() with a list of one entry
  qiskit/compiler/scheduler.py
  releasenotes/notes/fix-list-input-schedule-14fc48895a061735.yaml
  test/python/scheduler/test_basic_scheduler.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#7811 Add qiskit-bot notification config
  qiskit_bot.yaml
Labels: automerge, Changelog: None

#7893 Example for creating quantum circuit from unitary matrix
  qiskit/extensions/unitary.py
Labels: automerge, Changelog: None, documentation

#7898 Fix init_observable for Pauli
  qiskit/primitives/utils.py
  releasenotes/notes/fix-primitive-init-observable-pauli-e312c05d1c3bd804.yaml
Labels: stable backport potential, performance, Changelog: Bugfix, automerge, mod: primitives

#7897 Fix indent & improve consistency of primitive docs with Qiskit
  qiskit/primitives/base_estimator.py
  qiskit/primitives/base_sampler.py
  qiskit/primitives/estimator_result.py
  qiskit/primitives/sampler.py
  qiskit/primitives/sampler_result.py
  qiskit/primitives/utils.py
Labels: stable backport potential, automerge, Changelog: None, documentation

#7858 Add interfaces for a general Quantum Time Evolution Framework
  qiskit/algorithms/__init__.py
  qiskit/algorithms/aux_ops_evaluator.py
  qiskit/algorithms/eigen_solvers/eigen_solver.py
  qiskit/algorithms/eigen_solvers/numpy_eigen_solver.py
  qiskit/algorithms/evolvers/__init__.py
  qiskit/algorithms/evolvers/evolution_problem.py
  qiskit/algorithms/evolvers/evolution_result.py
  qiskit/algorithms/evolvers/imaginary/__init__.py
  qiskit/algorithms/evolvers/imaginary/imaginary_evolver.py
  qiskit/algorithms/evolvers/real/__init__.py
  qiskit/algorithms/evolvers/real/real_evolver.py
  qiskit/algorithms/list_or_dict.py
  qiskit/algorithms/minimum_eigen_solvers/minimum_eigen_solver.py
  qiskit/algorithms/minimum_eigen_solvers/numpy_minimum_eigen_solver.py
  qiskit/algorithms/minimum_eigen_solvers/vqe.py
  releasenotes/notes/time-evo-framework-9d58827bdbbebd62.yaml
  test/python/algorithms/evolvers/__init__.py
  test/python/algorithms/evolvers/test_evolution_problem.py
  test/python/algorithms/evolvers/test_evolution_result.py
  test/python/algorithms/test_aux_ops_evaluator.py
Labels: Changelog: New Feature, automerge

#7857 Add support for non-hermitian operators in AerPauliExpectation
  qiskit/opflow/expectations/aer_pauli_expectation.py
  releasenotes/notes/add-support-non-hermitian-op-aerpauliexpectation-653d8e16de4eca07.yaml
  test/python/opflow/test_aer_pauli_expectation.py
Labels: Changelog: New Feature, automerge, mod: opflow

#7917 remove ENHANCEMENT_REQUEST issue template
  .github/ISSUE_TEMPLATE/ENHANCEMENT_REQUEST.yaml
Labels: automerge, Changelog: None

#7856 Correcting documentation of Drag/LiftedDrag (Qiskit#7659)
  qiskit/pulse/library/parametric_pulses.py
Labels: automerge

#7925 Bug fix for DRAG pulse beta validation
  qiskit/pulse/library/parametric_pulses.py
  qiskit/test/mock/backends/washington/conf_washington.json
  qiskit/test/mock/backends/washington/defs_washington.json
  qiskit/test/mock/backends/washington/props_washington.json
  releasenotes/notes/fix-drag-pulse-validation-905f9b6353a0f2d1.yaml
  test/python/pulse/test_pulse_lib.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#7927 Deprecate networkx converter methods for DAGCircuit
  qiskit/dagcircuit/dagcircuit.py
  qiskit/dagcircuit/dagdependency.py
  releasenotes/notes/deprecate-nx-dag-f8a8d947186222c2.yaml
  test/python/dagcircuit/test_dagcircuit.py
Labels: Changelog: Deprecation, automerge

#7824 Allow `shots` to be a `numpy.int64`
  qiskit/compiler/assembler.py
  test/python/compiler/test_assembler.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#7698 Overhaul Azure Pipelines configuration
  .azure/docs-linux.yml
  .azure/lint-linux.yml
  .azure/test-linux.yml
  .azure/test-macos.yml
  .azure/test-windows.yml
  .azure/tutorials-linux.yml
  .azure/wheels.yml
  azure-pipelines.yml
Labels: type: qa, automerge, Changelog: None

#7923 Fix dag visualization for DAGCircuits without registers
  qiskit/visualization/dag_visualization.py
  releasenotes/notes/fix-dag-drawer-no-reg-6eee9d1f6e4b9261.yaml
  test/python/visualization/references/dag_no_reg.png
  test/python/visualization/test_dag_drawer.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#7931 Fix pulse `limit_amplitude` unittest
  test/python/pulse/test_pulse_lib.py
Labels: automerge, Changelog: None

#7929 Update qiskit_bot regex for rust file change trigger
  qiskit_bot.yaml
Labels: automerge, Changelog: None

#7933 Fix QPY deserialization of UCRX, UCRY, and UCRZ gates
  qiskit/qpy/binary_io/circuits.py
  releasenotes/notes/ucr-gates-qpy-b8f6fb1e34fae258.yaml
  test/python/circuit/test_circuit_load_from_qpy.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#7940 Set sphinx-build --keep-going by default
  tox.ini
Labels: automerge, Changelog: None

#7946 Revert "Workaround Aer bug with subnormal floats in randomised tests (#7719)"
  test/randomized/test_synthesis.py
  test/randomized/test_transpiler_equivalence.py
Labels: automerge, Changelog: None

#7924 Grover class crosslinks note to tutorials and textbook
  qiskit/algorithms/amplitude_amplifiers/grover.py
Labels: type: documentation, automerge, Changelog: None

#7945 Improve transpiler coverage of randomized equivalence test
  test/randomized/test_transpiler_equivalence.py
Labels: automerge, Changelog: None

#7671 Ensuring instruction labels are strings when provided to the Instruction constructor.
  qiskit/circuit/instruction.py
  releasenotes/notes/type-check-instruction-labels-on-creation-8399dd8b5d72f272.yaml
  test/python/circuit/test_extensions_standard.py
  test/python/circuit/test_instructions.py
Labels: Changelog: API Change, automerge

#7884 Update docstrings for renamed scheduling passes
  qiskit/transpiler/__init__.py
  qiskit/transpiler/passes/scheduling/alignments/reschedule.py
  qiskit/transpiler/passes/scheduling/padding/dynamical_decoupling.py
  qiskit/transpiler/passes/scheduling/scheduling/alap.py
  qiskit/transpiler/passes/scheduling/scheduling/asap.py
  qiskit/transpiler/passes/scheduling/scheduling/base_scheduler.py
Labels: stable backport potential, automerge, Changelog: None, documentation

#7912 Store simulator Backend in FakeBackend instance
  qiskit/test/mock/fake_backend.py
  qiskit/test/mock/utils/backend_converter.py
Labels: stable backport potential, performance, automerge, Changelog: None, mod: fake_provider

#7354 Add some explanation and example to circuit library documentation
  qiskit/circuit/__init__.py
  qiskit/circuit/library/__init__.py
Labels: type: documentation, priority: medium, stable backport potential, automerge, Changelog: None

#7918 Fix XXPlusYYGate documentation
  qiskit/circuit/library/standard_gates/xx_plus_yy.py
  releasenotes/notes/xxplusyy-doc-c6ddcc45044dcdcd.yaml
  test/python/circuit/test_extensions_standard.py
Labels: stable backport potential, automerge, Changelog: None, documentation

#7952 Make SabreSwap account for clbits in predecessors
  qiskit/transpiler/passes/routing/sabre_swap.py
  releasenotes/notes/fix-sabreswap-clbits-428eb5f3a46063da.yaml
  test/python/transpiler/test_sabre_swap.py
Labels: stable backport potential, randomized test, Changelog: Bugfix, automerge

#7958 Swap old networkx usage to retworkx
  qiskit/circuit/library/graph_state.py
Labels: stable backport potential, automerge, Changelog: None

#7960 Add uniformly controlled rotations to docs
  qiskit/extensions/__init__.py
  qiskit/extensions/quantum_initializer/__init__.py
Labels: stable backport potential, automerge, Changelog: None

#7813 Add swap strategies transpiler pass
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/routing/__init__.py
  qiskit/transpiler/passes/routing/swap_strategies/__init__.py
  qiskit/transpiler/passes/routing/swap_strategies/commuting_2q_block.py
  qiskit/transpiler/passes/routing/swap_strategies/commuting_2q_gate_router.py
  qiskit/transpiler/passes/routing/swap_strategies/pauli_2q_evolution_commutation.py
  qiskit/transpiler/passes/routing/swap_strategies/swap_strategy.py
  releasenotes/notes/swap-strategies-3ab013ca60f02b36.yaml
  test/python/circuit/test_extensions_standard.py
  test/python/circuit/test_gate_definitions.py
  test/python/transpiler/test_swap_strategy.py
  test/python/transpiler/test_swap_strategy_router.py
Labels: Changelog: New Feature, automerge

#7954 Deprecate old paths for module-availability testers
  qiskit/visualization/__init__.py
  releasenotes/notes/deprecate-old-optional-paths-982466a6336e4794.yaml
Labels: Changelog: Deprecation, automerge

#7970 Fix potential infinite loop in SabreSwap
  qiskit/transpiler/passes/routing/sabre_swap.py
  releasenotes/notes/sabreswap-loop-230ef99e61358105.yaml
  test/python/transpiler/test_sabre_swap.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#7942 Add delay handling to QASM 3 exporter
  qiskit/qasm3/ast.py
  qiskit/qasm3/exporter.py
  qiskit/qasm3/printer.py
  releasenotes/notes/qasm3-exporter-delay-ef3003e01412c97e.yaml
  test/python/circuit/test_circuit_qasm3.py
Labels: Changelog: New Feature, automerge, qasm

#7962 Prepare 0.20.1 release
  Cargo.lock
  Cargo.toml
  docs/conf.py
  qiskit/VERSION.txt
  releasenotes/notes/clifford_delay-be1a835413e2531e.yaml
  releasenotes/notes/fix-aux-ops-evaluator-83ce1606d1ad19b3.yaml
  releasenotes/notes/fix-dag-drawer-no-reg-6eee9d1f6e4b9261.yaml
  releasenotes/notes/fix-drag-pulse-validation-905f9b6353a0f2d1.yaml
  releasenotes/notes/fix-hard-coded-sleep-run-circuits-a1588164e61d5336.yaml
  releasenotes/notes/fix-list-input-schedule-14fc48895a061735.yaml
  releasenotes/notes/fix-plot-error-map-f3b4cc754b589d8f.yaml
  releasenotes/notes/fix-primitive-init-observable-pauli-e312c05d1c3bd804.yaml
  releasenotes/notes/prepare-0.20.1-72b215a1ca1f34c8.yaml
  releasenotes/notes/ucr-gates-qpy-b8f6fb1e34fae258.yaml
  releasenotes/notes/xxplusyy-doc-c6ddcc45044dcdcd.yaml
  setup.py
Labels: automerge, Changelog: None

#7974 Fix sdist build step on stable
  azure-pipelines.yml
Labels: automerge, Changelog: None

#7973 Fix sdist build and deployment
  azure-pipelines.yml
Labels: automerge, Changelog: None

#7919 Alias BaseOperator.__matmul__ to BaseOperator.dot
  qiskit/quantum_info/operators/mixins/group.py
  releasenotes/notes/add-overloading@-3fedb7bc2fd4d7f7.yaml
  test/python/quantum_info/operators/channel/test_chi.py
  test/python/quantum_info/operators/channel/test_choi.py
  test/python/quantum_info/operators/channel/test_kraus.py
  test/python/quantum_info/operators/channel/test_ptm.py
  test/python/quantum_info/operators/channel/test_stinespring.py
  test/python/quantum_info/operators/channel/test_superop.py
  test/python/quantum_info/operators/symplectic/test_pauli.py
  test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
  test/python/quantum_info/operators/test_operator.py
  test/python/quantum_info/operators/test_scalar_op.py
Labels: Changelog: New Feature, automerge, mod: quantum info

#7972 Fix order of input and gate declarations in QASM 3 exporter
  qiskit/qasm3/exporter.py
  releasenotes/notes/fix-qasm3-global-statement-order-ca8bdb35e0fb8dec.yaml
  test/python/circuit/test_circuit_qasm3.py
Labels: stable backport potential, Changelog: Bugfix, automerge, qasm

#7768 Support control flow in Unroller transpiler pass
  qiskit/circuit/controlflow/control_flow.py
  qiskit/circuit/controlflow/for_loop.py
  qiskit/circuit/controlflow/if_else.py
  qiskit/circuit/controlflow/while_loop.py
  qiskit/transpiler/passes/basis/unroller.py
  test/python/transpiler/test_unroller.py
Labels: automerge, Changelog: None

#7980 Update randomised transpiler-equivalence test strategies
  test/randomized/test_transpiler_equivalence.py
Labels: type: qa, randomized test, automerge, Changelog: None

#7907 add Quantum Shannon Decomposition
  qiskit/extensions/unitary.py
  qiskit/quantum_info/synthesis/qsd.py
  qiskit/transpiler/passes/synthesis/unitary_synthesis.py
  releasenotes/notes/quantum_shannon_decomp-facaa362a3ca8ba3.yaml
  test/python/quantum_info/test_synthesis.py
Labels: Changelog: New Feature, automerge

#7913 Improve scaling and performance of `Optimize1qSimpleCommutation`
  qiskit/transpiler/passes/optimization/optimize_1q_commutation.py
Labels: performance, automerge, Changelog: None

#7862 Add VF2PostLayout pass
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/layout/__init__.py
  qiskit/transpiler/passes/layout/apply_layout.py
  qiskit/transpiler/passes/layout/vf2_post_layout.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  releasenotes/notes/vf2-post-layout-f0213e2c7ebb645c.yaml
  test/python/providers/test_backend_v2.py
  test/python/pulse/test_builder.py
  test/python/transpiler/test_preset_passmanagers.py
  test/python/transpiler/test_vf2_post_layout.py
Labels: Changelog: New Feature, automerge

#7992 Tweak probabilities in random equivalence test
  test/randomized/test_transpiler_equivalence.py
Labels: type: qa, randomized test, automerge, Changelog: None

#8000 Fix `dt` units in test util function `convert_to_target`
  qiskit/test/mock/utils/backend_converter.py
  releasenotes/notes/fix-target-dt-4d306f1e9b07f819.yaml
  test/python/providers/test_fake_backends.py
Labels: type: qa, stable backport potential, Changelog: Bugfix, automerge
