Repository Qiskit/qiskit, pull requests merged in 2022-01, with the labels that each got.

#7462 Add distutils warning ignore from seaborn
  qiskit/test/base.py
  requirements-dev.txt
  test/python/circuit/test_gate_definitions.py
Labels: stable backport potential, automerge, Changelog: None

#7433 Alternate example for plot_bloch_multivector
  qiskit/visualization/state_visualization.py
Labels: stable backport potential, automerge, Changelog: None

#7467 Fix matrix representation of ``ExcitationPreserving`` circuit
  qiskit/circuit/library/n_local/excitation_preserving.py
Labels: type: documentation, stable backport potential, automerge, Changelog: None

#7425 Give FakeOpenPulse2Q qubit T2 times and readout errors
  qiskit/test/mock/fake_openpulse_2q.py
  releasenotes/notes/fix-fake-openpulse2q-15f9c880de52e98f.yaml
Labels: stable backport potential, Changelog: Bugfix, automerge

#7469 Fix documentation for Sphinx 4
  qiskit/circuit/__init__.py
  qiskit/circuit/library/__init__.py
  requirements-dev.txt
Labels: type: documentation, stable backport potential, automerge, Changelog: None

#7492 Pin sphinx-autodoc-typehints to unblock docs builds
  requirements-dev.txt
Labels: type: qa, stable backport potential, automerge, Changelog: None

#7489 Fix bad version test in P_BFGS
  qiskit/algorithms/optimizers/p_bfgs.py
Labels: stable backport potential, automerge, mod: algorithms, Changelog: None

#7216 Refactor BlueprintCircuit
  qiskit/algorithms/linear_solvers/matrices/numpy_matrix.py
  qiskit/algorithms/linear_solvers/matrices/tridiagonal_toeplitz.py
  qiskit/circuit/library/arithmetic/integer_comparator.py
  qiskit/circuit/library/arithmetic/linear_pauli_rotations.py
  qiskit/circuit/library/arithmetic/piecewise_chebyshev.py
  qiskit/circuit/library/arithmetic/piecewise_linear_pauli_rotations.py
  qiskit/circuit/library/arithmetic/piecewise_polynomial_pauli_rotations.py
  qiskit/circuit/library/arithmetic/polynomial_pauli_rotations.py
  qiskit/circuit/library/arithmetic/weighted_adder.py
  qiskit/circuit/library/basis_change/qft.py
  qiskit/circuit/library/blueprintcircuit.py
  qiskit/circuit/library/evolved_operator_ansatz.py
  qiskit/circuit/library/n_local/n_local.py
  qiskit/circuit/library/n_local/pauli_two_design.py
  qiskit/circuit/library/n_local/qaoa_ansatz.py
  test/python/circuit/library/test_blueprintcircuit.py
Labels: Changelog: None

#7515 Fixed Issue #7511
  qiskit/circuit/quantumcircuit.py
Labels: type: documentation, automerge, Changelog: None

#7517 Fix Bloch sphere with Matplotlib 3.3 and 3.4
  qiskit/visualization/bloch.py
  releasenotes/notes/fix-path2d-mpl3.4-b1af3a23b408d30a.yaml
Labels: stable backport potential, Changelog: Bugfix, automerge

#7087 Operation abstract base class
  qiskit/circuit/__init__.py
  qiskit/circuit/barrier.py
  qiskit/circuit/gate.py
  qiskit/circuit/instruction.py
  qiskit/circuit/measure.py
  qiskit/circuit/operation.py
  qiskit/circuit/reset.py
  qiskit/extensions/quantum_initializer/initializer.py
  qiskit/extensions/quantum_initializer/isometry.py
  qiskit/quantum_info/operators/dihedral/dihedral.py
  qiskit/quantum_info/operators/symplectic/clifford.py
  qiskit/quantum_info/operators/symplectic/pauli.py
  releasenotes/notes/Operation-abstract-base-class-99f46180c7ddaa6b.yaml
  test/python/circuit/test_operation.py
Labels: Changelog: New Feature, automerge

#7522 Fixed Code Error in Release Notes 0.34.1(Issue #7521)
  releasenotes/notes/0.19/execute-fix-108e835dc4f4593d.yaml
Labels: stable backport potential, automerge, Changelog: None

#7459 Fix display of register names with multiple underscores in mpl and latex drawers
  qiskit/visualization/matplotlib.py
  qiskit/visualization/utils.py
  releasenotes/notes/fix-multi-underscore-display-37b900195ca3d2c5.yaml
  test/ipynb/mpl/circuit/references/multi_underscore_false.png
  test/ipynb/mpl/circuit/references/multi_underscore_true.png
  test/ipynb/mpl/circuit/test_circuit_matplotlib_drawer.py
  test/python/visualization/references/test_latex_4597.tex
  test/python/visualization/references/test_latex_cif_single_bit_bundle.tex
  test/python/visualization/references/test_latex_conditional.tex
  test/python/visualization/references/test_latex_creg_initial_true.tex
  test/python/visualization/references/test_latex_meas_cond_bits_true.tex
  test/python/visualization/references/test_latex_meas_cond_true.tex
  test/python/visualization/references/test_latex_meas_condition.tex
  test/python/visualization/references/test_latex_multi_underscore_false.tex
  test/python/visualization/references/test_latex_multi_underscore_true.tex
  test/python/visualization/references/test_latex_no_barriers_false.tex
  test/python/visualization/references/test_latex_no_ops.tex
  test/python/visualization/references/test_latex_partial_layout.tex
  test/python/visualization/references/test_latex_plot_barriers_false.tex
  test/python/visualization/references/test_latex_plot_barriers_true.tex
  test/python/visualization/references/test_latex_plot_partial_barriers.tex
  test/python/visualization/references/test_latex_registerless_one_bit.tex
  test/python/visualization/references/test_latex_teleport.tex
  test/python/visualization/test_circuit_latex.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#7518 Fix display of negative fractions in arrays
  qiskit/visualization/array.py
  releasenotes/notes/fix-negative-fraction-display-735efdba3b825cba.yaml
Labels: stable backport potential, Changelog: Bugfix, automerge

#7510 Prevent duplicate bits in registers
  qiskit/circuit/register.py
  releasenotes/notes/fix-duplicated-bits-9e72181c9247f934.yaml
  test/python/circuit/test_register.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#6962 Nesting FlowControllers to allow nested conditionals in pass manager
  qiskit/transpiler/passmanager.py
  qiskit/transpiler/runningpassmanager.py
  releasenotes/notes/add-nested-conditionals-pass-manager-db7b8b9874018d0d.yaml
  test/python/transpiler/test_pass_scheduler.py
Labels: automerge

#6949 Remove ParametrizedSchedule
  qiskit/pulse/instruction_schedule_map.py
  qiskit/pulse/schedule.py
  releasenotes/notes/remove-parametrized-schedule-fc4b31a8180db9d9.yaml
  test/python/pulse/test_schedule.py
Labels: Changelog: Removal, automerge

#7456 Reject other QASM versions in QASM 2 parser
  qiskit/qasm/node/format.py
  qiskit/qasm/qasmlexer.py
  qiskit/qasm/qasmparser.py
  releasenotes/notes/qasm-lexer-bugfix-1779525b3738902c.yaml
  test/python/qasm/example_minor_version_fail.qasm
  test/python/qasm/example_version_2.qasm
  test/python/qasm/example_version_fail.qasm
  test/python/test_qasm_parser.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#7409 Need to remove max_credits
  examples/python/ibmq/hello_quantum.py
  examples/python/ibmq/using_qiskit_terra_level_0.py
  qiskit/assembler/run_config.py
  qiskit/compiler/assembler.py
  qiskit/execute_function.py
  qiskit/qobj/pulse_qobj.py
  qiskit/qobj/qasm_qobj.py
  qiskit/test/mock/fake_qobj.py
  qiskit/utils/quantum_instance.py
  releasenotes/notes/deprecate-max-credits-56a404050a655a04.yaml
  test/python/qobj/test_qobj.py
  test/python/qobj/test_qobj_deprecated.py
Labels: Changelog: Deprecation, automerge

#7102 Add support for Python 3.10
  .github/workflows/wheels.yml
  azure-pipelines.yml
  pyproject.toml
  qiskit/test/base.py
  setup.py
  tox.ini
Labels: Changelog: New Feature, automerge

#7484 Fix QI modifying input transpiled circuit on execute
  qiskit/utils/quantum_instance.py
  releasenotes/notes/fix-qi-transpiled-8df449529bf6d9a2.yaml
  test/python/algorithms/test_measure_error_mitigation.py
Labels: stable backport potential, Changelog: Bugfix, automerge, mod: algorithms

#7543 Add ikkoham as code owner for quantum_info and opflow
  .github/CODEOWNERS
Labels: automerge, Changelog: None

#7477 Update parametric pulse documentation.
  qiskit/pulse/library/parametric_pulses.py
Labels: stable backport potential, automerge, Changelog: None

#7549 Add cross-build wheel jobs for ppc64le and s390x
  .github/workflows/wheels.yml
  pyproject.toml
  releasenotes/notes/ibm-cpu-arch-support-3289377f3834f29e.yaml
Labels: type: qa, Changelog: New Feature, automerge

#7553 Drop support for 32bit py310 wheel builds
  pyproject.toml
  releasenotes/notes/py310-support-869d47583c976eef.yaml
Labels: Changelog: API Change, automerge

#7463 Add durations of pulse gates from DAG calibrations
  qiskit/dagcircuit/dagcircuit.py
  qiskit/transpiler/passes/calibration/builders.py
  qiskit/transpiler/passes/scheduling/alap.py
  qiskit/transpiler/passes/scheduling/asap.py
Labels: automerge, mod: pulse

#7535 Fix imported forward references in type hints
  qiskit/assembler/assemble_schedules.py
  qiskit/pulse/schedule.py
Labels: stable backport potential, automerge, Changelog: None

#7554 Fix error in Target non-global operation method with ideal gates
  qiskit/compiler/transpiler.py
  qiskit/transpiler/target.py
  releasenotes/notes/fix-non-global-operation-name-ideal-sim-3dcbc97e29c707c7.yaml
  test/python/compiler/test_transpiler.py
  test/python/transpiler/test_target.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#7570 Tweak apt usage in Ubuntu CI job configuration
  azure-pipelines.yml
Labels: stable backport potential, automerge, Changelog: None

#7541 Warn not error on overflow in QFT
  qiskit/circuit/library/basis_change/qft.py
  releasenotes/notes/warn-on-too-large-qft-a2dd60d4a374751a.yaml
  test/python/circuit/library/test_qft.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#7566 Use manylinux2014 on all Linux builds
  azure-pipelines.yml
  pyproject.toml
  releasenotes/notes/manylinux2014-e33268fda54e12b1.yaml
Labels: Changelog: API Change, automerge

#7559 Add `__repr__` to DAG nodes
  qiskit/dagcircuit/dagnode.py
  releasenotes/notes/add-repr-for-dag-nodes-2d0a95fecd3dd3db.yaml
  test/python/dagcircuit/test_dagcircuit.py
Labels: Changelog: New Feature, automerge

#7586 Fix typo at line 262 of qiskit.circuit.quantumcircuit.py in a #comment
  qiskit/circuit/quantumcircuit.py
Labels: automerge, Changelog: None

#7294 Fix linear solvers API documentation
  qiskit/algorithms/__init__.py
  qiskit/algorithms/linear_solvers/__init__.py
  qiskit/algorithms/linear_solvers/observables/absolute_average.py
  qiskit/algorithms/linear_solvers/observables/matrix_functional.py
  releasenotes/notes/fix-linear-solvers-api-2b4df93a42263337.yaml
Labels: type: documentation, automerge, mod: algorithms, Changelog: None

#7562 Remove probability_distributions module
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/probability_distributions/__init__.py
  qiskit/circuit/library/probability_distributions/lognormal.py
  qiskit/circuit/library/probability_distributions/normal.py
  qiskit/circuit/library/probability_distributions/uniform.py
  qiskit/test/base.py
  releasenotes/notes/remove_probability_distributions-d30bd77f0f2b9570.yaml
  test/python/circuit/library/test_probability_distributions.py
Labels: Changelog: Removal, automerge

#7551 Fix qubit order for 2-qubit ``LieTrotter`` evolution synthesis
  qiskit/circuit/library/pauli_evolution.py
  qiskit/synthesis/evolution/product_formula.py
  releasenotes/notes/fix-lietrotter-2q-61d5cd66e0bf7359.yaml
  test/python/circuit/library/test_evolution_gate.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#7579 Merge paramterized u1, u2 and p gate in Optimize1qGates
  qiskit/transpiler/passes/optimization/optimize_1q_gates.py
  releasenotes/notes/optimization-u2-gates-with-parameters-322b6c523251108c.yaml
  test/python/transpiler/test_optimize_1q_gates.py
Labels: Changelog: New Feature, automerge

#7590 Expose ``parameter_prefix`` in ``Z(Z)FeatureMap``
  qiskit/circuit/library/data_preparation/z_feature_map.py
  qiskit/circuit/library/data_preparation/zz_feature_map.py
  releasenotes/notes/add-parameter-prefix-support-to-ZFeatureMap-ZZFeatureMap-ba13832b9a832e88.yaml
  test/python/circuit/library/test_pauli_feature_map.py
Labels: Changelog: New Feature, automerge

#7476 Update README.md: `pip install qiskit` no longer installs all elements
  README.md
Labels: automerge, Changelog: None

#6033 Add .editorconfig
  .editorconfig
Labels: automerge, Changelog: None
