Repository Qiskit/qiskit, pull requests merged in 2022-10, with the labels that each got.

#8748 Sampled expectation value for distributions
  qiskit/__init__.py
  qiskit/quantum_info/__init__.py
  qiskit/quantum_info/analysis/__init__.py
  qiskit/result/__init__.py
  qiskit/result/distributions/__init__.py
  qiskit/result/sampled_expval.py
  releasenotes/notes/sampled_expval-85e300e0fb5fa5ea.yaml
  src/lib.rs
  src/pauli_exp_val.rs
  src/sampled_exp_val.rs
  test/python/result/test_sampled_expval.py
Labels: priority: medium, Changelog: New Feature, automerge, Rust

#8818 Force skip tweedledum 1.1.1 on macOS amd64
  requirements.txt
Labels: automerge, Changelog: None

#8762 plot_histogram now a valid histogram, plot_distribution for non-discrete data
  qiskit/visualization/__init__.py
  qiskit/visualization/counts_visualization.py
  releasenotes/notes/plot-hist-797bfaeea2156c53.yaml
Labels: Changelog: New Feature, automerge

#8823 Add control-flow support to `GatesInBasis`
  qiskit/transpiler/passes/utils/gates_basis.py
  test/python/transpiler/test_gates_in_basis_pass.py
Labels: priority: high, Changelog: New Feature, automerge

#8822 Update GateDirection and checker for control flow
  qiskit/transpiler/passes/utils/check_gate_direction.py
  qiskit/transpiler/passes/utils/gate_direction.py
  releasenotes/notes/gate-direction-target-a9f0acd0cf30ed66.yaml
  test/python/transpiler/test_check_gate_direction.py
  test/python/transpiler/test_gate_direction.py
Labels: priority: high, Changelog: New Feature, Changelog: Bugfix, automerge

#8828 Limit importlib_metadata in requirements
  requirements.txt
Labels: type: qa, automerge, Changelog: None

#8648 Add support for custom backend transpiler stages
  qiskit/compiler/transpiler.py
  qiskit/providers/__init__.py
  qiskit/providers/backend.py
  qiskit/transpiler/passmanager_config.py
  qiskit/transpiler/preset_passmanagers/__init__.py
  qiskit/transpiler/preset_passmanagers/level3.py
  releasenotes/notes/add-backend-custom-passes-cddfd05c8704a4b1.yaml
  releasenotes/notes/stage-plugin-interface-47daae40f7d0ad3c.yaml
  test/python/transpiler/test_preset_passmanagers.py
Labels: priority: medium, Changelog: New Feature, automerge, mod: transpiler

#8833 Resolve classical conditions in `QuantumCircuit.while_loop`
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/condition-in-while-loop-d6be0d6d6a1429da.yaml
  test/python/circuit/test_control_flow.py
Labels: Changelog: Bugfix, automerge

#8585 Improve the performance of Clifford.from_circuit()
  qiskit/quantum_info/operators/symplectic/clifford.py
  qiskit/quantum_info/operators/symplectic/clifford_circuits.py
  test/python/quantum_info/operators/symplectic/test_clifford.py
Labels: automerge, Changelog: None

#8837 Introduce observable key for Estimator
  qiskit/primitives/backend_estimator.py
  qiskit/primitives/base_estimator.py
  qiskit/primitives/estimator.py
  qiskit/primitives/utils.py
  test/python/primitives/test_backend_estimator.py
  test/python/primitives/test_estimator.py
Labels: Changelog: Bugfix, automerge, Changelog: None, mod: primitives

#8802 Fix reverse permutation for transpiled circuits in Operator.from_circuit
  qiskit/compiler/transpiler.py
  qiskit/quantum_info/operators/operator.py
  qiskit/transpiler/basepasses.py
  qiskit/transpiler/layout.py
  qiskit/transpiler/passes/layout/apply_layout.py
  qiskit/transpiler/runningpassmanager.py
  qiskit/visualization/circuit/latex.py
  qiskit/visualization/circuit/matplotlib.py
  qiskit/visualization/circuit/text.py
  qiskit/visualization/gate_map.py
  releasenotes/notes/fix-Opertor.from_circuit-transpile-5c056968ee40025e.yaml
  test/python/quantum_info/operators/test_operator.py
  test/python/transpiler/test_bip_mapping.py
  test/python/transpiler/test_preset_passmanagers.py
  test/python/transpiler/test_sabre_layout.py
  test/python/visualization/test_circuit_text_drawer.py
  test/python/visualization/test_gate_map.py
Labels: Changelog: API Change, Changelog: Bugfix, automerge

#8840 Remove nkanazawa1989 from code owner
  .github/CODEOWNERS
  qiskit_bot.yaml
Labels: automerge, Changelog: None

#8841 Fixing import in preset_passmanagers code example
  qiskit/transpiler/__init__.py
Labels: documentation, automerge, Changelog: None

#8832 Handle negative variance in Estimator
  qiskit/primitives/estimator.py
  test/python/primitives/test_estimator.py
Labels: bug, automerge, Changelog: None, mod: primitives

#8842 Fix in Transpiler Stage Plugin Interface docs
  qiskit/transpiler/preset_passmanagers/plugin.py
Labels: documentation, automerge, Changelog: None

#8843 Fix DenseLayout when loose bits are present in input circuit
  qiskit/transpiler/passes/layout/dense_layout.py
  releasenotes/notes/denselayout-loose-bits-3e66011432bc6232.yaml
  test/python/transpiler/test_dense_layout.py
Labels: Changelog: Bugfix, automerge

#8418 Add controlflow handling to stochastic swap pass
  qiskit/dagcircuit/dagcircuit.py
  qiskit/dagcircuit/dagnode.py
  qiskit/transpiler/passes/routing/stochastic_swap.py
  qiskit/transpiler/passes/routing/utils.py
  qiskit/transpiler/passes/utils/check_map.py
  test/python/transpiler/test_stochastic_swap.py
Labels: priority: high, Changelog: New Feature, automerge

#8847 Fix handling of 1q gates in UnitarySynthesis with target
  qiskit/transpiler/passes/synthesis/unitary_synthesis.py
  releasenotes/notes/fix-unitary-synth-1q-circuit-756ad4ed209a313f.yaml
  test/python/transpiler/test_unitary_synthesis.py
Labels: Changelog: Bugfix, automerge

#8844 Fix BasisTranslator with control-flow ops on other bits
  qiskit/transpiler/passes/basis/basis_translator.py
  test/python/transpiler/test_basis_translator.py
Labels: automerge, Changelog: None

#8848 Set a fixed seed for all BackendEstimator tests
  test/python/primitives/test_backend_estimator.py
Labels: type: qa, automerge, Changelog: None

#8791 Add shots to QuasiDistributions in primitives.Sampler
  qiskit/primitives/sampler.py
  test/python/primitives/test_sampler.py
Labels: automerge, Changelog: None, mod: primitives

#8849 Remove tweedledum from macOS arm64 immediately
  releasenotes/notes/begin-tweedledum-removal-25bb68fc72804f00.yaml
  requirements.txt
Labels: Changelog: API Change, automerge

#8867 Add retworkx to generated module list in the .pylintrc
  .pylintrc
  qiskit/circuit/equivalence.py
  qiskit/transpiler/coupling.py
  qiskit/transpiler/passes/basis/basis_translator.py
  qiskit/visualization/dag_visualization.py
Labels: type: qa, stable backport potential, automerge, Changelog: None

#8869 Ensure target is generated during run() with FakeBackendV2
  qiskit/providers/fake_provider/fake_backend.py
  test/python/providers/fake_provider/test_fake_backends.py
Labels: stable backport potential, automerge, Changelog: None

#8860 Minor doc fix in `SamplingVQE` and `BaseEstimator`
  qiskit/algorithms/minimum_eigensolvers/sampling_vqe.py
  qiskit/primitives/base_estimator.py
Labels: documentation, stable backport potential, automerge, mod: algorithms, Changelog: None, mod: primitives, Community PR

#8812 Fix bugs in primitives type validation and refactor
  qiskit/primitives/__init__.py
  qiskit/primitives/backend_estimator.py
  qiskit/primitives/backend_sampler.py
  qiskit/primitives/base/__init__.py
  qiskit/primitives/base/base_estimator.py
  qiskit/primitives/base/base_primitive.py
  qiskit/primitives/base/base_result.py
  qiskit/primitives/base/base_sampler.py
  qiskit/primitives/base/estimator_result.py
  qiskit/primitives/base/sampler_result.py
  qiskit/primitives/estimator.py
  qiskit/primitives/sampler.py
  test/python/primitives/test_estimator.py
  test/python/primitives/test_primitive.py
  test/python/primitives/test_result.py
Labels: stable backport potential, Changelog: None, mod: primitives

#8877 Fix pauli.evolve dtype casting error
  qiskit/quantum_info/operators/symplectic/base_pauli.py
  qiskit/quantum_info/operators/symplectic/pauli.py
  qiskit/quantum_info/operators/symplectic/pauli_list.py
  releasenotes/notes/fix_8438-159e67ecb6765d08.yaml
  test/python/quantum_info/operators/symplectic/test_pauli.py
  test/python/quantum_info/operators/symplectic/test_pauli_list.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#8851 Fix deprecation warning for `deprecated_functionality`
  qiskit/pulse/transforms/alignments.py
  releasenotes/notes/0.22/deprecated-pulse-deprecator-394ec75079441cda.yaml
Labels: stable backport potential, automerge, Changelog: None

#8879 Fix handling of controlflow ops when control flow is in basis
  qiskit/transpiler/passes/basis/unroll_3q_or_more.py
  test/python/transpiler/test_unroll_3q_or_more.py
Labels: priority: high, stable backport potential, automerge, Changelog: None

#8880 Fix control-flow routing in StochasticSwap
  qiskit/transpiler/passes/routing/stochastic_swap.py
  qiskit/transpiler/passes/routing/utils.py
  test/python/transpiler/test_stochastic_swap.py
Labels: priority: high, stable backport potential, automerge, Changelog: None

#8852 Fix transpile() for control flow operations with a Target/BackendV2
  qiskit/transpiler/target.py
  releasenotes/notes/fix-target-control-flow-representation-09520e2838f0657e.yaml
  test/python/compiler/test_transpiler.py
  test/python/transpiler/test_dense_layout.py
  test/python/transpiler/test_target.py
Labels: priority: high, stable backport potential, automerge

#8882 Prepare for 0.22.0rc2 tag
  Cargo.lock
  qiskit/VERSION.txt
  setup.py
Labels: automerge, Changelog: None

#8891 Fix StochasticSwap routing for if blocks with no else
  qiskit/transpiler/passes/routing/stochastic_swap.py
  test/python/transpiler/test_stochastic_swap.py
Labels: stable backport potential, automerge, Changelog: None

#8799 Return `DAGOpNode` from `dagcircuit.replace_block_with_op`
  qiskit/dagcircuit/dagcircuit.py
  releasenotes/notes/add-new-node-return-f2574c1593cbb57b.yaml
  test/python/dagcircuit/test_dagcircuit.py
Labels: Changelog: New Feature, automerge, Community PR

#8905 Fix pauli_basis deprecation
  qiskit/quantum_info/operators/symplectic/pauli_utils.py
  releasenotes/notes/fix-pauli-basis-dep-27c0a4506ad38d2c.yaml
Labels: stable backport potential, Changelog: Deprecation, Changelog: Bugfix, automerge

#8895 note that chop is not supported by SparsePauliOp either
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
Labels: documentation, stable backport potential, automerge, mod: quantum info, Changelog: None

#8796 Make primitives's key serializable
  qiskit/primitives/utils.py
Labels: automerge, Changelog: None, mod: primitives

#8928 Fix loose-bit handling in QPY
  qiskit/qpy/binary_io/circuits.py
  releasenotes/notes/fix-qpy-loose-bits-5283dc4ad3823ce3.yaml
  test/python/circuit/test_circuit_load_from_qpy.py
Labels: stable backport potential, Changelog: Bugfix, automerge, mod: qpy

#8835 Deprecate lists for argument input on transpile()
  qiskit/compiler/transpiler.py
  releasenotes/notes/deprecate-list-args-transpile-f92e5b3d411f361f.yaml
Labels: Changelog: Deprecation, automerge

#8927 Fix qpy custom ControlledGate with overloaded _define()
  qiskit/qpy/binary_io/circuits.py
  releasenotes/notes/fix-qpy-custom-controlled-gate-a9355df1a88a83a5.yaml
  test/python/circuit/test_circuit_load_from_qpy.py
Labels: stable backport potential, Changelog: Bugfix, automerge, mod: qpy

#8925 Fix handling of globally defined operations in Target
  qiskit/transpiler/passes/layout/dense_layout.py
  qiskit/transpiler/target.py
  releasenotes/notes/fix-global-inst-qarg-method-target-a9188e172ea7f325.yaml
  test/python/transpiler/test_target.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#8924 Fix `BarrierBeforeFinalMeasurements` with loose bits
  qiskit/transpiler/passes/utils/barrier_before_final_measurements.py
  releasenotes/notes/fix-barrier-before-final-measurements-loose-1849282c11fc5eb0.yaml
  test/python/transpiler/test_barrier_before_final_measurements.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#8612 Bump PyO3 and rust-numpy to latest release
  Cargo.lock
  Cargo.toml
Labels: automerge, Changelog: None, Rust, dependencies

#8930 Fix single-bit-condition equality in QuantumCircuit and DAGCircuit
  qiskit/dagcircuit/dagnode.py
  releasenotes/notes/fix-circuit-condition-compare-d8d85e5ca47c1416.yaml
  test/python/circuit/test_circuit_operations.py
  test/python/dagcircuit/test_dagcircuit.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#8447 fix hinton visualization bug
  qiskit/visualization/state_visualization.py
  releasenotes/notes/fix-hinton-bug-1141a297050f55bb.yaml
Labels: stable backport potential, automerge, Community PR, mod: visualization

#8945 Doc fix-ups for staged pass manager plugin
  qiskit/transpiler/preset_passmanagers/plugin.py
Labels: documentation, stable backport potential, automerge, Changelog: None

#8906 Fix classical-bit handling in control-flow StochasticSwap
  qiskit/transpiler/passes/routing/stochastic_swap.py
  releasenotes/notes/fix-clbit-handling-stochasticswap-controlflow-fbb9d8fab5040643.yaml
  test/python/compiler/test_transpiler.py
  test/python/transpiler/test_stochastic_swap.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#8944 Add singledispatchmethod to dependency
  qiskit/circuit/classicalfunction/__init__.py
  qiskit/transpiler/passes/basis/basis_translator.py
  releasenotes/notes/add-singledispatchmethod-78ff14b1ef25ef99.yaml
  requirements.txt
Labels: Changelog: API Change, automerge

#8932 Expand documentation backends/providers and primitives
  qiskit/primitives/backend_estimator.py
  qiskit/primitives/backend_sampler.py
  qiskit/providers/__init__.py
Labels: documentation, stable backport potential, automerge, Changelog: None

#8900 Fix Statevector.evolve and DensityMatrix.evolve for mixed dimension subsystems
  qiskit/quantum_info/operators/op_shape.py
  qiskit/quantum_info/states/densitymatrix.py
  qiskit/quantum_info/states/statevector.py
  releasenotes/notes/fix_8897-2a90c4b0857c19c2.yaml
  test/python/quantum_info/states/test_densitymatrix.py
  test/python/quantum_info/states/test_statevector.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#8784 Make UnrollCustomDefinitions pass target aware
  qiskit/transpiler/passes/basis/unroll_custom_definitions.py
  qiskit/transpiler/preset_passmanagers/common.py
  releasenotes/notes/target-aware-unroll-custom-definitions-a1b839de199ca048.yaml
  test/python/compiler/test_transpiler.py
  test/python/transpiler/test_unroll_custom_definitions.py
Labels: Changelog: New Feature, automerge, mod: transpiler

#8952 Fix parallel dispatch with target argument in transpile()
  qiskit/compiler/transpiler.py
  releasenotes/notes/fix-target-transpile-parallel-772f943a08d0570b.yaml
  test/python/compiler/test_transpiler.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#8968 Relax now-unneeded constraints
  constraints.txt
Labels: type: qa, automerge, Changelog: None

#8947 Remove tweedledum as a core dependency
  qiskit/circuit/classicalfunction/__init__.py
  qiskit/circuit/classicalfunction/boolean_expression.py
  qiskit/circuit/classicalfunction/classical_function_visitor.py
  qiskit/circuit/classicalfunction/classicalfunction.py
  qiskit/circuit/classicalfunction/utils.py
  qiskit/circuit/library/phase_oracle.py
  releasenotes/notes/remove-tweedledum-0f21ca327a782bc3.yaml
  requirements.txt
  test/python/classical_function_compiler/test_tweedledum2qiskit.py
Labels: Changelog: API Change, automerge

#8973 Disable pylint's import-error
  .pylintrc
  qiskit/algorithms/optimizers/nlopts/nloptimizer.py
  qiskit/circuit/equivalence.py
  qiskit/compiler/transpiler.py
  qiskit/opflow/gradients/gradient.py
  qiskit/opflow/gradients/hessian.py
  qiskit/providers/fake_provider/fake_backend.py
  qiskit/providers/fake_provider/fake_backend_v2.py
  qiskit/providers/fake_provider/fake_mumbai_v2.py
  qiskit/quantum_info/operators/measures.py
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
  qiskit/quantum_info/states/densitymatrix.py
  qiskit/quantum_info/states/statevector.py
  qiskit/result/sampled_expval.py
  qiskit/result/utils.py
  qiskit/test/base.py
  qiskit/tools/jupyter/__init__.py
  qiskit/tools/jupyter/job_watcher.py
  qiskit/transpiler/coupling.py
  qiskit/transpiler/passes/layout/dense_layout.py
  qiskit/transpiler/passes/optimization/_gate_extension.py
  qiskit/transpiler/passes/optimization/crosstalk_adaptive_schedule.py
  qiskit/transpiler/passes/optimization/hoare_opt.py
  qiskit/transpiler/passes/optimization/optimize_1q_gates.py
  qiskit/transpiler/passes/routing/sabre_swap.py
  qiskit/utils/backend_utils.py
  qiskit/utils/optionals.py
  qiskit/version.py
  qiskit/visualization/dag_visualization.py
  test/python/algorithms/test_measure_error_mitigation.py
  test/python/opflow/test_state_op_meas_evals.py
  test/python/utils/mitigation/test_meas.py
  tools/subunit_to_junit.py
Labels: type: qa, automerge, Changelog: None

#8975 Remove IBM Q example scripts
  examples/python/ibmq/ghz.py
  examples/python/ibmq/hello_quantum.py
  examples/python/ibmq/qft.py
  examples/python/ibmq/using_qiskit_terra_level_0.py
  examples/python/ibmq/using_qiskit_terra_level_1.py
  examples/python/ibmq/using_qiskit_terra_level_2.py
Labels: documentation, automerge, Changelog: None

#8974 Avoid skipping channels in pulse visualizer
  qiskit/visualization/pulse_v2/layouts.py
  releasenotes/notes/visualization-missing-channels-bc66c1c976a79c06.yaml
  test/python/visualization/pulse_v2/test_layouts.py
Labels: Changelog: Bugfix, automerge

#8987 Fix QEMU-based Linux wheel jobs
  pyproject.toml
Labels: stable backport potential, automerge, Changelog: None

#8998 Fix #8992 (SparsePauliOp.dot with real coefficients)
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
  releasenotes/notes/fix-sparse-pauli-real-63c31d87801671b1.yaml
  test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
Labels: stable backport potential, Changelog: Bugfix, automerge, mod: quantum info

#9001 Fix DCXGate's QASM docstring #8990
  qiskit/circuit/library/standard_gates/dcx.py
Labels: documentation, automerge, Changelog: None, Community PR

#9004 Fix manifest entry for mpl styles
  MANIFEST.in
  releasenotes/notes/fix-styles-manifest-b8c852a07fb86966.yaml
Labels: stable backport potential, Changelog: Bugfix, automerge, Community PR, mod: visualization

#8686 Remove references to IBM Q from the README.md
  README.md
Labels: documentation, stable backport potential, automerge, Changelog: None

#8996 Remove pip cache in azure pipelines jobs
  .azure/docs-linux.yml
  .azure/lint-linux.yml
  .azure/test-linux.yml
  .azure/test-macos.yml
  .azure/tutorials-linux.yml
Labels: stable backport potential, automerge, Changelog: None

#7697 Accelerated implementation of objective function class for approximate quantum compiling
  qiskit/transpiler/synthesis/aqc/__init__.py
  qiskit/transpiler/synthesis/aqc/aqc.py
  qiskit/transpiler/synthesis/aqc/cnot_structures.py
  qiskit/transpiler/synthesis/aqc/cnot_unit_circuit.py
  qiskit/transpiler/synthesis/aqc/cnot_unit_objective.py
  qiskit/transpiler/synthesis/aqc/fast_gradient/__init__.py
  qiskit/transpiler/synthesis/aqc/fast_gradient/fast_grad_utils.py
  qiskit/transpiler/synthesis/aqc/fast_gradient/fast_gradient.py
  qiskit/transpiler/synthesis/aqc/fast_gradient/layer.py
  qiskit/transpiler/synthesis/aqc/fast_gradient/pmatrix.py
  test/python/transpiler/aqc/fast_gradient/__init__.py
  test/python/transpiler/aqc/fast_gradient/test_cmp_gradients.py
  test/python/transpiler/aqc/fast_gradient/test_layer1q.py
  test/python/transpiler/aqc/fast_gradient/test_layer2q.py
  test/python/transpiler/aqc/fast_gradient/test_utils.py
  test/python/transpiler/aqc/fast_gradient/utils_for_testing.py
  test/python/transpiler/aqc/sample_data.py
  test/python/transpiler/aqc/test_aqc.py
  test/python/transpiler/aqc/test_gradient.py
Labels: automerge, Community PR

#8995 Fix transpile() with a Target containing an ideal Measure
  qiskit/transpiler/target.py
  releasenotes/notes/fix-transpile-ideal-measurement-c37e04533e196ded.yaml
  test/python/compiler/test_transpiler.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#9017 Add missing equivalences for XX{Plus,Minus}YYGate
  qiskit/circuit/library/standard_gates/equivalence_library.py
  releasenotes/notes/add-xxyy-equivalence-a941c9b9bc60747b.yaml
  test/python/circuit/test_gate_definitions.py
Labels: Changelog: New Feature, automerge

#9021 Fix exact floating-point comparison causing flaky test
  test/python/opflow/test_aer_pauli_expectation.py
Labels: type: qa, stable backport potential, automerge, Changelog: None

#9022 Add misssing language from README codeblocks
  README.md
Labels: documentation, stable backport potential, automerge, Changelog: None

#9018 Update NLopt install instructions
  qiskit/algorithms/optimizers/__init__.py
  qiskit/algorithms/optimizers/nlopts/__init__.py
  qiskit/utils/optionals.py
Labels: bug, documentation, stable backport potential, automerge, mod: algorithms, Changelog: None

#8983 Speed up `random_circuit`
  qiskit/circuit/random/utils.py
  releasenotes/notes/speedup-random-circuits-8d3b724cce1faaad.yaml
  test/python/circuit/test_random_circuit.py
Labels: performance, Changelog: New Feature, Changelog: API Change, automerge

#9006 add QuantumCircuit.from_instructions
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/circuit-from-instructions-832b43bfd2bfd921.yaml
  test/python/circuit/test_circuit_operations.py
Labels: Changelog: New Feature, automerge

#8942 Deprecate Python 3.7 support
  qiskit/__init__.py
  releasenotes/notes/deprecate-3.7-1040fe5988ba914a.yaml
Labels: Changelog: Deprecation, automerge

#8272 Fix zero-operand gates and instructions
  qiskit/circuit/controlledgate.py
  qiskit/circuit/gate.py
  qiskit/converters/circuit_to_gate.py
  qiskit/quantum_info/operators/op_shape.py
  releasenotes/notes/fix-zero-operand-gates-323510ec8f392f27.yaml
  test/python/circuit/test_controlled_gate.py
  test/python/converters/test_circuit_to_gate.py
  test/python/converters/test_circuit_to_instruction.py
  test/python/quantum_info/operators/test_operator.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#8955 Fix backend primitives on backends with job size limit
  qiskit/primitives/backend_estimator.py
  qiskit/primitives/backend_sampler.py
  releasenotes/notes/fix-max_circuits-backend-primitives-c70590bca557001f.yaml
  test/python/primitives/test_backend_estimator.py
  test/python/primitives/test_backend_sampler.py
Labels: stable backport potential, Changelog: Bugfix, automerge, mod: primitives

#8977 Fix handling of global ideal gates for target build_coupling_map()
  qiskit/transpiler/target.py
  releasenotes/notes/fix-mixed-ideal-target-coupling-map-7fca04f9c5139a49.yaml
  test/python/transpiler/test_target.py
Labels: stable backport potential, Changelog: Bugfix

#9027 Fix up docstring for VF2PostLayout
  qiskit/transpiler/passes/layout/vf2_post_layout.py
Labels: documentation, stable backport potential, automerge, Changelog: None
