Repository Qiskit/qiskit, pull requests merged in 2022-06, with the labels that each got.

#8065 Enhance Primitives' interface
  qiskit/primitives/base_estimator.py
  qiskit/primitives/base_sampler.py
  qiskit/primitives/estimator.py
  qiskit/primitives/estimator_result.py
  qiskit/primitives/sampler.py
  qiskit/primitives/sampler_result.py
  qiskit/primitives/utils.py
  releasenotes/notes/primitive-interface-408b91ed338a5bc4.yaml
  test/python/primitives/test_estimator.py
  test/python/primitives/test_sampler.py
Labels: Changelog: New Feature, mod: primitives

#8131 Fix double matrix computation in numpy eigensolver
  qiskit/algorithms/eigen_solvers/numpy_eigen_solver.py
Labels: performance, automerge, mod: algorithms, Changelog: None

#8125 Add function to easily generate preset pass managers
  qiskit/compiler/transpiler.py
  qiskit/transpiler/preset_passmanagers/__init__.py
  qiskit/transpiler/target.py
  releasenotes/notes/generate_pass_manager_preset-1e6c9641accd5d60.yaml
  test/python/transpiler/test_preset_passmanagers.py
Labels: Changelog: New Feature

#8117 set T2 with the correct value in ConfigurableFakeBackend
  qiskit/test/mock/utils/configurable_backend.py
  releasenotes/notes/fix-t2-configurablefakebackend-8660ab3d7a57a824.yaml
  test/python/mock/test_configurable_backend.py
Labels: Changelog: Bugfix, automerge, mod: fake_provider

#8099 fix marginal_counts (which failed on pulse backend) (issue #6430)
  qiskit/result/utils.py
  releasenotes/fix-marginal_counts-on-pulse-backend.yaml
  test/python/result/test_result.py
Labels: Changelog: Bugfix, automerge

#7481 Fixed error in plot_histogram when number_to_keep is smaller that the number of keys
  qiskit/visualization/counts_visualization.py
  releasenotes/notes/fix_plot_histogram_number-a0a4a023dfad3c70.yaml
  test/ipynb/mpl/graph/references/histogram_2_sets_with_rest.png
  test/ipynb/mpl/graph/references/histogram_with_rest.png
  test/ipynb/mpl/graph/test_graph_matplotlib_drawer.py
  test/python/visualization/test_plot_histogram.py
Labels: Changelog: Bugfix, automerge

#8147 Add Qiskit Textbook circuit drawer style
  qiskit/visualization/qcstyle.py
  qiskit/visualization/styles/textbook.json
  releasenotes/notes/add-textbook-circuit-style-98600038608c8f75.yaml
  test/ipynb/mpl/circuit/references/textbook_color.png
  test/ipynb/mpl/circuit/test_circuit_matplotlib_drawer.py
Labels: Changelog: New Feature, automerge

#8129 changing qc.decompose() to transpile(qc, backend)
  qiskit/transpiler/__init__.py
Labels: automerge, Changelog: None, documentation

#7408 Use `ParameterReferences` type for `ParameterTable` values
  qiskit/circuit/parametertable.py
  qiskit/circuit/quantumcircuit.py
  qiskit/opflow/gradients/circuit_gradients/lin_comb.py
  qiskit/opflow/gradients/circuit_gradients/param_shift.py
  qiskit/opflow/gradients/circuit_qfis/overlap_block_diag.py
  qiskit/opflow/gradients/circuit_qfis/overlap_diag.py
  releasenotes/notes/param-table-perf-72cd1c40533b3882.yaml
  test/python/circuit/test_circuit_data.py
  test/python/circuit/test_parameters.py
Labels: performance, Changelog: New Feature, automerge

#7846 Callback Protocol for Minimizer in VQE
  qiskit/algorithms/minimum_eigen_solvers/qaoa.py
  qiskit/algorithms/minimum_eigen_solvers/vqe.py
  qiskit/algorithms/optimizers/__init__.py
  qiskit/algorithms/optimizers/optimizer.py
  requirements.txt
Labels: type: documentation, automerge, mod: algorithms, Changelog: None

#8144 Fix the typo in the documentation of CSwapGate
  qiskit/circuit/library/standard_gates/swap.py
Labels: automerge, Changelog: None, documentation

#8168 Replace deprecated threading.currentThread with current_thread
  qiskit/tools/jupyter/backend_overview.py
Labels: automerge, Changelog: None

#8167 Fix the order of the Lie-Trotter formula in the documentation
  qiskit/synthesis/evolution/lie_trotter.py
Labels: type: documentation, automerge, Changelog: None, Community PR

#8171 Fix the order of the Suzuki-Trotter formula in the documentation
  qiskit/synthesis/evolution/suzuki_trotter.py
Labels: type: documentation, automerge, Changelog: None, Community PR

#8172 enables the code example
  qiskit/quantum_info/operators/symplectic/pauli.py
Labels: type: documentation

#8101 Add label assigned check in SparsePauliOp
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
  releasenotes/notes/add_check_from_sparse_list-97f13fde87c7bcb6.yaml
  test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
Labels: Changelog: New Feature, automerge, mod: quantum info, QAMP, Community PR

#8160 Fix QASM 3 exporter not respecting unknown `basis_gates`
  qiskit/qasm3/exporter.py
  releasenotes/notes/qasm3-fix-basis-gates-c96a0b357dfdcb47.yaml
  test/python/circuit/test_circuit_qasm3.py
Labels: Changelog: Bugfix, automerge, qasm

#7821 Serializable parametric pulse
  qiskit/assembler/assemble_circuits.py
  qiskit/assembler/assemble_schedules.py
  qiskit/pulse/__init__.py
  qiskit/pulse/library/__init__.py
  qiskit/pulse/library/parametric_pulses.py
  qiskit/pulse/library/pulse.py
  qiskit/pulse/library/symbolic_pulses.py
  qiskit/pulse/library/waveform.py
  qiskit/pulse/parameter_manager.py
  qiskit/qobj/converters/pulse_instruction.py
  qiskit/qpy/__init__.py
  qiskit/visualization/pulse_v2/core.py
  qiskit/visualization/pulse_v2/generators/waveform.py
  qiskit/visualization/pulse_v2/interface.py
  releasenotes/notes/add-serializable-parametric-pulse-31490c4d2cc49ec6.yaml
  test/python/pulse/test_block.py
  test/python/pulse/test_pulse_lib.py
Labels: Changelog: New Feature, automerge, mod: qpy

#8162 Switched `dag_drawer` from `pydot` to `retworkx`
  docs/conf.py
  qiskit/visualization/dag_visualization.py
  test/python/visualization/test_dag_drawer.py
Labels: automerge, Changelog: None, Community PR

#8142 decompose(reps=1) repeating decompose
  qiskit/circuit/library/blueprintcircuit.py
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/add-parameters-to-decompose-5a541d1b5afe2c68.yaml
  test/python/transpiler/test_decompose.py
Labels: Changelog: New Feature, automerge, Community PR

#8134 Add `.clear()` and `.copy_empty_like()` functionality to QuantumCircuit.
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/clear-circuit-b8edd4126f47d75a.yaml
  test/python/circuit/test_circuit_operations.py
Labels: Changelog: New Feature, automerge

#8165 Bug fixes in InverseCancellation pass
  qiskit/transpiler/passes/optimization/inverse_cancellation.py
  test/python/transpiler/test_inverse_cancellation.py
Labels: automerge

#8181 Fix indent in execute_function docstring
  qiskit/execute_function.py
Labels: automerge, Changelog: None

#8196 Explicitly set MSRV for rust extension
  .azure/test-linux.yml
  CONTRIBUTING.md
  README.md
  azure-pipelines.yml
  releasenotes/notes/msrv-0b626e1cfb415abf.yaml
Labels: Changelog: API Change, automerge, Rust

#8055 Fix handling of ControlledGates in QPY
  qiskit/qpy/__init__.py
  qiskit/qpy/binary_io/circuits.py
  qiskit/qpy/common.py
  qiskit/qpy/formats.py
  releasenotes/notes/fix-qpy-controlled-gates-e653cbeee067f90b.yaml
  test/python/circuit/test_circuit_load_from_qpy.py
  test/qpy_compat/test_qpy.py
Labels: Changelog: API Change, Changelog: Bugfix, automerge, mod: qpy

#8068 Speedup constant factors in `LookaheadSwap`
  qiskit/transpiler/passes/routing/lookahead_swap.py
  releasenotes/notes/speedup-lookahead-swap-4dd162fee2d25d10.yaml
Labels: performance, Changelog: New Feature, automerge

#8216 Edit Result to always contain date, status, header
  qiskit/result/result.py
  releasenotes/notes/result-fix-e4eaa021f49b5f99.yaml
  test/python/result/test_result.py
Labels: Changelog: API Change, Changelog: Bugfix, automerge

#8109 Fix BackendV2 support for PassManagerConfig.from_backend()
  qiskit/transpiler/passmanager_config.py
  releasenotes/notes/fix-pm-config-backend_v2-ac8b83267105a47d.yaml
  test/python/transpiler/test_passmanager_config.py
Labels: Changelog: Bugfix, automerge

#5089 Add namespace redirect hook for qiskit-aer
  qiskit/__init__.py
  qiskit/namespace.py
  qiskit/providers/__init__.py
  qiskit/version.py
Labels: priority: high, Changelog: Deprecation, automerge

#8123 Remove deprecated `optimize` from `Optimizer` (and small other fixes)
  qiskit/algorithms/minimum_eigen_solvers/vqe.py
  qiskit/algorithms/optimizers/adam_amsgrad.py
  qiskit/algorithms/optimizers/aqgd.py
  qiskit/algorithms/optimizers/bobyqa.py
  qiskit/algorithms/optimizers/gradient_descent.py
  qiskit/algorithms/optimizers/gsls.py
  qiskit/algorithms/optimizers/imfil.py
  qiskit/algorithms/optimizers/nlopts/nloptimizer.py
  qiskit/algorithms/optimizers/optimizer.py
  qiskit/algorithms/optimizers/p_bfgs.py
  qiskit/algorithms/optimizers/scipy_optimizer.py
  qiskit/algorithms/optimizers/snobfit.py
  qiskit/algorithms/optimizers/spsa.py
  releasenotes/notes/remove-deprecated-optimizer-methods-d580a07112ccaa2d.yaml
  test/python/algorithms/optimizers/test_gradient_descent.py
  test/python/algorithms/optimizers/test_optimizers.py
  test/python/algorithms/optimizers/test_spsa.py
Labels: Changelog: Deprecation, Changelog: Removal, Changelog: Bugfix, automerge, mod: algorithms

#8218 Optimize standard gate.__array__
  qiskit/circuit/library/standard_gates/ecr.py
  qiskit/circuit/library/standard_gates/h.py
  qiskit/circuit/library/standard_gates/p.py
  qiskit/circuit/library/standard_gates/r.py
  qiskit/circuit/library/standard_gates/rx.py
  qiskit/circuit/library/standard_gates/rxx.py
  qiskit/circuit/library/standard_gates/ry.py
  qiskit/circuit/library/standard_gates/ryy.py
  qiskit/circuit/library/standard_gates/rz.py
  qiskit/circuit/library/standard_gates/rzx.py
  qiskit/circuit/library/standard_gates/rzz.py
  qiskit/circuit/library/standard_gates/t.py
  qiskit/circuit/library/standard_gates/u.py
  qiskit/circuit/library/standard_gates/u1.py
  qiskit/circuit/library/standard_gates/u2.py
  qiskit/circuit/library/standard_gates/u3.py
  qiskit/circuit/library/standard_gates/xx_minus_yy.py
  qiskit/circuit/library/standard_gates/xx_plus_yy.py
  qiskit/circuit/library/standard_gates/y.py
Labels: automerge, Changelog: None

#7789 Leverage Python SharedMemory for common transpile args
  qiskit/compiler/transpiler.py
  qiskit/transpiler/passes/synthesis/unitary_synthesis.py
  releasenotes/notes/shared-memory-dependency-1e32e1c55902216f.yaml
  requirements.txt
  test/python/compiler/test_transpiler.py
  test/python/providers/test_backend_v2.py
Labels: performance, Changelog: API Change, Changelog: Bugfix, automerge

#8200 Set version number to 0.21.0rc1 for first release candidate
  Cargo.lock
  Cargo.toml
  docs/conf.py
  qiskit/VERSION.txt
  qiskit/qpy/interface.py
  setup.py
  test/qpy_compat/test_qpy.py
Labels: automerge, Changelog: None

#8051 Add dedicated functions for memory marginalization
  Cargo.lock
  Cargo.toml
  qiskit/result/__init__.py
  qiskit/result/utils.py
  releasenotes/notes/marginal-memory-29d9d6586ae78590.yaml
  src/lib.rs
  src/results/converters.rs
  src/results/marginalization.rs
  src/results/mod.rs
  test/python/result/test_memory_marginalization.py
Labels: Changelog: New Feature, automerge, Rust

#7300 QPY schedule serialization
  qiskit/pulse/instructions/acquire.py
  qiskit/pulse/library/symbolic_pulses.py
  qiskit/pulse/transforms/alignments.py
  qiskit/pulse/transforms/dag.py
  qiskit/qpy/__init__.py
  qiskit/qpy/binary_io/__init__.py
  qiskit/qpy/binary_io/circuits.py
  qiskit/qpy/binary_io/schedules.py
  qiskit/qpy/binary_io/value.py
  qiskit/qpy/common.py
  qiskit/qpy/formats.py
  qiskit/qpy/interface.py
  qiskit/qpy/type_keys.py
  releasenotes/notes/upgrade-qpy-schedule-f28f6a48a3abb4de.yaml
  test/python/pulse/test_instructions.py
  test/python/qpy/__init__.py
  test/python/qpy/test_block_load_from_qpy.py
  test/qpy_compat/test_qpy.py
Labels: Changelog: Deprecation, Changelog: New Feature, automerge, mod: pulse, mod: qpy

#8223 Refactor marginal_memory() hex to bin lookup table to be a true static
  Cargo.lock
  Cargo.toml
  src/lib.rs
  src/results/converters.rs
Labels: performance, automerge, Changelog: None, Rust

#8070 Remove deprecated classes and methods in quantum_info
  qiskit/opflow/primitive_ops/tapered_pauli_sum_op.py
  qiskit/quantum_info/__init__.py
  qiskit/quantum_info/operators/__init__.py
  qiskit/quantum_info/operators/dihedral/dihedral.py
  qiskit/quantum_info/operators/pauli.py
  qiskit/quantum_info/operators/symplectic/clifford.py
  qiskit/quantum_info/operators/symplectic/pauli.py
  releasenotes/notes/remove-deprecate-calsses-methods-7bd69606cc4ad61f.yaml
  test/python/quantum_info/operators/symplectic/test_legacy_pauli.py
Labels: Changelog: Removal, automerge, mod: quantum info, QAMP, Community PR

#8084 UMDA optimizer added
  qiskit/algorithms/optimizers/__init__.py
  qiskit/algorithms/optimizers/umda.py
  releasenotes/notes/umda-optimizer-9ddcda3d25cd8d9a.yaml
  test/python/algorithms/optimizers/test_umda.py
Labels: automerge, mod: algorithms, Community PR

#7747 Adding variational Quantum Deflation Algorithm for computing higher energy states
  qiskit/algorithms/__init__.py
  qiskit/algorithms/eigen_solvers/__init__.py
  qiskit/algorithms/eigen_solvers/vqd.py
  releasenotes/notes/vqd-implementation-details-09b0ead8b42cacda.yaml
  test/python/algorithms/test_vqd.py
Labels: Changelog: New Feature, automerge, mod: algorithms, Community PR

#8227 Release notes for Terra 0.21rc1
  releasenotes/notes/add-group-commuting-method-in-PauliList-and-SparsePauliOp-5dec2877c4a97861.yaml
  releasenotes/notes/add-overloading@-3fedb7bc2fd4d7f7.yaml
  releasenotes/notes/add-serializable-parametric-pulse-31490c4d2cc49ec6.yaml
  releasenotes/notes/add-support-non-hermitian-op-aerpauliexpectation-653d8e16de4eca07.yaml
  releasenotes/notes/add_check_from_sparse_list-97f13fde87c7bcb6.yaml
  releasenotes/notes/change-instruction-data-scalar-81f2066ca2435933.yaml
  releasenotes/notes/cleanup-timeline-drawer-a6287bdab4459e6e.yaml
  releasenotes/notes/clear-circuit-b8edd4126f47d75a.yaml
  releasenotes/notes/clifford_delay-be1a835413e2531e.yaml
  releasenotes/notes/delay-fake-backends-3f68c074e85d531f.yaml
  releasenotes/notes/deprecate-nx-dag-f8a8d947186222c2.yaml
  releasenotes/notes/feature-trotter-qrte-f7b28c4fd4b361d2.yaml
  releasenotes/notes/fix-aux-ops-evaluator-83ce1606d1ad19b3.yaml
  releasenotes/notes/fix-dag-drawer-no-reg-6eee9d1f6e4b9261.yaml
  releasenotes/notes/fix-drag-pulse-validation-905f9b6353a0f2d1.yaml
  releasenotes/notes/fix-eigs_bounds-function-in-TridiagonalToeplitz-class-52cfad8f72ae7341.yaml
  releasenotes/notes/fix-fake-backend-v2-dtm-unit-392a8fe3fcc9b793.yaml
  releasenotes/notes/fix-hard-coded-sleep-run-circuits-a1588164e61d5336.yaml
  releasenotes/notes/fix-latex-ket-max-size-f11c3a89215a49e7.yaml
  releasenotes/notes/fix-list-input-schedule-14fc48895a061735.yaml
  releasenotes/notes/fix-marginal_counts-zero-memory-0f6710d6923c8ad7.yaml
  releasenotes/notes/fix-plot-error-map-f3b4cc754b589d8f.yaml
  releasenotes/notes/fix-primitive-init-observable-pauli-e312c05d1c3bd804.yaml
  releasenotes/notes/fix-qasm3-global-statement-order-ca8bdb35e0fb8dec.yaml
  releasenotes/notes/fix-qpy-controlled-gates-e653cbeee067f90b.yaml
  releasenotes/notes/fix-rzx-builder-pulse-amp-ba5c876ddea17c41.yaml
  releasenotes/notes/fix-sabreswap-clbits-428eb5f3a46063da.yaml
  releasenotes/notes/fix-t2-configurablefakebackend-8660ab3d7a57a824.yaml
  releasenotes/notes/fix-target-dt-4d306f1e9b07f819.yaml
  releasenotes/notes/fix-transpile-backendv2-durations-dbc85688564cc271.yaml
  releasenotes/notes/fix_plot_histogram_number-a0a4a023dfad3c70.yaml
  releasenotes/notes/marginal-memory-29d9d6586ae78590.yaml
  releasenotes/notes/move-qiskit.test.mock-to-qiskit.providers.fake_provider-7f36ff80a05f9a9a.yaml
  releasenotes/notes/parallelize-circuit-scheduling-972d4616eabb2ccb.yaml
  releasenotes/notes/param-table-perf-72cd1c40533b3882.yaml
  releasenotes/notes/primitive-interface-408b91ed338a5bc4.yaml
  releasenotes/notes/pulse-round-a014390e414c79c8.yaml
  releasenotes/notes/qasm3-fix-basis-gates-c96a0b357dfdcb47.yaml
  releasenotes/notes/qiskit-toqm-41bd0f3b6760df6f.yaml
  releasenotes/notes/quantum_shannon_decomp-facaa362a3ca8ba3.yaml
  releasenotes/notes/remove-basebackend-7beac0abd17144fe.yaml
  releasenotes/notes/remove-basicaer-shot-limit-b7cd4e6f6739885c.yaml
  releasenotes/notes/remove-dagnode-deprecations-30703a2156d52b8a.yaml
  releasenotes/notes/remove-deprecate-calsses-methods-7bd69606cc4ad61f.yaml
  releasenotes/notes/remove-deprecated-optimizer-methods-d580a07112ccaa2d.yaml
  releasenotes/notes/result-fix-e4eaa021f49b5f99.yaml
  releasenotes/notes/sabreswap-fix-condition-593f36e855f9064c.yaml
  releasenotes/notes/sabreswap-loop-230ef99e61358105.yaml
  releasenotes/notes/statevector-enable-iter-4652d7ce87f4d459.yaml
  releasenotes/notes/time-evo-framework-9d58827bdbbebd62.yaml
  releasenotes/notes/ucr-gates-qpy-b8f6fb1e34fae258.yaml
  releasenotes/notes/umda-optimizer-9ddcda3d25cd8d9a.yaml
  releasenotes/notes/upgrade-qpy-schedule-f28f6a48a3abb4de.yaml
  releasenotes/notes/xxplusyy-doc-c6ddcc45044dcdcd.yaml
Labels: automerge, Changelog: None

#8209 Deprecated `QiskitIndexError` removed
  qiskit/exceptions.py
  releasenotes/notes/remove_QiskitIndexError-098fa04f0afe440b.yaml
Labels: Changelog: Removal, automerge

#8208 fixed docstring in `execute`
  qiskit/execute_function.py
Labels: stable backport potential, automerge, Changelog: None, Community PR

#8235 Move QPY version regex construction to import time
  qiskit/qpy/interface.py
Labels: stable backport potential, performance, automerge, Changelog: None, mod: qpy

#8234 Fix `UnitaryGate.qasm()` with unused qubits
  qiskit/extensions/unitary.py
  releasenotes/notes/fix-qasm2-identity-as-unitary-aa2feeb05707a597.yaml
  test/python/circuit/test_unitary.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#8137 Add shots option to primitives
  qiskit/primitives/estimator.py
  qiskit/primitives/sampler.py
  releasenotes/notes/primitive-shots-option-ed320872d048483e.yaml
  test/python/primitives/test_estimator.py
  test/python/primitives/test_sampler.py
Labels: Changelog: New Feature, automerge, mod: primitives

#8242 switched to `sphinx-design`
  docs/conf.py
  requirements-dev.txt
Labels: type: documentation, stable backport potential, automerge, Changelog: None, Community PR

#7823 Combine circuits with clbits onto those with none
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/compose-meas-no-meas-492ce91167d54154.yaml
  test/python/circuit/test_compose.py
Labels: Changelog: New Feature, automerge

#8199 Speed up pauli evolve clifford
  qiskit/quantum_info/operators/symplectic/base_pauli.py
  releasenotes/notes/improve-basepauli-evolve-clifford-d714b2eee475334b.yaml
Labels: performance, automerge, mod: quantum info

#8260 fix seed in qsd test
  test/python/quantum_info/test_synthesis.py
Labels: stable backport potential, automerge, Changelog: None
