Repository Qiskit/qiskit, pull requests merged in 2022-07, with the labels that each got.

#8210 Argument `epsilon` and `factr` of optimizers `L_BFGS_B` and `factr` of `P_BFGS` has been removed
  docs/conf.py
  qiskit/algorithms/optimizers/l_bfgs_b.py
  releasenotes/notes/remove_optimizers_L_BFGS_B_epsilon-03f997aff50c394c.yaml
Labels: Changelog: Removal, automerge, mod: algorithms

#8289 Remove stale note about pending QPY support for SymbolicPulse
  qiskit/pulse/library/symbolic_pulses.py
Labels: type: documentation, stable backport potential, automerge, Changelog: None, documentation

#8161 Fix the typo in the documentation of CU1Gate and CZGate
  qiskit/circuit/library/standard_gates/p.py
  qiskit/circuit/library/standard_gates/u1.py
  qiskit/circuit/library/standard_gates/z.py
Labels: type: documentation, automerge, Community PR

#8298 Fixed docstring in `Initialize`
  qiskit/extensions/quantum_initializer/initializer.py
Labels: stable backport potential, automerge, Changelog: None

#8307 Move compose_u3 into Rust
  qiskit/__init__.py
  qiskit/transpiler/passes/optimization/optimize_1q_gates.py
  src/lib.rs
  src/optimize_1q_gates.rs
Labels: automerge, Changelog: None, Rust

#8016 Added argsort and sort method to SparsePauliOp
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
  releasenotes/notes/0.21/add-sparsepauliop-methods-00a7e6cc7055e1d0.yaml
  test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
Labels: Changelog: New Feature, automerge, mod: quantum info, QAMP, Community PR

#8320 Move release note in wrong location and add script to block this
  .azure/lint-linux.yml
  Makefile
  releasenotes/notes/0.21/remove-hard-time-limit-vf2-be83830ecc71f72c.yaml
  tools/find_stray_release_notes.py
  tox.ini
Labels: stable backport potential, automerge, Changelog: None

#8173 Add wire_order option to all circuit drawers to allow defining the order of the wires
  qiskit/circuit/quantumcircuit.py
  qiskit/visualization/circuit_visualization.py
  qiskit/visualization/latex.py
  qiskit/visualization/matplotlib.py
  qiskit/visualization/text.py
  qiskit/visualization/utils.py
  releasenotes/notes/add-wire-order-to-drawers-657cb54e365c621a.yaml
  test/ipynb/mpl/circuit/references/wire_order.png
  test/ipynb/mpl/circuit/test_circuit_matplotlib_drawer.py
  test/python/visualization/references/test_latex_wire_order.tex
  test/python/visualization/test_circuit_drawer.py
  test/python/visualization/test_circuit_latex.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: Changelog: New Feature, automerge, unitaryhack-accepted, Community PR

#8346 Fix pairwise entanglement in `NLocal` circuits
  qiskit/circuit/library/n_local/n_local.py
  releasenotes/notes/fix-zzmap-pairwise-5653395849fec454.yaml
  test/python/circuit/library/test_pauli_feature_map.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#8345 Tensored fitter
  qiskit/utils/mitigation/fitters.py
  qiskit/utils/quantum_instance.py
  releasenotes/notes/tensored-subset-fitter-bd28e6e6ec5bdaae.yaml
  test/python/algorithms/test_measure_error_mitigation.py
Labels: Changelog: New Feature

#8366 Fix lint failure in qiskit/extensions/unitary.py
  qiskit/extensions/unitary.py
Labels: type: qa, priority: high, Changelog: None

#8381 Fix `Optimizer` reconstruction from `settings`
  qiskit/algorithms/optimizers/scipy_optimizer.py
  releasenotes/notes/fix-optimizer-settings-881585bfa8130cb7.yaml
  test/python/algorithms/optimizers/test_optimizers.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#8384 Fix `EvolvedOp.to_instruction`
  qiskit/opflow/evolutions/evolved_op.py
  releasenotes/notes/fix-evolvedop-to-instruction-c90c4f1aa6b4232a.yaml
  test/python/opflow/test_evolution.py
Labels: stable backport potential, Changelog: Bugfix, automerge, mod: opflow

#8370 Added links from gate classes' circuit library pages to their corresponding QuantumCircuit methods
  qiskit/circuit/barrier.py
  qiskit/circuit/library/generalized_gates/pauli.py
  qiskit/circuit/library/generalized_gates/rv.py
  qiskit/circuit/library/standard_gates/dcx.py
  qiskit/circuit/library/standard_gates/ecr.py
  qiskit/circuit/library/standard_gates/h.py
  qiskit/circuit/library/standard_gates/i.py
  qiskit/circuit/library/standard_gates/iswap.py
  qiskit/circuit/library/standard_gates/p.py
  qiskit/circuit/library/standard_gates/r.py
  qiskit/circuit/library/standard_gates/rx.py
  qiskit/circuit/library/standard_gates/rxx.py
  qiskit/circuit/library/standard_gates/ry.py
  qiskit/circuit/library/standard_gates/ryy.py
  qiskit/circuit/library/standard_gates/rz.py
  qiskit/circuit/library/standard_gates/rzx.py
  qiskit/circuit/library/standard_gates/rzz.py
  qiskit/circuit/library/standard_gates/s.py
  qiskit/circuit/library/standard_gates/swap.py
  qiskit/circuit/library/standard_gates/sx.py
  qiskit/circuit/library/standard_gates/t.py
  qiskit/circuit/library/standard_gates/u.py
  qiskit/circuit/library/standard_gates/x.py
  qiskit/circuit/library/standard_gates/y.py
  qiskit/circuit/library/standard_gates/z.py
Labels: Changelog: None, documentation, Intern PR

#8392 Sphinx 5.1 breaks doc building
  requirements-dev.txt
Labels: type: qa, automerge, Changelog: None

#8288 Fix handling of numpy arrays for indices in marginal_distribution
  qiskit/result/utils.py
  releasenotes/notes/fix-numpy-indices-marginal-dist-45889e49ba337d84.yaml
  test/python/result/test_counts.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#8393 Add explanatory reference to ``PiecewiseChebychev``
  qiskit/algorithms/linear_solvers/hhl.py
  qiskit/circuit/library/arithmetic/piecewise_chebyshev.py
  qiskit/circuit/library/arithmetic/piecewise_polynomial_pauli_rotations.py
Labels: stable backport potential, automerge, Changelog: None, documentation

#8166 Fixes #7078: Change prefix of MemorySlot channel in Qasm Instructions
  qiskit/pulse/channels.py
  qiskit/pulse/instructions/frequency.py
  qiskit/pulse/instructions/phase.py
  qiskit/pulse/instructions/play.py
  qiskit/pulse/transforms/canonicalization.py
  releasenotes/notes/introduce-classical-io-channel-0a616e6ca75b7687.yaml
  test/python/pulse/test_channels.py
  test/python/pulse/test_instructions.py
  test/python/pulse/test_transforms.py
Labels: automerge, mod: pulse, Community PR

#8391 Added U1, U2 and U3 deprecation warnings into Circuit Library
  qiskit/circuit/library/standard_gates/u1.py
  qiskit/circuit/library/standard_gates/u2.py
  qiskit/circuit/library/standard_gates/u3.py
Labels: automerge, Changelog: None, documentation

#8405 Fix converting `VectorStateFn` to a `CircuitStateFn`
  qiskit/opflow/state_fns/circuit_state_fn.py
  releasenotes/notes/fix-opflow-vector-to-circuit-fn-02cb3424269fa733.yaml
  test/python/opflow/test_state_op_meas_evals.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#8398 Prepare 0.21.1 release
  Cargo.lock
  Cargo.toml
  docs/conf.py
  qiskit/VERSION.txt
  releasenotes/notes/0.21/release-0.21.0-4a6c079c6301bde6.yaml
  releasenotes/notes/0.21/remove-hard-time-limit-vf2-be83830ecc71f72c.yaml
  releasenotes/notes/decompose-fix-993f7242eaa69407.yaml
  releasenotes/notes/fix-pulse-limit_amplitude-72b8b501710fe3aa.yaml
  releasenotes/notes/fix-zzmap-pairwise-5653395849fec454.yaml
  releasenotes/notes/global-phase-ucgate-cd61355e314a3e64.yaml
  setup.py
Labels: automerge, Changelog: None

#8407 Improve the performance of assemble when parameter_binds is a list of empty dicts
  qiskit/compiler/assembler.py
Labels: stable backport potential, performance, automerge, Changelog: None

#8416 Remove upper cap on Sphinx version (undoes #8392)
  requirements-dev.txt
Labels: stable backport potential, automerge, Changelog: None

#8321 Fix MPL and LaTeX circuit drawer when `idle_wires=False` and there are barriers
  qiskit/visualization/latex.py
  qiskit/visualization/matplotlib.py
  releasenotes/notes/fix-idle-wires-display-de0ecc60d4000ca0.yaml
  test/ipynb/mpl/circuit/references/idle_wires_barrier.png
  test/ipynb/mpl/circuit/test_circuit_matplotlib_drawer.py
  test/python/visualization/references/test_latex_idle_wires_barrier.tex
  test/python/visualization/test_circuit_latex.py
Labels: Changelog: Bugfix, automerge, Community PR

#8426 Fix compatibility with Scipy 1.9.0
  qiskit/algorithms/optimizers/scipy_optimizer.py
  qiskit/test/base.py
Labels: type: qa, priority: high, stable backport potential, Changelog: None
