Repository Qiskit/qiskit, pull requests merged in 2022-11, with the labels that each got.

#9045 Set Rust edition to 2021
  Cargo.lock
  Cargo.toml
Labels: automerge, Changelog: None, Rust

#9042 Use TOQM routing staged pass manager.
  qiskit/compiler/transpiler.py
  qiskit/transpiler/preset_passmanagers/common.py
  qiskit/transpiler/preset_passmanagers/level0.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  releasenotes/notes/toqm-extra-0.1.0-4fedfa1ff0fedfa0.yaml
  requirements-dev.txt
  setup.py
Labels: Changelog: API Change, automerge

#9046 Prepare 0.22.1 release
  Cargo.lock
  Cargo.toml
  docs/conf.py
  qiskit/VERSION.txt
  releasenotes/notes/fix-barrier-before-final-measurements-loose-1849282c11fc5eb0.yaml
  releasenotes/notes/fix-clbit-handling-stochasticswap-controlflow-fbb9d8fab5040643.yaml
  releasenotes/notes/fix-global-inst-qarg-method-target-a9188e172ea7f325.yaml
  releasenotes/notes/fix-hinton-bug-1141a297050f55bb.yaml
  releasenotes/notes/fix-pauli-basis-dep-27c0a4506ad38d2c.yaml
  releasenotes/notes/fix-sparse-pauli-real-63c31d87801671b1.yaml
  releasenotes/notes/fix-vf2-layout-no-noise-22261601684710c3.yaml
  releasenotes/notes/fix-vqd-kgt2-1ed95de3e32102c1.yaml
  releasenotes/notes/prepare-0.22.1-dec5623f902c4e7d.yaml
  setup.py
Labels: automerge, Changelog: None

#8962 Remove verify_parallel_map script
  .azure/test-linux.yml
  .azure/test-macos.yml
  .azure/test-windows.yml
  .github/workflows/coverage.yml
  test/python/compiler/test_transpiler.py
  tools/verify_parallel_map.py
  tox.ini
Labels: type: qa, automerge, Changelog: None

#7333 Make TwoQubitWeylDecomposition pickle-able
  qiskit/quantum_info/synthesis/two_qubit_decompose.py
  releasenotes/notes/fix-twoqubit-pickle-8628047aa396919a.yaml
  releasenotes/notes/pickle_weyl-34e16e3aab2f7133.yaml
  test/python/quantum_info/test_synthesis.py
Labels: Changelog: Bugfix, automerge

#9051 Add implicit iteration to CouplingMap
  qiskit/transpiler/coupling.py
  releasenotes/notes/iterable-couplingmap-b8f0cbb1b34a2005.yaml
  test/python/transpiler/test_coupling.py
Labels: Changelog: New Feature, automerge

#9058 Fix incorrect graph construction in VF2PostLayout
  qiskit/transpiler/passes/layout/vf2_post_layout.py
  releasenotes/notes/fix-vf2post-regression-d4b057ea02ce00d3.yaml
Labels: stable backport potential, Changelog: Bugfix, automerge

#9057 Remove qiskit-toqm tests and requirements-dev.txt entry
  requirements-dev.txt
  test/python/transpiler/test_preset_passmanagers.py
Labels: stable backport potential, automerge, Changelog: None

#8980 Remove deprecated methods from QuantumCircuit
  examples/python/rippleadd.py
  qiskit/circuit/quantumcircuit.py
  qiskit/test/base.py
  qiskit/transpiler/synthesis/graysynth.py
  releasenotes/notes/remove-deprecated-circuit-methods-3e4eb27c4709ba12.yaml
  test/python/circuit/test_calibrations.py
  test/python/circuit/test_circuit_multi_registers.py
  test/python/circuit/test_circuit_operations.py
  test/python/circuit/test_extensions_standard.py
  test/python/circuit/test_initializer.py
  test/python/circuit/test_parameters.py
  test/python/transpiler/test_basis_translator.py
  test/python/transpiler/test_collect_multiq_blocks.py
  test/python/transpiler/test_optimize_1q_decomposition.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: Changelog: Removal, automerge

#9064 Split out NLayout rust class into standalone Python module
  qiskit/__init__.py
  qiskit/transpiler/passes/routing/sabre_swap.py
  qiskit/transpiler/passes/routing/stochastic_swap.py
  src/lib.rs
  src/nlayout.rs
  src/stochastic_swap.rs
Labels: automerge, Changelog: None, Rust

#9063 Avoid deepcopy in pulse parser
  qiskit/pulse/parser.py
  releasenotes/notes/remove-pulse-deepcopy-9a19aa7f6452248b.yaml
Labels: stable backport potential, Changelog: Bugfix, automerge

#9035 Remove deprecated networkx dag converter functions
  .azure/tutorials-linux.yml
  qiskit/dagcircuit/dagcircuit.py
  qiskit/dagcircuit/dagdependency.py
  releasenotes/notes/remove-networkx-converters-0a7eccf6fa847975.yaml
  requirements-dev.txt
  test/python/dagcircuit/test_dagcircuit.py
Labels: Changelog: Removal, automerge

#9028 Add support for Python 3.11
  .azure/test-linux.yml
  .azure/wheels.yml
  .github/workflows/wheels.yml
  azure-pipelines.yml
  pyproject.toml
  qiskit/pulse/instruction_schedule_map.py
  requirements-dev.txt
  setup.py
  test/python/pulse/test_instruction_schedule_map.py
  tox.ini
Labels: stable backport potential, Changelog: New Feature, automerge

#9069 Fix Backend primitive classes for BackendV1 with no max_experiments
  qiskit/primitives/backend_estimator.py
  releasenotes/notes/fix-backend-primitive-no-max-experiments-e2ca41ec61de353e.yaml
  test/python/primitives/test_backend_estimator.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#9059 Prepare Qiskit Terra 0.22.2
  Cargo.lock
  Cargo.toml
  docs/conf.py
  qiskit/VERSION.txt
  releasenotes/notes/prepare-0.22.2-cd8a0fa538c623b9.yaml
Labels: automerge, Changelog: None

#9089 add qubits and clbits args to QuantumCircuit.from_instructions
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_circuit_operations.py
Labels: automerge, Changelog: None

#9088 Fix NumPy(Minimum)EigensolverResult typehints
  qiskit/algorithms/eigensolvers/numpy_eigensolver.py
  qiskit/algorithms/minimum_eigensolvers/numpy_minimum_eigensolver.py
  qiskit/algorithms/minimum_eigensolvers/sampling_vqe.py
  test/python/algorithms/minimum_eigensolvers/test_qaoa.py
Labels: automerge, mod: algorithms, Changelog: None

#9105 Pin jupyter-core to < 5.0.0
  constraints.txt
Labels: type: qa, automerge, Changelog: None

#9012 Calculate relative, not absolute, scores in SabreSwap
  qiskit/transpiler/passes/routing/sabre_swap.py
  src/sabre_swap/layer.rs
  src/sabre_swap/mod.rs
  src/sabre_swap/sabre_dag.rs
  test/python/transpiler/test_sabre_swap.py
Labels: priority: high, performance, Changelog: New Feature, automerge, Rust, mod: transpiler

#9083 Stabilising test_squ
  qiskit/extensions/quantum_initializer/squ.py
  test/python/circuit/test_squ.py
Labels: type: qa, stable backport potential, automerge, Changelog: None

#9078 🐛 fix deprecated `Loader.load_module()`
  qiskit/namespace.py
Labels: stable backport potential, automerge, Changelog: None, Community PR

#9113 Fixed sign bug in docs in LinCombEstimatorGradient.
  qiskit/algorithms/gradients/lin_comb_estimator_gradient.py
  releasenotes/notes/fix-complex-gradient-sign-25f153b5a53ae259.yaml
  test/python/algorithms/gradients/test_estimator_gradient.py
Labels: documentation, stable backport potential, Changelog: Bugfix, mod: algorithms

#9117 Use float-epsilon calculation in Sabre best scores
  src/sabre_swap/mod.rs
Labels: Changelog: Bugfix, automerge, Rust, mod: transpiler

#9127 Fix random seed initialization between runs in SabreSwap
  qiskit/transpiler/passes/routing/sabre_swap.py
  releasenotes/notes/fix-sabre-swap-random-seed-dcf3dace63042791.yaml
  src/sabre_swap/mod.rs
Labels: stable backport potential, Changelog: Bugfix, automerge, Rust, mod: transpiler

#9130 Add debug prints to lint CI job
  .azure/lint-linux.yml
Labels: type: qa, Changelog: None

#9081 Removed NLocal inital_state that is not a QuantumCircuit
  qiskit/circuit/library/n_local/n_local.py
  releasenotes/notes/initial_state-8e20b04fc2ec2f4b.yaml
Labels: Changelog: Removal, automerge

#9144 Reinstate `pulse.Instruction.draw`
  qiskit/pulse/instructions/instruction.py
  releasenotes/notes/reinstate-pulse-instruction-draw-7bf4bbabaa1f1862.yaml
Labels: stable backport potential, Changelog: Bugfix, automerge, mod: visualization

#9103 Fix the bug primitives cannot handle circuits with ndarray parameters
  qiskit/primitives/utils.py
  releasenotes/notes/fix-primitives-numpy-parameters-1589d997864dfb37.yaml
  test/python/primitives/test_sampler.py
Labels: stable backport potential, Changelog: Bugfix, automerge, mod: primitives

#9076 Fix serialization of primitives
  qiskit/primitives/backend_estimator.py
  qiskit/primitives/backend_sampler.py
  releasenotes/notes/fix-serialization-primitives-c1e44a37cfe7a32a.yaml
  test/python/primitives/test_estimator.py
Labels: stable backport potential, Changelog: Bugfix, automerge, mod: primitives

#9131 Remove deprecated redirects from visualization
  qiskit/visualization/__init__.py
  releasenotes/notes/remove-visualization-optionals-e4c3ed415bc1bbbe.yaml
Labels: Changelog: Removal, automerge, mod: visualization

#9104 Add gradient methods to FinDiffGradients
  qiskit/algorithms/gradients/finite_diff_estimator_gradient.py
  qiskit/algorithms/gradients/finite_diff_sampler_gradient.py
  releasenotes/notes/gradient-methods-b2ec34916b83c17b.yaml
  test/python/algorithms/gradients/test_estimator_gradient.py
  test/python/algorithms/gradients/test_sampler_gradient.py
Labels: Changelog: New Feature, automerge, mod: algorithms

#9121 Improve performance of _observable_key in Primitives
  qiskit/primitives/utils.py
Labels: automerge, Changelog: None, mod: primitives

#9082 Adding permutation synthesis algorithm for LNN
  qiskit/circuit/library/generalized_gates/permutation.py
  qiskit/synthesis/__init__.py
  qiskit/synthesis/permutation/__init__.py
  qiskit/synthesis/permutation/permutation_lnn.py
  qiskit/synthesis/permutation/permutation_utils.py
  releasenotes/notes/add-permutation-lnn-synthesis-46dca864cebe0af3.yaml
  test/python/circuit/library/test_permutation.py
  test/python/synthesis/test_permutation_synthesis.py
Labels: Changelog: New Feature, automerge, synthesis

#8917 Update Optimize1qGatesDecomposition to be Target aware
  qiskit/transpiler/passes/optimization/optimize_1q_commutation.py
  qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  qiskit/transpiler/target.py
  releasenotes/notes/target-aware-optimize-1q-decomposition-cb9bb4651607b639.yaml
  test/python/compiler/test_transpiler.py
  test/python/transpiler/test_optimize_1q_decomposition.py
Labels: Changelog: New Feature, automerge, mod: transpiler

#9161 validation/dd timing
  qiskit/transpiler/passes/scheduling/padding/dynamical_decoupling.py
Labels: automerge

#9142 fix: overwrite `AdaptVQE.supports_aux_operators`
  qiskit/algorithms/minimum_eigensolvers/adapt_vqe.py
  releasenotes/notes/adapt-vqe-supports-aux-operators-1383103839a338c6.yaml
  test/python/algorithms/minimum_eigensolvers/test_adapt_vqe.py
Labels: stable backport potential, Changelog: Bugfix, automerge, mod: algorithms

#9165 Update `HAS_NETWORKX` documentation
  qiskit/utils/optionals.py
Labels: documentation, automerge, Changelog: None

#8250 Increase Accuracy of OpenQASM 2.0 Dump
  qiskit/circuit/instruction.py
  qiskit/circuit/tools/pi_check.py
  releasenotes/notes/change-qasm-float-output-d69d0c2896f8ecbb.yaml
  test/python/circuit/test_circuit_qasm.py
  test/python/circuit/test_tools.py
Labels: Changelog: New Feature, automerge, qasm, Community PR

#9162 Switch from retworkx to rustworkx package
  Cargo.lock
  Cargo.toml
  qiskit/circuit/equivalence.py
  qiskit/circuit/library/graph_state.py
  qiskit/dagcircuit/dagcircuit.py
  qiskit/dagcircuit/dagdependency.py
  qiskit/opflow/converters/abelian_grouper.py
  qiskit/pulse/schedule.py
  qiskit/pulse/transforms/dag.py
  qiskit/quantum_info/operators/symplectic/pauli_list.py
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
  qiskit/transpiler/coupling.py
  qiskit/transpiler/passes/basis/basis_translator.py
  qiskit/transpiler/passes/layout/dense_layout.py
  qiskit/transpiler/passes/layout/noise_adaptive_layout.py
  qiskit/transpiler/passes/layout/vf2_layout.py
  qiskit/transpiler/passes/layout/vf2_post_layout.py
  qiskit/transpiler/passes/layout/vf2_utils.py
  qiskit/transpiler/passes/routing/algorithms/token_swapper.py
  qiskit/transpiler/passes/routing/sabre_swap.py
  qiskit/transpiler/preset_passmanagers/common.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  qiskit/transpiler/target.py
  qiskit/visualization/dag_visualization.py
  qiskit/visualization/gate_map.py
  releasenotes/notes/rustworkx-not-retworkx-b7c4da600df58701.yaml
  requirements.txt
  src/sabre_swap/layer.rs
  src/sabre_swap/mod.rs
  src/sabre_swap/neighbor_table.rs
  src/sabre_swap/sabre_dag.rs
  test/python/algorithms/minimum_eigensolvers/test_qaoa.py
  test/python/algorithms/test_measure_error_mitigation.py
  test/python/algorithms/test_qaoa.py
  test/python/dagcircuit/test_dagcircuit.py
  test/python/dagcircuit/test_dagdependency.py
  test/python/transpiler/test_token_swapper.py
  test/python/transpiler/test_vf2_layout.py
  test/python/transpiler/test_vf2_post_layout.py
Labels: Changelog: API Change, automerge

#9026 Improve performance of VF2 scoring and add support for scoring passes
  Cargo.lock
  Cargo.toml
  qiskit/__init__.py
  qiskit/transpiler/passes/layout/vf2_layout.py
  qiskit/transpiler/passes/layout/vf2_post_layout.py
  qiskit/transpiler/passes/layout/vf2_utils.py
  releasenotes/notes/vf2_custom_score_analysis-abb191d56c0c1578.yaml
  src/error_map.rs
  src/lib.rs
  src/vf2_layout.rs
  test/python/transpiler/test_vf2_layout.py
  test/python/transpiler/test_vf2_post_layout.py
Labels: performance, Changelog: New Feature, automerge, Rust

#8252 Fix mypy errors (dagcircuit)
  qiskit/dagcircuit/dagcircuit.py
  qiskit/dagcircuit/dagnode.py
Labels: automerge, Changelog: None, Community PR

#9171 Remove reference to Travis from README
  README.md
Labels: automerge, Changelog: None

#9079 Some formatting issues in circuit library documentation
  qiskit/circuit/library/n_local/n_local.py
  qiskit/circuit/library/n_local/two_local.py
  qiskit/circuit/quantumcircuit.py
Labels: documentation, automerge, Changelog: None

#9172 Unpin jaxlib Python-version constraints
  requirements-dev.txt
Labels: type: qa, automerge, Changelog: None

#9179 Use numpy.linalg.det instead of scipy's function
  qiskit/quantum_info/synthesis/one_qubit_decompose.py
  qiskit/quantum_info/synthesis/two_qubit_decompose.py
  test/python/circuit/test_circuit_qasm.py
  test/python/transpiler/test_dynamical_decoupling.py
Labels: performance, automerge, mod: quantum info, Changelog: None

#8811 Mark slowest tests as slow and add nightly slow test job
  .github/workflows/slow.yml
  test/python/algorithms/test_backendv1.py
  test/python/algorithms/test_backendv2.py
  test/python/algorithms/test_linear_solvers.py
  test/python/algorithms/test_phase_estimator.py
  test/python/algorithms/test_shor.py
  test/python/algorithms/test_vqd.py
  tox.ini
Labels: type: qa, automerge, Changelog: None

#9182 fix: QNSPSA with max_evals_grouped exceeding 1
  qiskit/algorithms/optimizers/qnspsa.py
  releasenotes/notes/fix-qnspsa-max-evals-grouped-52eb462fa6c82079.yaml
  test/python/algorithms/optimizers/test_spsa.py
Labels: bug, stable backport potential, automerge, mod: algorithms

#9115 Disable cron CI on old stable branch
  azure-pipelines.yml
Labels: type: qa, Changelog: None

#9193 Prepare 0.22.3
  Cargo.lock
  Cargo.toml
  docs/conf.py
  qiskit/VERSION.txt
  releasenotes/notes/fix-qnspsa-max-evals-grouped-52eb462fa6c82079.yaml
  releasenotes/notes/prepare-0.22.3-cdc2d5c29ec5555e.yaml
  releasenotes/notes/reinstate-pulse-instruction-draw-7bf4bbabaa1f1862.yaml
  setup.py
Labels: automerge, Changelog: None

#9192 Fix slow unit tests
  test/python/algorithms/optimizers/test_optimizer_aqgd.py
  test/python/algorithms/test_shor.py
Labels: type: qa, automerge, Changelog: None

#9138 Optimize QuantumCircuit.append
  qiskit/circuit/quantumcircuit.py
Labels: automerge, Changelog: None, Community PR

#9181 Copyright year in the documentation footer
  docs/conf.py
  qiskit/test/_canonical.py
Labels: documentation, automerge, Changelog: None

#9184 Remove deprecated functions from `ParameterView`
  qiskit/circuit/parametertable.py
  releasenotes/notes/remove-deprecated-parameterview-cc08100049605b73.yaml
Labels: Changelog: Removal, automerge

#9155 Fix shots argument of local_readout_mitigator
  qiskit/result/mitigation/correlated_readout_mitigator.py
  qiskit/result/mitigation/local_readout_mitigator.py
  qiskit/result/mitigation/utils.py
  releasenotes/notes/fix_shots_passing_local_readout_mitigator-603514a4e0d22dc5.yaml
  test/python/result/test_mitigators.py
Labels: Changelog: Bugfix, automerge, Community PR

#9200 Fix pickle of Rust `ErrorMap` struct
  src/error_map.rs
  test/python/transpiler/test_vf2_layout.py
Labels: automerge, Changelog: None, Rust, mod: transpiler

#9098 Adding linear synthesis algorithm for LNN
  qiskit/synthesis/__init__.py
  qiskit/synthesis/linear/__init__.py
  qiskit/synthesis/linear/graysynth.py
  qiskit/synthesis/linear/linear_depth_lnn.py
  qiskit/synthesis/linear/linear_matrix_utils.py
  releasenotes/notes/add-linear-synthesis-lnn-depth-5n-36c1aeda02b8bc6f.yaml
  test/python/synthesis/test_linear_synthesis.py
Labels: Changelog: New Feature, automerge, synthesis
