Repository Qiskit/qiskit, pull requests merged in 2023-11, with the labels that each got.

#11051 Deprecate legacy primitive attributes in base classes
  qiskit/algorithms/minimum_eigensolvers/diagonal_estimator.py
  qiskit/primitives/backend_estimator.py
  qiskit/primitives/backend_sampler.py
  qiskit/primitives/base/base_estimator.py
  qiskit/primitives/base/base_sampler.py
  qiskit/primitives/estimator.py
  qiskit/primitives/sampler.py
  releasenotes/notes/dep-primitives-attr-6b4ec9fde34c42e8.yaml
Labels: Changelog: Deprecation, mod: primitives

#11052 Remove validation methods from primitive base classes
  qiskit/primitives/base/base_estimator.py
  qiskit/primitives/base/base_primitive.py
  qiskit/primitives/base/base_sampler.py
  qiskit/primitives/base/validation.py
  test/python/primitives/test_estimator.py
  test/python/primitives/test_primitive.py
Labels: Changelog: Deprecation, mod: primitives

#11055 Deprecate `PauliList` estimator observables
  qiskit/primitives/utils.py
  releasenotes/notes/dep-estimator-paulilist-ef2bb2865b66f012.yaml
  test/python/primitives/test_estimator.py
Labels: Changelog: Deprecation, mod: primitives

#11176 Copy-in rather than copy-out in transpiler
  qiskit/transpiler/passmanager.py
Labels: stable backport potential, Changelog: None, mod: transpiler

#11181 Fix build ordering of `BlueprintCircuit._append`
  qiskit/circuit/library/blueprintcircuit.py
  releasenotes/notes/fix-blueprint-circuit-_append-b4d6c9c41db860f5.yaml
  test/python/circuit/library/test_blueprintcircuit.py
Labels: stable backport potential, Changelog: Bugfix, mod: circuit

#11178 Base pass manager bug fixes
  qiskit/passmanager/base_tasks.py
  qiskit/passmanager/flow_controllers.py
  qiskit/passmanager/passmanager.py
  qiskit/transpiler/basepasses.py
  test/python/passmanager/__init__.py
  test/python/passmanager/test_generic_pass.py
  test/python/passmanager/test_passmanager.py
Labels: stable backport potential, Changelog: None

#11184 Restore accidently deleted scheduling passes
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/scheduling/__init__.py
  qiskit/transpiler/passes/scheduling/alap.py
  qiskit/transpiler/passes/scheduling/alignments/__init__.py
  qiskit/transpiler/passes/scheduling/alignments/align_measures.py
  qiskit/transpiler/passes/scheduling/asap.py
  qiskit/transpiler/passes/scheduling/dynamical_decoupling.py
  releasenotes/notes/0.45/removed_deprecated_0.21-6c93f7bbc50ae40e.yaml
  test/python/transpiler/legacy_scheduling/test_instruction_alignments.py
  test/python/transpiler/legacy_scheduling/test_scheduling_pass.py
Labels: priority: high, Changelog: None

#11090 Improved Documentation and Error-Signaling of VF2PostLayout
  qiskit/transpiler/passes/layout/vf2_post_layout.py
  releasenotes/notes/vf2postlayout-no-better-solution-eb5ced3c8a60ea23.yaml
  test/python/transpiler/test_vf2_post_layout.py
Labels: Changelog: New Feature, mod: transpiler

#11186 fixed the broken formatting
  docs/deprecation_policy.rst
Labels: documentation, stable backport potential, Changelog: None, Community PR

#11164 Formatting and typo issues in qiskit.transpiler.Target
  qiskit/transpiler/target.py
Labels: documentation, stable backport potential, Changelog: None

#11096 Fix circuit drawer returning qubit[register] names for input
  qiskit/transpiler/passes/layout/sabre_layout.py
  releasenotes/notes/fix-qreg-visualization-after-layout-42d3e643b923d8bc.yaml
  test/visual/mpl/circuit/references/qreg_names_after_layout.png
  test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py
Labels: stable backport potential, Changelog: Bugfix, Community PR

#11198 Use final_layout_index in BackendEstimator
  qiskit/primitives/backend_estimator.py
Labels: Changelog: None, mod: primitives

#11190 Expire deprecation on `qargs=None` in DAG appends
  qiskit/dagcircuit/dagcircuit.py
  releasenotes/notes/remove-dag-none-be220777dc246803.yaml
  test/python/dagcircuit/test_dagcircuit.py
Labels: Changelog: Removal

#10631 Removed 2pi wrapping for global phase parameter
  qiskit/transpiler/passes/scheduling/dynamical_decoupling.py
  qiskit/transpiler/passes/scheduling/padding/dynamical_decoupling.py
  releasenotes/notes/fix-param-global-phase-31547267f6124552.yaml
  test/python/transpiler/test_dynamical_decoupling.py
Labels: Changelog: Bugfix, Community PR, mod: transpiler

#11197 Replaced references to master with references to main in docs/maintainers_guide.rst
  docs/maintainers_guide.rst
Labels: documentation, stable backport potential, Changelog: None, Community PR

#11179 Allow barriers in overlap circuit inputs
  qiskit/circuit/library/overlap.py
  releasenotes/notes/overlap-circuit-barriers-63b9b1be9c1da100.yaml
  test/python/circuit/library/test_overlap.py
Labels: stable backport potential, Changelog: Bugfix, mod: circuit

#11210 Use InverseCancellation in opt level 1 instead of CXCancellation
  qiskit/transpiler/preset_passmanagers/builtin_plugins.py
Labels: Changelog: None, mod: transpiler

#11223 Remove namespace packaging hooks
  qiskit/__init__.py
  qiskit/providers/__init__.py
  releasenotes/notes/remove-namespace-hooks-995bdb7515a9fe35.yaml
Labels: Changelog: Removal

#11222 Fix asv installation configuration
  asv.conf.json
Labels: type: qa, Changelog: None

#11224 Collapse release notes for pre-releases
  docs/release_notes.rst
  releasenotes/config.yaml
Labels: documentation, Changelog: None

#11020 Relax CI constraint on `numpy<1.25`
  constraints.txt
Labels: stable backport potential, Changelog: None

#11232 Revert "Relax CI constraint on `numpy<1.25` (#11020)"
  constraints.txt
Labels: type: qa, Changelog: None

#11215 Pulse model - add PulseTarget, Port
  qiskit/pulse/__init__.py
  qiskit/pulse/model/__init__.py
  qiskit/pulse/model/mixed_frames.py
  qiskit/pulse/model/pulse_target.py
  test/python/pulse/test_mixed_frames.py
  test/python/pulse/test_pulse_targets.py
Labels: mod: pulse

#11170 Singletonized `Measure` and `Reset` instructions
  qiskit/circuit/measure.py
  qiskit/circuit/quantumcircuit.py
  qiskit/circuit/reset.py
  qiskit/qasm2/parse.py
  releasenotes/notes/singletonize-instructions-78723f68cd0ac03f.yaml
  test/python/circuit/test_singleton.py
Labels: performance, Changelog: New Feature, Community PR

#11163 small typos and spelling issues in passes docs
  qiskit/transpiler/passes/analysis/count_ops_longest_path.py
  qiskit/transpiler/passes/analysis/dag_longest_path.py
  qiskit/transpiler/passes/basis/unroll_3q_or_more.py
  qiskit/transpiler/passes/basis/unroll_custom_definitions.py
  qiskit/transpiler/passes/calibration/pulse_gate.py
  qiskit/transpiler/passes/layout/apply_layout.py
  qiskit/transpiler/passes/layout/dense_layout.py
  qiskit/transpiler/passes/layout/enlarge_with_ancilla.py
  qiskit/transpiler/passes/layout/full_ancilla_allocation.py
  qiskit/transpiler/passes/layout/layout_2q_distance.py
  qiskit/transpiler/passes/layout/sabre_layout.py
  qiskit/transpiler/passes/layout/vf2_layout.py
  qiskit/transpiler/passes/layout/vf2_post_layout.py
  qiskit/transpiler/passes/optimization/collect_multiqubit_blocks.py
  qiskit/transpiler/passes/optimization/commutation_analysis.py
  qiskit/transpiler/passes/optimization/commutative_cancellation.py
  qiskit/transpiler/passes/optimization/consolidate_blocks.py
  qiskit/transpiler/passes/optimization/crosstalk_adaptive_schedule.py
  qiskit/transpiler/passes/optimization/cx_cancellation.py
  qiskit/transpiler/passes/optimization/echo_rzx_weyl_decomposition.py
  qiskit/transpiler/passes/optimization/normalize_rx_angle.py
  qiskit/transpiler/passes/optimization/optimize_1q_commutation.py
  qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py
  qiskit/transpiler/passes/optimization/optimize_1q_gates.py
  qiskit/transpiler/passes/optimization/reset_after_measure_simplification.py
  qiskit/transpiler/passes/optimization/template_optimization.py
  qiskit/transpiler/passes/routing/basic_swap.py
  qiskit/transpiler/passes/routing/commuting_2q_gate_routing/commuting_2q_gate_router.py
  qiskit/transpiler/passes/routing/layout_transformation.py
  qiskit/transpiler/passes/routing/lookahead_swap.py
  qiskit/transpiler/passes/routing/stochastic_swap.py
  qiskit/transpiler/passes/scheduling/padding/dynamical_decoupling.py
  qiskit/transpiler/passes/scheduling/padding/pad_delay.py
  qiskit/transpiler/passes/scheduling/scheduling/asap.py
  qiskit/transpiler/passes/scheduling/scheduling/set_io_latency.py
  qiskit/transpiler/passes/scheduling/time_unit_conversion.py
  qiskit/transpiler/passes/utils/check_map.py
  qiskit/transpiler/passes/utils/dag_fixed_point.py
  qiskit/transpiler/passes/utils/error.py
  qiskit/transpiler/passes/utils/fixed_point.py
  qiskit/transpiler/passes/utils/minimum_point.py
  qiskit/transpiler/passes/utils/remove_final_measurements.py
  qiskit/transpiler/passes/utils/unroll_forloops.py
Labels: documentation, stable backport potential, Changelog: None

#11238 Docstring only: Fix math parsing error for Pauli docstring
  qiskit/quantum_info/operators/symplectic/pauli.py
Labels: documentation, stable backport potential, Changelog: None, Community PR

#11241 Add new transpiler exception class for too many qubits
  qiskit/compiler/transpiler.py
  qiskit/transpiler/__init__.py
  qiskit/transpiler/exceptions.py
  releasenotes/notes/new-exception-too-wide-3231c1df15952445.yaml
  test/python/compiler/test_transpiler.py
Labels: Changelog: New Feature

#11211 Speed up InverseCancellation when there's nothing to cancel
  qiskit/transpiler/passes/optimization/inverse_cancellation.py
  releasenotes/notes/fix-parameterized-self-inverse-7cb2d68b273640f8.yaml
  test/python/transpiler/test_inverse_cancellation.py
Labels: performance, Changelog: Bugfix, mod: transpiler

#11119 Ensure metapackage is installed during CI and tox
  .azure/lint-linux.yml
  .azure/test-linux.yml
  .azure/test-macos.yml
  .azure/test-windows.yml
  .github/workflows/coverage.yml
  .github/workflows/slow.yml
  tox.ini
Labels: type: qa, stable backport potential, Changelog: None

#11253 Remove `print` calls from test suite
  test/python/circuit/library/test_functional_pauli_rotations.py
  test/python/circuit/library/test_integer_comparator.py
  test/python/circuit/library/test_nlocal.py
  test/python/circuit/library/test_permutation.py
  test/python/circuit/library/test_piecewise_chebyshev.py
  test/python/circuit/library/test_weighted_adder.py
  test/python/circuit/test_piecewise_polynomial.py
  test/python/primitives/test_backend_sampler.py
  test/python/primitives/test_sampler.py
  test/python/quantum_info/operators/symplectic/test_clifford.py
Labels: type: qa, Changelog: None

#11251 Fix `Channel.__hash__` in multiprocessing contexts
  qiskit/pulse/channels.py
  qiskit/pulse/instructions/instruction.py
  qiskit/pulse/model/frames.py
  qiskit/pulse/model/mixed_frames.py
  qiskit/pulse/model/pulse_target.py
  releasenotes/notes/fix-pulse-channel-hash-549a8fb5d8738c4d.yaml
Labels: stable backport potential, Changelog: Bugfix, mod: pulse

#11041 Fixed Issue 11026: SparsePauliOp.apply_layout should do nothing if given None
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
  releasenotes/notes/allow-none-layout-for-sparse_pauli_op-212470d5b5b307a0.yaml
  test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
Labels: Changelog: New Feature, mod: quantum info, Community PR

#11175 Fix pickling of conditioned custom gates from OpenQASM 2 import
  qiskit/qasm2/parse.py
  releasenotes/notes/fix-qasm2-deepcopy-conditioned-gate-2fa75fee622c1fc0.yaml
  test/python/qasm2/test_structure.py
Labels: stable backport potential, Changelog: Bugfix, mod: qasm2

#11259 Fix phase in readme state
  README.md
Labels: documentation, stable backport potential, Changelog: None

#11272 Fix `QuantumCircuit.barrier` argument conversion
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/fix-circuit-barrier-c696eabae1dcc6c2.yaml
  test/python/circuit/test_circuit_operations.py
Labels: stable backport potential, Changelog: Bugfix, mod: circuit

#11206 Allow correct retrieval of circuit with initialize instruction from qpy file
  qiskit/qpy/binary_io/circuits.py
  releasenotes/notes/fix-qpy-statepreparation-retrieval-1feea5eb74db7f1e.yaml
  test/python/circuit/test_circuit_load_from_qpy.py
Labels: stable backport potential, Changelog: Bugfix, mod: qpy, Community PR

#11261 Fix issue with ScheduleBlock qpy serialization and use_symengine
  qiskit/qpy/binary_io/schedules.py
  releasenotes/notes/fix-schedule-qpy-use-symengine-05ae1dfab73e3ff8.yaml
  test/python/qpy/test_block_load_from_qpy.py
Labels: stable backport potential, Changelog: Bugfix, mod: qpy

#11277 Remove the discrete pulse library
  qiskit/pulse/library/__init__.py
  qiskit/pulse/library/discrete.py
  qiskit/pulse/library/parametric_pulses.py
  releasenotes/notes/deprecate-discrete-pulse-library-d2482407d7965972.yaml
  releasenotes/notes/remove-discrete-pulse-library-d7aa098a528161df.yaml
  test/python/pulse/test_discrete_pulses.py
  test/python/pulse/test_instruction_schedule_map.py
  test/python/pulse/test_pulse_lib.py
  test/python/pulse/test_schedule.py
Labels: Changelog: Removal, mod: pulse

#10827 Oxidize `QuantumCircuit._data` and intern `CircuitInstruction` args
  crates/accelerate/src/lib.rs
  crates/accelerate/src/quantum_circuit/circuit_data.rs
  crates/accelerate/src/quantum_circuit/circuit_instruction.rs
  crates/accelerate/src/quantum_circuit/intern_context.rs
  crates/accelerate/src/quantum_circuit/mod.rs
  crates/accelerate/src/quantum_circuit/py_ext.rs
  qiskit/__init__.py
  qiskit/circuit/controlflow/if_else.py
  qiskit/circuit/instructionset.py
  qiskit/circuit/library/blueprintcircuit.py
  qiskit/circuit/quantumcircuit.py
  qiskit/circuit/quantumcircuitdata.py
  qiskit/converters/circuit_to_instruction.py
  qiskit/opflow/gradients/circuit_gradients/lin_comb.py
  releasenotes/notes/bit-interning-35da0aaa76aa7fc5.yaml
  test/python/circuit/test_circuit_data.py
  test/python/circuit/test_circuit_operations.py
Labels: priority: high, performance, Changelog: New Feature, Rust

#11217 Combined contribute_to_qiskit.rst with contributing.md
  CONTRIBUTING.md
  docs/contributing_to_qiskit.rst
  docs/index.rst
Labels: documentation

#11279 Deprecate `ParametricPulse` (0.46)
  qiskit/pulse/library/parametric_pulses.py
  releasenotes/notes/deprecate-parametric-pulse-0a692c1fa6b46d7f.yaml
Labels: Changelog: Deprecation, mod: pulse

#10902 Update platform support and require symengine
  docs/getting_started.rst
  pyproject.toml
  qiskit/circuit/parameter.py
  qiskit/circuit/parameterexpression.py
  qiskit/pulse/library/symbolic_pulses.py
  qiskit/qpy/binary_io/schedules.py
  qiskit/qpy/binary_io/value.py
  qiskit/qpy/interface.py
  releasenotes/notes/platform-support-f7f693aaf5dec044.yaml
  requirements.txt
  test/python/circuit/test_circuit_load_from_qpy.py
  test/python/qpy/test_block_load_from_qpy.py
Labels: priority: high, Changelog: API Change

#11288 Improve "Custom Pass Managers" docs
  qiskit/transpiler/__init__.py
Labels: documentation, stable backport potential, Changelog: None

#11159 Fixed issue 11143 by removing deprecated code
  qiskit/visualization/state_visualization.py
  releasenotes/notes/fix_11143-d32a262538873a9d.yaml
  test/python/quantum_info/states/test_statevector.py
Labels: Changelog: Removal, Community PR

#10323 Add pass to filter ops and label inserted barriers
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/utils/__init__.py
  qiskit/transpiler/passes/utils/barrier_before_final_measurements.py
  qiskit/transpiler/passes/utils/filter_op_nodes.py
  qiskit/transpiler/preset_passmanagers/builtin_plugins.py
  qiskit/transpiler/preset_passmanagers/common.py
  releasenotes/notes/add-filter-op-nodes-aa024a0f1058e4b7.yaml
  test/python/compiler/test_transpiler.py
  test/python/transpiler/test_filter_op_nodes.py
  test/python/transpiler/test_sabre_layout.py
  test/python/visualization/references/pass_manager_standard.dot
  test/python/visualization/references/pass_manager_style.dot
Labels: Changelog: New Feature

#11297 Fix clippy warnings on newer rust versions
  crates/accelerate/src/quantum_circuit/circuit_data.rs
Labels: Changelog: None, Rust

#11299 improve inverse cancellation docstring
  qiskit/transpiler/passes/optimization/inverse_cancellation.py
Labels: documentation, stable backport potential, Changelog: None

#11284 improve stagedpassmanager docstring
  qiskit/transpiler/passmanager.py
Labels: documentation, stable backport potential, Changelog: None

#11295 Avoid routing 2q barriers in SabreSwap
  crates/accelerate/src/sabre_swap/mod.rs
  crates/accelerate/src/sabre_swap/sabre_dag.rs
  qiskit/transpiler/passes/routing/sabre_swap.py
  releasenotes/notes/sabre-no-route-barrier-bc82fecb65d3ab9a.yaml
  test/python/transpiler/test_sabre_layout.py
  test/python/transpiler/test_sabre_swap.py
Labels: Changelog: Bugfix, Rust

#11307 Fix flakiness in pulse-optimal `UnitarySynthesis` test
  test/python/transpiler/test_unitary_synthesis.py
Labels: type: qa, stable backport potential, Changelog: None

#11306 Remove deprecated `IntegerComparator.num_ancilla_qubits`
  qiskit/circuit/library/arithmetic/integer_comparator.py
  releasenotes/notes/5079_IntegerComparator_num_ancilla_qubits-bd1cff3366c345ae.yaml
Labels: Changelog: Removal

#11262 Add support for Python 3.12
  .github/workflows/wheels.yml
  azure-pipelines.yml
  constraints.txt
  qiskit/providers/fake_provider/fake_backend_v2.py
  qiskit/providers/fake_provider/fake_mumbai_v2.py
  qiskit/transpiler/target.py
  qiskit_pkg/setup.py
  releasenotes/notes/add-py312-support-7077426af34ac5da.yaml
  requirements.txt
  setup.py
  test/python/providers/test_fake_backends.py
  tox.ini
Labels: stable backport potential, Changelog: New Feature

#11305 Remove __qiskit_version__ (deprecated in Qiskit Terra 0.25)
  qiskit/__init__.py
  qiskit/version.py
  releasenotes/notes/__qiskit_version__11305-bcf134513641462b.yaml
  test/python/test_version.py
Labels: Changelog: Removal

#11267 Pin rust compiler version to 1.73 for wheel builds
  .github/workflows/wheels.yml
  pyproject.toml
Labels: type: qa, Changelog: None, Rust

#11314 Relax CI pin on Numpy < 1.25
  constraints.txt
Labels: type: qa, stable backport potential, Changelog: None

#11312 Cleaning up some allow_DeprecationWarning
  qiskit/test/base.py
Labels: type: qa, Changelog: None

#11313 Relax CI pin on Aer <0.13
  constraints.txt
Labels: type: qa, stable backport potential, Changelog: None

#11252 Remove deprecated `algorithm_globals` and `validation` utils.
  qiskit/utils/__init__.py
  qiskit/utils/algorithm_globals.py
  qiskit/utils/validation.py
  releasenotes/notes/remove-algorithm-utils-707648b69af439dc.yaml
Labels: Changelog: Removal

#11294 Remove links to qiskit.org in API docs
  qiskit/circuit/library/phase_estimation.py
  qiskit/circuit/quantumcircuit.py
  qiskit/qasm3/__init__.py
  qiskit/qpy/__init__.py
  qiskit/transpiler/passes/basis/basis_translator.py
  qiskit/transpiler/passes/scheduling/alignments/pulse_gate_validation.py
  qiskit/utils/optionals.py
Labels: documentation, Changelog: None, Community PR

#11276 Fix deprecation policy link in `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: documentation, Changelog: None

#11246 Remove unnecessary installation of build requirements
  .github/workflows/wheels.yml
Labels: type: qa, Changelog: None

#11271 Replace `qiskit` metapackage with `qiskit-terra`
  .azure/lint-linux.yml
  .azure/test-linux.yml
  .azure/test-macos.yml
  .azure/test-windows.yml
  .github/workflows/coverage.yml
  .github/workflows/neko.yml
  .github/workflows/slow.yml
  .github/workflows/wheels.yml
  qiskit_pkg/LICENSE.txt
  qiskit_pkg/MANIFEST.in
  qiskit_pkg/README.md
  qiskit_pkg/setup.py
  releasenotes/notes/terra-nullius-7ef598626d8118c1.yaml
  setup.py
  tools/deploy_translatable_strings.sh
  tox.ini
Labels: type: qa, priority: high, Changelog: API Change

#11323 Deprecate leftover algorithm/opflow utils
  qiskit/utils/arithmetic.py
  qiskit/utils/circuit_utils.py
  qiskit/utils/entangler_map.py
  qiskit/utils/name_unnamed_args.py
  releasenotes/notes/deprecate-leftover-algorithm-utils-d77253426257f41f.yaml
  test/python/algorithms/test_entangler_map.py
  test/python/test_util.py
Labels: Changelog: Deprecation

#11324 Remove leftover algorithm/opflow utils
  qiskit/utils/__init__.py
  qiskit/utils/arithmetic.py
  qiskit/utils/circuit_utils.py
  qiskit/utils/entangler_map.py
  qiskit/utils/name_unnamed_args.py
  releasenotes/notes/remove-algorithm-utils-707648b69af439dc.yaml
  test/python/test_util.py
Labels: Changelog: Removal

#10944 Add representation of storage-owning `Var` nodes
  qiskit/circuit/classical/expr/__init__.py
  qiskit/circuit/classical/expr/expr.py
  test/python/circuit/classical/test_expr_properties.py
Labels: Changelog: New Feature, mod: circuit

#11331 Prepare 0.45.1 release
  Cargo.lock
  Cargo.toml
  docs/conf.py
  qiskit/VERSION.txt
  qiskit_pkg/setup.py
  releasenotes/notes/add-py312-support-7077426af34ac5da.yaml
  releasenotes/notes/fix-qreg-visualization-after-layout-42d3e643b923d8bc.yaml
  releasenotes/notes/fix-schedule-qpy-use-symengine-05ae1dfab73e3ff8.yaml
  releasenotes/notes/fix_sim_backend-f3971b1ed4d0c4e6.yaml
  releasenotes/notes/prepare-0.45.1-d30b63803378ae7c.yaml
  setup.py
Labels: Changelog: None

#10651 Fix Sabre extended set population order
  crates/accelerate/src/sabre_swap/mod.rs
Labels: performance, Rust, mod: transpiler

#11235 Add pow as supported operation for ParameterExpression
  qiskit/circuit/parameterexpression.py
  releasenotes/notes/add-parameter-pow-ff5f8d10813f5733.yaml
  test/python/circuit/test_parameters.py
Labels: Changelog: New Feature, Community PR, mod: circuit

#11308 Remove legacy qasm2 parser
  docs/apidoc/index.rst
  docs/apidoc/qasm.rst
  qiskit/circuit/library/blueprintcircuit.py
  qiskit/circuit/quantumcircuit.py
  qiskit/converters/__init__.py
  qiskit/converters/ast_to_dag.py
  qiskit/qasm/__init__.py
  qiskit/qasm/exceptions.py
  qiskit/qasm/node/__init__.py
  qiskit/qasm/node/barrier.py
  qiskit/qasm/node/binaryop.py
  qiskit/qasm/node/binaryoperator.py
  qiskit/qasm/node/cnot.py
  qiskit/qasm/node/creg.py
  qiskit/qasm/node/customunitary.py
  qiskit/qasm/node/expressionlist.py
  qiskit/qasm/node/external.py
  qiskit/qasm/node/format.py
  qiskit/qasm/node/gate.py
  qiskit/qasm/node/gatebody.py
  qiskit/qasm/node/id.py
  qiskit/qasm/node/idlist.py
  qiskit/qasm/node/if_.py
  qiskit/qasm/node/indexedid.py
  qiskit/qasm/node/intnode.py
  qiskit/qasm/node/measure.py
  qiskit/qasm/node/node.py
  qiskit/qasm/node/nodeexception.py
  qiskit/qasm/node/opaque.py
  qiskit/qasm/node/prefix.py
  qiskit/qasm/node/primarylist.py
  qiskit/qasm/node/program.py
  qiskit/qasm/node/qreg.py
  qiskit/qasm/node/real.py
  qiskit/qasm/node/reset.py
  qiskit/qasm/node/unaryoperator.py
  qiskit/qasm/node/universalunitary.py
  qiskit/qasm/pygments/__init__.py
  qiskit/qasm/pygments/lexer.py
  qiskit/qasm/qasm.py
  qiskit/qasm/qasmlexer.py
  qiskit/qasm/qasmparser.py
  qiskit/qasm2/__init__.py
  qiskit/tools/jupyter/library.py
  releasenotes/notes/remove-legacy-qasm2-parser-53ad3f1817fd68cc.yaml
  requirements-optional.txt
  requirements.txt
  setup.py
  test/benchmarks/converters.py
  test/python/basicaer/test_qasm_simulator.py
  test/python/circuit/library/test_permutation.py
  test/python/circuit/test_circuit_qasm.py
  test/python/circuit/test_circuit_registers.py
  test/python/circuit/test_unitary.py
  test/python/compiler/test_compiler.py
  test/python/converters/test_ast_to_dag.py
  test/python/qasm2/test_circuit_methods.py
  test/python/qasm2/test_legacy_importer.py
  test/python/test_qasm_parser.py
Labels: Changelog: Removal, mod: qasm2

#11304 Decomposition of single R gate in RR basis should be one R gate, not two
  crates/accelerate/src/euler_one_qubit_decomposer.rs
  releasenotes/notes/rr-decomposition-synthesis-70eb88ada9305916.yaml
  test/python/quantum_info/test_synthesis.py
Labels: performance, Changelog: New Feature, mod: quantum info, Rust, Community PR

#11342 Add Python 3.12 to ASV conf.
  asv.conf.json
Labels: stable backport potential, Changelog: None

#10958 Move build configuration to static configuration files
  pyproject.toml
  qiskit/transpiler/passes/synthesis/high_level_synthesis.py
  qiskit/transpiler/passes/synthesis/plugin.py
  qiskit/transpiler/preset_passmanagers/plugin.py
  qiskit/utils/optionals.py
  requirements-optional.txt
  setup.py
  tox.ini
Labels: type: qa, Changelog: None

#10977 Track runtime variables in control-flow builders
  qiskit/circuit/controlflow/builder.py
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_control_flow_builders.py
Labels: mod: circuit
