Repository Qiskit/qiskit, pull requests merged in 2023-02, with the labels that each got.

#9502 Bug fix property and methods of BackendV2Converter
  qiskit/providers/backend_compat.py
  releasenotes/notes/fix-backendv2converter-de342352cf882494.yaml
Labels: stable backport potential, Changelog: Bugfix, automerge

#9507 Add equivalences from `CR<Pauli>` to `R<Paulis>`
  qiskit/circuit/library/standard_gates/equivalence_library.py
  releasenotes/notes/crx-equivalences-cc9e5c98bb73fd49.yaml
Labels: Changelog: New Feature, automerge

#9504 Local fidelity
  qiskit/algorithms/state_fidelities/compute_uncompute.py
  releasenotes/notes/computeuncompute-local-fidelity-501fe175762b7593.yaml
  test/python/algorithms/state_fidelities/test_compute_uncompute.py
Labels: Changelog: New Feature, automerge, mod: algorithms, Community PR

#9512 Fix doc typos in pass_manager_drawer
  qiskit/visualization/pass_manager_visualization.py
Labels: documentation, automerge, Changelog: None, Community PR

#9510 DOC add build dependency to contributing guides
  CONTRIBUTING.md
Labels: documentation, automerge, Changelog: None, Community PR

#9515 MNT add py311 as a target to black config
  pyproject.toml
Labels: automerge, Changelog: None, Community PR

#8856 Upgrade GitHub Actions
  .github/workflows/randomized_tests.yml
  .github/workflows/slow.yml
  .github/workflows/wheels.yml
Labels: type: qa, stable backport potential, automerge, Changelog: None, Community PR

#9522 Fix some typos in the docstrings
  qiskit/circuit/library/arithmetic/polynomial_pauli_rotations.py
  qiskit/transpiler/passes/routing/sabre_swap.py
  qiskit/transpiler/passmanager.py
Labels: documentation, stable backport potential, automerge, Changelog: None

#9526 Add `synthesis.QDrift` to sphinx toctree
  qiskit/synthesis/__init__.py
Labels: documentation, stable backport potential, automerge, Changelog: None

#9529 Disable f-string clippy lint
  src/lib.rs
Labels: type: qa, automerge, Changelog: None

#6658 PhaseOracle and BooleanExpression allow setting the expression variable order
  qiskit/circuit/classicalfunction/boolean_expression.py
  qiskit/circuit/library/phase_oracle.py
  releasenotes/notes/expression-var-order-d87e9b04fb5d545c.yaml
  test/python/circuit/library/test_phase_oracle.py
Labels: Changelog: API Change, automerge, Community PR

#9531 Set MSRV in `Cargo.toml`
  Cargo.toml
Labels: type: qa, stable backport potential, automerge, Changelog: None, Rust

#9175 two-qubit unitary synthesis adapted to errors and over-complete gatesets
  qiskit/quantum_info/synthesis/__init__.py
  qiskit/quantum_info/synthesis/two_qubit_decompose.py
  qiskit/quantum_info/synthesis/xx_decompose/__init__.py
  qiskit/quantum_info/synthesis/xx_decompose/decomposer.py
  qiskit/quantum_info/synthesis/xx_decompose/embodiments.py
  qiskit/transpiler/passes/optimization/consolidate_blocks.py
  qiskit/transpiler/passes/optimization/optimize_1q_commutation.py
  qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py
  qiskit/transpiler/passes/synthesis/plugin.py
  qiskit/transpiler/passes/synthesis/unitary_synthesis.py
  qiskit/transpiler/preset_passmanagers/common.py
  qiskit/transpiler/preset_passmanagers/level3.py
  releasenotes/notes/unitary-synthesis-based-on-errors-8041fcc9584f5db2.yaml
  test/python/circuit/test_unitary.py
  test/python/quantum_info/xx_decompose/test_decomposer.py
  test/python/transpiler/test_bip_mapping.py
  test/python/transpiler/test_optimize_1q_commutation.py
  test/python/transpiler/test_unitary_synthesis.py
Labels: priority: medium, Changelog: New Feature, Changelog: API Change, automerge, mod: transpiler

#9533 Add circuit library to Terra API Reference list
  docs/apidocs/circuit_library.rst
  docs/apidocs/terra.rst
  docs/index.rst
Labels: documentation, stable backport potential, automerge, Changelog: None

#9406 Remove DagDepNode.condition (deprecated in #6110)
  qiskit/dagcircuit/dagdepnode.py
  releasenotes/notes/6110-709f6fa891bdb26b.yaml
Labels: Changelog: Removal, automerge

#9473 Fix typo of Target argument name
  qiskit/providers/backend_compat.py
  qiskit/providers/fake_provider/utils/backend_converter.py
  qiskit/transpiler/target.py
  releasenotes/notes/fix-target-aquire_alignment-typo-d32ff31742b448a1.yaml
  test/python/transpiler/test_target.py
Labels: Changelog: Bugfix, automerge

#9542 Fix fake backend not to use deprecated arguments in NoiseModel construction
  qiskit/providers/fake_provider/fake_backend.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#8257 Fix mypy errors (quantum_info)
  qiskit/quantum_info/states/statevector.py
  qiskit/quantum_info/synthesis/xx_decompose/decomposer.py
Labels: automerge, Changelog: None, Community PR

#9183 Fix C3SXGate roundtrip in OpenQASM 2
  qiskit/circuit/library/standard_gates/x.py
  qiskit/circuit/quantumcircuit.py
  qiskit/converters/ast_to_dag.py
  releasenotes/notes/fix-qasm2-c3sxgate-47171c9d17876219.yaml
  test/python/circuit/test_circuit_qasm.py
Labels: Changelog: Bugfix, automerge, qasm

#9545 Fix Python 3.7 support removal date (wrong year)
  releasenotes/notes/0.23/prepare-0.23.0-release-0d954c91143cf9a4.yaml
Labels: documentation, automerge, Changelog: None

#9551 rewrite needlessly confusing line
  qiskit/quantum_info/synthesis/xx_decompose/decomposer.py
Labels: automerge, Changelog: None

#9543 Add an equiv method to the StabilizerState class
  qiskit/quantum_info/states/stabilizerstate.py
  releasenotes/notes/add-equiv-stabilizerstate-6ef8790c765690c1.yaml
  test/python/quantum_info/states/test_stabilizerstate.py
Labels: Changelog: New Feature, automerge, mod: quantum info

#9561 Add flipping of `swap` to `GateDirection` pass
  qiskit/transpiler/passes/utils/gate_direction.py
  releasenotes/notes/gate-direction-swap-885b6f8ba9779853.yaml
  test/python/transpiler/test_gate_direction.py
Labels: Changelog: New Feature, automerge, mod: transpiler

#9568 Make `BarrierBeforeFinalMeasurements` deterministic
  qiskit/transpiler/passes/utils/merge_adjacent_barriers.py
  releasenotes/notes/deterministic-barrier-before-final-measurements-04e817d995794067.yaml
  test/python/transpiler/test_adjacent_barriers.py
  test/python/transpiler/test_barrier_before_final_measurements.py
Labels: Changelog: Bugfix, automerge, mod: transpiler

#9571 Improve efficiency of CouplingMap.make_symmetric
  qiskit/transpiler/coupling.py
Labels: performance, automerge, Changelog: None

#9563 Fix a few minor issues/typos in the ``qiskit.providers`` docs
  qiskit/providers/__init__.py
Labels: documentation, automerge, Changelog: None, Community PR

#9565 Support for time-dependent Hamiltonians and observable evaluation in ``TrotterQRTE``
  qiskit/algorithms/time_evolvers/time_evolution_problem.py
  qiskit/algorithms/time_evolvers/time_evolution_result.py
  qiskit/algorithms/time_evolvers/trotterization/trotter_qrte.py
  qiskit/algorithms/time_evolvers/variational/solvers/var_qte_linear_solver.py
  qiskit/algorithms/utils/assign_params.py
  qiskit/circuit/library/pauli_evolution.py
  releasenotes/notes/trotter-time-dep-hamiltonians-8c6c3d5f629e72fb.yaml
  test/python/algorithms/time_evolvers/test_time_evolution_problem.py
  test/python/algorithms/time_evolvers/test_trotter_qrte.py
  test/python/circuit/library/test_evolution_gate.py
Labels: Changelog: New Feature, automerge, mod: algorithms, Community PR

#9575 Fix `NumPy(Minimum)Eigensolver` for sparse matrices
  qiskit/algorithms/eigensolvers/numpy_eigensolver.py
  releasenotes/notes/fix-numpy-eigensolver-sparse-0e255d7b13b5e43b.yaml
Labels: stable backport potential, Changelog: Bugfix, automerge, mod: algorithms

#9560 Remove Sabre's manual insertion-order iteration and unnecessary sorts
  releasenotes/notes/sabre-sort-rng-056f26f205e38bab.yaml
  src/sabre_swap/layer.rs
  src/sabre_swap/mod.rs
  test/python/qasm/TestsSabreSwap_handle_measurement.qasm
  test/python/transpiler/test_sabre_layout.py
Labels: performance, Changelog: New Feature, Changelog: API Change, automerge, Rust, mod: transpiler

#9590 ZGate note in documentation fixed
  qiskit/circuit/library/standard_gates/z.py
Labels: documentation, automerge, Community PR

#9584 Add `rust-toolchain.toml` for a consistent Rust development version
  .azure/test-linux.yml
  .azure/wheels.yml
  CONTRIBUTING.md
  Cargo.toml
  azure-pipelines.yml
  rust-toolchain.toml
Labels: automerge, Changelog: None, Rust, refactor

#9596 Fix setting rustup toolchain override in wheel builds
  .azure/wheels.yml
  pyproject.toml
Labels: type: qa, automerge, Changelog: None

#9598 Fix sparse matrix conversion for `SciPy<Real/Imaginary>Evolver`
  qiskit/algorithms/time_evolvers/classical_methods/evolve.py
  releasenotes/notes/fix-numpy-eigensolver-sparse-0e255d7b13b5e43b.yaml
Labels: stable backport potential, Changelog: Bugfix, automerge, mod: algorithms

#9482 Fix tox.ini for tox 4
  tox.ini
Labels: type: qa, automerge, Changelog: None

#9589 Create SECURITY.md
  SECURITY.md
Labels: Changelog: None

#9525 Retain all deprecated `Bit` properties in QPY roundtrip
  qiskit/qpy/__init__.py
  qiskit/qpy/binary_io/circuits.py
  releasenotes/notes/fix-deprecated-bit-qpy-roundtrip-9a23a795aa677c71.yaml
  test/python/circuit/test_circuit_load_from_qpy.py
  test/qpy_compat/test_qpy.py
Labels: stable backport potential, Changelog: Bugfix, automerge, mod: qpy

#9593 Run Rust tests in CI
  .azure/test-linux.yml
  azure-pipelines.yml
Labels: type: qa, automerge, Changelog: None

#9538 Fix `VQD` with `SPSA` optimizer
  qiskit/algorithms/eigensolvers/vqd.py
  releasenotes/notes/fix-vqd-with-spsa-optimizers-9ed02b80f26e8abf.yaml
  test/python/algorithms/eigensolvers/test_vqd.py
Labels: stable backport potential, Changelog: Bugfix, automerge, mod: algorithms

#9615 Upgrade Pylint to 2.16.2
  .pylintrc
  qiskit/opflow/converters/pauli_basis_change.py
  requirements-dev.txt
  test/python/pulse/test_transforms.py
Labels: stable backport potential, automerge, Changelog: None, refactor

#9617 Fix target error and duration lookup in UnitarySynthesis
  qiskit/transpiler/passes/synthesis/unitary_synthesis.py
  test/python/transpiler/test_unitary_synthesis.py
Labels: priority: high, automerge, Changelog: None

#9621 Performance improvement of `SparsePauliOp.tensor`
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
Labels: performance, automerge, mod: quantum info, Changelog: None

#9625 Added pulses to the `SymbolicPulse` library
  qiskit/pulse/__init__.py
  qiskit/pulse/library/__init__.py
  qiskit/pulse/library/symbolic_pulses.py
  releasenotes/notes/add-new-symbolic-pulses-4dc46ecaaa1ba928.yaml
  test/python/pulse/test_pulse_lib.py
Labels: Changelog: New Feature, automerge, mod: pulse

#9630 Fix handling of simulator backends in BackendV2Converter
  qiskit/providers/backend_compat.py
  releasenotes/notes/fix-backendv2-converter-simulator-e8f150d1fd6861fe.yaml
  test/python/providers/test_fake_backends.py
Labels: stable backport potential, Changelog: Bugfix, automerge, mod: fake_provider

#9606 Do not count delay operations in `final_measurement_mapping`
  qiskit/primitives/utils.py
  test/python/primitives/test_utils.py
Labels: automerge, Changelog: None, mod: primitives

#9634 Enable ignored tests in SparsePauliOp
  test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
Labels: stable backport potential, automerge, mod: quantum info, Changelog: None

#9636 Add loop ops to Aer BackendV2 test
  test/python/providers/test_fake_backends.py
Labels: stable backport potential, automerge, Changelog: None

#9623 Add the gates ECR, iSwap, CY, SX, SXdg, DCX to the Clifford class
  qiskit/circuit/library/standard_gates/equivalence_library.py
  qiskit/quantum_info/operators/symplectic/clifford.py
  qiskit/quantum_info/operators/symplectic/clifford_circuits.py
  releasenotes/notes/add-gates-to-Clifford-class-7de8d3213c60836a.yaml
  test/python/quantum_info/operators/symplectic/test_clifford.py
Labels: stable backport potential, Changelog: Bugfix, automerge, mod: quantum info, synthesis

#9635 Fix inverse of ``SdgGate`` in Solovay Kitaev
  qiskit/synthesis/__init__.py
  qiskit/synthesis/discrete_basis/__init__.py
  qiskit/synthesis/discrete_basis/generate_basis_approximations.py
  qiskit/transpiler/passes/synthesis/solovay_kitaev_synthesis.py
  releasenotes/notes/fix-sk-sdg-81ec87abe7af4a89.yaml
  test/python/transpiler/test_solovay_kitaev.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#9643 Prepare 0.23.2
  Cargo.lock
  Cargo.toml
  docs/conf.py
  qiskit/VERSION.txt
  releasenotes/notes/add-gates-to-Clifford-class-7de8d3213c60836a.yaml
  releasenotes/notes/fix-backendv2-converter-simulator-e8f150d1fd6861fe.yaml
  releasenotes/notes/fix-backendv2converter-de342352cf882494.yaml
  releasenotes/notes/fix-instmap-from-target-f38962c3fd03e5d3.yaml
  releasenotes/notes/fix-vqd-with-spsa-optimizers-9ed02b80f26e8abf.yaml
  releasenotes/notes/prepare-0.23.2-80519f083ae7086c.yaml
  releasenotes/notes/qnspsa-float-bug-fix-4035f7e1eb61dec2.yaml
  setup.py
Labels: automerge, Changelog: None

#9616 Add `since` argument to deprecation functions
  qiskit/algorithms/amplitude_amplifiers/grover.py
  qiskit/algorithms/amplitude_estimators/ae.py
  qiskit/algorithms/amplitude_estimators/fae.py
  qiskit/algorithms/amplitude_estimators/iae.py
  qiskit/algorithms/amplitude_estimators/mlae.py
  qiskit/algorithms/aux_ops_evaluator.py
  qiskit/algorithms/eigen_solvers/eigen_solver.py
  qiskit/algorithms/eigen_solvers/numpy_eigen_solver.py
  qiskit/algorithms/eigen_solvers/vqd.py
  qiskit/algorithms/evolvers/evolution_problem.py
  qiskit/algorithms/evolvers/evolution_result.py
  qiskit/algorithms/evolvers/imaginary_evolver.py
  qiskit/algorithms/evolvers/real_evolver.py
  qiskit/algorithms/evolvers/trotterization/trotter_qrte.py
  qiskit/algorithms/factorizers/shor.py
  qiskit/algorithms/linear_solvers/hhl.py
  qiskit/algorithms/linear_solvers/linear_solver.py
  qiskit/algorithms/linear_solvers/matrices/linear_system_matrix.py
  qiskit/algorithms/linear_solvers/matrices/numpy_matrix.py
  qiskit/algorithms/linear_solvers/matrices/tridiagonal_toeplitz.py
  qiskit/algorithms/linear_solvers/numpy_linear_solver.py
  qiskit/algorithms/linear_solvers/observables/absolute_average.py
  qiskit/algorithms/linear_solvers/observables/linear_system_observable.py
  qiskit/algorithms/linear_solvers/observables/matrix_functional.py
  qiskit/algorithms/minimum_eigen_solvers/minimum_eigen_solver.py
  qiskit/algorithms/minimum_eigen_solvers/numpy_minimum_eigen_solver.py
  qiskit/algorithms/minimum_eigen_solvers/qaoa.py
  qiskit/algorithms/minimum_eigen_solvers/vqe.py
  qiskit/algorithms/optimizers/adam_amsgrad.py
  qiskit/algorithms/optimizers/spsa.py
  qiskit/algorithms/phase_estimators/phase_estimation_result.py
  qiskit/circuit/classicalregister.py
  qiskit/circuit/quantumregister.py
  qiskit/dagcircuit/dagcircuit.py
  qiskit/primitives/base/base_estimator.py
  qiskit/primitives/base/base_sampler.py
  qiskit/pulse/instructions/instruction.py
  qiskit/pulse/utils.py
  qiskit/qobj/converters/pulse_instruction.py
  qiskit/qpy/interface.py
  qiskit/quantum_info/operators/symplectic/random.py
  qiskit/quantum_info/synthesis/two_qubit_decompose.py
  qiskit/scheduler/utils.py
  qiskit/transpiler/target.py
  qiskit/utils/deprecation.py
  qiskit/visualization/pulse/interpolation.py
  qiskit/visualization/pulse/matplotlib.py
  qiskit/visualization/state_visualization.py
Labels: automerge, Changelog: None

#9645 minor formatting issue in qiskit.execute_function
  qiskit/execute_function.py
Labels: documentation, stable backport potential, automerge, Changelog: None

#9629 Fix bug in backend primitives with `bound_pass_manager`
  qiskit/primitives/backend_estimator.py
  qiskit/primitives/backend_sampler.py
  qiskit/primitives/base/base_estimator.py
  qiskit/primitives/base/base_sampler.py
  releasenotes/notes/fix-bound-pm-backend-primitives-98fd11c5e852501c.yaml
  test/python/primitives/test_backend_estimator.py
  test/python/primitives/test_backend_sampler.py
Labels: stable backport potential, Changelog: Bugfix, automerge, mod: primitives

#9567 Improve documentation of ``HamiltonianGate`` and ``UnitaryGate``
  qiskit/extensions/hamiltonian_gate.py
  qiskit/extensions/unitary.py
Labels: documentation, stable backport potential, automerge, Community PR

#9651 Fix typing error in `random_circuit` conditionals
  qiskit/circuit/random/utils.py
  releasenotes/notes/fix-random-circuit-conditional-6067272319986c63.yaml
  test/python/circuit/test_random_circuit.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#9668 Update the docsring of the circuit library
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/standard_gates/__init__.py
Labels: documentation, stable backport potential, automerge

#9681 Stop raising AttributeError when accessing missing calibration
  qiskit/transpiler/target.py
  releasenotes/notes/fix-missing-instproperty-calibration-e578052819592a0b.yaml
  test/python/transpiler/test_target.py
Labels: stable backport potential, Changelog: Bugfix, automerge
