Repository Qiskit/qiskit, pull requests merged in 2023-09, with the labels that each got.

#10757 Support new-style Bit in Pauli convertor from QuantumCircuit
  qiskit/quantum_info/operators/symplectic/pauli.py
  releasenotes/notes/fix_pauli_new_style_bit-0704933127b4debe.yaml
  test/python/quantum_info/operators/symplectic/test_pauli.py
Labels: stable backport potential, Changelog: Bugfix, mod: quantum info

#10739 Upgrade to qiskit-sphinx-theme 1.16
  .azure/docs-linux.yml
  requirements-dev.txt
Labels: documentation, stable backport potential, Changelog: None

#10656 Revert "Revert to one release notes file (#10639)"
  docs/legacy_release_notes.rst
  docs/release_notes.rst
Labels: documentation, Changelog: None

#10533 Move OpenQASM 2 exporter to `qiskit.qasm2`
  qiskit/circuit/quantumcircuit.py
  qiskit/qasm2/__init__.py
  qiskit/qasm2/export.py
  releasenotes/notes/qasm2-new-api-4e1e4803d6a5a175.yaml
  test/python/qasm2/test_export.py
Labels: Changelog: Deprecation, Changelog: New Feature, mod: qasm2

#10661 Updated badge in README.md
  README.md
Labels: Community PR

#10763 Fix download badge in README.md file and a typo
  README.md
Labels: Changelog: None, Community PR

#10724 Fail gracefully on bad `SabreDAG` construction
  .azure/test-linux.yml
  Cargo.toml
  crates/accelerate/Cargo.toml
  crates/accelerate/src/sabre_layout.rs
  crates/accelerate/src/sabre_swap/sabre_dag.rs
  crates/qasm2/Cargo.toml
Labels: stable backport potential, Changelog: None, Rust, mod: transpiler

#10750 Hardcode register name in timeline/test_generators.py to remove deprecated attribute
  qiskit/visualization/timeline/generators.py
  test/python/visualization/timeline/test_generators.py
Labels: Changelog: None

#10667 Fix issues with translation deployment script
  .github/workflows/docs_deploy.yml
  tools/deploy_translatable_strings.sh
  tools/github_poBranch_update_key.enc
Labels: type: qa, priority: high, stable backport potential, Changelog: None

#10761 Use qubit-index newtypes in Rust space
  crates/accelerate/src/edge_collections.rs
  crates/accelerate/src/error_map.rs
  crates/accelerate/src/nlayout.rs
  crates/accelerate/src/sabre_layout.rs
  crates/accelerate/src/sabre_swap/layer.rs
  crates/accelerate/src/sabre_swap/mod.rs
  crates/accelerate/src/sabre_swap/neighbor_table.rs
  crates/accelerate/src/sabre_swap/sabre_dag.rs
  crates/accelerate/src/sabre_swap/swap_map.rs
  crates/accelerate/src/stochastic_swap.rs
  crates/accelerate/src/vf2_layout.rs
  qiskit/transpiler/passes/routing/sabre_swap.py
  qiskit/transpiler/passes/routing/stochastic_swap.py
Labels: Changelog: None, Rust, mod: transpiler

#10773 Handle final comments with no terminating newline in OpenQASM 2
  crates/qasm2/src/lex.rs
  releasenotes/notes/fix-qasm2-final-comment-f0904c3e13215a00.yaml
  test/python/qasm2/test_structure.py
Labels: stable backport potential, Changelog: Bugfix, mod: qasm2, Rust

#10774 Enforce type safety in `NeighborTable`
  crates/accelerate/src/sabre_swap/mod.rs
  crates/accelerate/src/sabre_swap/neighbor_table.rs
Labels: Changelog: None, Rust, mod: transpiler

#10777 Optimize UnrollCustomDefinitions pass
  qiskit/transpiler/passes/basis/unroll_custom_definitions.py
Labels: performance, Changelog: None

#10784 Use `SmallVec` in `NeighborTable` for cache locality
  Cargo.lock
  crates/accelerate/Cargo.toml
  crates/accelerate/src/sabre_swap/neighbor_table.rs
Labels: performance, Changelog: None, Rust, mod: transpiler

#10783 Reuse scratch space for Sabre best-swap choice
  crates/accelerate/src/sabre_swap/mod.rs
Labels: performance, Changelog: None, Rust, mod: transpiler

#10756 Track Sabre decay heuristic on physical qubits
  crates/accelerate/src/sabre_swap/mod.rs
  releasenotes/notes/sabre-decay-physical-ad2f470cd45d69f3.yaml
  test/python/transpiler/test_sabre_layout.py
Labels: Changelog: Bugfix, Rust, mod: transpiler

#10753 Add fast-path construction to `DAGCircuit` methods
  qiskit/converters/ast_to_dag.py
  qiskit/converters/circuit_to_dag.py
  qiskit/dagcircuit/dagcircuit.py
  qiskit/quantum_info/synthesis/one_qubit_decompose.py
  qiskit/synthesis/discrete_basis/gate_sequence.py
  qiskit/transpiler/passes/basis/basis_translator.py
  qiskit/transpiler/passes/basis/translate_parameterized.py
  qiskit/transpiler/passes/layout/apply_layout.py
  qiskit/transpiler/passes/layout/disjoint_utils.py
  qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py
  qiskit/transpiler/passes/optimization/optimize_swap_before_measure.py
  qiskit/transpiler/passes/routing/algorithms/util.py
  qiskit/transpiler/passes/routing/basic_swap.py
  qiskit/transpiler/passes/routing/lookahead_swap.py
  qiskit/transpiler/passes/routing/sabre_swap.py
  qiskit/transpiler/passes/routing/stochastic_swap.py
  qiskit/transpiler/passes/scheduling/alap.py
  qiskit/transpiler/passes/scheduling/alignments/align_measures.py
  qiskit/transpiler/passes/scheduling/dynamical_decoupling.py
  qiskit/transpiler/passes/scheduling/padding/base_padding.py
  qiskit/transpiler/passes/utils/barrier_before_final_measurements.py
  qiskit/transpiler/passes/utils/convert_conditions_to_if_ops.py
  qiskit/transpiler/passes/utils/merge_adjacent_barriers.py
  releasenotes/notes/dag-appenders-check-84d4ef20c1e20fd0.yaml
Labels: performance, Changelog: New Feature, mod: transpiler

#10788 Speed up synthesis passes when there is nothing to synthesize
  qiskit/circuit/controlflow/__init__.py
  qiskit/dagcircuit/dagcircuit.py
  qiskit/transpiler/passes/synthesis/high_level_synthesis.py
  qiskit/transpiler/passes/synthesis/unitary_synthesis.py
  qiskit/transpiler/preset_passmanagers/common.py
Labels: performance, Changelog: None, mod: transpiler

#10758 Fix `qpy` for multiple controlled parametrized gates
  qiskit/qpy/binary_io/circuits.py
  releasenotes/notes/fix-qpy-repeated-controlled-gates-e19fc4ee65a22756.yaml
  test/python/circuit/test_circuit_load_from_qpy.py
Labels: stable backport potential, Changelog: Bugfix, mod: qpy

#10794 Cleanup venvs if new qpy payloads are created in backwards compat tests
  test/qpy_compat/process_version.sh
Labels: type: qa, stable backport potential, Changelog: None

#10793 Removal of deprecated property num_ancilla_qubits
  qiskit/circuit/library/arithmetic/polynomial_pauli_rotations.py
  releasenotes/notes/num-ancilla-qubits-deprecation-d616c3fc24250d22.yaml
Labels: Changelog: Removal, Community PR

#10710 Move qiskit-tutorials into this repository
  .azure/tutorials-linux.yml
  .github/workflows/docs_deploy.yml
  docs/tutorials/circuits/01_circuit_basics.ipynb
  docs/tutorials/circuits/1_getting_started_with_qiskit.ipynb
  docs/tutorials/circuits/2_plotting_data_in_qiskit.ipynb
  docs/tutorials/circuits/3_summary_of_quantum_operations.ipynb
  docs/tutorials/circuits/placeholder.ipynb
  docs/tutorials/circuits_advanced/01_advanced_circuits.ipynb
  docs/tutorials/circuits_advanced/02_operators_overview.ipynb
  docs/tutorials/circuits_advanced/03_advanced_circuit_visualization.ipynb
  docs/tutorials/circuits_advanced/04_transpiler_passes_and_passmanager.ipynb
  docs/tutorials/circuits_advanced/05_pulse_gates.ipynb
  docs/tutorials/circuits_advanced/06_building_pulse_schedules.ipynb
  docs/tutorials/circuits_advanced/07_pulse_scheduler.ipynb
  docs/tutorials/circuits_advanced/08_gathering_system_information.ipynb
  docs/tutorials/circuits_advanced/placeholder.ipynb
  docs/tutorials/circuits_advanced/pulse_modulation.png
  docs/tutorials/operators/01_operator_flow.ipynb
  docs/tutorials/operators/02_gradients_framework.ipynb
  docs/tutorials/operators/images/gradient_framework.png
  docs/tutorials/operators/placeholder.ipynb
  tools/prepare_tutorials.bash
Labels: documentation, Changelog: None

#10816 Add logging message with rust runtime to sabre passes
  qiskit/transpiler/passes/layout/sabre_layout.py
  qiskit/transpiler/passes/routing/sabre_swap.py
Labels: Changelog: None, mod: transpiler

#10765 Allow empty list default initialization for `SparsePauliOp`
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
  releasenotes/notes/sparse-pauli-op-num-qubits-9c1a3f7dcc7949b9.yaml
  test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
Labels: Changelog: New Feature, mod: quantum info, Community PR

#10792 Deprecate `bind_parameters` in favor of `assign_parameters`
  qiskit/algorithms/eigen_solvers/vqd.py
  qiskit/algorithms/eigensolvers/vqd.py
  qiskit/algorithms/evolvers/trotterization/trotter_qrte.py
  qiskit/algorithms/gradients/reverse/bind.py
  qiskit/algorithms/minimum_eigen_solvers/vqe.py
  qiskit/algorithms/optimizers/qnspsa.py
  qiskit/algorithms/optimizers/spsa.py
  qiskit/algorithms/time_evolvers/pvqd/pvqd.py
  qiskit/circuit/parameter.py
  qiskit/circuit/quantumcircuit.py
  qiskit/compiler/assembler.py
  qiskit/primitives/backend_estimator.py
  qiskit/primitives/backend_sampler.py
  qiskit/primitives/estimator.py
  qiskit/primitives/sampler.py
  qiskit/transpiler/passes/synthesis/unitary_synthesis.py
  qiskit/transpiler/passes/utils/unroll_forloops.py
  releasenotes/notes/deprecate-bind-parameters-283c94069e8a9142.yaml
  test/benchmarks/circuit_construction.py
  test/python/algorithms/test_aux_ops_evaluator.py
  test/python/algorithms/test_observables_evaluator.py
  test/python/algorithms/test_vqe.py
  test/python/algorithms/time_evolvers/variational/test_var_qrte.py
  test/python/circuit/test_circuit_load_from_qpy.py
  test/python/circuit/test_circuit_operations.py
  test/python/circuit/test_hamiltonian_gate.py
  test/python/circuit/test_parameters.py
  test/python/compiler/test_assembler.py
  test/python/primitives/test_backend_estimator.py
  test/python/primitives/test_estimator.py
  test/python/qasm2/test_circuit_methods.py
  test/python/qasm2/test_legacy_importer.py
  test/python/qasm3/test_export.py
  test/python/transpiler/test_optimize_1q_decomposition.py
  test/python/transpiler/test_template_matching.py
  test/python/visualization/test_circuit_latex.py
  test/python/visualization/test_circuit_text_drawer.py
  test/qpy_compat/test_qpy.py
  test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py
Labels: Changelog: Deprecation

#10526 Remove deprecated BIPMapping pass
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/routing/__init__.py
  qiskit/transpiler/passes/routing/algorithms/bip_model.py
  qiskit/transpiler/passes/routing/bip_mapping.py
  qiskit/utils/optionals.py
  releasenotes/notes/remove-deprecated-bip-mapper-e1206c8f905502dd.yaml
  test/python/transpiler/test_bip_mapping.py
Labels: Changelog: Removal

#10721 Add option to SabreLayout to specify starting layouts
  crates/accelerate/src/sabre_layout.rs
  qiskit/transpiler/passes/layout/sabre_layout.py
  releasenotes/notes/seed-sabre-with-layout-17d46e1a6f516b0e.yaml
  test/python/transpiler/test_sabre_layout.py
Labels: Changelog: New Feature, Rust, mod: transpiler

#10830 Do not emit warnings from `opflow` initialisation
  qiskit/opflow/operator_globals.py
Labels: type: qa, stable backport potential, Changelog: None

#10825 Fix GateDirection pass
  qiskit/transpiler/passes/utils/gate_direction.py
  releasenotes/notes/fix-gate-direction-d8bc96b62b27dba8.yaml
  test/python/transpiler/test_gate_direction.py
Labels: stable backport potential, Changelog: Bugfix

#10772 Kraus operator documentation formatting
  qiskit/quantum_info/operators/channel/kraus.py
Labels: documentation, stable backport potential, Changelog: None

#10549 Add fast path to `Parameter.assign`
  qiskit/circuit/parameter.py
  releasenotes/notes/optimise-parameter-assign-398ed4f2074ca201.yaml
Labels: performance, Changelog: New Feature

#10548 Optimise `QuantumCircuit.assign_parameters` for single-parameter binding
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/optimise-unsorted-parameters-310e5f2420771f49.yaml
Labels: performance, Changelog: New Feature

#10843 qreg_creg_descending calls deprecated Bit.index
  qiskit/visualization/timeline/layouts.py
Labels: stable backport potential, Changelog: None, mod: visualization

#10844 `QCircuitImage` calls deprecated `Bit.index`
  qiskit/visualization/circuit/latex.py
Labels: stable backport potential, Changelog: None

#10834 Allow dynamical decoupling pass to work on circuits with pulse gates
  qiskit/transpiler/passes/scheduling/padding/dynamical_decoupling.py
  releasenotes/notes/dd-pg-10833-ddddee68ffd913c4.yaml
  test/python/transpiler/test_dynamical_decoupling.py
Labels: stable backport potential, Changelog: Bugfix, mod: pulse, mod: transpiler

#10791 Remove deprecated code in 0.19
  qiskit/compiler/assembler.py
  qiskit/providers/models/backendconfiguration.py
  qiskit/qobj/__init__.py
  qiskit/transpiler/instruction_durations.py
  qiskit/utils/quantum_instance.py
  releasenotes/notes/remove-deprecated-code-in-0.19-a97ccfec62405b9a.yaml
Labels: Changelog: Removal, Community PR

#10314 Use singletons for standard library unparameterized, non-controlled gates
  qiskit/circuit/__init__.py
  qiskit/circuit/add_control.py
  qiskit/circuit/gate.py
  qiskit/circuit/instruction.py
  qiskit/circuit/instructionset.py
  qiskit/circuit/library/standard_gates/dcx.py
  qiskit/circuit/library/standard_gates/ecr.py
  qiskit/circuit/library/standard_gates/h.py
  qiskit/circuit/library/standard_gates/i.py
  qiskit/circuit/library/standard_gates/iswap.py
  qiskit/circuit/library/standard_gates/s.py
  qiskit/circuit/library/standard_gates/swap.py
  qiskit/circuit/library/standard_gates/sx.py
  qiskit/circuit/library/standard_gates/t.py
  qiskit/circuit/library/standard_gates/x.py
  qiskit/circuit/library/standard_gates/y.py
  qiskit/circuit/library/standard_gates/z.py
  qiskit/circuit/random/utils.py
  qiskit/circuit/singleton_gate.py
  qiskit/converters/ast_to_dag.py
  qiskit/converters/circuit_to_instruction.py
  qiskit/dagcircuit/dagcircuit.py
  qiskit/qasm2/parse.py
  qiskit/qpy/binary_io/circuits.py
  qiskit/transpiler/passes/optimization/reset_after_measure_simplification.py
  qiskit/transpiler/passes/scheduling/dynamical_decoupling.py
  qiskit/transpiler/passes/scheduling/padding/dynamical_decoupling.py
  qiskit/transpiler/passes/scheduling/scheduling/base_scheduler.py
  qiskit/transpiler/passes/scheduling/time_unit_conversion.py
  releasenotes/notes/singletons-83782de8bd062cbc.yaml
  test/python/circuit/gate_utils.py
  test/python/circuit/test_circuit_load_from_qpy.py
  test/python/circuit/test_gate_definitions.py
  test/python/circuit/test_instructions.py
  test/python/circuit/test_singleton_gate.py
  test/python/dagcircuit/test_dagcircuit.py
Labels: priority: high, performance, Changelog: New Feature, Changelog: API Change

#10863 adding an option to CouplingMap.reduce to allow disconnected coupling maps
  qiskit/transpiler/coupling.py
  releasenotes/notes/extend-coupling-map-reduce-bb19e35ec939570d.yaml
  test/python/transpiler/test_coupling.py
Labels: Changelog: New Feature

#10782 Use physical qubits internally within Sabre
  crates/accelerate/src/sabre_swap/layer.rs
  crates/accelerate/src/sabre_swap/mod.rs
  crates/accelerate/src/sabre_swap/swap_map.rs
  qiskit/transpiler/passes/routing/sabre_swap.py
  test/python/transpiler/test_sabre_layout.py
  test/python/transpiler/test_sabre_swap.py
Labels: performance, Changelog: None, Rust, mod: transpiler

#10865 Use singleton `SwapGate` in Sabre reconstruction
  qiskit/transpiler/passes/routing/sabre_swap.py
Labels: performance, Changelog: None, mod: transpiler

#10861 Remove quantum_info deprecated code in 0.22
  qiskit/quantum_info/__init__.py
  qiskit/quantum_info/operators/random.py
  qiskit/quantum_info/operators/symplectic/pauli_utils.py
  qiskit/quantum_info/operators/symplectic/random.py
  qiskit/quantum_info/random.py
  releasenotes/notes/remove-deprecated-code-in-0.22-128475199e6f3cc2.yaml
  test/python/quantum_info/operators/test_random.py
Labels: Changelog: Removal, Community PR

#10571 #10360 New sign feature in parameterexpression.py
  qiskit/circuit/parameterexpression.py
  releasenotes/notes/added-sign-feature-parameterexpression-57693dd69103dc8c.yaml
  test/python/circuit/test_parameters.py
Labels: Changelog: New Feature, Community PR

#10878 formating issues in schmidt_decomposition and diamond_norm
  qiskit/quantum_info/operators/measures.py
  qiskit/quantum_info/states/utils.py
Labels: documentation, stable backport potential, Changelog: None

#10814 Fix CI path for translations deploy
  .github/workflows/docs_deploy.yml
Labels: documentation, Changelog: None

#10574 Small doc formatting issues
  qiskit/circuit/gate.py
  qiskit/circuit/instruction.py
  qiskit/converters/circuit_to_dag.py
  qiskit/converters/circuit_to_dagdependency.py
  qiskit/dagcircuit/__init__.py
  qiskit/dagcircuit/dagdependency.py
  qiskit/execute_function.py
  qiskit/extensions/quantum_initializer/squ.py
  qiskit/visualization/pass_manager_visualization.py
Labels: documentation, stable backport potential, Changelog: None

#10866 fix random statevector distribution
  qiskit/quantum_info/states/random.py
  releasenotes/notes/fix-random-statevector-a8dbf991cbbdee8e.yaml
Labels: Changelog: Bugfix, mod: quantum info

#10876 Remove spurious `SXGate._ARRAY`
  qiskit/circuit/library/standard_gates/sx.py
Labels: Changelog: None

#10838 Add action to copy metadata to backport PRs
  .github/workflows/backport.yml
Labels: type: qa, stable backport potential, Changelog: None

#10823 Remove `requires_qe_access`, deprecated in 0.17
  qiskit/test/__init__.py
  qiskit/test/decorators.py
Labels: Changelog: None

#10881 remove qiskit.utils.deprecation.deprecate_function, deprecated in Terra 0.22
  qiskit/pulse/utils.py
  releasenotes/notes/remove_deprecated_functionality-13b33f9dfa7d690a.yaml
Labels: Changelog: Removal

#10892 Replace use of `numpy.lib.scimath` with preferred `numpy.emath`
  qiskit/quantum_info/synthesis/qsd.py
Labels: stable backport potential, Changelog: None

#10208 Update plot_gate_map() family to leverage graphviz for visualization
  qiskit/visualization/gate_map.py
  releasenotes/notes/update-gate-map-visualizations-6ea907a0502fdc1a.yaml
  test/python/visualization/test_gate_map.py
  test/visual/mpl/graph/references/16_qubit_gate_map.png
  test/visual/mpl/graph/references/1_qubit_gate_map.png
  test/visual/mpl/graph/references/27_qubit_gate_map.png
  test/visual/mpl/graph/references/5_qubit_gate_map.png
  test/visual/mpl/graph/references/65_qubit_gate_map.png
  test/visual/mpl/graph/references/7_qubit_gate_map.png
  test/visual/mpl/graph/references/coupling_map.png
  test/visual/mpl/graph/references/figsize.png
  test/visual/mpl/graph/references/font_color.png
  test/visual/mpl/graph/references/line_color.png
  test/visual/mpl/graph/references/qubit_color.png
  test/visual/mpl/graph/references/qubit_labels.png
  test/visual/mpl/graph/references/qubit_size.png
Labels: Changelog: New Feature, Community PR, mod: visualization

#10893 Pin Numpy < 2 in requirements
  releasenotes/notes/numpy-2-pin-f600328f24fab6dd.yaml
  requirements.txt
Labels: type: qa, Changelog: API Change

#10849 Support passing empty lists to Pauli delete method
  qiskit/quantum_info/operators/symplectic/pauli.py
  qiskit/quantum_info/operators/symplectic/pauli_list.py
  qiskit/quantum_info/operators/symplectic/pauli_table.py
  releasenotes/notes/support-empty-delete-for-pauli-16c5c5fae890c16c.yaml
  test/python/quantum_info/operators/symplectic/test_pauli.py
  test/python/quantum_info/operators/symplectic/test_pauli_list.py
  test/python/quantum_info/operators/symplectic/test_pauli_table.py
Labels: stable backport potential, Changelog: Bugfix, mod: quantum info, Community PR

#8264 Fix mypy errors (utils)
  qiskit/utils/deprecation.py
  qiskit/utils/units.py
Labels: Changelog: None, Community PR, mypy

#10820 Add `use_symengine` option to `qpy.dump`
  circuit.qpy
  qiskit/qpy/__init__.py
  qiskit/qpy/binary_io/circuits.py
  qiskit/qpy/binary_io/schedules.py
  qiskit/qpy/binary_io/value.py
  qiskit/qpy/common.py
  qiskit/qpy/formats.py
  qiskit/qpy/interface.py
  qiskit/qpy/type_keys.py
  releasenotes/notes/add-qpy-symbolic-encoding-81d5321af38f259f.yaml
  test/python/circuit/test_circuit_load_from_qpy.py
  test/python/qpy/test_block_load_from_qpy.py
Labels: performance, Changelog: New Feature, mod: qpy

#10901 Assert properties not specifics of `DenseLayout` results
  test/python/transpiler/test_dense_layout.py
Labels: type: qa, stable backport potential, Changelog: None

#10886 Remove use of deprecated `ast.Num` for Python 3.12
  qiskit/pulse/parser.py
Labels: type: qa, Changelog: None

#10904 Fix Clifford.from_operator to fail with non-Clifford diagonal operators
  qiskit/quantum_info/operators/symplectic/clifford.py
  releasenotes/notes/fix-clifford-from-diagonal-7708654373bd5b8b.yaml
  test/python/quantum_info/operators/symplectic/test_clifford.py
Labels: stable backport potential, Changelog: Bugfix, mod: quantum info

#10909 fix PTM and Chi documentation
  qiskit/quantum_info/operators/channel/chi.py
  qiskit/quantum_info/operators/channel/ptm.py
Labels: documentation, stable backport potential, mod: quantum info

#10801 Add documentation on OpenQASM 2 phase conventions
  qiskit/qasm2/__init__.py
Labels: documentation, stable backport potential, mod: qasm2, Changelog: None

#10895 Deprecated modules section in main TOC
  docs/apidoc/index.rst
Labels: documentation, Changelog: None

#10596 reduce decimal for probabilities_dict in Sampler
  qiskit/quantum_info/operators/symplectic/pauli.py
  qiskit/result/distributions/quasi.py
  releasenotes/notes/decimals_for_sampler-5aaa56642cce23e0.yaml
Labels: Changelog: None, mod: primitives

#10871 Fix pickle handling for SingletonGate class
  qiskit/circuit/singleton_gate.py
  test/python/circuit/test_singleton_gate.py
  test/python/compiler/test_transpiler.py
Labels: Changelog: None

#10897 Fix casting rules changing in Numpy 2
  qiskit/quantum_info/operators/symplectic/base_pauli.py
  qiskit/quantum_info/operators/symplectic/pauli_list.py
  qiskit/quantum_info/operators/symplectic/pauli_table.py
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
Labels: type: qa, mod: quantum info, Changelog: None

#10717 Remove deprecated `x` and `z` arguments to `Pauli`
  qiskit/quantum_info/operators/pauli.py
  qiskit/quantum_info/operators/symplectic/pauli.py
  releasenotes/notes/remove_8070-09b64e3a2aca1c2d.yaml
Labels: Changelog: Removal, mod: quantum info

#9351 Many mentions to QASM should be changed to OpenQASM 2
  qiskit/algorithms/optimizers/spsa.py
  qiskit/assembler/assemble_circuits.py
  qiskit/circuit/controlflow/for_loop.py
  qiskit/circuit/library/hamiltonian_gate.py
  qiskit/circuit/quantumcircuit.py
  qiskit/compiler/assembler.py
  qiskit/converters/ast_to_dag.py
  qiskit/providers/basicaer/qasm_simulator.py
  qiskit/providers/fake_provider/fake_qasm_backend.py
  qiskit/providers/fake_provider/fake_qasm_simulator.py
  qiskit/providers/models/backendconfiguration.py
  qiskit/qasm/node/__init__.py
  qiskit/qasm/node/binaryoperator.py
  qiskit/qasm/node/unaryoperator.py
  qiskit/qasm/qasm.py
  qiskit/qasm3/__init__.py
  qiskit/qasm3/exporter.py
  qiskit/qasm3/printer.py
  qiskit/qobj/common.py
  qiskit/qobj/qasm_qobj.py
  qiskit/result/result.py
  qiskit/tools/jupyter/library.py
  test/python/qasm3/test_export.py
  test/python/transpiler/test_mappers.py
Labels: documentation, stable backport potential, Changelog: None
