Repository Qiskit/qiskit, pull requests merged in 2023-08, with the labels that each got.

#10550 Fixed qiskit.transpiler.passes.DynamicalDecoupling depreciation note
  qiskit/transpiler/passes/scheduling/dynamical_decoupling.py
Labels: documentation, stable backport potential, Changelog: None, Community PR

#10541 Update minimum Rust version to 1.64
  Cargo.lock
  Cargo.toml
  README.md
  crates/accelerate/Cargo.toml
  crates/qasm2/Cargo.toml
  releasenotes/notes/rust-1.64-add4a4a8e5ce9786.yaml
  rust-toolchain.toml
Labels: Changelog: API Change, Rust

#10555 Update deprecated textbook URL in phase estimation docstring
  qiskit/circuit/library/phase_estimation.py
Labels: documentation, stable backport potential, Changelog: None, Community PR

#9569 Fix potential non-determinism in DAGOpNode sort key
  qiskit/dagcircuit/dagcircuit.py
  qiskit/dagcircuit/dagnode.py
  test/python/dagcircuit/test_dagcircuit.py
  test/python/transpiler/test_sabre_layout.py
Labels: Changelog: None, mod: transpiler

#10558 Disable Numpy-style docstring handling in Napoleon
  docs/conf.py
Labels: documentation, stable backport potential, Changelog: None

#10271 Add `draw` method to `Operator` class
  qiskit/quantum_info/operators/operator.py
  qiskit/visualization/state_visualization.py
  releasenotes/notes/add-operator-draw-method-47f0381ba3f2a280.yaml
  test/python/quantum_info/operators/test_operator.py
Labels: Changelog: New Feature, mod: quantum info, Community PR, mod: visualization

#8967 Add no-optionals and full-optionals test runs
  .azure/test-linux.yml
  .azure/test-macos.yml
  .azure/test-windows.yml
  .azure/tutorials-linux.yml
  .github/workflows/coverage.yml
  azure-pipelines.yml
  qiskit/transpiler/passes/layout/_csp_custom_solver.py
  qiskit/utils/optionals.py
  qiskit/visualization/bloch.py
  requirements-dev.txt
  requirements-optional.txt
  requirements-tutorials.txt
  setup.py
  test/python/circuit/test_equivalence.py
  test/python/quantum_info/states/test_densitymatrix.py
  test/python/quantum_info/states/test_statevector.py
  test/python/tools/jupyter/test_notebooks.py
  test/python/transpiler/test_coupling.py
  test/python/transpiler/test_csp_layout.py
  test/python/visualization/test_circuit_drawer.py
  test/python/visualization/test_circuit_latex.py
  test/python/visualization/test_dag_drawer.py
  test/python/visualization/test_gate_map.py
  test/python/visualization/test_pass_manager_drawer.py
  test/python/visualization/test_plot_histogram.py
  test/python/visualization/test_utils.py
  test/python/visualization/visualization.py
  tox.ini
Labels: type: qa, stable backport potential, Changelog: None

#10537 Fix multiple nested custom controlled gates in QPY
  qiskit/qpy/binary_io/circuits.py
  releasenotes/notes/fix-qpy-nested-custom-controlled-2a23dfe828bc46c8.yaml
  test/python/circuit/test_circuit_load_from_qpy.py
Labels: stable backport potential, Changelog: Bugfix, mod: qpy

#10545 Implementing Scheduling Pass as Plugins
  qiskit/transpiler/preset_passmanagers/builtin_plugins.py
  qiskit/transpiler/preset_passmanagers/level0.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  setup.py
Labels: Changelog: None, Community PR, Intern PR

#10598 Add a unit test of qubit-wise grouping of SparsePauliOp
  test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
Labels: stable backport potential, mod: quantum info, Changelog: None

#10467 Optimize ConsolidateBlocks further
  crates/accelerate/src/convert_2q_block_matrix.rs
  crates/accelerate/src/lib.rs
  qiskit/__init__.py
  qiskit/transpiler/passes/optimization/consolidate_blocks.py
  qiskit/transpiler/passes/utils/block_to_matrix.py
Labels: performance, Changelog: None, Intern PR

#10597 Change 1q UnitaryGate definition to use U instead of U3
  qiskit/extensions/unitary.py
  releasenotes/notes/unitary-u-not-u3-0a32c2d968f7890e.yaml
  test/python/circuit/test_circuit_qasm.py
  test/python/circuit/test_unitary.py
Labels: Changelog: API Change

#10580 Fix open circles drawing incorrectly in mpl drawer and up visual circuit tests to .9999 accuracy
  qiskit/visualization/circuit/matplotlib.py
  test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py
Labels: stable backport potential, Changelog: Bugfix, mod: visualization

#10477 Adding ``coupling-map`` and ``target`` to ``HighLevelSynthesis``
  qiskit/transpiler/passes/synthesis/high_level_synthesis.py
  qiskit/transpiler/passes/synthesis/plugin.py
  qiskit/transpiler/preset_passmanagers/common.py
  releasenotes/notes/add-target-to-hls.yaml
  test/python/transpiler/test_high_level_synthesis.py
Labels: Changelog: New Feature, synthesis, mod: transpiler

#10610 Add GitHub Actions documentation-deployment pipeline
  .azure/docs-linux.yml
  .azure/tutorials-linux.yml
  .github/workflows/docs_deploy.yml
  .gitignore
  azure-pipelines.yml
  docs/conf.py
  tools/docs_exclude.txt
  tools/github_poBranch_update_key.enc
  tools/install_ubuntu_docs_dependencies.sh
  tools/rclone.conf.enc
  tox.ini
Labels: Changelog: None

#10523 Add Python standard library to Intersphinx mapping
  docs/conf.py
Labels: documentation, stable backport potential, Changelog: None

#10522 Add exceptions to API documentation
  docs/apidoc/exceptions.rst
  docs/apidoc/index.rst
  qiskit/algorithms/amplitude_estimators/ae.py
  qiskit/circuit/__init__.py
  qiskit/circuit/exceptions.py
  qiskit/dagcircuit/__init__.py
  qiskit/exceptions.py
  qiskit/extensions/__init__.py
  qiskit/opflow/gradients/circuit_gradients/lin_comb.py
  qiskit/passmanager/__init__.py
  qiskit/providers/__init__.py
  qiskit/pulse/__init__.py
  qiskit/qasm2/__init__.py
  qiskit/qpy/__init__.py
  qiskit/qpy/exceptions.py
  qiskit/transpiler/__init__.py
  qiskit/transpiler/passes/synthesis/unitary_synthesis.py
Labels: documentation, stable backport potential, Changelog: None

#10619 Fixing the tools for plotting Pauli vec
  qiskit/visualization/state_visualization.py
  releasenotes/notes/paulivecplot-normalization-5dd3cf3393c75afb.yaml
  test/python/visualization/test_state_plot_tools.py
  test/visual/mpl/graph/references/paulivec.png
Labels: stable backport potential, Changelog: Bugfix

#10635 Fix repository_owner condition docs_deploy gha job
  .github/workflows/docs_deploy.yml
Labels: Changelog: None

#10540 Bump hashbrown to 0.14.0.
  Cargo.lock
  crates/accelerate/Cargo.toml
  crates/qasm2/Cargo.toml
Labels: Changelog: None, Rust

#10437 Reject bad values in `SparsePauliOp.paulis` setter
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
  releasenotes/notes/sparse-pauli-op-constraint-pauli-setter-52f6f89627d1937c.yaml
  test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
Labels: stable backport potential, Changelog: Bugfix, mod: quantum info, Community PR

#9536 Fix classical-synthesis label ordering with `registerless=False`
  qiskit/circuit/classicalfunction/classicalfunction.py
  qiskit/circuit/classicalfunction/utils.py
  releasenotes/notes/fix_9363-445db8fde1244e57.yaml
  test/python/classical_function_compiler/test_synthesis.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: stable backport potential, Changelog: Bugfix

#10423 constructing cliffords from linear functions and permutation gates
  qiskit/quantum_info/operators/symplectic/clifford.py
  qiskit/quantum_info/operators/symplectic/clifford_circuits.py
  releasenotes/notes/add-clifford-from-linear-and-permutation-7a2bdbaae7c1c7e8.yaml
  test/python/circuit/library/test_linear_function.py
  test/python/quantum_info/operators/symplectic/test_clifford.py
Labels: Changelog: New Feature, mod: quantum info

#10639 Revert to one release notes file
  docs/legacy_release_notes.rst
  docs/release_notes.rst
Labels: documentation, stable backport potential, Changelog: None

#10655 Pin sphinx version to less than 7.2
  requirements-dev.txt
Labels: type: qa, stable backport potential, Changelog: None

#10652 Fix performance of Sabre rust<->Python boundary
  crates/accelerate/src/sabre_layout.rs
  crates/accelerate/src/sabre_swap/mod.rs
  qiskit/transpiler/passes/routing/sabre_swap.py
  releasenotes/notes/fix-sabre-performance-1b4503b6ecde6d13.yaml
Labels: priority: high, Changelog: Bugfix

#10644 Prepare 0.25.1 release
  .github/workflows/docs_deploy.yml
  docs/conf.py
  docs/release_notes.rst
  qiskit/VERSION.txt
  qiskit_pkg/setup.py
  setup.py
Labels: Changelog: None

#10664 Fix error message at class SparsePauliOp
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
Labels: Changelog: None, Community PR

#10584 Update README.md to include sampler and estimator
  README.md
Labels: documentation, Changelog: None

#10663 Fix release jobs post-0.25.1 release
  azure-pipelines.yml
Labels: type: qa, stable backport potential, Changelog: None

#10640 Refer to IBM docs
  docs/_static/images/1xp.png
  docs/conf.py
  docs/index.rst
  requirements-dev.txt
Labels: documentation, stable backport potential, Changelog: None

#10621 Migrate translation stage to plugins
  qiskit/transpiler/preset_passmanagers/builtin_plugins.py
  qiskit/transpiler/preset_passmanagers/level0.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  setup.py
Labels: Changelog: None, mod: transpiler

#10623 Remove unsupported PassManager for scheduling stage
  qiskit/transpiler/preset_passmanagers/level3.py
Labels: Changelog: None

#10683 Remove workaround for abi3 BigUint -> Python int conversio
  crates/accelerate/src/results/marginalization.rs
Labels: performance, Changelog: None, Rust

#10622 Migrate layout stage to plugins
  qiskit/transpiler/preset_passmanagers/builtin_plugins.py
  qiskit/transpiler/preset_passmanagers/level0.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  qiskit/transpiler/preset_passmanagers/plugin.py
  releasenotes/notes/default-reserved-plugin-name-3825c2000a579e38.yaml
  setup.py
  test/python/transpiler/test_preset_passmanagers.py
Labels: Changelog: API Change, mod: transpiler

#10686 Fix warning on `__qiskit_version__`
  qiskit/version.py
  test/python/test_version.py
Labels: stable backport potential, Changelog: None

#10581 Optimization stage as a plugin.
  qiskit/transpiler/preset_passmanagers/builtin_plugins.py
  qiskit/transpiler/preset_passmanagers/level0.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  qiskit/transpiler/preset_passmanagers/plugin.py
  releasenotes/notes/default-reserved-plugin-name-3825c2000a579e38.yaml
  setup.py
  test/python/transpiler/test_preset_passmanagers.py
Labels: Changelog: New Feature, Intern PR, mod: transpiler

#10689 Migrate init stage to plugins
  qiskit/transpiler/preset_passmanagers/builtin_plugins.py
  qiskit/transpiler/preset_passmanagers/level0.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  qiskit/transpiler/preset_passmanagers/plugin.py
  releasenotes/notes/default-reserved-plugin-name-3825c2000a579e38.yaml
  setup.py
  test/python/transpiler/test_preset_passmanagers.py
Labels: Changelog: API Change, mod: transpiler

#10696 Add Qiskit 0.44.1 to release version table
  docs/release_notes.rst
Labels: documentation, Changelog: None

#10591 Keep resets at beginning of circuits
  docs/conf.py
  qiskit/transpiler/preset_passmanagers/builtin_plugins.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  releasenotes/notes/keep-initial-resets-a5f75cb16c8edb57.yaml
  test/python/compiler/test_transpiler.py
Labels: Changelog: API Change, mod: transpiler

#10702 Do not deepcopy operations in Unroll3qOrMore
  qiskit/transpiler/passes/basis/unroll_3q_or_more.py
Labels: performance, Changelog: None

#10682 Remove algorithms tutorials
  .azure/tutorials-linux.yml
  .github/workflows/docs_deploy.yml
  docs/tutorials.rst
  docs/tutorials/algorithms/placeholder.ipynb
Labels: documentation, stable backport potential, Changelog: None

#10711 Typos flagged by the IBM Quantum Platform automatic spellchecker
  docs/configuration.rst
  docs/release_notes.rst
  qiskit/circuit/controlflow/if_else.py
  qiskit/circuit/library/data_preparation/pauli_feature_map.py
  qiskit/circuit/library/n_local/n_local.py
  qiskit/circuit/parametertable.py
  qiskit/circuit/quantumcircuit.py
  qiskit/dagcircuit/dagcircuit.py
  qiskit/primitives/backend_estimator.py
  qiskit/providers/__init__.py
  qiskit/providers/options.py
  qiskit/qasm2/__init__.py
  qiskit/qpy/__init__.py
  qiskit/quantum_info/operators/custom_iterator.py
  qiskit/quantum_info/operators/symplectic/clifford.py
  qiskit/quantum_info/states/stabilizerstate.py
  qiskit/quantum_info/synthesis/two_qubit_decompose.py
  qiskit/result/mitigation/base_readout_mitigator.py
  qiskit/result/mitigation/correlated_readout_mitigator.py
  qiskit/result/mitigation/local_readout_mitigator.py
  qiskit/synthesis/clifford/clifford_decompose_greedy.py
  qiskit/synthesis/evolution/lie_trotter.py
  qiskit/synthesis/evolution/product_formula.py
  qiskit/synthesis/evolution/qdrift.py
  qiskit/synthesis/evolution/suzuki_trotter.py
  qiskit/transpiler/__init__.py
  qiskit/transpiler/passes/basis/unroll_3q_or_more.py
  qiskit/transpiler/passes/optimization/collect_multiqubit_blocks.py
  qiskit/transpiler/passes/optimization/crosstalk_adaptive_schedule.py
  qiskit/transpiler/passes/optimization/inverse_cancellation.py
  qiskit/transpiler/passes/scheduling/alignments/check_durations.py
  qiskit/transpiler/passes/scheduling/padding/base_padding.py
  qiskit/transpiler/passes/scheduling/scheduling/set_io_latency.py
  qiskit/transpiler/target.py
  qiskit/utils/__init__.py
  releasenotes/notes/0.13/suppress-packaging-warnings-396b38feb6b3d52f.yaml
Labels: documentation, stable backport potential, Changelog: None

#10642 Add validation to Sampler if there are no measurements
  qiskit/primitives/base/base_sampler.py
  releasenotes/notes/sampler-with-no-measure-6cd3a05555187b58.yaml
  test/python/primitives/test_sampler.py
Labels: stable backport potential, Changelog: Bugfix, mod: primitives

#10723 Fix test suite to account for beta numpy versions
  test/python/algorithms/optimizers/test_optimizers_scikitquant.py
Labels: type: qa, stable backport potential, mod: algorithms, Changelog: None, Community PR

#10719 change the url for the pip metadata
  setup.py
Labels: stable backport potential, Changelog: None

#10414 Add display of internal circuits for ControlFlowOps to text drawer
  qiskit/visualization/circuit/text.py
  releasenotes/notes/display-control-flow-text-8db4f15a68bf5322.yaml
  test/python/visualization/test_circuit_drawer.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: Changelog: New Feature, mod: visualization

#10730 Remove tox version cap
  tools/install_ubuntu_docs_dependencies.sh
Labels: type: qa, stable backport potential, Changelog: None

#10712 Fix virtual/physical-qubit distinction in Sabre
  crates/accelerate/src/sabre_layout.rs
  crates/accelerate/src/sabre_swap/mod.rs
  crates/accelerate/src/sabre_swap/sabre_dag.rs
  qiskit/transpiler/passes/layout/sabre_layout.py
  qiskit/transpiler/passes/routing/sabre_swap.py
Labels: Changelog: None, mod: transpiler

#10729 Cache DAGOpNode sort keys
  qiskit/dagcircuit/dagcircuit.py
  qiskit/dagcircuit/dagnode.py
Labels: performance, Changelog: None, mod: transpiler

#10692 Set up redirects for functions moved to module pages
  docs/api_redirects.txt
  docs/conf.py
  requirements-dev.txt
Labels: documentation, stable backport potential, Changelog: None

#10547 Fix broken documentation references in `qiskit.providers`
  qiskit/providers/__init__.py
  qiskit/providers/backend.py
  qiskit/providers/basicaer/basicaerjob.py
  qiskit/providers/basicaer/qasm_simulator.py
  qiskit/providers/basicaer/unitary_simulator.py
  qiskit/providers/fake_provider/__init__.py
  qiskit/providers/fake_provider/fake_backend.py
  qiskit/providers/models/__init__.py
  qiskit/providers/models/backendconfiguration.py
  qiskit/providers/models/backendproperties.py
  qiskit/providers/models/jobstatus.py
  qiskit/providers/models/pulsedefaults.py
Labels: documentation, Changelog: None

#10740 Fix potential non-determinism in SabreSwap rust code
  crates/accelerate/src/sabre_swap/layer.rs
  crates/accelerate/src/sabre_swap/mod.rs
Labels: Changelog: None, Rust
