Repository Qiskit/qiskit, pull requests merged in 2023-10, with the labels that each got.

#9337 Fix documentation of qiskit.circuit.classicalfunction
  qiskit/circuit/classicalfunction/__init__.py
Labels: documentation, stable backport potential, Changelog: None

#10945 Update estimator.py
  qiskit/primitives/estimator.py
Labels: Changelog: None

#10914 Prepare 0.25.2 release
  crates/accelerate/Cargo.toml
  crates/qasm2/Cargo.toml
  docs/conf.py
  docs/release_notes.rst
  qiskit/VERSION.txt
  releasenotes/notes/fix-clifford-from-diagonal-7708654373bd5b8b.yaml
  releasenotes/notes/fix_pauli_new_style_bit-0704933127b4debe.yaml
  releasenotes/notes/prepare-0.25.2-69e6db49ca39da3f.yaml
  setup.py
Labels: Changelog: None

#10660 Add `check_input` option to `UnitaryGate`
  qiskit/circuit/library/generalized_gates/unitary.py
  qiskit/transpiler/passes/optimization/consolidate_blocks.py
  releasenotes/notes/add-skip_check-option-UnitaryGate-fb3fad8a9ac3c156.yaml
Labels: performance, Changelog: New Feature

#10835 Improve the ergonomics of the TranspileLayout class
  qiskit/passmanager/passrunner.py
  qiskit/qpy/__init__.py
  qiskit/qpy/binary_io/circuits.py
  qiskit/qpy/formats.py
  qiskit/transpiler/basepasses.py
  qiskit/transpiler/layout.py
  qiskit/transpiler/runningpassmanager.py
  releasenotes/notes/transpile-layout-improvements-118dd902d93e5b96.yaml
  test/python/transpiler/test_transpile_layout.py
Labels: Changelog: New Feature, mod: primitives, mod: transpiler

#10948 Bump metapackage versions
  qiskit_pkg/setup.py
Labels: type: qa, Changelog: None

#10850 Fix bug in qs_decomposition
  qiskit/quantum_info/synthesis/qsd.py
  releasenotes/notes/10787-078d7caa70fc7de8.yaml
  test/python/quantum_info/test_synthesis.py
Labels: stable backport potential, Changelog: Bugfix

#10951 Optimize Quantumcircuit.decompose
  qiskit/circuit/quantumcircuit.py
Labels: performance, Changelog: None, Community PR

#10955 Bump package version for post release
  qiskit_pkg/setup.py
  setup.py
Labels: Changelog: None

#10966 Fix approximation=True usage in opflow migration guide
  docs/migration_guides/opflow_migration.rst
Labels: documentation, stable backport potential, mod: opflow, Changelog: None, Community PR

#10973 Avoid useless deepcopy of target with custom pulse gates in transpile
  qiskit/compiler/transpiler.py
Labels: stable backport potential, performance, Changelog: Bugfix

#9700 Support dynamic circuit in BackendEstimator
  qiskit/primitives/backend_estimator.py
  releasenotes/notes/primitives-dynamic-circuit-b489f82df47af138.yaml
  test/python/primitives/test_backend_estimator.py
  test/python/primitives/test_estimator.py
Labels: priority: high, stable backport potential, Changelog: Bugfix, mod: primitives

#10941 Fix IQX color schemes
  qiskit/visualization/circuit/styles/iqx-dark.json
  qiskit/visualization/circuit/styles/iqx.json
  releasenotes/notes/fix-iqx-colors-a744cea132896e53.yaml
  test/visual/mpl/circuit/references/iqx-dark_color.png
  test/visual/mpl/circuit/references/iqx_color.png
  test/visual/mpl/circuit/references/textbook_color.png
  test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py
Labels: Changelog: Bugfix

#10891 Remove use of singleton aliases removed in Numpy 2
  test/python/circuit/test_parameters.py
Labels: stable backport potential, Changelog: None

#10890 Remove use of dtype aliases to be removed in Numpy 2
  qiskit/pulse/library/continuous.py
  qiskit/pulse/library/samplers/decorators.py
  qiskit/pulse/library/waveform.py
  qiskit/quantum_info/states/quantum_state.py
  qiskit/result/postprocess.py
  qiskit/transpiler/synthesis/aqc/fast_gradient/fast_gradient.py
  qiskit/transpiler/synthesis/aqc/fast_gradient/layer.py
  qiskit/transpiler/synthesis/aqc/fast_gradient/pmatrix.py
  test/python/pulse/test_builder.py
  test/python/pulse/test_continuous_pulses.py
  test/python/result/test_result.py
  test/python/transpiler/aqc/fast_gradient/test_layer1q.py
  test/python/transpiler/aqc/fast_gradient/test_layer2q.py
  test/python/transpiler/aqc/fast_gradient/test_utils.py
  test/python/transpiler/aqc/fast_gradient/utils_for_testing.py
  test/python/transpiler/aqc/test_aqc.py
Labels: stable backport potential, Changelog: None

#10997 Pin `cvxpy` to known-good version
  constraints.txt
Labels: type: qa, stable backport potential, Changelog: None

#10789 Better align 1q euler decomposition output to multiples of π/2
  crates/accelerate/src/euler_one_qubit_decomposer.rs
  test/python/circuit/test_circuit_qasm.py
  test/python/qasm2/test_export.py
  test/python/transpiler/test_dynamical_decoupling.py
  test/qpy_compat/test_qpy.py
Labels: mod: quantum info, Changelog: None

#10846 Fix deprecated behaviour in timeline drawer
  qiskit/visualization/timeline/core.py
  qiskit/visualization/timeline/generators.py
  releasenotes/notes/timeline-visualisation-deprecated-bit-index-7277aa6e2a903cb7.yaml
  test/python/visualization/timeline/test_generators.py
Labels: Changelog: New Feature, mod: visualization

#10875 Fix hash of `Parameter` and `ParameterExpression`
  qiskit/circuit/parameter.py
  qiskit/circuit/parameterexpression.py
  qiskit/circuit/parametervector.py
  qiskit/pulse/schedule.py
  qiskit/qpy/binary_io/value.py
  releasenotes/notes/fix-parameter-hash-d22c270090ffc80e.yaml
  test/python/circuit/test_parameters.py
Labels: Changelog: New Feature, Changelog: Bugfix

#10947 Add `apply_layout` method to `SparsePauliOp`
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
  releasenotes/notes/sparse-pauli-op-apply-layout-43149125d29ad015.yaml
  test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
Labels: Changelog: New Feature, mod: quantum info, mod: primitives, mod: transpiler

#10956 BackendEstimator support BackendV2 without coupling_map
  qiskit/primitives/backend_estimator.py
  releasenotes/notes/backend-estimator-v2-support-a698353aeeb5236c.yaml
  test/python/primitives/test_backend_estimator.py
Labels: stable backport potential, performance, Changelog: Bugfix, mod: primitives

#10800 Add global-phase support to control-flow builders
  qiskit/circuit/controlflow/_builder_utils.py
  qiskit/circuit/controlflow/builder.py
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/fix-global-phase-control-flow-builders-38302f41302be928.yaml
  test/python/circuit/test_control_flow_builders.py
Labels: Changelog: Bugfix

#9846 Annotated operations
  qiskit/circuit/annotated_operation.py
  qiskit/converters/circuit_to_gate.py
  qiskit/quantum_info/operators/operator.py
  qiskit/transpiler/passes/synthesis/high_level_synthesis.py
  releasenotes/notes/add-annotated-operations-de35a0d8d98eec23.yaml
  test/python/circuit/test_annotated_operation.py
  test/python/compiler/test_transpiler.py
  test/python/transpiler/test_high_level_synthesis.py
Labels: priority: high, Changelog: New Feature

#10905 Deprecation of algorithm utils (`algorithm_globals` and `validation`)
  qiskit/algorithms/amplitude_amplifiers/grover.py
  qiskit/algorithms/eigensolvers/numpy_eigensolver.py
  qiskit/algorithms/minimum_eigensolvers/adapt_vqe.py
  qiskit/algorithms/minimum_eigensolvers/qaoa.py
  qiskit/algorithms/optimizers/aqgd.py
  qiskit/algorithms/optimizers/gsls.py
  qiskit/algorithms/optimizers/p_bfgs.py
  qiskit/algorithms/optimizers/scipy_optimizer.py
  qiskit/algorithms/optimizers/spsa.py
  qiskit/algorithms/optimizers/umda.py
  qiskit/algorithms/time_evolvers/pvqd/pvqd.py
  qiskit/algorithms/utils/validate_initial_point.py
  qiskit/opflow/evolutions/trotterizations/qdrift.py
  qiskit/opflow/operator_base.py
  qiskit/opflow/state_fns/dict_state_fn.py
  qiskit/opflow/state_fns/vector_state_fn.py
  qiskit/synthesis/evolution/qdrift.py
  qiskit/utils/algorithm_globals.py
  qiskit/utils/validation.py
  releasenotes/notes/deprecate-algorithm-utils-6cdc5856015a7e65.yaml
  test/python/algorithms/eigensolvers/test_vqd.py
  test/python/algorithms/evolvers/trotterization/test_trotter_qrte.py
  test/python/algorithms/minimum_eigensolvers/test_adapt_vqe.py
  test/python/algorithms/minimum_eigensolvers/test_qaoa.py
  test/python/algorithms/minimum_eigensolvers/test_qaoa_opflow.py
  test/python/algorithms/minimum_eigensolvers/test_sampling_vqe.py
  test/python/algorithms/minimum_eigensolvers/test_vqe.py
  test/python/algorithms/optimizers/test_optimizer_aqgd.py
  test/python/algorithms/optimizers/test_optimizer_nft.py
  test/python/algorithms/optimizers/test_optimizers.py
  test/python/algorithms/optimizers/test_optimizers_scikitquant.py
  test/python/algorithms/optimizers/test_spsa.py
  test/python/algorithms/optimizers/test_umda.py
  test/python/algorithms/test_aux_ops_evaluator.py
  test/python/algorithms/test_backendv1.py
  test/python/algorithms/test_grover.py
  test/python/algorithms/test_measure_error_mitigation.py
  test/python/algorithms/test_observables_evaluator.py
  test/python/algorithms/test_qaoa.py
  test/python/algorithms/test_validation.py
  test/python/algorithms/test_vqd.py
  test/python/algorithms/test_vqe.py
  test/python/algorithms/time_evolvers/test_pvqd.py
  test/python/algorithms/time_evolvers/test_trotter_qrte.py
  test/python/algorithms/time_evolvers/variational/test_var_qite.py
  test/python/algorithms/time_evolvers/variational/test_var_qrte.py
  test/python/algorithms/utils/test_validate_bounds.py
  test/python/algorithms/utils/test_validate_initial_point.py
  test/python/circuit/library/test_evolution_gate.py
  test/python/opflow/test_cvar.py
  test/python/opflow/test_evolution.py
  test/python/opflow/test_gradients.py
  test/python/opflow/test_pauli_expectation.py
Labels: Changelog: Deprecation, mod: algorithms

#11012 Remove patching of `SwapGate.__new__` from Sabre test
  test/python/transpiler/test_sabre_swap.py
Labels: type: qa, Changelog: None

#11015 Hardcode missing names in QPY backwards-compat tests
  test/qpy_compat/test_qpy.py
Labels: type: qa, stable backport potential, Changelog: None, mod: qpy

#11014 Rewrite singleton handling including `SingletonInstruction`
  docs/apidoc/circuit_singleton.rst
  docs/apidoc/index.rst
  qiskit/circuit/__init__.py
  qiskit/circuit/controlledgate.py
  qiskit/circuit/instruction.py
  qiskit/circuit/library/standard_gates/dcx.py
  qiskit/circuit/library/standard_gates/ecr.py
  qiskit/circuit/library/standard_gates/h.py
  qiskit/circuit/library/standard_gates/i.py
  qiskit/circuit/library/standard_gates/iswap.py
  qiskit/circuit/library/standard_gates/s.py
  qiskit/circuit/library/standard_gates/swap.py
  qiskit/circuit/library/standard_gates/sx.py
  qiskit/circuit/library/standard_gates/t.py
  qiskit/circuit/library/standard_gates/x.py
  qiskit/circuit/library/standard_gates/y.py
  qiskit/circuit/library/standard_gates/z.py
  qiskit/circuit/singleton.py
  qiskit/circuit/singleton_gate.py
  qiskit/qasm2/export.py
  qiskit/qasm3/exporter.py
  qiskit/qpy/binary_io/circuits.py
  qiskit/transpiler/passes/optimization/hoare_opt.py
  qiskit/transpiler/passes/optimization/optimize_1q_commutation.py
  qiskit/transpiler/passes/optimization/template_matching/template_substitution.py
  qiskit/transpiler/passes/synthesis/unitary_synthesis.py
  qiskit/transpiler/target.py
  qiskit/visualization/circuit/text.py
  releasenotes/notes/singletons-83782de8bd062cbc.yaml
  test/python/circuit/library/test_evolution_gate.py
  test/python/circuit/test_gate_definitions.py
  test/python/circuit/test_singleton.py
Labels: priority: high, performance, Changelog: New Feature, mod: circuit

#10809 Fix qpy for controlled `UnitaryGate`
  qiskit/qpy/binary_io/circuits.py
  releasenotes/notes/fix-qpy-controlled-unitary-26355d6ffa4cd2fb.yaml
  test/python/circuit/test_circuit_load_from_qpy.py
Labels: stable backport potential, Changelog: Bugfix, mod: qpy

#10634 Add NormalizeRXAngle and RXCalibrationBuilder passes
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/calibration/__init__.py
  qiskit/transpiler/passes/calibration/builders.py
  qiskit/transpiler/passes/calibration/rx_builder.py
  qiskit/transpiler/passes/optimization/__init__.py
  qiskit/transpiler/passes/optimization/normalize_rx_angle.py
  releasenotes/notes/single-pulse-rx-cal-347aadcee7bfe60b.yaml
  test/python/transpiler/test_calibrationbuilder.py
  test/python/transpiler/test_normalize_rx_angle.py
Labels: mod: pulse, Community PR, mod: transpiler

#10851 Fix deprecation warning of unscheduled circuits in timeline drawer
  qiskit/transpiler/passes/scheduling/dynamical_decoupling.py
  qiskit/visualization/timeline/core.py
  releasenotes/notes/fix-timeline-draw-unscheduled-warning-873f7a24c6b51e2c.yaml
Labels: Changelog: Deprecation, mod: pulse, mod: visualization, mod: transpiler

#10829 Starting layout analysis pass for sabre
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/layout/__init__.py
  qiskit/transpiler/passes/layout/sabre_pre_layout.py
  releasenotes/notes/add-sabre-starting-layout-7e151b7abb8a6c13.yaml
  test/python/transpiler/test_sabre_layout.py
  test/python/transpiler/test_sabre_pre_layout.py
Labels: Changelog: New Feature

#10786 Use only discrete-basis translations in `GateDirection`
  qiskit/transpiler/passes/utils/gate_direction.py
  releasenotes/notes/discrete-basis-gatedirection-bdffad3b47c1c532.yaml
  test/python/compiler/test_transpiler.py
  test/python/transpiler/test_gate_direction.py
Labels: Changelog: Bugfix, mod: transpiler

#10898 Singleton parameterless controlled gates
  qiskit/circuit/add_control.py
  qiskit/circuit/controlledgate.py
  qiskit/circuit/library/standard_gates/h.py
  qiskit/circuit/library/standard_gates/s.py
  qiskit/circuit/library/standard_gates/swap.py
  qiskit/circuit/library/standard_gates/sx.py
  qiskit/circuit/library/standard_gates/x.py
  qiskit/circuit/library/standard_gates/y.py
  qiskit/circuit/library/standard_gates/z.py
  qiskit/circuit/singleton.py
  qiskit/qpy/binary_io/circuits.py
  releasenotes/notes/singletons-83782de8bd062cbc.yaml
  test/python/circuit/test_controlled_gate.py
  test/python/circuit/test_gate_definitions.py
  test/python/circuit/test_singleton.py
  test/python/dagcircuit/test_dagcircuit.py
Labels: priority: high, Changelog: New Feature, Changelog: API Change

#7146 Add IGate rules to standard equivalence library
  qiskit/circuit/library/standard_gates/equivalence_library.py
  test/python/transpiler/test_basis_translator.py
Labels: priority: medium

#10859 NoiseAdaptiveLayout to consider inconsistencies in backend
  qiskit/transpiler/passes/layout/noise_adaptive_layout.py
  qiskit/transpiler/preset_passmanagers/builtin_plugins.py
  releasenotes/notes/fixes_7677_1-b9322834cae57b68.yaml
  test/python/transpiler/test_preset_passmanagers.py
Labels: Changelog: Bugfix

#11027 Remove redundant closure / anonymous function
  crates/accelerate/src/sabre_swap/neighbor_table.rs
Labels: Changelog: None, Rust

#10815 removed deprecated PauliTable, StabilizerTable and tests
  qiskit/quantum_info/__init__.py
  qiskit/quantum_info/operators/__init__.py
  qiskit/quantum_info/operators/random.py
  qiskit/quantum_info/operators/symplectic/__init__.py
  qiskit/quantum_info/operators/symplectic/clifford.py
  qiskit/quantum_info/operators/symplectic/pauli_list.py
  qiskit/quantum_info/operators/symplectic/pauli_table.py
  qiskit/quantum_info/operators/symplectic/pauli_utils.py
  qiskit/quantum_info/operators/symplectic/random.py
  qiskit/quantum_info/operators/symplectic/stabilizer_table.py
  qiskit/quantum_info/random.py
  qiskit/test/base.py
  releasenotes/notes/remove-deprecated-in-quantum-info-0f9bd2b0c093307d.yaml
  test/python/opflow/test_pauli_sum_op.py
  test/python/quantum_info/operators/symplectic/test_clifford.py
  test/python/quantum_info/operators/symplectic/test_pauli_list.py
  test/python/quantum_info/operators/symplectic/test_pauli_table.py
  test/python/quantum_info/operators/symplectic/test_pauli_utils.py
  test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
  test/python/quantum_info/operators/symplectic/test_stabilizer_table.py
  test/python/quantum_info/operators/test_random.py
Labels: Changelog: Removal, mod: quantum info, Community PR

#10607 Deprecate Unroller pass
  qiskit/circuit/add_control.py
  qiskit/compiler/transpiler.py
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/basis/unroller.py
  qiskit/transpiler/preset_passmanagers/__init__.py
  releasenotes/notes/deprecate-unroller-2081d35d6d83e7e9.yaml
  test/python/circuit/test_controlled_gate.py
  test/python/circuit/test_instruction_repeat.py
  test/python/qasm2/test_circuit_methods.py
  test/python/qasm2/test_legacy_importer.py
  test/python/transpiler/test_optimize_1q_gates.py
  test/python/transpiler/test_pass_call.py
  test/python/transpiler/test_passmanager.py
  test/python/transpiler/test_preset_passmanagers.py
  test/python/transpiler/test_staged_passmanager.py
  test/python/transpiler/test_unroller.py
  test/python/visualization/references/pass_manager_standard.dot
  test/python/visualization/references/pass_manager_style.dot
  test/python/visualization/test_pass_manager_drawer.py
  test/qpy_compat/test_qpy.py
Labels: Changelog: Deprecation, Changelog: API Change

#10618 Fix commutation analysis to group gates into blocks of pairwise commuting gates
  qiskit/transpiler/passes/optimization/commutation_analysis.py
  releasenotes/notes/fix-commutative-analysis-e74083969db46d0f.yaml
  test/python/transpiler/test_commutative_cancellation.py
Labels: Changelog: Bugfix

#10707 Inline parameter binding as part of BasisTranslator
  qiskit/transpiler/passes/basis/basis_translator.py
Labels: performance, Changelog: None, mod: transpiler

#11022 missing execquote in `api/qiskit/transpiler_synthesis_plugins`
  qiskit/transpiler/passes/synthesis/plugin.py
Labels: documentation, Changelog: None

#10754 Removed code deprecated in qiskit-terra 0.21, released on June 2022
  qiskit/execute_function.py
  qiskit/pulse/transforms/alignments.py
  qiskit/qpy/interface.py
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/scheduling/__init__.py
  qiskit/transpiler/passes/scheduling/alap.py
  qiskit/transpiler/passes/scheduling/alignments/__init__.py
  qiskit/transpiler/passes/scheduling/alignments/align_measures.py
  qiskit/transpiler/passes/scheduling/asap.py
  qiskit/transpiler/passes/scheduling/dynamical_decoupling.py
  qiskit/transpiler/passes/utils/__init__.py
  qiskit/transpiler/passes/utils/check_cx_direction.py
  qiskit/transpiler/passes/utils/cx_direction.py
  releasenotes/notes/removed_deprecated_0.21-6c93f7bbc50ae40e.yaml
  test/benchmarks/scheduling_passes.py
  test/python/transpiler/legacy_scheduling/test_instruction_alignments.py
  test/python/transpiler/legacy_scheduling/test_scheduling_pass.py
  test/python/transpiler/test_instruction_alignments.py
Labels: Changelog: Removal, Community PR

#11003 Update docs homepage banners
  docs/conf.py
  docs/index.rst
Labels: documentation, stable backport potential, Changelog: None

#11040 Add singleton lookup-key logic
  qiskit/circuit/library/standard_gates/dcx.py
  qiskit/circuit/library/standard_gates/ecr.py
  qiskit/circuit/library/standard_gates/h.py
  qiskit/circuit/library/standard_gates/i.py
  qiskit/circuit/library/standard_gates/iswap.py
  qiskit/circuit/library/standard_gates/s.py
  qiskit/circuit/library/standard_gates/swap.py
  qiskit/circuit/library/standard_gates/sx.py
  qiskit/circuit/library/standard_gates/t.py
  qiskit/circuit/library/standard_gates/x.py
  qiskit/circuit/library/standard_gates/y.py
  qiskit/circuit/library/standard_gates/z.py
  qiskit/circuit/singleton.py
  qiskit/transpiler/passes/optimization/hoare_opt.py
  test/python/circuit/test_singleton.py
Labels: performance, Changelog: None, mod: circuit

#10869 Add display of expressions to circuit drawers
  qiskit/circuit/quantumcircuit.py
  qiskit/visualization/circuit/_utils.py
  qiskit/visualization/circuit/circuit_visualization.py
  qiskit/visualization/circuit/matplotlib.py
  qiskit/visualization/circuit/text.py
  releasenotes/notes/add-expr-to-drawers-7a1ffa802064cad7.yaml
  test/python/visualization/test_circuit_text_drawer.py
  test/visual/mpl/circuit/references/for_loop.png
  test/visual/mpl/circuit/references/for_loop_1_qarg.png
  test/visual/mpl/circuit/references/for_loop_range.png
  test/visual/mpl/circuit/references/if_op_expr.png
  test/visual/mpl/circuit/references/if_op_expr_nested.png
  test/visual/mpl/circuit/references/layout_control_flow.png
  test/visual/mpl/circuit/references/nested_layout_control_flow.png
  test/visual/mpl/circuit/references/switch_case.png
  test/visual/mpl/circuit/references/switch_case_1_qarg.png
  test/visual/mpl/circuit/references/switch_expr.png
  test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py
Labels: Changelog: New Feature, mod: visualization

#10127 Pass manager refactoring: cleanup internals
  qiskit/passmanager/__init__.py
  qiskit/passmanager/base_pass.py
  qiskit/passmanager/base_tasks.py
  qiskit/passmanager/compilation_status.py
  qiskit/passmanager/flow_controllers.py
  qiskit/passmanager/passmanager.py
  qiskit/passmanager/passrunner.py
  qiskit/passmanager/propertyset.py
  qiskit/transpiler/__init__.py
  qiskit/transpiler/basepasses.py
  qiskit/transpiler/fencedobjs.py
  qiskit/transpiler/passmanager.py
  qiskit/transpiler/propertyset.py
  qiskit/transpiler/runningpassmanager.py
  releasenotes/notes/add-passmanager-module-3ae30cff52cb83f1.yaml
  test/python/transpiler/test_pass_scheduler.py
  test/python/transpiler/test_passmanager.py
Labels: priority: high, Changelog: Deprecation, Changelog: New Feature, Changelog: API Change, mod: transpiler

#10988 schedule() considers instruction map
  qiskit/compiler/scheduler.py
  qiskit/scheduler/lowering.py
  qiskit/scheduler/methods/basic.py
  qiskit/scheduler/schedule_circuit.py
  qiskit/scheduler/sequence.py
  releasenotes/notes/Adding-BackendV2-support-to-schedule-of-qiskit.compiler.scheduler-a0366d3397c73af0.yaml
  test/python/scheduler/test_basic_scheduler.py
Labels: Changelog: New Feature, Changelog: Bugfix, mod: pulse, Community PR

#11043 Fix typo in contributing_to_qiskit.rst
  docs/contributing_to_qiskit.rst
Labels: documentation, Changelog: None, Community PR

#10999 Pivot to gha for wheel builds and pypi trusted publishers
  .azure/wheels.yml
  .github/workflows/wheels.yml
  azure-pipelines.yml
Labels: type: qa, priority: high, stable backport potential, Changelog: None

#10734 Add UnitaryOverlap to the circuit library
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/overlap.py
  releasenotes/notes/unitary-overlap-7dde87a8e2d7a1f7.yaml
  test/python/circuit/library/test_overlap.py
Labels: priority: high, Changelog: New Feature

#11009 Fix build filter coupling map with mix ideal/physical targets
  qiskit/transpiler/target.py
  releasenotes/notes/fix-handling-of-mixed-ideal-target-with-filter-qubits-171894cb758356ca.yaml
  test/python/transpiler/test_target.py
Labels: stable backport potential, Changelog: Bugfix

#10965 Merging `UnrollCustomDefinitions` into `HighLevelSynthesis` as a single pass
  qiskit/transpiler/passes/synthesis/high_level_synthesis.py
  qiskit/transpiler/preset_passmanagers/common.py
  releasenotes/notes/hls-with-recursion-and-ucd-b559beb3a148fe59.yaml
  test/python/transpiler/test_high_level_synthesis.py
Labels: priority: medium, Changelog: New Feature

#11032 Add base-gate callback to `CUGate.params` return
  qiskit/circuit/controlledgate.py
  qiskit/circuit/instruction.py
  qiskit/circuit/library/standard_gates/equivalence_library.py
  qiskit/circuit/library/standard_gates/u.py
  releasenotes/notes/fix-cu-assign-parameters-fbf6f21d3e0c8c0b.yaml
  test/python/circuit/test_controlled_gate.py
Labels: Changelog: Bugfix

#11013 Add duration and unit kwargs to __init__ for all standard gates
  qiskit/circuit/library/standard_gates/global_phase.py
  qiskit/circuit/library/standard_gates/p.py
  qiskit/circuit/library/standard_gates/r.py
  qiskit/circuit/library/standard_gates/rx.py
  qiskit/circuit/library/standard_gates/rxx.py
  qiskit/circuit/library/standard_gates/ry.py
  qiskit/circuit/library/standard_gates/ryy.py
  qiskit/circuit/library/standard_gates/rz.py
  qiskit/circuit/library/standard_gates/rzx.py
  qiskit/circuit/library/standard_gates/rzz.py
  qiskit/circuit/library/standard_gates/s.py
  qiskit/circuit/library/standard_gates/u.py
  qiskit/circuit/library/standard_gates/u1.py
  qiskit/circuit/library/standard_gates/u2.py
  qiskit/circuit/library/standard_gates/u3.py
  qiskit/circuit/library/standard_gates/x.py
  qiskit/circuit/library/standard_gates/xx_minus_yy.py
  qiskit/circuit/library/standard_gates/xx_plus_yy.py
  qiskit/circuit/measure.py
  qiskit/circuit/reset.py
Labels: Changelog: None

#11031 Fix input normalisation of `transpile(initial_layout=...)`
  qiskit/compiler/transpiler.py
  releasenotes/notes/fix-input-normalization-of-transpile-initial-layout.yaml
  test/python/transpiler/test_transpile_layout.py
Labels: stable backport potential, Changelog: Bugfix, mod: transpiler

#11059 Bump main branch version post 0.45.0rc1 tag
  .mergify.yml
  Cargo.lock
  Cargo.toml
  docs/conf.py
  qiskit/VERSION.txt
  qiskit_pkg/setup.py
Labels: Changelog: None

#11060 Move one last release note for 0.45.0
  releasenotes/notes/0.45/fix-input-normalization-of-transpile-initial-layout.yaml
Labels: stable backport potential, Changelog: None

#11066 Fix bad version checker in "previous versions" documentation
  docs/conf.py
Labels: type: qa, Changelog: None

#11069 Relax tolerance of `UnitaryOverlap` tests
  test/python/circuit/library/test_overlap.py
Labels: type: qa, stable backport potential, Changelog: None

#11063 List support for coupling map in pass manager
  qiskit/transpiler/preset_passmanagers/__init__.py
  releasenotes/notes/preset-passmanager-coupling-map-89e588e4260cb214.yaml
  test/python/transpiler/test_preset_passmanagers.py
Labels: Community PR

#11070 Typo/grammar fixes on transpiler docs
  qiskit/transpiler/__init__.py
Labels: documentation, stable backport potential

#11065 Fix calling backend.name() for backendV2
  qiskit/utils/backend_utils.py
  releasenotes/notes/fix_backend_name-e84661707058b529.yaml
Labels: stable backport potential, Changelog: Bugfix

#11029 Add disable_validation option to SymbolicPulse
  qiskit/pulse/library/symbolic_pulses.py
  releasenotes/notes/symbolic-pulse-disable-validation-19cd8506b3a839b6.yaml
  test/python/pulse/test_pulse_lib.py
Labels: mod: pulse

#11080 fix: python function definition helper texts of directory qiskit/algorithms/optimizers/
  qiskit/algorithms/optimizers/gradient_descent.py
  qiskit/algorithms/optimizers/scipy_optimizer.py
  qiskit/algorithms/optimizers/spsa.py
  qiskit/algorithms/optimizers/steppable_optimizer.py
  qiskit/algorithms/optimizers/umda.py
Labels: documentation, stable backport potential, mod: algorithms, Community PR

#11023 Fix deprecated Numpy logic in `NormalizeRXAngles`
  qiskit/transpiler/passes/optimization/normalize_rx_angle.py
Labels: Changelog: None

#11084 Remove deprecated ``operators`` tutorials
  docs/tutorials.rst
  docs/tutorials/operators/01_operator_flow.ipynb
  docs/tutorials/operators/02_gradients_framework.ipynb
  docs/tutorials/operators/images/gradient_framework.png
Labels: documentation, Changelog: None

#11094 Emit a descriptive error when the QPY version is too new
  qiskit/qpy/interface.py
  releasenotes/notes/fix-error-message-qpy-version-cf0763da22ce2224.yaml
  test/python/qpy/test_circuit_load_from_qpy.py
  test/qpy_compat/process_version.sh
Labels: Changelog: Bugfix, mod: qpy

#10694 Qiskit Pulse - Introduce logical elements and frames
  docs/legacy_release_notes.rst
  qiskit/circuit/bit.py
  qiskit/circuit/library/generalized_gates/mcmt.py
  qiskit/circuit/quantumcircuit.py
  qiskit/converters/circuit_to_dag.py
  qiskit/dagcircuit/dagcircuit.py
  qiskit/dagcircuit/dagdependency.py
  qiskit/pulse/__init__.py
  qiskit/pulse/model/__init__.py
  qiskit/pulse/model/frames.py
  qiskit/pulse/model/logical_elements.py
  qiskit/pulse/model/mixed_frames.py
  qiskit/transpiler/__init__.py
  qiskit/transpiler/layout.py
  qiskit/transpiler/passes/optimization/normalize_rx_angle.py
  qiskit/transpiler/passes/routing/sabre_swap.py
  releasenotes/notes/0.20/bit-slots-17d6649872da0440.yaml
  releasenotes/notes/0.21/change-instruction-data-scalar-81f2066ca2435933.yaml
  releasenotes/notes/0.21/fix-reverse_bits-with-registerless-bits-6d17597b99640fb0.yaml
  releasenotes/notes/0.22/circuit-initialize-and-prepare-single-qubit-e25dacc8f873bc01.yaml
  releasenotes/notes/0.22/denselayout-loose-bits-3e66011432bc6232.yaml
  releasenotes/notes/0.23/fix-qpy-loose-bits-5283dc4ad3823ce3.yaml
  releasenotes/notes/0.24/fix-deprecated-bit-qpy-roundtrip-9a23a795aa677c71.yaml
  releasenotes/notes/0.25/fix-bit-copy-4b2f7349683f616a.yaml
  releasenotes/notes/0.45/remove-deprecated-code-in-0.19-a97ccfec62405b9a.yaml
  test/python/pulse/test_frames.py
  test/python/pulse/test_logical_elements.py
  test/python/pulse/test_mixed_frames.py
Labels: mod: pulse

#11092 Fix calling backend.name() for backendV2 (#11065) (#11076)
  qiskit/utils/backend_utils.py
  releasenotes/notes/fix_backend_name-e84661707058b529.yaml
Labels: Changelog: Bugfix

#11091 Typo/grammar fixes on transpiler docs (#11070) (#11075)
  qiskit/transpiler/__init__.py
Labels: documentation, Changelog: None

#11102 Prepare 0.25.3 release
  Cargo.lock
  Cargo.toml
  crates/accelerate/Cargo.toml
  crates/qasm2/Cargo.toml
  docs/conf.py
  docs/release_notes.rst
  qiskit/VERSION.txt
  qiskit_pkg/setup.py
  releasenotes/notes/backend-estimator-v2-support-a698353aeeb5236c.yaml
  releasenotes/notes/fix-error-message-qpy-version-cf0763da22ce2224.yaml
  releasenotes/notes/fix_backend_name-e84661707058b529.yaml
  releasenotes/notes/prepare-0.25.3-155bf49f7a7ca309.yaml
  releasenotes/notes/primitives-dynamic-circuit-b489f82df47af138.yaml
  setup.py
Labels: Changelog: None

#11113 Fix Barrier broadcast arguments
  qiskit/circuit/barrier.py
  releasenotes/notes/fix-barrier-arg-list-check-ff69f37ede6bdf6c.yaml
  test/python/circuit/test_circuit_operations.py
Labels: stable backport potential, Changelog: Bugfix

#10590 Plot State City Visualization Fixes
  qiskit/visualization/state_visualization.py
  releasenotes/notes/fix-plot-state-city-viz-2963c83bcf3d3347.yaml
  test/visual/mpl/graph/references/state_city.png
Labels: priority: medium, stable backport potential, Changelog: Bugfix, Community PR

#11120 Constrain `qiskit-aer==0.12.2`
  constraints.txt
Labels: type: qa, stable backport potential, Changelog: None

#11121 Remove stray QPY file
  circuit.qpy
Labels: stable backport potential, Changelog: None

#11118 Use absolute file paths in translations deployment
  .github/workflows/docs_deploy.yml
  tools/deploy_translatable_strings.sh
Labels: type: qa, stable backport potential, Changelog: None

#11112 Always run vf2 scoring serially
  qiskit/transpiler/passes/layout/vf2_layout.py
  qiskit/transpiler/passes/layout/vf2_post_layout.py
  qiskit/transpiler/passes/layout/vf2_utils.py
  releasenotes/notes/vf2-threading-b778a36de5b8832a.yaml
Labels: stable backport potential, performance, Changelog: None

#11117 Upgrade PyO3 to 0.20.0.
  Cargo.lock
  Cargo.toml
  crates/accelerate/Cargo.toml
Labels: Changelog: None, Rust, dependencies

#11074 Emit a descriptive error when the QPY version is too new
  qiskit/qpy/interface.py
  releasenotes/notes/fix-error-message-qpy-version-cf0763da22ce2224.yaml
  test/python/qpy/test_circuit_load_from_qpy.py
Labels: stable backport potential, Changelog: Bugfix, mod: qpy

#11100 some typos in 0.45 release notes
  releasenotes/notes/0.45/h_basic_aer-3fc5e6776f0de9c1.yaml
  releasenotes/notes/0.45/remove-deprecated-code-in-0.22-128475199e6f3cc2.yaml
  releasenotes/notes/0.45/remove-deprecated-code-in-0.22.0-139fa09ee0cc6df9.yaml
  releasenotes/notes/0.45/remove-deprecated-in-quantum-info-0f9bd2b0c093307d.yaml
  releasenotes/notes/0.45/single-pulse-rx-cal-347aadcee7bfe60b.yaml
  releasenotes/notes/0.45/singletons-83782de8bd062cbc.yaml
  releasenotes/notes/0.45/sparse-pauli-op-apply-layout-43149125d29ad015.yaml
  releasenotes/notes/0.45/transpile-layout-improvements-118dd902d93e5b96.yaml
Labels: documentation, stable backport potential, Changelog: None

#11115 Reuse VF2 scoring views for all scoring
  crates/accelerate/src/vf2_layout.rs
  qiskit/transpiler/passes/layout/vf2_layout.py
  qiskit/transpiler/passes/layout/vf2_post_layout.py
  qiskit/transpiler/passes/layout/vf2_utils.py
Labels: stable backport potential, performance, Changelog: None, Rust

#11123 only publish images if image tests run
  .azure/test-linux.yml
Labels: type: qa, stable backport potential, Changelog: None

#11077 Fixed typo in dagcircuit.py
  qiskit/dagcircuit/dagcircuit.py
Labels: Community PR

#11138 Fix typo in docs announcement banners
  docs/conf.py
  docs/index.rst
Labels: documentation, stable backport potential, Changelog: None

#11099 Fix lack of alternative for `Optimizer` in `AQC`
  qiskit/transpiler/synthesis/aqc/aqc.py
  qiskit/transpiler/synthesis/aqc/aqc_plugin.py
  releasenotes/notes/fix-aqc-optimizer-typehint-34b54c6278d23f79.yaml
  test/python/transpiler/aqc/test_aqc.py
  test/python/transpiler/aqc/test_aqc_plugin.py
Labels: stable backport potential, Changelog: Bugfix

#11101 Don't test forward compatibility in qpy compat tests
  test/qpy_compat/compare_versions.py
  test/qpy_compat/process_version.sh
Labels: type: qa, stable backport potential, Changelog: None

#11129 fix typo in files of `qiskit/circuit/` folder
  qiskit/circuit/instruction.py
  qiskit/circuit/library/standard_gates/x.py
  qiskit/circuit/quantumcircuit.py
  qiskit/circuit/singleton.py
Labels: stable backport potential, Changelog: None, Community PR

#11110 Deprecate the discrete pulse library
  docs/tutorials/circuits_advanced/06_building_pulse_schedules.ipynb
  qiskit/pulse/library/discrete.py
  releasenotes/notes/deprecate-discrete-pulse-library-d2482407d7965972.yaml
  test/python/compiler/test_assembler.py
  test/python/pulse/test_discrete_pulses.py
  test/python/pulse/test_instruction_schedule_map.py
  test/python/pulse/test_pulse_lib.py
  test/python/pulse/test_schedule.py
  test/python/visualization/pulse_v2/test_generators.py
Labels: Changelog: Deprecation, mod: pulse

#10505 Collect classical registers using a set (#10496)
  qiskit/dagcircuit/collect_blocks.py
  releasenotes/notes/fix-block-collapser-cregs-6c2d2dc6931d7bad.yaml
  test/python/dagcircuit/test_collect_blocks.py
Labels: stable backport potential, Changelog: Bugfix, Community PR

#11139 Use `circuit_drawer` for circuit drawer tests
  qiskit/visualization/circuit/circuit_visualization.py
  qiskit/visualization/circuit/matplotlib.py
  qiskit/visualization/circuit/text.py
  test/python/visualization/test_circuit_text_drawer.py
  test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py
Labels: type: qa, stable backport potential, Changelog: None, mod: visualization

#11155 Update deploy translatable strings script to push commit hash
  tools/deploy_translatable_strings.sh
Labels: type: qa, stable backport potential, Changelog: None
