Repository Qiskit/qiskit, pull requests merged in 2023-04, with the labels that each got.

#9891 Fix `offset` and `slope` definitions for Linear Pauli Rotations (#9861)
  qiskit/circuit/library/arithmetic/linear_pauli_rotations.py
Labels: documentation, Changelog: None, Community PR

#9775 Add `docs-clean` command to Tox
  tox.ini
Labels: Changelog: None

#9688 Fixes issue #9741 from exponential to linear number of cx gates in mcry
  qiskit/circuit/library/standard_gates/multi_control_rotation_gates.py
  releasenotes/notes/su2-synthesis-295ebf03d9033263.yaml
  test/python/circuit/test_controlled_gate.py
Labels: Community PR

#9818 PassManager.run: preserve input signature for length 1 list
  qiskit/transpiler/passmanager.py
  releasenotes/notes/fix-9798-30c0eb0e5181b691.yaml
  test/python/compiler/test_transpiler.py
  test/python/transpiler/test_passmanager_run.py
Labels: Community PR

#9855 Fix a bug in QuantumCircuit.draw related to vertical_compression
  qiskit/visualization/circuit/text.py
  releasenotes/notes/fix-circuit-drawing-low-compression-965c21de51b26ad2.yaml
  test/python/visualization/test_circuit_text_drawer.py
Labels: type: qa, Changelog: Bugfix, Community PR, mod: visualization

#9899 Fix `UnrollCustomDefinitions` handling of empty definitions
  qiskit/transpiler/passes/basis/unroll_custom_definitions.py
  releasenotes/notes/fix-unroll-custom-definitions-empty-definition-4fd175c035445540.yaml
  test/python/transpiler/test_unroll_custom_definitions.py
Labels: Changelog: Bugfix, mod: transpiler

#9886 Fixed handling of a list of coupling_maps passed to transpile()
  qiskit/compiler/transpiler.py
  releasenotes/notes/transpile-coupling-maps-3a137f4ca8e97745.yaml
  test/python/compiler/test_transpiler.py
Labels: Changelog: Bugfix

#9881 Fix `QuantumCircuitData` handling of `Operation`
  qiskit/circuit/quantumcircuitdata.py
  releasenotes/notes/fix-setting-circuit-data-operation-1b8326b1b089f10c.yaml
  test/python/circuit/test_circuit_data.py
Labels: Changelog: Bugfix

#9833 Add representation of "switch"
  qiskit/circuit/__init__.py
  qiskit/circuit/controlflow/__init__.py
  qiskit/circuit/controlflow/switch_case.py
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/switch-case-9b6611d0603d36c0.yaml
  test/python/circuit/test_control_flow.py
Labels: Changelog: New Feature

#9887 Fixed IQAE bug mentioned in issue 9280
  qiskit/algorithms/phase_estimators/ipe.py
  releasenotes/notes/iterative-phase-estimation-bugfix-b676ffc23cea8251.yaml
  test/python/algorithms/test_phase_estimator.py
Labels: Changelog: Bugfix, mod: algorithms, Community PR

#9271 Fixed typos in several documents
  qiskit/circuit/library/standard_gates/p.py
  qiskit/extensions/quantum_initializer/ucrx.py
  qiskit/extensions/quantum_initializer/ucry.py
  qiskit/extensions/quantum_initializer/ucrz.py
Labels: Community PR

#9557 Add Migration Guide for `qiskit.algorithms`
  docs/conf.py
  docs/index.rst
  docs/migration_guides/algorithms_migration.rst
  docs/migration_guides/index.rst
Labels: documentation, mod: algorithms, Changelog: None

#9909 Improve SabreSwap error message on unexpanded circuits
  qiskit/transpiler/passes/routing/sabre_swap.py
  test/python/transpiler/test_sabre_swap.py
Labels: Changelog: None, mod: transpiler

#9399 Adding HLS plugins for linear functions and cliffords
  qiskit/transpiler/passes/synthesis/high_level_synthesis.py
  releasenotes/notes/add-hls-plugins-038388970ad43c55.yaml
  setup.py
Labels: Changelog: New Feature

#9913 Add equivlences of ECR, SX and SXdg gates to the equivalence library
  qiskit/circuit/library/standard_gates/equivalence_library.py
  releasenotes/notes/add-ecr-sx-equivalences-5b6fe73ec599d1a4.yaml
  test/python/transpiler/test_basis_translator.py
Labels: Changelog: New Feature

#9911 Add flag to filter faulty qubits and gates to BackendV2Converter
  qiskit/providers/backend_compat.py
  releasenotes/notes/filter-faulty-qubits-and-gates-v2-converter-b56dac9c0ce8057f.yaml
  test/python/providers/test_fake_backends.py
Labels: Changelog: New Feature

#9906 Fix `AmplitudeEstimation` is silently ignoring `is_good_state` in the estimation problem
  qiskit/algorithms/amplitude_estimators/ae.py
  qiskit/algorithms/amplitude_estimators/estimation_problem.py
  releasenotes/notes/ae-warns-on-goodstate-7dbb689ba6a5e5e4.yaml
  test/python/algorithms/test_amplitude_estimators.py
Labels: Changelog: New Feature, Changelog: Bugfix, mod: algorithms

#9923 Update bot yaml
  qiskit_bot.yaml
Labels: Changelog: None

#9917 Don't cancel GHA runs on subsequent push events
  .github/workflows/coverage.yml
  .github/workflows/neko.yml
Labels: type: qa, Changelog: None

#9263 Make all Layout and Routing passes target aware
  qiskit/transpiler/passes/layout/csp_layout.py
  qiskit/transpiler/passes/layout/full_ancilla_allocation.py
  qiskit/transpiler/passes/layout/layout_2q_distance.py
  qiskit/transpiler/passes/layout/noise_adaptive_layout.py
  qiskit/transpiler/passes/layout/sabre_layout.py
  qiskit/transpiler/passes/layout/trivial_layout.py
  qiskit/transpiler/passes/routing/basic_swap.py
  qiskit/transpiler/passes/routing/bip_mapping.py
  qiskit/transpiler/passes/routing/layout_transformation.py
  qiskit/transpiler/passes/routing/lookahead_swap.py
  qiskit/transpiler/passes/routing/sabre_swap.py
  qiskit/transpiler/passes/routing/stochastic_swap.py
  qiskit/transpiler/passes/utils/check_map.py
  qiskit/transpiler/preset_passmanagers/builtin_plugins.py
  qiskit/transpiler/preset_passmanagers/common.py
  qiskit/transpiler/preset_passmanagers/level0.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  releasenotes/notes/target-aware-layout-routing-2b39bd87a9f928e7.yaml
  test/python/transpiler/test_basic_swap.py
  test/python/transpiler/test_bip_mapping.py
  test/python/transpiler/test_check_map.py
  test/python/transpiler/test_csp_layout.py
  test/python/transpiler/test_full_ancilla_allocation.py
  test/python/transpiler/test_layout_score.py
  test/python/transpiler/test_layout_transformation.py
  test/python/transpiler/test_lookahead_swap.py
  test/python/transpiler/test_sabre_layout.py
  test/python/transpiler/test_sabre_swap.py
  test/python/transpiler/test_stochastic_swap.py
  test/python/transpiler/test_trivial_layout.py
  test/python/visualization/references/pass_manager_standard.dot
  test/python/visualization/references/pass_manager_style.dot
Labels: Changelog: New Feature, mod: transpiler

#9938 Pin pygments in CI
  requirements-dev.txt
Labels: type: qa, stable backport potential, Changelog: None

#9929 Fix CheckMap pass target handling
  qiskit/transpiler/passes/utils/check_map.py
  qiskit/transpiler/preset_passmanagers/common.py
  qiskit/transpiler/preset_passmanagers/level1.py
  test/python/transpiler/test_check_map.py
  test/python/visualization/references/pass_manager_standard.dot
  test/python/visualization/references/pass_manager_style.dot
Labels: Changelog: None

#9949 Pin Sphinx theme to minor release
  requirements-dev.txt
Labels: documentation, Changelog: None

#9941 Ensure we run VF2PostLayout when needed in optimization level 1
  qiskit/transpiler/passes/utils/check_map.py
  qiskit/transpiler/preset_passmanagers/common.py
  releasenotes/notes/vf2postlayout-fix-16bb54d9bdf3aaf6.yaml
  test/python/transpiler/test_preset_passmanagers.py
  test/python/visualization/references/pass_manager_standard.dot
  test/python/visualization/references/pass_manager_style.dot
Labels: priority: high, Changelog: New Feature, Changelog: Bugfix

#9890 Add support for pulse reference to QPY
  qiskit/qpy/__init__.py
  qiskit/qpy/binary_io/schedules.py
  qiskit/qpy/common.py
  qiskit/qpy/type_keys.py
  releasenotes/notes/add-support-for-qpy-reference-70478baa529fff8c.yaml
  test/python/qpy/test_block_load_from_qpy.py
  test/qpy_compat/test_qpy.py
Labels: Changelog: New Feature, mod: pulse, mod: qpy

#9948 Fix docs build with Pygments 2.15
  qiskit/qasm/__init__.py
  requirements-dev.txt
Labels: type: qa, stable backport potential, Changelog: None

#9465 fixed issue 9453 by removing "_v2" from name in BackendV2 class
  qiskit/providers/fake_provider/backends/almaden/fake_almaden.py
  qiskit/providers/fake_provider/backends/armonk/fake_armonk.py
  qiskit/providers/fake_provider/backends/athens/fake_athens.py
  qiskit/providers/fake_provider/backends/belem/fake_belem.py
  qiskit/providers/fake_provider/backends/boeblingen/fake_boeblingen.py
  qiskit/providers/fake_provider/backends/bogota/fake_bogota.py
  qiskit/providers/fake_provider/backends/brooklyn/fake_brooklyn.py
  qiskit/providers/fake_provider/backends/burlington/fake_burlington.py
  qiskit/providers/fake_provider/backends/cairo/fake_cairo.py
  qiskit/providers/fake_provider/backends/cambridge/fake_cambridge.py
  qiskit/providers/fake_provider/backends/casablanca/fake_casablanca.py
  qiskit/providers/fake_provider/backends/essex/fake_essex.py
  qiskit/providers/fake_provider/backends/guadalupe/fake_guadalupe.py
  qiskit/providers/fake_provider/backends/hanoi/fake_hanoi.py
  qiskit/providers/fake_provider/backends/jakarta/fake_jakarta.py
  qiskit/providers/fake_provider/backends/johannesburg/fake_johannesburg.py
  qiskit/providers/fake_provider/backends/kolkata/fake_kolkata.py
  qiskit/providers/fake_provider/backends/lagos/fake_lagos.py
  qiskit/providers/fake_provider/backends/london/fake_london.py
  qiskit/providers/fake_provider/backends/manhattan/fake_manhattan.py
  qiskit/providers/fake_provider/backends/manila/fake_manila.py
  qiskit/providers/fake_provider/backends/melbourne/fake_melbourne.py
  qiskit/providers/fake_provider/backends/montreal/fake_montreal.py
  qiskit/providers/fake_provider/backends/mumbai/fake_mumbai.py
  qiskit/providers/fake_provider/backends/nairobi/fake_nairobi.py
  qiskit/providers/fake_provider/backends/ourense/fake_ourense.py
  qiskit/providers/fake_provider/backends/paris/fake_paris.py
  qiskit/providers/fake_provider/backends/poughkeepsie/fake_poughkeepsie.py
  qiskit/providers/fake_provider/backends/quito/fake_quito.py
  qiskit/providers/fake_provider/backends/rochester/fake_rochester.py
  qiskit/providers/fake_provider/backends/rome/fake_rome.py
  qiskit/providers/fake_provider/backends/santiago/fake_santiago.py
  qiskit/providers/fake_provider/backends/singapore/fake_singapore.py
  qiskit/providers/fake_provider/backends/sydney/fake_sydney.py
  qiskit/providers/fake_provider/backends/toronto/fake_toronto.py
  qiskit/providers/fake_provider/backends/valencia/fake_valencia.py
  qiskit/providers/fake_provider/backends/vigo/fake_vigo.py
  qiskit/providers/fake_provider/backends/washington/fake_washington.py
  qiskit/providers/fake_provider/backends/yorktown/fake_yorktown.py
  releasenotes/notes/rename-fake-backends-b08f8a66bc19088b.yaml
Labels: Changelog: API Change, Community PR

#9480 Remove deprecated methods and args in Primitives
  qiskit/algorithms/minimum_eigensolvers/diagonal_estimator.py
  qiskit/primitives/backend_estimator.py
  qiskit/primitives/backend_sampler.py
  qiskit/primitives/base/base_estimator.py
  qiskit/primitives/base/base_primitive.py
  qiskit/primitives/base/base_sampler.py
  qiskit/primitives/estimator.py
  qiskit/primitives/sampler.py
  releasenotes/notes/delete-args-and-methods-in-primitives-d89d444ec0217ae6.yaml
  test/python/algorithms/gradients/logging_primitives.py
  test/python/primitives/test_estimator.py
  test/python/primitives/test_sampler.py
Labels: priority: high, Changelog: Removal, mod: primitives

#9784 Add Rust-based OpenQASM 2 converter
  Cargo.lock
  crates/qasm2/Cargo.toml
  crates/qasm2/README.md
  crates/qasm2/src/bytecode.rs
  crates/qasm2/src/error.rs
  crates/qasm2/src/expr.rs
  crates/qasm2/src/lex.rs
  crates/qasm2/src/lib.rs
  crates/qasm2/src/parse.rs
  docs/apidocs/qasm2.rst
  docs/apidocs/terra.rst
  pyproject.toml
  qiskit/__init__.py
  qiskit/qasm2/__init__.py
  qiskit/qasm2/exceptions.py
  qiskit/qasm2/parse.py
  releasenotes/notes/qasm2-parser-rust-ecf6570e2d445a94.yaml
  setup.py
  test/python/qasm2/__init__.py
  test/python/qasm2/test_arxiv_examples.py
  test/python/qasm2/test_expression.py
  test/python/qasm2/test_lexer.py
  test/python/qasm2/test_parse_errors.py
  test/python/qasm2/test_structure.py
Labels: Changelog: New Feature, qasm, Rust

#9900 Remove faulty qubits and gates sections from transpile()
  qiskit/compiler/transpiler.py
  releasenotes/notes/remove-faulty-qubits-support-00850f69185c365e.yaml
  test/python/transpiler/test_faulty_backend.py
Labels: priority: high, Changelog: Removal

#9547 Deprecate PauliTable and StabilizerTable
  qiskit/quantum_info/operators/symplectic/clifford.py
  qiskit/quantum_info/operators/symplectic/pauli_table.py
  qiskit/quantum_info/operators/symplectic/stabilizer_table.py
  releasenotes/notes/deprecate-pauli-table-fc6dcdb5eeb6e0c4.yaml
  test/python/quantum_info/operators/symplectic/test_clifford.py
  test/python/quantum_info/operators/symplectic/test_pauli_list.py
  test/python/quantum_info/operators/symplectic/test_pauli_table.py
  test/python/quantum_info/operators/symplectic/test_stabilizer_table.py
  test/python/quantum_info/operators/test_random.py
Labels: Changelog: Deprecation, mod: quantum info

#9920 Generic PrimitiveJob and BaseSampler/BaseEstimator
  qiskit/primitives/backend_estimator.py
  qiskit/primitives/backend_sampler.py
  qiskit/primitives/base/base_estimator.py
  qiskit/primitives/base/base_sampler.py
  qiskit/primitives/estimator.py
  qiskit/primitives/primitive_job.py
  qiskit/primitives/sampler.py
Labels: documentation, Changelog: None, mod: primitives

#9541 Bug fix in template optimization, and minor cleanup
  qiskit/dagcircuit/dagdependency.py
  qiskit/transpiler/passes/optimization/template_matching/template_substitution.py
  releasenotes/notes/fix-template-opt-bd3c40382e9a993b.yaml
  test/python/transpiler/test_template_matching.py
Labels: Changelog: Bugfix

#9958 Wrap `io::Error` in `QASM2ParseError` on failed file read
  crates/qasm2/src/lib.rs
  test/python/qasm2/test_parse_errors.py
Labels: qasm, Changelog: None, Rust

#9255 Add constructor to build target from legacy transpiler model
  qiskit/transpiler/target.py
  releasenotes/notes/new-constructor-target-from-configuration-91f7eb569d95b330.yaml
  test/python/transpiler/test_target.py
Labels: priority: medium, Changelog: New Feature, mod: transpiler

#9554 Add Migration Guide for `QuantumInstance`
  docs/migration_guides/index.rst
  docs/migration_guides/qi_migration.rst
Labels: documentation, priority: high, mod: opflow

#9802 Add support for disjoint coupling maps to SabreLayout
  qiskit/transpiler/passes/layout/disjoint_utils.py
  qiskit/transpiler/passes/layout/sabre_layout.py
  qiskit/transpiler/passes/routing/sabre_swap.py
  releasenotes/notes/support-disjoint-cmap-sabre-551ae4295131a449.yaml
  test/python/compiler/test_transpiler.py
  test/python/transpiler/test_sabre_layout.py
Labels: priority: high, Changelog: New Feature

#9670 new unroll for-loops transpilation pass
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/utils/__init__.py
  qiskit/transpiler/passes/utils/unroll_forloops.py
  releasenotes/notes/unroll-forloops-7bf8000620f738e7.yaml
  test/python/transpiler/test_unroll_forloops.py
Labels: Changelog: New Feature

#9963 Add `max_trials` parameter to `VF2PostLayout`.
  qiskit/transpiler/passes/layout/vf2_post_layout.py
  releasenotes/notes/vf2-post-layout-max-trials-98b1c736e2e33861.yaml
  test/python/transpiler/test_vf2_post_layout.py
Labels: priority: high, Changelog: New Feature

#9959 Remove circular dependency on `qiskit.qasm.pi`
  qiskit/circuit/library/standard_gates/equivalence_library.py
  qiskit/circuit/library/standard_gates/h.py
  qiskit/circuit/library/standard_gates/r.py
  qiskit/circuit/library/standard_gates/rx.py
  qiskit/circuit/library/standard_gates/ry.py
  qiskit/circuit/library/standard_gates/s.py
  qiskit/circuit/library/standard_gates/sx.py
  qiskit/circuit/library/standard_gates/t.py
  qiskit/circuit/library/standard_gates/u2.py
  qiskit/circuit/library/standard_gates/x.py
  qiskit/circuit/library/standard_gates/xx_minus_yy.py
  qiskit/circuit/library/standard_gates/xx_plus_yy.py
  qiskit/circuit/library/standard_gates/y.py
  qiskit/circuit/library/standard_gates/z.py
  test/python/circuit/test_extensions_standard.py
  test/python/qasm3/test_export.py
Labels: type: qa, qasm, Changelog: None

#9921 `AdaptVQE` threshold improvements
  qiskit/algorithms/minimum_eigensolvers/adapt_vqe.py
  releasenotes/notes/adapt-vqe-thresholds-239ed9f250c63e71.yaml
  test/python/algorithms/minimum_eigensolvers/test_adapt_vqe.py
Labels: priority: medium, Changelog: New Feature, mod: algorithms

#9151 Allow list of optimizers+initial points in ``VQD``
  qiskit/algorithms/eigensolvers/vqd.py
  releasenotes/notes/vqd-list-initial-points-list-optimizers-033d7439f86bbb71.yaml
  test/python/algorithms/eigensolvers/test_vqd.py
Labels: Changelog: New Feature, mod: algorithms, Community PR

#9704 providers/options: implement Mapping
  qiskit/providers/options.py
  releasenotes/notes/options-implement-mutable-mapping-b11f4e2c6df4cf31.yaml
  test/python/providers/test_options.py
Labels: Changelog: New Feature, Community PR

#9883 Change algorithms from pending deprecation to deprecated
  qiskit/algorithms/amplitude_amplifiers/grover.py
  qiskit/algorithms/amplitude_estimators/ae.py
  qiskit/algorithms/amplitude_estimators/fae.py
  qiskit/algorithms/amplitude_estimators/iae.py
  qiskit/algorithms/amplitude_estimators/mlae.py
  qiskit/algorithms/aux_ops_evaluator.py
  qiskit/algorithms/eigen_solvers/eigen_solver.py
  qiskit/algorithms/eigen_solvers/numpy_eigen_solver.py
  qiskit/algorithms/eigen_solvers/vqd.py
  qiskit/algorithms/evolvers/evolution_problem.py
  qiskit/algorithms/evolvers/evolution_result.py
  qiskit/algorithms/evolvers/imaginary_evolver.py
  qiskit/algorithms/evolvers/real_evolver.py
  qiskit/algorithms/evolvers/trotterization/trotter_qrte.py
  qiskit/algorithms/minimum_eigen_solvers/minimum_eigen_solver.py
  qiskit/algorithms/minimum_eigen_solvers/numpy_minimum_eigen_solver.py
  qiskit/algorithms/minimum_eigen_solvers/qaoa.py
  qiskit/algorithms/minimum_eigen_solvers/vqe.py
  qiskit/algorithms/optimizers/qnspsa.py
  qiskit/algorithms/phase_estimators/hamiltonian_phase_estimation.py
  qiskit/algorithms/phase_estimators/ipe.py
  qiskit/algorithms/phase_estimators/phase_estimation.py
  releasenotes/notes/deprecate-algorithms-c6e1e28b6091c507.yaml
  test/python/algorithms/evolvers/test_evolution_problem.py
  test/python/algorithms/evolvers/test_evolution_result.py
  test/python/algorithms/evolvers/trotterization/test_trotter_qrte.py
  test/python/algorithms/optimizers/test_optimizer_aqgd.py
  test/python/algorithms/optimizers/test_optimizer_nft.py
  test/python/algorithms/optimizers/test_optimizers_scikitquant.py
  test/python/algorithms/optimizers/test_spsa.py
  test/python/algorithms/test_amplitude_estimators.py
  test/python/algorithms/test_aux_ops_evaluator.py
  test/python/algorithms/test_backendv1.py
  test/python/algorithms/test_backendv2.py
  test/python/algorithms/test_grover.py
  test/python/algorithms/test_measure_error_mitigation.py
  test/python/algorithms/test_numpy_eigen_solver.py
  test/python/algorithms/test_numpy_minimum_eigen_solver.py
  test/python/algorithms/test_phase_estimator.py
  test/python/algorithms/test_qaoa.py
  test/python/algorithms/test_vqd.py
  test/python/algorithms/test_vqe.py
  test/python/algorithms/time_evolvers/test_pvqd.py
Labels: priority: high, mod: algorithms

#9840 Add full path transpile() support for disjoint backends
  qiskit/transpiler/passes/layout/dense_layout.py
  qiskit/transpiler/passes/layout/disjoint_utils.py
  qiskit/transpiler/passes/layout/trivial_layout.py
  qiskit/transpiler/passes/routing/basic_swap.py
  qiskit/transpiler/passes/routing/bip_mapping.py
  qiskit/transpiler/passes/routing/lookahead_swap.py
  qiskit/transpiler/passes/routing/sabre_swap.py
  qiskit/transpiler/passes/routing/stochastic_swap.py
  test/python/compiler/test_transpiler.py
  test/python/transpiler/test_dense_layout.py
Labels: priority: high, Changelog: New Feature, mod: transpiler

#9972 Invoke `pip install` by module not executable
  .azure/docs-linux.yml
  .azure/lint-linux.yml
  .azure/test-linux.yml
  .azure/test-macos.yml
  .azure/test-windows.yml
  .azure/tutorials-linux.yml
  .azure/wheels.yml
  .github/workflows/coverage.yml
  .github/workflows/randomized_tests.yml
  .github/workflows/slow.yml
Labels: type: qa, stable backport potential, Changelog: None

#9322 Remove argument max_credits from execute and assemble
  qiskit/assembler/run_config.py
  qiskit/compiler/assembler.py
  qiskit/execute_function.py
  qiskit/qobj/pulse_qobj.py
  qiskit/qobj/qasm_qobj.py
  qiskit/utils/quantum_instance.py
  releasenotes/notes/remove-execute_function-max_credits-8c822b8b4b3d84ba.yaml
  test/python/qobj/test_qobj_deprecated.py
Labels: Changelog: Removal

#9919 Add builder interface for new switch statement
  qiskit/circuit/controlflow/_builder_utils.py
  qiskit/circuit/controlflow/builder.py
  qiskit/circuit/controlflow/if_else.py
  qiskit/circuit/controlflow/switch_case.py
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_control_flow_builders.py
Labels: priority: high

#9916 Add experimental OpenQASM 3 support for switch
  qiskit/qasm3/__init__.py
  qiskit/qasm3/ast.py
  qiskit/qasm3/experimental.py
  qiskit/qasm3/exporter.py
  qiskit/qasm3/printer.py
  test/python/qasm3/test_export.py
Labels: Changelog: New Feature, qasm

#9251 Adding global_phase gate in qiskit-terra
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/standard_gates/__init__.py
  qiskit/circuit/library/standard_gates/global_phase.py
  qiskit/quantum_info/operators/operator.py
  releasenotes/notes/add-global-phase-gate-b52c5b25ab8a3cf6.yaml
  test/python/circuit/test_controlled_gate.py
  test/python/circuit/test_extensions_standard.py
Labels: Community PR

#9976 Fix handling of numpy integers in marginal_distribution()
  qiskit/result/utils.py
  releasenotes/notes/fix-marginal-distribution-np-ints-ee78859bfda79b60.yaml
  test/python/result/test_counts.py
  test/python/result/test_quasi.py
Labels: Changelog: Bugfix

#9795 Prepare qiskit/transpiler/graysynth.py for deprecation in next release
  qiskit/synthesis/__init__.py
  qiskit/synthesis/linear/__init__.py
  qiskit/synthesis/linear/cnot_synth.py
  qiskit/synthesis/linear_phase/__init__.py
  qiskit/synthesis/linear_phase/cnot_phase_synth.py
  qiskit/transpiler/synthesis/__init__.py
  qiskit/transpiler/synthesis/graysynth.py
  releasenotes/notes/rename-graysynth-3fa4fcb7d096ab35.yaml
  test/python/circuit/library/test_linear_function.py
  test/python/synthesis/test_cnot_phase_synthesis.py
Labels: Changelog: Bugfix, synthesis

#9953 Refactor OpenQASM 2 exporter
  qiskit/circuit/library/generalized_gates/permutation.py
  qiskit/circuit/quantumcircuit.py
  qiskit/extensions/unitary.py
  releasenotes/notes/qasm2-exporter-rewrite-8993dd24f930b180.yaml
  test/python/circuit/test_circuit_qasm.py
  test/python/circuit/test_unitary.py
Labels: priority: medium, Changelog: Bugfix, qasm

#9160 add function to swap connected nodes in DAGCircuit
  qiskit/dagcircuit/dagcircuit.py
  releasenotes/notes/add-swap_nodes-to-dagcircuit-methods-2964426f02251fc4.yaml
  test/python/dagcircuit/test_dagcircuit.py
Labels: Changelog: New Feature, mod: transpiler

#9049 Improve error messages on failed control-flow transpilation
  qiskit/transpiler/passes/utils/error.py
  qiskit/transpiler/preset_passmanagers/common.py
  qiskit/transpiler/preset_passmanagers/level0.py
  qiskit/transpiler/preset_passmanagers/level1.py
  releasenotes/notes/error-pass-callable-message-3f29f09b9faba736.yaml
  test/python/transpiler/test_error.py
  test/python/transpiler/test_preset_passmanagers.py
Labels: Changelog: New Feature, mod: transpiler

#9979 Update docstring of CouplingMap.connected_components to reflect name …
  qiskit/transpiler/coupling.py
Labels: documentation, Changelog: None

#9275 plugin convenience function for getting the entry point object
  qiskit/transpiler/preset_passmanagers/plugin.py
  releasenotes/notes/entry_point_obj-60625d9d797df1d9.yaml
  test/python/transpiler/test_stage_plugin.py
Labels: Changelog: New Feature

#9849 Change QuantumCircuit.metadata to always be a dict
  qiskit/circuit/quantumcircuit.py
  qiskit/dagcircuit/dagcircuit.py
  qiskit/dagcircuit/dagdependency.py
  qiskit/test/base.py
  releasenotes/notes/circuit_metadata_always_dict-49015896dfa49d33.yaml
  test/python/circuit/test_circuit_properties.py
  test/python/dagcircuit/test_dagcircuit.py
  test/python/dagcircuit/test_dagdependency.py
Labels: mypy

#9926 Add QPY support for `switch` statement
  qiskit/qpy/__init__.py
  qiskit/qpy/binary_io/circuits.py
  qiskit/qpy/binary_io/value.py
  qiskit/qpy/type_keys.py
  test/python/circuit/test_circuit_load_from_qpy.py
  test/qpy_compat/test_qpy.py
Labels: mod: qpy

#9474 Update docstrings on BackendV2Converter and convert_to_target
  qiskit/providers/backend_compat.py
Labels: stable backport potential

#9927 Filter/ignore qubits in Target without any operations
  qiskit/transpiler/passes/layout/dense_layout.py
  qiskit/transpiler/passes/layout/disjoint_utils.py
  qiskit/transpiler/passes/layout/sabre_layout.py
  qiskit/transpiler/passes/layout/vf2_layout.py
  qiskit/transpiler/passes/layout/vf2_post_layout.py
  qiskit/transpiler/passes/layout/vf2_utils.py
  qiskit/transpiler/passes/routing/basic_swap.py
  qiskit/transpiler/passes/routing/bip_mapping.py
  qiskit/transpiler/passes/routing/lookahead_swap.py
  qiskit/transpiler/passes/routing/sabre_swap.py
  qiskit/transpiler/passes/routing/stochastic_swap.py
  qiskit/transpiler/target.py
  releasenotes/notes/filter-idle-qubits-cmap-74ac7711fc7476f3.yaml
  test/python/compiler/test_transpiler.py
Labels: priority: high, Changelog: None

#9928 Add support to `switch` in `transpile`
  qiskit/dagcircuit/dagcircuit.py
  qiskit/transpiler/passes/routing/stochastic_swap.py
  qiskit/transpiler/preset_passmanagers/common.py
  releasenotes/notes/switch-case-9b6611d0603d36c0.yaml
  test/python/compiler/test_transpiler.py
  test/python/providers/test_fake_backends.py
  test/python/transpiler/test_gates_in_basis_pass.py
  test/python/transpiler/test_stochastic_swap.py
  test/python/transpiler/test_target.py
Labels: priority: high, Changelog: New Feature, mod: transpiler

#9990 Add note on support window for experimental OQ3
  qiskit/qasm3/__init__.py
Labels: documentation, qasm, Changelog: None

#9942 Fix circuit drawer for instructions with circuit parameters
  qiskit/visualization/circuit/_utils.py
  releasenotes/notes/fix-circuit-drawer-for-qc-params-e78c67310ae43ccf.yaml
  test/python/visualization/test_circuit_text_drawer.py
Labels: Changelog: Bugfix, Community PR, mod: visualization

#9915 Remove remove_final_measurment hack in BackendEstimator
  qiskit/primitives/backend_estimator.py
  test/python/primitives/test_backend_estimator.py
Labels: priority: medium, Changelog: None, mod: primitives

#9987 Bug fix macros.measure with backendv2
  qiskit/pulse/macros.py
  releasenotes/notes/fix-macros-measure-with-backendV2-4354f00ab4f1cd3e.yaml
  test/python/pulse/test_macros.py
Labels: Changelog: Bugfix, mod: pulse

#9403 Operator apply permutation
  qiskit/quantum_info/operators/operator.py
  releasenotes/notes/operator-apply-permutation-c113c05513cb7881.yaml
  test/python/quantum_info/operators/test_operator.py
Labels: Changelog: New Feature, mod: quantum info

#10000 Don't run routing in SabreLayout with split components
  qiskit/transpiler/passes/layout/sabre_layout.py
  test/python/compiler/test_transpiler.py
  test/python/transpiler/test_sabre_layout.py
Labels: Changelog: None

#9999 Give ownership of output from `Target.build_coupling_map`
  qiskit/providers/backend.py
  qiskit/transpiler/passes/layout/sabre_layout.py
  qiskit/transpiler/passes/routing/sabre_swap.py
  qiskit/transpiler/target.py
  test/python/compiler/test_transpiler.py
  test/python/transpiler/test_target.py
Labels: Changelog: None, mod: transpiler

#10005 Bump main branch version post 0.24.0rc1 tag
  .mergify.yml
  Cargo.lock
  Cargo.toml
  crates/accelerate/Cargo.toml
  crates/qasm2/Cargo.toml
  docs/conf.py
  qiskit/VERSION.txt
  setup.py
Labels: Changelog: None

#10010 Upgrade straggler GitHub Actions to Node 16
  .github/workflows/coverage.yml
  .github/workflows/wheels.yml
Labels: type: qa, stable backport potential, Changelog: None

#10023 Update sx.py
  qiskit/circuit/library/standard_gates/sx.py
Labels: documentation, stable backport potential, Changelog: None, Community PR

#10019 Fix typo in documentation - parameters description
  qiskit/visualization/gate_map.py
Labels: documentation, stable backport potential, Changelog: None, Community PR

#10027 Disable cron runs on 0.22.x series
  azure-pipelines.yml
Labels: type: qa, Changelog: None

#10016 Use backend_compat module's convert to target
  qiskit/providers/backend_compat.py
  qiskit/providers/fake_provider/fake_backend.py
  test/python/providers/test_fake_backends.py
Labels: stable backport potential, Changelog: Bugfix

#9830 test_controlled_gate phase correct
  test/python/circuit/test_controlled_gate.py
Labels: type: qa, Changelog: None, Community PR

#10007 Fix delay padding to respect target's constraints
  qiskit/transpiler/passes/scheduling/alap.py
  qiskit/transpiler/passes/scheduling/asap.py
  qiskit/transpiler/passes/scheduling/base_scheduler.py
  qiskit/transpiler/passes/scheduling/dynamical_decoupling.py
  qiskit/transpiler/passes/scheduling/padding/base_padding.py
  qiskit/transpiler/passes/scheduling/padding/dynamical_decoupling.py
  qiskit/transpiler/passes/scheduling/padding/pad_delay.py
  qiskit/transpiler/preset_passmanagers/common.py
  releasenotes/notes/fix-delay-padding-75937bda37ebc3fd.yaml
  test/python/compiler/test_transpiler.py
  test/python/transpiler/legacy_scheduling/test_scheduling_pass.py
  test/python/transpiler/test_dynamical_decoupling.py
  test/python/transpiler/test_scheduling_padding_pass.py
Labels: stable backport potential, Changelog: Bugfix

#9170 Allow decomposing composite gates by name
  qiskit/circuit/library/standard_gates/xx_minus_yy.py
  qiskit/circuit/library/standard_gates/xx_plus_yy.py
  qiskit/circuit/quantumcircuit.py
  qiskit/transpiler/passes/basis/decompose.py
  releasenotes/notes/fix-decompose-name-f83f5e4e64918aa9.yaml
  test/python/transpiler/test_decompose.py
Labels: Changelog: Bugfix, Community PR

#10031 FIx 0q operation handling in `Statevector`
  qiskit/quantum_info/operators/op_shape.py
  releasenotes/notes/fix-0q-operator-statevector-79199c65c24637c4.yaml
  test/python/quantum_info/states/test_statevector.py
Labels: stable backport potential, Changelog: Bugfix

#10037 circuit: narrow the return type of QuantumCircuit.assign_parameters
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/improve-quantum-circuit-assign-parameters-typing-70c9623405cbd420.yaml
Labels: stable backport potential, Changelog: Bugfix, Community PR

#9845 Improve basis translator error message
  qiskit/providers/__init__.py
  qiskit/transpiler/passes/basis/basis_translator.py
Labels: stable backport potential, Changelog: None

#10044 Replace deprecated function call
  qiskit/pulse/library/waveform.py
  test/python/pulse/test_pulse_lib.py
Labels: stable backport potential, Changelog: None, Community PR

#9300 Fix for unintended rounding in 'state_to_latex' latex output
  qiskit/visualization/state_visualization.py
  releasenotes/notes/unintended-rounding-with-max-size-1498af5f9a467990.yaml
  test/python/quantum_info/states/test_statevector.py
Labels: stable backport potential, Changelog: Bugfix, Community PR, mod: visualization

#10020 Remove deprecations from mpl circuit drawer
  qiskit/visualization/circuit/circuit_visualization.py
  qiskit/visualization/circuit/matplotlib.py
  releasenotes/notes/remove-deprecated-mpl-drawer-9d6eaa40d5a86777.yaml
Labels: Changelog: Removal, Community PR, mod: visualization
