Repository Qiskit/qiskit, pull requests merged in 2023-03, with the labels that each got.

#9691 Remove dependency to pkg_resources
  qiskit/version.py
Labels: stable backport potential, Changelog: None

#9644 Switch from .pylintrc to pyproject.toml and drop default options
  .pylintrc
  pyproject.toml
  test/python/pulse/test_transforms.py
  test/python/transpiler/test_collect_2q_blocks.py
Labels: automerge, Changelog: None

#9666 Improve docstring for `Statevector.evolve`
  qiskit/quantum_info/states/statevector.py
Labels: documentation, stable backport potential, automerge, Changelog: None

#9201 Fix wrong argument supplied to _identity_op()
  qiskit/circuit/commutation_checker.py
  releasenotes/notes/fix-memory-commutation-checker-dbb441de68706b6f.yaml
  test/python/circuit/test_commutation_checker.py
Labels: stable backport potential, Changelog: Bugfix, automerge, Community PR

#9690 Ruff fix C4?? "unnecessary X"
  qiskit/algorithms/amplitude_amplifiers/grover.py
  qiskit/algorithms/gradients/utils.py
  qiskit/circuit/equivalence.py
  qiskit/circuit/quantumcircuit.py
  qiskit/compiler/assembler.py
  qiskit/dagcircuit/collect_blocks.py
  qiskit/dagcircuit/dagcircuit.py
  qiskit/dagcircuit/dagdependency.py
  qiskit/providers/basicaer/qasm_simulator.py
  qiskit/providers/models/backendproperties.py
  qiskit/pulse/builder.py
  qiskit/pulse/calibration_entries.py
  qiskit/pulse/instructions/call.py
  qiskit/pulse/library/symbolic_pulses.py
  qiskit/quantum_info/operators/dihedral/polynomial.py
  qiskit/tools/parallel.py
  qiskit/transpiler/passes/basis/basis_translator.py
  qiskit/transpiler/passes/calibration/rzx_builder.py
  qiskit/transpiler/passes/calibration/rzx_templates.py
  qiskit/transpiler/passes/optimization/optimize_cliffords.py
  qiskit/transpiler/passes/optimization/template_matching/template_substitution.py
  qiskit/transpiler/passes/routing/commuting_2q_gate_routing/swap_strategy.py
  qiskit/transpiler/passes/scheduling/padding/dynamical_decoupling.py
  qiskit/transpiler/passes/scheduling/scheduling/alap.py
  qiskit/transpiler/passes/scheduling/scheduling/asap.py
  qiskit/transpiler/passes/scheduling/scheduling/base_scheduler.py
  qiskit/transpiler/passes/synthesis/high_level_synthesis.py
  qiskit/transpiler/passes/synthesis/plugin.py
  qiskit/transpiler/passes/utils/remove_final_measurements.py
  qiskit/transpiler/preset_passmanagers/__init__.py
  qiskit/transpiler/target.py
  qiskit/utils/mitigation/fitters.py
  qiskit/visualization/counts_visualization.py
  qiskit/visualization/pulse_v2/events.py
  qiskit/visualization/state_visualization.py
  test/python/algorithms/test_phase_estimator.py
  test/python/circuit/test_circuit_load_from_qpy.py
  test/python/circuit/test_circuit_properties.py
  test/python/compiler/test_assembler.py
  test/python/compiler/test_transpiler.py
  test/python/converters/test_circuit_to_dagdependency.py
  test/python/converters/test_dag_to_dagdependency.py
  test/python/dagcircuit/test_dagcircuit.py
  test/python/pulse/test_reference.py
  test/python/qobj/test_qobj_identifiers.py
  test/python/result/test_result.py
  test/python/transpiler/aqc/fast_gradient/test_cmp_gradients.py
  test/python/transpiler/test_preset_passmanagers.py
  test/python/transpiler/test_solovay_kitaev.py
  test/python/transpiler/test_stochastic_swap.py
  test/python/transpiler/test_swap_strategy_router.py
Labels: type: qa, automerge, Changelog: None

#9674 Fix slow-test failures in `test_bound_pass_manager`
  test/python/primitives/test_backend_estimator.py
  test/python/primitives/test_backend_sampler.py
Labels: type: qa, automerge, Changelog: None

#9665 Fix qpy import of circuit with StatePreparation
  qiskit/qpy/binary_io/circuits.py
  releasenotes/notes/fix-qpy-import-StatePreparation-e20f8ab07bfe39a3.yaml
  test/python/circuit/test_circuit_load_from_qpy.py
Labels: stable backport potential, Changelog: Bugfix, automerge, mod: qpy, Community PR

#9708 Fix docstring format errors found by ruff
  qiskit/algorithms/time_evolvers/pvqd/pvqd.py
  qiskit/circuit/controlledgate.py
  qiskit/circuit/quantumcircuit.py
  qiskit/opflow/gradients/qfi_base.py
  qiskit/quantum_info/operators/symplectic/base_pauli.py
  qiskit/quantum_info/synthesis/qsd.py
  qiskit/tools/events/progressbar.py
  qiskit/tools/events/pubsub.py
  qiskit/tools/jupyter/progressbar.py
  qiskit/utils/backend_utils.py
  qiskit/utils/run_circuits.py
  qiskit/visualization/circuit/circuit_visualization.py
  test/python/circuit/test_commutation_checker.py
  test/python/dagcircuit/test_dagcircuit.py
  test/python/transpiler/test_commutative_cancellation.py
  test/python/transpiler/test_commutative_inverse_cancellation.py
Labels: type: qa, automerge, Changelog: None

#9578 Oxidize the internals of Optimize1qGatesDecomposition
  qiskit/transpiler/passes/optimization/optimize_1q_commutation.py
  qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py
  qiskit/transpiler/passes/synthesis/unitary_synthesis.py
  releasenotes/notes/speedup-one-qubit-optimize-pass-483429af948a415e.yaml
  src/euler_one_qubit_decomposer.rs
  test/python/transpiler/test_optimize_1q_decomposition.py
Labels: performance, Changelog: New Feature, automerge, Rust, mod: transpiler

#9707 More fixing extra whitespace surrounding docstrings
  qiskit/qasm/qasmlexer.py
  qiskit/quantum_info/operators/symplectic/stabilizer_table.py
  test/python/result/test_result.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: type: qa, automerge, Changelog: None

#9323 Remove TextDrawing arguments layout, global_phase, qregs, and cregs
  qiskit/visualization/circuit/circuit_visualization.py
  qiskit/visualization/circuit/text.py
  releasenotes/notes/circuit_visualization_args_removed-73399f362ab863b3.yaml
Labels: Changelog: Removal, automerge

#9677 Fix UnitarySynthesis with target that contains custom gates
  qiskit/transpiler/passes/synthesis/unitary_synthesis.py
  test/python/transpiler/test_unitary_synthesis.py
Labels: automerge, Changelog: None

#9712 Remove unneeded Sphinx templates and static files
  docs/_static/custom.css
  docs/_templates/layout.html
  docs/_templates/page.html
  docs/_templates/theme_variables.jinja
  docs/_templates/versions.html
  docs/conf.py
  docs/images/logo.png
  qiskit/circuit/classicalfunction/__init__.py
Labels: documentation, stable backport potential, automerge, Changelog: None

#9706 Improve deprecation message of `Bit.{index,register}`
  qiskit/circuit/bit.py
  qiskit/test/base.py
Labels: stable backport potential, automerge, Changelog: None

#9719 Fix handling of BackendV1 simulators in PassManagerConfig.from_backend
  qiskit/transpiler/instruction_durations.py
  qiskit/transpiler/passmanager_config.py
  releasenotes/notes/fix-backendv1-pm-config-from-backend-914869dd6e1c06be.yaml
  test/python/transpiler/test_passmanager_config.py
Labels: stable backport potential, Changelog: Bugfix, automerge, mod: transpiler

#9730 Fix typo in docstring
  qiskit/visualization/counts_visualization.py
Labels: documentation, stable backport potential, automerge, Changelog: None

#9714 Add docs team to tag list for docs configuation changes
  qiskit_bot.yaml
Labels: type: qa, automerge, Changelog: None

#9736 Update slack invite link to https://qisk.it/join-slack
  README.md
Labels: automerge, Changelog: None

#9733 Add inverse method to ECRGate
  qiskit/circuit/library/standard_gates/ecr.py
  releasenotes/notes/add-inverse-ecr-e03720252a0c9c1e.yaml
Labels: stable backport potential, Changelog: Bugfix, automerge

#9739 test/transpiler: add regression tests for #9701
  test/python/transpiler/test_optimize_1q_decomposition.py
Labels: automerge, Changelog: None, Community PR

#9701 transpiler/1q_decomposition: fix circuit score for zero gate errors
  qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py
  releasenotes/notes/0.23/fix-transpiler-optimize-1q-decomposition-score-e79ea05c3cf1b6fa.yaml
  test/python/transpiler/test_optimize_1q_decomposition.py
Labels: Changelog: Bugfix, automerge, Community PR

#9744 Fix bitstring padding in the `BackendSampler`
  qiskit/primitives/backend_sampler.py
  releasenotes/notes/fix-backendsampler-padding-ed959e6dc3deb3f3.yaml
  test/python/primitives/test_backend_sampler.py
Labels: stable backport potential, Changelog: Bugfix, automerge, mod: primitives

#9742 Add structure for multiple Rust crates
  .github/workflows/coverage.yml
  Cargo.lock
  Cargo.toml
  MANIFEST.in
  crates/accelerate/Cargo.toml
  crates/accelerate/README.md
  crates/accelerate/src/dense_layout.rs
  crates/accelerate/src/edge_collections.rs
  crates/accelerate/src/error_map.rs
  crates/accelerate/src/euler_one_qubit_decomposer.rs
  crates/accelerate/src/lib.rs
  crates/accelerate/src/nlayout.rs
  crates/accelerate/src/optimize_1q_gates.rs
  crates/accelerate/src/pauli_exp_val.rs
  crates/accelerate/src/results/converters.rs
  crates/accelerate/src/results/marginalization.rs
  crates/accelerate/src/results/mod.rs
  crates/accelerate/src/sabre_layout.rs
  crates/accelerate/src/sabre_swap/layer.rs
  crates/accelerate/src/sabre_swap/mod.rs
  crates/accelerate/src/sabre_swap/neighbor_table.rs
  crates/accelerate/src/sabre_swap/sabre_dag.rs
  crates/accelerate/src/sabre_swap/swap_map.rs
  crates/accelerate/src/sampled_exp_val.rs
  crates/accelerate/src/sparse_pauli_op.rs
  crates/accelerate/src/stochastic_swap.rs
  crates/accelerate/src/vf2_layout.rs
  setup.py
Labels: type: qa, automerge, Changelog: None, Rust

#9749 Tag Eric in Rust changes
  qiskit_bot.yaml
Labels: automerge, Changelog: None

#9748 Fix docs build on case-insensitive systems
  docs/conf.py
Labels: documentation, automerge, Changelog: None

#9754 Don't require Tweedledum for `qiskit.circuit.classicalfunction` on import
  qiskit/circuit/classicalfunction/__init__.py
  qiskit/circuit/classicalfunction/boolean_expression.py
  qiskit/circuit/classicalfunction/classical_function_visitor.py
  qiskit/circuit/classicalfunction/classicalfunction.py
  qiskit/circuit/classicalfunction/utils.py
Labels: automerge, Changelog: None

#9767 Suppress PulseSimulator deprecation warning in tests
  test/python/pulse/test_block.py
Labels: type: qa, automerge, Changelog: None

#9765 Fix `tox -e docs` for macOS
  .azure/docs-linux.yml
  setup.py
  tox.ini
Labels: documentation, automerge, Changelog: None

#9726 Fix zero-qubit `Pauli` label strings
  qiskit/quantum_info/operators/symplectic/pauli.py
  releasenotes/notes/fix-empty-pauli-label-ce2580584db67a4d.yaml
  test/python/opflow/test_op_construction.py
  test/python/primitives/test_estimator.py
  test/python/quantum_info/operators/symplectic/test_pauli.py
Labels: Changelog: Bugfix, automerge, mod: quantum info

#9766 Implementing CouplingMap.__eq__
  qiskit/transpiler/coupling.py
  releasenotes/notes/coupling-map-eq-b0507b703d62a5f3.yaml
  test/python/transpiler/test_coupling.py
Labels: Changelog: API Change, automerge

#9777 Qiskit gates not `qelib1.inc` are now defined when dumped
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/fix_9559-ec05304e52ff841f.yaml
  test/python/circuit/test_circuit_qasm.py
Labels: stable backport potential, Changelog: Bugfix, automerge, qasm

#9664 Fix `Parameter.is_real()`
  qiskit/circuit/parameterexpression.py
  releasenotes/notes/fix-parameter-is_real-8b8f99811e58075e.yaml
  test/python/circuit/test_parameters.py
Labels: Changelog: Bugfix, automerge, Community PR

#9786 Fix explicitly calibrated gates in `GateDirection`
  qiskit/transpiler/passes/utils/gate_direction.py
  releasenotes/notes/fix-gate-direction-calibration-c51202358d86e18f.yaml
  test/python/transpiler/test_gate_direction.py
Labels: stable backport potential, Changelog: Bugfix, automerge, mod: pulse, mod: transpiler

#9685 Add `add_deprecation_to_docstring` for docsite deprecation support
  qiskit/utils/deprecation.py
  releasenotes/notes/new-deprecation-utilities-066aff05e221d7b1.yaml
  test/python/utils/test_deprecation.py
Labels: Changelog: New Feature, automerge

#9787 Improve error messages in `Target`-based `GateDirection` pass
  qiskit/transpiler/passes/utils/gate_direction.py
  test/python/transpiler/test_gate_direction.py
Labels: stable backport potential, automerge, Changelog: None, mod: transpiler

#9698 extend the documentation for qiskit.circuit.QuantumCircuit.measure
  qiskit/circuit/quantumcircuit.py
Labels: documentation, stable backport potential, automerge, Changelog: None

#9413 Alternative construction mechanism for HLS config
  qiskit/transpiler/passes/synthesis/high_level_synthesis.py
  releasenotes/notes/add-alternative-hls-construction-afec157f7cf15b0b.yaml
  test/python/transpiler/test_high_level_synthesis.py
Labels: Changelog: New Feature, automerge

#9790 `@deprecate_arguments` and `@deprecate_function` add deprecation to docstring
  qiskit/algorithms/factorizers/shor.py
  qiskit/algorithms/linear_solvers/hhl.py
  qiskit/algorithms/phase_estimators/phase_estimation_result.py
  qiskit/dagcircuit/dagcircuit.py
  qiskit/utils/deprecation.py
  test/python/utils/test_deprecation.py
Labels: documentation, automerge, Changelog: None

#9779 Remove implicit broadcasting from `Pauli`/label construction of `PauliList`
  qiskit/quantum_info/operators/symplectic/pauli_list.py
  releasenotes/notes/paulilist-do-not-broadcast-from-paulis-96de3832fba21b94.yaml
  test/python/quantum_info/operators/symplectic/test_pauli_list.py
Labels: Changelog: Bugfix, automerge, mod: quantum info

#9771 Some doc formatting and link, mostly on quantumcircuit.py file
  qiskit/algorithms/optimizers/qnspsa.py
  qiskit/circuit/__init__.py
  qiskit/circuit/bit.py
  qiskit/circuit/controlflow/for_loop.py
  qiskit/circuit/instruction.py
  qiskit/circuit/instructionset.py
  qiskit/circuit/quantumcircuit.py
  qiskit/circuit/register.py
Labels: documentation, stable backport potential, automerge, Changelog: None

#9809 Attempt to trigger Azure pipelines on merge queue events
  azure-pipelines.yml
Labels: type: qa, stable backport potential, Changelog: None

#7264 new parameters in `plot_bloch_multivector`: `figsize`, `font_size`, and `title_font_size`
  qiskit/visualization/bloch.py
  qiskit/visualization/state_visualization.py
  releasenotes/notes/update-state-visualization-6836bd53e3a24891.yaml
  test/ipynb/mpl/graph/references/bloch_multivector_figsize_improvements.png
  test/ipynb/mpl/graph/test_graph_matplotlib_drawer.py
Labels: Changelog: New Feature, Community PR

#9583 Leverage Rust circuit sequence construction for `OneQubitEulerDecomposer`
  crates/accelerate/src/euler_one_qubit_decomposer.rs
  qiskit/quantum_info/synthesis/one_qubit_decompose.py
Labels: performance, mod: quantum info, Changelog: None, Rust

#9806 Remove useless `into_iter()` on `Range`
  crates/accelerate/src/dense_layout.rs
Labels: stable backport potential, Changelog: None, Rust

#9762 Clip probabilities in ``QuantumState``
  qiskit/quantum_info/states/densitymatrix.py
  qiskit/quantum_info/states/quantum_state.py
  qiskit/quantum_info/states/statevector.py
  releasenotes/notes/clip-quantumstate-probabilities-5c9ce05ffa699a63.yaml
  test/python/quantum_info/states/test_densitymatrix.py
  test/python/quantum_info/states/test_statevector.py
Labels: stable backport potential, Changelog: Bugfix, mod: quantum info, mod: primitives

#9807 Stop using mergify merge queue feature
  .mergify.yml
Labels: type: qa, Changelog: None

#9758 Fix Tox installing Terra from PyPI
  tox.ini
Labels: type: qa, Changelog: None

#9757 Consolidate `pip install` calls in CI
  .azure/lint-linux.yml
  .azure/test-linux.yml
  .azure/test-macos.yml
  .azure/test-windows.yml
  .azure/tutorials-linux.yml
Labels: type: qa, Changelog: None

#9819 Fix `QuantumCircuit.qasm` with `reset`
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/fix-qasm-reset-ef7b07bf55875be7.yaml
  test/python/circuit/test_circuit_qasm.py
Labels: stable backport potential, Changelog: Bugfix, qasm

#9799 transpile: narrow the return type depending on the circuits argument
  qiskit/compiler/transpiler.py
  releasenotes/notes/improve-transpile-typing-de1197f4dd13ac0c.yaml
Labels: documentation, Changelog: Bugfix, Community PR

#9828 Fix non-complex dtypes in OneQubitEulerDecomposer methods
  qiskit/quantum_info/synthesis/one_qubit_decompose.py
  releasenotes/notes/fix-type-angles-euler-decompose-233e5cee7205ed03.yaml
  test/python/quantum_info/test_synthesis.py
Labels: stable backport potential, Changelog: Bugfix, mod: quantum info, synthesis

#9735 Start deprecation of complex parameters in Qiskit Pulse
  qiskit/pulse/parameter_manager.py
  qiskit/pulse/utils.py
  releasenotes/notes/symbolic-pulse-complex-deprecation-89ecdf968b1a2d89.yaml
  test/python/pulse/test_parameter_manager.py
Labels: mod: pulse

#9620 Performance improvement of `SparsePauliOp.to_matrix`
  qiskit/quantum_info/operators/symplectic/base_pauli.py
  test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
Labels: performance, mod: quantum info

#9843 Fix missing handling of no-synthesis case in `UnitarySynthesis`
  qiskit/transpiler/passes/synthesis/unitary_synthesis.py
  test/python/transpiler/test_unitary_synthesis.py
Labels: Changelog: None

#9796 Improve ``Parameter`` handling in ``SparsePauliOp``
  qiskit/algorithms/time_evolvers/trotterization/trotter_qrte.py
  qiskit/algorithms/time_evolvers/variational/solvers/var_qte_linear_solver.py
  qiskit/algorithms/utils/assign_params.py
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
  releasenotes/notes/sparsepauliop-improved-parameter-support-413f7598bac72166.yaml
  test/python/algorithms/time_evolvers/test_trotter_qrte.py
  test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
Labels: Changelog: New Feature, mod: quantum info

#9844 Move OQ3 exporter tests to qasm3 module
  test/python/qasm3/__init__.py
  test/python/qasm3/test_export.py
Labels: type: qa, Changelog: None

#9825 Add option to skip deepcopy on dag_to_circuit
  qiskit/circuit/quantumcircuit.py
  qiskit/compiler/transpiler.py
  qiskit/converters/dag_to_circuit.py
  qiskit/transpiler/basepasses.py
  qiskit/transpiler/passes/basis/basis_translator.py
  qiskit/transpiler/passes/utils/control_flow.py
  qiskit/transpiler/runningpassmanager.py
  releasenotes/notes/deepcopy-option-dag_to_circuit-2974aa9e66dc7643.yaml
Labels: performance, Changelog: New Feature, mod: transpiler

#9850 Ensure up-to-date `pip`, `setuptools` and `wheel` in CI
  .azure/lint-linux.yml
  .azure/test-linux.yml
  .azure/test-macos.yml
  .azure/test-windows.yml
  .azure/tutorials-linux.yml
  .github/workflows/coverage.yml
  .github/workflows/randomized_tests.yml
  .github/workflows/slow.yml
Labels: type: qa, Changelog: None

#9832 Remove factorizers and linear solvers from `algorithms`
  qiskit/algorithms/__init__.py
  qiskit/algorithms/factorizers/__init__.py
  qiskit/algorithms/factorizers/shor.py
  qiskit/algorithms/linear_solvers/__init__.py
  qiskit/algorithms/linear_solvers/hhl.py
  qiskit/algorithms/linear_solvers/linear_solver.py
  qiskit/algorithms/linear_solvers/matrices/__init__.py
  qiskit/algorithms/linear_solvers/matrices/linear_system_matrix.py
  qiskit/algorithms/linear_solvers/matrices/numpy_matrix.py
  qiskit/algorithms/linear_solvers/matrices/tridiagonal_toeplitz.py
  qiskit/algorithms/linear_solvers/numpy_linear_solver.py
  qiskit/algorithms/linear_solvers/observables/__init__.py
  qiskit/algorithms/linear_solvers/observables/absolute_average.py
  qiskit/algorithms/linear_solvers/observables/linear_system_observable.py
  qiskit/algorithms/linear_solvers/observables/matrix_functional.py
  releasenotes/notes/remove-deprecated-factorizers-linear-solvers-4631870129749624.yaml
  test/python/algorithms/test_backendv1.py
  test/python/algorithms/test_backendv2.py
  test/python/algorithms/test_linear_solvers.py
  test/python/algorithms/test_shor.py
Labels: Changelog: Removal, mod: algorithms

#9860 Fix examples in `VarQITE` and `VarQRTE` docstrings
  qiskit/algorithms/time_evolvers/variational/var_qite.py
  qiskit/algorithms/time_evolvers/variational/var_qrte.py
Labels: documentation, Changelog: None

#9864 Apply new deprecation decorators to algorithms folder
  qiskit/algorithms/amplitude_amplifiers/grover.py
  qiskit/algorithms/amplitude_estimators/ae.py
  qiskit/algorithms/amplitude_estimators/fae.py
  qiskit/algorithms/amplitude_estimators/iae.py
  qiskit/algorithms/amplitude_estimators/mlae.py
  qiskit/algorithms/aux_ops_evaluator.py
  qiskit/algorithms/eigen_solvers/eigen_solver.py
  qiskit/algorithms/eigen_solvers/numpy_eigen_solver.py
  qiskit/algorithms/eigen_solvers/vqd.py
  qiskit/algorithms/evolvers/evolution_problem.py
  qiskit/algorithms/evolvers/evolution_result.py
  qiskit/algorithms/evolvers/imaginary_evolver.py
  qiskit/algorithms/evolvers/real_evolver.py
  qiskit/algorithms/evolvers/trotterization/trotter_qrte.py
  qiskit/algorithms/minimum_eigen_solvers/minimum_eigen_solver.py
  qiskit/algorithms/minimum_eigen_solvers/numpy_minimum_eigen_solver.py
  qiskit/algorithms/minimum_eigen_solvers/qaoa.py
  qiskit/algorithms/minimum_eigen_solvers/vqe.py
  qiskit/algorithms/optimizers/adam_amsgrad.py
  qiskit/algorithms/optimizers/qnspsa.py
  qiskit/algorithms/optimizers/spsa.py
  qiskit/algorithms/phase_estimators/hamiltonian_phase_estimation.py
  qiskit/algorithms/phase_estimators/ipe.py
  qiskit/algorithms/phase_estimators/phase_estimation.py
  qiskit/algorithms/phase_estimators/phase_estimation_result.py
  test/python/algorithms/optimizers/test_spsa.py
Labels: mod: algorithms, Changelog: None

#8263 Fix mypy errors (primitives)
  qiskit/primitives/backend_estimator.py
  qiskit/primitives/backend_sampler.py
  qiskit/primitives/base/base_primitive.py
Labels: mod: primitives, Community PR, mypy

#9801 Fix a typo in `PauliList.insert` docstring
  qiskit/quantum_info/operators/symplectic/base_pauli.py
  qiskit/quantum_info/operators/symplectic/pauli_list.py
Labels: documentation, Changelog: None

#9862 Only do HLS plugin discovery once
  qiskit/transpiler/passes/synthesis/high_level_synthesis.py
Labels: stable backport potential, performance, Changelog: None, mod: transpiler

#9870 Apply new deprecation decorators to qobj and qpy
  qiskit/qobj/__init__.py
  qiskit/qobj/converters/pulse_instruction.py
  qiskit/qobj/pulse_qobj.py
  qiskit/qobj/qasm_qobj.py
  qiskit/qpy/interface.py
Labels: Changelog: None

#8270 Fix mypy errors (visualization)
  qiskit/visualization/pulse/interpolation.py
  qiskit/visualization/pulse/matplotlib.py
  qiskit/visualization/pulse/qcstyle.py
  qiskit/visualization/pulse_v2/core.py
  qiskit/visualization/pulse_v2/drawings.py
  qiskit/visualization/pulse_v2/events.py
  qiskit/visualization/pulse_v2/generators/waveform.py
  qiskit/visualization/pulse_v2/types.py
  qiskit/visualization/timeline/core.py
Labels: Community PR

#9875 Apply new deprecation decorators to util files and folders
  qiskit/execute_function.py
  qiskit/opflow/gradients/derivative_base.py
  qiskit/synthesis/evolution/suzuki_trotter.py
  qiskit/test/decorators.py
  qiskit/utils/quantum_instance.py
Labels: type: qa, Changelog: None

#9873 Apply new deprecation decorators to quantum_info folder
  qiskit/quantum_info/operators/symplectic/pauli_table.py
  qiskit/quantum_info/operators/symplectic/pauli_utils.py
  qiskit/quantum_info/operators/symplectic/random.py
  qiskit/quantum_info/operators/symplectic/stabilizer_table.py
  qiskit/quantum_info/synthesis/clifford_decompose.py
  qiskit/quantum_info/synthesis/cnotdihedral_decompose.py
  qiskit/quantum_info/synthesis/two_qubit_decompose.py
Labels: type: qa, Changelog: None

#9871 Apply new deprecation decorators to pulse folder
  qiskit/pulse/instructions/instruction.py
  qiskit/pulse/library/parametric_pulses.py
  qiskit/pulse/library/symbolic_pulses.py
  qiskit/pulse/transforms/alignments.py
  qiskit/pulse/utils.py
Labels: type: qa, Changelog: None

#9877 Refactor test to not use deprecated `CXDirection`
  test/python/visualization/references/pass_manager_standard.dot
  test/python/visualization/references/pass_manager_style.dot
  test/python/visualization/test_pass_manager_drawer.py
Labels: type: qa, Changelog: None

#9486 Add public layout attribute to QuantumCircuit
  qiskit/circuit/quantumcircuit.py
  qiskit/transpiler/__init__.py
  qiskit/transpiler/layout.py
  releasenotes/notes/add-layout-attribute-c84e56c08ca93ada.yaml
Labels: Changelog: New Feature

#9612 Add MinimumPoint transpiler pass
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/utils/__init__.py
  qiskit/transpiler/passes/utils/minimum_point.py
  qiskit/transpiler/preset_passmanagers/level3.py
  releasenotes/notes/add-minimum-point-pass-09cf9a9eec86fd48.yaml
  test/python/compiler/test_transpiler.py
  test/python/transpiler/test_minimum_point.py
Labels: Changelog: New Feature, mod: transpiler

#8714 Add note on historical naming in CircuitInstruction
  qiskit/circuit/quantumcircuitdata.py
Labels: documentation, Changelog: None

#9882 Improve error messages on failed circuit-equality assertions
  qiskit/test/base.py
Labels: type: qa, Changelog: None

#9848 Add option to skip deepcopy on circuit_to_dag
  qiskit/circuit/quantumcircuit.py
  qiskit/converters/circuit_to_dag.py
  releasenotes/notes/deepcopy-option-circuit_to_dag-1d494b7f9824ec93.yaml
Labels: performance, Changelog: New Feature
