Repository Qiskit/qiskit, pull requests merged in 2023-01, with the labels that each got.

#9326 some small issues in Counts documentation
  qiskit/result/counts.py
Labels: stable backport potential, automerge, Changelog: None

#8839 Fix PulseQobj converter name collision
  qiskit/assembler/assemble_schedules.py
  qiskit/assembler/disassemble.py
  qiskit/qobj/converters/pulse_instruction.py
  releasenotes/notes/fix-pulse-qobj-converter-name-collision-0b225af630f4a6c6.yaml
  test/python/qobj/test_pulse_converter.py
Labels: Changelog: Bugfix, automerge

#9345 Change algorithms status from pending deprecate to deprecate
  qiskit/algorithms/__init__.py
  qiskit/algorithms/amplitude_amplifiers/grover.py
  qiskit/algorithms/amplitude_estimators/ae.py
  qiskit/algorithms/amplitude_estimators/fae.py
  qiskit/algorithms/amplitude_estimators/iae.py
  qiskit/algorithms/amplitude_estimators/mlae.py
  qiskit/algorithms/aux_ops_evaluator.py
  qiskit/algorithms/eigen_solvers/eigen_solver.py
  qiskit/algorithms/eigen_solvers/numpy_eigen_solver.py
  qiskit/algorithms/eigen_solvers/vqd.py
  qiskit/algorithms/evolvers/evolution_problem.py
  qiskit/algorithms/evolvers/evolution_result.py
  qiskit/algorithms/evolvers/imaginary_evolver.py
  qiskit/algorithms/evolvers/real_evolver.py
  qiskit/algorithms/evolvers/trotterization/trotter_qrte.py
  qiskit/algorithms/minimum_eigen_solvers/minimum_eigen_solver.py
  qiskit/algorithms/minimum_eigen_solvers/numpy_minimum_eigen_solver.py
  qiskit/algorithms/minimum_eigen_solvers/qaoa.py
  qiskit/algorithms/minimum_eigen_solvers/vqe.py
  qiskit/algorithms/optimizers/qnspsa.py
  qiskit/algorithms/phase_estimators/hamiltonian_phase_estimation.py
  qiskit/algorithms/phase_estimators/ipe.py
  qiskit/algorithms/phase_estimators/phase_estimation.py
  releasenotes/notes/deprecate-algorithms-508b9616d81eeb2d.yaml
  test/python/algorithms/evolvers/test_evolution_problem.py
  test/python/algorithms/evolvers/test_evolution_result.py
  test/python/algorithms/evolvers/trotterization/test_trotter_qrte.py
  test/python/algorithms/optimizers/test_optimizer_aqgd.py
  test/python/algorithms/optimizers/test_optimizer_nft.py
  test/python/algorithms/optimizers/test_optimizers_scikitquant.py
  test/python/algorithms/optimizers/test_spsa.py
  test/python/algorithms/test_amplitude_estimators.py
  test/python/algorithms/test_aux_ops_evaluator.py
  test/python/algorithms/test_backendv1.py
  test/python/algorithms/test_backendv2.py
  test/python/algorithms/test_grover.py
  test/python/algorithms/test_measure_error_mitigation.py
  test/python/algorithms/test_numpy_eigen_solver.py
  test/python/algorithms/test_numpy_minimum_eigen_solver.py
  test/python/algorithms/test_phase_estimator.py
  test/python/algorithms/test_qaoa.py
  test/python/algorithms/test_vqd.py
  test/python/algorithms/test_vqe.py
  test/python/algorithms/time_evolvers/test_pvqd.py
Labels: Changelog: Deprecation, automerge, mod: algorithms

#9348 Re-enable parallel sphinx builds by default
  tox.ini
Labels: type: qa, automerge, Changelog: None

#9329 Add GaussianSquareDrag symbolic pulse shape
  qiskit/pulse/__init__.py
  qiskit/pulse/library/__init__.py
  qiskit/pulse/library/symbolic_pulses.py
  qiskit/qobj/converters/pulse_instruction.py
  releasenotes/notes/gaussian-square-drag-pulse-1e54fe77e59d5247.yaml
  test/python/pulse/test_pulse_lib.py
Labels: automerge

#9067 Translate parameterized gates only in gradient calculations
  qiskit/algorithms/gradients/base_estimator_gradient.py
  qiskit/algorithms/gradients/base_sampler_gradient.py
  qiskit/algorithms/gradients/utils.py
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/basis/__init__.py
  qiskit/transpiler/passes/basis/translate_parameterized.py
  releasenotes/notes/gradients-preserve-unparameterized-8ebff145b6c96fa3.yaml
  test/python/algorithms/gradients/logging_primitives.py
  test/python/algorithms/gradients/test_estimator_gradient.py
  test/python/algorithms/gradients/test_qfi.py
  test/python/algorithms/gradients/test_sampler_gradient.py
  test/python/transpiler/test_parameterizedgate_translator.py
Labels: Changelog: New Feature, automerge, mod: algorithms

#9101 Fix `NumPyEigensolver` with `SparsePauliOp`
  qiskit/algorithms/eigensolvers/numpy_eigensolver.py
  qiskit/algorithms/minimum_eigensolvers/numpy_minimum_eigensolver.py
  qiskit/quantum_info/operators/operator.py
  releasenotes/notes/fix-numpy-eigensolver-sparse-pauli-op-b09a9ac8fb93fe4a.yaml
  test/python/algorithms/eigensolvers/test_numpy_eigensolver.py
  test/python/algorithms/minimum_eigensolvers/test_numpy_minimum_eigensolver.py
  test/python/quantum_info/operators/test_operator.py
Labels: Changelog: Bugfix, automerge, mod: algorithms

#9342 Remove deprecated MSBasisDecomposer transpiler pass
  qiskit/transpiler/passes/basis/ms_basis_decomposer.py
  releasenotes/notes/drop-ms-basis-pass-19721ea1fdfee713.yaml
Labels: Changelog: Removal, automerge

#9320 Fix documentation of circuit depth filter function
  qiskit/circuit/quantumcircuit.py
Labels: documentation, automerge, Changelog: None

#9354 Add ElePT as ``qiskit/algorithms`` code owner
  .github/CODEOWNERS
Labels: automerge, Changelog: None

#9316 Fix ``ComposedOp.to_matrix``
  qiskit/opflow/list_ops/composed_op.py
  qiskit/opflow/list_ops/list_op.py
  releasenotes/notes/fix-composedop-08e14db184c637c8.yaml
  test/python/opflow/test_op_construction.py
Labels: stable backport potential, Changelog: Bugfix, automerge, mod: opflow

#9310 Update `qiskit.utils.wrap_method` for Python 3.11
  azure-pipelines.yml
  qiskit/utils/classtools.py
  releasenotes/notes/wrap-method-311-147d254d4b40e805.yaml
  test/python/utils/test_classtools.py
Labels: Changelog: Bugfix, automerge

#9290 Fix typo in fake_provider.py
  qiskit/providers/fake_provider/fake_provider.py
Labels: documentation, automerge, Changelog: None, Community PR

#9318 Add efficient gate power methods
  qiskit/circuit/library/standard_gates/i.py
  qiskit/circuit/library/standard_gates/iswap.py
  qiskit/circuit/library/standard_gates/p.py
  qiskit/circuit/library/standard_gates/r.py
  qiskit/circuit/library/standard_gates/rx.py
  qiskit/circuit/library/standard_gates/rxx.py
  qiskit/circuit/library/standard_gates/ry.py
  qiskit/circuit/library/standard_gates/ryy.py
  qiskit/circuit/library/standard_gates/rz.py
  qiskit/circuit/library/standard_gates/rzx.py
  qiskit/circuit/library/standard_gates/rzz.py
  qiskit/circuit/library/standard_gates/s.py
  qiskit/circuit/library/standard_gates/t.py
  qiskit/circuit/library/standard_gates/xx_minus_yy.py
  qiskit/circuit/library/standard_gates/xx_plus_yy.py
  qiskit/circuit/library/standard_gates/z.py
  releasenotes/notes/efficient-gate-power-effa21e3ee4581ee.yaml
  test/python/circuit/test_gate_power.py
Labels: Changelog: New Feature, automerge

#9359 Simplify UnitarySynthesis pass test test_qv_natural
  test/python/transpiler/test_unitary_synthesis.py
Labels: type: qa, automerge, Changelog: None

#9220 Synthesis of a Clifford circuit into layers
  qiskit/synthesis/__init__.py
  qiskit/synthesis/clifford/__init__.py
  qiskit/synthesis/clifford/clifford_decompose_layers.py
  qiskit/synthesis/linear/linear_matrix_utils.py
  releasenotes/notes/clifford_layered_synthesis-1a6b1038458ae8c3.yaml
  test/python/synthesis/test_clifford_decompose_layers.py
Labels: Changelog: New Feature, automerge

#7483 Speed up `Clifford.compose`
  qiskit/quantum_info/operators/symplectic/clifford.py
  releasenotes/notes/clifford-compose-performance-96808ba11327e7dd.yaml
Labels: performance, Changelog: New Feature, automerge, mod: quantum info

#9319 Fix deprecation warning when running `pytest test_aer_pauli_expectation.py`
  test/python/opflow/test_aer_pauli_expectation.py
Labels: automerge, mod: opflow, Changelog: None, Community PR

#9304 Add option to allow passing unknown parameters to ParameterExpression.bind
  qiskit/circuit/parameter.py
  qiskit/circuit/parameterexpression.py
  releasenotes/notes/allow-unknown-parameters-eca32e2cfebe8c5a.yaml
  test/python/circuit/test_parameters.py
Labels: Changelog: New Feature, automerge

#9206 Fix `QuantumCircuit.compose` on unusual types and registers
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/fix-compose-35d2fdbe5b052bca.yaml
  test/python/circuit/test_compose.py
  test/python/dagcircuit/test_compose.py
Labels: Changelog: Bugfix, automerge

#9360 Move Solovay Kitaev docs to where they are more easily found
  qiskit/synthesis/__init__.py
  qiskit/synthesis/discrete_basis/__init__.py
  qiskit/synthesis/discrete_basis/gate_sequence.py
  qiskit/synthesis/discrete_basis/solovay_kitaev.py
  qiskit/transpiler/passes/synthesis/solovay_kitaev_synthesis.py
Labels: documentation, automerge, Changelog: None

#9292 refactored and optimized code
  examples/python/initialize.py
  qiskit/algorithms/amplitude_amplifiers/grover.py
Labels: automerge, Changelog: None, Community PR

#9314 Introducing ScalableSymbolicPulse to correctly compare pulses of amp,angle representation
  qiskit/pulse/__init__.py
  qiskit/pulse/library/__init__.py
  qiskit/pulse/library/symbolic_pulses.py
  qiskit/qpy/__init__.py
  qiskit/qpy/binary_io/circuits.py
  qiskit/qpy/binary_io/schedules.py
  qiskit/qpy/common.py
  qiskit/qpy/formats.py
  qiskit/qpy/interface.py
  releasenotes/notes/new_pulse_subclass-44da774612699312.yaml
  test/python/pulse/test_pulse_lib.py
Labels: Changelog: New Feature, Changelog: API Change, automerge, mod: pulse

#9361 Refactor coverage CI workflow
  .github/workflows/coverage.yml
  constraints.txt
Labels: type: qa, automerge, Changelog: None

#9364 Relax constraints on jupyter-core and ipywidgets
  .azure/test-linux.yml
  constraints.txt
  qiskit/test/base.py
Labels: type: qa, automerge, Changelog: None

#9368 Fix stable tests
  .azure/test-linux.yml
  .github/workflows/coverage.yml
  constraints.txt
  qiskit/algorithms/optimizers/snobfit.py
  qiskit/circuit/instruction.py
  qiskit/quantum_info/operators/channel/kraus.py
  qiskit/test/base.py
  qiskit/utils/classtools.py
  releasenotes/notes/wrap-method-311-147d254d4b40e805.yaml
  requirements-dev.txt
  test/python/algorithms/optimizers/test_optimizers_scikitquant.py
  test/python/test_util.py
  test/python/utils/test_classtools.py
Labels: type: qa, automerge, Changelog: None

#9362 Revert "Change algorithms status from pending deprecate to deprecate"
  qiskit/algorithms/__init__.py
  qiskit/algorithms/amplitude_amplifiers/grover.py
  qiskit/algorithms/amplitude_estimators/ae.py
  qiskit/algorithms/amplitude_estimators/fae.py
  qiskit/algorithms/amplitude_estimators/iae.py
  qiskit/algorithms/amplitude_estimators/mlae.py
  qiskit/algorithms/aux_ops_evaluator.py
  qiskit/algorithms/eigen_solvers/eigen_solver.py
  qiskit/algorithms/eigen_solvers/numpy_eigen_solver.py
  qiskit/algorithms/eigen_solvers/vqd.py
  qiskit/algorithms/evolvers/evolution_problem.py
  qiskit/algorithms/evolvers/evolution_result.py
  qiskit/algorithms/evolvers/imaginary_evolver.py
  qiskit/algorithms/evolvers/real_evolver.py
  qiskit/algorithms/evolvers/trotterization/trotter_qrte.py
  qiskit/algorithms/minimum_eigen_solvers/minimum_eigen_solver.py
  qiskit/algorithms/minimum_eigen_solvers/numpy_minimum_eigen_solver.py
  qiskit/algorithms/minimum_eigen_solvers/qaoa.py
  qiskit/algorithms/minimum_eigen_solvers/vqe.py
  qiskit/algorithms/optimizers/qnspsa.py
  qiskit/algorithms/phase_estimators/hamiltonian_phase_estimation.py
  qiskit/algorithms/phase_estimators/ipe.py
  qiskit/algorithms/phase_estimators/phase_estimation.py
  releasenotes/notes/deprecate-algorithms-508b9616d81eeb2d.yaml
  test/python/algorithms/evolvers/test_evolution_problem.py
  test/python/algorithms/evolvers/test_evolution_result.py
  test/python/algorithms/evolvers/trotterization/test_trotter_qrte.py
  test/python/algorithms/optimizers/test_optimizer_aqgd.py
  test/python/algorithms/optimizers/test_optimizer_nft.py
  test/python/algorithms/optimizers/test_optimizers_scikitquant.py
  test/python/algorithms/optimizers/test_spsa.py
  test/python/algorithms/test_amplitude_estimators.py
  test/python/algorithms/test_aux_ops_evaluator.py
  test/python/algorithms/test_backendv1.py
  test/python/algorithms/test_backendv2.py
  test/python/algorithms/test_grover.py
  test/python/algorithms/test_measure_error_mitigation.py
  test/python/algorithms/test_numpy_eigen_solver.py
  test/python/algorithms/test_numpy_minimum_eigen_solver.py
  test/python/algorithms/test_phase_estimator.py
  test/python/algorithms/test_qaoa.py
  test/python/algorithms/test_vqd.py
  test/python/algorithms/test_vqe.py
  test/python/algorithms/time_evolvers/test_pvqd.py
Labels: automerge, mod: algorithms, Changelog: None

#9369 Add FakePrague Egret R1 to fake backends
  qiskit/providers/fake_provider/__init__.py
  qiskit/providers/fake_provider/backends/__init__.py
  qiskit/providers/fake_provider/backends/prague/__init__.py
  qiskit/providers/fake_provider/backends/prague/conf_prague.json
  qiskit/providers/fake_provider/backends/prague/fake_prague.py
  qiskit/providers/fake_provider/backends/prague/props_prague.json
  qiskit/providers/fake_provider/fake_provider.py
  releasenotes/notes/add_fake_prague-79f82b83c2e2329c.yaml
Labels: Changelog: New Feature, automerge, mod: fake_provider

#8885 Lazy pulse qobj loading for large backend
  qiskit/providers/backend_compat.py
  qiskit/providers/fake_provider/utils/backend_converter.py
  qiskit/providers/models/backendproperties.py
  qiskit/providers/models/pulsedefaults.py
  qiskit/pulse/calibration_entries.py
  qiskit/pulse/instruction_schedule_map.py
  qiskit/qobj/converters/pulse_instruction.py
  qiskit/qobj/pulse_qobj.py
  qiskit/transpiler/passes/calibration/base_builder.py
  qiskit/transpiler/target.py
  releasenotes/notes/load-backend-fast-9030885adcd9248f.yaml
  test/python/compiler/test_transpiler.py
  test/python/pulse/test_calibration_entries.py
Labels: priority: high, Changelog: New Feature, automerge, mod: pulse

#9331 Fix: AQC returns a wrong circuit when the unitary has a determinant −1
  qiskit/transpiler/synthesis/aqc/aqc.py
  releasenotes/notes/fix-aqc-check-if-su-matrix.yaml
  test/python/transpiler/aqc/test_aqc.py
Labels: Changelog: Bugfix, automerge, Community PR

#9100 Relax register-naming restrictions
  qiskit/circuit/classicalregister.py
  qiskit/circuit/quantumcircuit.py
  qiskit/circuit/quantumregister.py
  qiskit/circuit/register.py
  qiskit/extensions/unitary.py
  qiskit/qpy/binary_io/circuits.py
  releasenotes/notes/relax-register-naming-0e7d2dba9bf7fb38.yaml
  test/python/circuit/test_circuit_qasm.py
  test/python/circuit/test_identifiers_circuits.py
  test/python/circuit/test_register.py
Labels: Changelog: Deprecation, Changelog: API Change, Changelog: Bugfix, automerge, qasm

#9339 Add FakeSherbrooke backend
  qiskit/providers/fake_provider/__init__.py
  qiskit/providers/fake_provider/backends/__init__.py
  qiskit/providers/fake_provider/backends/sherbrooke/__init__.py
  qiskit/providers/fake_provider/backends/sherbrooke/conf_sherbrooke.json
  qiskit/providers/fake_provider/backends/sherbrooke/defs_sherbrooke.json
  qiskit/providers/fake_provider/backends/sherbrooke/fake_sherbrooke.py
  qiskit/providers/fake_provider/backends/sherbrooke/props_sherbrooke.json
  qiskit/providers/fake_provider/fake_provider.py
Labels: Changelog: New Feature, automerge

#8790 Convert Equivalence Library to graph
  qiskit/circuit/equivalence.py
  qiskit/transpiler/passes/basis/basis_translator.py
  releasenotes/notes/equivalence-to-graph-3b52912ecb542db8.yaml
  test/python/circuit/test_equivalence.py
Labels: performance, Changelog: New Feature, Changelog: API Change, automerge, Community PR

#9377 Pin sphinx-autodoc-typehints
  constraints.txt
  requirements-dev.txt
Labels: type: qa, stable backport potential, automerge, Changelog: None

#9376 Prepare 0.22.4
  Cargo.lock
  Cargo.toml
  docs/conf.py
  qiskit/VERSION.txt
  releasenotes/notes/fix-backend-sampler-890cbcf913667b08.yaml
  releasenotes/notes/fix-composedop-08e14db184c637c8.yaml
  releasenotes/notes/fix-primitives-numpy-parameters-1589d997864dfb37.yaml
  releasenotes/notes/fix-sampling-vqe-aggregation-107e3983147c57bc.yaml
  releasenotes/notes/fix-sampling-vqe-performance-b5bfe92c2d3e10ab.yaml
  releasenotes/notes/fix-vqd-betas-async-df99ab6e26e9da1e.yaml
  releasenotes/notes/prepare-0.22.4-cddd573e87bffb9c.yaml
  releasenotes/notes/probabilities_dict_bug_fix-aac3b3d3853828dc.yaml
  releasenotes/notes/wrap-method-311-147d254d4b40e805.yaml
  setup.py
Labels: automerge, Changelog: None

#9325 Remove `gate` argument from qiskit.transpiler.passes.Decompose
  qiskit/transpiler/passes/basis/decompose.py
  releasenotes/notes/remove_gates_to_decompose-7099068d2886dce2.yaml
  test/python/transpiler/test_decompose.py
Labels: Changelog: Removal

#9353 Fix sparse z2 symmetries
  qiskit/quantum_info/analysis/z2_symmetries.py
  test/python/quantum_info/test_sparse_z2_symmetries.py
Labels: bug, automerge, mod: quantum info, Changelog: None, Community PR

#9324 Remove `label` argument from MCMTVChain and MCMT
  qiskit/circuit/library/generalized_gates/mcmt.py
  releasenotes/notes/remove_mcmt_label-cee8a11e0164f8e1.yaml
  test/python/circuit/library/test_mcmt.py
Labels: Changelog: Removal, automerge

#9379 Relax pin on sphinx-autodoc-typehints
  constraints.txt
Labels: type: qa, automerge, Changelog: None

#9321 Fix PauliOp matmul with iI & add PauliOp test
  qiskit/opflow/primitive_ops/pauli_op.py
  releasenotes/notes/fix-Identity-PauliOp-matmul-5e28c9207ed61e90.yaml
  test/python/opflow/test_op_construction.py
Labels: Changelog: Bugfix, automerge, mod: opflow, Community PR

#8834 Barrier support for `visualize_transition` and refactor
  qiskit/visualization/transition_visualization.py
Labels: Changelog: Bugfix, automerge

#8874 Refactor state latex drawer
  qiskit/visualization/array.py
  qiskit/visualization/state_visualization.py
  releasenotes/notes/latex-refactor-0745471ddecac605.yaml
  test/python/quantum_info/states/test_statevector.py
  test/python/visualization/test_utils.py
Labels: Changelog: Deprecation, Changelog: API Change, automerge, mod: visualization

#9041 Deprecate LinearFunctionsSynthesis transpiler pass
  qiskit/transpiler/passes/synthesis/linear_functions_synthesis.py
  releasenotes/notes/deprecate-linear-functions-synthesis-a62c41171cf396dc.yaml
  test/python/transpiler/test_linear_functions_passes.py
Labels: priority: medium, Changelog: Deprecation, automerge, mod: transpiler

#9287 Efficient classical calculation of expectation gradients
  qiskit/algorithms/gradients/__init__.py
  qiskit/algorithms/gradients/base_estimator_gradient.py
  qiskit/algorithms/gradients/lin_comb_estimator_gradient.py
  qiskit/algorithms/gradients/lin_comb_qgt.py
  qiskit/algorithms/gradients/reverse_gradient/__init__.py
  qiskit/algorithms/gradients/reverse_gradient/bind.py
  qiskit/algorithms/gradients/reverse_gradient/derive_circuit.py
  qiskit/algorithms/gradients/reverse_gradient/reverse_gradient.py
  qiskit/algorithms/gradients/reverse_gradient/reverse_qgt.py
  qiskit/algorithms/gradients/reverse_gradient/split_circuits.py
  releasenotes/notes/turbo-gradients-5bebc6e665b900b2.yaml
  test/python/algorithms/gradients/test_estimator_gradient.py
  test/python/algorithms/gradients/test_qfi.py
  test/python/algorithms/gradients/test_qgt.py
Labels: priority: high, Changelog: New Feature, automerge, mod: algorithms

#9383 Pin ``sphinx-autodoc-typehint``
  requirements-dev.txt
Labels: type: qa, automerge, Changelog: None

#9211 Add option to user config to control reverse_bits in circuit drawer
  qiskit/circuit/quantumcircuit.py
  qiskit/user_config.py
  qiskit/visualization/circuit/circuit_visualization.py
  releasenotes/notes/add-reverse-bits-to-user-config-options-0e465e6e92d5b49f.yaml
  test/python/test_user_config.py
  test/python/visualization/test_circuit_text_drawer.py
Labels: Changelog: New Feature, automerge, Community PR, mod: visualization

#9231 Primitives support the dynamic circuits with control flow
  qiskit/primitives/utils.py
  releasenotes/notes/circuit-key-supports-controlflow-a956ebd2fcebaece.yaml
  test/python/primitives/test_backend_sampler.py
  test/python/primitives/test_primitive.py
  test/python/primitives/test_sampler.py
Labels: priority: high, Changelog: New Feature, automerge, mod: primitives

#8080 Add deprecation warning on use of qiskit.IBMQ
  qiskit/__init__.py
  qiskit/providers/fake_provider/__init__.py
  qiskit/tools/jupyter/__init__.py
  qiskit/tools/monitor/overview.py
  qiskit/visualization/gate_map.py
  releasenotes/notes/deprecate-qiskit-ibmq-f0dc372526fe0c57.yaml
  tools/update_fake_backends.py
Labels: Changelog: Deprecation, automerge

#9312 Make BackendSampler set shots and stddev_upper_bound of returned QuasiDistribution
  qiskit/primitives/backend_sampler.py
  releasenotes/notes/backend-sampler-shots-c233d5a3965e0c11.yaml
  test/python/primitives/test_backend_sampler.py
Labels: Changelog: Bugfix, automerge, mod: primitives

#9148 Improve efficiency of vf2 pass search with free nodes
  qiskit/transpiler/passes/layout/vf2_layout.py
  qiskit/transpiler/passes/layout/vf2_post_layout.py
  qiskit/transpiler/passes/layout/vf2_utils.py
  src/error_map.rs
  src/vf2_layout.rs
  test/python/transpiler/test_vf2_layout.py
  test/python/transpiler/test_vf2_post_layout.py
Labels: priority: medium, performance, automerge, Changelog: None, Rust, mod: transpiler

#8597 Add final layout to output quantum circuit from transpiler
  qiskit/quantum_info/operators/operator.py
  qiskit/transpiler/basepasses.py
  qiskit/transpiler/layout.py
  qiskit/transpiler/passes/routing/basic_swap.py
  qiskit/transpiler/passes/routing/lookahead_swap.py
  qiskit/transpiler/runningpassmanager.py
  releasenotes/notes/final_layout-8178327a57b8b96a.yaml
  test/python/quantum_info/operators/test_operator.py
Labels: priority: medium, Changelog: New Feature, automerge

#8746 Implements VarQTE algorithm with primitives.
  qiskit/algorithms/__init__.py
  qiskit/algorithms/gradients/base_estimator_gradient.py
  qiskit/algorithms/gradients/base_qgt.py
  qiskit/algorithms/gradients/base_sampler_gradient.py
  qiskit/algorithms/gradients/finite_diff_estimator_gradient.py
  qiskit/algorithms/gradients/finite_diff_sampler_gradient.py
  qiskit/algorithms/gradients/lin_comb_estimator_gradient.py
  qiskit/algorithms/gradients/lin_comb_qgt.py
  qiskit/algorithms/gradients/lin_comb_sampler_gradient.py
  qiskit/algorithms/gradients/param_shift_estimator_gradient.py
  qiskit/algorithms/gradients/param_shift_sampler_gradient.py
  qiskit/algorithms/gradients/qfi.py
  qiskit/algorithms/gradients/spsa_estimator_gradient.py
  qiskit/algorithms/gradients/spsa_sampler_gradient.py
  qiskit/algorithms/time_evolvers/__init__.py
  qiskit/algorithms/time_evolvers/time_evolution_result.py
  qiskit/algorithms/time_evolvers/variational/__init__.py
  qiskit/algorithms/time_evolvers/variational/solvers/__init__.py
  qiskit/algorithms/time_evolvers/variational/solvers/ode/__init__.py
  qiskit/algorithms/time_evolvers/variational/solvers/ode/abstract_ode_function.py
  qiskit/algorithms/time_evolvers/variational/solvers/ode/assign_params.py
  qiskit/algorithms/time_evolvers/variational/solvers/ode/forward_euler_solver.py
  qiskit/algorithms/time_evolvers/variational/solvers/ode/ode_function.py
  qiskit/algorithms/time_evolvers/variational/solvers/ode/ode_function_factory.py
  qiskit/algorithms/time_evolvers/variational/solvers/ode/var_qte_ode_solver.py
  qiskit/algorithms/time_evolvers/variational/solvers/var_qte_linear_solver.py
  qiskit/algorithms/time_evolvers/variational/var_qite.py
  qiskit/algorithms/time_evolvers/variational/var_qrte.py
  qiskit/algorithms/time_evolvers/variational/var_qte.py
  qiskit/algorithms/time_evolvers/variational/var_qte_result.py
  qiskit/algorithms/time_evolvers/variational/variational_principles/__init__.py
  qiskit/algorithms/time_evolvers/variational/variational_principles/imaginary_mc_lachlan_principle.py
  qiskit/algorithms/time_evolvers/variational/variational_principles/imaginary_variational_principle.py
  qiskit/algorithms/time_evolvers/variational/variational_principles/real_mc_lachlan_principle.py
  qiskit/algorithms/time_evolvers/variational/variational_principles/real_variational_principle.py
  qiskit/algorithms/time_evolvers/variational/variational_principles/variational_principle.py
  releasenotes/notes/add-varqte-primitives-3f0ae76bc281e909.yaml
  test/python/algorithms/time_evolvers/variational/__init__.py
  test/python/algorithms/time_evolvers/variational/solvers/__init__.py
  test/python/algorithms/time_evolvers/variational/solvers/expected_results/__init__.py
  test/python/algorithms/time_evolvers/variational/solvers/expected_results/test_varqte_linear_solver_expected_1.py
  test/python/algorithms/time_evolvers/variational/solvers/ode/__init__.py
  test/python/algorithms/time_evolvers/variational/solvers/ode/test_forward_euler_solver.py
  test/python/algorithms/time_evolvers/variational/solvers/ode/test_ode_function.py
  test/python/algorithms/time_evolvers/variational/solvers/ode/test_var_qte_ode_solver.py
  test/python/algorithms/time_evolvers/variational/solvers/test_varqte_linear_solver.py
  test/python/algorithms/time_evolvers/variational/test_var_qite.py
  test/python/algorithms/time_evolvers/variational/test_var_qrte.py
  test/python/algorithms/time_evolvers/variational/test_var_qte.py
  test/python/algorithms/time_evolvers/variational/variational_principles/__init__.py
  test/python/algorithms/time_evolvers/variational/variational_principles/expected_results/__init__.py
  test/python/algorithms/time_evolvers/variational/variational_principles/expected_results/test_imaginary_mc_lachlan_variational_principle_expected1.py
  test/python/algorithms/time_evolvers/variational/variational_principles/expected_results/test_imaginary_mc_lachlan_variational_principle_expected2.py
  test/python/algorithms/time_evolvers/variational/variational_principles/expected_results/test_imaginary_mc_lachlan_variational_principle_expected3.py
  test/python/algorithms/time_evolvers/variational/variational_principles/imaginary/__init__.py
  test/python/algorithms/time_evolvers/variational/variational_principles/imaginary/test_imaginary_mc_lachlan_principle.py
  test/python/algorithms/time_evolvers/variational/variational_principles/real/__init__.py
  test/python/algorithms/time_evolvers/variational/variational_principles/real/test_real_mc_lachlan_principle.py
Labels: priority: high, Changelog: New Feature, automerge, mod: algorithms

#9248 Remove zero-probability states from Sampler's result
  qiskit/primitives/sampler.py
  releasenotes/notes/update-sampler-zero-filter-8bf0d721af4fbd17.yaml
  test/python/algorithms/test_grover.py
  test/python/primitives/test_sampler.py
Labels: automerge, mod: primitives

#9392 Update PyO3 and Rust Numpy to 0.18.0
  Cargo.lock
  Cargo.toml
  qiskit/transpiler/passes/layout/sabre_layout.py
  qiskit/transpiler/passes/routing/sabre_swap.py
  src/results/marginalization.rs
  src/sabre_layout.rs
  src/sabre_swap/mod.rs
Labels: automerge, Changelog: None, Rust, dependencies

#9273 Fix PVQD docs
  qiskit/algorithms/time_evolvers/pvqd/pvqd.py
Labels: documentation, automerge, Changelog: None

#9157 High-level-synthesis for permutations
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/generalized_gates/__init__.py
  qiskit/circuit/library/generalized_gates/permutation.py
  qiskit/circuit/quantumcircuit.py
  qiskit/synthesis/__init__.py
  qiskit/synthesis/permutation/__init__.py
  qiskit/synthesis/permutation/permutation_full.py
  qiskit/synthesis/permutation/permutation_utils.py
  qiskit/transpiler/passes/synthesis/high_level_synthesis.py
  qiskit/transpiler/passes/synthesis/linear_functions_synthesis.py
  releasenotes/notes/add-permutation-synthesis-plugins-9ab9409bc852f5de.yaml
  setup.py
  test/python/circuit/library/test_permutation.py
  test/python/circuit/test_circuit_qasm.py
  test/python/circuit/test_gate_definitions.py
  test/python/synthesis/test_permutation_synthesis.py
  test/python/transpiler/test_linear_functions_passes.py
Labels: priority: medium, Changelog: New Feature, automerge, synthesis, mod: transpiler

#9347 Add importer for OpenQASM 3
  qiskit/qasm3/__init__.py
  qiskit/qasm3/exceptions.py
  qiskit/utils/optionals.py
  releasenotes/notes/qasm3-import-0e7e01cb75aa6251.yaml
  requirements-dev.txt
  setup.py
  test/python/qasm3/test_import.py
Labels: priority: high, Changelog: New Feature, automerge, qasm

#9169 Constructing Cliffords from quantum circuits with other Cliffords
  qiskit/quantum_info/operators/symplectic/clifford_circuits.py
  qiskit/transpiler/passes/optimization/collect_cliffords.py
  releasenotes/notes/improve-collect-cliffords-f57aeafe95460b18.yaml
  test/python/quantum_info/operators/symplectic/test_clifford.py
  test/python/transpiler/test_clifford_passes.py
Labels: Changelog: New Feature, Changelog: Bugfix, automerge

#9396 Bump main branch version post 0.23.0rc1 tag
  .mergify.yml
  Cargo.lock
  Cargo.toml
  docs/conf.py
  qiskit/VERSION.txt
  setup.py
Labels: Changelog: None

#9394 Fix the ``AmplitudeEstimator`` algorithms for primitive usage
  qiskit/algorithms/amplitude_estimators/ae.py
  qiskit/algorithms/amplitude_estimators/ae_utils.py
  qiskit/algorithms/amplitude_estimators/fae.py
  qiskit/algorithms/amplitude_estimators/iae.py
  qiskit/algorithms/amplitude_estimators/mlae.py
  releasenotes/notes/fix-ae-algorithms-1c0a43c596766cb3.yaml
  test/python/algorithms/test_amplitude_estimators.py
Labels: priority: high, stable backport potential, Changelog: Bugfix, automerge, mod: algorithms

#9404 Fix ``TensoredOp.to_matrix`` with global coefficients
  qiskit/opflow/list_ops/tensored_op.py
  releasenotes/notes/fix-tensoredop-to-matrix-6f22644f1bdb8b41.yaml
  test/python/opflow/test_op_construction.py
  test/python/opflow/test_state_construction.py
Labels: stable backport potential, Changelog: Bugfix, automerge, mod: opflow

#9343 Add target support to basis, optimization, scheduling, and util passes
  qiskit/transpiler/passes/basis/unroller.py
  qiskit/transpiler/passes/calibration/pulse_gate.py
  qiskit/transpiler/passes/calibration/rzx_builder.py
  qiskit/transpiler/passes/optimization/commutative_cancellation.py
  qiskit/transpiler/passes/optimization/crosstalk_adaptive_schedule.py
  qiskit/transpiler/passes/optimization/echo_rzx_weyl_decomposition.py
  qiskit/transpiler/passes/optimization/optimize_1q_commutation.py
  qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py
  qiskit/transpiler/passes/optimization/optimize_1q_gates.py
  qiskit/transpiler/passes/scheduling/base_scheduler.py
  qiskit/transpiler/passes/scheduling/dynamical_decoupling.py
  qiskit/transpiler/passes/scheduling/padding/dynamical_decoupling.py
  qiskit/transpiler/passes/scheduling/scheduling/base_scheduler.py
  qiskit/transpiler/passes/scheduling/time_unit_conversion.py
  qiskit/transpiler/passes/utils/check_cx_direction.py
  qiskit/transpiler/preset_passmanagers/common.py
  qiskit/transpiler/preset_passmanagers/level0.py
  qiskit/transpiler/preset_passmanagers/level1.py
  qiskit/transpiler/preset_passmanagers/level2.py
  qiskit/transpiler/preset_passmanagers/level3.py
  releasenotes/notes/target-transpile-d029922a5dbc3a52.yaml
  test/python/transpiler/test_commutative_cancellation.py
  test/python/transpiler/test_dynamical_decoupling.py
  test/python/transpiler/test_optimize_1q_commutation.py
  test/python/transpiler/test_optimize_1q_gates.py
  test/python/transpiler/test_pulse_gate_pass.py
  test/python/transpiler/test_scheduling_padding_pass.py
  test/python/transpiler/test_unroller.py
  test/python/visualization/references/pass_manager_standard.dot
  test/python/visualization/references/pass_manager_style.dot
Labels: Changelog: New Feature, automerge, mod: transpiler

#9393 Bump MSRV to 1.61 and all rust dependencies to latest releases
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  README.md
  azure-pipelines.yml
  releasenotes/notes/bump-msrv-f6f2bd42b9636b5e.yaml
Labels: Changelog: API Change, automerge, Rust, dependencies

#9235 Update ECRGate documentation
  qiskit/circuit/library/standard_gates/ecr.py
Labels: documentation, stable backport potential, automerge, Changelog: None

#9349 Run QPY backwards compatibility tests in parallel
  .azure/test-linux.yml
  test/qpy_compat/process_version.sh
  test/qpy_compat/run_tests.sh
Labels: type: qa, stable backport potential, automerge, Changelog: None

#9391 Fix qpy for `MCX` gates
  qiskit/qpy/binary_io/circuits.py
  releasenotes/notes/fix-qpy-mcxgray-421cf8f673f24238.yaml
  test/python/circuit/test_circuit_load_from_qpy.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#9382 Improve the ``qiskit.algorithms`` docs: clearly show legacy vs. primitive algorithms
  qiskit/algorithms/__init__.py
  qiskit/algorithms/time_evolvers/__init__.py
  test/python/algorithms/time_evolvers/test_trotter_qrte.py
Labels: documentation, stable backport potential, automerge, Changelog: None

#9414 Relax ipywidgets (follow-up #9364)
  requirements-dev.txt
Labels: automerge, Changelog: None

#9416 Add missing test coverage for RZXCalibration builder with target
  qiskit/transpiler/passes/calibration/rzx_builder.py
  test/python/transpiler/test_calibrationbuilder.py
Labels: automerge, Changelog: None

#9434 Fix `PauliOp.adjoint()`
  qiskit/opflow/primitive_ops/pauli_op.py
  releasenotes/notes/fix-PauliOp-adjoint-a275876185df989f.yaml
  test/python/opflow/test_op_construction.py
Labels: stable backport potential, Changelog: Bugfix, automerge, mod: opflow, Community PR

#9441 Fix `SolovayKitaev` for roundoff errors in Qiskit gates
  qiskit/synthesis/discrete_basis/commutator_decompose.py
  qiskit/synthesis/discrete_basis/solovay_kitaev.py
  qiskit/transpiler/passes/synthesis/solovay_kitaev_synthesis.py
  test/python/transpiler/test_solovay_kitaev.py
Labels: stable backport potential, Changelog: Bugfix, automerge, Changelog: None

#9445 Add back qiskit.transpiler.passes.synthesis.graysynth module
  qiskit/transpiler/synthesis/__init__.py
  qiskit/transpiler/synthesis/graysynth.py
  test/python/synthesis/test_gray_synthesis.py
Labels: priority: high, stable backport potential, Changelog: None

#8420 Extended explanation from plot_state_paulivec API reference
  qiskit/visualization/state_visualization.py
Labels: documentation, stable backport potential, automerge, Changelog: None, Intern PR

#9223 Fix add_calibration bug
  qiskit/circuit/quantumcircuit.py
  qiskit/dagcircuit/dagcircuit.py
  releasenotes/notes/fix-dag-parameterized-calibration-f5c0a740fcdeb2ec.yaml
  test/python/transpiler/test_pulse_gate_pass.py
Labels: stable backport potential, Changelog: Bugfix, automerge, mod: transpiler

#9427 Fix find_z2_symmetries when resulting object is empty
  qiskit/quantum_info/analysis/z2_symmetries.py
  test/python/quantum_info/test_sparse_z2_symmetries.py
Labels: stable backport potential, automerge, mod: quantum info, Changelog: None, Community PR

#9460 Pin tox version in CI
  .azure/docs-linux.yml
Labels: type: qa, stable backport potential, automerge, Changelog: None

#9087 Improve transpiler documentation
  qiskit/transpiler/__init__.py
  qiskit/transpiler/passes/scheduling/scheduling/alap.py
  qiskit/transpiler/passes/scheduling/scheduling/asap.py
  qiskit/transpiler/preset_passmanagers/__init__.py
Labels: documentation, stable backport potential, automerge, Changelog: None

#9477 Add tweedledum to requirements-dev.txt
  requirements-dev.txt
Labels: type: qa, stable backport potential, automerge, Changelog: None

#9491 Fix performance of ``ReverseEstimatorGradient`` for partial gradients
  qiskit/algorithms/gradients/reverse_gradient/split_circuits.py
  releasenotes/notes/fix-partial-reverse-gradient-f35fb1f30ee15692.yaml
Labels: stable backport potential, performance, Changelog: Bugfix, automerge

#9487 Manage edge case of pickling instmap.
  qiskit/pulse/calibration_entries.py
  releasenotes/notes/fix-instmap-add-with-arguments-250de2a7960565dc.yaml
  test/python/pulse/test_instruction_schedule_map.py
Labels: stable backport potential, Changelog: Bugfix, automerge, mod: pulse

#9494 Fix bad deprecation of Register.name_format
  qiskit/circuit/register.py
  releasenotes/notes/fix-register-name-format-deprecation-61ad5b06d618bb29.yaml
  test/python/circuit/test_register.py
Labels: stable backport potential, Changelog: Bugfix, automerge

#9499 Prepare qiskit-terra 0.23.1
  Cargo.lock
  Cargo.toml
  docs/conf.py
  qiskit/VERSION.txt
  releasenotes/notes/fix-instmap-add-with-arguments-250de2a7960565dc.yaml
  releasenotes/notes/fix-partial-reverse-gradient-f35fb1f30ee15692.yaml
  releasenotes/notes/prepare-0.23.1-9fa7d954a6c0590e.yaml
  setup.py
Labels: automerge, Changelog: None
