Repository Qiskit/qiskit, pull requests merged in 2024-04, with the labels that each got.

#12103 Deprecate Python 3.8 support
  qiskit/__init__.py
  releasenotes/notes/deprecate-3.8-a9db071fa3c85b1a.yaml
Labels: type: qa, Changelog: Deprecation

#12115 Remove Hamamura-san from maintainer lists
  .github/CODEOWNERS
  qiskit_bot.yaml
Labels: type: qa, Changelog: None

#12122 Remove a few more references to Qiskit Terra
  qiskit/qasm3/__init__.py
  setup.py
Labels: stable backport potential, Changelog: None

#12090 improving transpiler layout docstrings
  qiskit/transpiler/layout.py
Labels: documentation, Changelog: None

#11902 pending deprecations from 0.21
  qiskit/transpiler/passes/scheduling/__init__.py
  qiskit/transpiler/passes/scheduling/alap.py
  qiskit/transpiler/passes/scheduling/alignments/align_measures.py
  qiskit/transpiler/passes/scheduling/asap.py
  qiskit/transpiler/passes/scheduling/dynamical_decoupling.py
  releasenotes/notes/removed_deprecated_0.21-741d08a01a7ed527.yaml
  test/python/transpiler/legacy_scheduling/test_instruction_alignments.py
  test/python/transpiler/legacy_scheduling/test_scheduling_pass.py
Labels: Changelog: Deprecation

#12131 Change Block to Bloc for consistency
  qiskit/primitives/__init__.py
Labels: documentation, stable backport potential, Changelog: None

#12121 Migrate to PyO3 0.21's Bounds API
  Cargo.lock
  Cargo.toml
  crates/accelerate/Cargo.toml
  crates/accelerate/src/convert_2q_block_matrix.rs
  crates/accelerate/src/dense_layout.rs
  crates/accelerate/src/edge_collections.rs
  crates/accelerate/src/error_map.rs
  crates/accelerate/src/euler_one_qubit_decomposer.rs
  crates/accelerate/src/lib.rs
  crates/accelerate/src/nlayout.rs
  crates/accelerate/src/optimize_1q_gates.rs
  crates/accelerate/src/pauli_exp_val.rs
  crates/accelerate/src/quantum_circuit/circuit_data.rs
  crates/accelerate/src/quantum_circuit/circuit_instruction.rs
  crates/accelerate/src/quantum_circuit/mod.rs
  crates/accelerate/src/quantum_circuit/py_ext.rs
  crates/accelerate/src/results/marginalization.rs
  crates/accelerate/src/results/mod.rs
  crates/accelerate/src/sabre_layout.rs
  crates/accelerate/src/sabre_swap/mod.rs
  crates/accelerate/src/sabre_swap/neighbor_table.rs
  crates/accelerate/src/sampled_exp_val.rs
  crates/accelerate/src/sparse_pauli_op.rs
  crates/accelerate/src/stochastic_swap.rs
  crates/accelerate/src/two_qubit_decompose.rs
  crates/accelerate/src/utils.rs
  crates/accelerate/src/vf2_layout.rs
  crates/qasm2/src/expr.rs
  crates/qasm2/src/lib.rs
  crates/qasm3/src/build.rs
  crates/qasm3/src/circuit.rs
  crates/qasm3/src/expr.rs
  crates/qasm3/src/lib.rs
Labels: Changelog: None, Rust

#12136 Fix `GenericBackendV2` duration tests
  qiskit/providers/fake_provider/generic_backend_v2.py
  test/python/providers/fake_provider/test_generic_backend_v2.py
Labels: stable backport potential, Changelog: None

#8761 Remove hardcoded styling in plot_histogram
  qiskit/visualization/counts_visualization.py
  releasenotes/notes/histogram-style-03807965c3cc2e8a.yaml
  test/visual/mpl/graph/references/histogram.png
  test/visual/mpl/graph/references/histogram_2_sets_with_rest.png
  test/visual/mpl/graph/references/histogram_color.png
  test/visual/mpl/graph/references/histogram_desc_value_sort.png
  test/visual/mpl/graph/references/histogram_hamming.png
  test/visual/mpl/graph/references/histogram_legend.png
  test/visual/mpl/graph/references/histogram_multiple_colors.png
  test/visual/mpl/graph/references/histogram_title.png
  test/visual/mpl/graph/references/histogram_value_sort.png
  test/visual/mpl/graph/references/histogram_with_rest.png
Labels: Changelog: None, mod: visualization

#12116 Creating a challenging backend to show the transpiler stochasticity
  qiskit/transpiler/__init__.py
Labels: documentation, stable backport potential, Changelog: None

#12139 Use math and cmath instead of numpy on scalars
  qiskit/circuit/_utils.py
  qiskit/circuit/library/arithmetic/integer_comparator.py
  qiskit/circuit/library/arithmetic/quadratic_form.py
  qiskit/circuit/library/data_preparation/state_preparation.py
  qiskit/circuit/library/generalized_gates/diagonal.py
  qiskit/circuit/library/generalized_gates/isometry.py
  qiskit/circuit/library/generalized_gates/rv.py
  qiskit/circuit/library/generalized_gates/unitary.py
  qiskit/circuit/library/hamiltonian_gate.py
  qiskit/circuit/library/standard_gates/multi_control_rotation_gates.py
  qiskit/circuit/library/standard_gates/u.py
  qiskit/primitives/backend_estimator_v2.py
  qiskit/providers/basic_provider/basic_simulator.py
  qiskit/quantum_info/analysis/distance.py
  qiskit/quantum_info/analysis/make_observable.py
  qiskit/quantum_info/analysis/z2_symmetries.py
  qiskit/quantum_info/operators/channel/chi.py
  qiskit/quantum_info/operators/channel/choi.py
  qiskit/quantum_info/operators/channel/kraus.py
  qiskit/quantum_info/operators/channel/ptm.py
  qiskit/quantum_info/operators/channel/quantum_channel.py
  qiskit/quantum_info/operators/channel/stinespring.py
  qiskit/quantum_info/operators/channel/superop.py
  qiskit/quantum_info/operators/channel/transformations.py
  qiskit/quantum_info/operators/symplectic/clifford.py
  qiskit/quantum_info/operators/symplectic/random.py
  qiskit/quantum_info/states/statevector.py
  qiskit/quantum_info/states/utils.py
  qiskit/result/mitigation/correlated_readout_mitigator.py
  qiskit/result/mitigation/local_readout_mitigator.py
  qiskit/result/mitigation/utils.py
  qiskit/synthesis/discrete_basis/commutator_decompose.py
  qiskit/synthesis/evolution/qdrift.py
  qiskit/synthesis/two_qubit/xx_decompose/circuits.py
  qiskit/synthesis/unitary/aqc/__init__.py
  qiskit/synthesis/unitary/aqc/cnot_structures.py
  qiskit/synthesis/unitary/aqc/fast_gradient/fast_gradient.py
  qiskit/synthesis/unitary/qsd.py
  qiskit/transpiler/passes/calibration/rzx_builder.py
  qiskit/transpiler/passes/synthesis/aqc_plugin.py
  qiskit/visualization/bloch.py
  qiskit/visualization/state_visualization.py
Labels: Changelog: None

#11855 Remove historical versions from release notes
  docs/release_notes.rst
Labels: documentation, stable backport potential, Changelog: None

#11904 Write module-level `qiskit.circuit` documentation
  qiskit/circuit/__init__.py
  qiskit/circuit/_classical_resource_map.py
  qiskit/circuit/annotated_operation.py
  qiskit/circuit/barrier.py
  qiskit/circuit/bit.py
  qiskit/circuit/classical/__init__.py
  qiskit/circuit/classical/expr/__init__.py
  qiskit/circuit/controlflow/break_loop.py
  qiskit/circuit/controlflow/builder.py
  qiskit/circuit/controlflow/continue_loop.py
  qiskit/circuit/controlflow/control_flow.py
  qiskit/circuit/controlflow/for_loop.py
  qiskit/circuit/controlflow/if_else.py
  qiskit/circuit/controlflow/switch_case.py
  qiskit/circuit/controlflow/while_loop.py
  qiskit/circuit/controlledgate.py
  qiskit/circuit/delay.py
  qiskit/circuit/instruction.py
  qiskit/circuit/instructionset.py
  qiskit/circuit/library/__init__.py
  qiskit/circuit/measure.py
  qiskit/circuit/operation.py
  qiskit/circuit/parameter.py
  qiskit/circuit/quantumcircuit.py
  qiskit/circuit/reset.py
  qiskit/circuit/store.py
Labels: documentation, Changelog: None, mod: circuit

#12025 Warning for the installation instruction on README
  README.md
Labels: Changelog: None

#11851 Use `sphinx.ext.linkcode` for more precise source code links
  .github/workflows/docs_deploy.yml
  docs/conf.py
  tox.ini
Labels: documentation, stable backport potential, Changelog: None, Community PR

#12148 Add asv benchmarks for "utility scale" compilation
  test/benchmarks/qasm/qaoa_barabasi_albert_N100_3reps.qasm
  test/benchmarks/qasm/qft_N100.qasm
  test/benchmarks/qasm/square_heisenberg_N100.qasm
  test/benchmarks/utility_scale.py
  tools/build_pgo.sh
  tools/pgo_scripts/test_utility_scale.py
Labels: type: qa, Changelog: None

#12153 Fix bad release-notes section
  releasenotes/notes/1.0/add-annotated-arg-to-control-d9a188fe66f037ad.yaml
Labels: type: qa, stable backport potential, Changelog: None

#12098 Add `copy` keyword argument to `QuantumCircuit.append`
  qiskit/circuit/library/blueprintcircuit.py
  qiskit/circuit/library/phase_oracle.py
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/quantumcircuit-append-copy-8a9b71ad4b789490.yaml
  test/python/circuit/test_compose.py
  test/python/circuit/test_parameters.py
Labels: performance, Changelog: New Feature, Changelog: Bugfix, mod: circuit

#12097 Improve performance and randomness of `QuantumVolume`
  qiskit/circuit/library/generalized_gates/unitary.py
  qiskit/circuit/library/quantum_volume.py
  releasenotes/notes/qv-perf-be76290f472e4777.yaml
  test/python/circuit/library/test_quantum_volume.py
Labels: performance, Changelog: New Feature, Changelog: API Change, mod: circuit

#12024 Add "extended support" as a badge
  README.md
Labels: documentation, Changelog: None

#12151 Reduce number of decomposers used during UnitarySynthesis default plugin
  qiskit/transpiler/passes/synthesis/unitary_synthesis.py
Labels: performance, Changelog: None

#12162 Fix bad indentation and missing hyphen on `vqd.py`
  qiskit/algorithms/eigensolvers/vqd.py
Labels: Community PR

#12164 Remove pointless statement exclusion in tests
  test/python/circuit/library/test_state_preparation.py
  test/python/circuit/test_circuit_properties.py
  test/python/pulse/test_pulse_lib.py
Labels: Changelog: None, Community PR

#12168 Fix last bad indentation on `vqd.py`
  qiskit/algorithms/eigensolvers/vqd.py
Labels: Community PR

#12159 warning users about `qiskit-terra` support
  README.md
Labels: documentation, Changelog: None

#12066 Add `.apply_layout()`method to `Pauli` class
  qiskit/quantum_info/operators/symplectic/pauli.py
  releasenotes/notes/pauli-apply-layout-cdcbc1bce724a150.yaml
  test/python/quantum_info/operators/symplectic/test_pauli.py
Labels: priority: high, Changelog: New Feature, mod: quantum info

#11977 Refactor Sabre to an explicitly stateful router
  crates/accelerate/src/lib.rs
  crates/accelerate/src/sabre/layer.rs
  crates/accelerate/src/sabre/layout.rs
  crates/accelerate/src/sabre/mod.rs
  crates/accelerate/src/sabre/neighbor_table.rs
  crates/accelerate/src/sabre/route.rs
  crates/accelerate/src/sabre/sabre_dag.rs
  crates/accelerate/src/sabre/swap_map.rs
  crates/accelerate/src/sabre_swap/mod.rs
  qiskit/__init__.py
  qiskit/transpiler/passes/layout/sabre_layout.py
  qiskit/transpiler/passes/routing/sabre_swap.py
Labels: Changelog: None, Rust, mod: transpiler

#11666 Fix handling of `Var` nodes in full-rebuild control-flow blocks
  qiskit/circuit/controlflow/_builder_utils.py
  test/python/circuit/test_control_flow_builders.py
Labels: Changelog: None, mod: circuit

#12172 Fix RNG-compatibility of Sabre for large sizes
  crates/accelerate/src/sabre/route.rs
Labels: Changelog: None, Rust, mod: transpiler

#12170 Default `init` plugin was not properly raising when called with an invalid optimization level
  qiskit/transpiler/preset_passmanagers/builtin_plugins.py
  releasenotes/notes/followup_11468-61c6181e62531796.yaml
  test/python/transpiler/test_stage_plugin.py
Labels: stable backport potential, Changelog: Bugfix, affects extended support

#12180 Fixes "phsyical" Typos
  qiskit/transpiler/passes/basis/unroll_3q_or_more.py
  qiskit/transpiler/passes/layout/apply_layout.py
Labels: Changelog: None, Community PR

#12184 Bump faer to latest 0.18.x release
  Cargo.lock
  crates/accelerate/Cargo.toml
  crates/accelerate/src/two_qubit_decompose.rs
  crates/accelerate/src/utils.rs
Labels: Changelog: None, Rust, dependencies

#12188 `empty` is deprecated in PyO3 0.21 in favor of `empty_bound`
  crates/accelerate/src/quantum_circuit/circuit_data.rs
Labels: Changelog: None, Rust

#11705 Add DAGDependencyV2 and Converters
  qiskit/converters/circuit_to_dagdependency_v2.py
  qiskit/converters/dag_to_dagdependency_v2.py
  qiskit/dagcircuit/dagdependency_v2.py
  qiskit/visualization/dag_visualization.py
  test/python/converters/test_circuit_to_dagdependency_v2.py
  test/python/converters/test_dag_to_dagdependency_v2.py
  test/python/dagcircuit/test_dagdependency_v2.py
Labels: Changelog: None

#12199 Updates for removing use-maxsplit-arg
  pyproject.toml
  test/python/visualization/test_circuit_drawer.py
Labels: type: qa, Changelog: None, Community PR

#12198 Updates for removing non-ascii-name
  pyproject.toml
  test/python/transpiler/test_optimize_1q_decomposition.py
Labels: type: qa, Changelog: None, Community PR

#12190 Add build requirements to `requirements-dev.txt`
  requirements-dev.txt
  tox.ini
Labels: type: qa, Changelog: None

#12095 Support ECR gates in `Pauli.evolve(QuantumCircuit)`
  qiskit/quantum_info/operators/symplectic/base_pauli.py
  releasenotes/notes/fix-pauli-evolve-ecr-and-name-bugs.yaml
  test/python/quantum_info/operators/symplectic/test_pauli.py
  test/python/quantum_info/operators/symplectic/test_pauli_list.py
Labels: Changelog: Bugfix, mod: quantum info

#12214 Document generate_preset_pass_manager supports list for initial_layout
  qiskit/transpiler/preset_passmanagers/__init__.py
  test/python/transpiler/test_preset_passmanagers.py
Labels: documentation, Changelog: None, mod: transpiler

#12216 Fix mistaken QPY custom-instructions documentation
  qiskit/qpy/__init__.py
Labels: documentation, stable backport potential, Changelog: None

#12217 Removing lint rules that are unused
  pyproject.toml
Labels: type: qa, Changelog: None, Community PR

#12285 Removing unnecessary-list-index-lookup from lint exclusions and updates
  pyproject.toml
  qiskit/transpiler/passes/routing/stochastic_swap.py
  test/python/compiler/test_transpiler.py
Labels: Community PR

#12176 Avoid intermediate DAGs in Optimize1qGatesDecomposition
  qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py
Labels: performance, Changelog: None

#12107 Expose plugin options
  qiskit/synthesis/linear/cnot_synth.py
  qiskit/synthesis/linear/linear_circuits_utils.py
  qiskit/transpiler/passes/synthesis/high_level_synthesis.py
  releasenotes/notes/add-linear-plugin-options-b8a0ffe70dfe1676.yaml
  test/python/transpiler/test_high_level_synthesis.py
Labels: Changelog: New Feature

#12129 Add mapping-like features to data_bin
  qiskit/primitives/containers/data_bin.py
  releasenotes/notes/databin-mapping-45d24d71f9bb4eda.yaml
  test/python/primitives/containers/test_data_bin.py
Labels: Changelog: New Feature, mod: primitives

#12149 Increase heuristic effort for optimization level 2
  qiskit/transpiler/preset_passmanagers/builtin_plugins.py
  qiskit/transpiler/preset_passmanagers/common.py
  releasenotes/notes/optimization-level2-2c8c1488173aed31.yaml
  test/python/compiler/test_transpiler.py
Labels: Changelog: API Change

#11997 Remove already "removed" `FakeBackendV2`
  qiskit/providers/fake_provider/fake_backend.py
Labels: Changelog: None

#12145 Deprecating Provider ABC, as abstraction is not very useful
  qiskit/providers/__init__.py
  qiskit/providers/backend.py
  qiskit/providers/fake_provider/generic_backend_v2.py
  qiskit/providers/provider.py
  releasenotes/notes/deprecate_providerV1-ba17d7b4639d1cc5.yaml
  test/python/primitives/test_backend_sampler.py
  test/python/providers/basic_provider/test_basic_provider_backends.py
  test/python/providers/basic_provider/test_multi_registers_convention.py
  test/python/transpiler/test_sabre_swap.py
  test/utils/base.py
Labels: Changelog: Deprecation

#12099 Add fast-path construction to `NLocal`
  qiskit/circuit/library/n_local/n_local.py
  releasenotes/notes/nlocal-perf-3b8ebd9be1b2f4b3.yaml
Labels: performance, Changelog: New Feature, mod: circuit

#12294 Removing modified-iterating-list from lint exclusions and updates
  pyproject.toml
  qiskit/transpiler/passes/optimization/template_matching/forward_match.py
Labels: type: qa, Changelog: None, Community PR

#11756 Treat Reset like Measure in ConstrainedReschedule
  qiskit/transpiler/passes/scheduling/alignments/reschedule.py
  qiskit/transpiler/passes/scheduling/base_scheduler.py
  releasenotes/notes/add-scheduler-warnings-da6968a39fd8e6e7.yaml
Labels: Changelog: Bugfix

#12296 Adding note for nested-min-max for linting
  pyproject.toml
Labels: type: qa, Changelog: None, Community PR

#12109 Add support for returning a DAGCircuit to TwoQubitBasisDecomposer
  qiskit/synthesis/two_qubit/two_qubit_decompose.py
  qiskit/synthesis/two_qubit/xx_decompose/decomposer.py
  qiskit/transpiler/passes/synthesis/unitary_synthesis.py
  releasenotes/notes/add-use-dag-flag-two-qubit-basis-decomposer-024a9ced9833289c.yaml
  test/python/synthesis/test_synthesis.py
Labels: type: feature request, performance, synthesis

#11999 Finalise support for Numpy 2.0
  qiskit/__init__.py
  qiskit/_numpy_compat.py
  qiskit/circuit/__init__.py
  qiskit/circuit/_utils.py
  qiskit/circuit/delay.py
  qiskit/circuit/library/generalized_gates/pauli.py
  qiskit/circuit/library/generalized_gates/permutation.py
  qiskit/circuit/library/generalized_gates/unitary.py
  qiskit/circuit/library/hamiltonian_gate.py
  qiskit/circuit/library/standard_gates/global_phase.py
  qiskit/circuit/library/standard_gates/p.py
  qiskit/circuit/library/standard_gates/r.py
  qiskit/circuit/library/standard_gates/rx.py
  qiskit/circuit/library/standard_gates/rxx.py
  qiskit/circuit/library/standard_gates/ry.py
  qiskit/circuit/library/standard_gates/ryy.py
  qiskit/circuit/library/standard_gates/rz.py
  qiskit/circuit/library/standard_gates/rzx.py
  qiskit/circuit/library/standard_gates/rzz.py
  qiskit/circuit/library/standard_gates/u.py
  qiskit/circuit/library/standard_gates/u1.py
  qiskit/circuit/library/standard_gates/u2.py
  qiskit/circuit/library/standard_gates/u3.py
  qiskit/circuit/library/standard_gates/xx_minus_yy.py
  qiskit/circuit/library/standard_gates/xx_plus_yy.py
  qiskit/primitives/backend_sampler_v2.py
  qiskit/primitives/containers/observables_array.py
  qiskit/primitives/containers/shape.py
  qiskit/quantum_info/operators/channel/chi.py
  qiskit/quantum_info/operators/channel/choi.py
  qiskit/quantum_info/operators/channel/ptm.py
  qiskit/quantum_info/operators/channel/superop.py
  qiskit/quantum_info/operators/dihedral/dihedral.py
  qiskit/quantum_info/operators/operator.py
  qiskit/quantum_info/operators/scalar_op.py
  qiskit/quantum_info/operators/symplectic/clifford.py
  qiskit/quantum_info/operators/symplectic/pauli.py
  qiskit/quantum_info/operators/symplectic/pauli_list.py
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
  qiskit/quantum_info/states/densitymatrix.py
  qiskit/quantum_info/states/statevector.py
  qiskit/visualization/array.py
  releasenotes/notes/numpy-2.0-2f3e35bd42c48518.yaml
  requirements.txt
  test/python/providers/test_backend_v2.py
  test/python/transpiler/test_dynamical_decoupling.py
Labels: Changelog: New Feature, dependencies

#12298 Fix pickling of `NLayout`
  crates/accelerate/src/nlayout.rs
  test/python/transpiler/test_layout.py
Labels: stable backport potential, Changelog: None

#12177 Extend Clifford class docs
  qiskit/quantum_info/operators/symplectic/clifford.py
Labels: documentation, Changelog: None

#12297 Removing use-dict-literal from lint exclusions and updates
  pyproject.toml
  qiskit/assembler/disassemble.py
  qiskit/compiler/assembler.py
  test/python/result/test_result.py
Labels: type: qa, Changelog: None, Community PR

#11388 Add Rust-based `SparsePauliOp.to_matrix` and Miri tests
  .github/workflows/miri.yml
  CONTRIBUTING.md
  crates/accelerate/src/lib.rs
  crates/accelerate/src/rayon_ext.rs
  crates/accelerate/src/sparse_pauli_op.rs
  crates/accelerate/src/test.rs
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
  releasenotes/notes/spo-to-matrix-26445a791e24f62a.yaml
  test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
Labels: type: qa, performance, Changelog: New Feature, mod: quantum info, Rust

#12303 Removing the superfluous-parens lint rule and updates
  pyproject.toml
  qiskit/quantum_info/operators/symplectic/random.py
  test/python/quantum_info/states/test_utils.py
Labels: Community PR

#12181 Add reverse permutation for LNN connectivity
  qiskit/synthesis/__init__.py
  qiskit/synthesis/linear_phase/cz_depth_lnn.py
  qiskit/synthesis/permutation/__init__.py
  qiskit/synthesis/permutation/permutation_reverse_lnn.py
  qiskit/synthesis/qft/qft_decompose_lnn.py
  releasenotes/notes/reverse-permutation-lnn-409a07c7f6d0eed9.yaml
  test/python/synthesis/test_permutation_synthesis.py
Labels: Changelog: New Feature, synthesis

#12183 Rework handling of instruction durations in preset pass managers
  qiskit/compiler/transpiler.py
  qiskit/transpiler/passes/scheduling/dynamical_decoupling.py
  qiskit/transpiler/passes/scheduling/padding/dynamical_decoupling.py
  qiskit/transpiler/passes/scheduling/time_unit_conversion.py
  releasenotes/notes/rework-inst-durations-passes-28c78401682e22c0.yaml
Labels: Changelog: Bugfix

#12088 Assignment of parameters in pulse `Schedule`/`ScheduleBlock` doable through parameter name
  qiskit/pulse/parameter_manager.py
  qiskit/pulse/schedule.py
  qiskit/pulse/utils.py
  releasenotes/notes/parameter_assignment_by_name_for_pulse_schedules-3a27bbbbf235fb9e.yaml
  test/python/pulse/test_parameter_manager.py
Labels: mod: pulse, Community PR

#12201 Have `QuantumCircuit.store` do integer-literal type promotion
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_circuit_vars.py
  test/python/circuit/test_store.py
Labels: Changelog: None, mod: circuit

#12186 Extend the basis gates of BasicSimulator
  qiskit/circuit/library/standard_gates/x.py
  qiskit/providers/basic_provider/basic_provider_tools.py
  qiskit/providers/basic_provider/basic_simulator.py
  releasenotes/notes/fixes_10852-e197344c5f44b4f1.yaml
  test/python/providers/basic_provider/test_standard_library.py
  test/python/transpiler/test_passmanager_config.py
Labels: Changelog: New Feature

#11651 Support standalone `expr.Var` in QPY
  qiskit/qpy/__init__.py
  qiskit/qpy/binary_io/circuits.py
  qiskit/qpy/binary_io/value.py
  qiskit/qpy/common.py
  qiskit/qpy/exceptions.py
  qiskit/qpy/formats.py
  qiskit/qpy/type_keys.py
  test/python/circuit/test_circuit_load_from_qpy.py
  test/qpy_compat/test_qpy.py
Labels: Changelog: New Feature, mod: qpy

#12179 Avoid intermediate DAGCircuit construction in 2q synthesis
  qiskit/transpiler/passes/synthesis/unitary_synthesis.py
Labels: performance, Changelog: None

#12309 Fix a type hint of an private method `BackendSamplerV2._run` (follow-up #12291)
  qiskit/primitives/backend_sampler_v2.py
  test/python/primitives/test_backend_estimator_v2.py
  test/python/primitives/test_backend_sampler_v2.py
  test/python/primitives/test_statevector_estimator.py
  test/python/primitives/test_statevector_sampler.py
Labels: documentation, Changelog: None, mod: primitives

#12102 Promote arm64 macOS to tier 1
  .github/workflows/tests.yml
  .github/workflows/wheels.yml
  pyproject.toml
  releasenotes/notes/macos-arm64-tier-1-c5030f009be6adcb.yaml
  tools/build_pgo.sh
Labels: type: qa, Changelog: New Feature
