Repository Qiskit/qiskit, pull requests merged in 2024-06, with the labels that each got.

#12485 Update operation.py docs
  qiskit/circuit/operation.py
Labels: Community PR

#12496 Add __pos__ for Parameter
  qiskit/circuit/parameterexpression.py
  releasenotes/notes/unary_pos_for_parameterexpression-6421421b6dc20fbb.yaml
  test/python/circuit/test_parameters.py
Labels: Changelog: New Feature, Community PR, mod: circuit

#12495 Implement `num_qubits` and `num_clbits` in Rust
  crates/circuit/src/circuit_data.rs
  qiskit/circuit/quantumcircuit.py
Labels: performance, Changelog: None, Rust

#12512 Fix version table in qpy docs
  qiskit/qpy/__init__.py
Labels: documentation, stable backport potential, Changelog: None

#12119 Implement `__array__` for `qasm2._DefinedGate`
  qiskit/qasm2/parse.py
  releasenotes/notes/qasm2-to-matrix-c707fe1e61b3987f.yaml
  test/python/qasm2/test_structure.py
Labels: stable backport potential, Changelog: Bugfix, mod: qasm2

#12522 Removed deprecated isometry bench test
  test/benchmarks/isometry.py
Labels: Community PR

#12513 fixing deprecated methods and incorrect dag state
  test/benchmarks/mapping_passes.py
Labels: type: qa, Changelog: None, Intern PR

#12372 [DAGCircuit Oxidation] Refactor bit management in `CircuitData`
  crates/circuit/src/bit_data.rs
  crates/circuit/src/circuit_data.rs
  crates/circuit/src/circuit_instruction.rs
  crates/circuit/src/intern_context.rs
  crates/circuit/src/interner.rs
  crates/circuit/src/lib.rs
  crates/circuit/src/packed_instruction.rs
Labels: Changelog: None, Rust

#12520 Bump pylint to 3.2.2
  pyproject.toml
  qiskit/transpiler/passmanager.py
  qiskit/visualization/circuit/text.py
  requirements-dev.txt
Labels: type: qa, Changelog: None

#12514 Stop using deprecated U3 gate in random hex benchmarks
  test/benchmarks/random_circuit_hex.py
Labels: type: qa, Changelog: None, Intern PR

#12526 Avoid exception in `Target.has_calibration` for instruction without properties
  qiskit/transpiler/target.py
  releasenotes/notes/target-has-calibration-no-properties-f3be18f2d58f330a.yaml
  test/python/transpiler/test_target.py
Labels: stable backport potential, Changelog: Bugfix

#12429 Fix `QuantumCircuit.depth` with zero-operands and `Expr` nodes
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/fix-qc-depth-0q-cdcc9aa14e237e68.yaml
  test/python/circuit/test_circuit_properties.py
Labels: stable backport potential, Changelog: Bugfix, mod: circuit

#12483 [unitaryHACK] Controlling the Insertion of Multi-Qubit Gates in the Generation of Random Circuits #12059
  qiskit/circuit/random/utils.py
  releasenotes/notes/extended-random-circuits-049b67cce39003f4.yaml
  test/python/circuit/test_random_circuit.py
Labels: unitaryhack-bounty, Community PR

#11585 Fix bugs with VF2Layout pass and Qiskit Aer 0.13
  qiskit/transpiler/passes/layout/vf2_layout.py
  qiskit/transpiler/passes/layout/vf2_utils.py
  releasenotes/notes/fix-vf2-aer-a7306ce07ea81700.yaml
  test/python/transpiler/test_vf2_layout.py
Labels: stable backport potential, Changelog: Bugfix, affects extended support

#12533 Fix broken BasisTranslator translation error link
  qiskit/transpiler/passes/basis/basis_translator.py
Labels: documentation, Changelog: None, Community PR

#12530 Improve public type annotations for `OneQubitEulerDecomposer`
  qiskit/synthesis/one_qubit/one_qubit_decompose.py
Labels: Changelog: None

#12327 Move utility functions _inverse_pattern and _get_ordered_swap to Rust
  crates/accelerate/src/lib.rs
  crates/accelerate/src/permutation.rs
  crates/pyext/src/lib.rs
  qiskit/__init__.py
  qiskit/synthesis/permutation/permutation_utils.py
  test/python/synthesis/test_permutation_synthesis.py
Labels: performance, synthesis, Rust, Community PR

#12535 Fix annotation
  qiskit/providers/providerutils.py
Labels: Changelog: None, Community PR

#12315 Moving group of lint rules
  pyproject.toml
  qiskit/primitives/backend_estimator.py
  qiskit/primitives/backend_sampler.py
  qiskit/providers/options.py
  qiskit/transpiler/basepasses.py
  qiskit/transpiler/passmanager.py
  test/python/circuit/test_unitary.py
  test/python/compiler/test_transpiler.py
Labels: Community PR

#12286 Removing consider-using-enumerate from lint exclusions and updates
  pyproject.toml
  qiskit/circuit/library/arithmetic/piecewise_polynomial_pauli_rotations.py
  qiskit/synthesis/stabilizer/stabilizer_circuit.py
  qiskit/transpiler/passes/optimization/inverse_cancellation.py
  qiskit/transpiler/passes/optimization/template_matching/forward_match.py
  qiskit/transpiler/passmanager.py
  qiskit/visualization/bloch.py
  test/python/synthesis/test_synthesis.py
Labels: Community PR

#12488 Use hash of numeric value for bound parameter expressions
  qiskit/circuit/parameterexpression.py
  releasenotes/notes/parameterexpression-hash-d2593ab1715aa42c.yaml
  test/python/circuit/test_parameters.py
Labels: stable backport potential, Changelog: Bugfix, mod: circuit

#12553 small doc improvements
  qiskit/dagcircuit/dagcircuit.py
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
  qiskit/transpiler/preset_passmanagers/__init__.py
Labels: documentation, Changelog: None

#12561 Do not retain and expose old elements of `ParameterVector`
  qiskit/circuit/parametervector.py
  qiskit/qpy/binary_io/value.py
  test/python/circuit/test_parameters.py
Labels: stable backport potential, Changelog: None, mod: circuit

#12542 Fix the possibly-used-before-assignment in pylint
  pyproject.toml
  qiskit/primitives/backend_estimator.py
  qiskit/pulse/macros.py
  qiskit/qpy/binary_io/circuits.py
  qiskit/quantum_info/operators/operator.py
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
  qiskit/transpiler/passes/basis/unroll_custom_definitions.py
  qiskit/transpiler/passes/optimization/commutative_cancellation.py
  qiskit/visualization/circuit/matplotlib.py
  test/benchmarks/randomized_benchmarking.py
  test/benchmarks/utils.py
  test/python/circuit/test_parameters.py
  test/python/classical_function_compiler/test_boolean_expression.py
  test/python/classical_function_compiler/test_classical_function.py
  test/python/classical_function_compiler/test_parse.py
  test/python/classical_function_compiler/test_simulate.py
  test/python/classical_function_compiler/test_synthesis.py
  test/python/classical_function_compiler/test_tweedledum2qiskit.py
  test/python/classical_function_compiler/test_typecheck.py
  test/python/visualization/test_circuit_drawer.py
  test/python/visualization/test_circuit_text_drawer.py
  test/python/visualization/test_gate_map.py
  test/python/visualization/test_plot_histogram.py
  tools/build_standard_commutations.py
Labels: type: qa, Changelog: None

#12459 Add infrastructure for gates, instruction, and operations in Rust
  .github/workflows/tests.yml
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  crates/accelerate/Cargo.toml
  crates/accelerate/src/isometry.rs
  crates/accelerate/src/two_qubit_decompose.rs
  crates/circuit/Cargo.toml
  crates/circuit/README.md
  crates/circuit/src/bit_data.rs
  crates/circuit/src/circuit_data.rs
  crates/circuit/src/circuit_instruction.rs
  crates/circuit/src/dag_node.rs
  crates/circuit/src/gate_matrix.rs
  crates/circuit/src/imports.rs
  crates/circuit/src/interner.rs
  crates/circuit/src/lib.rs
  crates/circuit/src/operations.rs
  crates/circuit/src/packed_instruction.rs
  crates/circuit/src/parameter_table.rs
  crates/pyext/Cargo.toml
  qiskit/circuit/controlflow/builder.py
  qiskit/circuit/instruction.py
  qiskit/circuit/instructionset.py
  qiskit/circuit/library/blueprintcircuit.py
  qiskit/circuit/library/standard_gates/ecr.py
  qiskit/circuit/library/standard_gates/global_phase.py
  qiskit/circuit/library/standard_gates/h.py
  qiskit/circuit/library/standard_gates/i.py
  qiskit/circuit/library/standard_gates/p.py
  qiskit/circuit/library/standard_gates/rx.py
  qiskit/circuit/library/standard_gates/ry.py
  qiskit/circuit/library/standard_gates/rz.py
  qiskit/circuit/library/standard_gates/swap.py
  qiskit/circuit/library/standard_gates/sx.py
  qiskit/circuit/library/standard_gates/u.py
  qiskit/circuit/library/standard_gates/x.py
  qiskit/circuit/library/standard_gates/y.py
  qiskit/circuit/library/standard_gates/z.py
  qiskit/circuit/parametertable.py
  qiskit/circuit/quantumcircuit.py
  qiskit/circuit/quantumcircuitdata.py
  qiskit/converters/circuit_to_instruction.py
  qiskit/qasm3/exporter.py
  qiskit/quantum_info/operators/dihedral/dihedral.py
  qiskit/transpiler/passes/scheduling/padding/dynamical_decoupling.py
  qiskit/transpiler/passes/scheduling/scheduling/base_scheduler.py
  qiskit/transpiler/passes/scheduling/time_unit_conversion.py
  releasenotes/notes/circuit-gates-rust-5c6ab6c58f7fd2c9.yaml
  requirements-optional.txt
  setup.py
  test/python/circuit/library/test_blueprintcircuit.py
  test/python/circuit/test_circuit_data.py
  test/python/circuit/test_circuit_operations.py
  test/python/circuit/test_compose.py
  test/python/circuit/test_instructions.py
  test/python/circuit/test_isometry.py
  test/python/circuit/test_parameters.py
  test/python/circuit/test_rust_equivalence.py
  test/python/qasm3/test_export.py
Labels: priority: high, performance, Changelog: New Feature, Changelog: API Change, Rust, mod: circuit

#12571 Bump version of macOS used on Azure
  .azure/test-macos.yml
Labels: type: qa, stable backport potential, Changelog: None

#12515 += depreciated changed to &=
  qiskit/circuit/library/n_local/two_local.py
  test/benchmarks/utils.py
Labels: type: qa, Changelog: None, Intern PR

#12587 Remove extra parenthesis in Primitive examples
  qiskit/primitives/__init__.py
Labels: documentation, Changelog: None

#12524 Fixed incorrect behavior of scheduling benchmarks
  test/benchmarks/scheduling_passes.py
Labels: Intern PR

#12596 Remove Eric from Rust bot notifications
  qiskit_bot.yaml
Labels: type: qa, Changelog: None

#12189 [0.46] Finalise support for Numpy 2.0
  qiskit/__init__.py
  qiskit/_numpy_compat.py
  qiskit/circuit/__init__.py
  qiskit/circuit/_utils.py
  qiskit/circuit/delay.py
  qiskit/circuit/library/generalized_gates/pauli.py
  qiskit/circuit/library/generalized_gates/permutation.py
  qiskit/circuit/library/generalized_gates/unitary.py
  qiskit/circuit/library/hamiltonian_gate.py
  qiskit/circuit/library/standard_gates/global_phase.py
  qiskit/circuit/library/standard_gates/p.py
  qiskit/circuit/library/standard_gates/r.py
  qiskit/circuit/library/standard_gates/rx.py
  qiskit/circuit/library/standard_gates/rxx.py
  qiskit/circuit/library/standard_gates/ry.py
  qiskit/circuit/library/standard_gates/ryy.py
  qiskit/circuit/library/standard_gates/rz.py
  qiskit/circuit/library/standard_gates/rzx.py
  qiskit/circuit/library/standard_gates/rzz.py
  qiskit/circuit/library/standard_gates/u.py
  qiskit/circuit/library/standard_gates/u1.py
  qiskit/circuit/library/standard_gates/u2.py
  qiskit/circuit/library/standard_gates/u3.py
  qiskit/circuit/library/standard_gates/xx_minus_yy.py
  qiskit/circuit/library/standard_gates/xx_plus_yy.py
  qiskit/quantum_info/operators/channel/chi.py
  qiskit/quantum_info/operators/channel/choi.py
  qiskit/quantum_info/operators/channel/ptm.py
  qiskit/quantum_info/operators/channel/superop.py
  qiskit/quantum_info/operators/dihedral/dihedral.py
  qiskit/quantum_info/operators/operator.py
  qiskit/quantum_info/operators/scalar_op.py
  qiskit/quantum_info/operators/symplectic/clifford.py
  qiskit/quantum_info/operators/symplectic/pauli.py
  qiskit/quantum_info/operators/symplectic/pauli_list.py
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
  qiskit/quantum_info/states/densitymatrix.py
  qiskit/quantum_info/states/statevector.py
  qiskit/visualization/array.py
  releasenotes/notes/numpy-2.0-2f3e35bd42c48518.yaml
  requirements.txt
  test/python/transpiler/test_dynamical_decoupling.py
Labels: Changelog: New Feature, dependencies

#12598 Add rust representation for SGates, TGates, and iSwap gate
  crates/circuit/src/gate_matrix.rs
  crates/circuit/src/imports.rs
  crates/circuit/src/operations.rs
  qiskit/circuit/library/standard_gates/iswap.py
  qiskit/circuit/library/standard_gates/s.py
  qiskit/circuit/library/standard_gates/sx.py
  qiskit/circuit/library/standard_gates/t.py
  qiskit/circuit/quantumcircuit.py
  test/python/circuit/test_rust_equivalence.py
Labels: performance, Changelog: None, Rust

#12609 Fix `TwoLocal` example: use compose instead of +
  qiskit/circuit/library/n_local/two_local.py
Labels: documentation, stable backport potential, Changelog: None

#12608 Fix v2 pulse drawer
  qiskit/visualization/pulse_v2/device_info.py
  releasenotes/notes/fix-v2-pulse-drawer-d05e4e392766909f.yaml
Labels: stable backport potential, Changelog: Bugfix

#12610 Prepare 1.1.1
  Cargo.lock
  Cargo.toml
  docs/conf.py
  qiskit/VERSION.txt
  releasenotes/notes/prepare-1.1.1-0b1163e5df275ba8.yaml
  releasenotes/notes/qasm2-to-matrix-c707fe1e61b3987f.yaml
Labels: Changelog: None

#12616 Prepare 0.46.2 release
  Cargo.lock
  Cargo.toml
  constraints.txt
  docs/conf.py
  qiskit/VERSION.txt
  qiskit_pkg/setup.py
  releasenotes/notes/prepare-0.46.2-cb6dd16bd95224be.yaml
  setup.py
Labels: Changelog: None

#12619 Invalidate `parameters` cache on circuit copy
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/fix-parameter-cache-05eac2f24477ccb8.yaml
  test/python/circuit/test_parameters.py
Labels: stable backport potential, Changelog: Bugfix, mod: circuit

#12594 Localise `py_op` caching data in `RefCell`
  crates/circuit/src/circuit_data.rs
  crates/circuit/src/circuit_instruction.rs
Labels: performance, Changelog: None, Rust

#12627 Fix type hint in SolovayKitaevDecomposition
  qiskit/synthesis/discrete_basis/solovay_kitaev.py
Labels: documentation, stable backport potential, Changelog: None, Community PR

#12597 Add remaining tests for `ParameterVector` and tweak its `repr`
  qiskit/circuit/parametervector.py
  test/python/circuit/test_parameters.py
Labels: type: qa, Changelog: None, mod: circuit

#12630 Fix `CircuitInstruction` legacy iterable typing
  crates/circuit/src/circuit_instruction.rs
  test/python/circuit/test_circuit_data.py
Labels: Changelog: None, Rust, mod: circuit

#12636 Missing backport for `generate_preset_pass_manager` docs
  qiskit/transpiler/preset_passmanagers/__init__.py
Labels: Community PR

#12606 Add Rust representation for `XXMinusYYGate` and `XXPlusYYGate`
  crates/circuit/src/gate_matrix.rs
  crates/circuit/src/imports.rs
  crates/circuit/src/operations.rs
  qiskit/circuit/library/standard_gates/xx_minus_yy.py
  qiskit/circuit/library/standard_gates/xx_plus_yy.py
Labels: performance, Changelog: None, Rust

#12605 Follow up on #12327: circuit construction in Rust
  crates/accelerate/src/lib.rs
  crates/accelerate/src/synthesis/mod.rs
  crates/accelerate/src/synthesis/permutation/mod.rs
  crates/accelerate/src/synthesis/permutation/utils.rs
  crates/pyext/src/lib.rs
  qiskit/__init__.py
  qiskit/circuit/library/generalized_gates/permutation.py
  qiskit/synthesis/permutation/permutation_full.py
  qiskit/synthesis/permutation/permutation_utils.py
  releasenotes/notes/oxidize-permbasic-be27578187ac472f.yaml
  test/python/synthesis/test_permutation_synthesis.py
Labels: performance, synthesis, Rust

#12572 Add rust representation for the u1, u2, and u3 gates
  crates/circuit/src/gate_matrix.rs
  crates/circuit/src/imports.rs
  crates/circuit/src/operations.rs
  qiskit/circuit/library/standard_gates/u1.py
  qiskit/circuit/library/standard_gates/u2.py
  qiskit/circuit/library/standard_gates/u3.py
  test/python/circuit/test_rust_equivalence.py
  test/python/qasm3/test_export.py
  test/python/transpiler/test_optimize_1q_gates.py
Labels: performance, Changelog: None, Rust

#12640 Deprecate tuple-like access to `CircuitInstruction`
  crates/circuit/src/circuit_instruction.rs
  crates/circuit/src/imports.rs
  releasenotes/notes/deprecate-legacy-circuit-instruction-8a332ab09de73766.yaml
  test/python/circuit/test_circuit_data.py
  test/utils/base.py
Labels: Changelog: Deprecation, mod: circuit

#12646 Add placeholders for all mising standard gates in Rust
  crates/circuit/src/imports.rs
  crates/circuit/src/operations.rs
Labels: Changelog: None, Rust

#12654 Pin scipy to 1.13.1 to bypass CI failures
  constraints.txt
Labels: type: qa, Changelog: None

#12579 Fix some bugs in loading Solovay Kitaev decompositions
  qiskit/synthesis/discrete_basis/generate_basis_approximations.py
  qiskit/synthesis/discrete_basis/solovay_kitaev.py
  releasenotes/notes/fix-sk-load-from-file-02c6eabbbd7fcda3.yaml
  test/python/transpiler/test_solovay_kitaev.py
Labels: stable backport potential, Changelog: Bugfix

#12653 GenericBackendV2 should fail when the backend cannot allocate the basis gate because its size
  qiskit/providers/fake_provider/generic_backend_v2.py
  releasenotes/notes/fixes_GenericBackendV2-668e40596e1f070d.yaml
  test/python/providers/fake_provider/test_generic_backend_v2.py
  test/visual/mpl/graph/test_graph_matplotlib_drawer.py
Labels: Changelog: Bugfix

#12661 Simplify QuantumCircuit._from_circuit_data bit handling
  qiskit/circuit/quantumcircuit.py
Labels: performance, Changelog: None, mod: circuit

#12663 adapting test/randomized/test_transpiler_equivalence.py to #12640
  test/randomized/test_transpiler_equivalence.py
Labels: type: qa, Changelog: None

#12623 Add test case to validate the rust->Python gate conversion
  test/python/circuit/test_rust_equivalence.py
Labels: type: qa, Changelog: None, mod: circuit

#12644 Add Rust representation for DCXGate
  crates/circuit/src/gate_matrix.rs
  crates/circuit/src/imports.rs
  crates/circuit/src/operations.rs
  qiskit/circuit/library/standard_gates/dcx.py
  qiskit/circuit/quantumcircuit.py
Labels: performance, Changelog: None, Rust, mod: circuit

#12662 Implement RGate in Rust
  crates/circuit/src/gate_matrix.rs
  crates/circuit/src/imports.rs
  crates/circuit/src/operations.rs
  qiskit/circuit/library/standard_gates/r.py
  qiskit/circuit/quantumcircuit.py
Labels: performance, Changelog: None, Rust, mod: circuit

#12651 Add some abbreviations for gates and linear algebra
  crates/accelerate/src/convert_2q_block_matrix.rs
  crates/accelerate/src/euler_one_qubit_decomposer.rs
  crates/accelerate/src/isometry.rs
  crates/accelerate/src/pauli_exp_val.rs
  crates/accelerate/src/sampled_exp_val.rs
  crates/accelerate/src/sparse_pauli_op.rs
  crates/accelerate/src/two_qubit_decompose.rs
  crates/accelerate/src/uc_gate.rs
  crates/circuit/src/gate_matrix.rs
  crates/circuit/src/lib.rs
  crates/circuit/src/operations.rs
  crates/circuit/src/util.rs
Labels: type: qa, Changelog: None, Rust

#12676 Suppress nonsense `DeprecationWarning` caused by `unittest`
  constraints.txt
  test/utils/base.py
Labels: type: qa, stable backport potential, Changelog: None

#12648 Port CRX/Y/Z gates to Rust
  crates/circuit/src/gate_matrix.rs
  crates/circuit/src/imports.rs
  crates/circuit/src/operations.rs
  qiskit/circuit/library/standard_gates/rx.py
  qiskit/circuit/library/standard_gates/ry.py
  qiskit/circuit/library/standard_gates/rz.py
  qiskit/circuit/quantumcircuit.py
Labels: performance, Changelog: None, Rust, mod: circuit

#12675 Fix clippy warnings on latest stable rust
  crates/accelerate/src/dense_layout.rs
  crates/accelerate/src/nlayout.rs
  crates/accelerate/src/stochastic_swap.rs
  crates/circuit/src/circuit_instruction.rs
Labels: type: qa, Changelog: None, Rust

#12690 Relax CI constraint on Rustworkx 0.15.0
  constraints.txt
Labels: type: qa, stable backport potential, Changelog: None

#12456 binary matrices utils in rust
  crates/accelerate/src/synthesis/linear/mod.rs
  crates/accelerate/src/synthesis/linear/utils.rs
  crates/accelerate/src/synthesis/mod.rs
  qiskit/__init__.py
  qiskit/quantum_info/operators/dihedral/random.py
  qiskit/synthesis/clifford/clifford_decompose_layers.py
  qiskit/synthesis/linear/__init__.py
  qiskit/synthesis/linear/linear_depth_lnn.py
  qiskit/synthesis/linear/linear_matrix_utils.py
  qiskit/synthesis/stabilizer/stabilizer_decompose.py
  qiskit/transpiler/passes/synthesis/high_level_synthesis.py
  releasenotes/notes/linear-binary-matrix-utils-rust-c48b5577749c34ab.yaml
  test/python/circuit/library/test_linear_function.py
  test/python/quantum_info/operators/symplectic/test_clifford.py
  test/python/synthesis/test_cx_cz_synthesis.py
  test/python/synthesis/test_linear_synthesis.py
  test/python/transpiler/test_high_level_synthesis.py
Labels: performance, synthesis, Rust
