Repository Qiskit/qiskit, pull requests merged in 2024-02, with the labels that each got.

#11694 Bump versions for Qiskit 0.45.3
  Cargo.lock
  Cargo.toml
  docs/conf.py
  qiskit/VERSION.txt
  qiskit_pkg/setup.py
  releasenotes/notes/qiskit-1.0-incompatibility-9ad22472837837d8.yaml
  setup.py
Labels: Changelog: None

#11696 Disable cron runs on old stable branch
  azure-pipelines.yml
Labels: type: qa, Changelog: None

#11417 Support stabilised syntax for OpenQASM 3 `switch`
  qiskit/qasm3/ast.py
  qiskit/qasm3/experimental.py
  qiskit/qasm3/exporter.py
  qiskit/qasm3/printer.py
  releasenotes/notes/qasm3-stable-switch-61a10036d1587778.yaml
  test/python/qasm3/test_export.py
Labels: Changelog: New Feature, mod: qasm3

#11695 Fix `approximation_degree` default in `generate_preset_pass_maanger`
  qiskit/transpiler/preset_passmanagers/__init__.py
  releasenotes/notes/preset-pass-manager-approximation-degree-503198b1974adf79.yaml
Labels: Changelog: API Change

#11689 fix typo
  qiskit/transpiler/passes/synthesis/plugin.py
Labels: documentation, Changelog: None

#11701 Update to `black~=24.1`
  qiskit/__init__.py
  qiskit/circuit/library/generalized_gates/isometry.py
  qiskit/circuit/library/generalized_gates/linear_function.py
  qiskit/circuit/library/generalized_gates/uc_pauli_rot.py
  qiskit/circuit/library/n_local/efficient_su2.py
  qiskit/circuit/library/n_local/n_local.py
  qiskit/circuit/library/n_local/two_local.py
  qiskit/circuit/quantumcircuit.py
  qiskit/primitives/backend_estimator.py
  qiskit/primitives/backend_sampler.py
  qiskit/primitives/containers/bindings_array.py
  qiskit/primitives/containers/observables_array.py
  qiskit/providers/models/backendproperties.py
  qiskit/pulse/instruction_schedule_map.py
  qiskit/qasm2/export.py
  qiskit/qasm3/ast.py
  qiskit/quantum_info/operators/symplectic/pauli.py
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
  qiskit/synthesis/two_qubit/xx_decompose/polytopes.py
  qiskit/synthesis/unitary/qsd.py
  qiskit/transpiler/passes/layout/sabre_pre_layout.py
  qiskit/transpiler/passes/layout/vf2_post_layout.py
  qiskit/transpiler/passes/optimization/commutation_analysis.py
  qiskit/transpiler/passes/optimization/template_matching/forward_match.py
  qiskit/transpiler/passes/routing/algorithms/types.py
  qiskit/transpiler/preset_passmanagers/builtin_plugins.py
  qiskit/utils/deprecation.py
  qiskit/utils/lazy_tester.py
  qiskit/visualization/state_visualization.py
  requirements-dev.txt
  test/python/circuit/library/test_linear_function.py
  test/python/circuit/test_gate_definitions.py
  test/python/circuit/test_random_circuit.py
  test/python/transpiler/test_apply_layout.py
  test/qpy_compat/test_qpy.py
Labels: type: qa, Changelog: None

#11698 Merge 0.45.3 into stable/0.46
  .github/workflows/docs_deploy.yml
  Cargo.lock
  Cargo.toml
  docs/conf.py
  qiskit/VERSION.txt
  qiskit/__init__.py
  qiskit/circuit/library/standard_gates/u3.py
  qiskit/pulse/library/symbolic_pulses.py
  qiskit/quantum_info/operators/measures.py
  qiskit/quantum_info/operators/symplectic/pauli.py
  qiskit/transpiler/passes/optimization/consolidate_blocks.py
  qiskit_pkg/setup.py
  releasenotes/notes/qiskit-1.0-incompatibility-9ad22472837837d8.yaml
  setup.py
  tools/rclone.conf.enc
Labels: Changelog: None

#11692 Remove pulse scoped_parameters and search_parameters
  qiskit/pulse/schedule.py
  releasenotes/notes/remove-pulse-scoped-parameters-fa897399900f2ef2.yaml
  test/python/pulse/test_reference.py
Labels: Changelog: Removal, mod: pulse

#11691 Deprecate pulse parameter scoping
  qiskit/pulse/schedule.py
  releasenotes/notes/deprecate-pulse-parameter-scoping-6b6b50a394b57937.yaml
  test/python/pulse/test_reference.py
Labels: Changelog: Deprecation, mod: pulse

#11636 Deprecate visualization code
  qiskit/visualization/circuit/_utils.py
  qiskit/visualization/counts_visualization.py
  releasenotes/notes/deprecate-visualization-code-8303626254b79abe.yaml
  test/python/visualization/test_plot_histogram.py
Labels: Changelog: Deprecation, mod: visualization

#11576 Remove deprecated features in 0.46 in primitives
  qiskit/primitives/base/base_estimator.py
  qiskit/primitives/base/base_primitive.py
  qiskit/primitives/base/base_primitive_job.py
  qiskit/primitives/base/base_result.py
  qiskit/primitives/base/base_sampler.py
  qiskit/primitives/base/estimator_result.py
  qiskit/primitives/base/sampler_result.py
  qiskit/primitives/primitive_job.py
  qiskit/primitives/utils.py
  test/python/primitives/test_estimator.py
  test/python/primitives/test_result.py
Labels: Changelog: Removal, mod: primitives

#11505 Fix qpy support for Annotated Operations
  qiskit/circuit/__init__.py
  qiskit/qpy/__init__.py
  qiskit/qpy/binary_io/circuits.py
  qiskit/qpy/formats.py
  qiskit/qpy/type_keys.py
  releasenotes/notes/fix-annotated-qpy-6503362c79f29838.yaml
  test/python/circuit/test_circuit_load_from_qpy.py
  test/qpy_compat/test_qpy.py
Labels: mod: qpy

#11593 Update `gate.inverse()` to return `AnnotatedOperation`
  qiskit/circuit/annotated_operation.py
  qiskit/circuit/barrier.py
  qiskit/circuit/controlledgate.py
  qiskit/circuit/delay.py
  qiskit/circuit/instruction.py
  qiskit/circuit/instructionset.py
  qiskit/circuit/library/basis_change/qft.py
  qiskit/circuit/library/blueprintcircuit.py
  qiskit/circuit/library/data_preparation/state_preparation.py
  qiskit/circuit/library/generalized_gates/diagonal.py
  qiskit/circuit/library/generalized_gates/isometry.py
  qiskit/circuit/library/generalized_gates/mcg_up_to_diagonal.py
  qiskit/circuit/library/generalized_gates/mcmt.py
  qiskit/circuit/library/generalized_gates/pauli.py
  qiskit/circuit/library/generalized_gates/permutation.py
  qiskit/circuit/library/generalized_gates/rv.py
  qiskit/circuit/library/generalized_gates/uc.py
  qiskit/circuit/library/generalized_gates/unitary.py
  qiskit/circuit/library/hamiltonian_gate.py
  qiskit/circuit/library/standard_gates/ecr.py
  qiskit/circuit/library/standard_gates/global_phase.py
  qiskit/circuit/library/standard_gates/h.py
  qiskit/circuit/library/standard_gates/i.py
  qiskit/circuit/library/standard_gates/p.py
  qiskit/circuit/library/standard_gates/r.py
  qiskit/circuit/library/standard_gates/rx.py
  qiskit/circuit/library/standard_gates/rxx.py
  qiskit/circuit/library/standard_gates/ry.py
  qiskit/circuit/library/standard_gates/ryy.py
  qiskit/circuit/library/standard_gates/rz.py
  qiskit/circuit/library/standard_gates/rzx.py
  qiskit/circuit/library/standard_gates/rzz.py
  qiskit/circuit/library/standard_gates/s.py
  qiskit/circuit/library/standard_gates/swap.py
  qiskit/circuit/library/standard_gates/sx.py
  qiskit/circuit/library/standard_gates/t.py
  qiskit/circuit/library/standard_gates/u.py
  qiskit/circuit/library/standard_gates/u1.py
  qiskit/circuit/library/standard_gates/u2.py
  qiskit/circuit/library/standard_gates/u3.py
  qiskit/circuit/library/standard_gates/x.py
  qiskit/circuit/library/standard_gates/xx_minus_yy.py
  qiskit/circuit/library/standard_gates/xx_plus_yy.py
  qiskit/circuit/library/standard_gates/y.py
  qiskit/circuit/library/standard_gates/z.py
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/add-annotated-arg-to-inverse-2e577f33793c06b1.yaml
  test/python/circuit/test_instructions.py
Labels: priority: medium

#11687 Add more classes for 2q synthesis to qiskit synthesis docs
  qiskit/synthesis/__init__.py
  qiskit/synthesis/two_qubit/__init__.py
  qiskit/synthesis/two_qubit/two_qubit_decompose.py
Labels: documentation, Changelog: None

#11711 Effect final removals from Qiskit 1.0
  qiskit/circuit/classicalregister.py
  qiskit/circuit/qpy_serialization.py
  qiskit/circuit/quantumcircuit.py
  qiskit/circuit/quantumregister.py
  qiskit/circuit/register.py
  qiskit/quantum_info/operators/measures.py
  qiskit/synthesis/two_qubit/two_qubit_decompose.py
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/scheduling/calibration_creators.py
  qiskit/transpiler/passes/scheduling/rzx_templates.py
  qiskit/transpiler/passes/synthesis/__init__.py
  qiskit/transpiler/passes/synthesis/linear_functions_synthesis.py
  qiskit/visualization/pulse_v2/stylesheet.py
  qiskit/visualization/timeline/stylesheet.py
  releasenotes/notes/rollup-removals-ce8326ea90c0ad99.yaml
  test/python/circuit/test_circuit_load_from_qpy.py
  test/python/circuit/test_circuit_properties.py
  test/python/circuit/test_register.py
  test/python/transpiler/test_linear_functions_passes.py
Labels: Changelog: Removal

#11674 Set version number to 1.0.0rc1 for first release candidate
  .github/workflows/wheels.yml
  docs/conf.py
  qiskit/VERSION.txt
Labels: Changelog: None

#11712 Bump main branch version post 1.0.0rc1 tag
  .mergify.yml
  Cargo.lock
  Cargo.toml
  docs/conf.py
  qiskit/VERSION.txt
Labels: Changelog: None

#11714 Ignore bump to `black~=24.1` in `git blame`
  .git-blame-ignore-revs
Labels: type: qa, Changelog: None

#11716 Update package metadata license field to use text
  pyproject.toml
Labels: stable backport potential, Changelog: None

#11722 Improve `primitives.containers.PubResult __repr__`
  qiskit/primitives/containers/pub_result.py
Labels: stable backport potential, Changelog: None

#11730 Fix qpy.dump()'s use_symengine when passed a truthy object
  qiskit/qpy/type_keys.py
  releasenotes/notes/fix-qpy-use-symengine-bool-like-d17550057a58abf2.yaml
  test/python/qpy/test_circuit_load_from_qpy.py
Labels: priority: high, stable backport potential, Changelog: Bugfix

#11728 fix argument documentation of transpile functions
  qiskit/compiler/transpiler.py
  qiskit/transpiler/preset_passmanagers/__init__.py
Labels: documentation, stable backport potential, Changelog: None

#11622 Add short-circuit to exit BasisTranslator early when possible
  qiskit/transpiler/passes/basis/basis_translator.py
Labels: performance, Changelog: None, mod: transpiler

#11173 Autolabel dependabot PRs with no changelog
  .github/dependabot.yml
Labels: type: qa, Changelog: None

#11734 Reduce noise from `reno lint`
  requirements-dev.txt
  tox.ini
Labels: type: qa, stable backport potential, Changelog: None

#11736 Annotate and clarify that metadata keys should be strings
  qiskit/primitives/containers/primitive_result.py
  qiskit/primitives/containers/pub_result.py
  test/python/primitives/containers/test_primitive_result.py
Labels: stable backport potential, Changelog: None

#11602 Dependabot: Add GitHub Actions updates to the current Cargo updates
  .github/dependabot.yml
Labels: type: qa, Changelog: None, Community PR

#11742 Remove qiskit-terra link in SECURITY.md
  SECURITY.md
Labels: Changelog: None, Community PR

#11748 Fix `parallel_map` docs
  qiskit/utils/parallel.py
Labels: documentation, stable backport potential, Changelog: None

#11758 Fix asv installation command
  asv.conf.json
Labels: type: qa, Changelog: None

#11757 Make scipy imports on default path lazy
  qiskit/quantum_info/operators/operator.py
  qiskit/synthesis/unitary/aqc/aqc.py
  tools/find_optional_imports.py
Labels: stable backport potential, performance, Changelog: None

#11719 Additions and fixes to qiskit synthesis docs and release notes
  qiskit/synthesis/__init__.py
  qiskit/synthesis/two_qubit/two_qubit_decompose.py
  releasenotes/notes/remove_qinfo_synthesis-1917c7ccfcc62180.yaml
Labels: documentation, stable backport potential, Changelog: None

#11765 Unskipping the test: `test.python.compiler.test_transpiler.TestTranspileMultiChipTarget.test_transpile_does_not_affect_backend_coupling_4_3`
  test/python/compiler/test_transpiler.py
Labels: type: qa, Changelog: None

#11766 Unskipping the test: `test.python.transpiler.test_layout_transformation.TestLayoutTransformation.test_full_connected_coupling_map`
  test/python/transpiler/test_layout_transformation.py
Labels: type: qa, Changelog: None

#11726 Update pulse instruction interface to the new pulse model
  qiskit/assembler/assemble_schedules.py
  qiskit/pulse/builder.py
  qiskit/pulse/instructions/acquire.py
  qiskit/pulse/instructions/delay.py
  qiskit/pulse/instructions/directives.py
  qiskit/pulse/instructions/frequency.py
  qiskit/pulse/instructions/instruction.py
  qiskit/pulse/instructions/phase.py
  qiskit/pulse/instructions/play.py
  qiskit/pulse/instructions/reference.py
  qiskit/pulse/instructions/snapshot.py
  qiskit/pulse/macros.py
  qiskit/pulse/model/mixed_frames.py
  qiskit/pulse/transforms/canonicalization.py
  qiskit/qobj/converters/pulse_instruction.py
  qiskit/visualization/pulse_v2/core.py
  test/python/circuit/test_circuit_operations.py
  test/python/circuit/test_parameters.py
  test/python/compiler/test_assembler.py
  test/python/compiler/test_disassembler.py
  test/python/primitives/test_primitive.py
  test/python/pulse/test_block.py
  test/python/pulse/test_builder.py
  test/python/pulse/test_builder_v2.py
  test/python/pulse/test_calibration_entries.py
  test/python/pulse/test_frames.py
  test/python/pulse/test_instruction_schedule_map.py
  test/python/pulse/test_instructions.py
  test/python/pulse/test_macros.py
  test/python/pulse/test_mixed_frames.py
  test/python/pulse/test_parameter_manager.py
  test/python/pulse/test_pulse_targets.py
  test/python/pulse/test_schedule.py
  test/python/pulse/test_transforms.py
  test/python/qobj/test_pulse_converter.py
  test/python/qpy/test_block_load_from_qpy.py
  test/python/scheduler/test_basic_scheduler.py
  test/python/transpiler/legacy_scheduling/test_instruction_alignments.py
  test/python/transpiler/test_calibrationbuilder.py
  test/python/transpiler/test_instruction_alignments.py
  test/python/transpiler/test_scheduling_padding_pass.py
  test/python/visualization/pulse_v2/test_core.py
  test/python/visualization/pulse_v2/test_events.py
  test/python/visualization/pulse_v2/test_generators.py
  test/python/visualization/pulse_v2/test_layouts.py
Labels: mod: pulse, experimental

#11749 Expand docstrings for annotated flag on `control()` and `inverse()`
  qiskit/circuit/library/generalized_gates/unitary.py
  qiskit/circuit/library/hamiltonian_gate.py
  qiskit/circuit/library/standard_gates/ecr.py
  qiskit/circuit/library/standard_gates/global_phase.py
  qiskit/circuit/library/standard_gates/h.py
  qiskit/circuit/library/standard_gates/i.py
  qiskit/circuit/library/standard_gates/p.py
  qiskit/circuit/library/standard_gates/r.py
  qiskit/circuit/library/standard_gates/rx.py
  qiskit/circuit/library/standard_gates/rxx.py
  qiskit/circuit/library/standard_gates/ry.py
  qiskit/circuit/library/standard_gates/ryy.py
  qiskit/circuit/library/standard_gates/rz.py
  qiskit/circuit/library/standard_gates/rzx.py
  qiskit/circuit/library/standard_gates/rzz.py
  qiskit/circuit/library/standard_gates/s.py
  qiskit/circuit/library/standard_gates/swap.py
  qiskit/circuit/library/standard_gates/sx.py
  qiskit/circuit/library/standard_gates/t.py
  qiskit/circuit/library/standard_gates/u.py
  qiskit/circuit/library/standard_gates/u1.py
  qiskit/circuit/library/standard_gates/u2.py
  qiskit/circuit/library/standard_gates/u3.py
  qiskit/circuit/library/standard_gates/x.py
  qiskit/circuit/library/standard_gates/xx_minus_yy.py
  qiskit/circuit/library/standard_gates/xx_plus_yy.py
  qiskit/circuit/library/standard_gates/y.py
  qiskit/circuit/library/standard_gates/z.py
Labels: documentation, stable backport potential, Changelog: None

#11773 Update release support in security policy
  SECURITY.md
Labels: documentation, stable backport potential, Changelog: None

#11744 Fix bad indentation on quantumcircuit.py
  qiskit/circuit/quantumcircuit.py
Labels: documentation, stable backport potential, Changelog: None

#11778 Remove more qiskit.org links
  CONTRIBUTING.md
  README.md
  docs/conf.py
  qiskit/utils/optionals.py
  test/python/transpiler/test_basis_translator.py
Labels: documentation, stable backport potential, Changelog: None

#11769 deterministic `test_fake_backend_v2_noise_model_always_present`
  test/python/providers/fake_provider/test_fake_backends.py
Labels: type: qa, Changelog: None

#11792 remove toqm from reserved names list
  qiskit/transpiler/preset_passmanagers/plugin.py
Labels: documentation, stable backport potential, Changelog: None

#11789 Make BaseEstimatorV2 importable from qiskit.primitives
  qiskit/primitives/__init__.py
Labels: stable backport potential, Changelog: None, mod: primitives

#11767 Introduce Pulse IR skeleton
  qiskit/pulse/ir/__init__.py
  qiskit/pulse/ir/ir.py
  test/python/pulse/test_mixed_frames.py
  test/python/pulse/test_pulse_ir.py
Labels: mod: pulse, experimental

#11785 Fix `GenericBackendV2` defaults
  qiskit/providers/fake_provider/generic_backend_v2.py
  test/python/primitives/test_backend_estimator.py
  test/python/providers/fake_provider/test_generic_backend_v2.py
  test/python/visualization/test_circuit_text_drawer.py
  test/visual/mpl/circuit/references/layout_control_flow.png
  test/visual/mpl/circuit/references/nested_layout_control_flow.png
Labels: stable backport potential, Changelog: None

#11797 Improve debugability of TwoQubitWeylDecomposition assertRoundTrip failures
  test/python/synthesis/test_synthesis.py
Labels: type: qa, stable backport potential, Changelog: None

#11800 Fix bug in `BindingsArray.__getitem__()`
  qiskit/primitives/containers/bindings_array.py
  test/python/primitives/containers/test_bindings_array.py
Labels: priority: high, stable backport potential, Changelog: None

#11798 Add script to report numpy env
  .azure/test-linux.yml
  .azure/test-macos.yml
  .azure/test-windows.yml
  .github/workflows/coverage.yml
  requirements-dev.txt
  tools/report_numpy_state.py
Labels: type: qa, stable backport potential, Changelog: None

#11755 Format synthesis docs
  qiskit/quantum_info/operators/dihedral/dihedral.py
  qiskit/quantum_info/operators/symplectic/clifford.py
  qiskit/synthesis/clifford/clifford_decompose_ag.py
  qiskit/synthesis/clifford/clifford_decompose_bm.py
  qiskit/synthesis/clifford/clifford_decompose_full.py
  qiskit/synthesis/clifford/clifford_decompose_greedy.py
  qiskit/synthesis/clifford/clifford_decompose_layers.py
  qiskit/synthesis/cnotdihedral/cnotdihedral_decompose_full.py
  qiskit/synthesis/cnotdihedral/cnotdihedral_decompose_general.py
  qiskit/synthesis/cnotdihedral/cnotdihedral_decompose_two_qubits.py
  qiskit/synthesis/discrete_basis/gate_sequence.py
  qiskit/synthesis/discrete_basis/generate_basis_approximations.py
  qiskit/synthesis/evolution/lie_trotter.py
  qiskit/synthesis/evolution/product_formula.py
  qiskit/synthesis/evolution/qdrift.py
  qiskit/synthesis/evolution/suzuki_trotter.py
  qiskit/synthesis/linear/cnot_synth.py
  qiskit/synthesis/linear/linear_circuits_utils.py
  qiskit/synthesis/linear/linear_depth_lnn.py
  qiskit/synthesis/linear_phase/cnot_phase_synth.py
  qiskit/synthesis/linear_phase/cx_cz_depth_lnn.py
  qiskit/synthesis/linear_phase/cz_depth_lnn.py
  qiskit/synthesis/one_qubit/one_qubit_decompose.py
  qiskit/synthesis/permutation/permutation_full.py
  qiskit/synthesis/permutation/permutation_lnn.py
  qiskit/synthesis/qft/qft_decompose_lnn.py
  qiskit/synthesis/stabilizer/stabilizer_circuit.py
  qiskit/synthesis/stabilizer/stabilizer_decompose.py
  qiskit/synthesis/two_qubit/two_qubit_decompose.py
  qiskit/synthesis/two_qubit/xx_decompose/decomposer.py
  qiskit/synthesis/unitary/qsd.py
Labels: documentation, priority: low, stable backport potential, Changelog: None

#11801 Update qiskit-terra to qiskit in README.md
  README.md
Labels: stable backport potential, Changelog: None

#11763 add synthesis plugin docs
  docs/apidoc/index.rst
  docs/apidoc/synthesis_aqc.rst
  docs/apidoc/transpiler_builtin_plugins.rst
  docs/apidoc/transpiler_synthesis_plugins.rst
  qiskit/synthesis/__init__.py
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/synthesis/aqc_plugin.py
  qiskit/transpiler/passes/synthesis/high_level_synthesis.py
  qiskit/transpiler/passes/synthesis/plugin.py
  qiskit/transpiler/passes/synthesis/solovay_kitaev_synthesis.py
  qiskit/transpiler/passes/synthesis/unitary_synthesis.py
Labels: documentation, stable backport potential, Changelog: None

#11750 bug loading MPL style from the configuration
  qiskit/visualization/circuit/qcstyle.py
  qiskit/visualization/circuit/styles/__init__.py
  releasenotes/notes/fix_11536-c87d192a133b3dc3.yaml
  test/python/visualization/test_circuit_drawer.py
Labels: stable backport potential, Changelog: Bugfix

#11775 Update deprecation policy document for Qiskit 1.0
  DEPRECATION.md
Labels: documentation, stable backport potential, Changelog: None

#11589 Add release notes for V2 of the primitives
  qiskit/primitives/__init__.py
  qiskit/primitives/base/__init__.py
  qiskit/primitives/base/base_estimator.py
  qiskit/primitives/base/base_sampler.py
  qiskit/primitives/containers/observables_array.py
  qiskit/primitives/statevector_estimator.py
  qiskit/primitives/statevector_sampler.py
  releasenotes/notes/primitives-v2-df871c0c6ac0b94a.yaml
Labels: documentation, stable backport potential, Changelog: None, mod: primitives

#11782 Fix scheduling units
  qiskit/circuit/duration.py
  releasenotes/notes/fix-scheduling-units-59477912b47d3dc1.yaml
  test/python/circuit/test_scheduled_circuit.py
Labels: stable backport potential, Changelog: Bugfix

#11786 deterministic `test_transpile_target_with_qubits_without_delays_with_scheduling_8`
  test/python/compiler/test_transpiler.py
Labels: type: qa, stable backport potential, Changelog: None

#11826 Fix pip uninstall command in qiskit-neko
  .github/workflows/neko.yml
Labels: type: qa, Changelog: None

#11795 Expose `PauliList.noncommutation_graph` in public API
  qiskit/quantum_info/operators/symplectic/pauli_list.py
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
  releasenotes/notes/public-noncommutation-graph-dd31c931b7045a4f.yaml
  test/python/quantum_info/operators/symplectic/test_pauli_list.py
  test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
Labels: Changelog: New Feature, mod: quantum info

#11830 quantum-computing.ibm.com is going to disappear, eventually
  MAINTAINING.md
  qiskit/circuit/quantumcircuit.py
  qiskit/qpy/__init__.py
  qiskit/transpiler/passes/basis/basis_translator.py
  qiskit/transpiler/passes/scheduling/alignments/pulse_gate_validation.py
Labels: documentation, Changelog: None

#11833 Fix image tests on 0.46 stable branch
  .azure/test-linux.yml
Labels: type: qa, Changelog: None

#11829 Fix custom pulse instruction conversion to Qobj.
  qiskit/qobj/converters/pulse_instruction.py
  releasenotes/notes/fix-custom-pulse-qobj-conversion-5d6041b36356cfd1.yaml
  test/python/compiler/test_assembler.py
Labels: stable backport potential, Changelog: Bugfix, mod: pulse

#11837 Fix bad release note list item
  releasenotes/notes/0.46/prepare-0.46.0-c3857463a3c052f7.yaml
Labels: documentation, Changelog: None

#11850 Add rust file support to verify_headers.py and check crates/
  crates/accelerate/src/utils.rs
  tools/verify_headers.py
  tox.ini
Labels: type: qa, stable backport potential, Changelog: None, Rust

#11844 Deduplicate SliceOrInt
  crates/accelerate/src/euler_one_qubit_decomposer.rs
  crates/accelerate/src/quantum_circuit/circuit_data.rs
  crates/accelerate/src/utils.rs
Labels: stable backport potential, performance, Changelog: None, Rust

#11840 Remove Qiskit 0.45 and 0.46 release notes from 1.0
  docs/release_notes.rst
Labels: documentation, Changelog: None

#11787 Fix `PropertySet` re-use in `BasePassManager.run`
  qiskit/passmanager/passmanager.py
  releasenotes/notes/fix-passmanager-reuse-151877e1905d49df.yaml
  test/python/passmanager/test_passmanager.py
Labels: stable backport potential, Changelog: Bugfix, mod: transpiler

#11834 Fix an unchecked condition in InverseCancellation
  qiskit/transpiler/passes/optimization/inverse_cancellation.py
  releasenotes/notes/fix-inverse-cancellation-self-inverse-e09a5553331e1b0b.yaml
  test/python/transpiler/test_inverse_cancellation.py
Labels: Changelog: Bugfix, Community PR

#11862 Prepare Qiskit 1.0.1
  Cargo.lock
  Cargo.toml
  docs/conf.py
  qiskit/VERSION.txt
  releasenotes/notes/fix-custom-pulse-qobj-conversion-5d6041b36356cfd1.yaml
  releasenotes/notes/fix-inverse-cancellation-self-inverse-e09a5553331e1b0b.yaml
  releasenotes/notes/fix-scheduling-units-59477912b47d3dc1.yaml
  releasenotes/notes/prepare-1.0.1-aecb2e3743bab4e1.yaml
Labels: Changelog: None

#11652 Ensure that Parameters compare equal when they have the same hash
  qiskit/circuit/parameter.py
  releasenotes/notes/parameter-hash-eq-645f9de55aa78d02.yaml
  test/python/circuit/test_parameters.py
Labels: stable backport potential, Changelog: Bugfix, mod: circuit

#11868 Fix Observables.coerce() for 0-d inputs
  qiskit/primitives/containers/observables_array.py
  releasenotes/notes/obs-array-coerce-0d-28b192fb3d004d4a.yaml
  test/python/primitives/containers/test_observables_array.py
Labels: stable backport potential, Changelog: Bugfix

#11873 Fix 1.0 release note leaving off entries
  docs/release_notes.rst
Labels: documentation, Changelog: None

#11871 Fix improper handling of `BindingsArray` in `EstimatorPub.coerce()`
  qiskit/primitives/containers/estimator_pub.py
  releasenotes/notes/fix-estimator-pub-coerce-5d13700e15126421.yaml
  test/python/primitives/containers/test_estimator_pub.py
Labels: stable backport potential, Changelog: Bugfix

#11877 Fix handling of control flow instructions in convert_to_target()
  qiskit/providers/backend_compat.py
  releasenotes/notes/fix-control-flow-convert-to-target-ae838418a7ad2a20.yaml
  test/python/providers/test_fake_backends.py
Labels: stable backport potential, Changelog: Bugfix

#11882 Fix typo in sparse_pauli_op.py
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
Labels: documentation, Changelog: None, Community PR

#11820 Revert "Revert memory-owning `expr.Var` nodes (#11667)"
  qiskit/circuit/__init__.py
  qiskit/circuit/classical/expr/__init__.py
  qiskit/circuit/classical/expr/expr.py
  qiskit/circuit/classical/expr/visitors.py
  qiskit/circuit/controlflow/builder.py
  qiskit/circuit/controlflow/control_flow.py
  qiskit/circuit/quantumcircuit.py
  qiskit/circuit/store.py
  releasenotes/notes/classical-store-e64ee1286219a862.yaml
  releasenotes/notes/expr-var-standalone-2c1116583a2be9fd.yaml
  test/python/circuit/classical/test_expr_helpers.py
  test/python/circuit/classical/test_expr_properties.py
  test/python/circuit/test_circuit_operations.py
  test/python/circuit/test_circuit_vars.py
  test/python/circuit/test_control_flow.py
  test/python/circuit/test_control_flow_builders.py
  test/python/circuit/test_store.py
Labels: Changelog: None, mod: circuit

#11866 Corrected probabilities method names in stabilizer state for issue #11688
  qiskit/quantum_info/states/stabilizerstate.py
  test/python/quantum_info/states/test_stabilizerstate.py
Labels: Changelog: None, Community PR

#11903 _mcsu2 should raise a QiskitError with a non-SU(2) input
  qiskit/circuit/library/standard_gates/multi_control_rotation_gates.py
Labels: Changelog: None, Community PR

#11874 Fixing bug in `qcstyle` that modified custom style dict
  qiskit/visualization/circuit/qcstyle.py
  releasenotes/notes/qcstyle-bug-custom-style-dicts-22deab6c602ccd6a.yaml
  test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py
Labels: stable backport potential, Changelog: Bugfix, Community PR

#11907 Fix transpilation of control flow to no hardware
  qiskit/transpiler/preset_passmanagers/common.py
  releasenotes/notes/fix-transpile-control-flow-no-hardware-7c00ad733a569bb9.yaml
  test/python/compiler/test_transpiler.py
Labels: stable backport potential, Changelog: Bugfix, mod: transpiler

#11916 Use pulp for simd acceleration
  Cargo.lock
  crates/accelerate/Cargo.toml
  crates/accelerate/src/pauli_exp_val.rs
Labels: performance, Changelog: None, Rust

#11912 Use const arrays for non-normalized basis in unitary synthesis
  crates/accelerate/src/two_qubit_decompose.rs
Labels: Changelog: None, Rust

#11910 Fix type hint and doc of `StatevectorEstimator.default_precision`
  qiskit/primitives/statevector_estimator.py
Labels: stable backport potential, Changelog: None, mod: primitives

#11913 Fix improper handling of BindingsArray in SamplerPub.coerce()
  qiskit/primitives/containers/sampler_pub.py
  releasenotes/notes/fix-estimator-pub-coerce-5d13700e15126421.yaml
  releasenotes/notes/fix-pub-coerce-5d13700e15126421.yaml
  test/python/primitives/containers/test_sampler_pub.py
Labels: stable backport potential, Changelog: Bugfix

#11922 Fix handling of control flow instructions in convert_to_target()
  qiskit/providers/backend_compat.py
  releasenotes/notes/fix-control-flow-convert-to-target-ae838418a7ad2a20.yaml
  test/python/providers/test_fake_backends.py
Labels: Changelog: Bugfix
