Repository Qiskit/qiskit, pull requests merged in 2024-10, with the labels that each got.

#13214 Add some more gates to CollectCliffords pass
  qiskit/transpiler/passes/optimization/collect_cliffords.py
  releasenotes/notes/add-gates-to-collect-clifford-af88dd8f7a2a4bf9.yaml
  test/python/transpiler/test_clifford_passes.py
Labels: Changelog: New Feature, mod: transpiler

#13234 Avoid checking if matrix is unitary in Split2qUnitaries
  crates/accelerate/src/split_2q_unitaries.rs
Labels: performance, Changelog: None, mod: transpiler

#12754 Fixed Incoherent notation for the RZX Gate api doc
  qiskit/circuit/library/standard_gates/rzx.py
Labels: documentation, Changelog: None, Community PR

#13231 Doc fix ZZ_feature_maps
  qiskit/circuit/library/blueprintcircuit.py
  qiskit/circuit/library/data_preparation/_zz_feature_map.py
  qiskit/circuit/library/data_preparation/pauli_feature_map.py
Labels: documentation, Changelog: None, Community PR

#13251 Workaround symengine serialization payload incompatibility
  qiskit/qpy/__init__.py
  qiskit/qpy/binary_io/schedules.py
  qiskit/qpy/binary_io/value.py
  qiskit/qpy/common.py
  qiskit/qpy/interface.py
  releasenotes/notes/fix-qpy-symengine-compat-858970a9a1d6bc14.yaml
  requirements.txt
Labels: priority: high, stable backport potential, Changelog: Bugfix

#13256 Prepare Qiskit 1.2.3
  Cargo.lock
  Cargo.toml
  docs/conf.py
  qiskit/VERSION.txt
  qiskit/qpy/__init__.py
  qiskit/qpy/common.py
  releasenotes/notes/fix-qpy-symengine-compat-858970a9a1d6bc14.yaml
  releasenotes/notes/prepare-1.2.3-1386aaab85a3fde0.yaml
Labels: Changelog: None

#13259 Fix bug in QPY symengine payload version handling
  qiskit/qpy/__init__.py
  qiskit/qpy/common.py
  qiskit/qpy/interface.py
  releasenotes/notes/fix-qpy-parsing-123-75357c3709e35963.yaml
  releasenotes/notes/fix-qpy-symengine-compat-858970a9a1d6bc14.yaml
  test/qpy_compat/get_versions.py
  test/qpy_compat/run_tests.sh
Labels: priority: high, stable backport potential, Changelog: Bugfix, mod: qpy

#13238 Add Rust quantum volume function
  crates/accelerate/src/circuit_library/mod.rs
  crates/accelerate/src/circuit_library/pauli_feature_map.rs
  crates/accelerate/src/circuit_library/quantum_volume.rs
  crates/accelerate/src/two_qubit_decompose.rs
  crates/circuit/src/circuit_data.rs
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/quantum_volume.py
  releasenotes/notes/add-qv-function-a8990e248d5e7e1a.yaml
  test/python/circuit/library/test_quantum_volume.py
Labels: performance, Changelog: New Feature, Rust, mod: circuit

#13261 Removes unused imports from code block
  qiskit/visualization/circuit/circuit_visualization.py
Labels: documentation, stable backport potential, Changelog: None, Community PR

#13094 Port `ElidePermutations` transpiler pass to Rust
  crates/accelerate/src/elide_permutations.rs
  crates/accelerate/src/lib.rs
  crates/circuit/src/dag_circuit.rs
  crates/pyext/src/lib.rs
  qiskit/__init__.py
  qiskit/circuit/library/generalized_gates/permutation.py
  qiskit/transpiler/passes/optimization/elide_permutations.py
  releasenotes/notes/port-elide-permutations-ed91c3d9cef2fec6.yaml
Labels: mod: transpiler

#13266 Prepare 1.2.4 release
  Cargo.lock
  Cargo.toml
  docs/conf.py
  qiskit/VERSION.txt
  releasenotes/notes/fix-qpy-parsing-123-75357c3709e35963.yaml
  releasenotes/notes/prepare-1.2.4-4a855c6e6bf78a4b.yaml
Labels: Changelog: None

#13265 Update version of Coveralls GitHub Action
  .github/workflows/coverage.yml
Labels: type: qa, stable backport potential, Changelog: None

#13150 `MCMTGate` & plugins
  crates/accelerate/src/synthesis/mod.rs
  crates/accelerate/src/synthesis/multi_controlled/mcmt.rs
  crates/accelerate/src/synthesis/multi_controlled/mod.rs
  pyproject.toml
  qiskit/__init__.py
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/generalized_gates/__init__.py
  qiskit/circuit/library/generalized_gates/mcmt.py
  qiskit/synthesis/__init__.py
  qiskit/synthesis/multi_controlled/__init__.py
  qiskit/synthesis/multi_controlled/mcmt_vchain.py
  qiskit/transpiler/passes/synthesis/hls_plugins.py
  releasenotes/notes/mcmt-gate-a201d516f05c7d56.yaml
  test/python/circuit/library/test_mcmt.py
  test/python/circuit/test_controlled_gate.py
  test/python/circuit/test_gate_definitions.py
Labels: Rust, mod: circuit

#13268 fixed circuit_drawer example in qiskit/visualization/circuit/circuit_visualization.py
  qiskit/visualization/circuit/circuit_visualization.py
Labels: documentation, stable backport potential, Community PR

#13281 Fix GitHub source code links for decorated functions
  docs/conf.py
Labels: documentation, stable backport potential

#13247 Improve deprecation of unit and duration
  crates/circuit/src/circuit_instruction.rs
  crates/circuit/src/dag_circuit.rs
  crates/circuit/src/operations.rs
  qiskit/circuit/delay.py
  qiskit/circuit/instruction.py
  qiskit/converters/circuit_to_dag.py
  qiskit/converters/dag_to_circuit.py
  qiskit/visualization/timeline/core.py
  qiskit/visualization/timeline/interface.py
  releasenotes/notes/deprecate-unit-duration-48b76c957bac5691.yaml
  test/utils/base.py
Labels: Changelog: Deprecation, Changelog: New Feature, Rust, mod: circuit

#13292 Fix GitHub source code links on Windows docs builds
  docs/conf.py
Labels: type: qa, documentation, stable backport potential, Changelog: None

#12811 [Oxidize BasisTranslator]: Move `basis_search` and `BasisSearchVisitor` to rust.
  crates/accelerate/src/basis/basis_translator/basis_search.rs
  crates/accelerate/src/basis/basis_translator/mod.rs
  crates/accelerate/src/equivalence.rs
  qiskit/__init__.py
  qiskit/transpiler/passes/basis/basis_translator.py
Labels: performance, Changelog: None, Rust

#13168 Add inverse function to StandardGate in rust
  crates/circuit/src/operations.rs
  test/python/circuit/test_rust_equivalence.py
Labels: Changelog: None, Rust

#13284 Add .index() and new() method to Qubit and Clbit
  crates/accelerate/src/check_map.rs
  crates/accelerate/src/commutation_checker.rs
  crates/accelerate/src/elide_permutations.rs
  crates/accelerate/src/euler_one_qubit_decomposer.rs
  crates/accelerate/src/gate_direction.rs
  crates/accelerate/src/gates_in_basis.rs
  crates/accelerate/src/synthesis/clifford/bm_synthesis.rs
  crates/accelerate/src/synthesis/clifford/greedy_synthesis.rs
  crates/accelerate/src/synthesis/clifford/utils.rs
  crates/accelerate/src/synthesis/multi_controlled/mcmt.rs
  crates/accelerate/src/synthesis/permutation/mod.rs
  crates/accelerate/src/unitary_compose.rs
  crates/circuit/src/dag_circuit.rs
  crates/circuit/src/lib.rs
Labels: Changelog: None, Rust

#13303 Document the `CommutationChecker`
  qiskit/circuit/__init__.py
Labels: documentation, stable backport potential, Changelog: None

#13296 Fixes typo on api/qiskit/providers page
  qiskit/providers/__init__.py
Labels: Community PR

#13313 Use PyO3 0.22 and rust-numpy 0.22
  Cargo.lock
  Cargo.toml
  crates/accelerate/Cargo.toml
  crates/accelerate/src/barrier_before_final_measurement.rs
  crates/accelerate/src/circuit_library/quantum_volume.rs
  crates/accelerate/src/commutation_checker.rs
  crates/accelerate/src/equivalence.rs
  crates/accelerate/src/error_map.rs
  crates/accelerate/src/euler_one_qubit_decomposer.rs
  crates/accelerate/src/nlayout.rs
  crates/accelerate/src/results/marginalization.rs
  crates/accelerate/src/sabre/heuristic.rs
  crates/accelerate/src/sabre/neighbor_table.rs
  crates/accelerate/src/sabre/route.rs
  crates/accelerate/src/stochastic_swap.rs
  crates/accelerate/src/target_transpiler/mod.rs
  crates/accelerate/src/two_qubit_decompose.rs
  crates/circuit/Cargo.toml
  crates/circuit/src/bit_data.rs
  crates/circuit/src/circuit_data.rs
  crates/circuit/src/circuit_instruction.rs
  crates/circuit/src/dag_circuit.rs
  crates/circuit/src/dag_node.rs
  crates/circuit/src/operations.rs
  crates/circuit/src/slice.rs
  crates/qasm2/src/bytecode.rs
Labels: Changelog: None, Rust, dependencies

#13311 Fix `QuantumCircuit.decompose` for high-level objects
  qiskit/circuit/quantumcircuit.py
  qiskit/transpiler/passes/basis/decompose.py
  releasenotes/notes/fix-decompose-hls-5019793177136024.yaml
  test/python/transpiler/test_decompose.py
Labels: Changelog: New Feature, Changelog: Bugfix

#13312 docs: clarify method purpose
  qiskit/quantum_info/operators/symplectic/base_pauli.py
Labels: documentation, stable backport potential, Changelog: None, Community PR

#13193 Remove duplicated weyl_coordinates python function
  crates/accelerate/src/two_qubit_decompose.rs
  qiskit/synthesis/two_qubit/weyl.py
  test/python/synthesis/test_weyl.py
  test/python/synthesis/xx_decompose/test_circuits.py
Labels: Changelog: None, Rust

#13327 Implement `__eq__` for remaining standard-library gates except `mcx`
  qiskit/circuit/library/standard_gates/p.py
  qiskit/circuit/library/standard_gates/u.py
  qiskit/circuit/library/standard_gates/u1.py
  qiskit/circuit/library/standard_gates/u2.py
  qiskit/circuit/library/standard_gates/u3.py
  releasenotes/notes/circuit-library-missing-eq-568e7a72008c0ab2.yaml
Labels: performance, Changelog: New Feature, mod: qasm3, mod: circuit

#13283 Use Rust generator function for QuantumVolume class
  qiskit/circuit/library/quantum_volume.py
  releasenotes/notes/add-qv-function-a8990e248d5e7e1a.yaml
Labels: performance, Changelog: New Feature, Changelog: API Change, mod: circuit

#13141 Oxidize `UnitarySynthesis` pass
  crates/accelerate/src/euler_one_qubit_decomposer.rs
  crates/accelerate/src/lib.rs
  crates/accelerate/src/two_qubit_decompose.rs
  crates/accelerate/src/unitary_synthesis.rs
  crates/circuit/src/dag_circuit.rs
  crates/circuit/src/imports.rs
  crates/pyext/src/lib.rs
  qiskit/__init__.py
  qiskit/transpiler/passes/synthesis/unitary_synthesis.py
  test/python/transpiler/test_unitary_synthesis.py
Labels: performance, Rust, mod: transpiler

#13328 Test wheel builds during PR CI on demand
  .github/workflows/wheels-build.yml
  .github/workflows/wheels-pr.yml
  .github/workflows/wheels.yml
  tools/build_pgo.sh
Labels: type: qa, Changelog: None, ci: test wheels

#13340 Fix OpenQASM 2 `gate` definitions following a shadowed built-in `gate`
  crates/qasm2/src/parse.rs
  releasenotes/notes/qasm2-builtin-gate-d80c2868cdf5f958.yaml
  test/python/qasm2/test_structure.py
Labels: stable backport potential, Changelog: Bugfix, mod: qasm2

#13235 Update dag_drawer Documentation to include DAGDependency on Allowed Types
  qiskit/visualization/dag_visualization.py
Labels: documentation, Community PR

#12957 Remove stale `variable_class_operations` set from `Target`
  crates/accelerate/src/target_transpiler/mod.rs
  test/python/transpiler/test_target.py
Labels: Changelog: None, Rust

#13358 Fix compatibility issues with SciPy 1.14
  constraints.txt
  qiskit/quantum_info/operators/channel/transformations.py
  qiskit/quantum_info/operators/operator.py
  releasenotes/notes/scipy-1.14-951d1c245473aee9.yaml
  test/python/quantum_info/operators/channel/test_kraus.py
  test/python/quantum_info/operators/channel/test_stinespring.py
  test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
  test/python/quantum_info/operators/test_operator.py
Labels: Changelog: Bugfix, mod: quantum info

#13309 Add official support for Python 3.13
  .github/workflows/tests.yml
  .github/workflows/wheels-build.yml
  asv.conf.json
  azure-pipelines.yml
  pyproject.toml
  test/python/utils/test_deprecation.py
  tox.ini
Labels: Changelog: New Feature, ci: test wheels

#13378 Avoid unnecessary matrix construction in `Split2qUnitaries`
  crates/accelerate/src/split_2q_unitaries.rs
Labels: performance, Changelog: None, Rust

#13375 Fix performance regression in UnitarySynthesis
  crates/accelerate/src/unitary_synthesis.rs
  qiskit/transpiler/passes/synthesis/unitary_synthesis.py
Labels: performance, Changelog: None, Rust

#13298 Implement arithmetic on `SparseObservable`
  crates/accelerate/src/sparse_observable.rs
  test/python/quantum_info/test_sparse_observable.py
Labels: Changelog: New Feature, mod: quantum info, Rust, mod: primitives

#13342 Use singleton canonical instances for OpenQASM 3 gate lookups
  crates/circuit/src/operations.rs
  qiskit/qasm3/exporter.py
Labels: performance, mod: qasm3

#13242 Fix CPhaseGate parameter name mismatch in API docs
  qiskit/circuit/library/standard_gates/p.py
  qiskit/circuit/library/standard_gates/rz.py
  qiskit/circuit/library/standard_gates/u1.py
Labels: documentation, Changelog: None, Community PR

#13379 Improve speed of `Pauli.to_label`
  qiskit/quantum_info/operators/symplectic/base_pauli.py
  releasenotes/notes/pauli-label-perf-b704cbcc5ef92794.yaml
Labels: performance, Changelog: New Feature, mod: quantum info

#13372 Implement `SparseObservable.apply_layout`
  crates/accelerate/src/lib.rs
  crates/accelerate/src/sparse_observable.rs
  test/python/quantum_info/test_sparse_observable.py
Labels: Changelog: New Feature, mod: quantum info, mod: primitives

#13241 IQP as circuit library function (and in Rust)
  crates/accelerate/src/circuit_library/iqp.rs
  crates/accelerate/src/circuit_library/mod.rs
  crates/accelerate/src/lib.rs
  qiskit/circuit/library/__init__.py
  qiskit/circuit/library/iqp.py
  releasenotes/notes/iqp-function-6594f7cf1521499c.yaml
  test/python/circuit/library/test_iqp.py
Labels: Rust, mod: circuit

#13338 Deprecate `instruction_durations`, `timing_constraints` and `backend_properties`
  qiskit/compiler/transpiler.py
  qiskit/transpiler/preset_passmanagers/generate_preset_pass_manager.py
  releasenotes/notes/fixes_13306-f9883a733491a72f.yaml
  test/python/circuit/test_scheduled_circuit.py
  test/python/compiler/test_transpiler.py
  test/python/transpiler/test_preset_passmanagers.py
  test/python/visualization/timeline/test_core.py
Labels: Changelog: Deprecation, mod: transpiler

#13367 Deprecate `BasicSimulator.configuration`
  qiskit/compiler/assembler.py
  qiskit/providers/basic_provider/basic_simulator.py
  releasenotes/notes/deprecate-basic-simulator-configuration-9d782925196993e9.yaml
  test/python/providers/basic_provider/__init__.py
Labels: Changelog: Deprecation

#13302 Parameterize Commutation Checker
  crates/accelerate/src/commutation_checker.rs
  qiskit/circuit/_standard_gates_commutations.py
  qiskit/transpiler/passes/optimization/template_matching/backward_match.py
  releasenotes/notes/Parameterized-commutation-checker-8a78a4715bf78b4e.yaml
  test/python/circuit/test_commutation_checker.py
  test/python/transpiler/test_commutative_inverse_cancellation.py
  tools/build_standard_commutations.py
Labels: performance, Changelog: New Feature, Rust, Community PR, mod: circuit

#13351 Deprecate `qiskit.result.mitigation`
  qiskit/result/mitigation/base_readout_mitigator.py
  qiskit/result/mitigation/correlated_readout_mitigator.py
  qiskit/result/mitigation/local_readout_mitigator.py
  qiskit/result/mitigation/utils.py
  releasenotes/notes/deprecate-mitigation-f5f6ef3233b3d726.yaml
  test/python/result/test_mitigators.py
Labels: Changelog: Deprecation

#13240 Improve qubit tracking in HighLevelSynthesis
  qiskit/transpiler/passes/synthesis/high_level_synthesis.py
  qiskit/transpiler/passes/synthesis/qubit_tracker.py
  releasenotes/notes/improve-hls-qubit-tracking-6b6288d556e3af9d.yaml
  test/python/circuit/library/test_mcmt.py
  test/python/transpiler/test_high_level_synthesis.py
Labels: mod: transpiler

#13384 Avoid iterating over nodes in Split2QUnitaries if there are no unitaries
  crates/accelerate/src/split_2q_unitaries.rs
Labels: performance, Changelog: None, Rust

#11557 Optimise `SparsePauliOp.from_operator`
  crates/accelerate/src/sparse_pauli_op.rs
  releasenotes/notes/faster-pauli-decomposition-faf2be01a6e75fff.yaml
  test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
Labels: performance, Changelog: New Feature, mod: quantum info, Rust

#13385 Fix type of `basis_gates` in `BasicSimulator` configuration
  qiskit/providers/basic_provider/basic_simulator.py
  releasenotes/notes/basicsimulator-config-copy-5ecdfdf161e488f2.yaml
Labels: stable backport potential, Changelog: Bugfix, mod: fake_provider

#13237 [Oxidize BasisTranslator]: Move the rest of the `BasisTranslator` to Rust.
  crates/accelerate/src/basis/basis_translator/basis_search.rs
  crates/accelerate/src/basis/basis_translator/compose_transforms.rs
  crates/accelerate/src/basis/basis_translator/mod.rs
  crates/accelerate/src/target_transpiler/mod.rs
  qiskit/transpiler/passes/basis/basis_translator.py
Labels: priority: high, performance, Changelog: None, Rust
