Repository Qiskit/qiskit, pull requests merged in 2024-05, with the labels that each got.

#12314 document entanglement="pairwise" for EfficientSU2
  qiskit/circuit/library/n_local/efficient_su2.py
Labels: documentation, Changelog: None

#12316 Fixing typos
  qiskit/transpiler/passes/synthesis/high_level_synthesis.py
Labels: documentation, Changelog: None

#12204 Add representation of `expr.Var` to `DAGCircuit`
  qiskit/circuit/controlflow/control_flow.py
  qiskit/converters/circuit_to_dag.py
  qiskit/converters/dag_to_circuit.py
  qiskit/dagcircuit/dagcircuit.py
  test/python/converters/test_circuit_to_dag.py
  test/python/dagcircuit/test_dagcircuit.py
Labels: Changelog: New Feature, mod: transpiler

#12207 Reject vars in `QuantumCircuit.to_instruction` and `to_gate`
  qiskit/converters/circuit_to_gate.py
  qiskit/converters/circuit_to_instruction.py
  test/python/converters/test_circuit_to_gate.py
  test/python/converters/test_circuit_to_instruction.py
Labels: Changelog: None, mod: circuit

#12215 Support `Var` in circuit-substitution methods
  crates/circuit/src/circuit_data.rs
  qiskit/circuit/_classical_resource_map.py
  qiskit/circuit/library/blueprintcircuit.py
  qiskit/circuit/quantumcircuit.py
  qiskit/dagcircuit/dagcircuit.py
  test/python/circuit/test_circuit_operations.py
  test/python/circuit/test_compose.py
  test/python/dagcircuit/test_compose.py
  test/python/dagcircuit/test_dagcircuit.py
Labels: Changelog: New Feature, mod: circuit

#12307 Add minimal support for standalone `Var` to visualisers
  qiskit/qasm3/ast.py
  qiskit/qasm3/exporter.py
  qiskit/qasm3/printer.py
  qiskit/visualization/circuit/matplotlib.py
  qiskit/visualization/circuit/text.py
  test/python/visualization/test_circuit_text_drawer.py
  test/visual/mpl/circuit/references/if_else_standalone_var.png
  test/visual/mpl/circuit/references/switch_standalone_var.png
  test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py
Labels: Changelog: New Feature, mod: visualization, mod: circuit

#12318 Restrict iteration of commutation passes to just qubits
  qiskit/transpiler/passes/optimization/commutation_analysis.py
  qiskit/transpiler/passes/optimization/commutative_cancellation.py
Labels: performance, Changelog: None, mod: transpiler

#12308 Support standalone `Var`s in OQ3 exporter
  qiskit/qasm3/exporter.py
  releasenotes/notes/qasm3-parameter-gate-clash-34ef7b0383849a78.yaml
  test/python/qasm3/test_export.py
Labels: Changelog: New Feature, mod: qasm3

#12326 Fix bugs in example of EstimatorV2
  qiskit/primitives/__init__.py
Labels: documentation, Changelog: None, mod: primitives

#12310 Add indexing and bitshift expressions
  qiskit/circuit/classical/expr/__init__.py
  qiskit/circuit/classical/expr/constructors.py
  qiskit/circuit/classical/expr/expr.py
  qiskit/circuit/classical/expr/visitors.py
  qiskit/qasm3/ast.py
  qiskit/qasm3/exporter.py
  qiskit/qasm3/printer.py
  qiskit/qpy/__init__.py
  qiskit/qpy/binary_io/circuits.py
  qiskit/qpy/binary_io/schedules.py
  qiskit/qpy/binary_io/value.py
  qiskit/qpy/type_keys.py
  releasenotes/notes/expr-bitshift-index-e9cfc6ea8729ef5e.yaml
  test/python/circuit/classical/test_expr_constructors.py
  test/python/circuit/classical/test_expr_helpers.py
  test/python/circuit/classical/test_expr_properties.py
  test/python/circuit/test_circuit_load_from_qpy.py
  test/python/circuit/test_store.py
  test/python/qasm3/test_export.py
  test/qpy_compat/test_qpy.py
Labels: Changelog: New Feature, mod: qpy, mod: qasm3, mod: circuit

#12312 Add equivalence library entry for swap to ECR or CZ
  qiskit/circuit/library/standard_gates/equivalence_library.py
  test/python/circuit/test_gate_definitions.py
  test/qpy_compat/test_qpy.py
Labels: performance, Changelog: None, mod: transpiler

#12322 Support standalone `Var` throughout transpiler
  qiskit/circuit/quantumcircuit.py
  qiskit/circuit/store.py
  qiskit/transpiler/passes/basis/basis_translator.py
  qiskit/transpiler/passes/basis/unroll_custom_definitions.py
  qiskit/transpiler/passes/layout/apply_layout.py
  qiskit/transpiler/passes/layout/sabre_layout.py
  qiskit/transpiler/passes/optimization/optimize_annotated.py
  qiskit/transpiler/passes/routing/stochastic_swap.py
  qiskit/transpiler/passes/synthesis/high_level_synthesis.py
  qiskit/transpiler/passes/utils/gates_basis.py
  test/python/circuit/test_circuit_operations.py
  test/python/compiler/test_transpiler.py
  test/python/transpiler/test_apply_layout.py
  test/python/transpiler/test_basis_translator.py
  test/python/transpiler/test_gates_in_basis_pass.py
  test/python/transpiler/test_high_level_synthesis.py
  test/python/transpiler/test_optimize_annotated.py
  test/python/transpiler/test_sabre_layout.py
  test/python/transpiler/test_stochastic_swap.py
  test/python/transpiler/test_unroll_custom_definitions.py
Labels: Changelog: New Feature, mod: transpiler, mod: circuit

#9523 Add ElidePermutations transpiler pass
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/layout/apply_layout.py
  qiskit/transpiler/passes/layout/set_layout.py
  qiskit/transpiler/passes/optimization/__init__.py
  qiskit/transpiler/passes/optimization/elide_permutations.py
  qiskit/transpiler/passmanager.py
  qiskit/transpiler/preset_passmanagers/builtin_plugins.py
  releasenotes/notes/add-elide-swaps-b0a4c373c9af1efd.yaml
  test/python/transpiler/test_elide_permutations.py
Labels: Changelog: New Feature, mod: transpiler

#12219 Update make_data_bin() to return DataBin proper
  qiskit/primitives/backend_estimator_v2.py
  qiskit/primitives/backend_sampler_v2.py
  qiskit/primitives/base/base_estimator.py
  qiskit/primitives/containers/data_bin.py
  qiskit/primitives/statevector_estimator.py
  qiskit/primitives/statevector_sampler.py
  releasenotes/notes/databin-construction-72ec041075410cb2.yaml
  test/python/primitives/containers/test_data_bin.py
  test/python/primitives/containers/test_primitive_result.py
  test/python/primitives/containers/test_pub_result.py
  test/python/primitives/test_backend_sampler_v2.py
  test/python/primitives/test_statevector_sampler.py
Labels: mod: primitives

#12158 Add enhancement to BitArray
  qiskit/primitives/containers/bit_array.py
  releasenotes/notes/add-bitarray-utilities-c85261138d5a1a97.yaml
  test/python/primitives/containers/test_bit_array.py
Labels: Changelog: New Feature, mod: primitives

#11387 Add star to linear pre-routing pass
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/routing/__init__.py
  qiskit/transpiler/passes/routing/star_prerouting.py
  releasenotes/notes/star-prerouting-0998b59880c20cef.yaml
  test/python/transpiler/test_star_prerouting.py
Labels: priority: high, Changelog: New Feature, mod: transpiler

#11811 Conjugate reduction in optimize annotated pass
  qiskit/dagcircuit/dagcircuit.py
  qiskit/transpiler/passes/optimization/optimize_annotated.py
  releasenotes/notes/optimize-annotated-conjugate-reduction-656438d3642f27dc.yaml
  test/python/transpiler/test_optimize_annotated.py
Labels: Changelog: New Feature, mod: transpiler

#12143 Add SamplerPubResult
  qiskit/primitives/backend_sampler_v2.py
  qiskit/primitives/base/base_sampler.py
  qiskit/primitives/containers/__init__.py
  qiskit/primitives/containers/pub_result.py
  qiskit/primitives/containers/sampler_pub_result.py
  qiskit/primitives/statevector_sampler.py
  releasenotes/notes/sampler-pub-result-e64e7de1bae2d35e.yaml
  test/python/primitives/containers/test_sampler_pub_result.py
Labels: mod: primitives

#12335 Fix composition of multiple virtual permutation layouts
  qiskit/transpiler/passes/optimization/elide_permutations.py
  qiskit/transpiler/passes/routing/star_prerouting.py
  test/python/transpiler/test_elide_permutations.py
Labels: Changelog: None

#12087 Adapt crates/qasm3 to work with recent versions of openqasm3_parser
  Cargo.lock
  crates/qasm3/Cargo.toml
  crates/qasm3/src/build.rs
  crates/qasm3/src/expr.rs
Labels: Changelog: None, mod: qasm3

#12331 Link to `qiskit.synthesis.unitary.aqc` on API index page
  docs/apidoc/index.rst
  docs/apidoc/qiskit.synthesis.unitary.aqc.rst
  qiskit/synthesis/__init__.py
Labels: documentation, stable backport potential, Changelog: None

#12338 Bump main branch version post 1.1.0rc1 tag
  .mergify.yml
  Cargo.lock
  Cargo.toml
  docs/conf.py
  qiskit/VERSION.txt
Labels: Changelog: None

#12340 Fix typo under 'pull request checklist' heading
  CONTRIBUTING.md
Labels: Community PR

#12218 Removing lint rule use-implicit-booleaness-not-comparison and updates
  pyproject.toml
  qiskit/pulse/instruction_schedule_map.py
  qiskit/synthesis/linear_phase/cnot_phase_synth.py
Labels: Community PR

#12325 Improve header hierarchy for API module pages
  qiskit/assembler/__init__.py
  qiskit/circuit/__init__.py
  qiskit/circuit/classical/types/__init__.py
  qiskit/circuit/classicalfunction/__init__.py
  qiskit/circuit/library/__init__.py
  qiskit/converters/__init__.py
  qiskit/providers/__init__.py
  qiskit/providers/basic_provider/__init__.py
  qiskit/providers/fake_provider/__init__.py
  qiskit/providers/models/__init__.py
  qiskit/qpy/__init__.py
  qiskit/result/__init__.py
  qiskit/scheduler/__init__.py
  qiskit/scheduler/methods/__init__.py
  qiskit/transpiler/passes/__init__.py
Labels: documentation, stable backport potential, Changelog: None

#12339 Fix Rustfmt and clippy with latest rust stable
  .cargo/config.toml
  crates/accelerate/src/sparse_pauli_op.rs
  crates/circuit/src/circuit_data.rs
  crates/qasm3/src/circuit.rs
Labels: Changelog: None, Rust

#12347 Add standalone test file for Clifford synthesis functions
  qiskit/circuit/library/generalized_gates/linear_function.py
  qiskit/circuit/library/generalized_gates/uc.py
  qiskit/circuit/library/generalized_gates/unitary.py
  qiskit/circuit/library/n_local/evolved_operator_ansatz.py
  qiskit/circuit/library/pauli_evolution.py
  qiskit/circuit/random/__init__.py
  qiskit/circuit/random/utils.py
  qiskit/quantum_info/operators/dihedral/random.py
  qiskit/synthesis/clifford/clifford_decompose_bm.py
  qiskit/synthesis/clifford/clifford_decompose_layers.py
  releasenotes/notes/add-random-clifford-util-5358041208729988.yaml
  test/python/quantum_info/operators/symplectic/test_clifford.py
  test/python/synthesis/test_clifford_sythesis.py
Labels: Changelog: None

#12358 docstring fixes
  qiskit/quantum_info/operators/symplectic/pauli.py
Labels: documentation, stable backport potential, Changelog: None

#12365 fix indentation in XXPlusYYGate docstring
  qiskit/circuit/library/standard_gates/xx_plus_yy.py
Labels: documentation, Changelog: None

#12178 Replace initialization method by Isometry in StatePreparation
  qiskit/circuit/library/data_preparation/initializer.py
  qiskit/circuit/library/data_preparation/state_preparation.py
  qiskit/circuit/library/generalized_gates/isometry.py
  qiskit/circuit/library/generalized_gates/mcg_up_to_diagonal.py
  qiskit/circuit/library/generalized_gates/uc.py
  qiskit/circuit/library/generalized_gates/uc_pauli_rot.py
  releasenotes/notes/replace-initialization-algorithm-by-isometry-41f9ffa58f72ece5.yaml
  test/benchmarks/statepreparation.py
Labels: performance, Changelog: New Feature, mod: circuit

#12147 Add new method for single bitstring target when measuring stabilizerstate probabilities_dict
  qiskit/quantum_info/states/stabilizerstate.py
  releasenotes/notes/outcome_bitstring_target_for_probabilities_dict-e53f524d115bbcfc.yaml
  test/python/quantum_info/states/test_stabilizerstate.py
Labels: Changelog: New Feature, mod: quantum info, Community PR

#12370 improve docstring of plot_circuit_layout
  qiskit/visualization/gate_map.py
Labels: documentation, stable backport potential, Changelog: None

#12369 fix edge coloring bug in plot_coupling_map
  qiskit/visualization/gate_map.py
  releasenotes/notes/plot-circuit-layout-5935646107893c12.yaml
Labels: stable backport potential, Changelog: Bugfix

#12333 Reorganize API index page into sections
  docs/apidoc/index.rst
Labels: documentation, stable backport potential, Changelog: None

#12376 Fix runtime scaling of StarPreRouting pass
  qiskit/transpiler/passes/routing/star_prerouting.py
Labels: stable backport potential, performance, Changelog: None, mod: transpiler

#12373 Removing unnecessary-dict-index-lookup lint rule and updates
  pyproject.toml
  qiskit/transpiler/target.py
Labels: type: qa, Changelog: None, Community PR

#12366 Removing consider-iterating-dictionary lint rule and updates
  pyproject.toml
  qiskit/circuit/library/n_local/pauli_two_design.py
  qiskit/pulse/parser.py
  qiskit/synthesis/discrete_basis/generate_basis_approximations.py
  qiskit/synthesis/discrete_basis/solovay_kitaev.py
  qiskit/transpiler/passes/synthesis/plugin.py
  qiskit/visualization/circuit/matplotlib.py
  qiskit/visualization/circuit/qcstyle.py
  test/python/transpiler/test_high_level_synthesis.py
Labels: type: qa, Changelog: None, Community PR

#12137 Fix missing layout in `Commuting2qGateRouter`
  qiskit/transpiler/passes/routing/commuting_2q_gate_routing/commuting_2q_gate_router.py
  releasenotes/notes/fix-swap-router-layout-f28cf0a2de7976a8.yaml
  test/python/transpiler/test_swap_strategy_router.py
Labels: stable backport potential, Changelog: Bugfix

#12288 Removing consider-using-dict-items from lint exclusions and updates
  SECURITY.md
  pyproject.toml
  qiskit/dagcircuit/collect_blocks.py
  qiskit/providers/basic_provider/basic_simulator.py
  qiskit/providers/models/backendconfiguration.py
  qiskit/providers/options.py
  qiskit/pulse/library/symbolic_pulses.py
  qiskit/result/models.py
  qiskit/result/result.py
  qiskit/transpiler/passes/optimization/collect_multiqubit_blocks.py
  qiskit/transpiler/target.py
  qiskit/visualization/circuit/latex.py
  qiskit/visualization/circuit/text.py
  test/python/primitives/test_backend_sampler_v2.py
  test/python/primitives/test_statevector_sampler.py
Labels: type: qa, Changelog: None, Community PR

#12304 Moving the unsupported-assignment-operation lint rule
  pyproject.toml
  qiskit/providers/options.py
Labels: type: qa, Changelog: None, Community PR

#12385 Fix {Pauli,SparsePauliOp}.apply_layout to raise an error with negative or duplicate indices
  qiskit/quantum_info/operators/symplectic/pauli.py
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
  releasenotes/notes/fix-apply-layout-duplicate-negative-indices-cf5517921fe52706.yaml
  test/python/quantum_info/operators/symplectic/test_pauli.py
  test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
Labels: stable backport potential, Changelog: Bugfix, mod: quantum info

#12356 Removing broad-exception-raised lint rule and updates
  pyproject.toml
  qiskit/quantum_info/quaternion.py
  qiskit/synthesis/clifford/clifford_decompose_bm.py
  qiskit/visualization/bloch.py
  qiskit/visualization/transition_visualization.py
  test/benchmarks/utils.py
  test/python/quantum_info/test_quaternions.py
  test/python/transpiler/test_preset_passmanagers.py
  test/python/transpiler/test_sabre_swap.py
  test/python/transpiler/test_stochastic_swap.py
Labels: type: qa, Changelog: None, Community PR

#12380 [DAGCircuit Oxidation] Port `DAGNode` to Rust
  crates/circuit/src/circuit_instruction.rs
  crates/circuit/src/dag_node.rs
  crates/circuit/src/lib.rs
  qiskit/dagcircuit/dagnode.py
Labels: Changelog: None, Rust, mod: circuit

#12396 Fix `QuantumCircuit.compose` with `Index` exprs
  qiskit/circuit/_classical_resource_map.py
  test/python/circuit/test_compose.py
Labels: stable backport potential, Changelog: None, mod: circuit

#12140 Handle huge integers in OpenQASM 2 expression evaluator
  crates/qasm2/src/expr.rs
  crates/qasm2/src/lex.rs
  releasenotes/notes/qasm2-bigint-8eff42acb67903e6.yaml
  test/python/qasm2/test_expression.py
Labels: stable backport potential, Changelog: Bugfix, mod: qasm2

#12375 Fix a corner case of `SparsePauliOp.apply_layout`
  qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
  releasenotes/notes/fix-sparse-pauli-op-apply-layout-zero-43b9e70f0d1536a6.yaml
  test/python/quantum_info/operators/symplectic/test_pauli.py
  test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
Labels: stable backport potential, Changelog: Bugfix, mod: quantum info

#12398 Fix two cross-references in `BasisTranslator` docstring
  qiskit/transpiler/passes/basis/basis_translator.py
Labels: documentation, stable backport potential, Changelog: None

#12406 export SamplerPubResult in qiskit.primitives module
  qiskit/primitives/__init__.py
Labels: Changelog: None, mod: primitives

#12410 Fix unnecessary serialisation of `PassManager` in serial contexts
  qiskit/passmanager/passmanager.py
  qiskit/utils/__init__.py
  qiskit/utils/parallel.py
  releasenotes/notes/parallel-check-8186a8f074774a1f.yaml
Labels: stable backport potential, Changelog: Bugfix, mod: transpiler

#12392 Avoid lossing precision when scaling frequencies
  qiskit/qobj/converters/pulse_instruction.py
  releasenotes/notes/fix-symbolic-unit-scaling-c3eb4d9be674dfd6.yaml
Labels: stable backport potential, Changelog: Bugfix, Community PR

#12403 Write complete manual `QuantumCircuit` documentation
  docs/apidoc/index.rst
  docs/apidoc/qiskit.circuit.QuantumCircuit.rst
  qiskit/circuit/__init__.py
  qiskit/circuit/quantumcircuit.py
Labels: documentation, stable backport potential, Changelog: None, mod: circuit

#12421 Add release notes for manual `Var` and `Store`
  qiskit/circuit/classical/expr/__init__.py
  qiskit/providers/__init__.py
  releasenotes/notes/1.1/classical-store-e64ee1286219a862.yaml
  releasenotes/notes/storage-var-a00a33fcf9a71f3f.yaml
Labels: Changelog: None

#12371 Prepare 1.1.0 release
  docs/conf.py
  docs/release_notes.rst
  qiskit/VERSION.txt
  qiskit/circuit/classical/expr/__init__.py
  qiskit/primitives/__init__.py
  qiskit/primitives/containers/__init__.py
  qiskit/primitives/containers/bit_array.py
  qiskit/primitives/containers/shape.py
  qiskit/providers/__init__.py
  releasenotes/notes/1.0/primitives-v2-df871c0c6ac0b94a.yaml
  releasenotes/notes/1.1/abstract-commutation-analysis-3518129e91a33599.yaml
  releasenotes/notes/1.1/add-annotated-arg-to-power-4afe90e89fa50f5a.yaml
  releasenotes/notes/1.1/add-backend-estimator-v2-26cf14a3612bb81a.yaml
  releasenotes/notes/1.1/add-backend-sampler-v2-5e40135781eebc7f.yaml
  releasenotes/notes/1.1/add-ctrl_state-mcp-parameter-b23562aa7047665a.yaml
  releasenotes/notes/1.1/add-elide-permutations-to-pipeline-077dad03bd55ab9c.yaml
  releasenotes/notes/1.1/add-elide-swaps-b0a4c373c9af1efd.yaml
  releasenotes/notes/1.1/add-linear-plugin-options-b8a0ffe70dfe1676.yaml
  releasenotes/notes/1.1/add-run-all-plugins-option-ba8806a269e5713c.yaml
  releasenotes/notes/1.1/added-parameter-ctrl_state-mcx-816dcd80e459a5ed.yaml
  releasenotes/notes/1.1/classical-store-e64ee1286219a862.yaml
  releasenotes/notes/1.1/commutation-checker-utf8-47b13b78a40af196.yaml
  releasenotes/notes/1.1/commutative-cancellation-preset-passmanager-c137ce516a10eae5.yaml
  releasenotes/notes/1.1/databin-construction-72ec041075410cb2.yaml
  releasenotes/notes/1.1/deprecate_providerV1-ba17d7b4639d1cc5.yaml
  releasenotes/notes/1.1/faster-lie-trotter-ba8f6dd84fe4cae4.yaml
  releasenotes/notes/1.1/fix-apply-layout-duplicate-negative-indices-cf5517921fe52706.yaml
  releasenotes/notes/1.1/fix-control-flow-fold-minus-one-f2af168a5313385f.yaml
  releasenotes/notes/1.1/fix-custom-pulse-qobj-conversion-5d6041b36356cfd1.yaml
  releasenotes/notes/1.1/fix-pub-coerce-5d13700e15126421.yaml
  releasenotes/notes/1.1/fix-pulse-builder-default-alingment-52f81224d90c21e2.yaml
  releasenotes/notes/1.1/fix-pulse-parameter-formatter-2ee3fb91efb2794c.yaml
  releasenotes/notes/1.1/fix-qdrift-evolution-bceb9c4f182ab0f5.yaml
  releasenotes/notes/1.1/fix-scheduling-units-59477912b47d3dc1.yaml
  releasenotes/notes/1.1/fix-sparse-pauli-op-apply-layout-zero-43b9e70f0d1536a6.yaml
  releasenotes/notes/1.1/fix-swap-router-layout-f28cf0a2de7976a8.yaml
  releasenotes/notes/1.1/fix-symbolic-unit-scaling-c3eb4d9be674dfd6.yaml
  releasenotes/notes/1.1/fixes_10852-e197344c5f44b4f1.yaml
  releasenotes/notes/1.1/fixes_11212-d6de3c007ce6d697.yaml
  releasenotes/notes/1.1/layout-compose-0b9a9a72359638d8.yaml
  releasenotes/notes/1.1/numpy-2.0-2f3e35bd42c48518.yaml
  releasenotes/notes/1.1/obs-array-coerce-0d-28b192fb3d004d4a.yaml
  releasenotes/notes/1.1/operator-from-circuit-bugfix-5dab5993526a2b0a.yaml
  releasenotes/notes/1.1/optimize-annotated-conjugate-reduction-656438d3642f27dc.yaml
  releasenotes/notes/1.1/parallel-check-8186a8f074774a1f.yaml
  releasenotes/notes/1.1/parameter-hash-eq-645f9de55aa78d02.yaml
  releasenotes/notes/1.1/parameter_assignment_by_name_for_pulse_schedules-3a27bbbbf235fb9e.yaml
  releasenotes/notes/1.1/pauli-apply-layout-cdcbc1bce724a150.yaml
  releasenotes/notes/1.1/plot-circuit-layout-5935646107893c12.yaml
  releasenotes/notes/1.1/prepare-1.1.0-732e167b70ab4d01.yaml
  releasenotes/notes/1.1/qasm2-bigint-8eff42acb67903e6.yaml
  releasenotes/notes/1.1/remove-final-reset-488247c01c4e147d.yaml
  releasenotes/notes/1.1/rework-inst-durations-passes-28c78401682e22c0.yaml
  releasenotes/notes/1.1/show_idle_and_show_barrier-6e77e1f9d6f55599.yaml
  releasenotes/notes/1.1/spo-to-matrix-26445a791e24f62a.yaml
  releasenotes/notes/1.1/star-prerouting-0998b59880c20cef.yaml
  releasenotes/notes/1.1/storage-var-a00a33fcf9a71f3f.yaml
  releasenotes/notes/fix-apply-layout-duplicate-negative-indices-cf5517921fe52706.yaml
  releasenotes/notes/parallel-check-8186a8f074774a1f.yaml
  releasenotes/notes/plot-circuit-layout-5935646107893c12.yaml
Labels: Changelog: None

#12394 Fix `qiskit.circuit` method header and broken cross-reference
  qiskit/circuit/__init__.py
Labels: documentation, stable backport potential, Changelog: None, Intern PR

#12428 Add merge queue to required tests on github actions
  .github/workflows/tests.yml
Labels: type: qa, stable backport potential, Changelog: None

#12434 Add missing parenthesis to pauli_feature_map.py
  qiskit/circuit/library/data_preparation/pauli_feature_map.py
Labels: documentation, stable backport potential, Changelog: None

#12321 add insert_barrier argument to UnitaryOverlap
  qiskit/circuit/library/overlap.py
  test/python/circuit/library/test_overlap.py
Labels: Changelog: New Feature, mod: circuit

#12446 Remove the duplicated docs for a `BackendV1` classmethod (backport #12443)
  qiskit/providers/backend.py
Labels: documentation, Changelog: None, Community PR

#12448 Remove reference to `transpile` from Pulse docs
  qiskit/pulse/builder.py
Labels: documentation, mod: pulse, Changelog: None

#12104 Expose internal rust interface to DenseLayout
  crates/accelerate/src/dense_layout.rs
Labels: priority: low, Changelog: None, Rust

#12453 Add `DenseLayout` trial to `SabreLayout`
  crates/accelerate/src/sabre/layout.rs
Labels: on hold, performance, Changelog: New Feature, Rust, mod: transpiler

#12469 Fix a bug in isometry.rs
  crates/accelerate/src/isometry.rs
  releasenotes/notes/fix-isometry-rust-adf0eed09c6611f1.yaml
  test/python/circuit/test_controlled_gate.py
Labels: stable backport potential, Changelog: Bugfix, Rust

#12191 Removing _name attribute from Parameter
  qiskit/circuit/parameter.py
Labels: Changelog: None, Community PR, refactor

#12482 Disable Neko on the extended support branch (stable/0.46)
  .github/workflows/neko.yml
Labels: type: qa, Changelog: None

#12185 Update `transpile()` and `generate_preset_pass_manager` to convert loose input of constraints to a `Target` with `Target.from_configuration()`
  qiskit/compiler/transpiler.py
  qiskit/transpiler/preset_passmanagers/__init__.py
  qiskit/transpiler/target.py
  releasenotes/notes/use-target-in-generate-preset-pm-5215e00d22d0205c.yaml
  test/python/compiler/test_transpiler.py
  test/python/transpiler/test_sabre_swap.py
  test/python/transpiler/test_stochastic_swap.py
Labels: Changelog: New Feature
