Repository Qiskit/qiskit, pull requests merged in 2025-05, with the labels that each got.

#14278 Fix display of Box End after transpile in text drawer
  qiskit/visualization/circuit/text.py
  releasenotes/notes/draw-control-flow-end-ceb58ed2c46ff758.yaml
  test/python/visualization/test_circuit_text_drawer.py
Labels: stable backport potential, Changelog: Bugfix, mod: visualization

#14281 fixed unescaped quotes in README.md example code
  README.md
Labels: stable backport potential, Changelog: None, Community PR

#14293 Update visualization tests to new pydot version
  constraints.txt
  test/python/visualization/references/pass_manager_standard.dot
  test/python/visualization/references/pass_manager_style.dot
Labels: Changelog: None

#14217 Bug fixes in Solovay Kitaev Decomposition
  qiskit/synthesis/discrete_basis/commutator_decompose.py
  qiskit/synthesis/discrete_basis/gate_sequence.py
  qiskit/synthesis/discrete_basis/generate_basis_approximations.py
  qiskit/synthesis/discrete_basis/solovay_kitaev.py
  releasenotes/notes/fix-sk-decomposition-23da3ee4b6a10d62.yaml
  test/python/transpiler/test_solovay_kitaev.py
Labels: stable backport potential, Changelog: Bugfix

#14296 Use ahash for hashing everywhere with IndexMap
  crates/accelerate/src/equivalence.rs
  crates/accelerate/src/sparse_observable/mod.rs
  crates/accelerate/src/synthesis/clifford/greedy_synthesis.rs
  crates/accelerate/src/target_transpiler/mod.rs
  crates/accelerate/src/unitary_synthesis.rs
  crates/circuit/src/dag_circuit.rs
Labels: performance, Changelog: None, Rust

#14301 Update comment about PackedOperation for StandardGate
  crates/circuit/src/packed_instruction.rs
Labels: Changelog: None, Rust

#14218 Fix incorrect error estimation in VF2 fallback
  qiskit/transpiler/passes/layout/vf2_utils.py
  releasenotes/notes/vf2-fallback-98550f601432a37b.yaml
Labels: stable backport potential, Changelog: Bugfix, mod: transpiler

#13975 Ancilla-Free Quantum Adder with Sublinear Depth
  pyproject.toml
  qiskit/circuit/library/arithmetic/adders/adder.py
  qiskit/synthesis/__init__.py
  qiskit/synthesis/arithmetic/__init__.py
  qiskit/synthesis/arithmetic/adders/__init__.py
  qiskit/synthesis/arithmetic/adders/rv_ripple_carry_adder.py
  qiskit/transpiler/passes/synthesis/hls_plugins.py
  releasenotes/notes/add-new-half-adder-6532be58252b2a86.yaml
  test/python/circuit/library/test_adders.py
  test/python/circuit/library/test_multipliers.py
Labels: Changelog: New Feature, synthesis, Community PR, mod: circuit

#14323 Pin ``snowballstemmer<3.0.0``
  constraints.txt
Labels: type: qa, Changelog: None

#14314 Add C API function to move a QkCircuit to Python
  crates/cext/src/circuit.rs
Labels: Changelog: None, C API

#14046 Add ctest execution to coverage reporting
  .github/workflows/coverage.yml
  CMakeLists.txt
  Makefile
Labels: type: qa, Changelog: None, C API

#14330 Fix alignment checks of `stretch` variables
  qiskit/transpiler/passes/scheduling/alignments/check_durations.py
  releasenotes/notes/stretch-duration-alignments-cd8395bcc8f6cdd0.yaml
  test/python/compiler/test_transpiler.py
Labels: stable backport potential, Changelog: Bugfix, mod: transpiler

#14246 Add Rust tests to the coverage collection
  .github/workflows/coverage.yml
Labels: type: qa, Changelog: None, Rust

#14273 C-API: Add fix for Windows and C++
  Makefile
  crates/cext/cbindgen.toml
  releasenotes/notes/fix-c-api-for-windows-and-cpp-0b8d79cd3fcf975a.yaml
Labels: Changelog: New Feature, Changelog: Bugfix, C API

#14336 Improving numerical errors in cossin decomposition
  crates/accelerate/src/cos_sin_decomp.rs
Labels: Changelog: None, synthesis, Rust

#14337 Prepare 1.4.3
  Cargo.lock
  Cargo.toml
  docs/conf.py
  qiskit/VERSION.txt
  releasenotes/notes/prepare-1.4.3-5595d66661012aaf.yaml
Labels: Changelog: None

#14341 Bump ahash to 0.8.12 on `qiskit_transpiler`
  Cargo.lock
Labels: dependencies

#14259 Improve QkCircuit C API docs
  crates/cext/src/circuit.rs
  docs/cdoc/index.h
  docs/cdoc/index.rst
  docs/cdoc/qk-circuit.rst
Labels: documentation, priority: high, Changelog: None

#14345 Fix UnitarySynthesis to respect synth_gates
  crates/transpiler/src/passes/unitary_synthesis.rs
  qiskit/transpiler/passes/synthesis/unitary_synthesis.py
  releasenotes/notes/fix-UnitarySynthesis-synth_gates-4e084db18ece8bfe.yaml
  test/python/transpiler/test_solovay_kitaev.py
  test/python/transpiler/test_unitary_synthesis.py
Labels: stable backport potential, Changelog: Bugfix, synthesis, Community PR

#14313 Remove py token from dag methods
  crates/circuit/src/converters.rs
  crates/circuit/src/dag_circuit.rs
  crates/transpiler/src/passes/barrier_before_final_measurement.rs
  crates/transpiler/src/passes/basis_translator/compose_transforms.rs
  crates/transpiler/src/passes/basis_translator/mod.rs
  crates/transpiler/src/passes/elide_permutations.rs
  crates/transpiler/src/passes/gate_direction.rs
  crates/transpiler/src/passes/high_level_synthesis.rs
  crates/transpiler/src/passes/split_2q_unitaries.rs
  crates/transpiler/src/passes/unitary_synthesis.rs
  crates/transpiler/src/target/mod.rs
Labels: Changelog: None, Rust

#14349 Bug fix in HighLevelSynthesis fast-return mechanism
  crates/transpiler/src/passes/high_level_synthesis.rs
  releasenotes/notes/fix-hls-fast-return-6daff39a5eba40ce.yaml
  test/python/transpiler/test_high_level_synthesis.py
Labels: stable backport potential, Changelog: Bugfix

#14352 Fix accidentally disjoint test
  test/python/compiler/test_transpiler.py
Labels: type: qa, Changelog: None

#14177 Port disjoint layout utils in rust
  Cargo.lock
  crates/circuit/src/bit.rs
  crates/pyext/src/lib.rs
  crates/transpiler/Cargo.toml
  crates/transpiler/src/passes/disjoint_layout.rs
  crates/transpiler/src/passes/mod.rs
  qiskit/__init__.py
  qiskit/transpiler/passes/layout/dense_layout.py
  qiskit/transpiler/passes/layout/disjoint_utils.py
  qiskit/transpiler/passes/layout/sabre_layout.py
  test/python/transpiler/test_sabre_layout.py
Labels: Changelog: None, Rust

#14363 Fix construction of IQP circuits
  crates/accelerate/src/circuit_library/iqp.rs
  releasenotes/notes/fix-iqp-203557797d0d448e.yaml
  test/python/circuit/library/test_iqp.py
Labels: Changelog: Bugfix

#14366 Avoid unecessary cloning in disjoint layout Python path
  crates/transpiler/src/passes/disjoint_layout.rs
Labels: performance, Changelog: None, Rust

#14370 Remove unused build dep pyo3-build-config on qiskit-cext
  Cargo.lock
  crates/cext/Cargo.toml
Labels: Changelog: None, Rust, C API

#14378 Fix new clippy warning in Rust 1.87
  crates/accelerate/src/sparse_observable/mod.rs
Labels: Changelog: None

#14380 Add missing links to `QuantumCircuit` stretch docs.
  qiskit/circuit/quantumcircuit.py
Labels: documentation, stable backport potential, Changelog: None

#14339 Prepare 2.0.1
  Cargo.lock
  Cargo.toml
  docs/conf.py
  qiskit/VERSION.txt
  releasenotes/notes/fix-duration-props-0543fe1d5e6e2820.yaml
  releasenotes/notes/fix-hls-fast-return-6daff39a5eba40ce.yaml
  releasenotes/notes/fix-sk-basis-set-2d90a4fa7aaa78b2.yaml
  releasenotes/notes/prepare-2.0.1-6af6a447bbc7d260.yaml
Labels: Changelog: None

#13278 Add ParameterExpression in Rust
  Cargo.lock
  Cargo.toml
  crates/circuit/Cargo.toml
  crates/circuit/src/lib.rs
  crates/circuit/src/parameter_expression.rs
  crates/circuit/src/symbol_expr.rs
  crates/circuit/src/symbol_parser.rs
  qiskit/circuit/parameter.py
  qiskit/circuit/parameterexpression.py
  qiskit/circuit/tools/pi_check.py
  qiskit/qpy/binary_io/value.py
  qiskit/transpiler/passes/optimization/template_matching/template_substitution.py
  qiskit/utils/optionals.py
  releasenotes/notes/parameter-expression-rs-6fddbb2556b7e1f7.yaml
  test/python/circuit/test_parameter_expression.py
  test/python/circuit/test_parameters.py
  test/python/circuit/test_tools.py
  test/python/qasm3/test_export.py
  test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
  test/python/transpiler/test_template_matching.py
Labels: priority: high, Changelog: New Feature, Rust

#14392 Fix clippy issues with latest clippy in parameter expression
  crates/circuit/src/parameter_expression.rs
  crates/circuit/src/symbol_expr.rs
Labels: Changelog: None, Rust

#14381 Revert "Port star_preroute to rust"
  crates/pyext/src/lib.rs
  crates/transpiler/src/passes/mod.rs
  crates/transpiler/src/passes/star_prerouting.rs
  qiskit/__init__.py
  qiskit/transpiler/passes/routing/star_prerouting.py
Labels: Changelog: None, mod: transpiler

#14353 Do not construct layout passes with no coupling map
  qiskit/transpiler/preset_passmanagers/builtin_plugins.py
  releasenotes/notes/no-layout-presets-87e0bcde698f002e.yaml
Labels: Changelog: API Change, mod: transpiler

#14120 Added VF2PostLayout at the end of optimization stage for level 3
  qiskit/transpiler/preset_passmanagers/builtin_plugins.py
  qiskit/transpiler/preset_passmanagers/level3.py
  releasenotes/notes/add-vf2postlayout-optimization-level-3-89ff6f484f7b7578.yaml
Labels: Community PR

#14399 Bump PyO3 and rust-numpy
  Cargo.lock
  Cargo.toml
  crates/transpiler/src/passes/high_level_synthesis.rs
Labels: Changelog: None, Rust, dependencies

#14395 Remove dateutil as a requirement
  releasenotes/notes/no-dateutil-ca2ca5f5a75fbb22.yaml
  requirements.txt
Labels: Changelog: API Change

#14408 Update intersphinx mapping URLs
  docs/conf.py
Labels: documentation, Changelog: None

#14225 Clifford+T transpiler pipeline
  qiskit/circuit/library/standard_gates/equivalence_library.py
  qiskit/quantum_info/__init__.py
  qiskit/quantum_info/operators/__init__.py
  qiskit/quantum_info/operators/symplectic/__init__.py
  qiskit/quantum_info/operators/symplectic/clifford_circuits.py
  qiskit/transpiler/__init__.py
  qiskit/transpiler/passmanager_config.py
  qiskit/transpiler/preset_passmanagers/builtin_plugins.py
  qiskit/transpiler/preset_passmanagers/common.py
  qiskit/transpiler/preset_passmanagers/generate_preset_pass_manager.py
  releasenotes/notes/add-clifford-t-transpiler-pipeline-e640b5ba64eab13a.yaml
  test/python/transpiler/test_clifford_t_passmanager.py
  test/python/transpiler/test_solovay_kitaev.py
Labels: Changelog: New Feature

#14417 Fix ConsolidateBlocks pass for collecting non-CX KAK gate
  qiskit/transpiler/passes/optimization/consolidate_blocks.py
  releasenotes/notes/fix-consolidate-blocks-e2421dd2408403eb.yaml
  test/python/transpiler/test_consolidate_blocks.py
Labels: priority: high, stable backport potential, Changelog: Bugfix, mod: transpiler

#14419 Remove test with a 5-year-old unconditional skip
  test/python/circuit/library/test_nlocal.py
Labels: type: qa, Changelog: None

#13688 block diagonal optimized quantum shannon decomposition
  crates/accelerate/src/cos_sin_decomp.rs
  qiskit/circuit/library/generalized_gates/unitary.py
  qiskit/synthesis/unitary/qsd.py
  releasenotes/notes/improve-controlled-UnitaryGate-5f3aa3d44034cfa7.yaml
  test/python/circuit/test_controlled_gate.py
  test/python/synthesis/test_qsd_synthesis.py
  test/python/synthesis/test_synthesis.py
Labels: synthesis

#14391 Avoid using string parsing for ParameterExpression.sympify()
  crates/circuit/src/parameter_expression.rs
  crates/circuit/src/symbol_expr.rs
  qiskit/circuit/parameter.py
  qiskit/circuit/parameterexpression.py
  test/python/circuit/test_parameter_expression.py
Labels: Changelog: None

#14389 Remove symengine from the requirements list
  pyproject.toml
  qiskit/qpy/binary_io/schedules.py
  releasenotes/notes/parameter-expression-rs-6fddbb2556b7e1f7.yaml
  requirements.txt
  test/python/qpy/test_circuit_load_from_qpy.py
  test/qpy_compat/run_tests.sh
Labels: Changelog: API Change

#14431 Fix more spurious complex parts in circuit functions
  qiskit/circuit/library/n_local/evolved_operator_ansatz.py
  releasenotes/notes/spurious-complex-b926da41d051e63a.yaml
  test/python/circuit/library/test_evolved_op_ansatz.py
  test/python/circuit/library/test_qaoa_ansatz.py
Labels: stable backport potential, Changelog: Bugfix, mod: circuit

#14374 Remove DT from C API for adding delays
  crates/cext/src/circuit.rs
  releasenotes/notes/add-delay-c-api-d040c3f8b60b295b.yaml
  test/c/test_circuit.c
Labels: Changelog: None, C API

#13474 Migrate CI to Github Actions
  .azure/lint_docs-linux.yml
  .azure/test-linux.yml
  .azure/test-macos.yml
  .azure/test-windows.yml
  .github/workflows/image-tests.yml
  .github/workflows/lint_docs.yml
  .github/workflows/on-merge-queue.yml
  .github/workflows/on-nightly.yml
  .github/workflows/on-pull-request.yml
  .github/workflows/on-push.yml
  .github/workflows/rust-tests.yml
  .github/workflows/test-linux.yml
  .github/workflows/test-mac.yml
  .github/workflows/test-windows.yml
  .github/workflows/tests.yml
  azure-pipelines.yml
Labels: type: qa, Changelog: None

#14436 Fixed AND terms for OR in `quantum_or.py`
  qiskit/circuit/library/boolean_logic/quantum_or.py
  releasenotes/notes/fix-calling-OR-gate-as-AND-f1b364d04734098d.yaml
Labels: stable backport potential, Changelog: Bugfix, Community PR

#14463 Pre-allocate bits storage in CircuitData::new
  crates/circuit/src/circuit_data.rs
Labels: performance, Changelog: None, Rust

#14020 `SingleQubitOperation` trait and speedup to `Optimize1qGatesDecomposition` pass
  crates/circuit/src/circuit_instruction.rs
  crates/circuit/src/operations.rs
  crates/circuit/src/packed_instruction.rs
  crates/transpiler/src/passes/optimize_1q_gates_decomposition.rs
  test/python/transpiler/test_optimize_1q_decomposition.py
Labels: performance, Rust

#14476 Remove wasm dependencies via uuid
  Cargo.lock
  Cargo.toml
Labels: Changelog: None, Rust, dependencies

#14226 Implementation of a Limited QASM3 Exporter except controlflow and Classical Variables in Rust
  Cargo.lock
  crates/circuit/src/bit.rs
  crates/qasm3/Cargo.toml
  crates/qasm3/src/ast.rs
  crates/qasm3/src/exporter.rs
  crates/qasm3/src/lib.rs
  crates/qasm3/src/printer.rs
  qiskit/qasm3/__init__.py
  qiskit/qasm3/exporter.py
  test/python/qasm3/test_export.py
Labels: priority: high, performance, Changelog: New Feature, Rust, mod: qasm3

#14433 CliffordT optimization
  qiskit/transpiler/passes/__init__.py
  qiskit/transpiler/passes/optimization/__init__.py
  qiskit/transpiler/passes/optimization/optimize_clifford_t.py
  qiskit/transpiler/preset_passmanagers/builtin_plugins.py
  releasenotes/notes/clifford-t-optimization-cf60aad9b106820e.yaml
  test/python/transpiler/test_optimize_clifford_t.py
Labels: Changelog: New Feature, mod: transpiler

#14483 Avoid all-to-all connectivity in slowest test
  test/python/compiler/test_transpiler.py
Labels: type: qa, stable backport potential, Changelog: None

#14334 Add ``qk_circuit_unitary``
  Cargo.lock
  crates/cext/Cargo.toml
  crates/cext/src/circuit.rs
  crates/cext/src/exit_codes.rs
  test/c/test_circuit.c
Labels: Changelog: None, Community PR, C API

#14488 Fix Sabre rebuild with nested `Var` and `Stretch`
  qiskit/transpiler/passes/routing/sabre_swap.py
  releasenotes/notes/fix-sabre-inner-vars-409448505fd56ca7.yaml
  test/python/transpiler/test_sabre_swap.py
Labels: stable backport potential, Changelog: Bugfix

#14490 Add `PackedInstruction::from_standard_gate`
  crates/accelerate/src/twirling.rs
  crates/circuit/src/circuit_data.rs
  crates/circuit/src/dag_circuit.rs
  crates/circuit/src/interner.rs
  crates/circuit/src/packed_instruction.rs
Labels: Changelog: None, Rust

#14481 Integrate C API tests into new GHA workflow structure
  .github/workflows/ctests.yml
  .github/workflows/on-merge-queue.yml
  .github/workflows/on-pull-request.yml
Labels: type: qa, Changelog: None

#14497 Add `--slowest` flag to stestr run in CI
  .github/workflows/slow.yml
  .github/workflows/test-linux.yml
  .github/workflows/test-mac.yml
  .github/workflows/test-windows.yml
Labels: type: qa, Changelog: None

#14495 Improve minor `DAGCircuit` internal-Rust interfaces
  crates/circuit/src/dag_circuit.rs
Labels: Changelog: None, Rust

#14484 Tidy up unnecessary all-to-all tests
  test/python/compiler/test_transpiler.py
  test/python/qpy/test_circuit_load_from_qpy.py
  test/python/transpiler/test_passmanager_config.py
Labels: type: qa, Changelog: None

#14458 Improve Sabre heuristic defaults
  qiskit/transpiler/passes/layout/sabre_layout.py
  qiskit/transpiler/passes/routing/sabre_swap.py
  releasenotes/notes/sabre-better-defaults-1d933690c44bfec6.yaml
  test/python/transpiler/test_sabre_swap.py
Labels: performance, Changelog: API Change, mod: transpiler

#14486 Fix QPY test of `use_symengine` if Symengine is available
  test/python/qpy/test_circuit_load_from_qpy.py
Labels: type: qa, stable backport potential, Changelog: None

#14275 Remove unexecutable code path in InstructionDurations
  qiskit/transpiler/instruction_durations.py
Labels: Changelog: None, mod: transpiler

#13253 Change style of DAG generated in dag_drawer()
  MANIFEST.in
  qiskit/visualization/circuit/latex.py
  qiskit/visualization/circuit/matplotlib.py
  qiskit/visualization/circuit/qcstyle.py
  qiskit/visualization/dag/__init__.py
  qiskit/visualization/dag/dagstyle.py
  qiskit/visualization/dag/styles/__init__.py
  qiskit/visualization/dag/styles/color.json
  qiskit/visualization/dag/styles/plain.json
  qiskit/visualization/dag_visualization.py
  qiskit/visualization/style.py
  releasenotes/notes/dag_drawer_custom_style-ec99bd874858f6a6.yaml
  test/python/visualization/test_dag_drawer.py
Labels: Changelog: New Feature, mod: visualization

#14283 Add QubitSparsePauli and QubitSparsePauliList classes to quantum_info
  crates/pyext/src/lib.rs
  crates/quantum_info/src/lib.rs
  crates/quantum_info/src/pauli_lindblad_map/mod.rs
  crates/quantum_info/src/pauli_lindblad_map/qubit_sparse_pauli.rs
  crates/quantum_info/src/sparse_observable/mod.rs
  qiskit/__init__.py
  qiskit/circuit/library/pauli_evolution.py
  qiskit/circuit/quantumcircuitdata.py
  qiskit/primitives/__init__.py
  qiskit/primitives/base/base_estimator.py
  qiskit/quantum_info/__init__.py
  qiskit/quantum_info/operators/symplectic/pauli.py
  qiskit/result/sampled_expval.py
  qiskit/synthesis/evolution/lie_trotter.py
  qiskit/synthesis/evolution/product_formula.py
  qiskit/synthesis/evolution/qdrift.py
  qiskit/synthesis/evolution/suzuki_trotter.py
  releasenotes/notes/0.20/fix_stabilizerstate_expval-2556c5ee916f5327.yaml
  releasenotes/notes/0.21/remove-deprecate-calsses-methods-7bd69606cc4ad61f.yaml
  releasenotes/notes/0.22/sampled_expval-85e300e0fb5fa5ea.yaml
  releasenotes/notes/0.24/fix-empty-pauli-label-ce2580584db67a4d.yaml
  releasenotes/notes/0.24/paulilist-do-not-broadcast-from-paulis-96de3832fba21b94.yaml
  releasenotes/notes/0.45/fix_pauli_new_style_bit-0704933127b4debe.yaml
  releasenotes/notes/0.45/remove_8070-09b64e3a2aca1c2d.yaml
  releasenotes/notes/1.1/pauli-apply-layout-cdcbc1bce724a150.yaml
  test/python/quantum_info/test_qubit_sparse_pauli.py
Labels: Changelog: New Feature, mod: quantum info, mod: primitives

#14423 Added support for querying version information in the Qiskit C API.
  crates/cext/cbindgen.toml
  releasenotes/notes/c-api-version-support-55b018bf9552db1f.yaml
  test/c/test_version_info.c
Labels: Changelog: New Feature, Intern PR, C API

#14394 Update synth_mcx_kg24 to use relative phase Toffolis
  qiskit/synthesis/multi_controlled/mcx_synthesis.py
  qiskit/transpiler/passes/synthesis/hls_plugins.py
  releasenotes/notes/add-new-mcx-plugins-2177db9195e2b680.yaml
  test/python/synthesis/test_multi_controlled_synthesis.py
Labels: Changelog: None, synthesis, Community PR
