Repository Qiskit/qiskit, pull requests merged in 2025-06, with the labels that each got.

#14509 Reapply "Add ``qk_circuit_unitary`` (#14334)" (#14492)
  Cargo.lock
  crates/cext/Cargo.toml
  crates/cext/src/circuit.rs
  crates/cext/src/exit_codes.rs
  test/c/test_circuit.c
Labels: Changelog: None, C API

#14519 Remove trailing function declaration in C tests
  test/c/common.h
Labels: Changelog: None, C API

#14396 Remove sympy as a hard dependency
  pyproject.toml
  qiskit/qpy/binary_io/parse_sympy_repr.py
  releasenotes/notes/no-sympy-19687d5ca814042c.yaml
  requirements-optional.txt
  requirements.txt
  test/python/circuit/library/test_evolution_gate.py
  test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
  test/python/quantum_info/operators/test_operator.py
  test/python/quantum_info/states/test_statevector.py
  test/python/transpiler/test_template_matching.py
  test/python/visualization/test_state_latex_drawer.py
  test/python/visualization/test_utils.py
  test/qpy_compat/run_tests.sh
Labels: Changelog: API Change

#14212 added get_qpy_version to retrieve qpy version
  qiskit/qpy/__init__.py
  qiskit/qpy/interface.py
  releasenotes/notes/get_qpy_version-75791c063af4e851.yaml
  test/python/qpy/test_circuit_load_from_qpy.py
Labels: Changelog: New Feature, mod: qpy, Community PR

#14203 Oxidize the Solovay Kitaev algorithm
  Cargo.lock
  crates/accelerate/Cargo.toml
  crates/synthesis/Cargo.toml
  crates/synthesis/src/discrete_basis/basic_approximations.rs
  crates/synthesis/src/discrete_basis/math.rs
  crates/synthesis/src/discrete_basis/mod.rs
  crates/synthesis/src/discrete_basis/solovay_kitaev.rs
  crates/synthesis/src/lib.rs
  qiskit/__init__.py
  qiskit/synthesis/discrete_basis/commutator_decompose.py
  qiskit/synthesis/discrete_basis/gate_sequence.py
  qiskit/synthesis/discrete_basis/generate_basis_approximations.py
  qiskit/synthesis/discrete_basis/solovay_kitaev.py
  qiskit/transpiler/passes/synthesis/solovay_kitaev_synthesis.py
  releasenotes/notes/sk-rust-cfd5b85115e7e858.yaml
  test/python/transpiler/test_solovay_kitaev.py
Labels: performance, Changelog: New Feature, Changelog: Bugfix, synthesis, Rust

#13929 Porting some of the MCX synthesis methods to Rust
  crates/circuit/src/imports.rs
  crates/synthesis/src/multi_controlled/mcx.rs
  crates/synthesis/src/multi_controlled/mod.rs
  qiskit/synthesis/multi_controlled/mcx_synthesis.py
  test/python/circuit/test_circuit_qasm.py
  test/python/qasm2/test_export.py
  test/python/transpiler/test_decompose.py
Labels: synthesis, Rust

#14525 Use a double quote header for complex.h
  crates/cext/cbindgen.toml
Labels: Changelog: None, C API

#14526 Fix qiskit-synthesis crate standalone builds
  crates/synthesis/Cargo.toml
  crates/synthesis/src/discrete_basis/basic_approximations.rs
  crates/synthesis/src/multi_controlled/mcx.rs
Labels: priority: high, Changelog: None, Rust

#14527 Add sanity check for all crates to CI
  .github/workflows/rust-tests.yml
Labels: type: qa, Changelog: None, Rust

#14513 Avoid using rustworkx 0.16.0 methods in vf2_utils
  qiskit/transpiler/passes/layout/vf2_utils.py
Labels: stable backport potential, Changelog: None

#14426 Add methods to QubitSparsePauli, QubitSparsePauliList, and PauliLindbladMap
  Cargo.lock
  crates/quantum_info/Cargo.toml
  crates/quantum_info/src/pauli_lindblad_map/pauli_lindblad_map_class.rs
  crates/quantum_info/src/pauli_lindblad_map/qubit_sparse_pauli.rs
  test/python/quantum_info/test_pauli_lindblad_map.py
  test/python/quantum_info/test_qubit_sparse_pauli.py
Labels: mod: quantum info, mod: primitives

#14439 Annotation serialisation framework
  crates/circuit/src/annotation.rs
  crates/circuit/src/lib.rs
  docs/apidoc/circuit_annotation.rst
  docs/apidoc/index.rst
  qiskit/circuit/__init__.py
  qiskit/circuit/annotation.py
  qiskit/circuit/controlflow/box.py
  qiskit/circuit/quantumcircuit.py
  qiskit/dagcircuit/dagnode.py
  qiskit/providers/fake_provider/generic_backend_v2.py
  qiskit/qasm3/__init__.py
  qiskit/qasm3/ast.py
  qiskit/qasm3/exporter.py
  qiskit/qasm3/printer.py
  qiskit/qpy/__init__.py
  qiskit/qpy/binary_io/circuits.py
  qiskit/qpy/formats.py
  qiskit/qpy/interface.py
  qiskit/qpy/type_keys.py
  releasenotes/notes/annotation-frameworkd-d9f86b90720359b5.yaml
  releasenotes/notes/generic-backend-box-a8cc92670f6dcf63.yaml
  test/python/circuit/test_annotation.py
  test/python/compiler/test_transpiler.py
  test/python/providers/fake_provider/test_generic_backend_v2.py
  test/python/qasm3/test_export.py
  test/python/qasm3/test_import.py
  test/python/qpy/test_circuit_load_from_qpy.py
Labels: priority: high, Changelog: New Feature

#14535 Add support for Measure and Reset in Target's C API
  crates/cext/src/circuit.rs
  crates/cext/src/transpiler/target.rs
  crates/transpiler/src/target/mod.rs
  test/c/test_target.c
Labels: Changelog: None, C API

#14539 Fix behavior of HLS plugins after `preserve_order=False`
  qiskit/transpiler/passes/synthesis/hls_plugins.py
  releasenotes/notes/fix-preserve-order-0b8c1bf383f42297.yaml
  test/python/transpiler/test_high_level_synthesis.py
Labels: stable backport potential, Changelog: Bugfix

#13899 Support stretchy delays in `box`
  qiskit/circuit/controlflow/box.py
  qiskit/circuit/delay.py
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/stretchy-boxes-f031618cf17b4c09.yaml
  test/python/circuit/test_circuit_load_from_qpy.py
  test/python/circuit/test_control_flow.py
  test/python/circuit/test_control_flow_builders.py
  test/python/compiler/test_transpiler.py
  test/python/qasm3/test_export.py
Labels: Changelog: New Feature, mod: transpiler, mod: circuit

#14543 Deprecate Python 3.9 support
  qiskit/__init__.py
  releasenotes/notes/2.1/deprecate-3.9-b0c1d363a38cafbd.yaml
Labels: Changelog: Deprecation

#14546 Bump main branch version post 2.1.0rc1 tag
  .mergify.yml
  Cargo.lock
  Cargo.toml
  docs/conf.py
  qiskit/VERSION.txt
Labels: Changelog: None

#14549 Fix index.rst to have alphabetical order
  docs/apidoc/index.rst
Labels: documentation, Changelog: None

#14365 allows string values in assign_parameters with strict=False
  qiskit/circuit/quantumcircuit.py
  releasenotes/notes/fix-assign_parameters-string-input-with-strict-false-5597010d6d0c4a5f.yaml
  test/python/circuit/test_parameters.py
Labels: Changelog: Bugfix, mod: circuit

#14511 Deprecate Remaining Legacy Circuit Library Classes and Update References
  qiskit/circuit/library/arithmetic/exact_reciprocal.py
  qiskit/circuit/library/arithmetic/linear_amplitude_function.py
  qiskit/circuit/library/arithmetic/piecewise_polynomial_pauli_rotations.py
  qiskit/circuit/library/data_preparation/pauli_feature_map.py
  qiskit/circuit/library/phase_oracle.py
  qiskit/circuit/library/quantum_volume.py
  releasenotes/notes/deprecate-circuit-libraries-d39877bc0e962f05.yaml
  test/python/circuit/library/test_phase_and_bitflip_oracles.py
  test/python/circuit/library/test_quantum_volume.py
Labels: Community PR, mod: circuit

#14575 Adding BlockCollector classes to documentation
  qiskit/dagcircuit/__init__.py
  qiskit/dagcircuit/collect_blocks.py
Labels: documentation, Changelog: None

#14580 Fix conversion from ``std::complex`` to ``QkComplex64`` error on MSVC
  crates/cext/include/complex.h
Labels: stable backport potential, C API

#14557 Make Rust-space `VarsMode` strongly, not stringly, typed
  crates/circuit/src/dag_circuit.rs
  crates/transpiler/src/passes/basis_translator/mod.rs
  crates/transpiler/src/passes/disjoint_layout.rs
  crates/transpiler/src/passes/elide_permutations.rs
  crates/transpiler/src/passes/high_level_synthesis.rs
  crates/transpiler/src/passes/split_2q_unitaries.rs
  crates/transpiler/src/passes/unitary_synthesis.rs
Labels: Changelog: None, Rust

#14586 Fix random number generator seed argument for quantum_volume
  qiskit/circuit/library/quantum_volume.py
  releasenotes/notes/qv-rng-4bc9572d2df93671.yaml
  test/python/circuit/library/test_quantum_volume.py
Labels: stable backport potential, Changelog: Bugfix, mod: circuit

#14593 Fix ``code-block:: c`` with lowercase ``c`` for docs
  docs/cdoc/qk-target-entry.rst
  docs/cdoc/qk-target.rst
Labels: documentation, stable backport potential, Changelog: None

#14585 Raising an error when an invalid PauliEvolutionGate is constructed
  qiskit/circuit/library/pauli_evolution.py
  releasenotes/notes/evogate-error-on-bad-list-b0b2c64f541f9dbd.yaml
  test/python/circuit/library/test_evolution_gate.py
Labels: Changelog: Bugfix

#14597 Fix classical bit mapping in HLS pass
  crates/transpiler/src/passes/high_level_synthesis.rs
  releasenotes/notes/fix-hls-clbits-6ddf1f8d1542eed2.yaml
  test/python/transpiler/test_high_level_synthesis.py
Labels: stable backport potential, Changelog: Bugfix

#14626 Prepare 2.0.3 release
  Cargo.lock
  Cargo.toml
  docs/conf.py
  qiskit/VERSION.txt
  releasenotes/notes/fix-elide-permutation-gates-e4d2a718e1d50afa.yaml
  releasenotes/notes/fix-hls-clbits-6ddf1f8d1542eed2.yaml
  releasenotes/notes/fix-rustworkx-compatibility-8736854c63091cc4.yaml
  releasenotes/notes/prepare-2.0.3-cc268a6d04861eff.yaml
Labels: documentation, Changelog: None

#14563 Port QubitProperties to Rust and integrate with Target module (#14306)
  crates/transpiler/src/target/mod.rs
  crates/transpiler/src/target/qubit_properties.rs
  qiskit/providers/backend.py
Labels: Changelog: None, Rust, Intern PR, mod: transpiler

#14379 Explicitly specify that `Target` cannot be modified by indexing.
  qiskit/transpiler/target.py
Labels: documentation, stable backport potential, Changelog: None

#14491 Allow qubit/clbit newtypes to be `petgraph` index-like
  crates/circuit/src/nlayout.rs
Labels: Changelog: None, Rust

#14630 Add documentation examples on box annotations and stretches
  qiskit/circuit/__init__.py
  qiskit/circuit/annotation.py
  requirements-dev.txt
Labels: documentation, stable backport potential, Changelog: None

#14637 Target C API: Avoid re-using freed pointer.
  test/c/test_target.c
Labels: type: qa, stable backport potential, Changelog: None, C API

#14641 Fix sympify() for expressions with vector element .subs()
  qiskit/circuit/parameterexpression.py
  test/python/circuit/test_parameter_expression.py
Labels: priority: high, stable backport potential, Changelog: Bugfix

#14651 Add missing stacklevel to deprecation warning for 3.9
  qiskit/__init__.py
  releasenotes/notes/fix-deprecation-warning-e512acab95844e36.yaml
Labels: stable backport potential, Changelog: Bugfix

#14571 Added circuit start table to the QPY file header
  qiskit/qpy/__init__.py
  qiskit/qpy/common.py
  qiskit/qpy/formats.py
  qiskit/qpy/interface.py
  releasenotes/notes/qpy-circuit-start-table-ac5d23c239bc4c68.yaml
Labels: Intern PR

#14660 Use Arc instead of Box for internal expression nodes in SymbolExpr
  crates/circuit/src/parameter_expression.rs
  crates/circuit/src/symbol_expr.rs
  crates/circuit/src/symbol_parser.rs
  releasenotes/notes/fix-performance-of-large-expression-351afeb1a7ebf4d6.yaml
Labels: stable backport potential, performance, Changelog: Bugfix
